### ISSUE TITLE
PLUS SERVER CONNECTION FAILER

### ISSUE THREAD

**Issue by msepty** [PlusToolkit/PlusLib#1021]
Hi, 
I try many times with plusserver to launch ,but still with failed , the same file plus configueration used on other pc wotk correctily but on my pc with windows 10, not work.

i change the CaptureDeviceId="1" from one to zero , but still the same error ,

file is bellow :
```
<PlusConfiguration version="2.8">
  <DataCollection StartupDelaySec="1.0" >
    <DeviceSet
      Name="PlusServer: Optical marker tracker using MMF video"
      Description="Tracking of printed ArUco markers using a simple camera. Marker positions and image data are broadcasted through OpenIGTLink (on port 18944 and 18945, respectively). To use a different camera, change CaptureDeviceId attribute (to 0, 1, 2, ...)." />
    <Device
      Id="VideoDevice"
      Type="MmfVideo"
      FrameSize="640 480"
      VideoFormat="YUY2"
      CaptureDeviceId="1" >
      <DataSources>
        <DataSource Type="Video" Id="Video" PortUsImageOrientation="MF" ImageType="RGB_COLOR" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStream" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>
    <Device
      Id="TrackerDevice"
      Type="OpticalMarkerTracker"
      CameraCalibrationFile="OpticalMarkerTracker/camera_calibration.yml"
      ToolReferenceFrame="Tracker"
      TrackingMethod="OPTICAL"
      MarkerDictionary="ARUCO_MIP_36h12">
      <DataSources>
        <DataSource Type="Tool" Id="Marker0" MarkerId="0" MarkerSizeMm="80" />
        <DataSource Type="Tool" Id="Marker1" MarkerId="1" MarkerSizeMm="80" />
        <DataSource Type="Tool" Id="Marker2" MarkerId="2" MarkerSizeMm="50" />
        <DataSource Type="Tool" Id="Marker3" MarkerId="3" MarkerSizeMm="50" />
        <DataSource Type="Tool" Id="Marker4" MarkerId="4" MarkerSizeMm="50" />
        <DataSource Type="Tool" Id="Marker5" MarkerId="5" MarkerSizeMm="30" />
        <DataSource Type="Tool" Id="Marker6" MarkerId="6" MarkerSizeMm="30" />
        <DataSource Type="Tool" Id="Marker7" MarkerId="7" MarkerSizeMm="30" />
        <DataSource Type="Tool" Id="Marker8" MarkerId="8" MarkerSizeMm="30" />
      </DataSources>
      <InputChannels>
        <InputChannel Id="VideoStream"  />
      </InputChannels>
      <OutputChannels>
        <OutputChannel Id="TrackerStream" >
          <DataSource Id="Marker0"/>
          <DataSource Id="Marker1"/>
          <DataSource Id="Marker2"/>
          <DataSource Id="Marker3"/>
          <DataSource Id="Marker4"/>
          <DataSource Id="Marker5"/>
          <DataSource Id="Marker6"/>
          <DataSource Id="Marker7"/>
          <DataSource Id="Marker8"/>
        </OutputChannel>
      </OutputChannels>
    </Device>
    <Device
      Id="CaptureDevice"
      Type="VirtualCapture"
      BaseFilename="RecordingTest.igs.mha"
      EnableCapturingOnStart="FALSE" >
      <InputChannels>
        <InputChannel Id="TrackerStream" />
      </InputChannels>
    </Device>
  </DataCollection>
  
  <PlusOpenIGTLinkServer
    MaxNumberOfIgtlMessagesToSend="1"
    MaxTimeSpentWithProcessingMs="50"
    ListeningPort="18944"
    SendValidTransformsOnly="true"
    OutputChannelId="TrackerStream" >
    <DefaultClientInfo>
      <MessageTypes>
        <Message Type="TRANSFORM" />
      </MessageTypes>
      <TransformNames>
        <Transform Name="Marker0ToTracker" />
        <Transform Name="Marker1ToTracker" />
        <Transform Name="Marker2ToTracker" />
        <Transform Name="Marker3ToTracker" />
        <Transform Name="Marker4ToTracker" />
        <Transform Name="Marker5ToTracker" />
        <Transform Name="Marker6ToTracker" />
        <Transform Name="Marker7ToTracker" />
        <Transform Name="Marker8ToTracker" />
      </TransformNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>
  <PlusOpenIGTLinkServer 
    MaxNumberOfIgtlMessagesToSend="1" 
    MaxTimeSpentWithProcessingMs="50" 
    ListeningPort="18945" 
    SendValidTransformsOnly="true" 
    OutputChannelId="VideoStream" > 
    <DefaultClientInfo> 
      <MessageTypes> 
        <Message Type="IMAGE" />
      </MessageTypes>
      <ImageNames>
        <Image Name="Image" EmbeddedTransformToFrame="Image" />
      </ImageNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>
</PlusConfiguration>
```

error message from the log  : 

time|level|timeoffset|message|location
010170_000000.000|INFO|000.000000| System start timestamp: 358336| in ..\..\..\PlusLib\src\PlusCommon\vtkPlusAccurateTimer.cxx(53)
120522_134653.302|INFO|000.001000| Software version: Plus-2.3.0.4819 - Win64| in vtkPlusLogger(188)
120522_134653.302|INFO|000.001000| Logging at level 3 (INFO) to file: C:/Users/hp/PlusApp-2.3.0.4819-Win64/data/120522_134653_PlusLog.txt| in ..\..\..\PlusLib\src\PlusServer\Tools\PlusServer.cxx(85)
120522_134653.303|INFO|000.002000| Server status: Reading configuration.| in ..\..\..\PlusLib\src\PlusServer\Tools\PlusServer.cxx(113)
120522_134653.306|INFO|000.005000| Selected US image orientation: MF| in ..\..\..\PlusLib\src\PlusDataCollection\vtkPlusDataSource.cxx(302)
120522_134653.307|ERROR|000.006000| Unknown device type: OpticalMarkerTracker. Supported devices: 3dConnexion, AuroraTracker, ChRobotics, Epiphan, FakeTracker, GenericSerialDevice, ICCapturing, ImageProcessor, Microchip, MmfVideo, NoiseVideo, OpenIGTLinkTracker, OpenIGTLinkVideo, PhidgetSpatial, PolarisTracker, SavedDataSource, UsSimulator, VFWVideo, VirtualBufferedDiscCapture, VirtualDiscCapture, VirtualMixer, VirtualSwitcher, VirtualVolumeReconstructor| in ..\..\..\PlusLib\src\PlusDataCollection\vtkPlusDeviceFactory.cxx(380)
120522_134653.307|ERROR|000.006000| Unable to create device: OpticalMarkerTracker| in ..\..\..\PlusLib\src\PlusDataCollection\vtkPlusDataCollector.cxx(121)
120522_134653.307|ERROR|000.006000| Unknown device type: VirtualCapture. Supported devices: 3dConnexion, AuroraTracker, ChRobotics, Epiphan, FakeTracker, GenericSerialDevice, ICCapturing, ImageProcessor, Microchip, MmfVideo, NoiseVideo, OpenIGTLinkTracker, OpenIGTLinkVideo, PhidgetSpatial, PolarisTracker, SavedDataSource, UsSimulator, VFWVideo, VirtualBufferedDiscCapture, VirtualDiscCapture, VirtualMixer, VirtualSwitcher, VirtualVolumeReconstructor| in ..\..\..\PlusLib\src\PlusDataCollection\vtkPlusDeviceFactory.cxx(380)
120522_134653.307|ERROR|000.006000| Unable to create device: VirtualCapture| in ..\..\..\PlusLib\src\PlusDataCollection\vtkPlusDataCollector.cxx(121)
120522_134653.307|ERROR|000.006000| Device TrackerDevice does not exist.| in ..\..\..\PlusLib\src\PlusDataCollection\vtkPlusDataCollector.cxx(177)
120522_134653.307|ERROR|000.006000| Datacollector failed to read configuration| in ..\..\..\PlusLib\src\PlusServer\Tools\PlusServer.cxx(118)

**Comment by Sunderlandkyl** [comment]
The config file is failing because the VirtualCapture device does not exist for that version of Plus (2.3.0). It looks like it was originally named VirtualDiscCapture in that version.

Could you try using the latest stable version: http://perk-software.cs.queensu.ca/plus/packages/stable/ ?

**Comment by msepty** [comment]
Thanks , work correctily .
