### ISSUE TITLE
Plus server connection error

### ISSUE THREAD

**Issue by javan-del** [PlusToolkit/PlusLib#1024]
Hello @Sunderlandkyl,

I am using the Clarius app version 10 and tried to connect to the 3D Slicer using PlusApp-2.9.0.20221206-Clarius-Win64.exe. However, it didn't work and I got an error. I was wondering if the new PlusApp works with Clarius version 10.
Thank you in advance

**Comment by Sunderlandkyl** [comment]
Yes, I updated the Clarius Cast SDK in Plus today. It should be available in tomorrow's nightly build.

**Comment by javan-del** [comment]
Thank you very much.

**Comment by javan-del** [comment]
Thank you for the update. I tried to install the new version of Plus to use Clarius 10. Now there is another error. When I try to connect it shows an error.
"Could not connect to scanner at ip: 192.168.0.125 port number: 5828| in E:\D\PTNPCb\PlusLib\src\PlusDataCollection\Clarius\vtkPlusClarius.cxx(1237)

the port number and ip that I am using are correct but I get the error. would you please help me to solve this problem?

**Comment by javan-del** [comment]
Hello @Sunderlandkyl,

Thank you for the update. I tried to install the new version of Plus to use Clarius 10. Now there is another error. When I try to connect it shows an error.
"Could not connect to scanner at ip: 192.168.0.125 port number: 5828| in E:\D\PTNPCb\PlusLib\src\PlusDataCollection\Clarius\vtkPlusClarius.cxx(1237)

the Port number and IP that I am using are correct but I get the error. would you please help me to solve this problem?

**Comment by Sunderlandkyl** [comment]
Could you attach a log with log level trace?

**Comment by javan-del** [comment]
Yes, this is the log file.

[Test 001_001.txt](https://github.com/PlusToolkit/PlusLib/files/10198579/Test.001_001.txt)

**Comment by piwj** [comment]
Hi all, 

I'm having the same issue. Can connect over the Cast API in Python but not in PlusServer. My logfile seems to be the same as well.

Looks like the connection is going through, but is being held up on the IsConnected check:
https://github.com/PlusToolkit/PlusLib/blob/475313a7f6a9a2a521527bceeaa78dfe5d1b096d/src/PlusDataCollection/Clarius/vtkPlusClarius.cxx#L1235 


The ConnectReturnFn seems to flag a successful connection and the delay in the connect function seems to be sufficient based on the timestamps in the logfile:
https://github.com/PlusToolkit/PlusLib/blob/475313a7f6a9a2a521527bceeaa78dfe5d1b096d/src/PlusDataCollection/Clarius/vtkPlusClarius.cxx#L242

Not sure why these two might not be interacting as expected. 

I'm not too familiar with how PlusServer works with its internal/external class structure and how that might interact with the singleton. I unfortunately don't have enough time to dig deeper at the moment, but thought I would share my findings regardless in case it helps anyone.

**Comment by Sunderlandkyl** [comment]
Thanks, I'll look into the issue.

**Comment by javan-del** [comment]
Hello @Sunderlandkyl,

Thank you very much.
I was wondering if there is any update about this issue.

**Comment by Sunderlandkyl** [comment]
The latest Clarius Plus package should be fixed.

**Comment by javan-del** [comment]
Thank you very much.
