### ISSUE TITLE
I am having the same issue. I have gotten to the point where I can open aruco_calibration.exe and camera index 0 on the command prompt, but pressing a, c, or s does not seem to capture any images for calibration. How do I continue to make the simple webcam based tracking markers shown here https://www.youtube.com/watch?v=MOqh6wgOOYs&ab_channel=PerkLabResearch ?

### ISSUE THREAD

**Issue by cookedJohn** [PlusToolkit/PlusLib#1029]
I am having the same issue. I have gotten to the point where I can open aruco_calibration.exe and camera index 0 on the command prompt, but pressing a, c, or s does not seem to capture any images for calibration. How do I continue to make the simple webcam based tracking markers shown here https://www.youtube.com/watch?v=MOqh6wgOOYs&ab_channel=PerkLabResearch ?

_Originally posted by @cookedJohn in https://github.com/PlusToolkit/PlusLib/issues/408#issuecomment-1355775416_

**Comment by adamrankin** [comment]
You could try the aruco team, they might be able to help you with the calibration.

The webcam markers are just aruco markers printed out and glued to a backer.
