### ISSUE TITLE
Feature request: Support 3DConnexion devices on Linux

### ISSUE THREAD

**Issue by henrykrumb** [PlusToolkit/PlusLib#1031]
So far, 3Dconnexion devices (3D mice) are only supported on Windows systems. However, although the official drivers are not supported on Linux (or other Unix) systems, the spacenav project (https://spacenav.sourceforge.net) manages to emulate them.

I would suggest to conditionally include libspnav on Linux systems and to implement dedicated Linux support in src/PlusDataCollection/3dConnexionTracking.

**Comment by adamrankin** [comment]
@Sunderlandkyl Do you guys have the hardware and time to improve?

@henrykrumb If you have any ability to implement this it would be much appreciated, I do not currently have the hardware or time to implement this feature.

Someone please feel free to re-open if they can implement this.
