### ISSUE TITLE
fCal.exe doesn't work

### ISSUE THREAD

**Issue by javan-del** [PlusToolkit/PlusLib#1040]
Hello,

I installed PlusApp-2.9.0.20230126-Clarius-Win64 and I want to open fCal.exe. However, there is an error and I can not open the application. I was wondering if you could help to solve the issue. 
Thank you very much.

**Comment by Sunderlandkyl** [comment]
Should be fixed in the package build tomorrow.

**Comment by javan-del** [comment]
Thank you very much.
