### ISSUE TITLE
Configure Philips iU22 and NDI Polaris Vega

### ISSUE THREAD

**Issue by Renate-M** [PlusToolkit/PlusLib#1049]
Hii,

I am trying to configure a Philips iU22, my laptop and a NDI Polaris Vega (No Stylus). First I tried to configurate the NDI Polaris Vega and my laptop, I think this was successful. However, I also want to configurate the Philips iU22 in order to stream real time data to Slicer. This is not succeeded yet. In Plus they say: ‘Connection successful’, but when I try to see the results in Slicer, I see nothing. I do not see any transformations or images. 

Here the steps I have taken:
-	Make a config file
-	Load the config file in the Plus Server -> Successful connetion
-	Connect Slicer to Plus via the steps in your tutorials (OpenIGTLinkIF -> + -> Active)
        Problem: I do not see the IN nodes in the I/O Configuration
-	Try to show the images by selecting ‘Image_...’ in the Red slice
        Problem: I do not see something like ‘Image_...’, only ‘None’, ‘Rename current volume’, ‘Edit current volume’

I added my .xml file. Can you please help me with this?
[PlusDeviceSet_Server_Philips_1.txt](https://github.com/PlusToolkit/PlusLib/files/10674350/PlusDeviceSet_Server_Philips_1.txt)

To explain the config file I made. I used the issue ‘Connecting Philips iU22 and NDI Aurora tracker #333’ to make this. So I am not sure what is happening in the parts ‘fCal’ and ‘vtkPlusPivotCalibration’, but I just left it there. I changed the ServerPort and the ServerAddress and changed the Aurora tracker to the Vega tracker.

I tried different config files, this one eventually disconnected with Plus, I do not know why, but I added this one because I think I should look like this eventually. Another config file did not disconnected after a while, but has a stylus in it and I do not want to use this. (I still had the problems of not being able to see the results with this file).

(I read something about the fact that Philips devices do not allow everybody to stream real time images, is this playing a role here?)

Looking forward to hear from you!

With kind regards,
Renate

**Comment by ungi** [comment]
Hi Renate, if you are following that ticket from 2018, then you are also running the MeVisLab software, right? PLUS cannot connect to that ultrasound machine directly. If you are running MeVisLab, then you should be able to test it using 3D Slicer. Just open an OpenIGTLink client in 3D Slicer with the correct IP address (of where MeVisLab is running) and the same port number that is displayed in PLUS. You should see the ultrasound images in 3D Slicer.
If this test fails, you need to make sure MeVisLab is running correctly, but I'm not sure who develops that software.

**Comment by lassoan** [comment]
If streaming works via MeVisLab and connection succeeds in Plus then it should all work in Plus and Slicer!

Most likely there is just some trivial problem that prevents you from seeing the images in Slicer. Start with the simplest possible configuration file that only contains the Philips video source. Connect to that using PlusServer, connect to PlusServer in Slicer, and check if you receive an image in OpenIGTLinkIF module, then select that image in a slice view. We can have a quick call if you can set up a meeting with screen sharing (and preferably also remote control) on your laptop.

**Comment by adamrankin** [comment]
Re-open if you have any further questions on this issue.
