### ISSUE TITLE
Issue in "Show Plots" in temporal calibration

### ISSUE THREAD

**Issue by javan-del** [PlusToolkit/PlusLib#1051]
Thank you very much @Sunderlandkyl.
Now I can open the fCal.exe. However, when I want to do the temporal calibration and click on the "Show Plots" button the application crashes. Would you please help with this issue?
Thank you very much.

**Comment by Sunderlandkyl** [comment]
Sure, I'll take a look at it.

**Comment by Sunderlandkyl** [comment]
Should be fixed by https://github.com/PlusToolkit/PlusApp/commit/6475097f76dbeccd2415249f85906d825a910745.

**Comment by javan-del** [comment]
Thank you very much 
I was wondering if there is a way that I can edit the plots. For example, adding an axis label, adjusting the size of text, show two lines(calibrated and uncalibrated results) in one plot. 
and, if there is any way to save the data(FixedPositionMetric, uncalibratedMovingPositionMetric, 
  , CalibratedMovingPositionMetric) to use them and plot them separately?
I appreciate it if you can inform me in this regard.
