### ISSUE TITLE
Plus tutorial using no special hardware

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#106]
According to a former discussion with Tamas, it would significantly boost the currency of Plus, if we had a tutorial that can be done at home using no special hardware.

A possible approach is a MicronTracker-like home-made tracking system, consisting only of a webcam, and printed markers.

The biggest component we don't have is a (checkerboard) camera calibration algorithm, but there may be an open-source method we can integrate.

Migrated from https://app.assembla.com/spaces/plus/tickets/610/details

**Comment by Sunderlandkyl** [comment]
2012-10-02 11:37
Tamas Ungi
If one wants to do a webcam tracker, IGSTK should be checked. They probably use OpenCV or something like that.
Unfortunately the biggest advantage of PLUS (ultrasound) is not so easy to try at home.

2012-10-02 13:09
Tamas Heffter
Victor Grzeda used checker board calibration and webcam in his project, see: for http://perk.cs.queensu.ca/projects/carm-encoding

2012-10-02 13:14
Csaba Pinter
Thanks!

**Comment by adamrankin** [comment]
This can be done now. Slicer also has camera calibration methods.
