### ISSUE TITLE
Temporal calibration crashed when trying to show plot

### ISSUE THREAD

**Issue by QianqianCai** [PlusToolkit/PlusLib#1064]
PLUS version: PlusApp-2.9.0.20230201-Clarius-Win64
Operating system: Windows 10
config file: PlusDeviceSet_fCal_Sim_TemporalCalibration (from the config folder)

I was able to connect and start the temporal calibration. It crashed when I clicked on 'Show plot'. There is no error message.

**Comment by Sunderlandkyl** [comment]
Should already be fixed in the latest version. See: https://github.com/PlusToolkit/PlusLib/issues/1051.
