### ISSUE TITLE
Cannot connect magewell device to Plus

### ISSUE THREAD

**Issue by schcat** [PlusToolkit/PlusLib#1075]
Hello, everybody!
I want to connect a magewell video capture card(https://cn.magewell.com/products/pro-capture-sdi-4k-plus) to Plus, but i don't know what kind of device it is in the manual(http://perk-software.cs.queensu.ca/plus/doc/nightly/user/Configuration.html), and get poor information about how to write .xml file for magewell device.
It appear in my Ubuntu system as /dev/video0, and can show video stream with "mplayer tv:// -tv driver=v4l2:device=/dev/video0".
Who can give me some clue about how to write .xml file for magewell device?

**Comment by lassoan** [comment]
You can connect using generic video devices. On Linux you can use Video for Linux (V4L2Video) or OpenCV (OpenCVVideo).

**Comment by schcat** [comment]
> You can connect using generic video devices. On Linux you can use Video for Linux (V4L2Video) or OpenCV (OpenCVVideo).

Thanks a lot! I have tried OpenCVVideo and got "Connection failed", using this config file:

`<PlusConfiguration version="2.1">
  <DataCollection StartupDelaySec="1.0">
    <DeviceSet Name="PlusServer: OpenCV Video" 
               Description="Broadcasting acquired video through OpenIGTLink"/>
    <Device Id="VideoDevice"
            Type="OpenCVVideo"
            RequestedCaptureApi="CAP_V4L2"
                VideoURL="/dev/video0">
      <DataSources>
        <DataSource Type="Video" Id="Video" ImageType="RGB_COLOR" PortUsImageOrientation="MF"/>
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStream" VideoDataSourceId="Video"/>
      </OutputChannels>
    </Device>
  </DataCollection>
</PlusConfiguration>`

Any suggestion about how to revise it?

**Comment by adamrankin** [comment]
Can you see any error/info messages in the system log? (Dmesg I think?)

**Comment by schcat** [comment]
> Can you see any error/info messages in the system log? (Dmesg I think?)


I checked /var/log/dmesg and got these message, it seems that Pro Capture worked normally.
```
[   34.698374] kernel: ProCapture: module verification failed: signature and/or required key missing - tainting kernel
[   34.702589] kernel: Pro Capture 0000:02:00.0: enabling device (0000 -> 0002)
[   34.814897] kernel: input: HDA NVidia HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input9
[   34.815100] kernel: input: HDA NVidia HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input10
[   34.815274] kernel: input: HDA NVidia HDMI/DP,pcm=8 as /devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input11
[   34.815427] kernel: input: HDA NVidia HDMI/DP,pcm=9 as /devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input12
[   34.815608] kernel: input: HDA NVidia HDMI/DP,pcm=10 as /devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input13
[   34.815763] kernel: input: HDA NVidia HDMI/DP,pcm=11 as /devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input14
[   34.838311] kernel: snd_hda_codec_realtek hdaudioC0D0: autoconfig for ALC887-VD: line_outs=4 (0x14/0x15/0x16/0x17/0x0) type:line
[   34.838318] kernel: snd_hda_codec_realtek hdaudioC0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[   34.838321] kernel: snd_hda_codec_realtek hdaudioC0D0:    hp_outs=1 (0x1b/0x0/0x0/0x0/0x0)
[   34.838324] kernel: snd_hda_codec_realtek hdaudioC0D0:    mono: mono_out=0x0
[   34.838326] kernel: snd_hda_codec_realtek hdaudioC0D0:    dig-out=0x11/0x0
[   34.838328] kernel: snd_hda_codec_realtek hdaudioC0D0:    inputs:
[   34.838331] kernel: snd_hda_codec_realtek hdaudioC0D0:      Front Mic=0x19
[   34.838333] kernel: snd_hda_codec_realtek hdaudioC0D0:      Rear Mic=0x18
[   34.838335] kernel: snd_hda_codec_realtek hdaudioC0D0:      Line=0x1a
[   34.857630] kernel: input: HDA Intel PCH Front Mic as /devices/pci0000:00/0000:00:1f.3/sound/card0/input15
[   34.857688] kernel: input: HDA Intel PCH Rear Mic as /devices/pci0000:00/0000:00:1f.3/sound/card0/input16
[   34.857734] kernel: input: HDA Intel PCH Line as /devices/pci0000:00/0000:00:1f.3/sound/card0/input17
[   34.857779] kernel: input: HDA Intel PCH Line Out Front as /devices/pci0000:00/0000:00:1f.3/sound/card0/input18
[   34.857832] kernel: input: HDA Intel PCH Line Out Surround as /devices/pci0000:00/0000:00:1f.3/sound/card0/input19
[   34.857872] kernel: input: HDA Intel PCH Line Out CLFE as /devices/pci0000:00/0000:00:1f.3/sound/card0/input20
[   34.857914] kernel: input: HDA Intel PCH Line Out Side as /devices/pci0000:00/0000:00:1f.3/sound/card0/input21
[   34.857958] kernel: input: HDA Intel PCH Front Headphone as /devices/pci0000:00/0000:00:1f.3/sound/card0/input22
[   34.857997] kernel: input: HDA Intel PCH HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input23
[   34.858035] kernel: input: HDA Intel PCH HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input24
[   34.858075] kernel: input: HDA Intel PCH HDMI/DP,pcm=8 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input25
[   35.261692] kernel: Pro Capture: V4L2 device registered as video0
```

**Comment by schcat** [comment]
It worked as OpenCVWebCam!
There is a mistake that i forgot to turn the compile options of "V4L2" and "OpenCV_Video" to "on" in CMakeList.txt.
Thank you everyone!
