### ISSUE TITLE
Clarius_Plus connection

### ISSUE THREAD

**Issue by javan-del** [PlusToolkit/PlusLib#1078]
Hello,

I was wondering if PlusApp works with the new Clarius version 10. 2.3.

Thank you in advance

**Comment by Sunderlandkyl** [comment]
The Clarius cast version in the latest Plus is updated to 10.2.3. Are you having trouble connecting?

**Comment by javan-del** [comment]
I didn't update it yet. I wanted to know if it works then update the system. I will update it now.
Thank you very much.

**Comment by javan-del** [comment]
I update it and It is working.
Thank you very much.
