### ISSUE TITLE
PlusServer connection to NDI Polaris tracker with Data averaging activated fails

### ISSUE THREAD

**Issue by orubioDeneb** [PlusToolkit/PlusLib#1095]
Since Firmware version 008, NDI Polaris Vega trackers allow to configure averaged data output by dividing its tracking frequency by a factor.

When configuring the tracker with Data averaging factor 2 with tracking frequency 400Hz, and trying to connect with PlusServer, a bad CRC error message arrives to the log constantly when trying to start the server.

Changing tracking configuration file to 200Hz is also not working. It is probably trying to change the tracking frequency to 200Hz and then performing the data averaging at that frecuency, but couldn't trace this more at this time.

NDI Track app is correctly working with this setup, so it does not seem a configuration error. Using FW revision 010 at this moment but same error appeared with any other version tested since revision 008. Trying to force tracking output to 1/n factor in NDI Configuration App also did not work.

Could be related to pull request #1068 as capture and tracking frequency differ when this option is activated?

Thank you very much

**Comment by adamrankin** [comment]
New feature added to support NDI API 3.8+ for data averaging in #1126.

Please explore the discussion in #1115 for details
