### ISSUE TITLE
More descriptive config file parameter names needed

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#110]
Some parameter names in the config files are still not informative enough. E.g.
VolumeReconstruction/OutputSpacing -- this could be OutputSpacingPixelsPerMm.
VolumeReconstruction/ClipRectangleOrigin ans Size -- this is clear for people who are familiar with VTK: http://www.vtk.org/Wiki/VTK/Tutorials/Extents , but not clear to other people. Maybe if units were added, that would make it easier to understand.

In general, when a parameter gives a measure, units must be specified in the name. When the parameter gives a geometrical object (point, vector, rectangle), it would be nice to also specify the coordinate system where the object is defined.

Migrated from https://app.assembla.com/spaces/plus/tickets/901/details

**Comment by Sunderlandkyl** [comment]
2014-10-03 08:56
Andras Lasso
Full documentation of parameters are provided in the user manual, so that should help.

**Comment by adamrankin** [comment]
Can addres individual variable names as discovered.
