### ISSUE TITLE
Error connecting NDI 3D Guidance trakSTAR with PLUS Server

### ISSUE THREAD

**Issue by ThanasisCH01** [PlusToolkit/PlusLib#1101]
Hey, I am a new in PLUS and I want to connect NDI 3D Guidance trakSTAR with PLUS server but always the connection is unsuccesfull. I use the driver PLusApp-2.8.0.20191105-Telemed-Win32.exe and the original config file "PlusDeviceSet_Server_Ascension3DG.xml", but I get some errors. You can find both config and log file below. Any ideas would be helpful. Thank u! 
[PlusDeviceSet_Server_Ascension3DG.xml.txt](https://github.com/PlusToolkit/PlusLib/files/12181418/PlusDeviceSet_Server_Ascension3DG.xml.txt)
[log file.txt](https://github.com/PlusToolkit/PlusLib/files/12181423/log.file.txt)

**Comment by ungi** [comment]
Hi, I'm getting this error message when the tracker is not powered on, or a cable is not plugged in. Could you check if the tracker works with the software provided by NDI? I think one example application is called Cubes that comes with the device. If it doesn't work with the example applications, then there is a problem on the hardware side.

**Comment by adamrankin** [comment]
If you'd like to follow up on this issue, please re-open.
