### ISSUE TITLE
Azure Kinect Camera

### ISSUE THREAD

**Issue by Marw1** [PlusToolkit/PlusLib#1105]
Good day:

I am trying to use the Azure Kinect Camera with the Plus ToolKit, I used the XML example, I got error message said that Unknown device type: AzureKinect.
I used the Plus Clarius and Win64, same result,
May I got feedback for this issue and is there a solving for.

Thank you for your time and hope to hear from you soon.

**Comment by Sunderlandkyl** [comment]
I don't think any of the pre-compiled Plus packages include support for Azure.
You can find instructions on how to build Plus from scratch here: https://github.com/PlusToolkit/PlusBuild/blob/master/README.md.
