### ISSUE TITLE
Building Plus with stealth link

### ISSUE THREAD

**Issue by FaizanSiddiqui91** [PlusToolkit/PlusLib#1107]
Hi, I am trying to build PLUS with stealthLink enabled.  However, I am stuck in this loop. To build Plus with stealthLink, we need VS 10 or 13. However, qt5 needs VTK 9.0+, which needs VS 2015. 

Is there any workaround to build PLUS with stealthlink? 

Thanks a lot.

**Comment by Sunderlandkyl** [comment]
It should still be possible to build Plus with VTK 8.2.0, and a lower version of Qt. The nightly StealthLink package currently uses Qt 5.7.
