### ISSUE TITLE
check index

### ISSUE THREAD

**Issue by maddin200** [PlusToolkit/PlusLib#1153]
D:\Data\OpenSource\PlusLib-master\src\PlusDataCollection\NVidiaDVP\nvSDIout.cpp line 978

code:
 // Offset
  csc->colorOffset[0] = l_vioConfig.vioConfig.outConfig.colorConversion.colorOffset[0];
  csc->colorOffset[1] = l_vioConfig.vioConfig.outConfig.colorConversion.colorOffset[1];
  csc->colorOffset[1] = l_vioConfig.vioConfig.outConfig.colorConversion.colorOffset[2]; // <-- same index

**Comment by Sunderlandkyl** [comment]
This was already fixed in 16a085f229a9ee6a1e8966a83264163ec3f50220.
