### ISSUE TITLE
Broadcast OpenIGTLink over Usb NCM 

### ISSUE THREAD

**Issue by D49ll** [PlusToolkit/PlusLib#1158]
I've implemented a new OTS using PlusToolKit framework. I am currently facing a latency issue with the data being sent from PlusToolKit to when its received in my HMD.  

When connecting to the plustoolkit server on localhost there are little to no noticeable latency in the hologram projections. However when connecting over the WiFi the latency becomes very noticeable. The HMD has an option to transfer data over USB NCM. I would like to test if this could reduce my latency. The USB NCM hosts on IPv4 Address. . : 169.254.130.159 port 16. 

Is it difficult to add this to the list of OpenIGTLink servers listings ips? I have very little knowledge about this networking, i have no idea if the purposed solution is even feasible.

**Comment by adamrankin** [comment]
I think PlusServer binds to all available IPs, so if your USB device is acting as a network adapter, then it should bind to it. Does it not bind when you start a server with the device connected?
