### ISSUE TITLE
Fcal: Couldn't get tracked frame from video source

### ISSUE THREAD

**Issue by Cua57** [PlusToolkit/PlusLib#1182]
Hello,

I am doing the Temporal calibration using Fcal (PlusApp-2.9.0.20230330-Clarius-Win64).
The video is successfully streaming from Clarius v 10.2.3 and fcal is connected.
However, the video didn't display in fcal and this error showed up.

Please let me know if you have any ideas to fix it.
Thanks a lot!
![2024-04-08_16h46_18](https://github.com/PlusToolkit/PlusLib/assets/36097437/da97a22d-265c-48a8-8c5b-4a099d33b71b)

**Comment by jonortega77** [comment]
Any update here?

**Comment by Sunderlandkyl** [comment]
As found by @jonortega77 (https://github.com/PlusToolkit/PlusLib/issues/1205), the issue was the firewall.
