### ISSUE TITLE
Custom stl to ultrasound simulator

### ISSUE THREAD

**Issue by catarinalopes21** [PlusToolkit/PlusLib#1214]
### Discussed in https://github.com/PlusToolkit/PlusLib/discussions/1213

<div type='discussions-op-text'>

<sup>Originally posted by **catarinalopes21** November 14, 2024</sup>
I am trying to use a custom stl instead of the vessel from the example. Slicer manages to get me an ultrasound of the vessel but not of the custom stl. I made sure to switch the stl model from the PLUS file, to have the stl in RAS coordinates, to verify that there are no duplicates of any file and all files are correct. Here is what the Slicer, config file and folder look like:

![image](https://github.com/user-attachments/assets/0b2a8c04-fb4e-4057-b561-4e254a2a73c8)

![image](https://github.com/user-attachments/assets/5dcc4d46-dcbc-436a-87ea-2fa2dc048899)

![image](https://github.com/user-attachments/assets/74b87bac-927d-42a9-9e00-81564dc3f48b)

I have also tried changing parameters in PLUS and the image does change... it just does not detect the custom stl</div>

**Comment by lassoan** [comment]
For user support, please keep using the discussion. Thank you!
