### ISSUE TITLE
Add support for Capistrano Labs probes.

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#129]
Support for probes from:

http://www.capolabs.com/

Migrated from https://app.assembla.com/spaces/plus/tickets/1007/details

**Comment by Sunderlandkyl** [comment]
2015-06-23 14:00
Matt McCormick
These are single element, mechanically rocked probes. The drivers need to be obtained from Capistrano Labs, but they agreed that it is fine to write a PLUS interface for them.

2015-06-24 11:38
Matt McCormick
re #1007: Add FindCapistrano.cmake.
Committed to: plus
This allows CMake to locate the Capistrano SDK, obtainable from Capistrano Labs.
In plus:4201

2015-06-24 13:47
Matt McCormick
re #1007: Add PLUS_USE_CAPISTRANO_VIDEO option.
Committed to: plus
Enables support for Capistrano Labs USB probes.
In plus:4202

2015-06-24 13:50
Matt McCormick
re #1007: Fix the search location for USBprobe.dll.
Committed to: plus
In plus:4203

2015-06-24 16:12
Matt McCormick
re: #1007: Add PlusLib CMake configuration for Capistrano.
Committed to: plus
In plus:4204

2015-07-02 13:21
Matt McCormick
re: #1007 Add vtkCapistranoVideoSourceTest skeleton.
Committed to: plus
In plus:4208

2015-07-02 14:02
Matt McCormick
re: #1007 Capistrano read xml configuration file.
Committed to: plus
In plus:4209

2015-07-02 14:13
Matt McCormick
re: #1007 Capistrano NotifyConfigured().
Committed to: plus
In plus:4210

2015-07-02 15:54
Matt McCormick
re: #1007: Copy 32bit USBprobe.dll and implement GetSdkVersion.
Committed to: plus
In plus:4211

2015-07-02 16:40
Matt McCormick
re: #1007 Do not create a default device when using a config input file.
Committed to: plus
In plus:4212

2015-07-02 16:57
Matt McCormick
re: #1007 CapoLabs attach and detach callback.
Committed to: plus
These functions are commented out in the distributed header, although they are
documented in the distributed PDF. We do not really use them except for
logging. Disable for now.
In plus:4213

2015-07-02 17:17
Matt McCormick
re: #1007 Find the CapoLabs usb probe.
Committed to: plus
In plus:4214

2015-07-29 17:56
Matt McCormick
re: #1007 Some CapoLabs probe initialization.
Committed to: plus
In plus:4230

2015-07-29 18:04
Andras Lasso
Thanks for your contribution. Please add user documentation to PlusLib\src\Documentation\UserManual\Device....dox and add it to the index page at PlusApp\Documentation\DeviceList.dox.

2015-07-30 14:18
Matt McCormick
Thanks for the guidance :-). Starting the documentation in the recommended locations...

2015-07-30 14:22
Matt McCormick
re: #1007 Add DeviceCapistrano.dox.
Committed to: plus
Start of the user manual documentation for the Capistrano Labs USB ultrasound
probe.
In plus:4232

2015-07-30 14:23
Matt McCormick
re: #1007 Add link to DeviceCapistrano in documentation.
Committed to: plus
In plus:4233

2015-08-03 16:30
Matt McCormick
re: #1007 Detect the number of Capistrano probes attached.
Committed to: plus
In plus:4236

2015-08-03 16:37
Matt McCormick
re: #1007 Set the Capistrano probe sample clock divider.
Committed to: plus
In plus:4237

2015-08-04 16:47
Matt McCormick
re: #1007 Call bmInitializeDisplay in Capistrano.
Committed to: plus
Based off the PLUS setup for Interson.
In plus:4238

2015-08-11 14:46
Matt McCormick
re #1007: CapistranoVideoSource InitializeDIB.
Committed to: plus
Based of Interson version / Capistrano SDK.
In plus:4247

2015-09-17 16:15
Hyun Jae Kang
re #1007: Implement functionalities of Capistrano US Probe
Committed to: plus
In plus:4361

2015-09-17 16:36
Hyun Jae Kang
re #1007: Update vtkCapistranoVideoSourceTest.cxx and PlusDeviceSet_CapistranoVideoSourceTest.xml
Committed to: plus
In plus:4362

2016-01-08 09:29
Hyun Jae Kang
re #1007: Added vtkCapistranoVideoSource in the constructor to support the broadcasting of Capistrano Video stream with vtkPlusOpenIGTLinkServer.
Committed to: plus
In plus:4427

2016-01-08 09:30
Hyun Jae Kang
re #1007: Updated the default image's size and orientation.
Committed to: plus
In plus:4428

**Comment by jamesobutler** [comment]
This is an old issue that was ported from Assembla and can be closed.

vtkPlusCapistranoVideoSource has been present in PlusLib for awhile now.
