### ISSUE TITLE
Enable rotation of Epiphan stream

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#148]
As per discussion from [this message](https://app.assembla.com/spaces/plus/messages/5677283), rotation of the incoming Epiphan stream is desired.

Migrated from https://app.assembla.com/spaces/plus/tickets/1116/details

**Comment by Sunderlandkyl** [comment]
2016-10-15 18:42
Adam Rankin
re #1116 Adding interface targets to PlusLib for convenient access to interface library headers
Committed to: plus
In plus:4910

2016-10-15 19:24
Adam Rankin
test #1116 Adding rotation and scaling parametsrs to the Epiphan capture device
Committed to: plus
In plus:4911

2016-10-15 19:35
Adam Rankin
re #1116 Cleaned up header file, removed useless if statement
Committed to: plus
In plus:4912

**Comment by adamrankin** [comment]
Not sure where/when, but this has been implemented.
