### ISSUE TITLE
Update the BK scanner interface

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#154]
- Make PlusServer compile with BK scanner interface
- Get doppler video, allow streaming of color video to make this work
- Get ultrasound sector information from the scanner
- Send ultrasound sector information with OpenIGTLinkIO

I have forked PlusLib on https://github.com/SINTEFMedtek/PlusLib

Migrated from https://app.assembla.com/spaces/plus/tickets/1149/details

**Comment by Sunderlandkyl** [comment]
2017-01-27 10:24
Adam Rankin
Hi Ole!

When did you fork the pluslib repo? The reason I ask is I had to destroy and recreate it to proprely import the branches.

If you did it a while ago, you'll have to re-clone the repo, and copy over the files (excluding .git folder) from the old clone to the new clone.

Apologies!

2017-01-27 10:25
Adam Rankin
I see it was 4 hours ago, that should be fine!

2017-05-12 06:27
Ole Vegard Solberg
@rankin and @lassoan : I'm considering replacing Grabbielib with an interface using Qt to simplify the code and make it multi platform. Is it ok to use Qt5:Network library instead of Grabbielib?

2017-05-12 07:40
Andras Lasso
PlusLib does not use Qt (other than having some common widgets defined there for convenience, but that's an optional component), so this would not be feasible. Several users not use Qt at all, so we should not add this dependency to any device. You should be able to use VTK or OpenIGTLink OS-independent socket classes.

2017-05-12 08:37
Andras Lasso
I fully agree with replacing GrabbieLib, as it is overcomplicated (it seemed, it was intended to do much more, but probably they did not have enough time) and really messy.

2017-05-12 08:58
Ole Vegard Solberg
Ok, I will probably use OpenIGTLink classes instead then.

2017-05-12 09:03
Andras Lasso
OK. I think OpenIGTLink sockets have been extracted from VTK a couple of years ago, and Device classes already depend on VTK (but not on OpenIGTLink) so it might be easier to use vtkSocket classes, but it's up to you.

2017-05-24 05:26
Ole Vegard Solberg
I ended up using vtkClientSocket, and my version of the BK interface now runs on OSX. However, it don't work on my Windows build: It seems VTK fails in creating sockets (vtkSocket.cxx line 145).

2017-05-24 08:48
Andras Lasso
Is the code available on your fork? I could test it on my computer, too.

2017-05-25 03:25
Ole Vegard Solberg
Yes everything is pushed to my fork. I'm working on the branch: us-sector-info.
You don't need any scanner to test this particular bug, as it fails when asking for a socket.
Just comment out #define OFFLINE_TESTING at the top of vtkPlusBkProFocusOemVideoSource.cxx.
You have to set ScannerAddress and OemPort in PlusDeviceSet_Server_BkProFocusOem.xml, as I don't use the IniFile.ini file:
~~~~
<Device
Id="VideoDevice"
Type="BkProFocusOem"
ScannerAddress="10.1.1.100"
OemPort="7915"
ContinuousStreamingEnabled="true"
ColorEnabled="true"
AcquisitionRate="20" >
...
</Device>
~~~~

**Comment by lassoan** [comment]
Integrated new BK OEM interface (#75).
