### ISSUE TITLE
Review of existing marker tracking toolkits

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#155]
It has to be BSD-like, mono optical, preferred: use surface scan data.

Interfacing OpenCV or ArUco for tracking:

ArUco: http://www.uco.es/investiga/grupos/ava/node/26
http://docs.opencv.org/3.1.0/d5/dae/tutorial_aruco_detection.html

ARMA: https://sites.google.com/site/georgeevangelidis/arma - license only for academic use
ARToolkit+: obsolete, replaced by stbtracker
Stbtracker: http://studierstube.icg.tugraz.at/handheld_ar/stbtracker.php - not open source!
Vuforia: http://www.ptc.com/news/2016/ptc-brings-vuforia-to-hololens - commercial
Wikitude 3D: supports hololens
ARMedia: www.inglobetechnologies.com - commercial
Princeton: http://tracking.cs.princeton.edu/code.html
Kudan: https://www.kudan.eu/kudan-news/comparison-kudan-vuforia/ - commercial
CurvSurf: http://www.curvsurf.com/ - commercial

ORBSLAM2: https://github.com/raulmur/ORB_SLAM2, markerless tracking using RGBD camera, actively developed - GPLv3

Migrated from https://app.assembla.com/spaces/plus/tickets/1186/details

**Comment by markasselin** [comment]
@Sunderlandkyl we can probably close this ticket since OpticalMarkerTracker has been implemented
