### ISSUE TITLE
Add support for OptiTrack hardware

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#158]
Adding support for OptiTrack V120:Duo and Prime 17W cameras.

Migrated from https://app.assembla.com/spaces/plus/tickets/1208/details

**Comment by Sunderlandkyl** [comment]
2017-07-12 10:55
Mark Asselin
re #1208: Updated config to work with NatNet SDK based OptiTrack device.
Committed to: plus
In plus:5107

2017-07-12 12:15
Andras Lasso
re #1208: Replaced legacy OptiTrack device (used retired TrackingTools) with one using NatNet SDK.

Branch: master
Commit: plus:0e0e4fc696

2017-07-12 12:15
Andras Lasso
Re #1208: Adding basic tracking functionality

Branch: master
Commit: plus:a7eca31ff8

2017-07-12 12:15
Andras Lasso
re #1208: Added OptiTrack documentation

Branch: master
Commit: plus:047909e580

2017-07-12 12:23
Andras Lasso
re #1208: Replaced legacy OptiTrack device (used retired TrackingTools SDK) with one using NatNet SDK.

Branch: master
Commit: plus.3:b4450588e4

2017-07-12 12:23
Andras Lasso
re #1208: Update FindOptiTrackSDK variable description

Branch: master
Commit: plus.3:3c120fd992

2017-07-12 13:19
Andras Lasso
re #1208: Added path hint to find NatNed SDK in PLTools

Branch: master
Commit: plus.3:a785ac95ab

**Comment by lassoan** [comment]
Remaining tasks are tracked in #170
