### ISSUE TITLE
Add device that uses ArUco marker tracking library

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#159]
- Use latest official git
- Upload our hack to https://github.com/PlusToolkit/ArUco
- Send a pull request to official version on SourceForge, see what happens (they merge as is, ignore, implement a nice solution instead, ...)
- Add aruco build to PlusBuild
- Add device vtkPlusOpticalMarkerTracker that uses ArUco library

Migrated from https://app.assembla.com/spaces/plus/tickets/1196/details

**Comment by Sunderlandkyl** [comment]
2017-05-15 12:42
Andras Lasso
Use vtkPlusIntelRealSenseTracker as an example (clone and modify). vtkPlusImageProcessorVideoSource is an example how to use another device's output as input.

2017-05-15 14:34
Adam Rankin
Let me know if I can help. I'd like this.

ArUco is in the SVN/git history (not sure which one).

What's your hack?

2017-05-15 16:03
Andras Lasso
The problem is that .lib and .dll filenames are hardcoded in the official repository, but the actual filenames are different on Linux/Windows. Our hack is to add an if(WIN32)..else()..endif() and hardcode different filenames for Windows and other platforms. I would not spend time with improving the ArUco build system unless there is a high chance that the maintainers would accept those. As a first step, we submit this simple (and ugly solution) and see how they deal with it.

2017-06-06 20:17
Andras Lasso
re #1196: Functional translational and rotational tracking for multiple markers.

Branch: master
Commit: plus:4619c808cc

2017-06-06 20:17
Andras Lasso
re #1196: Initial commit to create OpticalMarkerTracker device.

Branch: master
Commit: plus:88d5386d3b

2017-06-12 17:39
Mark Asselin
re #1196: Added example configuration for OpticalMarkerTracker &amp; associated files
Committed to: plus
In plus:5093

2017-06-13 14:00
Mark Asselin
re #1196: More descriptive DeviceSet name
Committed to: plus
In plus:5094

2017-06-14 11:32
Mark Asselin
re #1196: Renamed OpticalMarkerTracker tracking types to OPTICAL &amp; OPTICAL_AND_DEPTH
Committed to: plus
In plus:5095

2017-06-16 08:39
Andras Lasso
re #1196: Added warning for non-standard meter units in calibration

Branch: master
Commit: plus:668e5186d2

2017-06-16 08:39
Andras Lasso
re #1196: Added Doxygen documentation for OpticalMarkerTracker

Branch: master
Commit: plus:7e3b578bac

2017-06-16 08:39
Andras Lasso
re #1196: Rename tracking types to OPTICAL or OPTICAL_AND_DEPTH

Branch: master
Commit: plus:8a674b0873

2017-06-16 08:39
Andras Lasso
re #1196: Added aruco util executables to release

Branch: master
Commit: plus.2:934ad9f0b7

2017-06-16 08:39
Andras Lasso
re #1196: Added documentation for OpticalMarkerTracker & associated files

Branch: master
Commit: plus.2:cf4d1933ef

2017-06-16 13:46
Andras Lasso
re #1196: Fixed interference between multiple markers

Branch: master
Commit: plus:0ca8288c0e

2017-06-18 17:48
Mark Asselin
re #1196: Added premade marker sheet and updated config to use those markers
Committed to: plus
In plus:5098

2017-06-19 10:09
Andras Lasso
re #1196: Improved PlusDeviceSet_Server_OpticalMarkerTracker_Mmf.xml
Committed to: plus
CaptureDeviceId="0" to make the example work on systems where there is only a single camera.
In plus:5099

2017-06-19 10:10
Andras Lasso
re #1196: Improved OpticalMarkerTracker device documentation

Branch: master
Commit: plus:944e49830e

2017-06-19 12:01
Andras Lasso
Works very nicely!

At some point, log messages should be cleaned up. For example, it should not be logged as an error if a marker cannot be found.

2017-06-20 17:49
Andras Lasso
re #1196: Improved frame throughput using PixelCodec

Branch: master
Commit: plus:6937db207b

2017-06-20 17:49
Andras Lasso
re #1196: Added examples and marker sheet to dox documentation, removed bgr swap

Branch: master
Commit: plus:5896fa6486

2017-06-28 07:12
Andras Lasso
re #1196: Added example 3S Slicer scene that shows all markers on marker sheet
Committed to: plus
In plus:5102

2017-06-28 07:19
Andras Lasso
re #1196: Moved example 3D Slicer scene to OpticalMarkerTracker directory
Committed to: plus
In plus:5103

2017-06-29 10:14
Adam Rankin
I feel like the CMake for the aruco device could be more smoothly handled. Would you consider changing the CMake to auto-select dependent options instead of reporting they aren't selected?

For example, if the user selects PLUSBUILD_USE_aruco, then .._USE_OpenCV should auto-self-select
Same with OPTICAL_MARKER -> aruco -> OpenCV

Thoughts?

2017-06-29 10:14
Adam Rankin
(This would happen during the first configure after the user selected an option)

2017-06-30 20:49
Andras Lasso
I would be hesitant to automate this, just because very smart people tried to automate this for example in CTK and in Plastimatch build systems, and in both cases the result is a catastrophy. While I agree that a few mouse clicks could be saved by automating the process, developers would lose control and they would often need to resort to trial and error when they configure their project to figure out what they can and they can not do. For example, if you don't want to use a specific dependency then it is really difficult to configure your project if there is an automatic dependency enabling mechanism.

2017-07-13 11:44
Adam Rankin
re #1196 #1204 Cleaning up PlusBuild CMake to dynamically detect missing dependencies and enable them.

Branch: master
Commit: plus.3:f5ec8ad52f

2017-07-13 12:04
Adam Rankin
re #1196 #1204 Cleaning up PlusBuild CMake to dynamically detect missing dependencies and enable them.

Branch: master
Commit: plus.3:90d28fb35c

**Comment by lassoan** [comment]
@Sunderlandkyl Please test if you can set up marker tracking with your webcam based on documentation in user manual and the most recent nightly Plus package.

**Comment by markasselin** [comment]
@Sunderlandkyl Please let me know if there is anything unclear in the docs - I will update them promptly!

**Comment by Sunderlandkyl** [comment]
@markasselin The first thing that I've found is that the files that were hosted on Assembla are no longer accessible from the docs. (I guess the Assembla repo was shut down today)

**Comment by markasselin** [comment]
@sunderlandkyl Where is a good place on the new Perk github repos for me to move these to?

**Comment by Sunderlandkyl** [comment]
@markasselin Maybe [PlusDoc](https://github.com/PlusToolkit/PlusDoc)? We should probably check with Andras. @lassoan

**Comment by Sunderlandkyl** [comment]
@markasselin Actually, I think that most of the files are already located in https://github.com/PlusToolkit/PlusLibData/tree/master/ConfigFiles/OpticalMarkerTracker

**Comment by lassoan** [comment]
If there is no reason to do otherwise, the marker and config files should be in PlusLibData repository.

**Comment by Sunderlandkyl** [comment]
Double checked with the updated config file and the latest nightly.
Works good!
