### ISSUE TITLE
32->64 volume reconstruction is empty in Slicer

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#161]
With example setup (saved data)

PlusDeviceSet_Server_Sim_NwirePhantomTrackedFrameProcessing.xml
PlusDeviceSet_Server_Sim_NwirePhantomTrackedFrameAcquisition.xml

scout scan produces data, live volume reconstruction does not

Migrated from https://app.assembla.com/spaces/plus/tickets/1225/details

**Comment by Sunderlandkyl** [comment]
2017-08-18 15:34
ppandey
What are the results with offline reconstruction on saved data?

2017-08-21 12:32
ppandey
Origin (placement) of reconstructed volume is incorrect and physical dimensions of the reconstruction seems to be incorrectly dependant on the output spacing parameter when testing offline reconstruction.

**Comment by ssamira** [comment]
Hello, 

I have the same problem. The live volume reconstruction is empty in our case too. 
Following the ticket.

**Comment by Sunderlandkyl** [comment]
@lassoan I'm having trouble reproducing this. Would you mind giving me a hand?

**Comment by adamrankin** [comment]
If you're willing to work on this, this is definitely a use case that could use an automated test.

**Comment by Sunderlandkyl** [comment]
Sure, that sounds like a good idea.

**Comment by Sunderlandkyl** [comment]
@ssamira I wasn't able to replicate this issue on the latest nightly build of slicer and plus, using a 32-bit build of plus for the acquisition server, and a 64-bit build for the processing server.

Can you provide more information on what versions of Slicer and Plus you were using, as well as the exact setup?

**Comment by ssamira** [comment]
@Sunderlandkyl, this is what I am doing:
I am running the latest version of PLUS (2.4.0.5123-Ultrasonix-57-Win32) on a sonix touch machine. 
On the other machine, I run Slicer. I set up an OpenIGTLink and use the OpenIGTLinkRemote to StartVolumeReconstruction and GetVolumeReconstructionSnapshot using below commands:
<Command Name="StartVolumeReconstruction" VolumeReconstructorDeviceId="VolumeReconstructorDevice" />
<Command Name="GetVolumeReconstructionSnapshot" VolumeReconstructorDeviceId="VolumeReconstructorDevice" OutputVolDeviceName="recvol_Reference" />
I don't receive any error and all messages on the Plus side seems to be correct but the volume in the Slicer is empty. 
I also attached my config file to this.

[C52_Calibration_7cm_Freq3.3_00304_T.zip](https://github.com/PlusToolkit/PlusLib/files/1342656/C52_Calibration_7cm_Freq3.3_00304_T.zip)

**Comment by lassoan** [comment]
Please try the latest development snapshot and let us know if it works.

**Comment by ssamira** [comment]
Sure @lassoan, will let you know.

**Comment by prash-p** [comment]
This works for me now, I tested offline reconstruction, scout scanning and live reconstruction

**Comment by prash-p** [comment]
This issue needs to be reopened - I'm having scaling issues again on the latest development snapshots.

Using an acquisition and processing server to do higher resolution volume reconstruction, but I'm noticing that on the scout scan and live reconstruction functions the output volume has the wrong size (physically speaking) compared to the input image, and that this size changes with the output spacing parameter.
