### ISSUE TITLE
fCal records frames at 10fps, but device is running at 27fps

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#164]
Ultrasonix, 9cm, 27Hz reported on console

Migrated from https://app.assembla.com/spaces/plus/tickets/1226/details

**Comment by Sunderlandkyl** [comment]
2017-08-26 11:11
Adam Rankin
re #1226 applying astyle formatting to SonixVideo/vtkPlusSonixVideoSource.cxx

Branch: master
Commit: plus:a5676e21ed

2017-08-26 12:34
Adam Rankin
Assigned to changed from Adam Rankin to -none-

2017-08-28 12:36
Adam Rankin
https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusDataCollection/SonixVideo/vtkPlusSonixVideoSource.cxx#L136

This function is being called at the update rate indicated on the Ultrasonix console. This leads me to believe that the problem is somewhere in Plus.

**Comment by lassoan** [comment]
Most likely it is not a regression, so we will not address in the upcoming stable release

**Comment by adamrankin** [comment]
Device was indeed running at 10fps, but ultrasonix console was misrepresenting actual update rate.
