### ISSUE TITLE
Add automatic tests for OpenIGTLink tracker with TDATA input

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#166]
To make sure Plus works correctly with BrainLab. The BrainLabTrackerSim tool can be used as the server.

Migrated from https://app.assembla.com/spaces/plus/tickets/839/details

**Comment by Sunderlandkyl** [comment]
2017-08-18 14:54
Adam Rankin
re #839 Adding config files for TDATA test
Committed to: plus
In plus:5118

2017-08-18 14:55
Adam Rankin
test #839 openigtlink tracker device not properly requested tdata tracking start due to incorrect order of client info and starttdata messages

test added for tdata tracking

transformName parsing added to determine if a brainlab or a plus style transform name was sent in igt message

Branch: tdata_device_cleanup
Commit: plus:8a01d4111d

2017-08-29 12:15
Adam Rankin
test #839 openigtlink tracker device not properly requested tdata tracking start due to incorrect order of client info and starttdata messages (#71)

test added for tdata tracking

transformName parsing added to determine if a brainlab or a plus style transform name was sent in igt message

Branch: master
Commit: plus:86b01e0765

**Comment by adamrankin** [comment]
This has been completed.
