### ISSUE TITLE
Support for NDI Polaris broken in Plus-2.5

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#167]
(No description)

Migrated from https://app.assembla.com/spaces/plus/tickets/1221/details

**Comment by Sunderlandkyl** [comment]
2017-08-09 10:28
Adam Rankin
Can you be more specific? Which device? Which firmware?

2017-08-09 10:28
Adam Rankin
And are you sure you're on the latest ndicapi?

2017-08-09 10:29
Mark Asselin
@rankin I tried connecting to our Polaris Spectra using the latest nightly again this morning, both with and without specifying the COM port # in my config file. To no avail. I can connect to the tracker using NDITrack and the stable release of Plus using the same config file. The firmware revision is 015.

[Plus-2.5-ComNotSpecified.txt](https://bigfiles.assembla.com/spaces/plus/documents/download/d3FkocFq4r54S6acwqjQYw)
[Plus-2.5-ComSpecified.txt](https://bigfiles.assembla.com/spaces/plus/documents/download/d3Hv0gFq4r54owdmr6QqzO)
[PlusDeviceSet_Server_NDIPolaris.xml](https://bigfiles.assembla.com/spaces/plus/documents/download/d7AsdeFq4r56Rddmr6bg7m)

2017-08-09 10:30
Adam Rankin
built or installed plus?

2017-08-09 10:30
Mark Asselin
Installed from latest nightly. Is there more up to date code not in the nightly packages yet?

2017-08-09 10:31
Adam Rankin
I'll head in to work and test on our spectra. Give me 15 minutes

2017-08-09 10:32
Mark Asselin
Sure.

2017-08-09 11:01
Adam Rankin
Confirmed, fix on the way.

2017-08-09 11:01
Mark Asselin
Great, thanks!

2017-08-09 11:02
Adam Rankin
Hmm, I'll see if I can re-run the packaging

2017-08-09 11:03
Adam Rankin
Ah, firewalled. Either wait until tomorrow, build your own Plus, or see if @lassoan can re-run packaging.

2017-08-09 11:03
Adam Rankin
Assigned to changed from Adam Rankin to Mark Asselin
Status changed from New to Test

2017-08-09 11:04
Mark Asselin
I'm working on a few time critical things today, so I will test this tomorrow morning using the latest nightly.

2017-08-28 18:56
Adam Rankin
re #1221 adding support for 230400 baud rate for NDI aurora devices

Branch: master
Commit: plus:1fcb98da56

2017-08-29 13:43
Adam Rankin
re #1221 auto-selecting fastest available baud rate based on comm reply analysis

fixing openigtlink tracker test

Branch: master
Commit: plus:76b9a61580

**Comment by lassoan** [comment]
There have been no issues reported recently, so probably it works well now.
