### ISSUE TITLE
Create PLUS device to enhance spinal ultrasound images and detect bone surfaces

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#172]
(No description)

Migrated from https://app.assembla.com/spaces/plus/tickets/1108/details

**Comment by Sunderlandkyl** [comment]
2016-08-23 09:58
Ben Church
re #1108 Added vtkPlusTransverseProcessEnhancer device which currently just performs a vtkImageGaussianSmooth on the input ultrasound image. Added config file for this device and modified vtkP
Committed to: plus
In plus:4823

2016-08-25 12:48
Ben Church
re #1108: Added threshold operation to image processing pipeline. Image processor now reads more parameters from config file, making experimentation faster.
Committed to: plus
In plus:4831

2016-08-26 16:40
Adam Rankin
re #1108 Updating code to adhere to coding conventions. Fixing bugs relating to NULL checks. Implementing complete WriteConfiguration function.
Committed to: plus
Updating last of the PlusCommon::Trim usages
In plus:4834

2016-09-08 14:41
Ben Church
re #1108: Implemented Sobel edge detection plus a function to extract and combine its two-component output. I will next investigate pre-existing filters for component combination, island remov
Committed to: plus
In plus:4848

2016-09-09 12:29
Adam Rankin
re #1108 Reducing Mac build warnings
Committed to: plus
Updating code to adhere to coding conventions

Updating WriteConfiguration to output all stored values

Updating config file name to match convention
In plus:4850

2016-09-09 12:32
Adam Rankin
re #1108 Fixing linux build error
Committed to: plus
In plus:4851

2016-09-14 13:51
Ben Church
re #1108: Implemented another thresholder to binarize image so that vtkIslandRemoval2D works.
Committed to: plus
In plus:4867

2016-09-14 14:12
Ben Church
re #1108: Reverted since my last commit (or some attempt at conflict resolution) deleted NVidiaDVP files.
Committed to: plus
In plus:4868

2016-09-14 14:24
Ben Church
re #1108: Second commit attempt - Implemented another thresholder to binarize image so that vtkIslandRemoval2D works.
Committed to: plus
In plus:4869

2016-09-14 15:10
Ben Church
re #1108: Implemented "ImageConjunction" to retrieve pixel values from before image was binarized.
Committed to: plus
In plus:4870

2016-09-21 21:24
Ben Church
re #1108: Implemented image erosion and dilation as separate processes
Committed to: plus
In plus:4886

2016-10-05 16:13
Adam Rankin
re #1108 linux and mac build warning fixes
Committed to: plus
In plus:4890

2016-10-06 07:03
Andras Lasso
re #1108: Fixed build errors
Committed to: plus
In plus:4892

2017-05-19 14:12
Csaba Pinter
Assigned to changed from Ben Church to Bryan Travers

2017-05-31 10:44
Andras Lasso
re #1108: Added option to EditSequenceFile to mix multiple sequence files

Mixing means that the multiple sequences are merged into one.
Timestamps, video, and all fields are taken from the first sequence and all other fields are copied from other sequences.
No interpolation is performed: fields from the frame that has the closest timestamp will be used.

Branch: master
Commit: plus:6fc41a9fa8

2017-05-31 11:09
Andras Lasso
re #1108: Fixed EditSequenceFile mix test

Branch: master
Commit: plus:d8a0d7dea9

2017-09-06 19:46
Adam Rankin
Scoliosis transverse process enhancer (#72)

re #1108 added basic input, output, and image processing functionality to vtkPlusTransverseProcessEnhancerTest
Modified existing program vtkPlusTransverseProcessEnhancerTest so that it may better test and get outputs from vtkPlusTransverseProcessEnhancer.
command line arguments may be in the following format:
vtkPlusTransverseProcessEnhancerTest.exe --output-config-file=ConfigFile.xml --input-seq-file=BoneUltrasound_L14.mha --output-seq-file=BoneUltrasound_L14_OUT_TEST.mha

Larger additions to vtkPlusTransverseProcessEnhancerTest include:
-more descriptive error messages.
-support for output as a shadow image file, a lines image file, and processed lines image file.

Also changed vtkPlusTransverseProcessEnhancer.cxx so that it better reads and writes information in config files, as a result of this, vtkPlusTransverseProcessEnhancer.h also had to be modified.
vtkPlusTransverseProcessEnhancer.h was not changed in any other way.

re #1108 Added ways to get various outputs, including various intermediate output images, and an output config file for recording what inputs were used
Added an optional argument to vtkPlusTransverseProcessEnhancerTest to allow for testing vtkPlusTransverseProcessEnhancer's WriteConfiguration() method. Using this argument will cause a config file to be created. This new config file will be filled with the settings that are being used during the current run of the test program. This new config file is intended to be identical to the inputted config file.

Added or expanded on optional arguments for various intermediate outputs, such as:
--output-lines-image-file
--output-intermediate-image-file
--output-shadow-image-file
--output-processedlines-image-file

Rewrote vtkPlusTransverseProcessEnhancer.cxx's WriteConfiguration() using XML_WRITE macros
Added error checking to alternate output files in vtkPlusTransverseProcessEnhancer.cxx

vtkPlusTransverseProcessEnhancer.h was changed to allow for the changes mentioned above.

re #1108 Added support for intermediate images to be saved throughout different points in the code.

Removed some command line arguments from vtkPlusTransverseProcessEnhancerTest and added the bool argument: --save-intermediate-images which makes the program save various intermediate images before and after steps of the filters. These intermediate images are saved in the same location as where the output file goes, and their file name is: output image file name + _ + an incrementing index + special postfix + .mha ex: BoneUltrasound_L14_TEST_2Lines.mha

In code, the intermediate images are being stored in a dictionary where _ + an incrementing index + special postfix is the key

re #1108 Finalized ability to save intermediate images in vtkPlusTransverseProcessEnhancer
Ability to save intermediate images while running vtkPlusTransverseProcessEnhancerTest.cxx hes been presumably finished.
Intermediate images are now saved to the local Output folder in a directory named IntermediateImageFiles, then in a sub-directory based on the file's postfex

The programs used to save intermediate images in variables, this has been changed so that it saves them in a map. The reason for this was to simply things, and also to allow for easier future modifications if more intermediate frames are needed.

re #1108 Changed output so intermediate files are not in different folders

In the previous commit, intermediate images were stored in different folders based on what filter they were associated with. This has been reverted.
Also gave the intermediate and output image files more descriptive names.

re #1108 Made the ability to read config files more flexible and reliable

Previously, reading config files relied upon <Processor ... > being the first element of the input xml file. This has been changed to allow for <Processor ... > to be anywhere in the config file.

Changed variable name of DilationKernelRadiusPixel to DilationKernelSize so that it remained consistent with other xml files.

re #1108 Cleaned up codes to make them more readable

-Added comments from Ben
-Removed the code that was commented out
-Moved initialization of <vtkSmartPointer>'s so they are initialized in the constructor
-Removed intermediate images that were redundant
-Changed various variable/function names to be more clear

re #1108 Fixed a bug the caused intermediate images to be stored in the input file's directory

Intermediate images are now stored in the same directory as where the output file will be saved

re #1108 Will now always use all fitters unless told otherwise

When processing frames in vtkPlusTransverseProcessEnhancer, all filters will be used unless the the inputted config file says otherwise

re #1108 Added method to remove images that precede shadow images. Also cleaned up code.

-Added comments from Ben
-Modified some of the default values so that they produce a more accurate result if the user does not input their value.
-Changed variable names to make them more consistent or clear.
-Moved a section of code that processed image extents to its own method.

re #1108 Removed a TODO that was already implemented

In the last push, a TODO was implemented, but the TODO comment itself was not removed. This has been fixed.

re #1108 Added pipeline functionality and a check to see if bones start off camera

Changed the way some filters gained their input, so that the code behaves more like a pipeline

Added a step that eliminates bone areas that are located too close to the edge of the camera.
Added a way to determine where each bone area begins and ends.

re #1108 Fully connected the pipeline. This update doesn't fully work.

Added IslandRemover, ImageEroder, and ImageDialator steps to the pipeline, though they currently only update to a blank image.

Also moved the steps where preceding bone images, and bone images that are off camera are removed. They now happen after the ImageDialator step so as to not interfere with the pipeline.

re #1108 Fixed issues with the pipeline, and added a check that compares Bone areas to the areas beside them.

In the last commit, the pipeline was fragmented and did not work properly. This issue has since been fixed.
There is also a new function that checks the amount of shadow found in a bone area and compares it to the amount of bone in the areas around it. If the areas surrounding the bone have more shadow, then the area is no longer considered to be a potential bone area.
Also changed the search algorithm so it is more accurate, but recursive.

re #1108 Added Threshold check based on a column's Standard Deviation

In this commit, the threshold filter was replaced with a check that compared a pixel's value to the standard deviation of the pixels in it's column. If this pixel's value is lower, it is removed.

-Added Documentation
-Cleaned up code
-Fixed minor issue whereby the image was not being returned to the fan image

re #1108 Changed the search method to be non-recursive, cleaned up code

Replaced the method that was used to find bone areas with one that is non-recursive and faster.
Also moved some code around so that it made more sense.

re #1108 Bone area search is now based on slope. Added a second island removal step.

The location of bone areas is now determined when pre-bone images are removed, and saved in a class variable for faster, easier access in future. The start and end of bone areas is now determined based on their relative slope to the pixels around them, rather then if they are connected.
Note: the previous way to find bone areas is still in the code, it is just not accessible.

Another island removal step was added after the erosion step to remove smaller islands.

The step for comparing a bone area to the areas next to it was made more flexible, to accommodate large bone areas close it the edge of the screen

re #1108 added a method to segment bone areas based on their slope

Added in a method that looks at various slopes of each potential bone area. If a slope is too steep, it is divided into a separate bone area.
Also remove the second Island Removal step that was added in the last commit.
Cleaned up code, added comments

re #1108 Cleaned up code, removed slope comparison method

-Removed the method that compared a bone area's pixels to see the slope it made with the pixels around it.
-Changed variable names to be more clear.
-Added TODO's marking all magic numbers
-Keeps a better log of bone areas to make the code more efficient
-Added comments

re #1108 Cleaned up code

-Removed old threshold filter
-Removed FillShadowValues and ProcessLinesImage methods
-Added comments
-Fixed style issues
-Made changes to loops for efficiency

re #1108 added basic input, output, and image processing functionality to vtkPlusTransverseProcessEnhancerTest
Modified existing program vtkPlusTransverseProcessEnhancerTest so that it may better test and get outputs from vtkPlusTransverseProcessEnhancer.
command line arguments may be in the following format:
vtkPlusTransverseProcessEnhancerTest.exe --output-config-file=ConfigFile.xml --input-seq-file=BoneUltrasound_L14.mha --output-seq-file=BoneUltrasound_L14_OUT_TEST.mha

Larger additions to vtkPlusTransverseProcessEnhancerTest include:
-more descriptive error messages.
-support for output as a shadow image file, a lines image file, and processed lines image file.

Also changed vtkPlusTransverseProcessEnhancer.cxx so that it better reads and writes information in config files, as a result of this, vtkPlusTransverseProcessEnhancer.h also had to be modified.
vtkPlusTransverseProcessEnhancer.h was not changed in any other way.

re #1108 Added ways to get various outputs, including various intermediate output images, and an output config file for recording what inputs were used
Added an optional argument to vtkPlusTransverseProcessEnhancerTest to allow for testing vtkPlusTransverseProcessEnhancer's WriteConfiguration() method. Using this argument will cause a config file to be created. This new config file will be filled with the settings that are being used during the current run of the test program. This new config file is intended to be identical to the inputted config file.

Added or expanded on optional arguments for various intermediate outputs, such as:
--output-lines-image-file
--output-intermediate-image-file
--output-shadow-image-file
--output-processedlines-image-file

Rewrote vtkPlusTransverseProcessEnhancer.cxx's WriteConfiguration() using XML_WRITE macros
Added error checking to alternate output files in vtkPlusTransverseProcessEnhancer.cxx

vtkPlusTransverseProcessEnhancer.h was changed to allow for the changes mentioned above.

re #1108 Added support for intermediate images to be saved throughout different points in the code.

Removed some command line arguments from vtkPlusTransverseProcessEnhancerTest and added the bool argument: --save-intermediate-images which makes the program save various intermediate images before and after steps of the filters. These intermediate images are saved in the same location as where the output file goes, and their file name is: output image file name + _ + an incrementing index + special postfix + .mha ex: BoneUltrasound_L14_TEST_2Lines.mha

In code, the intermediate images are being stored in a dictionary where _ + an incrementing index + special postfix is the key

re #1108 Finalized ability to save intermediate images in vtkPlusTransverseProcessEnhancer
Ability to save intermediate images while running vtkPlusTransverseProcessEnhancerTest.cxx hes been presumably finished.
Intermediate images are now saved to the local Output folder in a directory named IntermediateImageFiles, then in a sub-directory based on the file's postfex

The programs used to save intermediate images in variables, this has been changed so that it saves them in a map. The reason for this was to simply things, and also to allow for easier future modifications if more intermediate frames are needed.

re #1108 Changed output so intermediate files are not in different folders

In the previous commit, intermediate images were stored in different folders based on what filter they were associated with. This has been reverted.
Also gave the intermediate and output image files more descriptive names.

re #1108 Made the ability to read config files more flexible and reliable

Previously, reading config files relied upon <Processor ... > being the first element of the input xml file. This has been changed to allow for <Processor ... > to be anywhere in the config file.

Changed variable name of DilationKernelRadiusPixel to DilationKernelSize so that it remained consistent with other xml files.

re #1108 Cleaned up codes to make them more readable

-Added comments from Ben
-Removed the code that was commented out
-Moved initialization of <vtkSmartPointer>'s so they are initialized in the constructor
-Removed intermediate images that were redundant
-Changed various variable/function names to be more clear

re #1108 Fixed a bug the caused intermediate images to be stored in the input file's directory

Intermediate images are now stored in the same directory as where the output file will be saved

re #1108 Will now always use all fitters unless told otherwise

When processing frames in vtkPlusTransverseProcessEnhancer, all filters will be used unless the the inputted config file says otherwise

re #1108 Added method to remove images that precede shadow images. Also cleaned up code.

-Added comments from Ben
-Modified some of the default values so that they produce a more accurate result if the user does not input their value.
-Changed variable names to make them more consistent or clear.
-Moved a section of code that processed image extents to its own method.

re #1108 Removed a TODO that was already implemented

In the last push, a TODO was implemented, but the TODO comment itself was not removed. This has been fixed.

re #1108 Added pipeline functionality and a check to see if bones start off camera

Changed the way some filters gained their input, so that the code behaves more like a pipeline

Added a step that eliminates bone areas that are located too close to the edge of the camera.
Added a way to determine where each bone area begins and ends.

re #1108 Fully connected the pipeline. This update doesn't fully work.

Added IslandRemover, ImageEroder, and ImageDialator steps to the pipeline, though they currently only update to a blank image.

Also moved the steps where preceding bone images, and bone images that are off camera are removed. They now happen after the ImageDialator step so as to not interfere with the pipeline.

re #1108 Fixed issues with the pipeline, and added a check that compares Bone areas to the areas beside them.

In the last commit, the pipeline was fragmented and did not work properly. This issue has since been fixed.
There is also a new function that checks the amount of shadow found in a bone area and compares it to the amount of bone in the areas around it. If the areas surrounding the bone have more shadow, then the area is no longer considered to be a potential bone area.
Also changed the search algorithm so it is more accurate, but recursive.

re #1108 Added Threshold check based on a column's Standard Deviation

In this commit, the threshold filter was replaced with a check that compared a pixel's value to the standard deviation of the pixels in it's column. If this pixel's value is lower, it is removed.

-Added Documentation
-Cleaned up code
-Fixed minor issue whereby the image was not being returned to the fan image

re #1108 Changed the search method to be non-recursive, cleaned up code

Replaced the method that was used to find bone areas with one that is non-recursive and faster.
Also moved some code around so that it made more sense.

re #1108 Bone area search is now based on slope. Added a second island removal step.

The location of bone areas is now determined when pre-bone images are removed, and saved in a class variable for faster, easier access in future. The start and end of bone areas is now determined based on their relative slope to the pixels around them, rather then if they are connected.
Note: the previous way to find bone areas is still in the code, it is just not accessible.

Another island removal step was added after the erosion step to remove smaller islands.

The step for comparing a bone area to the areas next to it was made more flexible, to accommodate large bone areas close it the edge of the screen

re #1108 added a method to segment bone areas based on their slope

Added in a method that looks at various slopes of each potential bone area. If a slope is too steep, it is divided into a separate bone area.
Also remove the second Island Removal step that was added in the last commit.
Cleaned up code, added comments

re #1108 Cleaned up code, removed slope comparison method

-Removed the method that compared a bone area's pixels to see the slope it made with the pixels around it.
-Changed variable names to be more clear.
-Added TODO's marking all magic numbers
-Keeps a better log of bone areas to make the code more efficient
-Added comments

re #1108 Cleaned up code

-Removed old threshold filter
-Removed FillShadowValues and ProcessLinesImage methods
-Added comments
-Fixed style issues
-Made changes to loops for efficiency

re #1108 Removed ability to skip filters, added comments

Based on parameters from the xml file, some filters could be turned on or off to better test them. This has been removed. Code was also cleaned up.

re #1108 Saving intermediate images made more efficient

Prior to entering the AddIntermediateImage method, there is now a check to see if intermediate images should be saved.

re #1108 Improved comments

Fixed spelling errors and made comments more clear

Branch: master
Commit: plus:142d2d217e

2017-09-11 14:50
Anonymous
re #1108: Fixed build error in EnhanceUsTrpSequence command-line tool

Testing will be needed

Branch: master
Commit: plus:6468f65deb

**Comment by nehk018** [comment]
Hello, 
when I try to build the latest version of PlusLib I get the next error:

PlusLib/src/PlusImageProcessing/vtkPlusTransverseProcessEnhancer.cxx:35:21: error: cannot call constructor ‘vtkPlusTransverseProcessEnhancer::Superclass {aka vtkPlusBoneEnhancer}::vtkPlusBoneEnhancer’ directly
   this->Superclass::vtkPlusBoneEnhancer();


Best regards
Jorge

**Comment by lassoan** [comment]
Thanks for reporting this. It seems that gcc has trouble with a modification that was committed yesterday.

@Sunderlandkyl could you touch it up? It shows up on our dashboard, too: http://perkdata.cs.queensu.ca/CDash/viewBuildError.php?buildid=84402

**Comment by Sunderlandkyl** [comment]
@nehk018 @lassoan Should be fixed now!
