### ISSUE TITLE
Add a new tracker device to support multiple US digital A2 encoders

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#174]
Add a new tracker device (vtkUSDigitalA2EncodersTracker) to support multiple US digital A2 encoders in vtkDataCollection.

Here is the design goal of the new tracker device:
1) Communication with multiple encoders (US Digital A2 type) with SEI interface.
2) Acquire encoder values from multiple connected encoders.
3) Combine acquired encoder values and generate one representative transformation matrix based on user-defined configuration.

Also add a following test code and configuration XML file.

Migrated from https://app.assembla.com/spaces/plus/tickets/1061/details

**Comment by Sunderlandkyl** [comment]
2016-01-14 13:05
Adam Rankin
US digital provides documentation of the protocol, but do they offer an implementation to abstract away the details?

protocol link

2016-01-14 13:06
Adam Rankin
Found it:

software

2016-01-14 13:08
Adam Rankin
Minor comment, I would recommend a more flexible name since the software API supports the A2, A2K, A2T and HD25A encoders.

Perhaps

vtkUSDigitalEncoderSEITracker

2016-01-14 13:44
Andras Lasso
Or just vtkUSDigitalEncoderTracker. It can be specified in the documentation what exact protocols and devices it supports.

2016-01-14 13:46
Hyun Jae Kang
Thank Adam for your comment,

I think "vtkUSDigitalEncoderSEITracker " is good name for the new class. I will change the class name.

Could you give me some information of matrix-operation/transformation-matrix(4x4) operation within PlusLib?

And, I have another question.
Can we change the order of transformation conversion with XML configuration?

For example, there are three transformation matrix T1, T2, T3.
And then, Can we generate the following final transformation matrix based on a user-defined XML configuration,?
Case 1) T_out = T1 x T2 x T3
Case 2) T_out = T2 x T1 x T3
Case 3) T_out = T3 X T1 x T2

This class will support multiple encoder and each encoder will provide a movement/rotation according to a specific coordinate. Finally, one representative transformation matrix will be computed with the acquired and calculated multiple sub-transformation.

If possible, I would like to implement the above function with reconfigurable based on a XML configuration.

2016-01-14 13:54
Adam Rankin
PlusLib uses vtkMatrix4x4 for it's transformation storage.

Depending on the interface of the API, if you poll the devices for data, then look into vtkPlusDevice::InternalUpdate. If the API provides a callback, then InternalUpdate is not needed (unless for other reasons).

To record a transform to a tool data source, look into vtkPlusDevice::ToolTimeStampedUpdate

You can store anything you like in XML. Look into vtkPlusDevice::ReadConfiguration and vtkPlusDevice::WriteConfiguration. A configuration file is typically set up by the user (or the engineer supporting the user) or provided by you, the author!

For helpful examples, look at vtkNDITracker or vtkAscension3DGTrackerBase to learn from!

2016-01-14 13:55
Adam Rankin
Both of those devices are polling-based acquisition.

2016-01-14 14:04
Hyun Jae Kang
Thanks for your helpful comments.

2016-01-14 14:21
Andras Lasso
Transforms are automatically concatenated and inverted as needed. You just have to specify a unique name for each coordinate system you have and then each transform is defined by specifying from what to what coordinate system it transforms. Tracker tools so far use a common coordinate system name, but (AToTracker, BToTracker, etc) but we can change that to be able to specify arbitrary "To" and "From" names.

2016-01-14 14:53
Hyun Jae Kang
Thanks Andras for your helpful comments.

Could you give me some information about which class or code will be good for me to understand about the Transformation-chain. I found the class of "PlusTransformName". But, I am still looking for real matrix operation part within PlusLib.

2016-01-14 15:13
Adam Rankin
I think what you're looking for is vtkTransformRepository

https://www.assembla.com/spaces/plus/subversion/source/HEAD/trunk/PlusLib/src/PlusCommon/vtkTransformRepository.cxx

Basically, a TrackedFrame puts all of its non-persistent transforms (typically from tracker devices) into the repository (which already contains persistent transforms, such as calibrations) and then the repository will then provide any transform you wish so long as it can be computed (by inverting known transforms, chaining transforms together, etc...)

2016-01-14 15:17
Hyun Jae Kang
Thanks Adam for your quick and valuable comments.

2016-01-14 15:17
Adam Rankin
This is not something you will have to manage though. By providing the correct config file syntax (data source for a tool/tools) and using ToolTimeStampedUpdate all of this is managed for you.

2016-01-14 15:21
Hyun Jae Kang
Thanks,
I will check vtkTransformRepository and the its test code.

2016-02-24 10:08
Hyun Jae Kang
re #1061: Added the macro of "#cmakedefine PLUS_USE_USDIGITALENCODERS_TRACKER" for a new class of USDigitalEncodersTracking
Committed to: plus
In plus:4511

2016-02-24 10:10
Hyun Jae Kang
re #1061: Added the class of vtkUSDigitalEncodersTracker for USDigitalEncodersTracking
Committed to: plus
In plus:4512

2016-02-24 10:11
Hyun Jae Kang
re #1061: Added the option of PLUS_USE_USDIGITALENCODERS_TRACKER for vtkUSDigitalEncodersTracking
Committed to: plus
In plus:4513

2016-02-24 10:12
Hyun Jae Kang
re #1061: Added the class of vtkUSDigitalEncodersTracking to support multiple USDigital Encoders tracking system
Committed to: plus
In plus:4514

2016-02-24 10:26
Hyun Jae Kang
re #1061: Redefined the versiontxt to avoid compile error of already defined global variable.
Committed to: plus
In plus:4515

2016-02-24 10:31
Hyun Jae Kang
re #1061: Added a test code of vtkUSDigitalEncodersTrackerTest.cxx for vtkUSDigitalEncodersTracking
Committed to: plus
In plus:4516

2016-02-25 15:24
Hyun Jae Kang
re #1061: Added the option of USDigitalEncodersTracker for the vtkUSDigitalEncodersTracker device.
Committed to: plus
In plus:4518

2016-03-10 13:39
Hyun Jae Kang
re #1061: Added the control functions of US Digital Encoders for a calibration task of USDigitalEncodersTracker.
Committed to: plus
- PlusStatus SetUSDigitalA2EncodersStrobeMode();
- PlusStatus SetUSDigitalA2EncodersSleep();
- PlusStatus SetUSDigitalA2EncodersWakeup();
- PlusStatus SetUSDigitalA2EncoderOriginWithAddr(long address);
- PlusStatus SetUSDigitalA2EncoderOriginWithSN(long sn);
- PlusStatus SetAllUSDigitalA2EncoderOrigin();
- PlusStatus SetUSDigitalA2EncoderModeWithAddr(long address, long mode);
- PlusStatus SetUSDigitalA2EncoderModeWithSN(long sn, long mode);
- PlusStatus GetUSDigitalA2EncoderModeWithAddr(long address, long* mode);
- PlusStatus GetUSDigitalA2EncoderModeWithSN(long sn, long* mode);
- PlusStatus SetUSDigitalA2EncoderResoultionWithAddr(long address, long res);
- PlusStatus SetUSDigitalA2EncoderResoultionWithSN(long sn, long res);
- PlusStatus GetUSDigitalA2EncoderResoultionWithAddr(long address, long* res);
- PlusStatus GetUSDigitalA2EncoderResoultionWithSN(long sn, long* res);
- PlusStatus SetUSDigitalA2EncoderPositionWithAddr(long address, long pos);
- PlusStatus SetUSDigitalA2EncoderPositionWithSN(long sn, long pos);
- PlusStatus GetUSDigitalA2EncoderPositionWithAddr(long address, long* pos);
- PlusStatus GetUSDigitalA2EncoderPositionWithSN(long sn, long* pos);
- long GetUSDigitalA2EncoderAddressWithSN(long sn);
In plus:4563

2016-04-28 16:31
Hyun Jae Kang
re #1061: Fixed a wrong function call within SetAllUSDigitalA2EncoderOrigin.
Committed to: plus
- Replace the function call of SetUSDigitalA2EncoderOriginWithSN with SetUSDigitalA2EncoderOriginWithAddr to reset all connected US digital encoders.
In plus:4613

2016-07-13 13:03
Adam Rankin
Milestone changed from Continuous activities to Release Plus-Future

2016-11-22 14:54
Dzenan Zukic
re #1061 Adding support for coreXY configuration for US Digital encoders:
Committed to: plus
http://corexy.com/theory.html
In plus:4940

2016-12-26 12:08
Dzenan Zukic
re #1061 Fixing bug from rev. 4940
Committed to: plus
The last commit had real code commented-out
and simulated time-base position code active.
In plus:4998

2017-07-05 10:30
Adam Rankin
re #1061 USDigital encoders don't require serial numbers (#62)

re #1061 USDigital encoders don't require serial numbers

Instead, rely on experimentally determined implicit ordering of encoders: encoder with a lower serial number gets a lower address

re #1061 reformatting USDigitalEncodersTracking

re #1061 fixing a couple of old bugs

re #1061 initialize member variables at declaration

re #1061 remove redundant comments

re #1061 remove unnecessary clear calls in the constructor

re #1061 Remove unused BaudRate parameter

Branch: master
Commit: plus:71c06c5d66

2017-07-11 14:44
Adam Rankin
re #1061 Fixing build on VS2010

Adjusting code to conform to Plus coding conventions

Extracting INVALID_SEI_ADDRESS (-1) validity check to function

Branch: master
Commit: plus:af8a40ff55

2017-07-12 10:04
Andras Lasso
re #1061: Fixed build error on VS2010

Branch: master
Commit: plus:8395e087fb

2017-08-09 12:41
Dzenan Zukic
re #1061 config file simplification to go along with PR68
Committed to: plus
https://github.com/PlusToolkit/PlusLib/pull/68
In plus:5115

2017-08-15 16:13
Adam Rankin
re #1061 Supporting multiple coreXY configurations (#68)

re #1061 Supporting multiple coreXY configurations - internal class cleanup

re #1061 Supporting multiple coreXY configurations - removing serial numbers

re #1061 Supporting multiple coreXY configurations - simplifying the class

re #1061 Supporting multiple coreXY configurations - removing Encoder_ prefix

re #1061 Supporting multiple coreXY configurations - minor cleanup

re #1061 Supporting multiple coreXY configurations - substance changes

re #1061 Supporting multiple coreXY configurations - sequential addresses

re #1061 Supporting multiple coreXY configurations - reducing duplication

re #1061 Supporting multiple coreXY configurations - removing persistence and PreTMatrix

re #1061 Supporting multiple coreXY configurations - per DataSource ToolReferenceFrame

re #1061 Supporting multiple coreXY configurations - review suggestions

Branch: master
Commit: plus:1e6e9d7a9d

2017-09-15 14:35
Adam Rankin
Use device IDs instead of device addresses (#77)

re #1061 Supporting non-default addresses of encoders

re #1061 Fixing spelling

re #1061 Using deviceID instead of address for direct encoder queries

re #1061 Renaming functions to indicate switch from addresses to device IDs

Branch: master
Commit: plus:7c794e6867

2017-09-15 14:43
Adam Rankin
re #1061 minor code style (#78)

Branch: master
Commit: plus:9560643fe5

**Comment by dzenanz** [comment]
Should this issue be closed? This is already implemented, and we should be able to reference a closed issue from future pull requests, right?
