### ISSUE TITLE
GetPolydata command does not adhere to conventions

### ISSUE THREAD

**Issue by adamrankin** [PlusToolkit/PlusLib#177]
Name is not correct and attribute case is incorrect

**Comment by lassoan** [comment]
@adamrankin It seems that we'll be ready for a new stable version within a week (depending on what we decide to include from OptiTrack developments). Do you think you can close this issue by then or can this be postponed to be fixed after the stable release?

**Comment by adamrankin** [comment]
It will be closed by release. I am fixing up some client side code for server drops, then I will be testing it.
