### ISSUE TITLE
Enable true absolute encoder functionality to USDigitalEncodersTracker

### ISSUE THREAD

**Issue by jamesobutler** [PlusToolkit/PlusLib#180]
The [USDigitalEncodersTracker.h](https://github.com/PlusToolkit/PlusLib/blob/2a89e14be2910d61dc18cdb2598a116012b85fdc/src/PlusDataCollection/USDigitalEncodersTracking/vtkPlusUSDigitalEncodersTracker.h#L18-L20) says it is an 

> Interface for multiple US Digital A2, A2T, A4, HBA2, HBA4 or HD25A encoders to generate pose information of a target object.

These are all absolute encoders, but it appears within the USDigitalEncodersTracker that the "absoluteness" isn't really being used.  [Here](https://github.com/PlusToolkit/PlusLib/blob/2a89e14be2910d61dc18cdb2598a116012b85fdc/src/PlusDataCollection/USDigitalEncodersTracking/vtkPlusUSDigitalEncodersTracker.cxx#L173-L177) within the `internalConnect` call it sets the position to zero.  

The default encoder [mode](https://github.com/PlusToolkit/PlusLib/blob/2a89e14be2910d61dc18cdb2598a116012b85fdc/src/PlusDataCollection/USDigitalEncodersTracking/vtkPlusUSDigitalEncodersTracker.cxx#L79) is multi-turn mode and from the [A2K](https://www.usdigital.com/products/a2k) encoder product page it says that when in Multi-turn mode the power must be maintained to prevent reset to zero.  This functionality is ok, but when PLUS resets the position at each start even if power has not been cycled to the encoders, it pretty much removes any "absoluteness" of positioning and requires calibration each time the server starts.

Hey @dzenanz, do you agree that the positioning shouldn't be set to zero on start?

**Comment by dzenanz** [comment]
I have noticed resetting the encoders to zero in code, but I though it was done because you wanted it. I can easily remove it if you want.

**Comment by jamesobutler** [comment]
Yeah go ahead and remove it.  I think Hyun Jae originally put it in there when the class was created. Unsure what was the original reasoning.
