### ISSUE TITLE
Use PlusLib or PlusApp modification date in PlusApp package name

### ISSUE THREAD

**Issue by lassoan** [PlusToolkit/PlusLib#189]
If only PlusLib is changed, then date in PlusApp package name (PlusApp-2.5.0.20170918-Telemed-Win32.exe) is not updated, which is quite confusing.

Problem is that in CPackConfig.cmake PLUSAPP_COMMIT_DATE_NO_DASHES variable is used for constructing the package name:

    SET(CPACK_PACKAGE_FILE_NAME "PlusApp-${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}.${PLUSAPP_COMMIT_DATE_NO_DASHES}-${PLUSAPP_PACKAGE_EDITION_PLATFORM}" )

Proposed solution:
- In PlusLib, compute a latest PLUSLIB_COMMIT_DATE and pass it to PlusApp through UsePlusLib.cmake.in (there are already PLUSLIB_REVISION and similar fields, it could be added there)
- in PlusApp, compute latest date from PLUSLIB_COMMIT_DATE and PLUSAPP_COMMIT_DATE, and use that for generating the package name

**Comment by adamrankin** [comment]
My vote would be pass date from pluslib to plusapp. PlusApp requires PlusLib, so that dependency is always reliable.

Perhaps it should be the higher of the two modification dates?

**Comment by lassoan** [comment]
Yes, I meant computing the higher of the two modification dates.
