### ISSUE TITLE
Test Plus before releasing new stable version

### ISSUE THREAD

**Issue by lassoan** [PlusToolkit/PlusLib#192]
Double-check that all main features of Plus work before releasing stable build. See the "test plan" below. It would be nice to add more details (what config file was used, etc) as the test is performed. The test report would be used as a template for testing the next stable release (probably it would make sense to add to the PlusLib or PlusApp repository).

------

- [x] Green dashboard (no build or test errors):
  - Some tests are unstable (AccurateTimerTest, PlusMathTest, etc.), but they are not blocking issues
  - Windows
    - [x] PlusBuild
    - [x] PlusApp
    - [x] PlusLib
  - Linux
    - [x] PlusBuild
    - [x] PlusApp
    - [x] PlusLib
- Plus runs on Ultrasonix (Windows XP Embedded):
  - Slicer version: 4.8.0
  - Ultrasound exam software version: Sonix 5.7
  - Ultrasound probe: Ultrasonix C5-2
  - [x] Live image is displayed in Slicer
  - [x] Start/stop recording works in Slicer using PlusRemote
  - [x] Scout scan and live volume reconstruction works in Slicer using PlusRemote
- [x] Tracking using NDI Polaris
Polaris still has issues connecting to macOs and Linux (see https://github.com/PlusToolkit/PlusLib/issues/263), however this is not a blocking issue, since no stable packages are built for either Linux or Mac.
- [x] Tracking using NDI Aurora
- [x] Tracking using PhidgetSpatial
- [x] Ultrasound imaging using Interson
- [x] Ultrasound imaging using Telemed
- [x] Image acquisition using Epiphan
- [x] Image acquisition using webcam - Video for Windows
- [x] Grayscale image acquisition using webcam - MMF
- [x] Color image acquisition using webcam - MMF
- [x] Image acquisition using ImagingControls
- [x] Tracking using StealthLink
  - Make sure to test image retrieve using OpenIGTLinkRemote
- [x] Tracking using OpticalMarkerTracking
- [x] Tracking using OptiTrack
- [x] Replay of tracked video from saved data source
- [x] US simulator using Slicer scene in DataStore
- [x] OpenIGTLinkTracker
- [x] OpenIGTLinkVideo
- [x] ThorLabs spectroscope

Not included in testing (we may revise this and move some items to the list of required tests):
- Tracking using MicronTracker: not a priority anymore (Firewire interface is difficult to set up; OpticalMarkerTracking and OptiTrack devices can be used instead for most applications)
- RealSense: still experimental
- IntersonArraySDK: we don't have the hardware
- Agilent: we don't have the hardware
- BrachyTracking: not a priority anymore, we don't have all the hardware
- Capistrano: we don't have the hardware
- CHRobotics: not a priority anymore (PhidgetSpatial is easier to use)
- Haptics: we don't have the hardware
- ImageProcessor: still experimental
- IntuitiveDaVinci: we don't have the hardware
- MicrochipTracking: we don't have the hardware
- NDICertus: not a priority anymore (use Polaris instead, that's what most commercial devices use)
- NVidiaDVP: we don't have the hardware
- BK ultrasound OEM: we don't have the hardware
- BK ultrasound CameraLink: we don't have the hardware
- Optimet: we don't have the hardware
- OvrVisionPro: we don't have the hardware
- Philips3D: we don't have the hardware
- USDigital encoders: we don't have the hardware
- WinProbe: we don't have the hardware

**Comment by jamesobutler** [comment]
The group I work with has hardware for Capistrano(3rd party SDK required), USDigitalEncoders, and WinProbe(3rd party SDK required). If you need anything related to testing, you can let us know.  I think we are the primary/only users of these items too.

**Comment by lassoan** [comment]
@jamesobutler We plan to release a new stable version of Plus based on the current master branch content in 1-2 weeks. It would be great if you could test if Capistrano, USDigitalEncoders, and WinProbe interfaces work well.

**Comment by adamrankin** [comment]
Please delay release until I can confirm NDI tracker working on MacOSX, assuming your are locking dependencies to versions. Working on it right now.

**Comment by Sunderlandkyl** [comment]
Sure, I'll wait to until you finish before finalizing PlusLib and the dependencies.
