### ISSUE TITLE
PlusTranverseProcessor test data doesn't exist

### ISSUE THREAD

**Issue by adamrankin** [PlusToolkit/PlusLib#194]
The test is looking for a data file that doesn't exist.

It seems like it may have been a missed file during a commit?

**Comment by lassoan** [comment]
@cpinter Could you please check this with Bryan? Thanks!

**Comment by Sunderlandkyl** [comment]
@cpinter @lassoan Was it the consensus that this test should be disabled?
In addition to the missing data file, there also seems to be a missing config file.

**Comment by cpinter** [comment]
Sorry for the delay, I'll find out. He implemented a test and had test data, so this test should work (if it's really for the vtkPlusTransverseProcessEnhancer, the title is not definitive).

**Comment by travers-bryan** [comment]
I have made a pull request with the files necessary for the test to run. Please let me know of there is anything wrong with the files or the test.

**Comment by lassoan** [comment]
https://github.com/PlusToolkit/PlusLibData/pull/8 is merged.
@Sunderlandkyl Please check if this works as expected now.

**Comment by Sunderlandkyl** [comment]
Confirmed, the test passes on both Windows (http://perkdata.cs.queensu.ca/CDash/testDetails.php?test=1552680&build=82429) and Linux (http://perkdata.cs.queensu.ca/CDash/testDetails.php?test=1552760&build=82430)

**Comment by cpinter** [comment]
Thanks, @travers-bryan !
