### ISSUE TITLE
Support multiple tracking tools in StealthLink

### ISSUE THREAD

**Issue by lassoan** [PlusToolkit/PlusLib#196]
There are some limitations in what tools can be tracked simultaneously by StealthStation, but all tools should be accessible through StealthLink:

**Comment by lassoan** [comment]
You can use TESLA to build a Plus package with StealthLink support. The build tree is here: d:\D\PTNPSLb

**Comment by lassoan** [comment]
from @Sunderlandkyl:

> I made some modifications to Plus so that it could track all of the tools in the FOV, instead of just 1.
> It works, however the execution time of InternalUpdate has gone from ~0.043s to ~0.188s (for 3 tools and 1 reference frame).
> Specifically, querying the server for instrument data takes about ~0.043s per tracked object.
> 
> I'm going to keep looking at the documentation to see if I can find an alternative method.

**Comment by lassoan** [comment]
Thanks. It sounds promising, however the dropping of the frame rate from 23fps to 5fps may not be acceptable in many applications.

@ungi Do we need to track more tools than what StealthStation supports?

If yes, then we'll have to contact Medtronic to see if really 5fps is the best performance we can get. If not, then just commit what we have (but make sure the performance is not degraded compared to what we had before).

**Comment by Sunderlandkyl** [comment]
@lassoan If I make the optimization that we discussed today (removing a redundant query). The fps would be something like:

- 1 frame + 1 tool: 23.3fps
- 1 frame + 2 tools: 11.6fps
- 1 frame + 3 tools: 7.8fps
- 1 frame + 4 tools: 5.8fps

This should give us the same performance as before when using 1 frame and 1 tool, but would still decrease in performance as more tools are added.

Perhaps we could add an option in the config file to either track all tools, or to match the StealthStation's behavior and only track the tool that is closest to the frame?

**Comment by lassoan** [comment]
> Perhaps we could add an option in the config file to either track all tools

Good idea. Let's add an option for that. Probably the best would be to add it in the DataSource element (AlwaysTrack? ForceQuery? or something like that) so that it can be set for specific tools only, by default disabled (better performance).
