### ISSUE TITLE
Instrucctions to add a new module.

### ISSUE THREAD

**Issue by nehk018** [PlusToolkit/PlusLib#198]
Few weeks ago I saw a manual to add a new module to the Plus Toolkit in Assembla.

I have been searching the manual in Git, but I have not found it.
I'm trying to add a Infrared Camera like a  Plus module. 

Can anyone help me?
Thank you.
Jorge Quintero
IAC. Tenerife. Canary Island.

**Comment by adamrankin** [comment]
Definitely. This would be a good guide to have. I will write one up today.

**Comment by dzenanz** [comment]
I will probably add Andor camera support in the near future. It would be better to have a guide with best practices instead of just picking a similar module, copying/renaming it and starting from there. The latter approach run a risk of using deprecated functionality or old style.

**Comment by lassoan** [comment]
I agree that such guides are useful but keep it very generic and high-level and refer to working code for details.

**Comment by markasselin** [comment]
@nehk018 Out of curiosity, which camera do you plan on integrating?

**Comment by dzenanz** [comment]
iKon Model DU934P-BV

**Comment by nehk018** [comment]
@markasselin I'm using a Compac Seek Camera. It's a phone device, but I found a driver for linux. I know it isn't the best device, but now it's the only infrared camera that I have.

**Comment by markasselin** [comment]
@dzenanz @nehk018 Great to hear more devices are being added to PLUS!

**Comment by lassoan** [comment]
Closing this now. Please reopen if you have further questions related to this topic.
