### ISSUE TITLE
What is the appropriate way to submit code changes?

### ISSUE THREAD

**Issue by carlos-luque** [PlusToolkit/PlusLib#199]
We have found and fixed some bugs in DataCollection code and we would like to know what the regular procedure to submit the changes is.

**Comment by lassoan** [comment]
We follow standard [GitHub Flow process](https://guides.github.com/introduction/flow/). Just send a pull request with proposed changes.

**Comment by adamrankin** [comment]
We appreciate bug fixes! Thanks so much.

**Comment by lassoan** [comment]
Closing this now. Please reopen if you have further questions related to this topic.
