### ISSUE TITLE
Connecting to NDI Polaris is unreliable

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#202]
When testing the NDI Polaris, I frequently found that I had to start the server multiple times in order to make a successful connection.

Log File: [100617_094842_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/1363215/100617_094842_PlusLog.txt)

**Comment by adamrankin** [comment]
If you set the serial port, does it connect immediately?

What is the reproduceability of this? Does it happen with a freshly powered on Polaris? Was the Polaris connected too previously by a previous plus instance? a previous NDI software instance?

**Comment by adamrankin** [comment]
Is this a Spectra, Vicra? What is the firmware version?

**Comment by Sunderlandkyl** [comment]
Spectra, firmware: 007.000.012.

It happens quite frequently, both with and without previous connections.
I tried setting the serial port, and it didn't seem to have an effect one way or the other.

**Comment by prash-p** [comment]
I notice the same behaviour. I am using a Polaris that predates the spectra/vicra models

**Comment by adamrankin** [comment]
[Spectra_Combined_Firmware_Revision_012.zip](https://github.com/PlusToolkit/PlusLib/files/1369553/Spectra_Combined_Firmware_Revision_012.zip)
[Spectra_Combined_Firmware_Revision_015.zip](https://github.com/PlusToolkit/PlusLib/files/1369552/Spectra_Combined_Firmware_Revision_015.zip)

Could you try with revision 15, and see if the behaviour changes? You can flash back to 12 afterwards if you like. I do not experience the same issues. I will test on a few devices that we have in the lab.

**Comment by lassoan** [comment]
I would prefer not to update to the latest firmware until this issue is fully resolved. Communication worked flawlessly using rev12 firmware, so we should be able to keep that, while also making all the nice improvements available (at least for devices with rev15 firmware).

**Comment by adamrankin** [comment]
This is to test if it's a firmware 12 issue. I can't debug further until it's tested.

**Comment by adamrankin** [comment]
Specifically, I am wondering if it is a serial baud rate issue, due to the new autoselection of fastest baud rate. Perhaps the OS is reporting that a baud rate is ok, but the device can't actually handle that. It should fail much sooner than copying over ROM files, but the errors in the log don't actually make any sense.

That part of the code hasn't changed.

**Comment by adamrankin** [comment]
Do you connect your device via USB and use the 2.8.28.0 driver from NDI (2013-03-26)?

**Comment by lassoan** [comment]
The problem is with firmware 12. If it works with 15 then we still have to switch back to 12 to test. Have you tested your tracker with firmware 12? Did it work well?

Camera, system control unit, and wired tools all have firmware and configuration data stored internally, so I would like to avoid upgrading them because potentially we might not be able to restore exactly everything to the current state (which is what many other Plus users have).

**Comment by adamrankin** [comment]
100% success rate with Spectra rev 14 and Vicra rev 15. Downgrading Spectra to 12 now.

**Comment by adamrankin** [comment]
Hmm, downgrading may require some sort of force parameter. Will check in with NDI.

**Comment by adamrankin** [comment]
If you remove the baud rate argument, does it work?

**Comment by adamrankin** [comment]
Hmm, no, mine works with and without the argument.

**Comment by Sunderlandkyl** [comment]
> Do you connect your device via USB and use the 2.8.28.0 driver from NDI (2013-03-26)?

Yes

> If you remove the baud rate argument, does it work?

I can confirm that removing the baud rate doesn't work.

**Comment by adamrankin** [comment]
I can't really test different code combinations as my devices work =/

In Plus stable, you get 100% connection rate, right?

**Comment by Sunderlandkyl** [comment]
Yeah, the stable version works perfectly.

**Comment by adamrankin** [comment]
I am working with NDI to revert our Spectra to revision 12, but it's not going smoothly. If you guys have time to identify why the code fails to connect, that would be very much appreciated.

A CRC error should be extremely rare, if never.

**Comment by Sunderlandkyl** [comment]
We could also set up a remote desktop on a computer with the Polaris connected if that would help.

**Comment by Sunderlandkyl** [comment]
I'm trying to debug the error, but I haven't found the source of the problem.
I'm attaching a set of more verbose log files.

Connecting seems to fail in two different ways:
[102417_105536_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/1411301/102417_105536_PlusLog.txt)
[102417_105557_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/1411303/102417_105557_PlusLog.txt)

And:
[102417_105546_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/1411302/102417_105546_PlusLog.txt)
[102417_105311_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/1411304/102417_105311_PlusLog.txt)

I don't know if these are independent or related issues.

**Comment by adamrankin** [comment]
Identified one bug, will see if it's the cause. Config file says BaudRate 115200, but Plus is requesting 1.2Mb

**Comment by adamrankin** [comment]
Could you test with https://github.com/PlusToolkit/PlusLib/tree/ndi_requested_baud ?

**Comment by lassoan** [comment]
We spent almost the entire day with testing this. We found a couple of small bugs (including what you've just fixed) but the main issue is seems to be around setting the baud rate. Setting a fixed baud rate definitely helped but communication still randomly breaked down after changing the baud rate. Maybe we just need to add/increase delays. We'll do further testing.

**Comment by Sunderlandkyl** [comment]
I created a pull request integrating your changes Adam, with the changes that Andras and I made: https://github.com/PlusToolkit/PlusLib/pull/244

I managed to fix one of the remaining issues that were affecting some of the higher baud rates.
When some of the blocks of the tool definition file failed to upload, the function wouldn't fail, since it only reported the error code from the last block. I changed it to retry each block until it succeeds, and to fail if any of the blocks are not uploaded.

The only remaining major issue is that the frame number seems to alternate between a small, likely correct number, and a larger incorrect one.

I'll report back if I find something.

**Comment by adamrankin** [comment]
This is such odd behaviour. Is it because we never used to try the high baud rates?

**Comment by lassoan** [comment]
Maybe higher baud rates are not stable with the older firmware versions? In the PerkLab we've been using standard RS-232 baud rates without any problem (of course we do not get very high frame rates).

**Comment by Sunderlandkyl** [comment]
Fixed Polaris connection issues in pull requests: https://github.com/PlusToolkit/PlusLib/pull/244, https://github.com/PlusToolkit/ndicapi/pull/6, and https://github.com/PlusToolkit/ndicapi/pull/7.

Confirmed fixed on latest nightly.
