### ISSUE TITLE
Image still streams when embedded transform is not available

### ISSUE THREAD

**Issue by prash-p** [PlusToolkit/PlusLib#204]
In the development snapshot I have noticed that the ultrasound image is still being updated even when the coordinate reference frame I am embedding it in is interrupted or unavailable. 

Previously, the image used to freeze if the transform to the reference frame was not available, and this would be a good indicator that the transform is not available. Would it be possible to add some sort of indication when the embedded image transform gets interrupted?

**Comment by lassoan** [comment]
There is a check here that prevents sending of the image if the embedded transform is invalid:

https://github.com/PlusToolkit/PlusLib/blob/cb775a9d61fc5d277a9651657acd5ad292d972ed/src/PlusOpenIGTLink/vtkPlusIgtlMessageFactory.cxx#L173

Could you double-check if the ImageTo(EmbeddedTransformToFrame)Transform is invalid?
Could you add a break point to the line referenced above and see what happens there?

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
