### ISSUE TITLE
Optical Marker Tracker on Ultrasonix 

### ISSUE THREAD

**Issue by Colleenog** [PlusToolkit/PlusLib#211]
We have the Optical Marker Tracker configured on the Windows 64 version of PLUS, and would like to try it as our tracker with the Ultrasonix machine video stream. However, when we use the same config file with the Ultrasonix version of PLUS, the error message reports that Optical Marker Tracker is not supported. Is this feature planned to be integrated into the Ultrasonix version of PLUS?

Thank you!

**Comment by adamrankin** [comment]
It could be enabled for the build, as it has no conflicts. @lassoan?

**Comment by lassoan** [comment]
As far as I know, Ultrasonix does not have 64-bit SDK, so if you want to run something on the Ultrasonix device then it has to be a 32-bit release. I think OpticalMarkerTracker device could be enabled for the Ultrasonix WinXP embedded edition. @Sunderlandkyl could you test if OpticalMarkerTracker device works on the Ultrasonix machine?

By the way, if you don't need to use SonixGPS tracker then you can run the generic 32-bit Plus package on any computer and connect to Ultrasonix through the network.

If you need to use 64-bit Plus then you can run a separate 32-bit Plus server to get images from Ultrasonix and make it available through OpenIGTLink. There is an example configuration file for this in the repository.

**Comment by adamrankin** [comment]
Just fyi, the optical marker tracker is moderately CPU intensive (or GPU, if available). I don't know how the performance would be on a Sonix machine.

**Comment by Sunderlandkyl** [comment]
Well, there's only one way to be sure. I'll give it a try and report back when I can.

**Comment by Sunderlandkyl** [comment]
I couldn't find a webcam that worked on our Ultrasonix machine, but I built a version of Plus with both Ultrasonix and the OpticalMarkerTracker, and it was able to run.

I've enabled OpticalMarkerTracker support on the nightly Ultrasonix packages, so it should be available later today when the nightly is built.

**Comment by lassoan** [comment]
This should work in latest development snapshots. Please reopen if it does not work as expected.
