### ISSUE TITLE
 vtkFreehandCalibrationOPEIOptimizationMethodTest Fails

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#212]
http://perkdata.cs.queensu.ca/CDash/testDetails.php?test=1533129&build=81520

- Update baseline.

**Comment by Sunderlandkyl** [comment]
@lassoan Something that I noticed is that the test fails on Windows, but passes on Mac/Linux.
In the event that updating the baseline breaks the test on Mac/Linux, should I update the test threshold so that it passes on those platforms?

The alternative would be to update the threshold on Windows and leave the baseline where it is.

**Comment by lassoan** [comment]
Windows is our main platform. It would be better to compute the baselines on Windows and adjust thresholds on other platforms.

**Comment by Sunderlandkyl** [comment]
Will close after there are no failures in the next nightly build.
