### ISSUE TITLE
Adding support for building OptiTrack using PLTools

### ISSUE THREAD

**Issue by markasselin** [PlusToolkit/PlusLib#214]

**Comment by markasselin** [comment]
@Sunderlandkyl Could you please add this to the tasks for Plus 2.5

**Comment by Sunderlandkyl** [comment]
@markasselin When do you plan to work on this?

**Comment by markasselin** [comment]
@Sunderlandkyl I will be completing it this weekend so that it can be included in the stable PLUS 2.5 release.

**Comment by lassoan** [comment]
Thanks @markasselin. I've merged the pull request, tested it on my computer, and build was successfully completed.
