### ISSUE TITLE
Stylus calibration calibrate and show result during calibration

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#217]
_From @Sunderlandkyl on September 21, 2017 15:19_

Stylus calibration could calibrate in course of the calibration process and show preminilary results from time to time (eg. every 10 acquired points), similarly like in phantom registration

Migrated from https://app.assembla.com/spaces/plus/tickets/475/details

_Copied from original issue: PlusToolkit/PlusApp#10_

**Comment by lassoan** [comment]
Stylus calibration is a short (5-15sec) process. Showing preliminary results would not likely to have any effect on how the calibration goes.
