### ISSUE TITLE
Communication with NDI Certus tracker randomly breaks

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#219]
_From @Sunderlandkyl on September 21, 2017 15:24_

After a period of approximately 1 hour, the NDI ceases communication with the host.

Tested on an NDI Certus with fCal build 1892.

Migrated from https://app.assembla.com/spaces/plus/tickets/546/details

_Copied from original issue: PlusToolkit/PlusApp#12_

**Comment by lassoan** [comment]
NDI Certus tracker is not used commonly in clinical practice (NDI Polaris trackers are used clinically by both Medtronic and BrainLab). Robustness issues are inconvenient but tolerable in laboratory experiments. Therefore, fixing this issue is low priority.

**Comment by lassoan** [comment]
No requests have been coming in for NDI Certus support for many years, therefore closing the issue.
