### ISSUE TITLE
Add visualization of line segmentation results to fCal

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#222]
_From @Sunderlandkyl on September 21, 2017 15:52_

Live update of segmentation results to see if the line can be segmented. Perhaps similar to segmentation parameter dialog? Or maybe make seg dialog do both jobs?

Migrated from https://app.assembla.com/spaces/plus/tickets/780/details

_Copied from original issue: PlusToolkit/PlusApp#15_

**Comment by lassoan** [comment]
As far as I remember, this has been implemented. @Sunderlandkyl Could you please check if this has been implemented already? If not then put it into Plus-Future.

**Comment by adamrankin** [comment]
Yes, implemented and if I may say, very helpful.
