### ISSUE TITLE
Revise the new Sikuli capabilities and switch to QtTesting framework if needed

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#225]
_From @Sunderlandkyl on September 21, 2017 17:53_

Note: Sikuli has been revived (got some funding and new owners), so before ditching it, we should wait for a release and try it.

We need to find a substitute for Sikuli for automated GUI testing, and QtTesting seems to be the best candidate (Slicer community also uses this one).

Tests need to be created for the same tasks that we cover with Sikuli at the moment.
If QtTesting proves to be a good solution for the automated tests, we can remove the Sikuli tests once we have the QtTesting variant.

Edit: QtTesting is a viable candidate as demonstrated by the IGSIO/OpenIGTLinkIO project!

Migrated from https://app.assembla.com/spaces/plus/tickets/614/details

_Copied from original issue: PlusToolkit/PlusApp#18_

**Comment by Sunderlandkyl** [comment]
2016-07-13 12:44
Adam Rankin
Reclassifying as a bug as currently UI tests do not work.

2016-07-13 14:13
Adam Rankin
http://doc.qt.io/qt-5/qttestlib-tutorial3-example.html
http://stackoverflow.com/questions/4753845/build-qt-tests-with-cmake

2016-08-28 16:17
Adam Rankin
re #614 Preparing for transition to QTest
Committed to: plus
Cleaning up PlusApp CMake files

Applying formatting changes to PlusApp code
In plus:4840

2016-08-28 16:20
Adam Rankin
re #614 removing Sikuli from PlusLib
Committed to: plus
In plus:4841

2016-08-28 17:40
Adam Rankin
re #614 reverting to non-smart pointer logic, memory management is already handled
Committed to: plus
In plus:4842

2016-08-28 22:55
Adam Rankin
re #614 Removing last remnants of Sikuli infrastructure
Committed to: plus
Creating empty Qt test for ToolStateDisplayWidgetTest and SegmentationParameterDialogTest
In plus:4843

2016-08-28 22:59
Adam Rankin
re #614 correcting auto-fail test
Committed to: plus
In plus:4844

**Comment by lassoan** [comment]
It is unlikely that we will invest into improving GUI support within Plus (and instead implement application GUI in 3D Slicer; or in Python - communicating with Plus via pyigtl). Therefore, we will not expand automated GUI testing capabilities.
