### ISSUE TITLE
Add documentation page for ApplicationEnhanceUsTrpSequence to Documentation/Tools.dox

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#229]
_From @Sunderlandkyl on September 21, 2017 18:10_

(No description)

Migrated from https://app.assembla.com/spaces/plus/tickets/1199/details

_Copied from original issue: PlusToolkit/PlusApp#22_

**Comment by Sunderlandkyl** [comment]
2017-05-16 14:53
Ben Church
re #1199: Added line to create doxygen documentation subpage for ApplicationEnhanceUsTrpSequence (#1198)

Branch: master
Commit: plus.2:63b4b34b5d

2017-05-16 14:53
Adam Rankin
Merge pull request #7 from BenChurch/master

re #1199: Added line to create doxygen documentation subpage for Appl…

Branch: master
Commit: plus.2:00b45ab54c

**Comment by Sunderlandkyl** [comment]
@lassoan Since the page in question exists at: http://perk-software.cs.queensu.ca/plus/doc/nightly/user/ApplicationEnhanceUsTrpSequence.html, can this issue be closed, or assigned to a different milestone?

**Comment by lassoan** [comment]
This page looks OK but I don't find the device listed on the devices page and a description of the XML attributes.
