### ISSUE TITLE
Is it possible to build the PlubApp without PlusBuild?

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#230]
_From @carlos-luque on October 6, 2017 12:20_

I am trying to build PlusApp linking to precompiled libraries instead of the PlusBuild ones.  I have two doubts:

1. Why does cmake request about VTK_DIR, ITK_DIR, OpenIGTLinkIO_DIR, and OpenCV_DIR? when I set up the path for the OpenIGTLinkIO_DIR, the cmake warns that the variables were already defined. This is the error message I get: 
`CMake Error at ···· openIGTlinkIO/lib/cmake/igtlio/OpenIGTLinkIOTargets.cmake:34 (message):
Some (but not all) targets in this export set were already defined.
  Targets Defined: igtlioConverter;igtlioDevices;igtlioLogic
  Targets not yet defined: igtlioTools`
2. Why do I need to link these libraries to PlusApp, when PlusLib already does it?

I appreciate some guidances.

_Copied from original issue: PlusToolkit/PlusApp#24_

**Comment by Sunderlandkyl** [comment]
_From @lassoan on October 6, 2017 12:37_

Of course it is possible to build PlusApp without PlusBuild, but you then have to do all the build steps manually (checkout and build required libraries and configure PlusApp to find them). If you have any doubts what PlusApp needs, just build using PlusBuild first and see what it builds. You can find in External_PlusApp.cmake all the information that are passed to the PlusApp build.

**Comment by Sunderlandkyl** [comment]
_From @adamrankin on October 6, 2017 13:16_

I will try to build openigtlinkio to make sure the cmake logic is correctly done for out-of-tree builds

**Comment by Sunderlandkyl** [comment]
_From @adamrankin on October 6, 2017 13:34_

PlusBuild CMake uses the _DIR variables as the location of the build folders for the various libraries. If you want to use PlusBuild to build some libraries, but use some of your own, then you could set (for example) VTK_DIR to use your own VTK, but have PlusBuild build everything else (it will pass your VTK to all the other projects as well).

**Comment by Sunderlandkyl** [comment]
_From @carlos-luque on October 6, 2017 14:22_

Thanks a lot for your answers.

Unfortunately, I have already tried these solutions. I set up the _DIR variables in the PlusApp Cmake. These variables are VTK_DIR, ITK_DIR and PlusLib_DIR and they reference to successfully compiled libraries (VTK, ITK, and PlusLib).
Cmake warns the following messages:

`CMake Warning at CPackConfig.cmake:105 (MESSAGE):
  Unable to set OpenIGTLinkIO_DIR for package generation!
Call Stack (most recent call first):
  CMakeLists.txt:196 (INCLUDE)`

`CMake Warning at CPackConfig.cmake:115 (MESSAGE):
  Unable to set OpenCV_DIR for package generation!
Call Stack (most recent call first):
  CMakeLists.txt:196 (INCLUDE)`

When I run the command line _make_, I have the following error:

`/PlusApp/PlusServerLauncher/PlusServerLauncherMainWindow.h:17:10: fatal error: igtlioLogic.h: No existe el archivo o el directorio
 #include <igtlioLogic.h>
compilation terminated.
`

If I set up the variable OpenIGTLinkIO_DIR in PlusApp CMake, the cmake shows the message:

`CMake Error at ···· openIGTlinkIO/lib/cmake/igtlio/OpenIGTLinkIOTargets.cmake:34 (message): Some (but not all) targets in this export set were already defined. Targets Defined: igtlioConverter;igtlioDevices;igtlioLogic Targets not yet defined: igtlioTools` 

I am working on it. Any suggestion will be welcome.

**Comment by Sunderlandkyl** [comment]
_From @adamrankin on October 6, 2017 14:24_

Linux?

**Comment by Sunderlandkyl** [comment]
_From @carlos-luque on October 6, 2017 14:25_

Yes, I am working in Linux.

**Comment by Sunderlandkyl** [comment]
_From @adamrankin on October 6, 2017 14:28_

So, OpenIGTLinkIO_DIR is not required by PlusApp. Did you mean PlusLib?

**Comment by Sunderlandkyl** [comment]
_From @carlos-luque on October 6, 2017 14:35_

No, I didn't. I have compiled PlusLib succesfully. Now I am trying to compile **_PlusApp_** and cmake asks not only PlusLib (PlusLib_DIR), but also VTK_DIR, ITK_DIR, and so on.

**Comment by Sunderlandkyl** [comment]
_From @adamrankin on October 6, 2017 14:36_

Could you upload your PlusLibConfig.cmake referred to in your PlusLib_DIR folder?

**Comment by Sunderlandkyl** [comment]
_From @adamrankin on October 6, 2017 14:37_

(OpenIGTLinkIO_DIR is required transitively, but should be transparent if PlusLib is configured/built as we think it should be).

**Comment by Sunderlandkyl** [comment]
_From @carlos-luque on October 6, 2017 14:43_

This is the file. The dummy extension txt is due to supported files. 
 
[PlusLibConfig .cmake.txt](https://github.com/PlusToolkit/PlusApp/files/1363009/PlusLibConfig.cmake.txt)

**Comment by Sunderlandkyl** [comment]
_From @adamrankin on October 6, 2017 14:46_

and in PlusApp, you have no manually set an OpenIGTLinkIO_DIR, correct?

Could you upload OpenIGTLinkIOConfig.cmake from 
`/opt/home/cluque/local/software/openIGTlinkIO/lib/cmake/igtlio`
or the directory you've specified in OpenIGTLinkIO_DIR (if applicable)

**Comment by Sunderlandkyl** [comment]
_From @carlos-luque on October 6, 2017 14:52_

I manually set up OpenIGTLinkIO_DIR. 

[OpenIGTLinkIOConfig.cmake.txt](https://github.com/PlusToolkit/PlusApp/files/1363032/OpenIGTLinkIOConfig.cmake.txt)

**Comment by Sunderlandkyl** [comment]
_From @adamrankin on October 6, 2017 14:56_

Ok, PlusLib should be responsible for managing OpenIGTLinkIO_DIR.

Could you remove the override from PlusApp?

Also, are any of the libraries installed via a package manager? Or are all dependencies built?

**Comment by Sunderlandkyl** [comment]
_From @carlos-luque on October 6, 2017 15:10_

I built all dependencies. 

If I remove OpenIGTLinkIO_DIR from PlusApp Cmake, then I get the warning
`CMake Warning at CPackConfig.cmake:105 (MESSAGE): Unable to set OpenIGTLinkIO_DIR for package generation! Call Stack (most recent call first): CMakeLists.txt:196 (INCLUDE)`

**Comment by Sunderlandkyl** [comment]
_From @adamrankin on October 6, 2017 15:15_

Does the folder
`/opt/home/cluque/local/software/openIGTlinkIO/lib/cmake/igtlio`
exist?

**Comment by Sunderlandkyl** [comment]
_From @carlos-luque on October 6, 2017 15:23_

Yes, but I have to check a few more things, and I will be back to you on Monday. 
Thanks for much.

**Comment by Sunderlandkyl** [comment]
_From @carlos-luque on October 9, 2017 14:56_

Finally, I could build the PlusApp, because I switched the folder _-prefix_ to the folder _-bin_.  The issue was that the variables _OpenIGTLinkIO_DIR_ and _OpenCV_DIR_ in PlusLib had not be set up correctly. 

I cannot understand why the PLusApp requests the VTK and ITK libraries if they are defined by PlusLib.

**Comment by Sunderlandkyl** [comment]
_From @adamrankin on October 9, 2017 15:28_

They don't. It calls FindPackage(PlusLib) followed by Include(${PLUSLIB_USE_FILE} which establishes all of its dependencies.

**Comment by Sunderlandkyl** [comment]
_From @carlos-luque on October 9, 2017 15:41_

I have checked it in the file PlusLibConfig.cmake (attached). I think that the variables are properly defined. 
[PlusLibConfig.cmake.txt](https://github.com/PlusToolkit/PlusApp/files/1369049/PlusLibConfig.cmake.txt)

Do you think it is correct configuration?

**Comment by Sunderlandkyl** [comment]
_From @adamrankin on October 9, 2017 16:12_

It's autogenerated based on the inputs you give PlusLib. If you're able to build PlusLib, then you should be able to build PlusApp.

**Comment by Sunderlandkyl** [comment]
_From @adamrankin on October 9, 2017 16:14_

I believe if you had given a -prefix dir to PlusLib, it would not have built.

**Comment by Sunderlandkyl** [comment]
_From @carlos-luque on October 10, 2017 11:35_

Finally, both libraries (PlusApp and PlusLib) were built. I can execute fcal, PlusServerLauncher, and  DiagnosticTool. 

Thanks for your time.

**Comment by Sunderlandkyl** [comment]
_From @adamrankin on October 10, 2017 12:16_

No problem, sorry it didn't go smoothly. I admit we rarely have people build the supporting libraries independently.

**Comment by lassoan** [comment]
Closing this now. Please reopen if you have further questions related to this topic.
