### ISSUE TITLE
MSVC / Ninja Build

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#231]
_From @Sunderlandkyl on September 21, 2017 16:13_

Build/test with the CMake Ninja with MSVC.

Migrated from https://app.assembla.com/spaces/plus/tickets/891/details

_Copied from original issue: PlusToolkit/PlusBuild#10_

**Comment by Sunderlandkyl** [comment]
2014-05-26 22:45
Matt McCormick
re #891: Pass CMAKE_BUILD_TYPE with MSVC / Ninja
Committed to: plus
Redefine ep_common_args, which had been abandoned for
PlusLib, OpenIGTLink, PlusApp, VTK, ITK PlusBuild's.
In plus:3328

2014-05-26 22:51
Matt McCormick
re #891: PlusLib does not assume VS output paths.
Committed to: plus
MSVC / Ninja does not have Release in TEST_OUTPUT_PATH.

Use TARGET_FILE CMake generator expression in ADD_TEST commands.
In plus:3329

2014-05-27 00:53
Matt McCormick
re #891: BuildAndTest.bat needs build configuration.
Committed to: plus
So CMake is aware of the build directories.
In plus:3331

2014-05-27 23:02
Matt McCormick
re #891: Use BUILD_TYPE variable for Nightly build.
Committed to: plus
As noted by @rankin.
In plus:3335

2014-09-16 15:49
Andras Lasso
re #891: Fixed BuildAndTest.bat in PlusApp for VS2012
Committed to: plus
In plus:3688

2014-09-16 16:12
Andras Lasso
re #891: Fixed BuildAndTest.bat to make sure errors are reported to the dashboard
Committed to: plus
The problem was that when the build failed then the script terminated before performing the build&test step with dashboard submission.
In plus:3689

2014-09-16 16:12
Andras Lasso
re #891: Fixed BuildAndTest.bat to make sure errors are reported to the dashboard
Committed to: plus
The problem was that when the build failed then the script terminated before performing the build&test step with dashboard submission.
In plus:3690

**Comment by adamrankin** [comment]
Re-open if desired.
