### ISSUE TITLE
RelWithDebInfo is a second-class citizen

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#233]
_From @Sunderlandkyl on September 21, 2017 18:17_

RelWithDebInfo build mode lacks SEIDrv32.dll and ATC3DG.DLL. These files are present in Debug and Release folders (along with Qt's DLLs and PlusConfig.xml), in spite of me never even building in either of these modes.

Migrated from https://app.assembla.com/spaces/plus/tickets/980/details

_Copied from original issue: PlusToolkit/PlusBuild#12_

**Comment by Sunderlandkyl** [comment]
2015-04-06 20:54
Andras Lasso
DLLs are copied to bin/Debug bin/Release directories to avoid the need to use a launcher. This should be done for MinSizeRel and RelWithDebugInfo configurations, too.

As a workaround, you can copy all the DLLs in Release to RelWithDebugInfo.

2015-04-07 10:45
Andras Lasso
Note for final solution: Copying all Qt DLLs to two additional directories would waste a lot of disk space. Use a custom target/command to copy DLLs to bin. That would allow populating only those directories that the developer actually wants to use.

2015-04-09 08:25
Andras Lasso
Copy also PlusConfig.xml

2016-06-30 10:39
Adam Rankin
@dzenanz is this still a priority for you?

2016-06-30 16:08
Adam Rankin
Milestone changed from Plus-2.3.0 to Plus-2.4.0

2016-07-11 11:19
Dzenan Zukic
No, this is not a priority for me (never was). I was simply submitting it as a bug report.

2016-07-11 11:22
Adam Rankin
Ok, thanks!

2017-06-07 13:56
Dzenan Zukic
@david.kuegler833514 Can this be closed now?

**Comment by lassoan** [comment]
No response for several months - closing this now.

**Comment by adamrankin** [comment]
I know we're trying to reduce stale tickets, but this is not a bad one to move to some sort of Release-Future class, as it is mostly CMake additions that would resolve this issue, and it's mostly copy-paste of the Debug cases. It would also aid in performance optimization when needed.

Just a thought.

**Comment by lassoan** [comment]
Is the only remaining issue that all DLLs have to be copied from Release to RelWithDebugInfo (not overwriting existing ones)?

**Comment by adamrankin** [comment]
I think so, I haven't fully investigated, but I think so.

**Comment by adamrankin** [comment]
DLLs (and PDBs)

**Comment by lassoan** [comment]
OK. Let's keep this issue open and whenever somebody will work on this then we'll add details.

By the way, normally no PDB files are generated for release-mode builds, so when you copy from the Release folder, there will be only DLLs.

**Comment by dzenanz** [comment]
Qt and SDKs release builds might not have PDBs, but libraries in Plus' super-build will have them (ITK, VTK, OpenIGTLink and OpenIGTLinkIO).

**Comment by lassoan** [comment]
ITK, VTK, Openigtlink, etc. DLLs and PDBs are generated in the correct location. Only Qt and probably some device SDK DLLs has to be copied manually from Release versions.

None of the Release builds (Plus, ITK, VTK, or any third-party) has PDBs if it they are built with default Release settings in VisualStudio, as Release setting explicitly turns off generation of PDB files.

**Comment by adamrankin** [comment]
Right, duuuhhh... So only copying of Release DLLs for external libraries/SDKs.

**Comment by adamrankin** [comment]
See PR here
[https://github.com/PlusToolkit/PlusBuild/pull/21](https://github.com/PlusToolkit/PlusBuild/pull/21)

**Comment by adamrankin** [comment]
Working on PlusLib/vtkPlusDataCollection CMake now.
