### ISSUE TITLE
Update dashboard URL

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#234]
_From @Sunderlandkyl on September 21, 2017 18:21_

CDash server is moved from crunch.cs.queensu.ca to perkdata.cs.queensu.ca.
Update CDash submission URLs and documentation accordingly.
Also change PlusLib's project name from PLUS to PlusLib for consistency.

Migrated from https://app.assembla.com/spaces/plus/tickets/1215/details

_Copied from original issue: PlusToolkit/PlusBuild#13_

**Comment by Sunderlandkyl** [comment]
2017-08-03 21:07
Andras Lasso
re #1215: Updated dashboard URL

Branch: master
Commit: plus.3:d9de447eb8

2017-08-03 21:09
Andras Lasso
re #1215: Updated dashboard URL

Branch: master
Commit: plus:442c91dae8

2017-08-03 21:10
Andras Lasso
re #1215: Updated dashboard URL

Branch: master
Commit: plus.2:60626170cf

2017-08-03 21:16
Adam Rankin
Yeesss... the inconsistent naming has bugged me forever!

**Comment by lassoan** [comment]
This has probably been fixed. @Sunderlandkyl please double-check that there is no reference to the old URL (crunch.cs.queensu.ca) anywhere anymore - in source code and documentation, in any of the repositories.

**Comment by Sunderlandkyl** [comment]
I can't find any references to crunch.cs.queensu.ca in the current source code or documentation, although it still exists in the 2.4 branch.

**Comment by lassoan** [comment]
It's good then. Having it in the 2.4 branch is no problem.
