### ISSUE TITLE
CMake maintenance

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#235]
_From @Sunderlandkyl on September 21, 2017 18:24_

This ticket is used to capture all minor fixes and improvements to CMake configuration of PlusBuild/PlusApp/PlusLib

Major changes or changes specific to a current task should be submitted under their respective tickets.

Migrated from https://app.assembla.com/spaces/plus/tickets/1216/details

_Copied from original issue: PlusToolkit/PlusBuild#14_

**Comment by Sunderlandkyl** [comment]
2017-08-04 11:50
Adam Rankin
Assigned to set to Adam Rankin
re #1216 Only producing Ultrasonix SDK versions if ultrasonix is selected

(cleaning up CMake interface when configuring)

Branch: master
Commit: plus.3:9d6c2f07f5

**Comment by lassoan** [comment]
We don't require references to tickets in all cases anymore, so this ticket is no longer needed to be kept open.
