### ISSUE TITLE
Integration of Clarius Ultrasound 

### ISSUE THREAD

**Issue by prash-p** [PlusToolkit/PlusLib#240]
Does anyone have any experience with the Clarius ultrasound systems, and whether it is easy to integrate this into plus?
https://www.clarius.me/products/

**Comment by lassoan** [comment]
We have recently started discussion with them. If we can secure the grant funding that we plan to get then an interface in Plus is expected to be available in a few months.

**Comment by lassoan** [comment]
Closing this now. Please reopen if you have further questions related to this topic.
