### ISSUE TITLE
Integration of Atracsys Optical Trackers

### ISSUE THREAD

**Issue by prash-p** [PlusToolkit/PlusLib#241]
Does anyone have any experience with the Atracsys cameras (https://atracsys.com/web/eng/measurement/products_2), and knows if it is possible to integrate them with PLUS?

**Comment by lassoan** [comment]
Atracsys interface in Plus will be available in a couple of weeks.

**Comment by prash-p** [comment]
Great! Is that for a specific model or any atracsys camera?

**Comment by lassoan** [comment]
We tested it with spryTrack.

**Comment by markasselin** [comment]
@prash-p Atracsys support for spryTrack and fusionTrack trackers is complete! It will be integrated into the PLUS master branch imminently.

**Comment by prash-p** [comment]
Thanks @markasselin!

**Comment by markasselin** [comment]
@Sunderlandkyl This issue can be closed now...

**Comment by emmanuelajaero** [comment]
@prash-p  and @markasselin Is there any tutorial on how to integrate fusionTrack to PLUS. I have been searching without success

**Comment by Sunderlandkyl** [comment]
There is no tutorial. Have you tried installing [PlusApp-2.9.0.20240801-fusionTrack-Win64.exe](http://perk-software.cs.queensu.ca/plus/packages/nightly/) and running the included config file?
