### ISSUE TITLE
Change OptiTrack RunMotiveInBackground attribute

### ISSUE THREAD

**Issue by lassoan** [PlusToolkit/PlusLib#242]
RunMotiveInBackground attribute name is very confusing. What does it mean if it set to FALSE? Not running Motive? Running in the foreground? Running something else than Motive? What "background" means?

In general, a flag
- should refer to a single concept (here there are 1. running motive, 2. running in the background)
- should be always positive (background is kind of negative, sounds like suppressing something)

Recommended name: ShowMotiveGUI

Need to update code, documentation, and example config files.

**Comment by lassoan** [comment]
Don't forget to update the configuration files as well.

**Comment by lassoan** [comment]
Is there an option to start Motive with the GUI shown? If it's easy to implement then it might be useful to have all these options:
- connect to running Motive application (don't stop when PlusServer disconnects)
- start Motive with GUI (and stop when PlusServer disconnects)
- start Motive in the background (and stop when PlusServer disconnects)

**Comment by markasselin** [comment]
Config files are already updated, see [#7](https://github.com/PlusToolkit/PlusLibData/pull/7)

**Comment by markasselin** [comment]
I will take a look for an option to start motive with GUI - the only way I know of right now would be to call command prompt from inside PLUS and execute the usual <path-to-Motive>/Motive.exe command to launch an application.

**Comment by markasselin** [comment]
@lassoan It looks like the only way to start and stop Motive with GUI from PLUS would be to run it within a hidden command prompt - in my opinion this isn't the nicest solution.

**Comment by lassoan** [comment]
You can start any process from a process (no need to create a "command prompt") but if this is not a built-in feature of the SDK then let's _not_ implement it.

Can you confirm that these are the two options that we choose from by using the ShowMotiveGUI flag?
* connect to running Motive application (user starts/stops Motive manually)
* Plus starts Motive in the background on connect (and Plus stops Motive on disconnect)

**Comment by markasselin** [comment]
Yes. If the ShowMotiveGUI flag is TRUE then we will connect to a running instance of the Motive application (initiated and closed by the user). If the flag is FALSE then PLUS will start and stop Motive's processing functionality in the background.

If the user tries to run a PLUS config with ShowMotiveGUI FALSE, but Motive is already running, then the Motive API will show a warning dialog.
