### ISSUE TITLE
Adding support for OpenHaptics devices

### ISSUE THREAD

**Issue by sjh26** [PlusToolkit/PlusLib#245]
I have been working on getting the OpenHaptics libraries (http://www.geomagic.com/en/products/open-haptics/overview) working with Plus.  I have a basic working version (tracking only, no force data yet ): https://github.com/sjh26/PlusLib/commit/007e9f924dc133e91d2fc356e42d456cd2d4301b  and https://github.com/sjh26/PlusBuild/commit/8a84f595e775d80df0e2f7e8f28d0edb4569b32e

In order to have the full haptic functionality, I need to also pull velocity data from the device (single 3d vector) and push force data to it (also a single 3D vector).  Does Plus support pushing data to devices like this?

**Comment by sjh26** [comment]
@lassoan

**Comment by lassoan** [comment]
You can use an OpenIGTLink tracker device that receives transforms (4x4 double values) and use output channel is that device as input for your haptic device.

You can store any 3-element vector in the translation component (4th column) of the transformation matrix.

If you find that latency is too high then using POSITION or SENSOR message instead of TRANSFORM might help (POSITION may have been implemented already). And/or we could implement direct data sending similar to COMMAND messages.

**Comment by sjh26** [comment]
I am having trouble accessing the input channel i have created for the transform from slicer

I've configured the devices as below, as confirmed that the Slicer device is correctly transmitting data.  In my code I am using these methods to get the tool from the input channel:

vtkPlusDataSource* forceInput;
inputChannel->GetOwnerDevice()->GetToolByPortName("Force", forceInput)

This appears to work (return success), but how do I then pull the latest transform from it?
I have tried forceInput->GetLatestStreamBufferItem(item), but it always fails.

Thanks

<Device
      Id="Slicer"
      Type="OpenIGTLinkTracker"
      MessageType="TRANSFORM"
      ToolReferenceFrame="Ref"
      ServerAddress="127.0.0.1"
      ServerPort="22222"
      IgtlMessageCrcCheckEnabled="true"
      AcquisitionRate="20"
      ReconnectOnReceiveTimeout="true"
      UseReceivedTimestamps ="FALSE"
      UseLastTransformsOnReceiveTimeout ="TRUE">
      <DataSources>
        <DataSource Type="Tool" Id="Force" PortName="Force"/>
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="SlicerStream">
          <DataSource Id="Force" />
        </OutputChannel>
      </OutputChannels>
    </Device>
    <Device
      Id="NeedleTracker"
      Type="OpenHapticsDevice"
      AcquisitionRate="50"
      ToolReferenceFrame="Tracker"
      DeviceName="PLUS"  >
      <DataSources>
        <DataSource Type="Tool" Id="Stylus"  PortName="Stylus" />
      </DataSources>
      <InputChannels>
        <InputChannel Id="SlicerStream" />
      </InputChannels>
      <OutputChannels>
        <OutputChannel Id="NeedleStream">
          <DataSource Id="Stylus" />
        </OutputChannel>
      </OutputChannels>
    </Device>

**Comment by sjh26** [comment]
Nevermind!!  Got it working now

**Comment by sjh26** [comment]
I have the device fully working now (force input, stylus tracking, velocity, and button outputs).  What would be the next step towards getting this integrated?

**Comment by adamrankin** [comment]
Commit your work to github, and then make a pull request!

**Comment by adamrankin** [comment]
The SDK does not include the PhantomIOLib.dll included in the driver package, meaning an installed Plus won't work if this device is included unless they install the device driver. This may not be the end of the world, but it's definitely sub-optimal. Could you reach out to the manufacturer and find out if we can include the driver DLLs in our deployed package?

**Comment by lassoan** [comment]
> installed Plus won't work if this device is included unless they install the device driver

There are a couple of devices like this (Interson ultrasound, Thorlabs spectrometer). Often placing a missing DLL in a package is not enough - you may need to properly install a driver, register controls, etc.

So far we've been creating a new edition of Plus for each devices that require installation of some custom driver (e.g., Interson, Thorlabs), or just not have it enabled in any current editions (e.g., Capistrano). In the long term, we could address this by implementing loading of DLLs on request, when needed (https://github.com/PlusToolkit/PlusLib/issues/232).
