### ISSUE TITLE
NDI Vega active tool support

### ISSUE THREAD

**Issue by prash-p** [PlusToolkit/PlusLib#248]
On this page (http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceNDI.html), there is a config file for passive tool support with the Vega. Is there also active tool support built in with Vega (similar to Polaris?)

**Comment by adamrankin** [comment]
The Vega uses the same API as the Spectra pretty much. The only difference is the addition of a network interface. Config files for the Spectra should work with the Vega, with some tweaking.

**Comment by adamrankin** [comment]
Let me know if you need any more information.

**Comment by houssamhariri** [comment]
We're trying to connect the Polaris Vega to PLUS server using the attached config file "NDI_vega.xml". We tried it on both the Win64 and Telemed-Win32 versions of PLUS, but can't get it to connect. The log file is attached. We think the issue has to do with the IP address so we tried using the dynamic address (169.254....), we tried using a static address, and we tried playing with all the settings in the control panel and in the NDI Configure. Nothing worked so far. Note that we're using an ethernet connection directly (no switch) to the Vega, and the NDI Toolbox apps can connect to it and track without a problem. 

Do you have any recommendations on how to connect it?

[NDI_vega.txt](https://github.com/PlusToolkit/PlusLib/files/1905231/NDI_vega.txt)
[041218_144321_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/1905236/041218_144321_PlusLog.txt)

**Comment by adamrankin** [comment]
I don't think the stable (2.6.0) has Vega support. Have you tried the nightly? Also, you can remove the BaudRate attribute as it is not used for the Vega.

**Comment by houssamhariri** [comment]
I just tried the nightly and removed the baud rate. Still the same issue. I used 192.168.1.10 instead of 192.168.1.101 (like the example) for the IP address because that's what I get from the NDI configure software.  

[041218_172225_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/1905403/041218_172225_PlusLog.txt)

[NDI_vega.txt](https://github.com/PlusToolkit/PlusLib/files/1905406/NDI_vega.txt)

**Comment by adamrankin** [comment]
Just in case, is the NDI software still running when you try and connect with Plus?

**Comment by houssamhariri** [comment]
No, the NDI software wasn't running. I tried it again, just in case. Still, the same issue (log file attached). Does the Vega work with the win32 version of PLUS or does it need the win64 version? Are there any specific settings that we should set in the NDI configure software or in the control panel? 

[041318_093136_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/1908227/041318_093136_PlusLog.txt)

**Comment by adamrankin** [comment]
For the NDI device it works in both 32 and 64 bit.

Ensure you are connecting via IP (and not Bonjour) using the NDI software. There are some circumstances where the Vega does not renew its DHCP lease, in which case try unplugging and replugging the unit to reboot it.

**Comment by houssamhariri** [comment]
OK, that worked, thanks!

**Comment by adamrankin** [comment]
Great.

This is a known bug by NDI, they are aware of it and will fix it at some point I'm sure.

**Comment by lassoan** [comment]
@adamrankin Could you add a note about this known issue in the User manual? https://github.com/PlusToolkit/PlusLib/blob/master/src/Documentation/UserManual/DeviceNDI.dox Thank you!

**Comment by BKalen** [comment]
Hello,

I have been having this same issue and have followed along until "Ensure you are connecting via IP (and not Bonjour) using the NDI software" and do not know how to verify which my computer is using to connect. Any insight how I can go about looking this up?

Thanks!

**Comment by houssamhariri** [comment]
@BKalen, it's been a while so I may have forgotten some details, but here's what I remember:
1. Connect your Vega by Ethernet
2. Go into the network settings from control panel: Control Panel\Network and Internet\Network and Sharing Center
3. Click on Ethernet
4. Click properties
5. Double click IPv4
6. Set the IP address manually to something 192.168.1.10x
7. Open NDI Configure app
8. In the NDI Configure app, it will most likely be connected with a dynamic IP address (e.g. on our computer it started with 169.254)
9. Change this to Static IP in the NDI Configure app and set it to 192.168.1.10n. MAKE SURE you set n to something different than x.
10. Change the IP address in the PLUS config file to match the one you set manually. 

That worked for us, hope it works for you too.

**Comment by BKalen** [comment]
Thank you for the reply! For step 8, where in NDI configure does is show the dynamic IP? I only see the static IP under Settings and Options
