### ISSUE TITLE
Incorporate frame tracking devices in vtkPlusTransverseProcessEnhancer config

### ISSUE THREAD

**Issue by BenChurch** [PlusToolkit/PlusLib#251]
vtkPlusTransverseProcessEnhancer currently works without tracking information. Add tracking devices to PlusDeviceSet_Server_Ultrasonix_C5-2_TransverseProcessEnhancer_1ImageAcquisition.xml and PlusDeviceSet_Server_Ultrasonix_C5-2_TransverseProcessEnhancer_2Processing.xml so that frames appearing in Slicer track US probe

**Comment by adamrankin** [comment]
Reopen if desired.
