### ISSUE TITLE
Limit log file size

### ISSUE THREAD

**Issue by dzenanz** [PlusToolkit/PlusLib#256]
Is there a way to limit the size of the log file?

E.g. if a PlusServer loses connection to a device, a stream of messages is written to the log quickly (e.g. 30 times per second), making the size of the log file reach gigabyte proportions over a 24 hour period. Excerpt:
```
092817_143808.818|ERROR|067.533000| Unable to read position of second encoder with address: 3| in C:\P\Dzenan\PR17_x32\PlusLib\src\PlusDataCollection\USDigitalEncodersTracking\vtkPlusUSDigitalEncodersTracker.cxx(311)
092817_143808.853|ERROR|067.568000| Unable to read position of second encoder with address: 3| in C:\P\Dzenan\PR17_x32\PlusLib\src\PlusDataCollection\USDigitalEncodersTracking\vtkPlusUSDigitalEncodersTracker.cxx(311)
```

**Comment by adamrankin** [comment]
This is a tricky discussion. Certainly assigning an optional max size is fine, but I would strongly avoid imposing any mandatory limits.

**Comment by dzenanz** [comment]
An optional maximum size would be great. Where should that code go? Into `void vtkPlusLogger::Flush()` or somewhere else?

**Comment by adamrankin** [comment]
I don't think it will be a small change, as the fact that the log has reached its limit must be conveyed to application(s). Perhaps this is just a final log entry saying further processing is halted as limit has been reached.

In which case, there should be some logic in the logger to know whether or not to accept new log entries.

**Comment by dzenanz** [comment]
My idea was to check if log limit has been reached, and if it has call `exit()`. Letting the application know that without either exiting or silently stopping to accept new log entries seems like a big change.

A better use of time would be to add a mechanism to not repeat the exact same message constantly. For example, we could Replace `LOG_X` macros like this. Old style:
```cpp
  if (aTrackedFrameList == NULL)
  {
    LOG_ERROR("vtkPlusChannel::GetTrackedFrameListSampled failed: unable to get tracked frame list. Output tracked frame list is NULL.");
    return PLUS_FAIL;
  }
```
to this:
```cpp
  LOG_ERROR_IF(aTrackedFrameList == NULL, "vtkPlusChannel::GetTrackedFrameListSampled failed: unable to get tracked frame list. Output tracked frame list is NULL.")
```
`LOG_ERROR_IF` being something like this:
```cpp
#define LOG_ERROR_IF(condition, msg) \
  { \
  static bool lastCheck = true; \
  if (condition) \
  { \
    if (lastCheck)
    { \
      LOG_ERROR(msg); \
    } \
  } \
  else \
  { \
    lastCheck = false;
  } \
  }
```
Similarly for other logging levels.

**Comment by lassoan** [comment]
I agree with Adam that such logging is an error. We have a policy (I think we even described it somewhere in logging guidelines) that continuous logging is only allowed at TRACE level. If a connection breaks, you log once (at ERROR or WARNING level), when it happened, and may log again when it is restored (probably at INFO level).
