### ISSUE TITLE
Plus Server Debug Build in VS2010

### ISSUE THREAD

**Issue by purav70** [PlusToolkit/PlusLib#260]
We ran into a problem building the debug version of Plus in VS2010, where PlusApp specifically would not build. The error we ran into was cmake being unable to find the Qt config files. It turns out the problem lies in this line of code, in PlusApp/InstallFiles.cmake

216    IF(${_config} STREQUAL RELEASE OR ${_config} STREQUAL NOCONFIG)
 
Code following this wouldn't run as it is looking for a release version of noconfig version (not sure what this is). However, building in debug, it wouldn't be able to find a release version. Therefore, we modified this line to and it solves the issue.

IF(${_config} STREQUAL RELEASE OR ${_config} STREQUAL NOCONFIG OR ${_config} STREQUAL DEBUG)

**Comment by lassoan** [comment]
I think this change would add Qt debug files to the installation package, which would just increase the package size but would not be used.

Building Qt in release mode or release&debug mode should solve the problem without any change in Plus.

**Comment by dzenanz** [comment]
@purav70 Can this issue be closed?
