### ISSUE TITLE
Create new stable release - Plus 2.6

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#268]
Tasks:
--

- [x] PlusBuild
  - [x] Create stable branch
  - [x] Update default GIT_TAG for stable branches
    - [x] PLUSLIB_GIT_REVISION
    - [x] PLUSAPP_GIT_REVISION
    - [x] PLUSBUILD_PLUSLIBDATA_GIT_REVISION
  - [x] Update GIT_TAG for external dependencies to use specific tags/commits

- [x] PlusLib
  - [x] Create stable branch
  - [x] Update Plus version in CMakeLists.txt

- [x] PlusApp
  - [x] Create stable branch

- [x] PlusLibData
  - [x] Create stable branch

- [x] Update dashboard scripts on ARTERY
  - [x] Nightly builds
  - [x] Continuous builds
  - [x] Packages
  - [x] Test scripts before uploading stable release

- [x] Update minor version number in the trunk to 7
- [x] Update new release checklist ([PlusBuild/Docs/NewReleaseChecklist.md](https://github.com/PlusToolkit/PlusBuild/blob/master/Docs/NewReleaseChecklist.md))

**Comment by Sunderlandkyl** [comment]
@lassoan I added all of the necessary tasks that I could think of.
Regarding this:

>  Update dependencies to use specific default tags

Is this something that should be done, (ie: using a specific commit for each dependency repo) so that new regressions aren't introduced by changes in the dependencies?

**Comment by adamrankin** [comment]
The SINTEF merge was not clean, I would recommend repeating the release procedures and testing before making the release.

**Comment by lassoan** [comment]
SINTEF changes are not included in the stable release.

**Comment by adamrankin** [comment]
https://github.com/IGSIO/OpenIGTLinkIO/pull/29

**Comment by adamrankin** [comment]
Ah, you'll use the revision before that in the release. Gotcha.

**Comment by Sunderlandkyl** [comment]
Alright, I think that's everything. Let me know if there's something I've forgotten.
