### ISSUE TITLE
OpenIGTLink v1 commands not correctly responded too

### ISSUE THREAD

**Issue by adamrankin** [PlusToolkit/PlusLib#276]
When using SlicerIGT's OpenIGTLink remote, commands receive no reply or command failed even when the command succeeded.

Investigate.

**Comment by lassoan** [comment]
PlusRemote module works in Slicer, so maybe only some commands fail to get response.

Note that when you get a CMD_NNN string command message you always has to respond with an ACK_NNN string command acknowledgment message (it is not enough to just send the requested data in a POLYDATA message).

**Comment by adamrankin** [comment]
Yes, I am noticing that the handling of v1/v2 is message dependant. It would be ideal if this handling was in the command processor.

**Comment by adamrankin** [comment]
I have improved it somewhat now, and the base vtkPlusCommand class will now switch behaviour based on this->RespondWithCommandMessage when messages call this->QueueCommandResponse

**Comment by adamrankin** [comment]
Hmm, it is handled in vtkPlusOpenIGTLinkServer::CreateIgtlMessageFromCommandResponse

Investigating why it's not working

**Comment by adamrankin** [comment]
Haha just kidding. Coder error.
