### ISSUE TITLE
position from inertial sensor

### ISSUE THREAD

**Issue by u0078867** [PlusToolkit/PlusLib#280]
Is there a way to get the position from inertial sensor data?

e.g. integrating twice (supposing x0=0, v0=0) the acceleration vector expressed in the IMU reference frame and analysing the drifts?

We might be interested in this for voxel-array reconstruction.

We could not find ourselves if this was already implemented for CHRobotics and Phidget IMU in the code, we only see calculations on orientations only.

Thanks!

**Comment by Sunderlandkyl** [comment]
I am not familiar with the inertial sensor devices. @lassoan should have a better idea of what is currently implemented.

**Comment by lassoan** [comment]
Double integration is not possible on portable sensors (noise level is so high that you get several meters of position error within a second).

Typically you reconstruct volumes using inertial sensors by pivoting or rotating the probe.
