### ISSUE TITLE
Make BK support available in release package

### ISSUE THREAD

**Issue by lassoan** [PlusToolkit/PlusLib#281]
BK interface is fully our own code, so it should be no problem making it available in public releases.

**Comment by lassoan** [comment]
@Sunderlandkyl Could you check if we can enable BK support in all packages? (check if we can build it, run it without having access to a BK scanner; does not increase the package size significantly, etc.)

**Comment by lassoan** [comment]
@Sunderlandkyl it would be great if you could quickly build a package for Win32 and post the link here so that our collaborators at CNMC can try it.

**Comment by Sunderlandkyl** [comment]
[Here's a link to the 32 bit build. I'll upload a 64-bit build shortly.](https://www.dropbox.com/sh/sges20yj8ywzbeq/AAAwxTcNuvAjqG5UJOlS20NYa?dl=0)

It runs on my computer without a BK scanner, and doesn't seem to increase the package size by much, so we could probably enable it for all of the packages.

**Comment by Sunderlandkyl** [comment]
I'll wait until we hear that the BK support works well (https://github.com/PlusToolkit/PlusLib/issues/285) before enabling it on the nightly (and I assume, stable) builds.

**Comment by Sunderlandkyl** [comment]
@lassoan originally I was going to wait until I heard that the BK support enabled packages worked.  Do you want me to go ahead and enable support on the Nightly builds anyways (except the Ultrasonix)?

**Comment by lassoan** [comment]
Yes, I think we can enable that now so that people can test it.
