### ISSUE TITLE
How can I define the paths of the PLusLib and PlusApp in PlusBuild? 

### ISSUE THREAD

**Issue by carlos-luque** [PlusToolkit/PlusLib#287]
Hello, 

I cloned the repository PLusLib, PlusApp and PlusBuild and made some code changes in PlusLib and PlusBuild. I would  like to test the changes are correct in both libraries, but I cannot find the way to pass the paths of the PlusLib and PlusApp to the PlusBuild that compiles that libraries.

The PlusBuild defines the default paths for the library contents :
- PlusLib: ${CMAKE_BINARY_DIR}/PlusLib
- PlusApp: ${CMAKE_BINARY_DIR}/PlusApp

Those paths can't be changed from PlusBuild. Is there any way to define the other paths in PlusBuild? or how can I connect all libraries with different paths than default ones? 

Thanks in advances

**Comment by adamrankin** [comment]
PlusBuild downloads and compiles PlusLib and PlusApp, and so we put them in hardcoded directories (as you've stated).

Our typical work flow is to modify the cloned folders <PlusBuild binary dir>/PlusLib and use those as our git repositories.

My suggestion would be to overwrite <PlusBuild binary dir>/PlusLib with your external copy.

**Comment by carlos-luque** [comment]
Thanks for your reply.

**Comment by adamrankin** [comment]
Let me know if this solution doesn't work for you.

**Comment by carlos-luque** [comment]
The solution works. 
Thanks.
