### ISSUE TITLE
The widgets are not built in Windows

### ISSUE THREAD

**Issue by carlos-luque** [PlusToolkit/PlusLib#289]
Hello, 

   I am trying to build Plus toolkit (with Qt5.7 and Qt5.9.2) in Windows, but I have the same errors as both Qt versions:

`Error	2356	error C1083: Cannot open include file: 'ui_QPlusDeviceSetSelectorWidget.h': No such file or directory [D:\PlusBBin57\PlusApp-bin\PlusServerLauncher\PlusServerLauncher.vcxproj]	D:\PlusBBin57\PlusLib\src\PlusWidgets\QPlusDeviceSetSelectorWidget.h	13	1	PlusApp
Error	2357	error C1083: Cannot open include file: 'ui_QPlusConfigFileSaverDialog.h': No such file or directory [D:\PlusBBin57\PlusApp-bin\fCal\fCal.vcxproj]	D:\PlusBBin57\PlusLib\src\PlusWidgets\QPlusConfigFileSaverDialog.h	13	1	PlusApp
Error	2358	error C1083: Cannot open include file: 'ui_QPlusConfigFileSaverDialog.h': No such file or directory [D:\PlusBBin57\PlusApp-bin\fCal\fCal.vcxproj]	D:\PlusBBin57\PlusLib\src\PlusWidgets\QPlusConfigFileSaverDialog.h	13	1	PlusApp
Error	2359	error C1083: Cannot open include file: 'ui_QPlusDeviceSetSelectorWidget.h': No such file or directory [D:\PlusBBin57\PlusApp-bin\fCal\fCal.vcxproj]	D:\PlusBBin57\PlusLib\src\PlusWidgets\QPlusDeviceSetSelectorWidget.h	13	1	PlusApp
Error	2364	error C1083: Cannot open include file: 'ui_QPlusDeviceSetSelectorWidget.h': No such file or directory [D:\PlusBBin57\PlusApp-bin\PlusServerLauncher\PlusServerLauncher.vcxproj]	D:\PlusBBin57\PlusLib\src\PlusWidgets\QPlusDeviceSetSelectorWidget.h	13	1	PlusApp
Error	2365	error C1083: Cannot open include file: 'ui_QPlusConfigFileSaverDialog.h': No such file or directory [D:\PlusBBin57\PlusApp-bin\fCal\fCal.vcxproj]	D:\PlusBBin57\PlusLib\src\PlusWidgets\QPlusConfigFileSaverDialog.h	13	1	PlusApp
Error	2366	error C1083: Cannot open include file: 'ui_QPlusConfigFileSaverDialog.h': No such file or directory [D:\PlusBBin57\PlusApp-bin\fCal\fCal.vcxproj]	D:\PlusBBin57\PlusLib\src\PlusWidgets\QPlusConfigFileSaverDialog.h	13	1	PlusApp
Error	2367	error C1083: Cannot open include file: 'ui_QPlusDeviceSetSelectorWidget.h': No such file or directory [D:\PlusBBin57\PlusApp-bin\fCal\fCal.vcxproj]	D:\PlusBBin57\PlusLib\src\PlusWidgets\QPlusDeviceSetSelectorWidget.h	13	1	PlusApp
`
 My environment setup is:
- Windows 8
- Visual Studio 2013
- Qt 5.7 and Qt 5.9.2 
- Latest PlusBuild  (PlusLib and PlusApp version is master)
- PLUSLIB_WIDGET is true

How can I fix those errors?

**Comment by adamrankin** [comment]
What version of CMake?

**Comment by adamrankin** [comment]
@markasselin Could this be related to #283 ?

**Comment by markasselin** [comment]
@carlos-luque Which version of CMake are you using?

**Comment by adamrankin** [comment]
@markasselin Same with 3.9.2 (VS2015, which I'm pretty sure will not affect this issue, & Win 10, and Qt 5.9.1)

**Comment by markasselin** [comment]
@adamrankin I'm using VS2013 with Qt5.9.1. Everything built fine for CMake 3.7.2, but for CMake 3.10.0 I have to run the build again and it succeeds the second time. 

What behavior would I notice if widgets didn't build correctly?

**Comment by adamrankin** [comment]
Build errors in PlusLib.

If the errors are in PlusApp, then it's probably a problem of PLUSLIB_INCLUDE_DIRS.

What happens with 3.10.0 the first time?

**Comment by markasselin** [comment]
The first time I get the same error as @carlos-luque. After rebuilding PlusLib build a-ok.

**Comment by adamrankin** [comment]
Same, are you able to identify why it doesn't succeed first time?

**Comment by markasselin** [comment]
I un-intelligently rebuilt without saving the build log from the first built, so I'm now waiting for a clean build to run.

**Comment by carlos-luque** [comment]
The cmake version is 3.9.7.  I have all log files if necessary. If you tell me what files you need, I can send them to you by email.

**Comment by adamrankin** [comment]
We've been able to reproduce your issue, and I think @markasselin is going to look into it. If so Mark, could you assign yourself? If not, let me know and I'll see if Andras is available.

**Comment by lassoan** [comment]
I won't be able to work on this for at least a couple of days.

**Comment by carlos-luque** [comment]
Great, I'll use another cmake version. Is the version 3.7.2 OK?.

**Comment by adamrankin** [comment]
I guess so, the issue occured for me in 3.9.4

**Comment by markasselin** [comment]
@carlos-luque Everything builds ok for me in 3.7.2. Or, try running the CMake 3.10.0 build twice - this succeeded for me. It fails the first time, then when the build is run a second time it succeeds. I've had no problems after that.

@lassoan @adamrankin I'm investigating, in the meantime we should remove commit 64bf672d79 from PlusLib master so that building works as expected for all CMake versions except 3.10.0.

**Comment by carlos-luque** [comment]
Thank all for your messages. 

The cmake version 3.7.2 works in my environment setup. I could build the Plus toolkit with Qt 5.9.2.
 I'm curious about it.

**Comment by markasselin** [comment]
@lassoan @adamrankin PR #294 fixes this issue

**Comment by markasselin** [comment]
@carlos-luque Everything should be fixed now for you to build with 3.10.0 successfully. Thank you for bringing this issue to our attention!

**Comment by carlos-luque** [comment]
@markasselin  you're welcome, thanks for replying quickly
