### ISSUE TITLE
PlusApp-StealthLink

### ISSUE THREAD

**Issue by remidel** [PlusToolkit/PlusLib#292]
Hi,

I would like to use the PlusApp-Stealthlink package to connect the Medtronic Stealthstation with Slicer but the zip file is protected by a password. Do you know how could I have access to the package ?

Thank you

**Comment by adamrankin** [comment]
Could one of the Queen's group let him know?

**Comment by lassoan** [comment]
Do you have license from Medtronic to access your StealthStation through StealthLink? If yes, then please contact me at lasso@queensu.ca for the password.
