### ISSUE TITLE
On-line user manual is not searchable

### ISSUE THREAD

**Issue by lassoan** [PlusToolkit/PlusLib#298]
Search box is not available in user manual (http://perk-software.cs.queensu.ca/plus/doc/nightly/user/index.html). This makes it very difficult to find information.

User manual should be build with server-side indexing enabled in CMake.

**Comment by Sunderlandkyl** [comment]
Search box should be available now in user documentation.

**Comment by adamrankin** [comment]
Will confirm tomorrow. (unless you can manually push the docs to the server?)

**Comment by Sunderlandkyl** [comment]
Already did.

**Comment by Sunderlandkyl** [comment]
* Clarification, i just manually enabled the argument in PlusApp, I didn't test the cmake change.

**Comment by adamrankin** [comment]
Ah ok, want to verify the whole chain.

**Comment by Sunderlandkyl** [comment]
Yeah, I'm going update PlusBuild on the Package PC and test now.

**Comment by Sunderlandkyl** [comment]
Had to make one more change (https://github.com/PlusToolkit/PlusBuild/commit/026bf177c1f655efc1521a1da2787d81aa0f90fe), but it works now on the nightly build machine, and user docs have been updated on the website.

**Comment by lassoan** [comment]
It works great, thank you!
