### ISSUE TITLE
Static libraries broken, again

### ISSUE THREAD

**Issue by dzenanz** [PlusToolkit/PlusLib#304]
The error messages are below. This set of link errors repeats a few times in build of PlusLib.
```
vtkPlusServer.lib(vtkPlusSetUsParameterCommand.obj) : error LNK2001: unresolved external symbol "public: virtual class vtkPlusCommand * __thiscall vtkPlusSetUsParameterCommand::Clone(void)" (?Clone@vtkPlusSetUsParameterCommand@@UAEPAVvtkPlusCommand@@XZ)
vtkPlusServer.lib(vtkPlusSetUsParameterCommand.obj) : error LNK2001: unresolved external symbol "protected: virtual char const * __thiscall vtkPlusSetUsParameterCommand::GetClassNameInternal(void)const " (?GetClassNameInternal@vtkPlusSetUsParameterCommand@@MBEPBDXZ)
vtkPlusServer.lib(vtkPlusSetUsParameterCommand.obj) : error LNK2001: unresolved external symbol "public: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall vtkPlusSetUsParameterCommand::GetUsDeviceId(void)const " (?GetUsDeviceId@vtkPlusSetUsParameterCommand@@UBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)
vtkPlusServer.lib(vtkPlusSetUsParameterCommand.obj) : error LNK2001: unresolved external symbol "public: virtual int __thiscall vtkPlusSetUsParameterCommand::IsA(char const *)" (?IsA@vtkPlusSetUsParameterCommand@@UAEHPBD@Z)
vtkPlusServer.lib(vtkPlusSetUsParameterCommand.obj) : error LNK2001: unresolved external symbol "protected: virtual class vtkObjectBase * __thiscall vtkPlusSetUsParameterCommand::NewInstanceInternal(void)const " (?NewInstanceInternal@vtkPlusSetUsParameterCommand@@MBEPAVvtkObjectBase@@XZ)
vtkPlusServer.lib(vtkPlusSetUsParameterCommand.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall vtkPlusSetUsParameterCommand::SetUsDeviceId(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?SetUsDeviceId@vtkPlusSetUsParameterCommand@@UAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
vtkPlusServer.lib(vtkPlusSetUsParameterCommand.obj) : error LNK2001: unresolved external symbol "public: virtual void __thiscall vtkPlusSetUsParameterCommand::SetUsDeviceId(char const *)" (?SetUsDeviceId@vtkPlusSetUsParameterCommand@@UAEXPBD@Z)
vtkPlusServer.lib(vtkPlusSetUsParameterCommand.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) const vtkPlusSetUsParameterCommand::`vftable'" (__imp_??_7vtkPlusSetUsParameterCommand@@6B@) referenced in function "protected: __thiscall vtkPlusSetUsParameterCommand::vtkPlusSetUsParameterCommand(void)" (??0vtkPlusSetUsParameterCommand@@IAE@XZ)
```

**Comment by dzenanz** [comment]
Are there instructions on how to set up a nightly build for the [dashboard](http://perkdata.cs.queensu.ca/CDash/index.php?project=PlusLib)? Are there special permissions needed for that? I am willing to use my machine to do nightly builds of PlusLib.

**Comment by adamrankin** [comment]
No special permission needed. We provide convenience scripts BuildAndTest.sh -N (BuildAndTest.bat -N on Windows).

**Comment by adamrankin** [comment]
I also highly encourage the use of a build suffix if you are going to do a nightly static build. It's one of the options in PlusBuild (and PlusLib)

**Comment by dzenanz** [comment]
There is a `BUILDNAME` _vs14x86-Windows-6.1.7601_, but I could not find a suffix, only install prefix :smile: 
I have manually started a `BuildAndTest.bat -N` for PlusLib now, and scheduled one nightly for 21:14 ET.

**Comment by dzenanz** [comment]
The first run finished, build results are available [here](http://perkdata.cs.queensu.ca/CDash/buildSummary.php?buildid=85931).

**Comment by adamrankin** [comment]
PLUSBUILD_BUILDNAME_POSTFIX, sorry.

**Comment by dzenanz** [comment]
Ah, that is only defined in PlusBuild, not PlusLib. I will create a new build then, exclusively for nightly testing.

**Comment by dzenanz** [comment]
Here is a [build](http://perkdata.cs.queensu.ca/CDash/buildSummary.php?buildid=86405) which is currently on the dashboard. It shows the errors static libraries build gets into.

**Comment by lassoan** [comment]
@Sunderlandkyl Could you please help with this?

1. We need to fix the build error. Probably moving implementation of vtkPlusCommand* Clone() from the header to the cxx file will solve the problem.

2. To catch such build errors earlier, we need to add a **static** build configuration of Plus on ARTERY, for both stable and master branch.

**Comment by Sunderlandkyl** [comment]
@lassoan Sure, I'll take a look at it.

**Comment by adamrankin** [comment]
Ew.

PlusLib_STATIC defined in PlusConfigure.h (generated in CMake)
If in body, PlusConfigure is included after header, PlusLib_STATIC is not yet defined, thus the vtkPlusServerExport macro is not correct for the library type.

Fixed by moving PlusConfigure before class header file in body.

@lassoan move to `target_compile_definitions`?

**Comment by adamrankin** [comment]
@lassoan or update export file template to #include <PlusConfigure.h> in the export file so that preprocessor defines are gauranteed to be present?

**Comment by lassoan** [comment]
It's described in the coding rules that PlusConfigure.h may be the first include in all cxx files (not only because of PlusLib_STATIC define but for other reasons, too). It would be nice if we could enforce it better than just documentation. 

If we put the header into the export file template then we would still need to make sure that the export header file is included first, so it would not help much.

I think adding one a static build configuration to the dashboard would be an effective measure to at least detect the issue (in some cases).

**Comment by Sunderlandkyl** [comment]
@lassoan The static builds have been setup on ARTERY, they should start reporting tomorrow.

**Comment by lassoan** [comment]
Perfect, thank you!
