### ISSUE TITLE
Error in build instructions for Linux

### ISSUE THREAD

**Issue by leb** [PlusToolkit/PlusLib#305]
In the [build instructions for Linux](https://github.com/PlusToolkit/PlusBuild/blob/master/Docs/BuildInstructionsLinux.md), it says that "Qt entry should read as /some/qt-install-dir/bin/qmake". However, I believe it should read something like /some/qt-install-dir/lib/cmake/Qt5. (This is probably obvious to those experienced with cmake, but some of us are not.)

**Comment by Sunderlandkyl** [comment]
Thanks for finding this! It should be fixed now. Let us know if you find any other issues with the documentation.
