### ISSUE TITLE
Docs out of sync

### ISSUE THREAD

**Issue by dzenanz** [PlusToolkit/PlusLib#306]
I had a [branch](https://github.com/dzenanz/PlusLib/tree/winprobeRF) in my repo with a lot of changes. [Merging](https://github.com/dzenanz/PlusLib/tree/wpRF) current master required a lot of manual conflict resolution. I am now trying to use AStyle to format the resulting file, but the format given in this [document](https://github.com/PlusToolkit/PlusBuild/blob/master/Docs/BuildInstructionsWindows.md) does not seem complete: the styler adds two spaces between code and `//comments`, whereas there was only one space before. I looked at the options in AStyle Visual Studio extension, and could not see an option which would affect that. Am I doing something wrong, or is the documentation slightly out of date?

Just underneath in the same [document](https://github.com/PlusToolkit/PlusBuild/blob/master/Docs/BuildInstructionsWindows.md), DoxygenComments links to a VS extension version which only works in VS2013. Is there an updated extension which does the same job, e.g. [this](https://marketplace.visualstudio.com/items?itemName=StaughtonCoding.OneClickDocs)?

**Comment by lassoan** [comment]
If I understand correctly, the question is about what code formatting style we should use.

Since VTK adopted sensible bracing indentation and method documentation style, we could consider switching to latest VTK style. What do you think? @adamrankin @cpinter @Sunderlandkyl

**Comment by adamrankin** [comment]
Definitely fine by me. Any auto-formatters that people find that work would be great. So far, the Astyle visual studio extension is ok, but I'm open to new options.

**Comment by lassoan** [comment]
I don't think there is an auto-formatter for VTK style, but VTK contributors developed scripts for making specific changes throughout the code when it was needed. As far as I know, usage of auto-formatters is not permitted: you are only allowed to change formatting in the block of code that you modified.

I think we should avoid using auto-formatters (that modify the entire file) in Plus, too. The only exception is doing large bulk updates, specifically to change style or make style consistent across the library. These bulk updates should be announced well in advance and happen very rarely (not more than once a year or so), to minimize overhead of non-trivial merges.
