### ISSUE TITLE
First steps to connect a (not yet supported) XSENS mtw inertial measurment unit

### ISSUE THREAD

**Issue by terajnol** [PlusToolkit/PlusLib#308]
Hi all,

I would like to connect my Mtw IMU to 3D slicer through PLUS Toolkit.
I downloaded the toolkit and I am following the tutorials (on http://www.slicerigt.org/wp/user-tutorial/) but I couldn't get exactly what to edit in the config file. As adviced, I start from an example file, PlusDeviceSet_Server_Microchip.xml.
How does PLUS access to my device, just by the id of the serial port ?
Also, in the config file, are the IDs of the "Device" and "DataSources" sections just variable names for PLUS or real IDs of my current device ?

In my case, the Mtw IMU is wireless, so I have a wireless dongle connected to my serial port, and this dongle needs special configuration to set the radio signal. I think I need to run my Xsens program to set up communication between my dongle and the IMU, and then to ask the IMU to send data. Then I can access this data from PLUS toolkit and send that to 3D Slicer. Am I right ?

Thanks for your kind help,

**Comment by Sunderlandkyl** [comment]
[Is this the device that you are referring to?](https://www.xsens.com/products/mtw-awinda/)

To use the Xsens MTw with Plus, a new device would need to be implemented in Plus that uses the Xsens API. Here is an example for a device that communicates with OptiTrack hardware: https://github.com/PlusToolkit/PlusLib/tree/master/src/PlusDataCollection/OptiTrack.

Unfortunately we don't have access to an Xsens device here, which would make implementing such a device difficult. If you would like to implement a device for Xsens hardware, then we could integrate it into Plus to allow other users to use these devices!

To answer your question about the IDs, they are used internally by Plus to refer to the tools, and are used to create transform names (see http://perk-software.cs.queensu.ca/plus/doc/nightly/user/Configuration.html).

PortName is generally used to identify the tools provided by the device. (For some devices, such as the OptiTrack the ID is used to identify the tools from the device, although I don't believe that is standard behavior).

(@lassoan @adamrankin Let me know if I missed anything, or if any of my info is incorrect.)

**Comment by adamrankin** [comment]
No, that's correct.

PortName for each device has unique behaviour, and should be documented in each device's documentation page.

@terajnol If you have the ability to implement a device interface class, that would be great. If you need a starter, I can give you some information. Otherwise, I would recommend duplicating a similar device and starting from there.

**Comment by terajnol** [comment]
Thank you for your fast answers !
@Sunderlandkyl, Yes I was referring to the Mtw Awinda device.
Sadly I don't have good enough knowledge to implement a new Xsens device interface class yet. First, I think I am going to use the OpenIGTLink library directly with Xsens API to connect my device to 3D Slicer. If I get everything working fast enough, I could spend some more time on PLUS and maybe implement this device.

**Comment by adamrankin** [comment]
No worries!

Just fyi, Plus is basically what you've described. It's a series of classes that collects data from the device's API, and performs some data manipulation (not something you'd have to worry about) and makes that data available to a number of interfaces (one of those being an OpenIGTLink server).

**Comment by lassoan** [comment]
@terajnol you would be much better off using Plus, as you would need to write one very simple class. PortName is used for identifying a particular component - forn example, if you connect 5 wireless sensors, PortName can be used to associate a sensor with a Plus data source.

**Comment by terajnol** [comment]
OK, then I am gonna try to write this class. If everything works fine with PLUS and my Xsens Mtw Awinda device, I will provide this code for potential future users.
My plan is to start from the Microchip Tracker device [example](https://github.com/PlusToolkit/PlusLib/tree/master/src/PlusDataCollection/MicrochipTracking), which seems to be similar to mine (and the C++ class does not seem very difficult).
Few questions about that: 
- What is the relation between the config xml file and the C++ class ?
- How should I test my C++ class for the new device ? Do I need to download specific sources ?

**Comment by adamrankin** [comment]
I added a page describing the steps necessary to add a new device interface [here](https://github.com/PlusToolkit/plustoolkit.github.io/blob/master/devicecode.md).

@lassoan @cpinter @Sunderlandkyl would you guys also check it out, and add/remove any information you think necessary?

**Comment by lassoan** [comment]
Awesome, thanks @adamrankin this page is really useful! I would put it into the API documentation (hosted in the source code repository, generated by Doxygen, http://perk-software.cs.queensu.ca/plus/doc/nightly/dev/), otherwise we cannot keep it in sync with code changes.

**Comment by lassoan** [comment]
> What is the relation between the config xml file and the C++ class

On startup, Plus framework creates on instance of your device class (if the XML file contains your device type in DataCollection section) and calls its ReadConfiguration method to set up its parameters.

> If everything works fine with PLUS and my Xsens Mtw Awinda device, I will provide this code for potential future users

The easiest if you clone PlusLib repository and make necessary changes in your fork. If you have any question then you can just send a link to the relevant code section.

**Comment by terajnol** [comment]
@adamrankin Thanks for the doc, it is fantastic ! 
I am done with the cmake find module thanks to the examples (I have almost never worked on Cmake before).
I am now working on the Cmake part and I have few questions:

- I think there is a mistake in the document on Cmake/PlusBuild/Example : 

> OPTION(PLUS_USE_YourDeviceName "Provide support for <your device description>" OFF)

should be ON

- I downloaded PlusBluid repository, as well as PlusLib, but I don't understand when PlusLib is called. Is it when PlusBuild is built ? 

- When I am done with the Cmake part, I plan to build PlusBuild following the [tutorial](https://github.com/PlusToolkit/PlusBuild/blob/master/Docs/BuildInstructionsWindows.md) to check errors on compialtion. Am I right or is there a better way to check my changes ?

Thank you all for your reactivity

**Comment by terajnol** [comment]
My mistake, there is no error in 

> OPTION(PLUS_USE_YourDeviceName "Provide support for " OFF)

**Comment by adamrankin** [comment]
Our common work pattern is to use PlusBuild. When compiling, it will download and build all dependencies, and also download and build PlusLib and PlusApp.

I then work on that working copy of PlusLib (open it's solution if using Visual Studio), instead of trying to use an external one.

I only compile PlusBuild once, but compile PlusLib repeatedly during development.

**Comment by adamrankin** [comment]
Let me know if you have any more questions about adding the device.
