### ISSUE TITLE
Module to process two inputs devices.

### ISSUE THREAD

**Issue by nehk018** [PlusToolkit/PlusLib#321]
Hello everbody,

I want to process two visual images from OpenCv cameras. The idea is to develop a plus module that can process this two images, and then send with OpenIGLink to Slicer. It's that possible?

How can I create this new module?? It's there any module to use as a example?

Thank you.
Jorge

**Comment by adamrankin** [comment]
It's possible! You would have two OpenCV devices, each with a different index (a patch may be required to allow openCV devices to be accessed by index as well)

Then, have a second igtlinkserver tag in the config file running on a different port.

**Comment by nehk018** [comment]
Thank you Adam.

But, How can I create a module to process the two images? I need to access to both images from my new module or device, but I don't know how can I get the images to process it.

I would like to create a new module which has some cameras as inputs (visual cameras, infrared cameras or 3d cameras). The module process, unified and register the images and then send with OpenIGTLink.

So I don't know who can I create my module to capture the images.

Thank you
Jorge

**Comment by nehk018** [comment]
Thank you Andras,

I will follow your recomendations.

Now I'm trying to read a input device in plus. My config file is:

<DataCollection StartupDelaySec="1.0" >
    <DeviceSet 
      Name="PlusServer: 3d infrared and visual camera image processing"
      Description="Proccessing infrared and visual camera image"
    />
    <Device
      Id="VideoDevice"
      Type="OpenCVVideo" 
      RequestedCaptureApi="CAP_V4L2"
      VideoURL="/dev/video0">>
      <DataSources>
        <DataSource Type="Video" Id="Video" ImageType="RGB_COLOR" PortUsImageOrientation="MF"  />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStream" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>
    <Device
      Id="CaptureDevice"
      Type="3difvcp" >
      <InputChannels>
        <InputChannel Id="VideoStream" />
        <InputChannel Id="VideoStream" />
      </InputChannels>
     <OutputChannels>
        <OutputChannel Id="VideoOut" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>
  </DataCollection>

I don't know how can I read the input frames from two channels. I'm using the vtkPlusVirtualCapture as example, but i don't found where are the inputs channels.

Thank you
Jorge

**Comment by adamrankin** [comment]
Plus architecture dictates that only one video stream may be present in a channel.

In this situation, a capture device cannot record two streams. However, two capture devices can record 1 stream each.

You could configure a file like the following:
``` xml
<?xml version="1.0"?>
<PlusConfiguration version="2.1">
  <DataCollection StartupDelaySec="1.0">
    <DeviceSet Name="PlusServer: 3d infrared and visual camera image processing" 
               Description="Proccessing infrared and visual camera image"/>
    <Device Id="VideoDevice"
            Type="OpenCVVideo"
            RequestedCaptureApi="CAP_V4L2"
            VideoURL="/dev/video0" >
      <DataSources>
        <DataSource Type="Video" Id="Video" ImageType="RGB_COLOR" PortUsImageOrientation="MF"/>
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStream" VideoDataSourceId="Video"/>
      </OutputChannels>
    </Device>
  
    <Device Id="3difvcp_left" 
            Type="CaptureDevice"
            BaseFilename="3divcp_left.nrrd"
            EnableCompression="TRUE"
            EnableCapturingOnStart="FALSE" >
      <InputChannels>
        <InputChannel Id="VideoStream"/>
      </InputChannels>
    </Device>
  
    <Device Id="3difvcp_right" 
            Type="CaptureDevice"
            BaseFilename="3difvcp_right.nrrd"
            EnableCompression="TRUE"
            EnableCapturingOnStart="FALSE" >
      <InputChannels>
        <InputChannel Id="VideoStream"/>
      </InputChannels>
    </Device>
  </DataCollection>
</PlusConfiguration>
```

But then the two capture devices would be redundant as they are recording the same input.

Is your opencv video a single piece of memory that contains two images, or do you have two webcams as input at the same time (eg: /dev/video0 and /dev/video1)?

**Comment by nehk018** [comment]
Sorry Adam, I didn't explain correctly. I would like to integrate two diferents devices as Infrared Camera and Opencv video. 

I think the configuration file is:

`<PlusConfiguration version="2.0">

  <DataCollection StartupDelaySec="1.0" >
    <DeviceSet 
      Name="PlusServer: 3d infrared and visual camera image processing"
      Description="Proccessing infrared and visual camera image"
    />
    <Device
      Id="VideoDevice"
      Type="OpenCVVideo" 
      RequestedCaptureApi="CAP_V4L2"
      VideoURL="/dev/video0">
      <DataSources>
        <DataSource Type="Video" Id="Video" ImageType="RGB_COLOR" PortUsImageOrientation="MF"  />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStream1" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>
     <Device
      Id="VideoDevice"
      Type="InfraredSeekCam">
      <DataSources>
        <DataSource Type="Video" Id="Video" PortUsImageOrientation="UF"  />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStream2" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>
    <Device
      Id="CaptureDevice"
      Type="3difvcp"
      ShowImages="true"
      BaseFilename="RecordingTest.mha"
      EnableCapturingOnStart="FALSE" >
      <InputChannels>
        <InputChannel Id="VideoStream1" />
        <InputChannel Id="VideoStream2" />
      </InputChannels>
      <OutputChannels>
        <OutputChannel Id="OutPut" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>
  </DataCollection>`

The idea is processing both images and then send via openigtlink to Slicer.  

It's possible??

Thank you very much

**Comment by adamrankin** [comment]
``` xml
<PlusConfiguration version="2.0">

  <DataCollection StartupDelaySec="1.0" >
    <DeviceSet 
        Name="PlusServer: 3d infrared and visual camera image processing"
        Description="Processing infrared and visual camera image"
        />

    <Device
        Id="VideoDevice"
        Type="OpenCVVideo" 
        RequestedCaptureApi="CAP_V4L2"
        VideoURL="/dev/video0">
      <DataSources>
        <DataSource Type="Video" Id="Video" ImageType="RGB_COLOR" PortUsImageOrientation="MF" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStream1" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>

    <Device
        Id="VideoDevice"
        Type="InfraredSeekCam">
      <DataSources>
        <DataSource Type="Video" Id="Video" PortUsImageOrientation="UF" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStream2" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>

    <Device
        Id="infraredcapture"
        Type="CaptureDevice"
        BaseFilename="infrared.nrrd"
        EnableCapturingOnStart="FALSE" >
      <InputChannels>
        <InputChannel Id="VideoStream2" />
      </InputChannels>
    </Device>

    <Device
        Id="cvcapture"
        Type="CaptureDevice"
        BaseFilename="opencv.nrrd"
        EnableCapturingOnStart="FALSE" >
      <InputChannels>
        <InputChannel Id="VideoStream1" />
      </InputChannels>
    </Device>
  </DataCollection>

  <PlusOpenIGTLinkServer 
    MaxNumberOfIgtlMessagesToSend="1"
    MaxTimeSpentWithProcessingMs="50"
    ListeningPort="18944"
    SendValidTransformsOnly="true"
    OutputChannelId="VideoStream1" >
    <DefaultClientInfo> 
      <MessageTypes> 
        <Message Type="IMAGE" />
      </MessageTypes>
      <ImageNames>
        <Image Name="OpenCVImage" EmbeddedTransformToFrame="Reference" />
      </ImageNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>

  <PlusOpenIGTLinkServer 
    MaxNumberOfIgtlMessagesToSend="1" 
    MaxTimeSpentWithProcessingMs="50" 
    ListeningPort="18945" 
    SendValidTransformsOnly="true" 
    OutputChannelId="VideoStream2" > 
    <DefaultClientInfo> 
      <MessageTypes> 
        <Message Type="IMAGE" />
      </MessageTypes>
      <ImageNames>
        <Image Name="InfraredImage" EmbeddedTransformToFrame="Reference" />
      </ImageNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>

  <CoordinateDefinitions>
    <!-- This would be the calibration from a tracker sensor to the camera -->
    <Transform From="InfraredImage" To="Reference"
      Matrix="
        1 0 0 0
        0 1 0 0
        0 0 1 0
        0 0 0 1"
      Date="2011.12.06 17:57:00" />
      <!-- This would be the calibration from a tracker sensor to the webcam -->
    <Transform From="OpenCVImage" To="Reference"
      Matrix="
        1 0 0 0
        0 1 0 0
        0 0 1 0
        0 0 0 1"
      Error="0.404711" Date="012712_152104" />
  </CoordinateDefinitions>
</PlusConfiguration>
```

In Slicer, have two OpenIGTLinkIF connections, one for 18944 and one for 18945

**Comment by nehk018** [comment]
Thank you adam, and sorry for the delay
