### ISSUE TITLE
CMake complains about UsePlusLib.cmake 

### ISSUE THREAD

**Issue by samuelgerber** [PlusToolkit/PlusLib#323]
CMake complains about:
- wrong number of arguments in INCLUDE_EXTERNAL_MSPROJECT()
- SET_TARGET_PROPERTIES(vtkPlusServer PROPERTIES FOLDER ${GROUPNAME})

Attached is a cmake file with the offending lines uncommented so that cmake configuration works.
[UsePlusLib.zip](https://github.com/PlusToolkit/PlusLib/files/1656559/UsePlusLib.zip)

CMake version 3.10.1

**Comment by lassoan** [comment]
What CMake options have you changed when you configured Plus? Have you disabled OpenIGTLink?

**Comment by lassoan** [comment]
@Sunderlandkyl I had a quick look and it seems that in PlusLib\src\UsePlusLib.cmake.in, this line `  INCLUDE_EXTERNAL_MSPROJECT(@vcProj_vtkPlusServer@)` should be moved in the `IF(@PLUS_USE_OpenIGTLink@)` branch. Could you take it over from here? Thanks!

**Comment by samuelgerber** [comment]
Yes, PLUS_USE_OpenIGTLink is disabled in my PlusLib build.

**Comment by lassoan** [comment]
Ok, that causes the issue then. We'll fix it soon. Thanks for reporting this.

**Comment by Sunderlandkyl** [comment]
Should be fixed now.
