### ISSUE TITLE
Add Intel RealSense camera support to packages

### ISSUE THREAD

**Issue by lassoan** [PlusToolkit/PlusLib#325]
We should make Intel RealSense camera support available in pre-built Plus packages.

If the SDK files are small and no driver installation is required then it could be added to all packages (except WindowsXP and other special packages).

**Comment by Sunderlandkyl** [comment]
RealSense is now available all packages except the Ultrasonix in both Stable and Nightly releases.
Installer size hasn't been affected much, if at all, and it runs on a clean computer with no RealSense installation.

**Comment by lassoan** [comment]
Perfect! Thanks for testing and integrating this.
