### ISSUE TITLE
Send landmarks associated with an image volume

### ISSUE THREAD

**Issue by adamrankin** [PlusToolkit/PlusLib#327]
When a GetImage command is sent to PlusServer, check for an associated landmark file and send any found landmarks as metadata

**Comment by lassoan** [comment]
Get image is used StealthLink device.

**Comment by lassoan** [comment]
Theirs also a similar standard OpenIGTLink message for getting landmarks. Both commands are implemented in BrainLab navigation systems and in Slicer.

**Comment by adamrankin** [comment]
Ah interesting, I'll look into it.

I may change the base class behaviour to return an image from the first available channel that has image data.
