### ISSUE TITLE
Connection failed: Ultrasonix L14-5 through Ulterius

### ISSUE THREAD

**Issue by houssamhariri** [PlusToolkit/PlusLib#329]
Trying to set up a config file for Ultrasonix L14-5 with Aurora tracker. I was able to do this successfully using the Porta interface, but could not with the Ulterius interface. See error log and config files below. 

[PLUS_Ulterius_error.txt](https://github.com/PlusToolkit/PlusLib/files/1687549/PLUS_Ulterius_error.txt)

[PlusDeviceSet_Server_Aurora_Ultrasonix_L14-5_Ulterius - Houssam.txt](https://github.com/PlusToolkit/PlusLib/files/1687556/PlusDeviceSet_Server_Aurora_Ultrasonix_L14-5_Ulterius.-.Houssam.txt)

**Comment by Sunderlandkyl** [comment]
It looks like your using an older version of Plus. Can you try the config file using the Plus 2.7 nightly?http://perk-software.cs.queensu.ca/plus/packages/nightly/

**Comment by houssamhariri** [comment]
Tried it with the nightly build, but still no luck. Please see attached error trace log. 

[trace.txt](https://github.com/PlusToolkit/PlusLib/files/1696933/trace.txt)

**Comment by houssamhariri** [comment]
Closed by mistake. Issue is still ongoing so I reopened.

**Comment by prash-p** [comment]
@Sunderlandkyl is ulterius required to use the L14-5 probe on an Ultrasonix machine? How can we check if it is installed and running properly?

**Comment by Sunderlandkyl** [comment]
I'm not sure @lassoan do you have any input on this?

**Comment by lassoan** [comment]
If you cannot connect to your ultrasound system:
1. Make sure Exam software is running.
2. Make sure that in the Exam software settings, "SonixLive straming" checkbox is checked. If the checkbox is disabled (you cannot check it) then you have to enter your license key that enables this option.

**Comment by houssamhariri** [comment]
Just tried it with "SonixLive streaming" checkbox ticked and with the newest version of PLUS, but still says connection failed. Note that the SonixRP software and Plus server are both running on the same machine. I also confirmed that the SonixRP is up-to-date, version is 6.1.x. Error log is attached below. 

[trace.txt](https://github.com/PlusToolkit/PlusLib/files/1709219/trace.txt)

**Comment by lassoan** [comment]
Is the Exam software running when you are trying to connect? Is the Exam software is in research mode? Can you connect with Ultrasonix demo applications that are included in the Ultrasonix SDK?

**Comment by houssamhariri** [comment]
Yes. Yes (tried in both modes). Not sure which demo applications you're referring to, can you give an example? 

Another thing I noticed is that at the top of the window it says "Sonix: no connections" although I can see the ultrasound image from the transducer.
