### ISSUE TITLE
Using the Curve Maker extension

### ISSUE THREAD

**Issue by ankur5200** [PlusToolkit/PlusLib#331]
Hello sir,
I am using two probe sensors from 3D Guidance trackSTAR tracker and using it in 3D slicer. I want to connect the 2 sensors(Needle Model on 3D slicer) with a curve. 
At present I am using Curve Maker extension to connect the two sensors but I am unable to get desired output.
When I move the first sensor in the curve path , then there should be some curve in the distance between the two sensors. That curve I am trying to make using Curve Maker.
I am attaching the required screenshots and the way I am using my sensors.
Looking forward to hear from you soon.
Thank you.
![screenshot 3](https://user-images.githubusercontent.com/35588053/36655348-16bbb418-1afd-11e8-9c9d-b6dff1979784.png)
![screenshot 4](https://user-images.githubusercontent.com/35588053/36655352-1957b474-1afd-11e8-9535-4fd250050399.png)
![screenshot 5](https://user-images.githubusercontent.com/35588053/36655353-1ba66d60-1afd-11e8-9f52-14b2c058bfc7.png)
![img_20180226_135735](https://user-images.githubusercontent.com/35588053/36655374-300b4924-1afd-11e8-95dd-4d289a6a8d5d.jpg)

**Comment by lassoan** [comment]
Would you like to display the trajectory that the sensors followed as you moved them? In that case use SlicerIGT extension's Collect Points module in combination with MarkupsToModel extension's Markups to Model module.

If your goal is to estimate the curvature of a flexible tool, then you must compute the curve point yourself based on the measured position and orientation of the sensors, mounting position of the sensors, mechanical properties of the flexible tool, shape of airways or vessels the tool is inserted into, etc. and then feed those point positions into Markups to Model module.

**Comment by ankur5200** [comment]
Yes, similar to that. eg.., If I am moving my sensor and taking a curve, then that curve should be displayed on the screen.

**Comment by ankur5200** [comment]
![screenshot 6](https://user-images.githubusercontent.com/35588053/36659860-e1058a42-1b10-11e8-91bd-2dd9172d8da8.png)

This is the screenshot of what you suggested.
I couldn't understand how to proceed with it.
Looking forward for your kind assistance.
Thank you

**Comment by ankur5200** [comment]
Also if I could know what should be in an Input model and output model would be really helpful. I seriously need your help.

**Comment by ankur5200** [comment]
I am unable to set up the hierarchy...which transformation node should be where.

**Comment by ankur5200** [comment]
![screenshot 6](https://user-images.githubusercontent.com/35588053/36661152-7808b0a0-1b15-11e8-86fe-e642d5d90523.png)
![screenshot 7](https://user-images.githubusercontent.com/35588053/36661155-79f92688-1b15-11e8-9e95-84bf4598e1b9.png)
I have reached till here. I am facing problem in hierarchy. The yellow line connecting the two points should show the curve motion as one of the sensor is bent.

**Comment by ankur5200** [comment]
![screenshot 7](https://user-images.githubusercontent.com/35588053/36661236-be615958-1b15-11e8-9dd1-0ca17de16511.png)
![screenshot 8](https://user-images.githubusercontent.com/35588053/36661246-c3fbceac-1b15-11e8-9353-86a0572d5db8.png)
I have reached till here. I am facing problem in hierarchy. The yellow line connecting the two points should show the curve motion as one of the sensor is bent.

**Comment by lassoan** [comment]
@tavaughan Could you please help explaining how to use Collect Points + Markups to Model to show trajectory of a tracked tool?

**Comment by tavaughan** [comment]
If tool trajectory is what you need to see, then you can do the following:

Before you start, pause any tool recording that you have (stop things from moving).

1. Open CollectPoints
2. Set the input transform, in your case the transform for your sensor
3. Create a new model - the model will store 3D points where the tool has been
![toolpathcollectpoints1](https://user-images.githubusercontent.com/6616890/36740892-c2cfdaea-1bb1-11e8-8c87-13b6c958285e.png)

4. Enable auto-collect by clicking on the checkbox
![toolpathcollectpoints2](https://user-images.githubusercontent.com/6616890/36741112-44e678cc-1bb2-11e8-888f-7c226ac652aa.png)

5. Go to markups to model module
6. Change it to curve mode
7. Set the input to the model node you created in step 3.
8. Enable auto-update. When new points are added, it will update the curve
![toolpathmarkupstomodel](https://user-images.githubusercontent.com/6616890/36741240-99a722a8-1bb2-11e8-8751-76c43f67081a.png)

If you want to, you can change the appearance of the curve (straight lines, smooth curves, type of interpolation, etc) using the advanced options. Check the SlicerMarkupsToModel github page for more details:
https://github.com/SlicerIGT/SlicerMarkupsToModel

If you want to have two curves being updated in real-time, then you will need to create a second CollectPoints "Parameter Node", and a second MarkupsToModel "Parameter Node".

I hope that helps!

**Comment by ankur5200** [comment]
Thank you for such a nice description.
I have few doubts.
How to take the point? I mean from where am I suppose to collect the
points. How does it work. And if there is any specific consideration while
taking the points.

Looking forward to hear from you soon.
Thanks

**Comment by tavaughan** [comment]
If you use CollectPoints as shown above, points will be collected whenever the sensor transform changes (i.e. when you move the sensor).

**Comment by ankur5200** [comment]
Okay. So that's means I need not to mark any points on the screen. It will
mark by it's own once I follow this.
Do I need to change anything in data hierarchy?

Thank you

**Comment by tavaughan** [comment]
Yes, it should show the path that the sensors took.

Points are recorded in the Ras coordinate system, and the model is stored in the Ras coordinate system, so it should work without doing anything to the hierarchy. If you find that something behaves oddly, let me know.

Hope that helps!

**Comment by ankur5200** [comment]
Thank you . What all you explained is working perfectly. But What I am looking forward is little bit different from this.

I have 2 sensors and placed together one after the other. When I bend first sensor (Sensor A), there is a curve between the two sensors(Sensor A and B). I need to see that curve in 3D slicer during real time navigation.
I am attaching the screenshots of the sensors and 3D slicer model, where I have explained it . 

Looking forward to hear from you soon. 
Thank You
![screenshot explaining the problem 13](https://user-images.githubusercontent.com/35588053/36772035-8735aa4a-1c8e-11e8-9d5e-6d2855c90f0f.png)
![sensors arrangement](https://user-images.githubusercontent.com/35588053/36772037-890ea722-1c8e-11e8-92bd-0f028cb45004.jpg)
![screenshot hierarchy 14](https://user-images.githubusercontent.com/35588053/36772040-8ee4454e-1c8e-11e8-9ba5-d2593843a591.png)

**Comment by tavaughan** [comment]
There are two lines in the first screenshot, a red one and a blue one. Are you trying to make one of those? If yes, is it the red line or the blue line?

**Comment by ankur5200** [comment]
The red line connecting the two sensors, as in the white color sensor wire between the sensors A and B as in screenshot 2. And the blue line is the bent when the sensor A is bent.
I want to make the Red line which will show the connection between the two sensors and a Blue line will show the bent. While doing in 3D slicer, color won't matter.

**Comment by lassoan** [comment]
If your goal is to estimate the curve of a flexible tool based on a few attached sensors, then **you must compute the curve yourself**. We cannot help you with that. You nee to use the measured position and orientation of the sensors (Plus gives you that) but then you have to take into account mounting position of the sensors, mechanical properties of the flexible tool, shape of airways or vessels the tool is inserted into, etc. to compute the curve points. Once you have the curve points, you can feed those point positions into Markups to Model module to display it as a nice, continuous curve.
