### ISSUE TITLE
Add Google Analytics to Plus webpages

### ISSUE THREAD

**Issue by lassoan** [PlusToolkit/PlusLib#334]
Currently, we use StatCounter to count visits to the Plus website, but it gives very little information. We would need to set up Google Analytics instead. Add it both for GitHub pages (https://plustoolkit.github.io/) and User manual (http://perk-software.cs.queensu.ca/plus/doc/nightly/user/index.html).

**Comment by Sunderlandkyl** [comment]
@lassoan
Tested on the live site. Both the GitHub pages and user manual analytics works.
If you want to review them, I made pull requests in PlusBuild and PlusApp. Otherwise, I can just go ahead and merge them.

**Comment by lassoan** [comment]
This is great, thanks a lot, you were really fast (again)!
