### ISSUE TITLE
Registering brain inside a skull

### ISSUE THREAD

**Issue by ankur5200** [PlusToolkit/PlusLib#335]
Hello,

I have one 3D model of a head( Surface model) scanned using 3D  camera. I have imported in 3D slicer as a Model. I just have a surface model and I want to insert CT/MRI data inside the skull. Is there any possible way to do this.

Looking forward to hear from you soon.
Thank You

**Comment by Sunderlandkyl** [comment]
If you can identify landmark points on the head in both the CT and the surface model, you can compute a registration between the two using the Fiducial Registration Wizard.

**Comment by lassoan** [comment]
You can find Fiducial Registration Wizard in SlicerIGT extension.

After completing landmark-based registration, you may use `Model registration` module (in SlicerIGT extension) to perform automatic ICP-based surface alignment to make the result even more accurate.

**Comment by ankur5200** [comment]
![screenshot 18](https://user-images.githubusercontent.com/35588053/36957554-1a6c8d1c-2070-11e8-82b7-c986bb78e4e0.png)



Thank you for your guidance. I have a surface model and I have downloaded the sample MRI head scan. I am trying to use Fiducial Registration Wizard and the transform I am using is shown in the screenshot.

![screenshot 19](https://user-images.githubusercontent.com/35588053/36957581-43687b18-2070-11e8-9159-427d97b12651.png)

Is this the right way to do. And any suggestion as on how to decrease the error. 
Thank you

**Comment by ankur5200** [comment]
First I am clicking on to the From Fiducials and marking it on the MRI slices and then I am clicking onto the To Fiducials and marking onto the model. and then updating it. Is this the right way?

**Comment by lassoan** [comment]
Sounds correct. Don't forget to create an output transform and apply it to the  MRI image.

**Comment by ankur5200** [comment]
![screenshot 20](https://user-images.githubusercontent.com/35588053/36957807-09551a56-2072-11e8-924f-a450ffb9dfab.png)

But output transform you mean the Registration Result(From>To) Transform. eg.., If I have taken it as 1To2...then I need to change the hierarchy and insert it into MRHead(Sample data). as in the screenshot attached?

Thank you

**Comment by lassoan** [comment]
Also make sure you clicked on the corresponding points in the same order (or try to enable automatic point matching). You would probably also benefit from using more landmarks and more accurately identifiable points.

**Comment by ankur5200** [comment]
![screenshot 21](https://user-images.githubusercontent.com/35588053/36958406-8c396d38-2076-11e8-8a36-c9a0ec2efa41.png)
![screenshot 22](https://user-images.githubusercontent.com/35588053/36958407-8d0f75c2-2076-11e8-8086-da56a48df49b.png)

Thank you sir,
I am doing the registration but my error is around 10 ( which after practice I would decrease it), but I am not sure if the hierarchy is correct, and the model and MR slices are totally in opposite direction. 
How to proceed with that. Do I need to make any changes in hierarchy?
Thank You.

**Comment by lassoan** [comment]
It is very important to mark the points on the untransformed image and surface, then compute the transform, and finally apply the transform to the image or surface.

If the size of the image and surface scan are different then you can try similarity transform (but then you have to provide more landmark points).

If the points don't line up then apply the transform to the surface model (maybe you've mixed up what is fiducial list 1/2).

To learn how landmark registration works, complete relevant SlicerIGT tutorials (http://www.slicerigt.org/wp/user-tutorial/).

**Comment by ankur5200** [comment]
Thank You 
Do I need to make any changes in the hierarchy?

**Comment by ankur5200** [comment]
![screenshot 27](https://user-images.githubusercontent.com/35588053/36961499-a27d895c-2086-11e8-9c98-b5148854b7fb.png)

This is what I am getting. If you could suggest some technique to improve the accuracy would be really helpful.
Thank You

**Comment by lassoan** [comment]
Could you save the scene as mrb file, uoad to Dropbox, and copy-paste the link here, so that I can see what's wrong? If you place the landmark points accurately then the error should be insert a few mm.

**Comment by ankur5200** [comment]
Dear Sir,
I have created the dropbox and shared the files with you at your  lasso@queensu.ca ID.
Looking forward to hear from you soon.

**Comment by ankur5200** [comment]
Dear sir,
Hope you have received the files?

**Comment by ankur5200** [comment]
Dear sir,
Looking forward to hear from you.

**Comment by ankur5200** [comment]
![screenshot 29](https://user-images.githubusercontent.com/35588053/37252078-1b1a7144-2556-11e8-8525-836f53f5aae6.png)
This is the screenshot of the orientation of CT i am getting

![screenshot 30](https://user-images.githubusercontent.com/35588053/37252099-63112fe2-2556-11e8-81a6-3977150096eb.png)
This is how I want it to allign

Dear sir,
My CT is aligned in different orientation. I need to change it conventional way . How can I do it.

Thank You
