### ISSUE TITLE
how to calibrate a fff camera in plus

### ISSUE THREAD

**Issue by timeanddoctor** [PlusToolkit/PlusLib#336]
I try to navigate research through the camer with Plus showed in https://www.youtube.com/watch?v=MOqh6wgOOYs. However, I donnot how to calibrate the camera which seems to be the first step after connecting the plus and 3dslicer successfully.

**Comment by lassoan** [comment]
It is described in detail here:
http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceOpticalMarkerTracker.html

**Comment by timeanddoctor** [comment]
Thank you for the prompty reply.
After reading the tutorial, I haven't found the download link both “aruco_print_marker.exe” and "aruco_calibration.exe ".
Maybe it was a part of slicer? Should I runn the code directly in slicer's commend window?
`aruco_calibration.exe live:0 camera_calibration.yml -size 0.03556 `

**Comment by timeanddoctor** [comment]
`>>> aruco_calibration.exe live:0 camera_calibration.yml -size 0.03556 
  File "<console>", line 1
    aruco_calibration.exe live:0 camera_calibration.yml -size 0.03556
                             ^
SyntaxError: invalid syntax`
I was wrong......

**Comment by lassoan** [comment]
aruco_calibration.exe is bundled with Plus. Start "Plus command prompt", it opens a command prompt in the folder where the binaries are located.

**Comment by lassoan** [comment]
What operating system do you use?
Which Plus package did you download?

**Comment by timeanddoctor** [comment]
After copy the code in "Plus command prompt", I have successed open my camera.
My computer based on Win7*64.
The misstake happen because I copy the code in 3d slicer's pyphon interact. 
Thanks.
Best wishes for you！
