### ISSUE TITLE
can I have a registration just by surface-drawing for no marked patient. 

### ISSUE THREAD

**Issue by timeanddoctor** [PlusToolkit/PlusLib#337]
can I have a registration just by surface-drawing for no marked patient.  A patient have scanned the CT with no marks on the brain surface.  Can I have a registration, rather than Fiducial Registration,  just by surface-drawing for no marked patient.

**Comment by lassoan** [comment]
Not in Plus, but in Slicer, yes. See https://discourse.slicer.org/t/function-for-surface-registration/1776/2.

**Comment by lassoan** [comment]
Model Registration module in SlicerIGT extension in Slicer can register two surfaces without any landmarks. However, the module uses ICP method, which may stuck in a local optimum, so it is important to make initial position close to the optimal position.
