### ISSUE TITLE
Can I register between 2d images and 3d model.

### ISSUE THREAD

**Issue by timeanddoctor** [PlusToolkit/PlusLib#338]
In order to navigate, can I register between 2d images by intraoperative X-ray and preoperative CT DICOM.
There is no O-army scanner in my hospital, and a  preoperative CT of spinal is extremly important. I try to get two 2d-images from  intraopterative X-ray for a patient, such as Lateral position and Frontal position. Some marks have been attached to the patient body before the surgery.

**Comment by lassoan** [comment]
This kind of image-based 2D/3D registration is out of Plus toolkit's scope. ITK includes an algorithm that may be usable (https://itk.org/Doxygen/html/group__TwoProjectionRegistration.html). You can get more information and help at ITK forum (https://discourse.itk.org/).
