### ISSUE TITLE
Compiling Plus-2.6 fails with OpenIGTLinkIO

### ISSUE THREAD

**Issue by olevs** [PlusToolkit/PlusLib#339]
I'm compiling Plus-2.6 on Linux and macOS with BK and Polaris support. Compiling Plus-2.6 with OpenIGTLinkIO used to work, but this now fails.

It seems like Plus-2.6 and OpenIGTLinkIO are no longer in synch. Errors shows that Plus-2.6 now tries to use a newer version of igtlio::PolyDataConverter. I guess this can be fixed by either switching to an older version of OpenIGTLinkIO or fixing the two lines in vtkPlusOpenIGTLinkServer.cxx: 785 and 788, and other issues with OpenIGTLinkIO version differences.

Compile errors:
   /home/dev/dev/plus/PlusB-bin/PlusLib/src/PlusServer/vtkPlusOpenIGTLinkServer.cxx:785:9: error: ‘MessageContent’ is not a member of ‘igtlio::PolyDataConverter’
        igtlio::PolyDataConverter::MessageContent content;
        ^
   /home/dev/dev/plus/PlusB-bin/PlusLib/src/PlusServer/vtkPlusOpenIGTLinkServer.cxx:786:9: error: ‘content’ was not declared in this scope
        content.deviceName = "PlusServer";
        ^
   /home/dev/dev/plus/PlusB-bin/PlusLib/src/PlusServer/vtkPlusOpenIGTLinkServer.cxx:788:9: error: ‘VTKToIGTL’ is not a member of ‘igtlio::PolyDataConverter’
        igtlio::PolyDataConverter::VTKToIGTL(content, (igtl::PolyDataMessage::Pointer*)&msg);
        ^
   ninja: build stopped: subcommand failed.

**Comment by olevs** [comment]
Changing PlusBuild/SuperBuild/External_OpenIGTLinkIO.cmake line 16
from "master" to "577bfedd66d720413ea380ca764471d908c9476b"
seems to work for changing to the previously used version of OpenIGTLinkIO.

**Comment by olevs** [comment]
I see that I used the master branch of PlusBuild. I realize it should work ok if I instead use the Plus-2.6 branch of PlusBuild.

**Comment by lassoan** [comment]
To build Plus-2.6, use Plus-2.6 branch of PlusBuild:
https://github.com/PlusToolkit/PlusBuild/tree/Plus-2.6

Stable build is tested every night on the dashboard and it all looks good:
http://perkdata.cs.queensu.ca/CDash/index.php?project=PlusLib&filtercount=1&showfilters=1&field1=buildname/string&compare1=63&value1=stable
