### ISSUE TITLE
fCAL Calibration (issue in image spacing definition)

### ISSUE THREAD

**Issue by joaolgfonseca** [PlusToolkit/PlusLib#342]
Hello,

I am facing some problems in defining the image spacing in the segmentation parameters menu in fCAL application. When I tried to define the image spacing using the green and blue dots, I did not find them on the interface. Is there a different way to define the image spacing using fCAL when we use an image grabber to capture the images?

I found this issue in 2.6 and 2.7 versions, but it is possible to define the image spacing on version 2.4.  However, other issues that you solved are present in version 2.4, and I would like to use the most recent version.

Also, the manual definition of the region of interest crashes the application too.

I tested both the win64 and win32.

Best regards,
João

**Comment by adamrankin** [comment]
Hi, which is are you using? I am able to see and manipulate the spacers on the nightly using windows.

What do you mean by define ROI manually? Using the spin boxes? In the config file?

**Comment by joaolgfonseca** [comment]
Hello,

I'm sorry. I was checking the configuration file and I found that I configured it incorrectly. I did not set the <segmentation> tag. This is why I was not unable to change parameters and the program crashed.

It is working now using the version 2.6.0.20171113. 

Version 2.7.0.20171206 seems more unstable.
