### ISSUE TITLE
Do I have to change to a 32 bits computers?

### ISSUE THREAD

**Issue by timeanddoctor** [PlusToolkit/PlusLib#344]
![2018-03-15_232049](https://user-images.githubusercontent.com/28825816/37473017-62e06880-28a8-11e8-8714-1dd9201e3a7e.jpg)

**Comment by Sunderlandkyl** [comment]
You should be able to run both on a 64-bit computer.

**Comment by timeanddoctor** [comment]
![2018-03-15_233207](https://user-images.githubusercontent.com/28825816/37473335-1b637a32-28a9-11e8-8dac-30dd4f20a2d7.jpg)

**Comment by Sunderlandkyl** [comment]
You can check which Plus packages contain Ascension support in the table here: https://plustoolkit.github.io/download

**Comment by timeanddoctor** [comment]
Thank you very much Professer Sunderlandkyl. 
Though I connect 3d slicer by 32bits Plus, the computer connot detect the device for lacking of drive.
My device was mentioned  [https://discourse.slicer.org/t/is-plus-compatible-with-cygnus-pfs-a-dc-magnetic-navigate/2123/2](url);
![2018-03-15_233520](https://user-images.githubusercontent.com/28825816/37473772-d948c00c-28a9-11e8-84a6-a00712ffd0b4.jpg);
I try to find a drive from it's website but nothing.https://www.ascension-tech.com/products/transmitters/
I'll be grateful that you can help me download and send me a drive software.
My Email: lizhenzhu1@sina.com
Thanks.

**Comment by Sunderlandkyl** [comment]
I don't think that I can provide you with the drivers (@lassoan let me know if that's something we can do).

The drivers might be available at https://support.ndigital.com/, although I don't have access so I am unable to check. The ascension may have also come with a CD containing the drivers.

**Comment by lassoan** [comment]
Does Cygnus software work well on that computer? If yes, then drivers should be OK.
Can you copy-paste the Plus error log? (not a screenshot but the text that you see in the Plus log window if you click the colored circle in the bottom-right corner)

**Comment by timeanddoctor** [comment]
![2018-03-18_173438](https://user-images.githubusercontent.com/28825816/37564557-48d22604-2ad3-11e8-9beb-fb0ef48237a6.jpg)
the cygnus software worked on Linux.

**Comment by lassoan** [comment]
64-bit systems can run both 32-bit and 64-bit applications.

You can also build Plus on Linux and run it in Linux and stream the navigation data to any other computer running Slicer on a 64-bit operating system. You may need to make some changes in Plus to make Ascension support available in Linux (https://github.com/PlusToolkit/PlusLib/issues/345).

You can get Ascension3DG driver for Windows from NDI support. If you have difficulty getting it then contact me at lasso@queensu.ca.

**Comment by timeanddoctor** [comment]
Dear Professor lassoan
Thank you for your prompty reply.
I have try to connect the 3DG with the help of NDI-China-Agent and still failed. They told me that they couldnot find the driver as well. I think the best choice system for me is Windows used usaully. So I will Emailed to you. In the meantime, I will try to deal with this problem follow:https://github.com/ChristophJud/ATC3DGTracker.
Thanks.
