### ISSUE TITLE
Add Ascension tracker support in Linux

### ISSUE THREAD

**Issue by lassoan** [PlusToolkit/PlusLib#345]
If somebody needs to connect Ascension3DG device on Linux then this repository may help:
https://github.com/ChristophJud/ATC3DGTracker

NDI is not developing Ascension trackers anymore (it will be probably discontinued within a few years) and Linux is very rarely used for IGT system development, so there is **no need to work on this now**.

**Comment by adamrankin** [comment]
Re-open if desired.
