### ISSUE TITLE
Can't connect to NDI Aurora。

### ISSUE THREAD

**Issue by barony14** [PlusToolkit/PlusLib#347]
when I choose " NDI Arora Tracker" and launcher server,it just shows "Connection failed!
Please select another device set and try again!"
The Info is following
![default](https://user-images.githubusercontent.com/33677387/37957850-8e47befa-31e1-11e8-89eb-730997ba15f1.png)
Thank you in advance!

**Comment by adamrankin** [comment]
Have you confirmed you can connect to COM4 using NDI's Track software?

**Comment by barony14** [comment]
yes, the NDI's Track software works well. But PLUS can not connect to  the Tracker.

**Comment by adamrankin** [comment]
Do you know how to generate a trace using NDI Track?

If so, could you paste the log?

**Comment by barony14** [comment]
I don't know how to generate a trace. I paste a picture which shows my NDI system working well,
![track](https://user-images.githubusercontent.com/33677387/38069664-161e56b8-334a-11e8-82da-4d47619ce268.PNG)
And in PLUS launcher, like this
![error](https://user-images.githubusercontent.com/33677387/38069738-8937799a-334a-11e8-9693-fd29003cfefb.PNG)

**Comment by barony14** [comment]
is this trace?
[trace.txt](https://github.com/PlusToolkit/PlusLib/files/1858800/trace.txt)

**Comment by adamrankin** [comment]
That is the Plus log, which is great, but the NDI trace will tell me a lot of valuable information.

In the NDI Track App, could you go to 

Utilities->Console
File->Trace Communications
**either**
File->Log to File
**or**
Copy and paste log

Then, connect to your device as usual and upload/paste the log here. Thanks!

**Comment by adamrankin** [comment]
Could you try the nightly package tomorrow and add an entry to the config file:

CheckDSR="false"

then try again?

(this is a bit of a guess, but worth a try)

**Comment by barony14** [comment]
thank you for your advice, and here is the NDI trace log
[ndi trace.txt](https://github.com/PlusToolkit/PlusLib/files/1862720/ndi.trace.txt)

**Comment by barony14** [comment]
here is the PLUS trace log (using plusapp 2.7.0.20180328-win64)
[trace.txt](https://github.com/PlusToolkit/PlusLib/files/1862745/trace.txt)

**Comment by adamrankin** [comment]
Could you set the baud rate to 115200?

BaudRate="115200" in aurora device config

**Comment by barony14** [comment]
I tried your advice but it was not usefull. Now the problem is the "serialport" I set is "3", and my NDI aurora
tracker is COM3, but in the trace it's COM4(index3), following is the trace log
[trace.txt](https://github.com/PlusToolkit/PlusLib/files/1866867/trace.txt)
I change the "serialport" to "2", in the trace it's COM3(index2) and still can't connect.

**Comment by barony14** [comment]
yes, the default number is 9600, then I set baudrate=115200, useless

**Comment by adamrankin** [comment]
To confirm, you've set
CheckDSR="false"

**Comment by adamrankin** [comment]
Could you rerun the plus log with logging level set to debug? --verbose=4 for command line, dropdown box for GUI

**Comment by barony14** [comment]
oh, I may be wrong. I always open the NDI toolbox first and PLUS secend, just now I directly open the PLUS and connect to COM4 succesfully. Sorry, this may be my own mistake.

**Comment by adamrankin** [comment]
Ok, glad to hear it.
