### ISSUE TITLE
Calibration fCal Telemed L12

### ISSUE THREAD

**Issue by ChiaraTe** [PlusToolkit/PlusLib#348]
Hi,
I tried to calibrate the Telemed's linear probe L12 with phantom multi-N version 2.0 of PerkLab but I can't obtain an error under 3 mm despite having errors under 1 mm in  Stylus calibration, phantom registration and temporal calibration. I can obtain an error under 1 mm with Ultrasonix linear US (L14-5 probe) but with the probe L12, I can't.  I also tried to modify the phantom reducing the distance between the wires but without results. Do you have any suggestions how to improve the results? 
Thanks in advance

**Comment by ChiaraTe** [comment]
Is there anyone who has an idea about how to solve the problem? thanks

**Comment by lassoan** [comment]
Have you followed all the recommendations described in the FAQ at http://perk-software.cs.queensu.ca/plus/doc/nightly/user/ApplicationfCal.html?

**Comment by salimohamadi** [comment]
Dear ChiaraTe,
I have a TELEMED US machine like you and I'm trying to set up a calibration process using fcal. would you please help me find my answers.
what transforms did you use for : "Probe_L12", "fCal_2.1" ModelToObjectTransform in the "Rendering" section of your config file.
and also for : "Image" To="TransducerOriginPixel" transform .
Thanks
Samaneh Alimohamdi

**Comment by lassoan** [comment]
Probe_L12: use identity matrix (diagonal 1.0).

fCal_2.1: see here https://github.com/PlusToolkit/PlusModelCatalog/blob/master/fCalPhantom/fCal_2/PhantomDefinition_fCal_2.1_Wiring_2.0.xml

Last column (first two values) of ImageToTransducerOriginPixel transform must contain the pixel coordinates of the center of the first image line (center of the transducer). Center of the transducer model will be aligned to this point. This transform is only used for visualization of the transducer and does not effect calibration result.
