### ISSUE TITLE
Recording Generic Serial Device output via fCal

### ISSUE THREAD

**Issue by TomJoosten** [PlusToolkit/PlusLib#349]
Hello,

Some time ago, I have been able to calibrate my setup (which consists of a Philips iU22 ultrasound device with the NDI Aurora EM tracking system) and get that to run using fCal. Currently, I'm trying to incorporate a sensor which is connected to an Arduino UNO. To this extent, I have used [the page on Generic Serial Devices](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceGenericSerial.html). Now I want to read the serial printed data from the device and save that with the corresponding US frame (preferably in the metadata). 

So what I think I need to do, is combine the transformation matrices and image data in a VirtualMixer, and thereafter do the same for the serial data. However, [the page on FileSequenceFile](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/FileSequenceFile.html) does not define a field for this purpose. What I am currently trying to do is to get the serial data to be in the metadata of the fCal temporal calibration simulation mode images .mha-file. So, I made the following changes to the example fCal temporal calibration file:

Added a SerialDevice:
```
    <Device 
      Id="SerialDevice"
      Type="GenericSerialDevice"
      SerialPort="3"
      BaudRate="9600"
      LineEnding="0d"
      MaximumReplyDurationSec="1.0"
      >
      <DataSources>
        <DataSource Id="SerialData" Type="FieldData"/>
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="FieldChannel">
          <DataSource Id="SerialData"/>
        </OutputChannel>
      </OutputChannels>
    </Device>
```
Changed the VirtualMixer to use the FieldChannel, as I am currently not interested in the transforms. I believe that if I wish to display both the transforms and images along the serial data I have to use several VirtualMixers. This is of later concern.

```
    <Device 
      Id="TrackedVideoDevice" 
      Type="VirtualMixer" >
      <InputChannels>
        <InputChannel Id="VideoStream" />
	<InputChannel Id="FieldChannel" />
      </InputChannels>
      <OutputChannels>
        <OutputChannel Id="TrackedVideoStream"/>
      </OutputChannels>
    </Device>
```
Added a PlusServer entry: (But I think this is the client side, to receive strings, am I right?)
```
  <PlusOpenIGTLinkServer 
    MaxNumberOfIgtlMessagesToSend="1" 
    MaxTimeSpentWithProcessingMs="50" 
    ListeningPort="18944" 
    LogWarningOnNoDataAvailable="false"
    OutputChannelId="FieldChannel" >
    <DefaultClientInfo> 
      <MessageTypes> 
        <Message Type="STRING" />
      </MessageTypes>
      <StringNames>
        <String Name="SerialData" />
      </StringNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>
```

However, this does not write the SerialData to the metadata (which I expected as something like `Seq_Frame0000_SerialData : Message` in the metadata). Do I need to include something like a VirtualCapture? I am unsure on how this works and if it is the best solution to capture the serial data. A .txt-file with readouts and their corresponding frame numbers also would suffice.

Could you give me some pointers?

Kind regards,

Tom Joosten

**Comment by TomJoosten** [comment]
I am conducting some tests with just the Arduino UNO serial data, to see what data comes in. It seems that the problem is here. I am using this (very minimal) config-file:

```
<PlusConfiguration version="2.1">
  <DataCollection StartupDelaySec="1.0">
    <DeviceSet 
      Name="PlusServer: Generic serial device" 
      Description="Send text and receive response through OpenIGTLink."
    />
    <Device 
      Id="SerialDevice"
      Type="GenericSerialDevice"
      SerialPort="3"
      BaudRate="9600"
      LineEnding="0d"
      MaximumReplyDurationSec="1.0"
      >
      <DataSources>
        <DataSource Id="SerialData" Type="FieldData"/>
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="FieldChannel">
          <DataSource Id="SerialData"/>
        </OutputChannel>
      </OutputChannels>
    </Device>
  </DataCollection>
  
</PlusConfiguration>
```
And by using `DiagDataCollection.exe` I receive the following errors:
```
 .\DiagDataCollection.exe --config-file=C:\Users\tom\PlusApp-2.6.0.2017
1129-Win64\config\GenericSerialDevice.xml
System start timestamp: 82353
Software version: Plus-2.6.0.268f9604 - Win64
60 seconds left...
Filtered timestamp is probably invalid for tracker buffer item with item index=78, time=1.617. The item may have been tagged with an inaccurate timestamp, therefore it will not be recorded.
Filtered timestamp is probably invalid for tracker buffer item with item index=79, time=1.69. The item may have been tagged with an inaccurate timestamp, therefore it will not be recorded.
Filtered timestamp is probably invalid for tracker buffer item with item index=80, time=1.793. The item may have been tagged with an inaccurate timestamp, therefore it will not be recorded.
Filtered timestamp is probably invalid for tracker buffer item with item index=81, time=1.891. The item may have been tagged with an inaccurate timestamp, therefore it will not be recorded.
Filtered timestamp is probably invalid for tracker buffer item with item index=82, time=1.993. The item may have been tagged with an inaccurate timestamp, therefore it will not be recorded.

...

---------------------------------
Device: SerialDevice
Channel: FieldChannel
|ERROR|061.428000| Failed to get timestamp report table from buffer - table is NULL!| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusTimestampedCircularBuffer.cxx(641)
|ERROR|061.498000| Failed to get timestamp report table from source 'SerialData' buffer!| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(1896)
Write HTML report to C:/Users/tom/PlusApp-2.6.0.20171129-Win64/data/DataCollectionReport-040618_144850.html
PS C:\Users\tom\PlusApp-2.6.0.20171129-Win64\bin
```
So I think I should fix the timestamps which are received from the Arduino UNO, however I have no clue on where to start.

Kind regards,

Tom

**Comment by Sunderlandkyl** [comment]
@lassoan

**Comment by adamrankin** [comment]
It would be a neat feature to have, if serial messages were written into a field data stream? This would enable time-synced recording of serial output and other forms of data.

**Comment by TomJoosten** [comment]
I am trying to get this to work. I have been following the guide (as you might've noticed) on adding a device. As I have little to no experience with C++ programming, I find this a challenging task. :-)

What I think I want: To update `vtkPlusDataCollection.dll` in my Plus installation to include my new device (which currently is just a plain copy of `vtkPlusMicrochipTracker` with a different name, `IGITDevice` ). I should therefore:

- Install Visual Studio 2017 Community, Qt 5.7 and CMake
- Clone the PlusBuild repository
- Edit all the CMake lists, according to the tutorial
- Copy the files from vtkPlusMicrochipTracker (.cxx and .h) change their names and place them into the folder `IGITDevice`
- Config and generate in CMake gui
- Open Visual Studio, select release mode and x64 (I seemed to get some errors with Win32) and build the solution.

The building runs without any errors. So I then go to `C:\D\PlusB-bin\bin\Release`, find my binary (`vtkPlusDataCollection.dll`) and copy that to my PlusApp folder? (`<PlusApp>\bin\`)

Should this suffice to add the device? (After this of course comes another hard part, actually modifying the device to do what I want. However, I can see that I can use the `textReceived` variable to write to another variable which I can send to the `.mhd`-file, I suppose.  

I am however getting some errors when opening fCal with my new `vtkPlusDataCollection.dll` file, which is shown below:

![image](https://user-images.githubusercontent.com/36889038/38498191-e357d1c4-3c03-11e8-9e73-6e2167da2595.png)

**Comment by adamrankin** [comment]
No need to copy the DLL. fCal.exe should be in `C:\D\PlusB-bin\bin\Release` as well. Is that the one you're running?

Cheers,
Adam

**Comment by adamrankin** [comment]
Ah, it looks like you're running fCal from an installed Plus, as opposed to the one that you built. If you run `C:\D\PlusB-bin\bin\Release\fCal.exe` things should work as expected.

**Comment by TomJoosten** [comment]
Yes, that was exactly what I was doing. I messed up some things trying to fix the issue and am now in the process of doing a clean build.

**Comment by adamrankin** [comment]
It is already stored! At least in frames. I'll see if the fields in frames are written to disc.

**Comment by adamrankin** [comment]
``` c++
  // Store in frame
  if (this->FieldDataSource != nullptr)
  {
    PlusTrackedFrame::FieldMapType fieldMap;
    fieldMap[this->FieldDataSource->GetId()] = textReceived;
    this->FieldDataSource->AddItem(fieldMap, this->FrameNumber);
    this->FrameNumber++;
  }
```

**Comment by adamrankin** [comment]
It should be written to file. You do need to add a virtual capture device to the config file.

**Comment by TomJoosten** [comment]
So, if I understand correctly, the GenericSerialDevice already processes the received serial input. This can then be saved by using a Virtual Capture such as in [this page](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceVirtualCapture.html), where I have to combine images and string by means of a Virtual Mixer first. I will try that! Thank you!

**Comment by adamrankin** [comment]
Correct! Sorry I didn't look into it sooner.

**Comment by TomJoosten** [comment]
I got everything to work! At first I was adding my serial data to each ultrasound frame. But I realized that it might be wise to record the serial data at a higher frame rate. Therefore, this configuration works:

```
<PlusConfiguration version="2.1">
  <DataCollection StartupDelaySec="1.0">
    <DeviceSet 
      Name="PlusServer: Generic serial device" 
      Description="Capture serial output"
    />
    <Device 
      Id="SerialDevice"
      Type="GenericSerialDevice"
      SerialPort="3"
      BaudRate="9600"
      LineEnding="0d"
      >
      <DataSources>
        <DataSource Id="SerialData" Type="FieldData"/>
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="FieldChannel">
          <DataSource Id="SerialData"/>
        </OutputChannel>
      </OutputChannels>
    </Device>
    <Device
      Id="CaptureDevice"
      Type="VirtualCapture"
      BaseFilename="SerialData.mha"
      EnableCapturingOnStart="FALSE" >
      <InputChannels>
        <InputChannel Id="FieldChannel" />
      </InputChannels>
    </Device>
  </DataCollection>
</PlusConfiguration>
```

Thank you for your help again Adam.

Kind regards,

Tom

**Comment by adamrankin** [comment]
My pleasure, I'm glad it works.
