### ISSUE TITLE
ToolTipToTool transform from StealthLink

### ISSUE THREAD

**Issue by remidel** [PlusToolkit/PlusLib#351]
Hello,

My project involves extracting neuro-navigation data from the Medtronic Stealthstation using StealthLink. I am using PLUS to extract and record my data in Slicer (using slicerIGT). I am also using the SureTrack2 tool from Medtronic to track my custom US probe.

I am able to visualize the SureTrack position relative to my CT skull model (extracted from the StealthStation) but my problem is that the tip of the SureTrack localizer is not the tip of my US probe but is the SureTrack itself. I can visualize the position of my probe with the StealthStation but I can only see the position of the SureTrack in Slicer. I tried to add a SureTrackTipToSureTrack transform using the pivot calibration module but the resulting transform is incorrect.

Is there a way I can extract the ToolTipToTool transform from StealthLink directly ? 

From the StealthLink Client I have seen that there is the ToolToTracker transform but also the tip and hind position of the localizer (see screenshot attached) but I don't know if it is possible to extract those information to have the correct position of the SureTrack localizer in Slicer.

Thank you in advance for your help,

Rémi

![stealthlink_suretrack](https://user-images.githubusercontent.com/33317181/38893517-6a5cc902-4282-11e8-929e-a60316ad81dc.png)

**Comment by Sunderlandkyl** [comment]
Unfortunately, the StealthLink device for Plus does not get the tip position or the ToolTipToTool transform from the StealthStation. Perhaps the StealthLink device could be updated at some point to include this information.

Currently, the only way to get ToolTipToTool is to use the pivot calibration in SlicerIGT.
What was the issue that you encountered with pivot calibration?

**Comment by lassoan** [comment]
Probably StealthStation cannot do spin calibration. It could make sense to double-check this with Medtronic but if this is the case then you have to either calibrate the tool in Slicer (it has both pivot and spin calibration) or work with the orientation that the StealthStation provides (probably it is fixed to the SureTrack's coordinate system).

**Comment by Sunderlandkyl** [comment]
You may also have to flip the StylusTipToStylus transform. 
![image](https://user-images.githubusercontent.com/9222709/38905043-0694094a-427c-11e8-9c32-d7d46c75c7e3.png)

**Comment by lassoan** [comment]
Is your probe a blunt tip pointing device? Is the tip sphere shaped? If yes then make a hole that matches the radius of the sphere and pivot in that hole.

**Comment by remidel** [comment]
No the probe has a non-spherical shape and is curved at the end. Here is a picture of the tip of my US probe :
![probetip](https://user-images.githubusercontent.com/33317181/39014839-5478e728-4413-11e8-8a50-dc1a197c56f2.png)

**Comment by lassoan** [comment]
You can 3D print cap (with a sharp or sphere tip) that you put on the probe when you do the pivot calibration. Since you know exactly the cap's dimensions, you can compute the offset between the cap's tip and your probe's tip.

**Comment by adamrankin** [comment]
Let us know if you have any further questions.
