### ISSUE TITLE
Connecting GE Logiq-e to PLUS

### ISSUE THREAD

**Issue by nmasoumi** [PlusToolkit/PlusLib#352]
I have a GE Logiq-e ultrasound machine and NDI Polaris. I could successfully connect my NDI Polaris to PLUS and visualize tracking data with Slicer. I couldn't find my ultrasound machine in the supported ultrasound machines of the PLUS. What is the best way to acquire tracked ultrasound data with my current devices?

Thanks in-advance for your help

**Comment by adamrankin** [comment]
Hello,

Unfortunately none of the Plus developers have had a GE machine, and so an interface to their system has not been implemented. As I understand it GE machines have a research interface, so if you have that available to you and are wiling to write an interface, that would be amazing (see https://plustoolkit.github.io/devicecode).

Failing that, you can use a screengrabber and either the MMF vidoe device (if Windows and screengrabber acts like webcam), or OpenCV device, or the Epiphan device if you buy an Epiphan screengrabber.

**Comment by nmasoumi** [comment]
Hi Adam,

Thanks for the response. I'm at IMPACT group at Concordia University, Montreal, Quebec. We are really interested in contributing to PLUS toolkit. I noticed GE doesn't have a research interface. Fortunately we have an Alpinoin ultrasound machine which has it. Is there any developer added Alpinion to PLUS or should we figure it out ourselves?

**Comment by adamrankin** [comment]
I am not familiar with the Alpinion system. There is no interface for it in Plus currently. Does it provide an SDK?

I had heard that the CINTEF group in Norway had research access to a GE system, I was hoping it was more prevalent.

**Comment by adamrankin** [comment]
Let us know if you need any further help developing a device interface.
