### ISSUE TITLE
Synchronize two video device 

### ISSUE THREAD

**Issue by nehk018** [PlusToolkit/PlusLib#353]
Hello,

I need to synchronize two input video devices (Infrared Camera and OpenCV camera). We try to use the Virtual Mixer, but i dind't work.

Our idea is using a configuration file as:
  
    <Device
      Id="VideoDevice"
      Type="VirtualMixer" >
      <InputChannels>
        <InputChannel Id="SeekStream" />
        <InputChannel Id="WebcamStream" />
      </InputChannels>

      <OutputChannels>
        <OutputChannel Id="WebcamseekStream"/>
      </OutputChannels>
    </Device> 

And then send both images with OpenIGTLink:

`<PlusOpenIGTLinkServer
    MaxNumberOfIgtlMessagesToSend="10"
    MaxTimeSpentWithProcessingMs="50"
    ListeningPort="18944"
    SendValidTransformsOnly="true"
    OutputChannelId="WebcamseekStream" >
    <DefaultClientInfo>
      <MessageTypes>
        <Message Type="IMAGE" />
        <Message Type="TRANSFORM" />
      </MessageTypes>
     <TransformNames>
        <Transform Name="ImageWebcamToImageSeek" />
     </TransformNames>
    <ImageNames>
      <Image Name="WebcamStream" EmbeddedTransformToFrame="WebcamStream" />
      <Image Name="SeekStream" EmbeddedTransformToFrame="SeekStream" />
    </ImageNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>`

Has Plus this functionality?

Thanks.
Jorge

**Comment by adamrankin** [comment]
Unfortunately, no, and this is by design. A channel can contain 0-1 video streams, and 0-N tracker/field streams.

To send two streams to Slicer, you would need two `<PlusOpenIGTLinkServer>` tags with unique ports. There is no time synchronization done by Plus, aside from timestamps in recordings.
