### ISSUE TITLE
Curve Maker not Installing, Please Help!

### ISSUE THREAD

**Issue by dotoleary** [PlusToolkit/PlusLib#354]
After installing Curve Maker from the extension tab and restarting slicer, Curve Maker does not appear in the informatics tab. 

I get the following critical errors upon starting 3d slicer:

Stream Error: 
File "<string>", line 1
    import imp;imp.load_source('CurveMaker', 'C:/Users/Mitchell O'Leary/AppData/Roaming/NA-MIC/Extensions-26813/CurveMaker/lib/Slicer-4.8/qt-scripted-modules/CurveMaker.py');del imp;
                                                                      ^
SyntaxError: invalid syntax

Qt Error: 
loadSourceAsModule - Failed to load file "C:/Users/Mitchell O'Leary/AppData/Roaming/NA-MIC/Extensions-26813/CurveMaker/lib/Slicer-4.8/qt-scripted-modules/CurveMaker.py"  as module "CurveMaker" ! 
Fail to instantiate module  "CurveMaker"

**Comment by lassoan** [comment]
This issue tracker is for Plus toolkit. I would suggest to use MarkupsToModel module instead, as it is an improved version of CurveMaker, but if you still want to use CurveMaker then report the error on its project page: https://github.com/tokjun/CurveMaker.

**Comment by dotoleary** [comment]
my apologies, thank you!

**Comment by dotoleary** [comment]
interesting observation: I get the same two errors after installing markupstomodel.... any suggestions as to what could be going on?

**Comment by lassoan** [comment]
You'll see these errors until you uninstall CurveMaker (or install an updated version of CurveMaker, where this error is fixed).

**Comment by dotoleary** [comment]
Thank you for being so helpful! 

I have uninstalled both CurveMaker and 3d slicer as a whole multiple times to no avail. 
I find it odd that I cannot download the Markupstomodel either, do you think my slicer download is corrupt in some fashion?

**Comment by lassoan** [comment]
What Slicer version you have installed and what operating system do you use?
