### ISSUE TITLE
Troubleshooting connection to hardware using Plus and SlicerIGT

### ISSUE THREAD

**Issue by arushriswarup** [PlusToolkit/PlusLib#359]
Hello, 

I am trying to use the Aurora NDI with SlicerIGT. I connected the NDI to the computer and attached the electromagnetic tracker to port 1. I have two issues. 
1. Plus gives me a connection failure message, see screenshot: 
![plus screenshot 1](https://user-images.githubusercontent.com/19232963/40143865-9de120e8-592a-11e8-8e47-0629d2df05d7.PNG)

2. Sometimes connection is successful, in which case I cannot get the status of the new connection to be on, see screenshots: 
![plus screenshot 2](https://user-images.githubusercontent.com/19232963/40143886-b6a92544-592a-11e8-8ae6-48f1fc089232.PNG)

![slicer screensho](https://user-images.githubusercontent.com/19232963/40143794-6ac9f388-592a-11e8-8164-cb3544094af7.PNG)

Please let me know if I am missing any steps. 

Thanks, 
Arushri

**Comment by arushriswarup** [comment]
Here is the log file for the Plus Server when connection is lost: 
|INFO|000.015000| Software version: Plus-2.2.0.4177 - Win64| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(57)
|INFO|000.015000| Logging at level 3 to file: C:/Users/SolidworksServer/PlusApp-2.2.0.4177-Win64/data/051618_165113_PlusLog.txt| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(58)
|INFO|000.017000| Supported devices: - 3dConnexion (ver: Plus-2.2.0) - AuroraTracker (ver: NDICAPI-3.1) - ChRobotics (ver: Plus-2.2.0) - Epiphan (ver: Plus-2.2.0) - FakeTracker (ver: Plus-2.2.0) - GenericSerialDevice (ver: Plus-2.2.0) - ICCapturing (ver: The Imaging Source UDSHL-3.2) - ImageProcessor (ver: Plus-2.2.0) - MmfVideo (ver: Plus-2.2.0) - NoiseVideo (ver: Plus-2.2.0) - OpenIGTLinkTracker (ver: OpenIGTLink v1.10.10) - OpenIGTLinkVideo (ver: OpenIGTLink v1.10.10) - PhidgetSpatial (ver: Plus-2.2.0) - PolarisTracker (ver: NDICAPI-3.1) - SavedDataSource (ver: Plus-2.2.0) - UsSimulator (ver: Plus-2.2.0) - VFWVideo (ver: Plus-2.2.0) - VirtualBufferedDiscCapture (ver: Plus-2.2.0) - VirtualDiscCapture (ver: Plus-2.2.0) - VirtualMixer (ver: Plus-2.2.0) - VirtualSwitcher (ver: Plus-2.2.0) - VirtualVolumeReconstructor (ver: Plus-2.2.0) | in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(62)
|INFO|000.023000| Server host name: SolidworksServe| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(82)
|INFO|000.035000| Server IP addresses: 169.254.176.2, 169.254.58.254, 142.20.171.63, 127.0.0.1| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(103)
|INFO|047.174000| Connect using configuration file: C:\Users\SolidworksServer\PlusApp-2.2.0.4177-Win64\config\PlusDeviceSet_Server_NDIAurora.xml| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(215)
|INFO|047.174000| Server process command line: "C:/Users/SolidworksServer/PlusApp-2.2.0.4177-Win64/bin/PlusServer.exe" --config-file="C:\Users\SolidworksServer\PlusApp-2.2.0.4177-Win64\config\PlusDeviceSet_Server_NDIAurora.xml" --verbose=3| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(135)
|INFO|047.266000|SERVER> Software version: Plus-2.2.0.4177 - Win64 | in PlusServerLauncher(0)
|INFO|047.266000|SERVER> Logging at level 3 (INFO) to file: C:/Users/SolidworksServer/PlusApp-2.2.0.4177-Win64/data/051618_165201_PlusLog.txt | in PlusServerLauncher(0)
|INFO|047.856000| Server process started successfully| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(142)
|ERROR|050.916000|SERVER> Active NDI tool not found in port 1. Make sure the tool is plugged in.; in ..\..\..\PlusLib\src\DataCollection\PolarisTracking\vtkNDITracker.cxx(861) | in PlusServerLauncher(0)
|ERROR|050.916000|SERVER> Failed to determine NDI port handle for tool ReferenceToTracker; in ..\..\..\PlusLib\src\DataCollection\PolarisTracking\vtkNDITracker.cxx(630) | in PlusServerLauncher(0)
|ERROR|050.916000|SERVER> Failed to enable tool ports; in ..\..\..\PlusLib\src\DataCollection\PolarisTracking\vtkNDITracker.cxx(309) | in PlusServerLauncher(0)
|ERROR|050.916000|SERVER> TrackerDevice: Cannot connect to data source, ConnectInternal failed; in ..\..\..\PlusLib\src\DataCollection\vtkPlusDevice.cxx(960) | in PlusServerLauncher(0)
|ERROR|050.916000|SERVER> Unable to connect device: TrackerDevice.; in ..\..\..\PlusLib\src\DataCollection\vtkDataCollector.cxx(299) | in PlusServerLauncher(0)
|ERROR|050.916000|SERVER> Datacollector failed to connect to devices; in ..\..\..\..\PlusLib\src\PlusServer\Testing\PlusServer.cxx(132) | in PlusServerLauncher(0)
|ERROR|050.980000| Server stopped unexpectedly. Return code: 0| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(333)
|INFO|050.980000| Disconnect request successful| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(209)
|INFO|573.337000| Connect using configuration file: C:\Users\SolidworksServer\PlusApp-2.2.0.4177-Win64\config\PlusDeviceSet_Server_NDIAurora.xml| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(215)
|INFO|573.338000| Server process command line: "C:/Users/SolidworksServer/PlusApp-2.2.0.4177-Win64/bin/PlusServer.exe" --config-file="C:\Users\SolidworksServer\PlusApp-2.2.0.4177-Win64\config\PlusDeviceSet_Server_NDIAurora.xml" --verbose=3| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(135)
|INFO|573.429000|SERVER> Software version: Plus-2.2.0.4177 - Win64 | in PlusServerLauncher(0)
|INFO|573.429000|SERVER> Logging at level 3 (INFO) to file: C:/Users/SolidworksServer/PlusApp-2.2.0.4177-Win64/data/051618_170047_PlusLog.txt | in PlusServerLauncher(0)
|INFO|574.019000| Server process started successfully| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(142)
|ERROR|577.183000|SERVER> Active NDI tool not found in port 1. Make sure the tool is plugged in.; in ..\..\..\PlusLib\src\DataCollection\PolarisTracking\vtkNDITracker.cxx(861) | in PlusServerLauncher(0)
|ERROR|577.183000|SERVER> Failed to determine NDI port handle for tool ReferenceToTracker; in ..\..\..\PlusLib\src\DataCollection\PolarisTracking\vtkNDITracker.cxx(630) | in PlusServerLauncher(0)
|ERROR|577.183000|SERVER> Failed to enable tool ports; in ..\..\..\PlusLib\src\DataCollection\PolarisTracking\vtkNDITracker.cxx(309) | in PlusServerLauncher(0)
|ERROR|577.183000|SERVER> TrackerDevice: Cannot connect to data source, ConnectInternal failed; in ..\..\..\PlusLib\src\DataCollection\vtkPlusDevice.cxx(960) | in PlusServerLauncher(0)
|ERROR|577.183000|SERVER> Unable to connect device: TrackerDevice.; in ..\..\..\PlusLib\src\DataCollection\vtkDataCollector.cxx(299) | in PlusServerLauncher(0)
|ERROR|577.183000|SERVER> Datacollector failed to connect to devices; in ..\..\..\..\PlusLib\src\PlusServer\Testing\PlusServer.cxx(132) | in PlusServerLauncher(0)
|ERROR|577.248000| Server stopped unexpectedly. Return code: 0| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(333)
|INFO|577.248000| Disconnect request successful| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(209)
|INFO|684.162000| Connect using configuration file: C:\Users\SolidworksServer\PlusApp-2.2.0.4177-Win64\config\PlusDeviceSet_Server_NDIAurora.xml| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(215)
|INFO|684.162000| Server process command line: "C:/Users/SolidworksServer/PlusApp-2.2.0.4177-Win64/bin/PlusServer.exe" --config-file="C:\Users\SolidworksServer\PlusApp-2.2.0.4177-Win64\config\PlusDeviceSet_Server_NDIAurora.xml" --verbose=3| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(135)
|INFO|684.254000|SERVER> Software version: Plus-2.2.0.4177 - Win64 | in PlusServerLauncher(0)
|INFO|684.254000|SERVER> Logging at level 3 (INFO) to file: C:/Users/SolidworksServer/PlusApp-2.2.0.4177-Win64/data/051618_170238_PlusLog.txt | in PlusServerLauncher(0)
|INFO|684.844000| Server process started successfully| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(142)
|ERROR|687.898000|SERVER> Active NDI tool not found in port 1. Make sure the tool is plugged in.; in ..\..\..\PlusLib\src\DataCollection\PolarisTracking\vtkNDITracker.cxx(861) | in PlusServerLauncher(0)
|ERROR|687.899000|SERVER> Failed to determine NDI port handle for tool ReferenceToTracker; in ..\..\..\PlusLib\src\DataCollection\PolarisTracking\vtkNDITracker.cxx(630) | in PlusServerLauncher(0)
|ERROR|687.900000|SERVER> Failed to enable tool ports; in ..\..\..\PlusLib\src\DataCollection\PolarisTracking\vtkNDITracker.cxx(309) | in PlusServerLauncher(0)
|ERROR|687.900000|SERVER> TrackerDevice: Cannot connect to data source, ConnectInternal failed; in ..\..\..\PlusLib\src\DataCollection\vtkPlusDevice.cxx(960) | in PlusServerLauncher(0)
|ERROR|687.901000|SERVER> Unable to connect device: TrackerDevice.; in ..\..\..\PlusLib\src\DataCollection\vtkDataCollector.cxx(299) | in PlusServerLauncher(0)
|ERROR|687.902000|SERVER> Datacollector failed to connect to devices; in ..\..\..\..\PlusLib\src\PlusServer\Testing\PlusServer.cxx(132) | in PlusServerLauncher(0)
|ERROR|687.998000| Server stopped unexpectedly. Return code: 0| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(333)
|INFO|687.999000| Disconnect request successful| in ..\..\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(209)

**Comment by Sunderlandkyl** [comment]
Hi,
Can you try connecting with the latest stable version?
http://perk-software.cs.queensu.ca/plus/packages/stable/

**Comment by lassoan** [comment]
> the updated log file in the latest comment is 2.6.

OK, good then. That version should be used.

According to the new logs, tracker is not found on port 4. Follow instructions on http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceNDI.html for setting correct SerialPort attribute in the configuration file.

**Comment by arushriswarup** [comment]
Connection successful - thanks so much!

**Comment by lassoan** [comment]
Awesome!

@adamrankin your automatic port detection code is working!

**Comment by adamrankin** [comment]
To be fair, it just tries to connect to every port lol.
