### ISSUE TITLE
NDI Vega Connection Failed 

### ISSUE THREAD

**Issue by EmptyZJH** [PlusToolkit/PlusLib#363]
Hi,
I am trying to use NDI Vega with SlicerIGT. Since there wasn't a config file in the folder, I copied the example vega config file to the folder. After I connected the NDI to the computer, it gave me a connection failed message. I'm wondering if there's something wrong with the config file. Below I attached the log file. Can anyone help me with that?
It says that it cannot find the file, so I created a path as shown and copied the src folder to the place. But still it cannot find the file. Also, the path is a little bit weird.
![srt](https://user-images.githubusercontent.com/27412210/40825089-2272372c-65a9-11e8-9415-1ea4e745ca45.PNG)

**Comment by adamrankin** [comment]
Can you upload the config file you used?

**Comment by EmptyZJH** [comment]
[NDIVega.txt](https://github.com/PlusToolkit/PlusLib/files/2066559/NDIVega.txt)

**Comment by adamrankin** [comment]
This config file does not match the error above. The device type "RTSPVideo" does not exist. Could you confirm the config file/error log match and re-upload?

**Comment by EmptyZJH** [comment]
[NdiError.zip](https://github.com/PlusToolkit/PlusLib/files/2071541/NdiError.zip)

Hi Adam, I feel so sorry about giving you the wrong config file. Here I uploaded a zipfile, which contains the config file, the error log and the rom. Tell me if you need extra information, thanks!

**Comment by adamrankin** [comment]
Is this downloaded Plus, or did you build it yourself? The build that you're using doesn't have OpenCV video enabled, and you've used RTSPVideo as an incorrect device type.

**Comment by adamrankin** [comment]
The sample config file is incorrect. I am fixing it and will upload a new version. The IP of your device will have to change to match your network.

**Comment by adamrankin** [comment]
See https://github.com/PlusToolkit/PlusLibData/commit/d2dcc2d2b8ad84eea14bd6147dcf289da1e4f405

**Comment by EmptyZJH** [comment]
![image](https://user-images.githubusercontent.com/27412210/41012701-7ac4fb10-6975-11e8-8b05-0e5398d1d737.png)

Hi, Adam.
I fixed the file as you did, and I  built the OpenCV. My plus is a downloaded one and I just installed it, does it make any differences? And I don't know where to insert the openCV path in the config file. I am a little it unfamiliar with the xml file, so thanks for your patience!

**Comment by adamrankin** [comment]
Does that file work? Are you able to connect?

**Comment by EmptyZJH** [comment]
Still, it cannot find OpenCVVideo. I checked the supported devices, though I don't know what it exactly it is, and found the NDITracker. I used it but some new errors occur.
[opencv_error.txt](https://github.com/PlusToolkit/PlusLib/files/2075043/opencv_error.txt)

[nditracker_error.txt](https://github.com/PlusToolkit/PlusLib/files/2075040/nditracker_error.txt)

**Comment by adamrankin** [comment]
The build of Plus does not have opencv video enabled. If you enable the checkbox in CMake and rebuild it will be available.

**Comment by EmptyZJH** [comment]
So I have to use a built one? Fine, i gotta try

**Comment by EmptyZJH** [comment]
![image](https://user-images.githubusercontent.com/27412210/41072924-3d32604e-6a33-11e8-9428-a6d4833e1d37.png)

You know, It seems a little bit stupid, but I don't know how to build it. Do i need to use the six folders? Or just the six pined ones? And I don't see an over all Cmakelist. What should I do?

**Comment by EmptyZJH** [comment]
You know, It seems a little bit stupid, but I don't know how to build it. Do i need to use all the 17 folders? Or just the six pined ones? And I don't see an over all Cmakelist. What should I do?
![image](https://user-images.githubusercontent.com/27412210/41073003-bfc1ed54-6a33-11e8-99a8-d30c18b1c42b.png)

**Comment by adamrankin** [comment]
If you clone and build the PlusBuild repository, it will download all necessary dependencies and build PlusLib (and PlusApp if options for it are set)

**Comment by EmptyZJH** [comment]
I built the PlusBuilt repository, but it outputs this:
![588da8ff2685be79f5554fd901e5134](https://user-images.githubusercontent.com/27412210/41136766-4f12b250-6b0a-11e8-9fda-cff9edbd4c9b.png)
So I used the offline mode,  however the problem still exists and it doesn't give me the path to add dependencies.
![2febf7948415217f95383ad3643bfd8](https://user-images.githubusercontent.com/27412210/41137147-3006ddda-6b0c-11e8-8568-e739cf405d0b.png)

**Comment by adamrankin** [comment]
Ah yes, this is a symptom if you download it instead of cloning the repository. You can ignore these messages and continue with the build.

**Comment by EmptyZJH** [comment]
Yes, but when I debug the project, it blocks here
![3adf66e92dde8e7e8d7e182bcd2f1a5](https://user-images.githubusercontent.com/27412210/41138046-35538aae-6b11-11e8-90e3-3fecfcb30b3d.png)

**Comment by EmptyZJH** [comment]
like 20% of the whole project

**Comment by adamrankin** [comment]
So, it just stops building? Are their any errors?

**Comment by EmptyZJH** [comment]
No erroes, it just stops

**Comment by adamrankin** [comment]
I've never seen this before. I don't know what's happening. I just did a build on my machine and it's working as expected. It may be an issue specific to your machine. Do you have another computer you can try on?

**Comment by lassoan** [comment]
Please first build Plus as described in the build instructions. It'll be much easier to see then what is different in your custom build. PlusBuild is essentially an example of how to build PlusLib and all required dependencies (OpenIGTLink, VTK, ITK, etc.) into applications (fCal, PlusServerLauncher, etc. in PlusApp repository).

**Comment by EmptyZJH** [comment]
Hi Adam and Lassoan,
I used another computer and succeeded building the PlusBuild. Then I built the PlusLib, then I failed in building PlusApp as below.
![image](https://user-images.githubusercontent.com/27412210/41267138-c70659d6-6e2c-11e8-822f-210b6600c8f5.png)

**Comment by EmptyZJH** [comment]
Hi Adam and Lassoan,
I used another computer and succeeded building the PlusBuild. Then I built the PlusLib, then I failed in building PlusApp as below.
![image](https://user-images.githubusercontent.com/27412210/41267425-0629c926-6e2e-11e8-94f7-fe6388bf9141.png)

**Comment by EmptyZJH** [comment]
Hi Adam and Lassoan,
So uh... As I followed your instructions, I changed another computer and I succeeded in building the PlusBuild. Then I built the PlusLib. But then I failed in building the PlusApp. Here I attempted to run the PlusServerLauncher, but the connection failed again. The error log is as below.
![srt](https://user-images.githubusercontent.com/27412210/41281550-42a476cc-6e64-11e8-9e74-41317bdb7035.PNG)
I think this is because I didn't build the PlusApp. But when I build the PlusApp, there is a warning which might be the problem.
![image](https://user-images.githubusercontent.com/27412210/41282517-d804ce5e-6e66-11e8-862f-4027023036aa.png)
So, how should I set the PlusLib directory in detail? Or should there be any other problems?
Thank you very much !

**Comment by lassoan** [comment]
Can you start PlusServer.exe successfully from the command-line?

**Comment by EmptyZJH** [comment]
I cannot. It says it needs config file.
![image](https://user-images.githubusercontent.com/27412210/41324731-df1a209a-6ee8-11e8-8814-7c0110c26ebe.png)

**Comment by EmptyZJH** [comment]
![image](https://user-images.githubusercontent.com/27412210/41325043-be03963c-6eea-11e8-8153-a543f31ca191.png)
It cannot identify the config file..

**Comment by lassoan** [comment]
you need to specify full path, including folder name and file extension

**Comment by EmptyZJH** [comment]
![2](https://user-images.githubusercontent.com/27412210/41332098-fc8324ee-6f0e-11e8-9708-0274a06231d4.JPG)
I used the full path and file name, it worked but still cannot connect to the device.
![1](https://user-images.githubusercontent.com/27412210/41332104-028a7810-6f0f-11e8-9c01-b2e47fb5fa02.JPG)

**Comment by adamrankin** [comment]
Did you adjust the config file to use the IP of your vega?

**Comment by EmptyZJH** [comment]
Yes Adam! I switched some figures but sitll cannot make it work.
Firstly, I tried this
![s](https://user-images.githubusercontent.com/27412210/41569641-398f1a9e-739e-11e8-8cae-b6b3c6f57668.JPG)
Then I tried this
![s1](https://user-images.githubusercontent.com/27412210/41569648-43b1f9f6-739e-11e8-8d84-47a8b7d6d918.JPG)
Then I even tried my PC's. I has two network cards on my PC, one IP address is assigned and the other one is automatic so I tried both. I don't know if this is the problem.
There might be another problem that causes the problem. I am using a USB adapter to connect the NDI and the PC, so can the IP change?
Thank you very much!

**Comment by EmptyZJH** [comment]
The Log File for all the 
![0](https://user-images.githubusercontent.com/27412210/41570113-e6106ace-739f-11e8-97cc-e743859f5243.JPG)
situations are the same and is attached below.

**Comment by adamrankin** [comment]
So, to clarify:

Are you using a USB/Ethernet dongle, and plugging in the Vega directly into that dongle? If so, you can try connecting to the Bonjour name (P9-00284) instead of an IP. Otherwise, you can assign it an IP, assign your USB/Ethernet dongle an IP on the same subnet, and that should work.

**Comment by EmptyZJH** [comment]
Adam, I know this might be emberrasing, 
![20180706190458](https://user-images.githubusercontent.com/27412210/42376047-5079355e-8150-11e8-9e7b-ad05713c3da0.jpg)
Look, here's the thing we're using, but...I tried the bonjour name and I also assign it an IP, neither worked.

**Comment by adamrankin** [comment]
I'm not sure. You may need to reach out to NDI support to figure out how to set the IP or the device or connect via Bonjour.

**Comment by EmptyZJH** [comment]
Hi @adamrankin and @lassoan  ,
I finally connected to the Vega. Because the IP is changing all the time, I have to test it before using it. Thank you for helping me during these time.
Jiahao

**Comment by adamrankin** [comment]
No problem, I'm pretty sure you can assign an IP to the Vega from within NDI Configure.
