### ISSUE TITLE
ndicapi include error when compiling PlusLib

### ISSUE THREAD

**Issue by IngEya** [PlusToolkit/PlusLib#366]
Hello I'm trying to use PlusLib with PLUS_USE_NDI option for communicating with ndi polaris.
I've downloaded ndicapi and was able to compile it with CMAKE, Now i'm tring to compile PlusLib but i keep having this error when i check PLUS_USE_NDI option:

CMake Error at src/PlusDataCollection/CMakeLists.txt:373 (MESSAGE):
 Wanted to add ndicapi library to install, but dependent files don't exist.
Do you need to build it?
Configuring incomplete, errors occurred!

![01](https://user-images.githubusercontent.com/35607659/40980122-068d1464-68d8-11e8-94aa-1757c3cd008e.PNG)

**Comment by lassoan** [comment]
When you first build Plus, please follow build instructions very closely: https://github.com/PlusToolkit/PlusBuild/blob/master/Docs/BuildInstructionsWindows.md

Once you have a working build using the official build instructions, you can try to build it differently. If something is not working as expected, then compare your custom build to the successful build. if you want to build Plus as part of your application, then copy-paste relevant code parts from the PlusBuild repository to yours.

**Comment by IngEya** [comment]
Well yes i'm trying to add PlusLib to my application and i'm having difficulties doing that. 
In fact, i want to use PlusLib for communicating with Polaris and retrieve tracking datas. So as first step i included ndicapi without using PlusBuild to my application. And now with PlusLib it's more difficult . 
Can you please explane to me how to do that exactly.

**Comment by adamrankin** [comment]
If you give the instructions here a try:
https://github.com/PlusToolkit/PlusBuild/blob/master/Docs/BuildInstructionsWindows.md

and are still unable to build, let us know. Those instructions are updated fairly regularly and should work.

Once everything is built, you can write your own application that uses PlusLib via CMake's FIND_PACKAGE(PlusLib) command.

**Comment by IngEya** [comment]
In deed, using PlusBuild i can build without any problem. But, because i keep having problems with the importation of PlusLib in my application i thought about directly building PlusLib.

I am using find_package(PlusLib) and i could include the files in my app but i couldn't access the functions that were exported using dllExport ( Ex PlusStatus) because my application is using a dllExport by it self, and just couldn't link the two. That's why i wanted to know what is the relevant code and if you have an example of CMakeLists configuration for such an app.

**Comment by adamrankin** [comment]
Could you post your applications CMakeLists.txt? I can double check it. Could you also post the build errors you receive when building your application?

**Comment by adamrankin** [comment]
Let us know if you continue experiencing the issue.
