### ISSUE TITLE
 Tool TimeStamp Update failed for tool: ProbeToReference with timestamp: XXXX

### ISSUE THREAD

**Issue by ChiaraTe** [PlusToolkit/PlusLib#367]
Hi,
in our setup, we are using an OpenIGTLinkTracker device, but the following error " Tool TimeStamp Update failed for tool: [...]" seems to prevent the update of Probe pose (we checked the code OpenIGTLinkTracker in PlusLib). The poses are sent from a robotic manipulator working in ROS environment, through a ROSIGTLBRIDGE. We have tested different openigtlink settings in Plus config file: 	  UseReceivedTimestamps,   AcquisitionRate.

Do you have any suggestion on how to fix this problem?

**Comment by adamrankin** [comment]
Could you post the error log and the config file you're using?

**Comment by ChiaraTe** [comment]
Thanks

[log.txt](https://github.com/PlusToolkit/PlusLib/files/2079401/log.txt)

[Panda_multi - Copia.txt](https://github.com/PlusToolkit/PlusLib/files/2079404/Panda_multi.-.Copia.txt)

**Comment by ChiaraTe** [comment]
"By the way, the same ROSIGTBRIDGE configuration is correctly working with Slicer, where we are able to receive transformations  and visualize their motions."

**Comment by ChiaraTe** [comment]
we have still same error, if we set  UseReceivedTimestamps flag to false we can correctly see in the "Tool state display"  the status (OK) of the "ProbeToReference". Otherwise (with  UseReceivedTimestamps=false) we can't see the status. we are attaching the Log file, the configuration file is the same as above. 
Any suggestion is well accepted


[060818_101503_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/2083658/060818_101503_PlusLog.txt)

**Comment by adamrankin** [comment]
Is it easy to set up a ROSIGTBRIDGE server? Do they have an example that uses pre-recorded data so I can set up a test environment?

**Comment by lassoan** [comment]
If you want to use the received timestamps then you need to synchronize the clocks of the computer running PlusServer and the computer that has the ROS node. If you still have problems then it might be possible that the ROS-OpenIGTLink bridge does not set the OpenIGTLink message timestamps correctly.

**Comment by adamrankin** [comment]
Also, if you are able to run it with --verbose=4 (DEBUG messages), I think we'll get some useful information. I have a feeling it has to do with timestamp matching or filtering (maybe).

**Comment by adamrankin** [comment]
Reopen if needed.
