### ISSUE TITLE
Tracking Quality number for 3D Guidance trakSTAR 

### ISSUE THREAD

**Issue by andinet** [PlusToolkit/PlusLib#369]
A quick question

I am using [TrackingTest ](https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusDataCollection/Testing/TrackingTest.cxx) to connect to a 3D Guidance trakSTAR  and collect position and orientation information of an ultrasound probe.  I am interested to capture and display the tracking "Quality number".  Is the best option to modify this test program or is there a better tool available in PlusLib or PlusApp for this?

thanks
Andinet

**Comment by Sunderlandkyl** [comment]
@lassoan

**Comment by lassoan** [comment]
The tool ports quality1, quality2, and quality3 provide the quality values for all the tools. See details here:
http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceAscension3DG.html

**Comment by adamrankin** [comment]
Let us know if you need any more detail.
