### ISSUE TITLE
probe calibration using fcal

### ISSUE THREAD

**Issue by salimohamadi** [PlusToolkit/PlusLib#370]
Hi,
In preparing the configuration file for probe calibration using fcal, there should be "ModelToObjectTransform" in the "Rendering" section. if anyone has these transforms for "TELEMED L12 probe" and "fCal_2.1 phantom"? 
In addition there is a transform:  Transform From="Image" To="TransducerOriginPixel" . what about this one.
now I have copied these parts from the template files from the plus toolkit website as follows:

```
<Rendering WorldCoordinateFrame="Reference">
    <DisplayableObject Type="Model" ObjectCoordinateFrame="TransducerOrigin" Id="ProbeModel"
      File="Probe_L12.stl"
      ModelToObjectTransform="
        -1 0 0 29.7
        0 -1 0 1.5
        0 0 1 -14
        0 0 0 1" />
    <DisplayableObject Type="Model" ObjectCoordinateFrame="Reference" Id="Volume"/>
    <DisplayableObject Type="Model" ObjectCoordinateFrame="StylusTip" Id="StylusModel" File="Stylus_Example.stl" />
    <DisplayableObject Id="PhantomModel" Type="Model" ObjectCoordinateFrame="Phantom"
      Opacity="0.6"
      File="fCal_2.1.stl"
      ModelToObjectTransform="
        1 0 0 0
        0 1 0 0
        0 0 1 0
        0 0 0 1" />
    <DisplayableObject Type="Image" ObjectCoordinateFrame="Image" Id="LiveImage"/>
  </Rendering>

  <CoordinateDefinitions>
    <Transform From="Image" To="TransducerOriginPixel"
      Matrix="1 0 0 -410
              0 1 0 5
              0 0 1 0
              0 0 0 1"
      Date="2011.12.06 17:57:00" Error="0.0" />    
  </CoordinateDefinitions>
```

thanks

**Comment by Sunderlandkyl** [comment]
@lassoan (In case I say anything untrue).
I think that these should be fine.
The ModelToObjectTransform is model specific, so if you are using the probe model that comes with fCal, then it should work.

See: http://perk-software.cs.queensu.ca/plus/doc/nightly/user/ApplicationfCal.html (look for ModelToObjectTransform)

Image to Transducer origin pixel should be the transform from the image origin to the centre of the first line of the image, in the Image coordinate system.

See: http://perk-software.cs.queensu.ca/plus/doc/nightly/user/ApplicationfCalCoordinateSystemDefinitions.html
