### ISSUE TITLE
loading calibration result in PLUS

### ISSUE THREAD

**Issue by salimohamadi** [PlusToolkit/PlusLib#371]
Hi,
my question is that how can I load the probe calibration result using fcal to "PLUS" application.
If I should write the resulting transform to the configuration file manually or load a .xml file in PLUS.

Thanks,
Samaneh Alimohamadi

**Comment by Sunderlandkyl** [comment]
You can add the resulting transform to your config file.

**Comment by salimohamadi** [comment]
thanks
