### ISSUE TITLE
Latest PlusApp binary not using latest PlusLib commit

### ISSUE THREAD

**Issue by jamesobutler** [PlusToolkit/PlusLib#390]
I downloaded the latest PlusApp binary PlusApp-2.7.0.20180726-Win64.exe to try the newest update to the IntelRealSense device as it has changed from a tracker to a video device, but PlusVersion is indicating that it is using `Software version: Plus-2.7.0.bd3a71ab - Win64`.

Is there an automated build issue?  I looked at the cdash but couldn't tell which build system is used to upload the PlusApp binaries to the main website.

**Comment by Sunderlandkyl** [comment]
There was a build error the latest package hasn't been updated yet.
http://perkdata.cs.queensu.ca/CDash/viewBuildError.php?buildid=99611

**Comment by jamesobutler** [comment]
Ahh gotcha. Sorry I was only looking at the PlusApp dashboard, not the PlusBuild dashboard.

**Comment by Sunderlandkyl** [comment]
Besides the StealthLink package, all of the packages should now be updated. The StealthLink package should be available tomorrow.
