### ISSUE TITLE
Endobronchial Ultrasound Probe 

### ISSUE THREAD

**Issue by slavasani** [PlusToolkit/PlusLib#396]
Hello,

I'm working on endobronchial ultrasound navigation and I'd like to know is it possible to use fCAL software to perform calibration between NDI Aurora electromagnetic sensor and this kind of ultrasound probes. 

Thank you.

**Comment by adamrankin** [comment]
I would assume so. Do you have a screen grabber (example: [Epiphan](https://www.epiphan.com/))? Or does your ultrasound vendor have a research interface for streaming of US images?

**Comment by slavasani** [comment]
It doesn't have a research interface, I can just capture the whole screen that contains video bronchoscopy as well, I use pinnacle capture card in order to capture the screen.

**Comment by adamrankin** [comment]
Then its a matter of configuration! Is the capture card recognized as a webcam? Which OS?

**Comment by adamrankin** [comment]
So, you can use the MMF device or OpenCV video device to capture video, pair that with a NDI Aurora tracker device, and a virtual mixer, and you're off to the races.

Some examples are [MMF](https://github.com/PlusToolkit/PlusLibData/blob/master/ConfigFiles/PlusDeviceSet_Server_MmfVideoCapture.xml), [OpenCV](https://github.com/PlusToolkit/PlusLibData/blob/master/ConfigFiles/PlusDeviceSet_Server_OpenCVWebcam.xml), [NDI Aurora](https://github.com/PlusToolkit/PlusLibData/blob/master/ConfigFiles/PlusDeviceSet_Server_NDIAurora.xml), and an example of [mixing two devices together](https://github.com/PlusToolkit/PlusLibData/blob/master/ConfigFiles/PlusDeviceSet_Server_Ultrasonix_L14-5_Ascension3DG_calibrated.xml)

With a config file created, you can play with the [cropping](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/Configuration.html#ClipRectangleOrigin) attributes to remove any extraneous image contents from the screen capture.

**Comment by slavasani** [comment]
Thank you so much for your help. I will go for it.

در تاریخ ۸ اوت ۲۰۱۸ ۹:۰۹ بعدازظهر، "Adam Rankin" <notifications@github.com>
نوشت:
