### ISSUE TITLE
How to get video URL on vega?

### ISSUE THREAD

**Issue by EmptyZJH** [PlusToolkit/PlusLib#397]
Hi Adam, 

This is Jiahao again! I regret to bother you but I don't know how to configure the video URL properly. Below is the config-file you gave me.

[PlusDeviceSet_Server_NDIVega.txt](https://github.com/PlusToolkit/PlusLib/files/2277316/PlusDeviceSet_Server_NDIVega.txt)

But I cannot get the video. Can you tell me how to fix this? Thank you!

**Comment by EmptyZJH** [comment]
![srt](https://user-images.githubusercontent.com/27412210/43949675-c9c32e02-9cc0-11e8-86f1-55b61474ffc1.PNG)

Here is the log file.

**Comment by adamrankin** [comment]
That URL does look correct. Your alternative is to use the Bonjour name, which is something like `rtsp://p9-XYZ123/video`
