### ISSUE TITLE
Question: Using SetCommand to update acquisition rate?

### ISSUE THREAD

**Issue by jamesobutler** [PlusToolkit/PlusLib#398]
Could `Acquisition Rate=` be defined as a parameter to change as part of the new Get/SetCommand framework? Maybe as another [PlusServer command](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/PlusServerCommands.html)?

I currently don't have access to change Frame Rate of a linear array based video device due to its SDK, but I'm hoping I could set the `Acquisition Rate=` parameter of the video device on the fly instead as a way to control frame rate.  I would want to set different acquisition rates prior to new video captures as a way to reduce the MHD+RAW data size. I could also use this functionality to modulate RAW frame spacing when I'm using motion stages for a continuous 3D volume capture scan.  Changing this on the fly like other ultrasound imaging parameters would be great so I don't have to stop and restart the server again with an updated configuration.

Also, where in the capture process would you recommend restricting frame rate (video device>virtual mixer>virtual capture)?  If I want stream FPS in 3D Slicer and capture FPS to be the same, then is it best to restrict it at the video device level to eliminate extra processing by any downstream device?  Just thinking about various other ways of using the parameter, I guess you could restrict it to say 10 FPS at virtual capture to reduce saved file size, but still pass a higher frame rate across PlusOpenIGTLinkServer using the virtual mixer output channel.

**Comment by adamrankin** [comment]
>Could Acquisition Rate= be defined as a parameter to change as part of the new Get/SetCommand framework?

Sorry James, didn't mean to ignore this, it's a great idea.

> Also, where in the capture process would you recommend restricting frame rate (video device>virtual mixer>virtual capture)?
I think the capture FPS is restricted to the source FPS, it doesn't record duplicate frames if no new frame is available.

**Comment by jamesobutler** [comment]
No problem. Yeah the linear array we have has a set frame rate for given parameters and can't be set directly. Changing imaging depth influences frame rate, but I was looking for a way to modulate frame rate acquisition on the fly while keeping those other parameters the same. When we use robotic stages to move a probe to create 3D volumes, changing the frame rate is one way to get a desired Z dimension step size in addition to motion speed. Not having to start the server again when trying to use different acquisition rate values could act as a workaround for not being able to change frame rate directly for this device.

**Comment by adamrankin** [comment]
Self note: @adamrankin 

Check if capture device continues recording last known frame if input is frozen

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
