### ISSUE TITLE
Problem with creating the Scene

### ISSUE THREAD

**Issue by salimohamadi** [PlusToolkit/PlusLib#399]
Hi.
After calculating the prob calibration matrix by fcal, now I want to display the scene using the 3D Slicer software. But there are two problems.
First, I can not display the ultrasound image in the correct location (attached to the probe). ( attached pictures 1 and 2 shows the transforms [used] for the scene )
Second, there is a 90-degree rotation between the probe position and what is seen in the image.
looking forward to hearing from the PLUS friendly team. ( at
![1](https://user-images.githubusercontent.com/40351746/44029205-b29ca336-9f11-11e8-9f5d-a1e10966ece3.jpg)
![2](https://user-images.githubusercontent.com/40351746/44029206-b2ddc1cc-9f11-11e8-8236-2c387e31b7ee.jpg)
![3](https://user-images.githubusercontent.com/40351746/44029207-b30313dc-9f11-11e8-8311-1fe12d404b26.jpg)
![4](https://user-images.githubusercontent.com/40351746/44029208-b328ed1e-9f11-11e8-9f9a-79755ebf1640.jpg)

Thanks
Samaneh Alimohamadi

**Comment by Sunderlandkyl** [comment]
Can you attach your config file?

**Comment by salimohamadi** [comment]
Hi.
Thanks for answering.
two config files are attached: one used in fcal for probe calibration and
one used in PLUS SERVER for data aquisition and visualization.

Thanks

**Comment by Sunderlandkyl** [comment]
Unfortunately, you can't send attachments to GitHub through email.
You can add the config file as embedded text in the message or attach directly through the web interface.

**Comment by salimohamadi** [comment]
the calibration step was repeated but the rotation between the probe and its picture is steel remained. I think the problem backs to the transforms and their hierarchy defined in the 3D slicer ( a picture attached previously). would you please help me how should it be for both the probe and the US image.

I have two config file:
 1-for calibration
2- for data acquisition and scene visualization

<PlusConfiguration version="2.5" PlusRevision="Plus-2.6.0.d3024ea5 - Win32">
  <DataCollection StartupDelaySec="1">
    <DeviceSet Name="fCal: TELEMED (L12 probe) + NDI Aurora Tracker (Probe, Reference, Stylus) - fCal phantom 2.1_20180728_141649CalibratedError0.815458 "
	Description="TELEMED (L12 probe) and NDI Aurora Tracker Both Data Acquisition" />
    	
	<Device
      Id="TrackerDevice"
      Type="AuroraTracker"
      SerialPort="1"
      ToolReferenceFrame="Tracker"
      BaudRate="0"
      MeasurementVolumeNumber="0"
      LocalTimeOffsetSec="-0.000317143">
      <DataSources>
        <DataSource Type="Tool" Id="Stylus" PortName="0" BufferSize="150">
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
        </DataSource>
        <DataSource Type="Tool" Id="Reference" PortName="1" BufferSize="150">
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
        </DataSource>
        <DataSource Type="Tool" Id="Probe" PortName="2" BufferSize="150">
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
        </DataSource>
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream">
          <DataSource Id="Stylus" />
          <DataSource Id="Reference" />
          <DataSource Id="Probe" />
        </OutputChannel>
      </OutputChannels>
    </Device>
    <Device
      Id="VideoDevice"
      Type="TelemedVideo"
      DepthMm="40"
      FrequencyMhz="10"
      DynRangeDb="62"
      GainPercent="90"
      PowerPercent="88">
      <DataSources>
        <DataSource Type="Video" Id="Video" PortUsImageOrientation="UF" BufferSize="150" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStream" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>
    <Device Id="TrackedVideoDevice" Type="VirtualMixer">
      <InputChannels>
        <InputChannel Id="TrackerStream" />
        <InputChannel Id="VideoStream" />
      </InputChannels>
      <OutputChannels>
        <OutputChannel Id="TrackedVideoStream" />
      </OutputChannels>
    </Device>
  </DataCollection>
  <CoordinateDefinitions>
    <Transform From="Image" To="Probe"
      Matrix="
        -0.0747706	-0.00855718	-0.0388065	16.2385
        -0.0413121	0.00997615	0.0711326	2.1052
        -0.002763	0.0776899	-0.0134085	37.3529
        0	0	0	1"
       Error="0.815458" Date="072818_141638" />
    <Transform From="Image" To="TransducerOriginPixel"
      Matrix="
        1	0	0	-410
        0	1	0	5
        0	0	1	0
        0	0	0	1"
       Date="2011.12.06 17:57:00" />
    <Transform From="Phantom" To="Reference"
      Matrix="
        -0.00405981	0.246539	 0.969124	-21.8315
         0.973432	0.222849	-0.0526134	 21.1896
        -0.22894	0.943163	-0.240893	-8.92953
         0	        0	         0	         1"
       Error="0.529971" Date="072518_164413" />
    <Transform From="StylusTip" To="Stylus"
      Matrix="
         0.99799	 0	        0.0633689	7.09359
        -0.0018724	 0.999563	0.0294882	3.30094
        -0.0633412	-0.0295476	0.997554	111.667
         0	         0	        0	        1"
       Error="0.21318" Date="072518_164137" />
    <Transform From="TransducerOriginPixel" To="TransducerOrigin"
      Matrix="
        0.08547	0	        0	        0 
        0	    0.0787928	0	        0
        0	    0	        0.0821315	0
        0	    0	        0	        1"
       Date="072818_141638" />
  </CoordinateDefinitions>
  
  <Rendering WorldCoordinateFrame="Reference" DisplayedImageOrientation="MFA">
    <DisplayableObject Type="Model" ObjectCoordinateFrame="TransducerOrigin" Id="ProbeModel"   File="UsProbe_Telemed_L12.stl"
      ModelToObjectTransform="
	    1	0	0	-13
        0	1	0	1
        0	0	1	0
        0	0	0	1" />
    <DisplayableObject Type="Model" ObjectCoordinateFrame="Reference"        Id="Volume" />
    <DisplayableObject Type="Model" ObjectCoordinateFrame="StylusTip"        Id="StylusModel"   File="Stylus_Example.stl" />
    <DisplayableObject Type="Model" ObjectCoordinateFrame="Phantom"          Id="PhantomModel"  File="fCal_2.1.stl"             Opacity="0.6"
      ModelToObjectTransform="
        1	0	0	0
        0	1	0	0
        0	0	1	0
        0	0	0	1" />
    <DisplayableObject Type="Image" ObjectCoordinateFrame="Image" Id="LiveImage" />
  </Rendering>
  
  <Segmentation
    ApproximateSpacingMmPerPixel="0.078"
    MorphologicalOpeningCircleRadiusMm="0.27"
    MorphologicalOpeningBarSizeMm="2.0"
    ClipRectangleOrigin="27 27"
    ClipRectangleSize="766 562"
    MaxLinePairDistanceErrorPercent="10"
    AngleToleranceDegrees="10"
    MaxAngleDifferenceDegrees="10"
    MinThetaDegrees="-70"
    MaxThetaDegrees="70"
    MaxLineShiftMm="10.0"
    ThresholdImagePercent="10"
    CollinearPointsMaxDistanceFromLineMm="0.6"
    UseOriginalImageIntensityForDotIntensityScore="FALSE"
    NumberOfMaximumFiducialPointCandidates="20" />
  <PhantomDefinition>
    <Description Name="fCAL" Type="Multi-N" Version="2.1" WiringVersion="2.5" Institution="Queen&apos;s University PerkLab" />
    <Geometry>
      <Pattern Type="NWire">
        <Wire Name="7:G1_g1" EndPointFront="30.0 0.0 0.0" EndPointBack="30.0 0.0 40.0" />
        <Wire Name="8:L1_h1" EndPointFront="55.0 0.0 0.0" EndPointBack="35.0 0.0 40.0" />
        <Wire Name="9:M1_m1" EndPointFront="60.0 0.0 0.0" EndPointBack="60.0 0.0 40.0" />
      </Pattern>
      <Pattern Type="NWire">
        <Wire Name="4:G3_g3" EndPointFront="30.0 10.0 0.0" EndPointBack="30.0 10.0 40.0" />
        <Wire Name="5:H3_l3" EndPointFront="35.0 10.0 0.0" EndPointBack="55.0 10.0 40.0" />
        <Wire Name="6:M3_m3" EndPointFront="60.0 10.0 0.0" EndPointBack="60.0 10.0 40.0" />
      </Pattern>
      <Pattern Type="NWire">
        <Wire Name="1:H5_h5" EndPointFront="35.0 20.0 0.0" EndPointBack="35.0 20.0 40.0" />
        <Wire Name="2:L5_i5" EndPointFront="55.0 20.0 0.0" EndPointBack="40.0 20.0 40.0" />
        <Wire Name="3:M5_m5" EndPointFront="60.0 20.0 0.0" EndPointBack="60.0 20.0 40.0" />
      </Pattern>
      <Landmarks>
        <Landmark Name="#1" Position="-32.53 -5.25 45.0" />
        <Landmark Name="#2" Position="-32.53 -5.25  5.0" />
        <Landmark Name="#3" Position="-32.53 19.75 -5.0" />
        <Landmark Name="#4" Position="-32.53 19.75 45.0" />
        <Landmark Name="#5" Position="105.47 -5.25 -5.0" />
        <Landmark Name="#6" Position="105.47 -5.25 45.0" />
        <Landmark Name="#7" Position="105.47 14.75 -5.0" />
        <Landmark Name="#8" Position="105.47 19.75 45.0" />
        <Landmark Name="#9" Position=" -3.53 -9.25 45.0" />
        <Landmark Name="#10" Position=" 41.47 -9.25 45.0" />
        <Landmark Name="#11" Position=" 86.47 -9.25 45.0" />
        <Landmark Name="#12" Position=" 96.47 -9.25 30.0" />
        <Landmark Name="#13" Position=" 86.47 -9.25 -5.0" />
        <Landmark Name="#14" Position=" 21.47 -9.25 -5.0" />
        <Landmark Name="#15" Position=" -3.53 -9.25 -5.0" />
        <Landmark Name="#16" Position="-13.53 -9.25 10.0" />
      </Landmarks>
    </Geometry>
  </PhantomDefinition>
  <VolumeReconstruction
    OutputSpacing="0.5 0.5 0.5"
    ClipRectangleOrigin="0 0"
    ClipRectangleSize="820 616"
    Interpolation="LINEAR"
    Optimization="FULL"
    CompoundingMode="MEAN"
    FillHoles="OFF" />
  <fCal
    PhantomModelId="PhantomModel"
    ReconstructedVolumeId="Volume"
    TransducerModelId="ProbeModel"
    StylusModelId="StylusModel"
    ImageDisplayableObjectId="LiveImage"
    NumberOfCalibrationImagesToAcquire="200"
    NumberOfValidationImagesToAcquire="100"
    NumberOfStylusCalibrationPointsToAcquire="200"
    RecordingIntervalMs="100"
    MaxTimeSpentWithProcessingMs="70"
    ImageCoordinateFrame="Image"
    ProbeCoordinateFrame="Probe"
    ReferenceCoordinateFrame="Reference"
    TransducerOriginCoordinateFrame="TransducerOrigin"
    TransducerOriginPixelCoordinateFrame="TransducerOriginPixel"
    TemporalCalibrationDurationSec="10"
    FixedChannelId="VideoStream"
    FixedSourceId="Video"
    MovingChannelId="TrackerStream"
    MovingSourceId="ProbeToTracker"
    DefaultSelectedChannelId="TrackedVideoStream"
    FreeHandStartupDelaySec="5" />
	
  <vtkPlusPivotCalibrationAlgo 
  ObjectMarkerCoordinateFrame="Stylus" 
  ReferenceCoordinateFrame="Reference" 
  ObjectPivotPointCoordinateFrame="StylusTip" />
  
  <vtkPlusPhantomLandmarkRegistrationAlgo 
  PhantomCoordinateFrame="Phantom" 
  ReferenceCoordinateFrame="Reference" 
  StylusTipCoordinateFrame="StylusTip" 
  DetectionTimeSec="1.0" 
  StylusTipMaximumDisplacementThresholdMm="1.8" />
  
  <vtkPlusProbeCalibrationAlgo 
  ImageCoordinateFrame="Image" 
  ProbeCoordinateFrame="Probe" 
  PhantomCoordinateFrame="Phantom" 
  ReferenceCoordinateFrame="Reference" />
  
</PlusConfiguration>





<PlusConfiguration version="2.3">

  <DataCollection StartupDelaySec="1.0">
    <DeviceSet 
      Name="PlusServer: TELEMED (L12 probe) and NDI Aurora Tracker (Probe, Reference, Stylus) Both Data Acquisition - fCal phantom 2.1_20180728_141649CalibratedError0.815458"
	  Description="TELEMED (L12 probe) and NDI Aurora Tracker (Probe, Reference, Stylus) Both Data Acquisition" />     		
	
	<Device
      Id="TrackerDevice"
      Type="AuroraTracker"  
      SerialPort="1"
      ToolReferenceFrame="Tracker" >
      <DataSources>
        <DataSource Type="Tool" Id="Stylus"             PortName="0" />
		<DataSource Type="Tool" Id="Reference"          PortName="1" />
		<DataSource Type="Tool" Id="Probe"              PortName="2" />
		<DataSource Type="Tool" Id="WaterTank"          PortName="3" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream">
          <DataSource  Id="Stylus" />
		  <DataSource  Id="Reference" />
		  <DataSource  Id="Probe" />
		  <DataSource  Id="WaterTank" />
		  </OutputChannel>
      </OutputChannels>
    </Device>
	<Device 
		Id="VideoDevice" 
		Type="TelemedVideo" 
        DepthMm="40"
        FrequencyMhz="10"
        DynRangeDb="62"
        GainPercent="90"
        PowerPercent="88" >
	<DataSources>
		<DataSource 
		Type="Video" 
		Id="Video" 
		PortUsImageOrientation="UN" 
		BufferSize="150" />	
	</DataSources>
		<OutputChannels>
		<OutputChannel Id="VideoStream" 
		VideoDataSourceId="Video"/>
		</OutputChannels>
	</Device>
	
	<Device Id="CaptureDevice" 
	        Type="VirtualDiscCapture" 
	        BaseFilename="Recording.mha" 
	        EnableCapturingOnStart="FALSE" >
		<InputChannels>
		<InputChannel Id="VideoStream"/>
		</InputChannels>
	</Device>
	
	<Device 
	Id="TrackedVideoDevice" 
	Type="VirtualMixer">
	<InputChannels>
		<InputChannel Id="TrackerStream"/>
		<InputChannel Id="VideoStream"/>
	</InputChannels>
	<OutputChannels>
		<OutputChannel Id="TrackedVideoStream"/>
	</OutputChannels>
	</Device>
	
</DataCollection>
<PlusOpenIGTLinkServer 
	MaxNumberOfIgtlMessagesToSend="1" 
	MaxTimeSpentWithProcessingMs="50" 
	ListeningPort="18944" 
	SendValidTransformsOnly="true" 
	OutputChannelId="TrackedVideoStream" >
	<DefaultClientInfo>
		<MessageTypes>
			<Message Type="IMAGE"/>
			<Message Type="TRANSFORM"/>
		</MessageTypes>
	<TransformNames>
	
	    <Transform Name="StylusTipToStylus" />
		<Transform Name="StylusToTracker" />
		
		<Transform Name="CalibrationPhantomToReference" />
		<Transform Name="ReferenceToTracker" />	
		
		<Transform Name="WaterTankToTracker" />
		
		<Transform Name="ProbeModelToTrOrigin" />
		<Transform Name="TrOriginToTrOriginPixel" />			
		<Transform Name="TrOriginPixelToImage" />
		<Transform Name="ImageToProbe" />
		<Transform Name="ProbeToTracker"/>				
		
	</TransformNames>
	
		<ImageNames>
			<Image Name="Image" 
			EmbeddedTransformToFrame="Reference"/>
		</ImageNames>
	</DefaultClientInfo>
</PlusOpenIGTLinkServer>
<CoordinateDefinitions>
	<Transform From="ProbeModel" To="TrOrigin"
      Matrix="
        1	0	0	-13
        0	1	0	1
        0	0	1	0
        0	0	0	1"
       Date="2011.12.06 17:57:00" />
	   <Transform From="TrOrigin" To="TrOriginPixel"
      Matrix="
        11.7	0	        0	        0 
        0	    12.6915  	0	        0
        0	    0	        12.1756 	0
        0	    0	        0	        1"
       Date="072818_141638" />
    <Transform From="TrOriginPixel" To="Image"
      Matrix="
        1	0	0	410
        0	1	0	-5
        0	0	1	0
        0	0	0	1"
       Date="2011.12.06 17:57:00" />
   <Transform From="Image" To="Probe"
      Matrix="
        -0.0747706	-0.00855718	-0.0388065	16.2385
        -0.0413121	0.00997615	0.0711326	2.1052
        -0.002763	0.0776899	-0.0134085	37.3529
        0	0	0	1"
       Error="0.815458" Date="072818_141638" />    
	 <Transform From="CalibrationPhantom" To="Reference"
      Matrix="
        -0.00405981	0.246539	0.969124	-21.8315
        0.973432	0.222849	-0.0526134	21.1896
        -0.22894	0.943163	-0.240893	-8.92953
        0	0	0	1"
       Error="0.529971" Date="072518_164413" /> 
    <Transform From="StylusTip" To="Stylus"
      Matrix="
        0.99799	0	0.0633689	7.09359
        -0.0018724	0.999563	0.0294882	3.30094
        -0.0633412	-0.0295476	0.997554	111.667
        0	0	0	1"
       Error="0.21318" Date="072518_164137" />  
    	 

	 
</CoordinateDefinitions>


  

<VolumeReconstruction
    OutputSpacing="0.5 0.5 0.5"
    ClipRectangleOrigin="0 0"
    ClipRectangleSize="820 616"
    Interpolation="LINEAR"
    Optimization="FULL"
    CompoundingMode="MEAN"
    FillHoles="OFF" />



</PlusConfiguration>



Thanks

**Comment by salimohamadi** [comment]
<PlusConfiguration version="2.5" PlusRevision="Plus-2.6.0.d3024ea5 - Win32">
  <DataCollection StartupDelaySec="1">
    <DeviceSet Name="fCal: TELEMED (L12 probe) + NDI Aurora Tracker (Probe, Reference, Stylus) - fCal phantom 2.1_20180728_141649CalibratedError0.815458 "
	Description="TELEMED (L12 probe) and NDI Aurora Tracker Both Data Acquisition" />
    	
	<Device
      Id="TrackerDevice"
      Type="AuroraTracker"
      SerialPort="1"
      ToolReferenceFrame="Tracker"
      BaudRate="0"
      MeasurementVolumeNumber="0"
      LocalTimeOffsetSec="-0.000317143">
      <DataSources>
        <DataSource Type="Tool" Id="Stylus" PortName="0" BufferSize="150">
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
        </DataSource>
        <DataSource Type="Tool" Id="Reference" PortName="1" BufferSize="150">
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
        </DataSource>
        <DataSource Type="Tool" Id="Probe" PortName="2" BufferSize="150">
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
          <CustomProperties>
            <Manufacturer>
              NDI-MF2
            </Manufacturer>
            <NdiIdentity>
              02000000
            </NdiIdentity>
            <PartNumber>
              610016 T6A0-L00051
            </PartNumber>
            <Revision>
              000
            </Revision>
            <SerialNumber>
              3A913800
            </SerialNumber>
          </CustomProperties>
        </DataSource>
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream">
          <DataSource Id="Stylus" />
          <DataSource Id="Reference" />
          <DataSource Id="Probe" />
        </OutputChannel>
      </OutputChannels>
    </Device>
    <Device
      Id="VideoDevice"
      Type="TelemedVideo"
      DepthMm="40"
      FrequencyMhz="10"
      DynRangeDb="62"
      GainPercent="90"
      PowerPercent="88">
      <DataSources>
        <DataSource Type="Video" Id="Video" PortUsImageOrientation="UF" BufferSize="150" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStream" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>
    <Device Id="TrackedVideoDevice" Type="VirtualMixer">
      <InputChannels>
        <InputChannel Id="TrackerStream" />
        <InputChannel Id="VideoStream" />
      </InputChannels>
      <OutputChannels>
        <OutputChannel Id="TrackedVideoStream" />
      </OutputChannels>
    </Device>
  </DataCollection>
  <CoordinateDefinitions>
    <Transform From="Image" To="Probe"
      Matrix="
        -0.0747706	-0.00855718	-0.0388065	16.2385
        -0.0413121	0.00997615	0.0711326	2.1052
        -0.002763	0.0776899	-0.0134085	37.3529
        0	0	0	1"
       Error="0.815458" Date="072818_141638" />
    <Transform From="Image" To="TransducerOriginPixel"
      Matrix="
        1	0	0	-410
        0	1	0	5
        0	0	1	0
        0	0	0	1"
       Date="2011.12.06 17:57:00" />
    <Transform From="Phantom" To="Reference"
      Matrix="
        -0.00405981	0.246539	 0.969124	-21.8315
         0.973432	0.222849	-0.0526134	 21.1896
        -0.22894	0.943163	-0.240893	-8.92953
         0	        0	         0	         1"
       Error="0.529971" Date="072518_164413" />
    <Transform From="StylusTip" To="Stylus"
      Matrix="
         0.99799	 0	        0.0633689	7.09359
        -0.0018724	 0.999563	0.0294882	3.30094
        -0.0633412	-0.0295476	0.997554	111.667
         0	         0	        0	        1"
       Error="0.21318" Date="072518_164137" />
    <Transform From="TransducerOriginPixel" To="TransducerOrigin"
      Matrix="
        0.08547	0	        0	        0 
        0	    0.0787928	0	        0
        0	    0	        0.0821315	0
        0	    0	        0	        1"
       Date="072818_141638" />
  </CoordinateDefinitions>
  
  <Rendering WorldCoordinateFrame="Reference" DisplayedImageOrientation="MFA">
    <DisplayableObject Type="Model" ObjectCoordinateFrame="TransducerOrigin" Id="ProbeModel"   File="UsProbe_Telemed_L12.stl"
      ModelToObjectTransform="
	    1	0	0	-13
        0	1	0	1
        0	0	1	0
        0	0	0	1" />
    <DisplayableObject Type="Model" ObjectCoordinateFrame="Reference"        Id="Volume" />
    <DisplayableObject Type="Model" ObjectCoordinateFrame="StylusTip"        Id="StylusModel"   File="Stylus_Example.stl" />
    <DisplayableObject Type="Model" ObjectCoordinateFrame="Phantom"          Id="PhantomModel"  File="fCal_2.1.stl"             Opacity="0.6"
      ModelToObjectTransform="
        1	0	0	0
        0	1	0	0
        0	0	1	0
        0	0	0	1" />
    <DisplayableObject Type="Image" ObjectCoordinateFrame="Image" Id="LiveImage" />
  </Rendering>
  
  <Segmentation
    ApproximateSpacingMmPerPixel="0.078"
    MorphologicalOpeningCircleRadiusMm="0.27"
    MorphologicalOpeningBarSizeMm="2.0"
    ClipRectangleOrigin="27 27"
    ClipRectangleSize="766 562"
    MaxLinePairDistanceErrorPercent="10"
    AngleToleranceDegrees="10"
    MaxAngleDifferenceDegrees="10"
    MinThetaDegrees="-70"
    MaxThetaDegrees="70"
    MaxLineShiftMm="10.0"
    ThresholdImagePercent="10"
    CollinearPointsMaxDistanceFromLineMm="0.6"
    UseOriginalImageIntensityForDotIntensityScore="FALSE"
    NumberOfMaximumFiducialPointCandidates="20" />
  <PhantomDefinition>
    <Description Name="fCAL" Type="Multi-N" Version="2.1" WiringVersion="2.5" Institution="Queen&apos;s University PerkLab" />
    <Geometry>
      <Pattern Type="NWire">
        <Wire Name="7:G1_g1" EndPointFront="30.0 0.0 0.0" EndPointBack="30.0 0.0 40.0" />
        <Wire Name="8:L1_h1" EndPointFront="55.0 0.0 0.0" EndPointBack="35.0 0.0 40.0" />
        <Wire Name="9:M1_m1" EndPointFront="60.0 0.0 0.0" EndPointBack="60.0 0.0 40.0" />
      </Pattern>
      <Pattern Type="NWire">
        <Wire Name="4:G3_g3" EndPointFront="30.0 10.0 0.0" EndPointBack="30.0 10.0 40.0" />
        <Wire Name="5:H3_l3" EndPointFront="35.0 10.0 0.0" EndPointBack="55.0 10.0 40.0" />
        <Wire Name="6:M3_m3" EndPointFront="60.0 10.0 0.0" EndPointBack="60.0 10.0 40.0" />
      </Pattern>
      <Pattern Type="NWire">
        <Wire Name="1:H5_h5" EndPointFront="35.0 20.0 0.0" EndPointBack="35.0 20.0 40.0" />
        <Wire Name="2:L5_i5" EndPointFront="55.0 20.0 0.0" EndPointBack="40.0 20.0 40.0" />
        <Wire Name="3:M5_m5" EndPointFront="60.0 20.0 0.0" EndPointBack="60.0 20.0 40.0" />
      </Pattern>
      <Landmarks>
        <Landmark Name="#1" Position="-32.53 -5.25 45.0" />
        <Landmark Name="#2" Position="-32.53 -5.25  5.0" />
        <Landmark Name="#3" Position="-32.53 19.75 -5.0" />
        <Landmark Name="#4" Position="-32.53 19.75 45.0" />
        <Landmark Name="#5" Position="105.47 -5.25 -5.0" />
        <Landmark Name="#6" Position="105.47 -5.25 45.0" />
        <Landmark Name="#7" Position="105.47 14.75 -5.0" />
        <Landmark Name="#8" Position="105.47 19.75 45.0" />
        <Landmark Name="#9" Position=" -3.53 -9.25 45.0" />
        <Landmark Name="#10" Position=" 41.47 -9.25 45.0" />
        <Landmark Name="#11" Position=" 86.47 -9.25 45.0" />
        <Landmark Name="#12" Position=" 96.47 -9.25 30.0" />
        <Landmark Name="#13" Position=" 86.47 -9.25 -5.0" />
        <Landmark Name="#14" Position=" 21.47 -9.25 -5.0" />
        <Landmark Name="#15" Position=" -3.53 -9.25 -5.0" />
        <Landmark Name="#16" Position="-13.53 -9.25 10.0" />
      </Landmarks>
    </Geometry>
  </PhantomDefinition>
  <VolumeReconstruction
    OutputSpacing="0.5 0.5 0.5"
    ClipRectangleOrigin="0 0"
    ClipRectangleSize="820 616"
    Interpolation="LINEAR"
    Optimization="FULL"
    CompoundingMode="MEAN"
    FillHoles="OFF" />
  <fCal
    PhantomModelId="PhantomModel"
    ReconstructedVolumeId="Volume"
    TransducerModelId="ProbeModel"
    StylusModelId="StylusModel"
    ImageDisplayableObjectId="LiveImage"
    NumberOfCalibrationImagesToAcquire="200"
    NumberOfValidationImagesToAcquire="100"
    NumberOfStylusCalibrationPointsToAcquire="200"
    RecordingIntervalMs="100"
    MaxTimeSpentWithProcessingMs="70"
    ImageCoordinateFrame="Image"
    ProbeCoordinateFrame="Probe"
    ReferenceCoordinateFrame="Reference"
    TransducerOriginCoordinateFrame="TransducerOrigin"
    TransducerOriginPixelCoordinateFrame="TransducerOriginPixel"
    TemporalCalibrationDurationSec="10"
    FixedChannelId="VideoStream"
    FixedSourceId="Video"
    MovingChannelId="TrackerStream"
    MovingSourceId="ProbeToTracker"
    DefaultSelectedChannelId="TrackedVideoStream"
    FreeHandStartupDelaySec="5" />
	
  <vtkPlusPivotCalibrationAlgo 
  ObjectMarkerCoordinateFrame="Stylus" 
  ReferenceCoordinateFrame="Reference" 
  ObjectPivotPointCoordinateFrame="StylusTip" />
  
  <vtkPlusPhantomLandmarkRegistrationAlgo 
  PhantomCoordinateFrame="Phantom" 
  ReferenceCoordinateFrame="Reference" 
  StylusTipCoordinateFrame="StylusTip" 
  DetectionTimeSec="1.0" 
  StylusTipMaximumDisplacementThresholdMm="1.8" />
  
  <vtkPlusProbeCalibrationAlgo 
  ImageCoordinateFrame="Image" 
  ProbeCoordinateFrame="Probe" 
  PhantomCoordinateFrame="Phantom" 
  ReferenceCoordinateFrame="Reference" />
  
</PlusConfiguration>

**Comment by salimohamadi** [comment]
unfortunately, I can't copy my config file here

**Comment by salimohamadi** [comment]
[Desktop.zip](https://github.com/PlusToolkit/PlusLib/files/2289458/Desktop.zip)

**Comment by salimohamadi** [comment]
the calibration step was repeated but the rotation between the probe and its picture is steel remained. I think the problem backs to the transforms and their hierarchy defined in the 3D slicer ( a picture attached previously). would you please help me how should it be for both the probe and the US image.

I have two config file:
1-for calibration
2- for data acquisition and scene visualization

They are in the zip file attached above

**Comment by salimohamadi** [comment]
what is the difference between the "Reference" in lines 160 and 113 in PlusServer config file and the "Reference sensor " that is attached to the calibration phantom fcal2.1? Are they all referring to one thing?

**Comment by salimohamadi** [comment]
by this " transform hierarchy" this scene obtained. the US image can be seen like a line. I'm really confused.

![photo_2018-08-15_17-01-58](https://user-images.githubusercontent.com/40351746/44148568-21db245a-a0ae-11e8-8a04-d3e3ff954a3c.jpg)
![photo_2018-08-15_17-02-05](https://user-images.githubusercontent.com/40351746/44148569-2200a8a6-a0ae-11e8-8722-3b2ffbbbb93e.jpg)

**Comment by Sunderlandkyl** [comment]
You'll need to download the SlicerIGT extension and use the volume reslice driver to change the Ultrasound image slicing.
- Download SlicerIGT
- Switch to Volume Reslice Driver module
For the desired view:
- Select "Driver": Image_Reference (name might be slightly different)
- Select "Mode": Transverse

Does the ultrasound image show up in the correct location?

Image_Reference is already in the Reference coordinate system. Most of your other transforms move things into the Tracker coordinate system. In that case, you can change the EmbeddedTransformToFrame to "Tracker" if that's what you want (making the image: Image_Tracker).

**Comment by salimohamadi** [comment]
thanks for answering. according to your advice, I changed the EmbeddedTransformToFrame to "Tracker" and using the Volume Reslice Driver, US image can be seen now. but the position of the probe relative to US image is not correct. please see the attached video and help me with that.
Thanks

**Comment by salimohamadi** [comment]
[ScreenCapture_8-18-2018 3.43.53 PM_0002_0003_00041.zip](https://github.com/PlusToolkit/PlusLib/files/2299511/ScreenCapture_8-18-2018.3.43.53.PM_0002_0003_00041.zip)
[Uploading ScreenCapture_8-18-2018 3.43.53 PM_0002_0003_00042_00045_00046.zip…]()

**Comment by Sunderlandkyl** [comment]
I can't see how you have your probe model set up in the video.
You need to add some transform to the config file that can display the model in the correct location.

Try specifying ProbeToImage and adding the model to the hierarchy like so:
- ProbeToTracker
  - ImageToProbe
    - ProbeModelToImage

**Comment by adamrankin** [comment]
Re-open if further discussion.
