### ISSUE TITLE
The application was unable to start correctly

### ISSUE THREAD

**Issue by zoujinger** [PlusToolkit/PlusLib#400]
Hi,

I try to connect NDI aurora to Slicer through PLUS. There are some troubles
When I use PlusApp-2.7.0.20180802-Win64.exe and PlusApp-2.6.0.20180310-Win64.exe, the trouble is 'The application was unable to start correctly(0x015002). Click OK to close the application'
Here is the troubleshooting and my computer system:
![image](https://user-images.githubusercontent.com/27009979/44246121-0cef0400-a20f-11e8-8e16-f9aeb7909a65.png)

And when I use PlusApp-2.3.0.4819-Win64.exe, I can't find NDI auraro in Device set

When I use PlusApp-2.2.0.4177-Win64.exe, here is the trouble:
![connection_failed](https://user-images.githubusercontent.com/27009979/44246338-54c25b00-a210-11e8-992a-84c344819703.PNG)

But I can use the NDI track on the computer successfully. It was connected to COM3
![success_track](https://user-images.githubusercontent.com/27009979/44246427-bd113c80-a210-11e8-8f9a-e258c596a255.PNG)

Looking forward t your help.
Thanks.

Best Regard,
Jing

**Comment by Sunderlandkyl** [comment]
Try installing the Visual Studio redistributables listed here: https://plustoolkit.github.io/download, restarting your computer, and then trying Plus 2.7/2.6 again.

**Comment by zoujinger** [comment]
Thanks.
The distribute has been installed before.
The version of visual studio is 2017.
![vsdistribute](https://user-images.githubusercontent.com/27009979/44316872-b842c780-a460-11e8-9d2b-b06df8813464.PNG)

**Comment by Sunderlandkyl** [comment]
If you've tried all of the redistributables on the download page, you might try the following:
- Download and install VS2010 redistributable: https://www.microsoft.com/en-ca/download/details.aspx?id=8328
- Download and run Dependency Walker (http://dependencywalker.com/) on Plus, and uploading the results
