### ISSUE TITLE
VirtualCapture compresses metaimage with warning saying it can't

### ISSUE THREAD

**Issue by jamesobutler** [PlusToolkit/PlusLib#402]
When recording with compression enabled and an output file with MHA or MHD extension type I get a warning message about it not being supported.  When I look at the header information of each file types afterwards, it does indicated `CompressedData = True` and by looking at the file size it appears to be compressed.

https://github.com/PlusToolkit/PlusLib/blob/ecfe79335fd2e73d1e78235ec069870fa8dc21d3/src/PlusDataCollection/VirtualDevices/vtkPlusVirtualCapture.cxx#L183-L190

**Comment by jamesobutler** [comment]
Even though using PlusServerRemoteControl I could get it to save compressed MHD data, the data appeared to be messed up and wouldn't uncompress using EditSequenceFile with [error](https://github.com/PlusToolkit/PlusLib/blob/55ba073b85c39f5302c0ea7789c30c333d6057de/src/PlusCommon/IO/vtkPlusMetaImageSequenceIO.cxx#L398-L402) "Cannot uncompress the pixel data: uncompressed data is less than expected."

From @dzenanz 

> MetaImage can only compress using GZip algorithm. I don't know whether it requires the entire input to be provided before it runs, or (more likely) incremental compression is possible but requires more complex interaction with the compression library. Either way, we can't use it in VirtualCapture now.

**Comment by jamesobutler** [comment]
@adamrankin @lassoan Do you have any news about GZip support for MHA/MHD?  Otherwise, I might move to using NHDR/NRRD as my file extension which VirtualCapture supports for GZip compression.

GZip usage appears to work well and was about a 2% CPU increase when capturing at ~15-20 FPS. I would guess this might go up to 20% CPU different when capturing 10X FPS.

**Comment by dzenanz** [comment]
I took a bit deeper look into MetaImage since I made that statement. It uses `zlib`, which is using a similar algorithm as GZip, perhaps even the same one.

**Comment by lassoan** [comment]
> Do you have any news about GZip support for MHA/MHD?

For real-time acquisition we typically record uncompressed to file, as it has less overhead and we usually only need to record up to a couple of minutes at once. So, for us it is not a priority to implement compressed real-time streaming to file with zlib (deflate) compression.

@Sunderlandkyl is working on real-time streaming using video compression (WebM/VP9), as it provides much higher compression ratio. We need this so that we can record optical camera videos up to 1-2 hours long.

**Comment by adamrankin** [comment]
I record using compressed nrrd. metaimage cannot record compressed incrementally due to a zip issue. I looked into this ages ago and don't remember the exact details.

>  So, for us it is not a priority to implement compressed real-time streaming to file with zlib (deflate) compression.

This is already implemented in the form of compressed nrrd recording.

**Comment by jamesobutler** [comment]
The loophole of allowing compression to be specified for metaimage recording using StartRecordingCommand was exposed again in caca9d8222122f9695f30ad3ee924388f2da3c77. The original fix was in 93d9d4175970a3986f2429acad9040df6367409a.

@Sunderlandkyl Was it intentional to move the `SetEnableFileCompression` call back to being placed after `OpenFile` within vtkPlusStartStopRecordingCommand [here](https://github.com/PlusToolkit/PlusLib/commit/caca9d8222122f9695f30ad3ee924388f2da3c77#diff-2d211fdef2a8c1424851920006bd1fd6R314)?

**Comment by Sunderlandkyl** [comment]
It was intentional. When I was testing the MKV writing using PlusRemote, I found that I was unable to enable/disable compression remotely, since it was being overwritten within OpenFile, rather than using what was sent in the command.

I didn't realize that its location was part of a previous fix. I'll work tomorrow on a fix that solves both problems.

**Comment by jamesobutler** [comment]
Ok thanks! The fix was so that the compression specification in the Start command would get applied to the VirtualCapture device, then when it would go to open the file, and if the currently specified output filename was also a metaimage file it would revert the compression back to false.

**Comment by Sunderlandkyl** [comment]
Both issues should be fixed in 4b18140
