### ISSUE TITLE
Extend US parameters to other devices

### ISSUE THREAD

**Issue by adamrankin** [PlusToolkit/PlusLib#404]
With OpenCV, V4L2, VFW, and MMF devices supporting webcams, it would be nice if we could change camera parameters live like we can for US devices.

Duplicating the subclass to `vtkPlusCameraDevice` is fine by me, but I was wondering if we wanted to generalize `vtkPlusUsDevice`?

**Comment by lassoan** [comment]
I agree that this would make sense to have a base class for cameras (especially if we add calibration, distortion correction, etc.). I would not mix this with ultrasound imaging but have a separate base class.

**Comment by adamrankin** [comment]
Sounds good.

**Comment by jamesobutler** [comment]
It would also be nice to have a group for Tracker devices to change parameters like origin position live.  We update the origin position of our absolute encoders for our motion stage after a calibration sequence using our custom wrapper around Plus.

**Comment by adamrankin** [comment]
Maybe `vtkPlusDevice` needs a `PlusStatus SetParameter(const std::string& name, const std::string& value)` or `PlusStatus SetParameter(PLUS_DEVICE_PARAMETER parameter, const std::string& value)` function that can be overridden by child classes.

**Comment by adamrankin** [comment]
@lassoan My preferred solution to this would be to have SetParameter in `vtkPlusDevice` and have the sub classes override it.

That way, we keep the unified architecture of vtkPlusDevice and each device can handle it however they choose.

Thoughts?

(I'm just thinking back as to why we merged image device and tracker device in the first place).

**Comment by adamrankin** [comment]
I am coding up the base class implementation now, will upload a PR in ~30m-1h

**Comment by markasselin** [comment]
Ahh, wonderful! Take your time

**Comment by adamrankin** [comment]
Infrastructure is available, people can add subclasses with specific behaviour as desired.
