### ISSUE TITLE
Vega unable to connect

### ISSUE THREAD

**Issue by BKalen** [PlusToolkit/PlusLib#406]
Hello.

I received a NDI Vega camera the other week and have been working to get it set up and connected to Plus to implement with SlicerIGT. I keep getting the error messages attached and after changing IPs and ports a few different, I have hit a wall and am looking for guidance. I built Plus from source and have slicer downloaded with the applicable modules. I believe the error lies in the XML, but I am not too familiar with it to be sure. Attached is also the current Version of XML I have been using.

[PlusDeviceSet_Server_NDIVega.txt](https://github.com/PlusToolkit/PlusLib/files/2324594/PlusDeviceSet_Server_NDIVega.txt)
[082718_083842_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/2324597/082718_083842_PlusLog.txt)

**Comment by lassoan** [comment]
Could you please check if [answers that have previously given to similar questions ](https://github.com/PlusToolkit/PlusLib/issues?utf8=%E2%9C%93&q=is:issue+is:closed+vega+) help?

@adamrankin It seems that either defaults are not set up right, documentation is lacking, or it's just too complicated to set up this tracker. What could we do to make things simpler?

**Comment by BKalen** [comment]
I have gone through these threads and tried to follow the steps outlined and nothing has seemed to work. This is why I believe it is something with the XML. NDI Vega Connection Failed #363 was the thread I found most helpful

**Comment by BKalen** [comment]
The main difference in set up is I am going through an ethernet switch with the host computer and camera and not using a USB dongle

**Comment by adamrankin** [comment]
The vega is a network enabled device. You can either access it by 1) its Bonjour name if you have Bonjour services enabled **or** you must configure a static IP **or** you must configure DHCP.

**Comment by BKalen** [comment]
Hey guys. After working with IT and other colleagues, I was able to resolve the tool ports error I was getting, but I still cannot fully connect to the server. It does however recognize the OpenIGTLink from slicer when I make that connection active. I followed the PlusBuild Instructions and configured with all options I found necessary.  Is there something I missed in my build? Or is there any missing libraries for OpenCV I might need?

[100318_150255_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/2444154/100318_150255_PlusLog.txt)
[PlusDeviceSet_Server_NDIVega.txt](https://github.com/PlusToolkit/PlusLib/files/2444179/PlusDeviceSet_Server_NDIVega.txt)

**Comment by adamrankin** [comment]
If you've enabled it from PlusBuild, all of the dependent libraries should be good. This looks like a connection error. Googling the error message...

**Comment by adamrankin** [comment]
Nevermind, generic can't connect message. Are you able to view the video stream from another program? For example, VLC can play rtsp streams.

**Comment by BKalen** [comment]
I will have to read up on how do that and attempt tomorrow. I will keep you updated

**Comment by BKalen** [comment]
Doesn't seem like VLC can connect to Video URL for a Network stream. I used the camera IP (static IP) with both the default port for VLC and 8765 for the camera. It is also not recognizing any capture devices other than Default

**Comment by adamrankin** [comment]
Simple questions first:

Have you used the Configure app to enable the video feed on the tracker? It is off by default.

**Comment by BKalen** [comment]
I don't see an area to enable a video feed. Under features I see Video Camera Not Installed, but no option to enable or install

**Comment by BKalen** [comment]
The most recent revisions of the User Guide and API guide state Video Camera is not supported so the documentation was removed

**Comment by adamrankin** [comment]
Another simple question: does your unit have a camera physically installed?

**Comment by BKalen** [comment]
I guess not. I'll have to talk with NDI to see what can be done.

Thanks for your time and help Adam!

**Comment by adamrankin** [comment]
No problem, sorry it's such an adventure.
