### ISSUE TITLE
Volume reconstruction using the Epiphan frame grabber

### ISSUE THREAD

**Issue by lgroves6** [PlusToolkit/PlusLib#407]
I was reading the volume reconstruction page for the PlusServer, and it mentions that it is to reconstruct a 2D ultrasound image to a 3D ultrasound image. I was wondering if it is specific to ultrasound systems. I am using the Epiphan frame grabber on a TEE ultrasound machine and the volume reconstruction isn't working. I am assuming this is due to the requirement of an ultrasound connection, but I was wondering if it is possible to do for the Epiphan device, or if there is any work around. I have attached my config file below in case there is any issues within the file, I have converted it to a txt file so that I am able to upload it here. Any help is appreciated. Thanks! 
[EpiphanPhilipsTEEVolumeReconstructionandTrackingtxt.txt](https://github.com/PlusToolkit/PlusLib/files/2337055/EpiphanPhilipsTEEVolumeReconstructionandTrackingtxt.txt)

**Comment by Sunderlandkyl** [comment]
It should be possible.

What versions of Plus and Slicer are you using?
Can you attach a log file?

**Comment by lgroves6** [comment]
I am using Slicer 4.8.1 and Plus Applications 2.6.0.2017-11-29 (Win32). The plus log doesn't give me any errors, which is why I thought it might just be ignoring it since I am not using an ultrasound device. I have attached the log below. 
[083118_122738_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/2340839/083118_122738_PlusLog.txt)

**Comment by Sunderlandkyl** [comment]
Were you able to connect to the server in Slicer? The log doesn't show any connections.

**Comment by lgroves6** [comment]
Yes I was able to, it connects and streams in the whole screen from the frame grabber.

**Comment by Sunderlandkyl** [comment]
Is it possible that you uploaded the wrong log file?

The log should have a line similar to this to show that Plus was connected to Slicer:
```
090418_163113.532|INFO|091.045000| Received new client connection (client 1 at 127.0.0.1:18944). Number of connected clients: 1| in E:\D\PSNP64b\PlusLib\src\PlusServer\vtkPlusOpenIGTLinkServer.cxx(256)
```

And one similar to this if the StartRecording command was received:
```
090418_163401.135|INFO|025.257000| vtkPlusStartStopRecordingCommand::Execute:| in E:\D\PSNP64b\PlusLib\src\PlusServer\Commands\vtkPlusStartStopRecordingCommand.cxx(263)
```

**Comment by adamrankin** [comment]
Reopen if still persisting.
