### ISSUE TITLE
how to calibrate a web camera in plus

### ISSUE THREAD

**Issue by kamrulhasan-rit** [PlusToolkit/PlusLib#408]
I try to navigate research through the camer with Plus showed in https://www.youtube.com/watch?v=MOqh6wgOOYs. However, I don't know when I write the code "aruco_calibration.exe live:0 camera_calibration.yml -size 0.03556" in the plus command prompt, it pops up a camera window but nothing to see the camera rather than a black window with some noise moving.

**Comment by lassoan** [comment]
Do you have a front and back webcam on your computer? Try live:1, live:2, etc. to access the correct one.

**Comment by kamrulhasan-rit** [comment]
I have only one camera and so I used live:1

**Comment by kamrulhasan-rit** [comment]
It shows like this
![calibrate](https://user-images.githubusercontent.com/36611351/44932850-f7acc600-ad34-11e8-9ead-e9d7c80bdbb9.PNG)

**Comment by lassoan** [comment]
What operating system do you have?

**Comment by kamrulhasan-rit** [comment]
windows 7 64 bit

**Comment by lassoan** [comment]
Is there a chance you can connect this camera to a newer computer, running Windows 10?

Even Microsoft stopped mainstream support for Windows 7 more than 3 years ago and will completely shut it down in about 1.5 years. If everything works well on a more recent computer, then instead of troubleshooting this problem, it may be easier to update your computer.

**Comment by kamrulhasan-rit** [comment]
I had connected to windows 10 also with slicer version 4.9 nightly built and also with plusserver. But same things happen.

**Comment by lassoan** [comment]
What camera is this? Can you try a different one?

**Comment by kamrulhasan-rit** [comment]
Its a logitech 1080p webcam and its working now. what should be the next step to get this:  https://www.youtube.com/watch?v=MOqh6wgOOYs ?

**Comment by cookedJohn** [comment]
I am having the same issue. I have gotten to the point where I can open aruco_calibration.exe and camera index 0 on the command prompt, but pressing a, c, or s does not seem to capture any images for calibration. How do I continue to make the simple webcam based tracking markers shown here https://www.youtube.com/watch?v=MOqh6wgOOYs&ab_channel=PerkLabResearch ?

**Comment by cookedJohn** [comment]
I am having the same issue. I can open camera index 0 on aruco_calibration.exe on command prompt. How do I calibrate the markers? Pressing the keys a, c, and s does not seem to do anything.
