### ISSUE TITLE
fCal not loading config files

### ISSUE THREAD

**Issue by HonDon7** [PlusToolkit/PlusLib#416]
I am new to Plus. I downloaded and built the master. When trying to use fCal Ion some of the PlusData examples I could not get any config file to load. 

I finally added this code at line 156 of the QConfigurationToolbox.cxx
	  vtkPlusConfig::GetInstance()->SetDeviceSetConfigurationData(configRootElement); 

I cannot attach the output file as I am writing this ticket well after I have moved on after getting it to work. The output file has long since been deleted.

**Comment by adamrankin** [comment]
See https://github.com/PlusToolkit/PlusApp/commit/2a4970f7a51196b477c3c8e70cae85d007f4d540
