### ISSUE TITLE
Volume reconstruction problem

### ISSUE THREAD

**Issue by salimohamadi** [PlusToolkit/PlusLib#418]
Hi. 
I had a problem that I would like to share with others to prevent it from happening again. After performing the probe calibration, every time I turned on the PLUS, the probe position was mistaken at the site and the reason was lack of a fix connection between the sensor and the probe. To prevent this, the sensor must be completely probe mounted so that it does not even have the slightest movement.

But the problem I'm facing with now is in the ultrasound 3D volume reconstruction.  It seems that the 3D reconstruction algorithm eliminates the overlapping areas of the probe swept even when the " compounding mode" is "on". so the output 3D surface is not continuous.
some figures in addition to my config file are attached to show the problem.

and another question. 
Is the "fcal" probe calibration algorithm valid for the TELEMED' curve probe?  since in the lumbar injections, a deeper depth is required and in your website, there is only the linear probe's STL file.

looking forward to hearing from you.
Thanks,
Samaneh

![1](https://user-images.githubusercontent.com/40351746/46010034-2d439580-c0ce-11e8-9999-e67de63dc748.png)
![2](https://user-images.githubusercontent.com/40351746/46010036-2d439580-c0ce-11e8-9daa-23ef8b4a6b81.png)
![3](https://user-images.githubusercontent.com/40351746/46010037-2ddc2c00-c0ce-11e8-9ff1-d18000c8bd66.png)

[TELEMED (L12 probe) and NDI Aurora Tracker (Probe, Reference, Stylus) Volume Reconstruction 3 - fCal phantom 2.1_ version 3 - 20180905_150820CalibratedError0.zip](https://github.com/PlusToolkit/PlusLib/files/2414868/TELEMED.L12.probe.and.NDI.Aurora.Tracker.Probe.Reference.Stylus.Volume.Reconstruction.3.-.fCal.phantom.2.1_.version.3.-.20180905_150820CalibratedError0.zip)

**Comment by Sunderlandkyl** [comment]
The calibration algorithm is valid if you are using the same probe, with the same depth setting, and the probe sensor is mounted in the same location.

Are you having trouble with both scout scan + live volume reconstruction?
Can you attach a Plus log file?

**Comment by lassoan** [comment]
> 3D reconstruction algorithm eliminates the overlapping areas of the probe swept even when the " compounding mode" is "on".

There is no such compounding mode as "on". See valid values and their description at perk-software.cs.queensu.ca/plus/doc/nightly/user/AlgorithmVolumeReconstruction.html#ElementVolumeReconstruction

**Comment by salimohamadi** [comment]
Dear Sunderland,
my config file was attached above in my last message as a zip file.
in terms of the probe, I would like to know may I calibrate and use the TELEMED's curve probe? because I think the fcal has been set just for the TELEMED's linear probe.
thanks for answering

**Comment by salimohamadi** [comment]
Dear lassoan,
thanks for answering. I will check my config file to find the mistake.

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
