### ISSUE TITLE
Connection Fail: Plus Server and 3D Slicer Issue

### ISSUE THREAD

**Issue by jennyrhodes** [PlusToolkit/PlusLib#423]
Having issues using Plus Server Launcher. 

Installed Plus Server and IGT/OpenLink for nightly Slicer. Used correct config directory and went to "device set" and used "PlusServer: Media Foundation video capture device -color." Received **"Connection failed. Please select another device set and try again"**

I want to use my **built-in webcam** on surface book2 windows 64bit computer. Please advise.

**Comment by adamrankin** [comment]
The red circle in the bottom right of Plus Server Launcher will have turned red. Can you click on it and copy/paste any error messages here?

**Comment by jennyrhodes** [comment]
|ERROR|119.897000| Server process error: Crashed| in E:\D\PTNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(716)
|ERROR|119.916000| Server stopped unexpectedly. Return code: -1073741811| in E:\D\PTNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(729)
|INFO|119.916000| Disconnect request successful| in E:\D\PTNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(554)

Thank you for fast response.

**Comment by adamrankin** [comment]
I'll make a 64 bit build and test the webcam setup.

**Comment by jennyrhodes** [comment]
Please let me know if it works. I might be missing a step.

**Comment by jennyrhodes** [comment]
Reinstalled just in case. Have a new slightly different error:

|WARNING|259.691000|SERVER> > Unable to init capture device with requested details: device ID: 0 (Empty) stream 0, 640x480, 30Hz, YUY2| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\MicrosoftMediaFoundation\vtkPlusMmfVideoSource.cxx(314)
|ERROR|259.711000|SERVER> VideoDevice: Cannot connect to data source, ConnectInternal failed| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDevice.cxx(1204)
|ERROR|259.730000|SERVER> Datacollector failed to connect to devices| in :\D\PSNP64b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(129)
|INFO|259.845000| Server process started successfully| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(213)
|ERROR|260.956000| Server process error: Crashed| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(444)
|ERROR|260.957000| Server stopped unexpectedly. Return code: -1073741811| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(457)
|INFO|260.958000| Disconnect request successful| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(307)

**Comment by adamrankin** [comment]
Yes, I just installed the latest nightly and got the same log (except mine doesn't crash). You will have to adjust the config file for your desired parameters.

Example:
My webcam can do 
> |INFO|022.226000|SERVER> Stream index 0 - Frame size: 800x600, video format: RGB24, frame rate: 30

So I'll change my config file with the following two attributes:
>FrameSize="800 600"
>VideoFormat="RGB24"

and I'll add the following attribute:
>AcquisitionRate="30"

**Comment by jennyrhodes** [comment]
how do you find the webcam |INFO|?

**Comment by adamrankin** [comment]
I'm not sure about the crashing, but it may be crashing on exit, which although not great, will still allow you to work.

In the log, there will be many many listings of what the webcam can support.

**Comment by jennyrhodes** [comment]
In the log I get the following: It says "found capture devices:" and then on the next line "supported vide formats for Device Id 0 (Empty)"

It's like it doesn't know I have a camera?

**Comment by adamrankin** [comment]
Hmm, does your webcam work with the windows Camera app?

**Comment by jennyrhodes** [comment]
I was able to get an image on Slicer. I am using the arUco markers. In Slicer, they do not show up in "IN" under IGTL Connector.

Additionally, my image is grainy and I can not distinguish anything. my image is in the corner of the viewing screen.

**Comment by adamrankin** [comment]
The MMF config file is not setup for ArUco marker tracking. You'll have to use a different config file for that. I'm not sure if that's built for the downloadable builds.

@lassoan is aruco in the 64bit build?

**Comment by jennyrhodes** [comment]
I have switched to using "PlusServer Optical marker tracking using MMF video" with port 18945. Marker0toTracker and other items in the "IN" dropdown do not show up.

**Comment by adamrankin** [comment]
Hmm, I am not familiar with the optical marker tracker. Can the marker be seen in the video? Some basic problem solving may yield results.

**Comment by jennyrhodes** [comment]
Yes the marker can be clearly seen within the video.  I have the config file to make the transform but none of the transforms populate in the slicer app. I am following the 2017 "brain surgery navigation with live tractography" tutorial online

**Comment by adamrankin** [comment]
I will refer you to @ungi and @lassoan as they are more familiar with this area than I am.

**Comment by jennyrhodes** [comment]
Thank you

**Comment by lassoan** [comment]
> "PlusServer Optical marker tracking using MMF video" with port 18945. Marker0toTracker and other items in the "IN" dropdown do not show up.

Transforms are sent through port 18944.
