### ISSUE TITLE
ArUco Markers "Pose Estimation Fail"

### ISSUE THREAD

**Issue by jennyrhodes** [PlusToolkit/PlusLib#424]
I am using plus with arUco marker with a built in webcam. I keep getting "pose estimation fail" from the server. Please advise how to fix.

**Comment by lassoan** [comment]
Make sure you to calibrate your camera and print the markers at 100% magnification (do not fit document size to page).

**Comment by jennyrhodes** [comment]
Markers were printed at 100% and camera was calibrated. Any other ideas?

**Comment by jennyrhodes** [comment]
I calibrated again and I no longer get the position failure error. However nothing happens when I hold up the markers.

This is shown in IO Configuraiton in Slicer:
Scene>
IGTLConnector C
>IN
>Image_Image

"Marker1toTracker" etc. do not show up.

**Comment by ungi** [comment]
A couple of things you could check:
Is the camera calibration file in the same folder as the PLUS config file, and does the CameraCalibrationFile in the config file have the correct calibration file name?
Does the MarkerDictionary value in the PLUS config file correspond to the marker patterns you printer?
Do you have the correct Marker numbers listed under DataSources in the PLUS config file?
Are the same marker names listed in the OutputChannel?
Is that same channel id in OutputChannelId of PlusOpenIGTLinkServer?

I've just tested OpticalMarkerTracker last week and I remember it took me a couple of hours to figure out all the things I missed in the setup, but I got it working eventually.

**Comment by ungi** [comment]
I cannot read your config file using the link "config.txt". Can you share a link to the original config file (e.g. dropbox, OneDrive), or just paste the contents in a message here?

**Comment by jennyrhodes** [comment]
Sorry about that.

https://drive.google.com/open?id=1mc2WI9I4hrZwg9OmHVL_iX-QkSRWyYQS

**Comment by jennyrhodes** [comment]
I switched to 3 and 4 (marker size 50mm). Still cannot get anything to show up or even track. Maybe I am doing something wrong in Slicer.

In the Image_Image video feed, I am holding up the two markers, but nothing is happening in the 3D preview.

Also in IGTLink, there are no transforms populated.

**Comment by Sunderlandkyl** [comment]
As @lassoan mentioned in the previous issue, you need to create another OpenIGTLink connector using port 18944.

In your config file, images are sent over 18945 and transforms are on 18944.

**Comment by Sunderlandkyl** [comment]
Try changing the PortUsImageOrientation back to MF.

**Comment by jennyrhodes** [comment]
Changed back to MF. Getting the following error in the server plus log:

"Items are requested from 0, but the oldest available data is acquired at [big number]"
"Failed to get tracked frame list from data collector"

also there are no transforms populated. see below. sorry for all of the problems and thanks for the help. 

My steps are launch server and then go over to slicer IGTLink module and add two different connectors (active port 18944 and active port 18945).

![update](https://user-images.githubusercontent.com/43787082/46417558-8ffce880-c6ef-11e8-8770-085bf57624c2.PNG)

**Comment by Sunderlandkyl** [comment]
You could also try UF and UN.
If you're using a laptop webcam, perhaps the image is being mirrored on the X-axis.

**Comment by jennyrhodes** [comment]
I am able to get the orientation correct. I think the problem is that the transforms are not sending over and there is not proper communication between plus server and slicer. 

In the tutorial the transforms are populated immediately. I am not getting what is shown below in the tutorial. I do not have any linear transforms.

<img width="305" alt="tutorial" src="https://user-images.githubusercontent.com/43787082/46418493-7e1c4500-c6f1-11e8-947c-6a5d8c9c2daa.png">

**Comment by ungi** [comment]
I have recorded my screen when testing with markers 3 and 4. Maybe you can spot something on the video that you are not doing the same way: https://1drv.ms/v/s!AhiABcbe1DBygqI84R_PHvjCkaBLEw
This is the config file I use in the video: https://1drv.ms/u/s!AhiABcbe1DBygqIJgokq6qNyh-mGRg

**Comment by jennyrhodes** [comment]
Thank you for the video. I will try to recreate and update you.

**Comment by jennyrhodes** [comment]
Thank you for the video. I will try to recreate and update you.

**Comment by Sunderlandkyl** [comment]
You do appear to be receiving transforms from Plus.
Do you mean that you can't see them as the blue needles in the 3D view?

That appears to be a problem with the Nightly version of OpenIGTLinkIF.
If you go to the Transforms module, can you see the transformation matrix changing?

**Comment by jennyrhodes** [comment]
I am able to see the transformation matrix changing. I was mainly confused because I was not seeing the blue needles. 

It is working now. Thank you all for your help you have gone above and beyond.
