### ISSUE TITLE
Pivot Calibration Question

### ISSUE THREAD

**Issue by jennyrhodes** [PlusToolkit/PlusLib#425]
I am using arUco markers. I am following this tutorial for pivot calibration:
https://drive.google.com/open?id=1pWZgLehasRvOzC_icbqFca-u40mHhd0-

Question: If I just wanted to put two arUco markers on the skull and move skull only, is there a simpler way of putting the virtual markers on the STL file and linking them together?

I am not sure if I actually need to use pivot calibration for this.

**Comment by Sunderlandkyl** [comment]
To do the tutorial, you will need two markers, one on the skull (Reference) and one on the stylus (Stylus).
The pivot calibration is necessary for calculating the location of the tip of the stylus relative to the Stylus transform.
