### ISSUE TITLE
PlusServer freezes after about 100 frames

### ISSUE THREAD

**Issue by dzenanz** [PlusToolkit/PlusLib#427]
I am working on [WinProbe](https://github.com/dzenanz/PlusLib/commit/698c93b794b3dea9844804adbcd0bd964f80179b) driver in Plus. Using [vtkWinProbeVideoSourceTest](https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusDataCollection/Testing/vtkWinProbeVideoSourceTest.cxx), things work: ultrasound image is displayed live. Using [PlusServer](https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusServer/Tools/PlusServer.cxx), live image is displayed for about 2 seconds, and then updating stops. Command line parameters for both:

_--verbose=4 --config-file=[/path/to/PlusDeviceSet_Server_WinProbe.xml](https://github.com/PlusToolkit/PlusLibData/blob/master/ConfigFiles/PlusDeviceSet_Server_WinProbe.xml)_

At verbose level 4, frame number is [echoed](https://github.com/dzenanz/PlusLib/commit/698c93b794b3dea9844804adbcd0bd964f80179b#diff-bb24314bd63c803aa01f3777b7ed4a5aR131) into the console. When running under debugging (F5), frame numbers go to about 111. Without debugging (Ctrl-F5), frame numbers stop around 180. It does not matter whether Slicer is listening via OpenIGTLink or not.

Is there some explanation for this difference in behavior? And more importantly, how to fix it?

**Comment by Sunderlandkyl** [comment]
Does this happen with any other devices, or just the WinProbe?

**Comment by dzenanz** [comment]
Currently, I only have WinProbe to test. @RMR54 or @jperdomo23 could test with other devices, but I do not think this happens with other devices.

**Comment by RMR54** [comment]
That's right @dzenanz, it appears to occur for WinProbe and I haven't observed it happening when streaming with Capistrano.

**Comment by dzenanz** [comment]
It turns out this was caused by a missing DLL (`UltraVision.DXWrapper.dll`, part of WinProbeSDK). I never would have guessed based on the symptoms. The solution was stumbled upon by fixing another problem.
