### ISSUE TITLE
philips epiq 7 Support

### ISSUE THREAD

**Issue by homerteo** [PlusToolkit/PlusLib#429]
The successors of the philips ie33 are the epiq 7. I would like to know if there is compatibility between Plus Toolkit and epiq 7 to record data.

Thank you.

**Comment by Sunderlandkyl** [comment]
I don't know if they use the same API. If they do, then it could be compatible.

@adamrankin do you know if the Philips device supports the EPIQ 7?

**Comment by adamrankin** [comment]
It does not. I am hoping to work with Philips to see if the EPIQ offers a research interface.

**Comment by lassoan** [comment]
If non-real-time loading is sufficient: you can import Philips 4D volumes into 3D Slicer using [SlicerHeart extension](https://github.com/SlicerHeart/SlicerHeart).

Philips has research interface for most of their systems, but they allow real-time image access to very few groups in the world, under very strict conditions. To get access, you need to convince them that your group has the necessary clinical and engineering resources, funding, worthy scientific goals aligned with Philips interests, and clear all the legal hurdles.
