### ISSUE TITLE
Frame grabber connection

### ISSUE THREAD

**Issue by freddierp** [PlusToolkit/PlusLib#433]
I've been trying to connect our U/S machine through the Startech USB S-video & composite Audio Video Capture Cable (Part # SVID2USB23) without success. I always get a reboot of my computer when doing so can someone help with the issue.

**Comment by adamrankin** [comment]
Does it work with the windows camera app or any other webcam software?

**Comment by freddierp** [comment]
Yes. It does. I tried the sample codes for frame grabber when launching the plus server.

**Comment by adamrankin** [comment]
To confirm, you are not running the other software when you try to run Plus?

**Comment by freddierp** [comment]
no I am not. The one that seems to work the best is the code for Video for Windows compatible imaging device but it connects to my webcam instead of the frame grabber.

**Comment by lassoan** [comment]
In general, these inexpensive capture devices provide very low quality results, which are unacceptable for most applications. Their hardware architecture and software interfaces may be also very limited (they may only provide low-frame rate, interlaced output, with lossy compression, they may use crossbar to switch between connectors, etc.). I would recommend getting an [ImagingControls framegrabber](https://www.theimagingsource.com/products/converters/video-to-usb-2.0/dfgusb2pro/) instead, which squeezes out more acceptable image quality from the already very limited S-video connection (it costs about $200). Or, if DVI or VGA outputs are available, invest into an [Epiphan DVI2USB framegrabber](https://www.epiphan.com/products/dvi2usb-3-0/) (costs about $700).

Anyway, you should still be able to use the cheap ones, too. Video for Windows in Plus is hardcoded to use the first device (we did not spend time with making this configurable, as it is a very outdated interface). Instead, we recommend using [Microsoft Media Foundation interface](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceMicrosoftMediaFoundation.html
) and you may also try [OpenCV capture interface](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceOpenCVVideo.html). You may need to connect through a virtual camera software if the device uses a crossbar - see details [here](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceMicrosoftMediaFoundation.html).

**Comment by adamrankin** [comment]
You can try the OpenCV capture device with CAP_VFW (or CAP_V4W) and DeviceIndex="1" (or 2, or 3, etc...) as arguments.

**Comment by freddierp** [comment]
I been trying to use the  Microsoft Media Foundation interface but it keeps connecting to m webcam instead. The OpenCV capture does not seem to work. It fails to connect. I removed the URL part from CV and tried adding the deviceIndex as you said but no success.  
[code microsoft.txt](https://github.com/PlusToolkit/PlusLib/files/2532506/code.microsoft.txt)

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
