### ISSUE TITLE
system hangs on volume reconstruction using 3D Slicer

### ISSUE THREAD

**Issue by smaatze** [PlusToolkit/PlusLib#443]
Hello, I have a problem with volume reconstruction and hope everyone could help me
In the volume reconstruction, there is option “spacing”. When I chose numbers less than “0.5” for it, the system hangs and the ultrasound and the tracker will be disconnected. My system configuration is:
CPU: Intel, core i7, 3.06 GH
RAM: 12 GB
Graphic: GeForce NVIDIA GTx 750 Ti
Graphic RAM : 2 GB
The software “ process explorer “ doesn’t show any full load working of CPU or GPU. 
Please help me with that.

**Comment by adamrankin** [comment]
32 bit build or install?

**Comment by prash-p** [comment]
I also have this issue, when using a 64 install. Typically PLUS times out and eventually crashes so I have to restart the server.

**Comment by adamrankin** [comment]
Do either of you have a MSVC build of Plus? If so, are you familiar with performance capturing in Visual Studio?

**Comment by prash-p** [comment]
I'm using the nightly pre-built versions of PLUS. I have previously tried to build PLUS on Windows, but I have run into too many errors.

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
