### ISSUE TITLE
Volume Reconstructor Application gives wrong results

### ISSUE THREAD

**Issue by prash-p** [PlusToolkit/PlusLib#445]
Tested on Stable and development Win 64 versions.

The results I get from doing an 'Offline Reconstruction' with Plus Remote + SlicerIGT do not seem to match the results when I use VolumeReconstructor.exe directly from the command line, with the same input source file. I have to make a separate config file to use the command line tool, containing only a volumeReconstruction element (why is it not possible to use the config file directly as output by Plus when recording a sequence?)

When using Plus Remote I get the expected reconstruction, but using the command line I seem to be getting the reconstruction in the wrong location and the output is a segmentation map (when imported in Slicer) instead of a scalar uint8 volume.

**Comment by prash-p** [comment]
This is the config file I'm using with the application:

`<PlusConfiguration version="2.1" PlusRevision="Plus-2.7.0.4b181408 - Win64">
<DeviceSet Name="Vol Recon Only" Description=" " />
      <VolumeReconstruction 
        ImageCoordinateFrame="Image"
        ReferenceCoordinateFrame="Phantom"
        Optimization="FULL"
        CompoundingMode="MEAN"
        FillHoles="ON"
        Interpolation="NEAREST_NEIGHBOR"
        NumberOfThreads="4"
        ClipRectangleOrigin="0 0"
        ClipRectangleSize="0 0"
        OutputOrigin="0 0 0"
        OutputExtent=" "
        OutputSpacing="0.3 0.3 0.3">
    <HoleFilling>
      <HoleFillingElement
        Type="STICK"     
        StickLengthLimit="9"
        NumberOfSticksToUse="1" />
    </HoleFilling>
  </VolumeReconstruction>

  <CoordinateDefinitions>
    <Transform From="StylusTip" To="Stylus"
      Matrix="
        1	0	0	-18.7472
        0	-1	-1.22465e-16	0.128555
        0	1.22465e-16	-1	-159.01
        0	0	0	1"
       Error="0.079" Date="111318_115449" />
    <Transform From="Image" To="Probe"
      Matrix="
        0.0961967	0.00198534	0.0168013	-53.5166
        -0.0168313	0.0014136	0.0962016	31.1163
        0.00171227	-0.0976427	0.00173435	-44.1661
        0	0	0	1" />
  </CoordinateDefinitions>
  
</PlusConfiguration>
`

Transforms ProbeToTracker and PhantomToTracker are provided in the source .mha file

**Comment by prash-p** [comment]
Update: When using the virtual volume reconstructor device and Plus Remote, I can recover the correct results. This is slightly annoying because I was hoping to batch process a group of .mha sequence files using the volumereconstructor.exe command line tool, instead of creating a config file for each separate file and then going into slicer and plus remote. Any clues @adamrankin @lassoan ?

**Comment by prash-p** [comment]
Slice was importing .mha volumes as label maps by default for some reason, so have to untick this option everytime (using 'show more options') when loading data in Slicer.
Wrong location problem due to difference in plus' coordinate frame and slicer's coordinate frame, have to invert R and A axis when importing in Slicer to recover correct position...

**Comment by lassoan** [comment]
There is a heuristics in Slicer's "Add Data" dialog that tries to guess if it is a labelmap or not. Having "label" or "seg" in the filename will make it interpreted as labelmap by default.

Slicer uses RAS coordinate system internally and LPS when reading from file. If you want consistent behavior then you can define an ReferenceToLPS transform in Plus (as diagonal matrix (-1.0,-1.0,1.0,1.0)) and reconstruct in LPS coordinate system (instead of Reference coordinate system) when using command-line tools.
