### ISSUE TITLE
Unable to find the stylus calibration file (fCal)

### ISSUE THREAD

**Issue by Praveensidharth** [PlusToolkit/PlusLib#450]
Hi,

I am trying to use fcal to interface ultrasound image(using frame grabber) and Polaris spectra stereo camera. I was able to connect, capture and perform stylus calibration. I am however not able to perform the phantom registration and other sequential calibration tasks. I would be grateful if someone can guide me on finding the stylus calibration file and provide me documentation to perform the rest of the tasks. 

I have attached the config for reference.

Thank you
[PlusDeviceSet_fCal_Epiphan_NDIPolaris.zip](https://github.com/PlusToolkit/PlusLib/files/2615460/PlusDeviceSet_fCal_Epiphan_NDIPolaris.zip)

**Comment by Sunderlandkyl** [comment]
Can you upload your log file?

If you already have the stylus calibration, you can add the transform to the config file:
```
<CoordinateDefinitions>
    <Transform From="StylusTip" To="Stylus"
      Matrix="
        0.997221  0.0675365  0.0314631  194.844
        -0.06757  0.997715  0  -13.2023
        -0.0313912  -0.00212596  0.999505  -6.13342
        0  0  0  1"
       Error="0.450335" Date="091112_150057"/>
</CoordinateDefinitions>````

**Comment by Praveensidharth** [comment]
I got some errors while processing, I attached the log file and errors which I got. 

![configuration](https://user-images.githubusercontent.com/45356545/49152438-d3af4f80-f338-11e8-90f3-5a9f85aad540.png)
![capturing](https://user-images.githubusercontent.com/45356545/49152443-d9a53080-f338-11e8-8bf7-f80ee96327d4.png)
![stylus](https://user-images.githubusercontent.com/45356545/49152446-ddd14e00-f338-11e8-8082-e08028d11b56.png)
![phantomtoreference](https://user-images.githubusercontent.com/45356545/49152474-f5103b80-f338-11e8-8fb1-e4c4285a6fe4.png)
![screenshot 11](https://user-images.githubusercontent.com/45356545/49152550-33a5f600-f339-11e8-8563-0a1cb168168e.png)

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
