### ISSUE TITLE
Missing dll for packages including MicronTracker

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#451]
![image](https://user-images.githubusercontent.com/9222709/49037734-0286c380-f189-11e8-8ecd-adf24b298263.png)

digiclops.dll is included in the build, but is not included in the package.

**Comment by adamrankin** [comment]
I'll check it out, I changed this recently.

**Comment by adamrankin** [comment]
Easy fix, got it.

**Comment by Sunderlandkyl** [comment]
Great, thanks!

**Comment by lassoan** [comment]
Thank you, I'll test the nightly build tomorrow.
