### ISSUE TITLE
Temporal Calibration doesn't take into account the ROI

### ISSUE THREAD

**Issue by MaXZon3** [PlusToolkit/PlusLib#453]
Dear all,

First of all, thank you very much for your software. It looks very interesting and I'm trying to use it to perform a calibration between a US image and an attached EM sensor from the trakSTAR device.

I succeeded to use the software until the temporal calibration step.

In our project, we need the temporal calibration step because we grab the entire screen from the US device through a frame grabber. So, the frames and the transformation matrices are not synchronized.

To show our problem, you can directly use the `PlusDeviceSet_fCal_Sim_TemporalCalibration.xml` file that you give.
Using this simulation, if I go to the Spatial Calibration step and change the coordinates, nothing changes.
For example, I tried to change the combo box like:
- from `x=10, y=10`
- to `x=20, y=20`

The result looks like this:
![segmentationparametersettings](https://user-images.githubusercontent.com/15032112/49086627-4941ef80-f255-11e8-8fc7-3a7c5f1aa67e.PNG)

But, the line detection still continues to work!:
![temporalcalibration](https://user-images.githubusercontent.com/15032112/49086794-ab9af000-f255-11e8-9479-a7edf8d58b04.PNG)

So, when we test with live data, the line detection doesn't work because of too many information in the images. (Here is a video example: [WaterTank.zip](https://github.com/PlusToolkit/PlusLib/files/2620300/WaterTank.zip))

So, two questions:

1. Should I manually crop my video stream before sending it to `fCal` ?
2. Or, is the cropping box for temporal calibration broken?

Thank you for your help.

Regards.

**Comment by MaXZon3** [comment]
> 
> 
> I don't think the ROI ever applied to the temporal calibration. I'll check it out. A workaround for now is to crop the image before sending it to fCal.

As explained [in your tutorial presentation](https://github.com/PlusToolkit/PlusLib/files/2620647/PlusTutorialfCalCalibrationProcess.pptx), it's written that it works like that (slide 12). 🤔

**Comment by adamrankin** [comment]
Yes, I take it back, it should be working.

**Comment by MaXZon3** [comment]
Thank you. I'll test today and let you know 😉 .

**Comment by adamrankin** [comment]
Also, the segmentation parameter dialog only applies to the spatial calibration. The ROI set in that dialog does not affect temporal calibration.

**Comment by adamrankin** [comment]
I will change the preview to take into account any clipping set in the configuration file.

**Comment by MaXZon3** [comment]
> 
> 
> Now, one small detail, what you see in fCal is a preview, which doesn't take cropping into account. When you perform the calibration, does it work?

Oh, I didn't notice that. I will test but I remember that it doesn't work with the given video in my [previous comment](https://github.com/PlusToolkit/PlusLib/issues/453#issue-384814651).

> 
> 
> Also, the segmentation parameter dialog only applies to the spatial calibration. The ROI set in that dialog does not affect temporal calibration.

So, I think that there is a mistake in the PlusTutorialfCalCalibrationProcess.pptx file (slide 12), because it's written:
>
>
> The same ROI is used for temporal calibration as for spatial calibration, so the ROI can be set in the same place, in the Spatial calibration tab, as shown above

Is it really a mistake in the presentation or a software regression? 🤔 

> 
> 
> I will change the preview to take into account any clipping set in the configuration file.

Thank you for your help 😉

**Comment by adamrankin** [comment]
`Also, the segmentation parameter dialog only applies to the spatial calibration. The ROI set in that dialog does not affect temporal calibration.`

@lassoan could you confirm? The code shows no connection, but the tutorial slides say otherwise. I will double check the code.

**Comment by adamrankin** [comment]
Double checked, nowhere in the code does the segmentation parameter dialog apply the clipping to temporal calibration, nor does the temporal calibration pull clipping parameters from spatial calibration configuration.

**Comment by lassoan** [comment]
You are supposed to clip the image in the video source.

The additional ROI is only needed for spatial calibration because that algorithm is particularly sensitive (detecting fiducial line candidates and match to calibration phantom geometry is tricky). No additional 

ROI should be needed for line detection and I'm quite sure spatial calibration ROI is not used for temporal calibration's line detection.

**Comment by adamrankin** [comment]
And yes, that tutorial is incorrect. Did you get that from a link on plustoolkit.org?

**Comment by MaXZon3** [comment]
> Double checked, nowhere in the code does the segmentation parameter dialog apply the clipping to temporal calibration, nor does the temporal calibration pull clipping parameters from spatial calibration configuration.

Just to be sure, if I give the right coordinates in :
```
<vtkTemporalCalibrationAlgo
   ClipRectangleOrigin="10 10"
   ClipRectangleSize="10 10" />
```
is the clip really applied before launching the line detection algorithm? Or, as recommended by @lassoan , must I really need to crop them before? In that case, what is exactly the purpose of the `ClipRectangle...` parameters?

> You are supposed to clip the image in the video source.
> 
> The additional ROI is only needed for spatial calibration because that algorithm is particularly sensitive (detecting fiducial line candidates and match to calibration phantom geometry is tricky). No additional
> 
> ROI should be needed for line detection and I'm quite sure spatial calibration ROI is not used for temporal calibration's line detection. It could be nice to have, but should not be necessary.

In our case, we need to perform the hole calibration process quickly because the EM sensor attached to the US probe can be removed and attached anywhere from one day to another.

It's why we would like to perform it with live video stream. If I need to crop the data manually, it supposed to be recorded, cropped and replayed in fCal witch take times that we would like to reduce.

Another option could be to crop it live with an external software (such as ffmpeg for example). But doing so, it will add computation time and I supposed that the result could be wrong because that pre-processing step is not needed while doing the spatial calibration.

Do I have well understand your point when you recommend to `clip the image in the video source`?

> And yes, that tutorial is incorrect. Did you get that from a link on plustoolkit.org?

From [this link](https://github.com/PlusToolkit/PlusDoc/raw/master/tutorials/PlusTutorialfCalCalibrationProcess.pptx) referenced in [your documentation page](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/ApplicationfCal.html) (first link called `Performing tracked ultrasound probe calibration using fCal, see also the video tutorial`).

**Comment by MaXZon3** [comment]
@adamrankin I tested your [pull request](https://github.com/PlusToolkit/PlusApp/pull/57) and it works well! The ROI set in the segmentation parameters is correctly applied in the temporal calibration algorithm too and it is also visible in the preview. 👍 

Just one question: after performing a temporal registration, if I change the ROI in the segmentation parameters, it seems to not change in the temporal calibration anymore (it keeps the first one). Is it the expected behavior?

Thank you again for your time! 😃

**Comment by adamrankin** [comment]
> it seems to not change in the temporal calibration anymore (it keeps the first one). Is it the expected behavior?

Ah I did assume that `OnActivated` of the toolbox was called everytime you switched to it (and thus settings would be reloaded. I'll fix that up.

**Comment by adamrankin** [comment]
Great!
