### ISSUE TITLE
fCal tutorial documentation is out-of-date

### ISSUE THREAD

**Issue by adamrankin** [PlusToolkit/PlusLib#455]
Links on this page
http://perk-software.cs.queensu.ca/plus/doc/nightly/user/ApplicationfCal.html

have incorrect information in the calibration tutorial.

**Comment by lassoan** [comment]
You can fix it here: https://github.com/PlusToolkit/PlusApp/blob/master/Documentation/ApplicationfCal.dox

**Comment by adamrankin** [comment]
I wonder if it's better use of our time to just port temporal calibration to slicer. I guess network lag (even in machine) is undesirable...

**Comment by adamrankin** [comment]
Nice, any thoughts on just producing a plus extension?

**Comment by lassoan** [comment]
The "Plus extension" is called [SlicerIGSIO](https://github.com/IGSIO/SlicerIGSIO/).

**Comment by Sunderlandkyl** [comment]
I think perhaps that there is a distinction that could be made depending on if we want to consider SlicerIGSIO to be a utility extension vs an extension with many user-facing modules.

**Comment by lassoan** [comment]
That's true. We can keep SlicerIGSIO a utility extension and keep user-facing modules in SlicerIGT and other extensions.

**Comment by lassoan** [comment]
IGSIO will provide python wrapping for all of its classes (using VTK's wrapper). They will be usable from any Python interpreter, including Slicer's.
