### ISSUE TITLE
[Discussion] Next release

### ISSUE THREAD

**Issue by adamrankin** [PlusToolkit/PlusLib#460]
@Sunderlandkyl @lassoan 

With the inclusion of video streaming I would suggest incrementing the next release to 3.0 as opposed to 2.10.

Thoughts?

**Comment by Sunderlandkyl** [comment]
Either 3.0 or 2.10 sounds fine to me. I don't have any preference.

I'll go through the release checklist this week and create the new stable release.

The cutoff will likely be the commit before the IGSIO migration + commits for any additional fixes that are required.
