### ISSUE TITLE
Stealthlink AxiEM electromagnetic

### ISSUE THREAD

**Issue by order86** [PlusToolkit/PlusLib#462]
Hello guys,
do you think is it possible to track also Medtronic AxiEM electromagnetic tools into 3d Slicer? I've tried to add the correct port name in config.XML file. For example:
      <DataSource Type="Tool" Id="Reference" PortName="Non-Invasive Patient Tracker" /> 
<DataSource Type="Tool" Id="Stylus" PortName="TRACER_Pointer" />

but it seems that these Port Names are not recognized.
Do you have experiences about that?

thanks

**Comment by order86** [comment]
DataSource Type="Tool" Id="Stylus" PortName="9733367_AXIEM_TRACER_Pointer" 
        DataSource Type="Tool" Id="TProbe" 	 PortName="9733365_AXIEM_Navigation_Pointer"

**Comment by order86** [comment]
this is the example:
	<DataSource Type="Tool" Id="Stylus" PortName="TRACER Pointer" />
        <DataSource Type="Tool" Id="TProbe" 	 PortName="Navigation Pointer" />

**Comment by order86** [comment]
<DataSource Type="Tool" Id="Stylus" PortName="TRACER Pointer" />
        <DataSource Type="Tool" Id="TProbe" 	 PortName="Navigation Pointer" />

**Comment by adamrankin** [comment]
I am not familiar with that magnetic tracker, does it use an interface of an existing device type in Plus? Could I see the whole device tag that you have configured?

**Comment by order86** [comment]
<Device
      Id="SLD"
      Type="StealthLinkTracker"
      ServerAddress="172.16.13.55"
      ServerPort="6996"
      RegistrationUpdatePeriod="0.0"
      ToolReferenceFrame="Tracker" >
      <DataSources>
        
        
		<DataSource Type="Tool" Id="Stylus" PortName="TRACER Pointer" />
        <DataSource Type="Tool" Id="TProbe" 	 PortName="Navigation Pointer" />
        <DataSource Type="Tool" Id="Reference" PortName="Non-Invasive Patient Tracker" /> 
        <DataSource Type="Tool" Id="Ras" 	    PortName="RasRegistration" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream">
          
		  <DataSource  Id="Stylus" />
          <DataSource  Id="TProbe" />
          <DataSource  Id="Reference" />
          <DataSource  Id="Ras" />
        </OutputChannel>
      </OutputChannels>
    </Device>
    <Device
      Id="CaptureDevice"
      Type="VirtualCapture"
      BaseFilename="RecordingTest.mha"
      EnableCapturingOnStart="FALSE" >
      <InputChannels>
        <InputChannel Id="TrackerStream" />
      </InputChannels>
    </Device> 

Probably

**Comment by Sunderlandkyl** [comment]
Can you upload a log file?
When trying to connect to the StealthStation, it should show a list of the available tools.

**Comment by lassoan** [comment]
> I am not familiar with that magnetic tracker, does it use an interface of an existing device type in Plus? Could I see the whole device tag that you have configured?

AxiEM is Medtronic StealthStation's EM tracker. It uses StealthLink to send tracking data similarly (hopefully exactly the same way) as the optical tracker.

**Comment by order86** [comment]
Tomorrow i will be at work and i will paste you the log file. But, unfortunatly in the log file there wasn't a list of the available tools. There was only an error about the wrong name of PortName

**Comment by adamrankin** [comment]
Re-open if further discussion.
