### ISSUE TITLE
PlusVersion software version text changed

### ISSUE THREAD

**Issue by jamesobutler** [PlusToolkit/PlusLib#465]
Previously PlusVersion would show something like "Software version: Plus-2.7.0.31cbda03 - Win32", but my most recent build shows "Logging software version: IGSIO-1.0.0 - Win32". Is this as expected? I had some code that I used to confirm I was using a Plus build at a specific PlusLib commit.

**Comment by Sunderlandkyl** [comment]
A number of classes from PlusCommon, including the logging classes, were migrated to IGSIO.
The "Logging software version: ..." message is printed by IGSIO when logging starts.

I'll see about either overriding the message when logging is instantiated, or logging the Plus software version when the server starts.

**Comment by lassoan** [comment]
We could override default igsio project name and version by setting CMake variables when igsio is configured. If those variables were not specified then default name and version (specified in igsio) would be used.

**Comment by Sunderlandkyl** [comment]
Should be fixed by: 483130df35ec6793b40b6e69d7510cdc42199d16

**Comment by jamesobutler** [comment]
@Sunderlandkyl Unfortunately the commit broke static Plus builds which is what I use. You can see the cdash report [here](http://perkdata.cs.queensu.ca/CDash/viewBuildError.php?buildid=107771)

**Comment by Sunderlandkyl** [comment]
Static builds should be fixed (9404c991e7d80badb4db1df3c06f662af8761c90)

**Comment by jamesobutler** [comment]
Ah thanks! Hadn't refreshed the main repo page. I'll start my build again.

**Comment by jamesobutler** [comment]
I see "Software version: Plus-2.7.0.d7778944 - Win32" now when using PlusVersion.exe. Thanks!
