### ISSUE TITLE
Volume scan-convert 4DEC9-5/10 from Ultrasonix

### ISSUE THREAD

**Issue by magednasan** [PlusToolkit/PlusLib#467]
Hello,
I would like to know whether we can perform a volume scan-convert of a stack of US frames (acquired using  4DEC9-5/10 transducer and Propello application) using PlusToolkit.
Regards,

**Comment by Sunderlandkyl** [comment]
What file format are the US frames in?
If they're combined in a single nrrd/mha/mhd file, you can use the VolumeReconstructor application: http://perk-software.cs.queensu.ca/plus/doc/nightly/user/ApplicationVolumeReconstructor.html

**Comment by magednasan** [comment]
It is .vol file!

**Comment by lassoan** [comment]
We have been using Plus for 4D data acquisition and live volume reconstruction:

https://www.youtube.com/watch?v=KTz0nwAmeMo

We used 4DL14-5/38 probe, but it should work with your probe, too. The configuration file that we used is here: perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceSonixVideo.html

I think the Propello demo application saves scan-converted slices into .vol files, so you can extract data from there and save into a sequence file data Plus can interpret and reconstruct volumes for it. You can find sequence file format specification in Plus documentation and we can explain any details if unclear, but you would need to figure out the conversion from .vol file on your own.

**Comment by lassoan** [comment]
You can query pixel spacing from the ultrasound machine and use that to compute the radius in pixels or you can open one ultrasound image and count the pixels there.

**Comment by magednasan** [comment]
Thank you, that was useful!
