### ISSUE TITLE
Unable to perform spatial calibration

### ISSUE THREAD

**Issue by MaXZon3** [PlusToolkit/PlusLib#470]
Hello again 👋 😄 

First, thank you for [your corrections](https://github.com/PlusToolkit/PlusLib/issues/453) last week!
We were able to successfully perform the temporal registration (~190ms).

Now, we are stuck in the last step: performing the spatial calibration. 😢 

Indeed, we 3D printed you proposed model called `fCal_2.1.stl` and put the wires as proposed in some configuration files examples.
![img_20181207_101409](https://user-images.githubusercontent.com/15032112/49724290-3d98f480-fc69-11e8-9573-c98e5ed07de8.jpg)

The detection of points in the Segmentation Parameter Settings window look to works well after changing the Morphology parameters.
![2018-12-06-11-22-57](https://user-images.githubusercontent.com/15032112/49724679-26a6d200-fc6a-11e8-9786-3016f3852224.png)

But, we are unable to well detect the wires (red points never change to green points) as in your spatial calibration simulation example.
![2018-12-06-11-16-00](https://user-images.githubusercontent.com/15032112/49724544-d62f7480-fc69-11e8-9c9e-d94d3257dd95.png)

Here is a zip file with a video of our spatial calibration test + our associated configuration file + the `fCal_2.1.stl` file that we used.
[XP 2018_12_06.zip](https://github.com/PlusToolkit/PlusLib/files/2662678/XP.2018_12_06.zip)

I think that we may have done several mistakes but here is some ideas that we already checked:
- The points defined in the `<PhantomDefinition>` looks good (check the 3D coordinates with Paraview)
- No transforms are applied (`modelToObjectTransform` are set to identity in `<DisplayableObject>`)
- Stylus calibration looks good (`Error = ~0.3 mm`)
- Phantom to reference registration looks good (`Error = ~0.98 mm`)

Do you have an idea of what we are possibly doing wrong? 🤔 

Thank you very much for your time! 😃

**Comment by MaXZon3** [comment]
Yes sure. 😃 
[120618_091716_PlusLog.zip](https://github.com/PlusToolkit/PlusLib/files/2666979/120618_091716_PlusLog.zip)

**Comment by MaXZon3** [comment]
Hello :wave: ,

Any update about this issue ? :smiley:

**Comment by adamrankin** [comment]
Have you adjusted the spacing in the seg parameter dialog?

**Comment by MaXZon3** [comment]
Not in the segmentation parameter dialog nor directly in the spatial calibration tab in fCal. :worried:

**Comment by adamrankin** [comment]
Ok, on the top left of seg. para. dialog, click the spacing checkbox, a green and blue widgets will appear. drag the green knobs such that they are aligned with a wide set of wires (M1_m1 and G1_g1, for example) and the blue knobs such that they are aligned with a tall set of wires (M1_m1 and M5_m5, for example). The dots should turn green.

**Comment by lassoan** [comment]
If you set the spacing as @adamrankin suggested above then you'll see the dots turn green.

However, there are a few issues. The image in the screenshot is extremely bad quality. For example, you have reflection from the bottom of the water tank. See tips on [fCal application documentation](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/ApplicationfCal.html) and [calibration tutorial slides](https://github.com/PlusToolkit/PlusDoc/raw/master/tutorials/PlusTutorialfCalCalibrationProcess.pptx) about how to improve image quality.

It is also suboptimal that the wires cover only a tiny fraction of the image (you have a large field of view and depth; compared to that, the calibration phantom is very small). So, your accuracy will not be good (you may have several mm of errors). You would either need to fabricate a larger phantom, such as the [fCal 3 phantom](http://perk-software.cs.queensu.ca/plus/doc/nightly/modelcatalog), or don't use calibration phantom at all but calibrate using a tracked stylus (see [U-31 SlicerIGT tutorial](http://www.slicerigt.org/wp/user-tutorial/)).

**Comment by adamrankin** [comment]
I would second moving to the tracked stylus method of calibration.

**Comment by MaXZon3** [comment]
> Ok, on the top left of seg. para. dialog, click the spacing checkbox, a green and blue widgets will appear. drag the green knobs such that they are aligned with a wide set of wires (M1_m1 and G1_g1, for example) and the blue knobs such that they are aligned with a tall set of wires (M1_m1 and M5_m5, for example). The dots should turn green.

Ok, thank you very much for this explanation! We will try this way.

> If you set the spacing as @adamrankin suggested above then you'll see the dots turn green.
> 
> However, there are a few issues. The image in the screenshot is extremely bad quality. For example, you have reflection from the bottom of the water tank. See tips on [fCal application documentation](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/ApplicationfCal.html) and [calibration tutorial slides](https://github.com/PlusToolkit/PlusDoc/raw/master/tutorials/PlusTutorialfCalCalibrationProcess.pptx) about how to improve image quality.
> 
> It is also suboptimal that the wires cover only a tiny fraction of the image (you have a large field of view and depth; compared to that, the calibration phantom is very small). So, your accuracy will not be good (you may have several mm of errors). You would either need to fabricate a larger phantom, such as the [fCal 3 phantom](http://perk-software.cs.queensu.ca/plus/doc/nightly/modelcatalog), or don't use calibration phantom at all but calibrate using a tracked stylus (see [U-31 SlicerIGT tutorial](http://www.slicerigt.org/wp/user-tutorial/)).

Thank you for the advise. Regarding to the bad image quality, we tried our best to have the better image as possible :sweat_smile: . We will try to improve that and print the version 3 of the phantom. Thank you also for the documentation and slides that we had already read ([we previously had found an error](https://github.com/PlusToolkit/PlusLib/issues/453)).

Regarding your recommendation to use the 3D slicer extension, what is the point to have both methods (fCal and SlicerIGT)? :thinking: 

So, regarding you comment and the following one:
> I would second moving to the tracked stylus method of calibration.
it is better to use `SlicerIGT` to perform the hole calibration process than `fCal` directly? I was thinking that using the phantom will give us a better precision. Am I right?

Again, thank you for your help @adamrankin & @lassoan :+1: .

We will try both `fCal` (with both phantom) and `SlicerIGT` (with a tracked stylus) as soon as possible and I'll come back to validate if the initial problem of this issue is solved or not :wink: .

And ... Happy New Year. :tada: :smile:

**Comment by MaXZon3** [comment]
Dear @adamrankin and @lassoan ,

We made some experiments last week and the [previous proposition](https://github.com/PlusToolkit/PlusLib/issues/470#issuecomment-449007440) from @adamrankin works well and we succeed to perform some probe calibrations! :tada: .

We have not yet try the solution from SlicerIGT as adviced for the moment.

Just a kind reminder about the question in my [previous message](https://github.com/PlusToolkit/PlusLib/issues/470#issuecomment-451893857), is it better to use `SlicerIGT` to perform the hole calibration process than `fCal` directly?

Thank you very much for your time and all your answers. :smiley: :+1:

**Comment by adamrankin** [comment]
Well, this is more of a personal preference question, as I have seen results from both methods produce high quality calibrations.

I have moved to the Slicer method of calibration as our lab is investing in other mathematical models of calibration, and implementing them in Slicer.

If you're interested, see the G(uided)U(ltra)S(ound)CAL(ibration) module of SlicerVASST extension in Slicer.

**Comment by ungi** [comment]
Another thought on methods of calibration. The method in fCal (and similar methods) require precise phantom manufacturing and custom phantom design for specific transducers. But if it is done well, the calibration does not depend on the user. In comparison the SlicerIGT method (and similar methods) can be readily used for any transducer, but the accuracy depends on the operator skill and experience.
I recommend fCal style method for product development, and SlicerIGT style method for custom research prototype solutions.
As Adam says, both methods are accurate when done properly.

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
