### ISSUE TITLE
Multimodality tracking/ Coordinate transforms in Matlab 

### ISSUE THREAD

**Issue by slavasani** [PlusToolkit/PlusLib#472]
Hello,

I was going to test EMT tracker against Optic tracker so I used 3D Slicer for the sake of Temporal synchronization and Spatial calibration. I exactly followed 3D slicer tutorial/Multimodality tracking and everything went well, I saved transformations and recorded data through Plus remote but when I load trackers data in Matlab and multiple transformations to have the stylus tip position in Optic reference coordinate system as I had in the 3D slicer, the result doesn't seem correct. The sequence of transformations is shown in the picture. 
Have I missed a point? Do I need to consider something in the process of multiplying Transformations in Matlab?
I would appreciate if someone helps me.

![capture](https://user-images.githubusercontent.com/40196849/50151268-a91c3b00-02d5-11e9-911c-471d7c29a688.gif)

**Comment by lassoan** [comment]
Does everything work well in Slicer? Were you able to compute the transform between optical and electromagnetic tracker?

Have you considered performing all necessary computations in Python - in 3D Slicer's Python console, in a [Slicer Jupyter notebook](https://github.com/Slicer/SlicerJupyter), or in a Python scripted module in Slicer?

**Comment by slavasani** [comment]
I had made a mistake in the sequence of multiplying the matrixes. I reached the correct result with the sequences that are shown below.  
![capture](https://user-images.githubusercontent.com/40196849/51423595-e5de9900-1bd7-11e9-90e6-7eaf2d4a61ec.JPG)
