### ISSUE TITLE
simple surface reconstruction using a tracker

### ISSUE THREAD

**Issue by dimitri80** [PlusToolkit/PlusLib#473]
Hello,
This is great project you have here, I was wondering if you could help me out.  I am using an Atracsys fusionTrack500 tracker and need to log a stylus tip's path to create a point cloud.   the PointSetExtractor tool  can almost meet my needs, but it appears dependent on a sequence metafile to obtain the path,  is there a way to just use the PointSetExtractor with a live feed from the tracker?   Perhaps the TrackingTest tool is the right way to go for this, but I dont see a way to load a tools Stylus Tip into that.   

To be clear, I would like to find a way, using just a tracker, a reference geometry, and a stylus to 1) calibrate the stylus tip and 2) be able to log its positions/rotations to create a point cloud.  

Any help would be greatly appreciated.

**Comment by lassoan** [comment]
I don't think there is a readily usable solution for exactly what you would like to do, but there are several ways to achieve that quite easily.

Can you tell us a bit more about your end goal (what is the clinical problem and what approach are you considering to solve it) so that we can make recommendations accordingly?

**Comment by adamrankin** [comment]
I would perform the stylus calibration in fCal, then stream the tracked tip to Slicer, then use SlicerIGT's CollectPoints module.

**Comment by dimitri80** [comment]
@adamrankin the fCal calibration and then collecting points module worked wonderfully, the next step is how to transform the RAS anatomical coordinates of the captured fiducials into an image coordinate system,  or xyz with direction/rotation.  i wonder if there is a module that can do this transformation that you might recommend, i have been searching the archives about this subject, and there seems to be a lot of different opinions on the best way to.  thank you.

@lassoan thank you very much for your interest in what I am trying to achieve.  i am attempting to use a fusionTrack500 and the Plus toolkit to track the tool tip of a Kuka robot that is milling precision surgical quality models.  by tracking and creating a point cloud of the tool path I would like to be able to compare the actual (tracked path) to the programmed path and eventually be able to correct it on the fly, this as well as using the tracker for spot measurments.  Any suggestions would be greatly appreciated.

**Comment by adamrankin** [comment]
You might be able to use the slicer sequences module to do that.

@lassoan can you manually add a time point to a sequence or is it always a
recording?

**Comment by adamrankin** [comment]
Ok, I've confirmed that the sequence module can do what you'd like. You can manually capture one transform at a time, and build a sequence of transforms, which you can then save as .mha for analysis.

![image](https://user-images.githubusercontent.com/3210398/50575099-1cd54200-0dc4-11e9-8e38-6ed9aca108ed.png)

Click on your incoming transform, then click on the arrow. It will store the current transformation (4x4 matrix) into the sequence.

**Comment by lassoan** [comment]
You can use [EditSequenceFile](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/ApplicationEditSequenceFile.html) tool to combine transforms to get transformation between any pair of coordinate systems (i.e., position&orientation in any coordinate system).

You can also use Slicer to collect transforms (using Sequence browser module of Sequences extension; or using Transform Recorder module of PerkTutor extension). The nice thing is that you can visualize points in real-time, perform registrations, etc. in Slicer, using existing modules or minimal Python scripting. You might use parts of [TrackingErrorInspector](https://github.com/SlicerIGT/SlicerTrackingErrorInspector) extension useful for data acquisition and real-time visualization. If you have any questions related to Slicer or Slicer extensions, then post it on the [Slicer forum](https://discourse.slicer.org).
