### ISSUE TITLE
Can't connect to NDI Aurora in Debug

### ISSUE THREAD

**Issue by CrazyJinx1** [PlusToolkit/PlusLib#474]
Hello!
I have downloaded the PLUS  software from your website and then connected my NDI Aurora to the PLUS  successfully .Then I build the project using your source code.But  I can't connect to Aurora in debug mode(I have modified the "SerialPort" to "6"  which is the NDI serial port ).
Would you mind tell me why and how to do to solve this question?
Thank you very much!~

**Comment by CrazyJinx1** [comment]
![_20181219110744](https://user-images.githubusercontent.com/45961825/50196511-5c406f00-037e-11e9-9a3e-117d12d6ca5b.png)
Here is my trace log

**Comment by Sunderlandkyl** [comment]
You need to enable PLUS_USE_NDI in CMake.

**Comment by CrazyJinx1** [comment]
> You need to enable PLUS_USE_NDI in CMake.

Wow ,I have solved this problem.I am really appreciated for your help!
