### ISSUE TITLE
How to open the console

### ISSUE THREAD

**Issue by CrazyJinx1** [PlusToolkit/PlusLib#476]
Hello!
I want to open the console to test which step my code is running ?
How to do this?  Thank you ~

**Comment by adamrankin** [comment]
Do you mean how to step-through debug a program? I'm afraid that's outside of the scope that we can help you with, but there are many excellent tutorials online.

**Comment by CrazyJinx1** [comment]
> Do you mean how to step-through debug a program? I'm afraid that's outside of the scope that we can help you with, but there are many excellent tutorials online.

I am afraid that my expression is unclear.I want to see this console window  like MITK 
![image](https://user-images.githubusercontent.com/45961825/50382753-77461280-06e1-11e9-90e9-40a72e4f1dd9.png)
Do you have any way to do this ? 
Thank you!

**Comment by lassoan** [comment]
PlusServer provides a log, both in files and in console window. How do you start PlusServer? Using command-line, using PlusServerLauncher Plus application, or using 3D Slicer's PlusRemote module?
