### ISSUE TITLE
Some troubles about NDI's timestamp 

### ISSUE THREAD

**Issue by CrazyJinx1** [PlusToolkit/PlusLib#478]
Hello !
 I have connected my ultrasound device and NDI Aurora to PLUS .But I have some troubles about timestamp.Here is my log.
![image](https://user-images.githubusercontent.com/45961825/50381609-24ab2d00-06c6-11e9-97f9-25bd40e47f7b.png)
I am a novice programmer in c++,so some questions might be difficult for me.Would you mind telling  me how to do to solve this problem?
Thank you very much!

**Comment by lassoan** [comment]
Did you manage to fix the issue? What was the problem?

**Comment by CrazyJinx1** [comment]
> Did you manage to fix the issue? What was the problem?

Yes, I have fixed this issue.This problem might be caused by the breakpoint I set .Whenever I connect my device to PLUS , this breakpoint may stay for a moment.Now I have remove the breakpoint and these error are disappeared.
Thanks for your attention!
