### ISSUE TITLE
converting vertices to ".stl" file format

### ISSUE THREAD

**Issue by salimohamadi** [PlusToolkit/PlusLib#480]
Hi. I have a 3D point cloud (vertices) and I'm looking for a way to get their faces in Matlab to be able to create a ".stl" or ".ply" file format to load my data in 3D Slicer. I have attached my vertices. I wonder if someone can help me?

[MeanModel.zip](https://github.com/PlusToolkit/PlusLib/files/2717810/MeanModel.zip)

**Comment by lassoan** [comment]
I would recommend to ask on MATLAB forums about how to export point data to standard file formats that other software can read, for example .ply format.

You then need to reconstruct a surface from points, for example, using MeshLab (free, open-source application). However, surface reconstruction is a non-trivial operation, it applies various heuristics trying to guess how to connect the points to generate surface, so it is better to avoid in the first place.

This question does not seem to be related to Plus toolkit. If you need help with surface reconstruction and loading into Slicer then post to MeshLab forum or [Slicer forum](https://discourse.slicer.org).

**Comment by salimohamadi** [comment]
Dear Andras Lasso,
thanks for answering.
And, happy new year
