### ISSUE TITLE
Visualizing the Recorded data in Matlab

### ISSUE THREAD

**Issue by salimohamadi** [PlusToolkit/PlusLib#481]
Hi. I have scanned an object from 2 different directions and recorded it from PlusRemote/Recording.
So after these steps:
- 1-segmentation the US images,
- 2-making the hierarchy that I have in Slicer by multiplying the segmentation result by the transform matrixes extracting from ".mha" saved file, as follows:
pointsToTracker = ProbeToTracker * ImageToProbe * TrOriginPixelToImage * TrOriginToTrOriginPixel * ProbeModelToTrOrigin * USpoints ;
- 3- visualizing the result by "scatter3" function,

I expect to see two sets of points overlapping because these two sets of points are obtained from two scans of an object. But this does not happen. 
looking forward to getting a solution to my problem.

**Comment by lassoan** [comment]
I don't know what coordinate system USpoints are defined in. If point positions are ultrasound image pixel coordinates then it is the Image coordinate system, so you need to apply ProbeToTracker * ImageToProbe to transform all of them to the same physical coordinate system.

There is a wide range of data collection, calibration, registration, visualization methods available in [3D Slicer](https://www.slicer.org) and its [SlicerIGT](http://www.slicerigt.org/), [SlicerOpenIGTLink](https://github.com/openigtlink/SlicerOpenIGTLink/), [PerkTutor](http://perktutor.github.io/), etc. I would recommend using that and maybe customize/extend it with some more Python scripting as needed.

**Comment by salimohamadi** [comment]
Thanks. the problem was fixed. The points that I did not take into consideration were applying the transforms in the way you said and also the US image reference, which, unlike the default in the MATLAB, is considered relative to MF orientation.
