### ISSUE TITLE
Buffer resize on the fly

### ISSUE THREAD

**Issue by dzenanz** [PlusToolkit/PlusLib#483]
In #93, at `2011-12-20 07:08` @lassoan wrote:
>Changing frame size during data collection is currently not supported in Plus.

Has anything changed since then?

**Comment by adamrankin** [comment]
No, and without a champion to drive it, it probably won't be done any time soon.

It would require considerable infrastructure redesign and reimplementation.

**Comment by dzenanz** [comment]
Thanks for the answer!

**Comment by lassoan** [comment]
It would not be very difficult to allow frame size change if it was acceptable to clear the buffer when switching frame size. Clearing the buffer would have the disadvantage that data synchronization/interpolation would not have the older items to work from. So, after a frame size switch you might need to wait a second or so (depending on how much delay is in the system) until data interpolation works well again.

**Comment by adamrankin** [comment]
Ah yes, if clearing the buffer is acceptable, then this wouldn't be as bad. What about recorded data, should we enable multiple frame sizes in a saved file (via image size attribute per frame), or file is closed on frame size change and a new one is opened (or other solution)?

**Comment by dzenanz** [comment]
So in-between changing buffer size, should I stop/start recording, or disconnect/connect?

**Comment by adamrankin** [comment]
Well, that depends. Each device is free to override those in case they do something in hardware. The only risk is that if you try to call those too quickly back-to-back, some device may still be processing the stop when you call the start.

For most devices, stop/start recording is just a Plus software concept. I think neither of those, and assume that a computer is fast enough to de-allocate/re-allocate/allocate memory within the time span of 1 frame.

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
