### ISSUE TITLE
Access to the PLTools repository from PerkLab

### ISSUE THREAD

**Issue by zoez526** [PlusToolkit/PlusLib#484]
Hello,

I am a student from UBC BiSICL and am working on integrating PLUS with NDI vega and Clarius(a portable ultrasound scanner device). I am wondering if it's possible for me to have access to the PLTools repository from PerkLab, so that I can access the NDI sdk?

Thanks, 
Zoe

**Comment by adamrankin** [comment]
The NDI access is publicly available at
https://github.com/PlusToolkit/ndicapi
