### ISSUE TITLE
Windows build failed with error "unable to connect to svn repo"

### ISSUE THREAD

**Issue by zoez526** [PlusToolkit/PlusLib#485]
Hello, 

I got the following error message when trying to build PlusBuild on windows visual studio 2017 and am not sure how to resolve this. Do you have any suggestions?

![capture](https://user-images.githubusercontent.com/35669350/51493969-eb6ce800-1d6b-11e9-82e9-731db253e067.PNG)

Thanks, 
Zoe

**Comment by Sunderlandkyl** [comment]
You need to checkout either the master branch for the latest version, or the Plus-2.6 for the current stable.

**Comment by Sunderlandkyl** [comment]
Done (https://github.com/PlusToolkit/PlusBuild/commit/f7837560e74d28e6a9b6ae022ce891968b769cd4). Thanks for pointing this out!
