### ISSUE TITLE
LINK error 1104: cannot find .lib file for new device

### ISSUE THREAD

**Issue by zoez526** [PlusToolkit/PlusLib#489]
Hello, 

I am trying to add a new ultrasound probe device called Clarius to PlusDataCollection. I got the LINK error below but was not sure how to resolve it. I'm wondering if you could provide some guidance on this?
![clariusliblinkerror0130](https://user-images.githubusercontent.com/35669350/52010776-31702d00-248b-11e9-92f6-925d44eaa534.PNG)

Here's the script I added in the PlusDataCollction/CMakeList.txt:
`IF(PLUS_USE_CLARIUS)
  FIND_PACKAGE(Threads REQUIRED)
  FIND_PACKAGE(CLARIUS REQUIRED)
  
  SET(CLARIUS_SRCS
      Clarius/vtkPlusClarius.cxx
      )

  IF(MSVC OR ${CMAKE_GENERATOR} MATCHES "Xcode")
    SET(CLARIUS_HDRS
        Clarius/vtkPlusClarius.h
        )
  ENDIF()

  LIST(APPEND ${PROJECT_NAME}_HDRS
      ${CLARIUS_HDRS}
      )

  LIST(APPEND ${PROJECT_NAME}_SRCS
      ${CLARIUS_SRCS}
      )
 
  LIST(APPEND ${PROJECT_NAME}_INCLUDE_DIRS
	  ${CMAKE_CURRENT_SOURCE_DIR}/Clarius
      )
  
  SET(External_Libraries_Install ${External_Libraries_Install} ${CLARIUS_LIB_DIR}/listen${CMAKE_STATIC_LIBRARY_SUFFIX})
  LIST(APPEND ${PROJECT_NAME}_LIBS
	  Clarius
      )
ENDIF()`

**Comment by adamrankin** [comment]
Is Clarius a CMake target? Defined either in a find module (FindClarius.cmake) or a CMakeified project (Clarius_DIR which contains ClariusConfig.cmake)?

**Comment by zoez526** [comment]
Hello Adam,

Thanks for the reply.

Clarius is not a Cmake target. I have added a find module(FindClarius.cmake) in PlusBuild/Modules. When I run Config in the CMake GUI, it indicates that Clarius is found: 
![image](https://user-images.githubusercontent.com/35669350/52012138-a5f89b00-248e-11e9-94fc-2e2e851d083b.png)

However, I think this linking error was produced because it was unable to open the static library file built from PlusDataCollection/vtkPlusClarius.cxx? 

Thanks,
Zoe

**Comment by zoez526** [comment]
Hello Adam, 

I think my wording earlier was not clear. I am just confused by the highlighted part here: 
![image](https://user-images.githubusercontent.com/35669350/52018408-26bf9300-249f-11e9-9c7b-0f81785c31e7.png)

I am assuming I only need to pass in the path to .lib files provided by Clarius SDK for <Your_Device_Library_Name>?

**Comment by adamrankin** [comment]
Ah, does your find module package things up into a CMake target via 
```CMake
...
ADD_LIBRARY(<targetName> <STATIC|SHARED> IMPORTED)
...
```
?

**Comment by adamrankin** [comment]
An example of one I made is here:
https://github.com/PlusToolkit/PlusBuild/blob/master/Modules/FindV4L2.cmake#L50

**Comment by zoez526** [comment]
Hi Adam,

Thanks for providing the examples. 

I'm getting this interesting error now.
![image](https://user-images.githubusercontent.com/35669350/52027256-90e83000-24bf-11e9-8226-e080d46f737b.png)
I'm not sure why it is trying to find lib.obj. The Clarius sdk provides .dll, .lib and .h files. 

Here's how my FindClarius.cmake file looks like:
![image](https://user-images.githubusercontent.com/35669350/52027321-d60c6200-24bf-11e9-9b02-6c1a6defe06c.png)

Also, here is the cmake script in PlusLib/srcs/PlusDatacollection/CMakeLists.txt
![image](https://user-images.githubusercontent.com/35669350/52027695-2cc66b80-24c1-11e9-84bf-81c5a295b650.png)

Thanks,
Zoe

**Comment by adamrankin** [comment]
Very close! The find module IMPORTED_LOCATION is the full file path to the .dll

https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED_LOCATION.html

I led you a bit astray by linking a linux example, on Windows you'll need to also define

https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED_IMPLIB.html

which is the full file path to the .lib file

**Comment by adamrankin** [comment]
Here is a Windows example:
https://github.com/PlusToolkit/PlusBuild/blob/master/Modules/FindAgilentMD1.cmake#L63

**Comment by zoez526** [comment]
Thank you so much for your support! The error has been resolved now!
