### ISSUE TITLE
Clarius tracked ultrasound probe

### ISSUE THREAD

**Issue by zoez526** [PlusToolkit/PlusLib#490]
Hello, 

I am working with this device called Clarius whose SDK provides grey scale ultrasound image and IMU(inertial measurement unit) data.  The IMU data can be converted to tracking data. Therefore, in this case, I will be obtaining imaging and tracking data from the same device. I am not sure if this is doable in PLUS because I haven't found a similar device in the existing repo. Specifically, there are two things that I am hoping to get more information on: 

1. If I set vtkPlusClarius.IsTracker() to return true, will this have any impact on obtaining the image from the ultrasound probe? Or it will only indicate that this device has tracking ability and not affect other functions?

2. Would this be a valid configuration file?
![image](https://user-images.githubusercontent.com/35669350/52095386-92752f00-2577-11e9-9edf-88939dab70b5.png)
(I'm having doubts with this configuration file because it has two DataSources and two outputChannels  with different types. )

Thanks,
Zoe

**Comment by adamrankin** [comment]
> Or it will only indicate that this device has tracking ability and not affect other functions?
This is correct.

The configuration file looks perfectly fine. What you're doing was considered when I did the redesign of the device input/output system.

**Comment by zoez526** [comment]
Thanks for letting me know!
