### ISSUE TITLE
Error linking to vtkImageViewer dll when testing

### ISSUE THREAD

**Issue by zoez526** [PlusToolkit/PlusLib#491]
Hello,

I am having trouble linking the vtkImageViewer dll file when testing image data collection from ultrasound device. It seems like it detected the vtkImageViewer header file but could not find the dll library. I am wondering if I'm missing something here?
[image](https://user-images.githubusercontent.com/35669350/52232328-16c5fb80-2871-11e9-93f8-89f1a750c219.png)

Thanks,
Zoe

**Comment by adamrankin** [comment]
Do you mean when you try to start your program Windows complains it can't find vtkImageViewer.dll?

**Comment by zoez526** [comment]
yes.  The error looks like this: 
LNK2019	unresolved external symbol "__declspec(dllimport) public: static class vtkImageViewer * __cdecl vtkImageViewer::New(void)" (__imp_?New@vtkImageViewer@@SAPEAV1@XZ) referenced in function "public: static class vtkSmartPointer<class vtkImageViewer> __cdecl vtkSmartPointer<class vtkImageViewer>::New(void)" (?New@?$vtkSmartPointer@VvtkImageViewer@@@@SA?AV1@XZ)	ClariusTest	C:\Users\zoez\PlusB-bin\PlusLib-bin\src\PlusDataCollection\Testing\vtkPlusClariusTest.obj

**Comment by adamrankin** [comment]
No, that's a linker error, when trying to compile and link your program. 

Have you added the appropriate VTK library to your list of libraries to link in CMake?

**Comment by zoez526** [comment]
Thanks for the help! The error was resolved by adding "vtkInteractionImage" library in CMake.
