### ISSUE TITLE
Unable to display video stream in vtkImageViewer

### ISSUE THREAD

**Issue by zoez526** [PlusToolkit/PlusLib#492]
Hello, 

I have created a test for the device Clarius by copying the existing test [vtkTelemedVideoSourceTest.cxx](https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusDataCollection/Testing/vtkTelemedVideoSourceTest.cxx). I set it to stream B mode ultrasound videos. There were no errors being thrown, however no images were streamed in the pop up window (The window at the top right corner of the image below).

![image](https://user-images.githubusercontent.com/35669350/52318994-29792700-297c-11e9-8fa6-67cc29f7366c.png)

I tried setting a breakpoint in vtkExtractImageRow::ReqeustData (line 84 [here](https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusDataCollection/Testing/vtkTelemedVideoSourceTest.cxx)), and the function was never excuted. 

I am wondering if I'm missing something here? 

Thanks,
Zoe

**Comment by adamrankin** [comment]
That seems like an overly complicated test. Just run a PlusServer with your device and connect Slicer to it. If that doesn't produce an image, you can diagnose it in your device class only.

**Comment by zoez526** [comment]
Thanks for letting me know!

For future reference: the images were streamed to Slicer, but in vtkImageViewer the image would freeze after 1 frame.
