### ISSUE TITLE
Logger is no longer a singleton

### ISSUE THREAD

**Issue by dzenanz** [PlusToolkit/PlusLib#493]
Since the move to `IGSIO` for some functionality, `vtkPlusLogger` inherits from `vtkIGSIOLogger` but [creates a separate instance](https://github.com/PlusToolkit/PlusLib/blob/9404c991e7d80badb4db1df3c06f662af8761c90/src/PlusCommon/vtkPlusLogger.cxx#L38). So my application which used to set log level to 5 now does not get all the messages, because Plus internals now use `vtkIGSIOLogger` which is a separate instance from `vtkPlusLogger`.

Expected behavior: there is a single logger instance, and `vtkPlusLogger` is an empty descendant, or even better just a rename `using vtkPlusLogger = vtkIGSIOLogger;`

**Comment by dzenanz** [comment]
It looks like I have mistaken about two instances - there seems to be a single instance. However, SetLogLevel(5) is not respected. The errors from [vtkPlusTimestampedCircularBuffer](https://github.com/PlusToolkit/PlusLib/blob/f4e6e889ec6c04d0bd3bce5d4c49f5dc3446897e/src/PlusDataCollection/vtkPlusTimestampedCircularBuffer.cxx#L78) and [vtkPlusBuffer](https://github.com/PlusToolkit/PlusLib/blob/f4e6e889ec6c04d0bd3bce5d4c49f5dc3446897e/src/PlusDataCollection/vtkPlusBuffer.cxx#L415) are not logged.

**Comment by dzenanz** [comment]
Setting the logging level has no effect if done before this statement:
```C++
vtkPlusConfig::GetInstance()->SetDeviceSetConfigurationData(configRootElement);
```
Either `vtkIGSIOLogger::Instance()->SetLogLevel(5);` or `vtkPlusLogger::Instance()->SetLogLevel(5);` work after that statement.

Is this expected? Is this documented somewhere?

**Comment by Sunderlandkyl** [comment]
I don't think that this is expected behavior, seems like a bug.
I'll take a look at it.

**Comment by dzenanz** [comment]
That fixed it. Thanks!
