### ISSUE TITLE
Understanding the matrix transformations in config files

### ISSUE THREAD

**Issue by zoez526** [PlusToolkit/PlusLib#496]
Hello, 

I took the screenshot below from one of the configuration files for Telemed. I'm wondering what is the purpose of the matrix transform (inside the CoordinateDefinition element) and what does the values specify?

Thanks
Zoe
<img width="734" alt="screen shot 2019-02-14 at 9 42 31 pm" src="https://user-images.githubusercontent.com/35669350/52836980-c1c08b80-30a1-11e9-8263-5d4fa5f75fdb.png">

**Comment by adamrankin** [comment]
What is the purpose of that specific transform, or any transform in general? 

The 4x4 matrix represents a linear transformation ([khanacademy.org](https://www.khanacademy.org/math/precalculus/precalc-matrices/matrices-as-transformations/a/matrices-as-transformations))

**Comment by zoez526** [comment]
I understood that this is a linear transformation. However in this context, since it is streaming images received from telemed to slicer via openIGTLink, and there are no tracking devices, why is a transformation required?

**Comment by adamrankin** [comment]
I couldn't answer that, you'd have to contact the original author of the config file. A scaling to 20% does seem arbitrary.

**Comment by ungi** [comment]
You may delete the whole CoordinateDefinitions section. It is most likely not needed in your case. The 0.2 scaling was only to be able to use the ruler tool in Slicer to measure distances. In that specific setup 1 pixel was 0.2 mm. And Slicer only measures in mm, while the Image coordinate system is in pixels.

**Comment by Sunderlandkyl** [comment]
If you delete the CoordinateDefinitions section, you'll need to change the EmbeddedTransformToFrame to "Image".

**Comment by zoez526** [comment]
Thanks for the help! Also found documentation [here ](http://perk-software.cs.queensu.ca/plus/doc/nightly/dev/CoordinateSystemDefinitions.html)which was very useful!
