### ISSUE TITLE
Error MicronTracker  with PlusApp-2.6.0.20180310-Telemed-Win32

### ISSUE THREAD

**Issue by ChiaraTe** [PlusToolkit/PlusLib#497]
Hi,
I would like to use MicronTracker camera with PlusApp-2.6.0.20180310-Telemed-Win32 but I have this error

![errore_plus6](https://user-images.githubusercontent.com/38109724/52943994-b3f35a80-336e-11e9-889a-f92eb959fefd.PNG)

Can someone help me?
Thanks

**Comment by ungi** [comment]
I haven't used MicronTracker in many years. But I remember I had to update the camera calibration file. There may be one that comes with PLUS (same folder where the config files are), but it may not be good for your camera, so you need replace it with the one that is in your MicronTracker installation folder.

**Comment by ChiaraTe** [comment]
HI, I have just tried this solution but doesn't work. Do you have another suggestions? 
Thank you so much

**Comment by lassoan** [comment]
Does MicronTracker's CPP demo work on your computer? What MicronTracker SDK are you using?

**Comment by ChiaraTe** [comment]
Hi, yes MicronTracker's CPP demo works. 
This is my version:
![sdkmicrontracker](https://user-images.githubusercontent.com/38109724/53086292-1a11e600-3505-11e9-935c-0efb6593393d.PNG)

**Comment by ChiaraTe** [comment]
Hi,
Do you have any ideas?

**Comment by lassoan** [comment]
What is the MicronTracker SDK version in your Plus package? It is logged when you start PlusServer (or you can run PlusVersion from the Plus command prompt).

If there is a mismatch then you may need to rebuild Plus with the same MTC version as your system is configured with.

**Comment by ChiaraTe** [comment]
I downloaded 
PlusApp-2.6.0.20190221-MTC-3.7-Win32.exe  but  this is the output of Plusversion from prompt : 
![image](https://user-images.githubusercontent.com/38109724/54348339-204d3b00-4649-11e9-9224-2c20653c5488.png)
  In your versions  of Plus-MTC 3.7  there is MTC 3.6 .

**Comment by ChiaraTe** [comment]
Moreover in plus 2.4 there is MCT 3.7 , in the  higher versions of Plus there is MCT 3.6

**Comment by lassoan** [comment]
@ChiaraTe MicronTracker SDK version must match exactly, but at least the major.minor version must be the same. Could you try to build Plus with the MicronTracker SDK version that you use?

@Sunderlandkyl Could you check the package build scripts and make sure the MicronTracker SDK version in the package name matches the actually used version?

**Comment by Sunderlandkyl** [comment]
It looks like the capitalization of the CMake option for the Microntracker preferred version was changed at some point between Plus-2.4 and Plus-2.6 either in PlusBuild, or in the build script. The correct variable is not set, so the package defaults to 3.7.

Updating the build script now.

**Comment by Sunderlandkyl** [comment]
The MicronTracker version in all compatible nightly and stable packages is now 3.7.6.8.

**Comment by ChiaraTe** [comment]
thank you!
