### ISSUE TITLE
Error when compiling on Mac with latest commits

### ISSUE THREAD

**Issue by UCLGuichard** [PlusToolkit/PlusLib#498]
Hi @Sunderlandkyl 
I pulled your latest commits to `master` but the build on Mac Mojave fails:
```
PlusDataCollection/vtkPlusBuffer.cxx:285:33: error: non-constant-expression cannot be narrowed
      from type 'int' to 'std::__1::array<unsigned int, 3>::value_type' (aka 'unsigned int') in initializer list [-Wc++11-narrowing]
    FrameSizeType frameSize = { dimensions[0],dimensions[1], dimensions[2]};
                                ^~~~~~~~~~~~~
```
Any suggestion will be appreciated.
Kind regards

**Comment by adamrankin** [comment]
I can investigate on Monday, I have a Mac build machine to debug.

**Comment by adamrankin** [comment]
And by Monday I mean Tuesday (sorry, today is a holiday)

**Comment by UCLGuichard** [comment]
OK cool, that's be great. Thanks @adamrankin

**Comment by Sunderlandkyl** [comment]
Should be fixed by https://github.com/PlusToolkit/PlusLib/commit/a36394019dbe3c94e2eb6c541261e895d41f1462.

**Comment by UCLGuichard** [comment]
Hi @Sunderlandkyl 
Thank you, I will try it out and let you know.

**Comment by UCLGuichard** [comment]
Hi,
It works. Thank you. Closing the issue.
