### ISSUE TITLE
connect to device successfully,but warning 'no data is broadcasted , as no data is available yet'.

### ISSUE THREAD

**Issue by barony14** [PlusToolkit/PlusLib#500]
We use a ultrasound device--sonoscape (a chinese company), and HDMI-to-USB video capture device. 
I uploaded our config:
[PlusDeviceSet_Server_US video - 副本.txt](https://github.com/PlusToolkit/PlusLib/files/2897512/PlusDeviceSet_Server_US.video.-.txt)
Does plus not support this ultrasound device and probe?

**Comment by lassoan** [comment]
These low-cost framegrabbers can be typically used via Microsoft Media Foundation video device in Plus.
