### ISSUE TITLE
Updating Motive to version 2.1.1

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#501]
I've tried the latest version of Motive, and it seems to have solved the NPTrackingTools concurrency issue.
Unfortunately, as we've discussed before, the Motive 2.1.X+ api is 64-bit only, limiting the number of packages that we can include it in, and what devices we can pair it with (ie Telemed).

One possibility was to also update the Telemed SDK to the latest version, but it looks like that the new SDK still requires that developed applications are 32-bit (http://www.pcultrasound.com/download/download_sdk/).

Thoughts?

@lassoan @ungi @markasselin

**Comment by ungi** [comment]
It seems to me that we should package Telemed with Motive 1, and package the latest Motive in the 64-bit release. Running two PLUS servers can be the backup plan for those who need Motive 2 and Telemed. I'm sure Telemed will have to come out with 64-bit support soon.

**Comment by markasselin** [comment]
@ungi’s solution is the best I’ve been able to come up with as well. Optitrack Motive 2 only supports 64 bit and Telemed only 32 bit, so we must use Motive 1 with Telemed and the Win32 package. The only question is whether to use Motive 1 or 2 with the 64 bit windows package. I think Motive 2 is best, to give PLUS users that option if they want it. Especially now that the concurrency issue is fixed.

**Comment by Sunderlandkyl** [comment]
Yes, I think that supporting both versions is probably the only solution that we have currently.

So, in summary, I am going to:
- [ ] Update motive 2.x to 2.1.1.
- [ ] Restore old motive 1.0 classes
- [ ] Add CMake option to switch between devices (default to 2.0 on x64, default to 1.0 on x86).

**Comment by Sunderlandkyl** [comment]
Support for both API has been added.
64-bit defaults to 2.1.1.
32-bit defaults to 1.10.3.
