### ISSUE TITLE
Image to Probe trasnform

### ISSUE THREAD

**Issue by magednasan** [PlusToolkit/PlusLib#502]
Hello,
I am trying to calibrate 3D Ultrasound transducer with an optical marker using fcal, Polaris and 4DEC9 ultrasound transducer.
The resulted transformation I've got is similar to:
 `<Transform From="Image" To="Probe"
      Matrix="
        0.0119607	-0.00129998	0.257837	-30.0536
        0.00872487	0.257815	0.00115911	263.76
        -0.257975	0.00303061	0.0119935	96.0326
        0	0	0	1"
       Error="0.503238" Date="012119_173631" />`
I've noticed that the rotation matrix is not orthogonal: Det(R) = 0.017193, which leads to my question:
I want to know if this matrix represents only (Rotation and Translation) or it includes scaling information as well. And do I need further information rather than the (Image_to_probe) matrix to find the translation and the rotation?
My objective is to find the geometrical rigid transformation from the origin of the central US frame (Since I am using 3D transducer) and the origin of the marker attached to the transducer. The calibration process is performed using N-wires phantom 3.1.
Thanks in advance,

**Comment by lassoan** [comment]
ImageToProbe contains scaling (pixel size).

Non-orthogonal matrix indicates inaccuracies in the calibration process - see http://perk-software.cs.queensu.ca/plus/doc/nightly/user/ApplicationfCal.html for tips and tricks.

You can also enforce orthogonal matrix and isotropic spacing by adding `OptimizationMethod="2D" IsotropicPixelSpacing="TRUE"` attributes to `vtkPlusProbeCalibrationAlgo` element in the configuration file. (see https://github.com/PlusToolkit/PlusLib/blob/master/src/Documentation/UserManual/AlgorithmProbeCalibration.dox)
