### ISSUE TITLE
Unable to retrieve transform messages from OpenIGTLink Tracker

### ISSUE THREAD

**Issue by Tiffas** [PlusToolkit/PlusLib#504]
Hi, 
I am trying to retrieve transform matrices from a KUKA robot. I use the following xml config file:

<PlusConfiguration version="2.1">

	<DataCollection StartupDelaySec="1.0" >
	
		<DeviceSet 
			Name="Plus server: KUKA"
			Description="Broadcasting positions sent by the KUKA robot through OpenIGTLink."/>
			
		<Device
			Id="FlangeToKUKABase"
			Type="OpenIGTLinkTracker"
			MessageType="TRANSFORM"
			ServerAddress="172.31.1.147"
			ServerPort="30000"
			IgtlMessageCrcCheckEnabled="FALSE"
			UseReceivedTimestamps="FALSE"
			SendTimeoutSec="30"
			ToolReferenceFrame="KUKABase">
			<DataSources>
				<DataSource Id="Flange" Type="Tool"/>
			</DataSources>
			<OutputChannels>
				<OutputChannel Id="TrackerStream">
					<DataSource Id="Flange"/>
				</OutputChannel>
			</OutputChannels>
		</Device>
		
	</DataCollection>

	<PlusOpenIGTLinkServer
		MaxNumberOfIgtlMessagesToSend="1"
		MaxTimeSpentWithProcessingMs="50"
		ListeningPort="18944"
		OutputChannelId="TrackerStream"
		IgtlMessageCrcCheckEnabled="FALSE"
		SendValidTransformsOnly="FALSE"
		>
		<DefaultClientInfo>
			<MessageTypes>
				<Message Type="TRANSFORM" />
			</MessageTypes>
				<TransformNames> 
					<Transform Name="FlangeToKUKABase" />
				</TransformNames>
			</DefaultClientInfo>
	</PlusOpenIGTLinkServer>
	
</PlusConfiguration>

When I connect with an OpenIGTLink client in Slicer to retrieve the transform matrices I have the following error:

|DEBUG|063.850463|SERVER>  FlangeToKUKABase-FlangeToKUKABase: vtkPlusBuffer: Cannot do data interpolation. The closest item to the requested time (time: 31.832861, uid: 621) is invalid.| in /home/daunizeau/Devel/Slicer/Modules/PlusBuild-Release/PlusLib/src/PlusDataCollection/vtkPlusBuffer.cxx(1195)
|DEBUG|063.850590|SERVER>  Skipped transformation matrix - Invalid transform in the transform repository (Flange to KUKABase)| in /home/daunizeau/Devel/Slicer/Modules/PlusBuild-Release/PlusLib/src/PlusOpenIGTLink/vtkPlusIgtlMessageCommon.cxx(78)

Is there a way to deactivate matrix interpolation ? 

Thanks

**Comment by Sunderlandkyl** [comment]
I don't believe that there is a way to deactivate the interpolation.

The reason that it is failing is because the incoming transform does not have a "TransformStatus" metadata element.

For now, the interpolation should work fine if you add "TransformStatus" to the metadata with the value "OK".

@lassoan This is the issue that I mentioned when debugging with the ultrasound simulator.
I believe the solution that we discussed was to optionally treat TOOL_UNKNOWN status as TOOL_OK?
I'll see about adding that functionality now.

**Comment by adamrankin** [comment]
TOOL_UNKNOWN should be verbosely notified to the user, as it means that someone somewhere isn't populating the field correctly.

**Comment by adamrankin** [comment]
Does the incoming transform use any v1 style status? Also, KUKA! @Tiffas Any possibility of you posting a picture of your setup? I'd use it to show my lab the possibility of surgical robots with Plus/Slicer.

**Comment by Tiffas** [comment]
The KUKA robot only sends basic Transform messages with the 58 bytes header. It used to work on Plus2.4. Unfortunately I had to reinstall all my setup on a new computer and I did not manage to build the 2.4 version on this new computer. I am currently on version 2.7.0. @adamrankin let me just ask my boss, but anyway I will write a paper soon on my work with Plus/Slicer, KUKA and a Verasoncis scanner, if I manage to retrieve the KUKA position ;)

**Comment by adamrankin** [comment]
We will make the KUKA robot work, definitely. I can manage some time this afternoon (EST) to work on it.

**Comment by Tiffas** [comment]
So I did some nasty hacks so that TOOL_UNKNOWN is considered a TOOL_OK. It works fine. I opened an issue #459 some month ago and I think it is somehow related. 
If my understanding is correct, metadata appeared on OpenIGTLink v3, and this "TransformStatus" element is now kind of mandatory, which make use of OpenIGTLink v1 and v2 deprecated. I think this not a good thing, v1 and v2 are correctly documented and easy to understand, it allow people new to Plus/Slicer to easily start using Plus with custom devices (which was my case). I think it would be great and useful for newcomers if Plus kept a full support of v1 and v2. @adamrankin I sent you an email with a picture of my setup.

**Comment by adamrankin** [comment]
I agree, v1 and v2 were not meant to be deprecated. I have a fix in my WC,
but I had to build overnight to run the tests. Will merge today.

**Comment by adamrankin** [comment]
Hi @Tiffas, could you confirm that this fix works?

**Comment by Tiffas** [comment]
Hi, it works ! Thanks !
