### ISSUE TITLE
Plus Server Stopped when starting scout scan in 3D Slicer Plus Remote Module

### ISSUE THREAD

**Issue by zhanhel** [PlusToolkit/PlusLib#507]
We are using Ultrasound (frame grabber) and Polaris to try to do 3D reconstruction in Slicer via Plus Server.

So far we have been able to show tracked image in Red Slice and 3D plane but we can't make the scout scan work to do the volume reconstruction. Each time we click on the scout scan, either the connection between Plus server and the devices breaks or the Reply log in Plus Remote module shows:

<CommandReply Name="StartRecording" Status="FAIL" Error="VirtualCapture (CaptureDevice) StartRecording Recording to file is already in progress." Message="Command failed. See error message."></CommandReply>

We have been following the SlicerIGT-U34 LiveVolumeReconstruction Tutorial but can't proceed past Scout Scan. 

Another issue that we are having is that the ultrasound image in the Red Slicer looks very compressed and out of normal ratio. We would appreciate any help that you may offer.

We have attached the config file here as well in case you need to check on that.

Thanks a lot! 
Kevin

[ConfigFile.txt](https://github.com/PlusToolkit/PlusLib/files/2947629/ConfigFile.txt)

**Comment by Sunderlandkyl** [comment]
I believe that this was an issue that was fixed in 2.7.
Can you try the latest nightly 2.7 release?

**Comment by zhanhel** [comment]
Hey Kyle,

Thanks for the help. After we updated our PlusServer to 2.7 and Slicer to 4.10.1, the disconnection issue was resolved and we were able to see some rough 3D images after Scout Scan. However one issue remains, which is that our ultrasound image is still not at the right size. It looks like the image was strongly compressed. FYI we are using a linear probe instead of a curved one. We have attached the screenshot of how the image looks like in the Slicer view. We appreciate your help!

![image](https://user-images.githubusercontent.com/48366749/54299662-bcb40680-4591-11e9-8d3d-dd994c541aa6.png)

**Comment by Sunderlandkyl** [comment]
Check your Image to Probe transform. It seems to be causing the compression.

**Comment by zhanhel** [comment]
Thanks Kyle! I think that was the issue! One more question, once we got the 3D structure we were trying to increase the quality of the image by changing the "shift" value in Volume Rendering module. However, it did not work as we saw in the tutorial. Do you have any suggestions on how to change threshold of volume reconstruction or how to improve the quality of the reconstruction in SlicerIGT module?  Again, thanks for helping us solving those problems!

**Comment by ungi** [comment]
The example bone in the video was intentionally scanned in clear gel that does not produce high intensity pixels on ultrasound images. So we can verify correct volume by just shifting the pixel intensity threshold. In real life applications simple thresholding will not separate object as nicely as in the video. Typically you need to implement a more sophisticated segmentation filter on the images before object appear as clearly as in the video.
