### ISSUE TITLE
Polhemus Patriot tracking device support

### ISSUE THREAD

**Issue by caioath** [PlusToolkit/PlusLib#512]
Hi everyone
I could not find support for Polhemus Patriot tracking device on Plus. Has it been done before? I'm asking in order to avoid redoing something already done.
Not an IT expert but I can take a shot building if it's not been done yet.

Thanks

**Comment by Sunderlandkyl** [comment]
I don't think that an interface for Polhemus devices has been implemented.

If you would like to try to implement one, you can find instructions here: https://plustoolkit.github.io/devicecode

It would be great if you could contribute device support to Plus!

**Comment by adamrankin** [comment]
If you have any questions following the guide, let me know!

**Comment by caioath** [comment]
I'll start now and I'll post updates later.

Thank you for the support!
