### ISSUE TITLE
Record and replay color sequence file

### ISSUE THREAD

**Issue by MaXZon3** [PlusToolkit/PlusLib#516]
Hi :wave: 

We are attempting to record an `RGB_COLOR` stream with `fCal`. This creates an `.mha` sequence file.

Then, we loaded this sequence in 3DSlicer using the `Sequence` plugin.

When playing this sequence, the result is not as expected. It only looks like one slice of the video is visible.

![Capture du 2019-03-26 15-37-04](https://user-images.githubusercontent.com/15032112/55005868-0e6e7f00-4fdd-11e9-9834-d94f70daf565.png)

It only happens when `ImageType` is set to `RGB_COLOR`. When recording a sequence with `BRIGHTNESS` value, it works as expected.

Loading a `BRIGHTNESS` sequence in ParaView results in a 3D volume that could be visualized with volume rendering with the frames stacks in the `z` direction.

![Capture du 2019-03-26 15-44-35](https://user-images.githubusercontent.com/15032112/55006461-17138500-4fde-11e9-845d-1cd66e8b64de.png)

Loading a `RGB_COLOR` sequence in ParaView results in a `3*width*height` volume with multiple frames inside.

![Capture du 2019-03-26 15-43-46](https://user-images.githubusercontent.com/15032112/55006472-1c70cf80-4fde-11e9-945c-9e074c2a65d2.png)

Here is the configuration of our device:
```xml
    <Device
      Id="VideoDevice" 
      Type="MmfVideo" 
      FrameSize="640 480"
      VideoFormat="YUY2"
      CaptureDeviceId="0" >
      <DataSources>
        <DataSource Type="Video" Id="Video" PortUsImageOrientation="MF" ImageType="RGB_COLOR"  />
      </DataSources>      
      <OutputChannels>
        <OutputChannel Id="VideoStream" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>
```

Do you have any idea of what could be the issue in this case? :thinking: 

Thank you very much. :smiley:

**Comment by Sunderlandkyl** [comment]
The sequence reader from VTK/ITK does not support color image sequences.

If you would like to load color sequences in Slicer, you can download the SlicerIGSIO extension.
It provides access to the same sequence reading/writing methods that are used in Plus.

**Comment by MaXZon3** [comment]
Ok, I tried to use SlicerIGSIO but it only added a IO section with a VideoIO subsection.

![Capture du 2019-03-28 14-49-39](https://user-images.githubusercontent.com/15032112/55164070-4c99a900-516b-11e9-8e8d-34fee9490bba.png)


When loading the same colored mha, the behavior is still the same.

Do I use it the wrong way? Did I missed something? :thinking:

**Comment by Sunderlandkyl** [comment]
No, you used it correctly.
There is an issue with the current nightly build of SlicerIGSIO on Linux/Mac, so the current version is out-of-date.

I'll let you know once I've resolved it.

**Comment by Sunderlandkyl** [comment]
The current version of SlicerIGSIO should now be availiable on Linux (there are still some MacOS packaging issues).

To use the SlicerIGSIO importer, make sure your recorded sequence uses the compound extension *.igs.mha. The description should show up in the import dialog as "IGSIO Sequence".

**Comment by MaXZon3** [comment]
Thank you! It works well! :+1:
