### ISSUE TITLE
IGT Optitrack configuration file

### ISSUE THREAD

**Issue by GL1984** [PlusToolkit/PlusLib#517]
I am taking my first steps in IGT configuration files. I am using Windows 10 OS, PlusApp-2.7.0.20190322-Win64, Motive 2.0.2 (Optitrack trio) and 3D Slicer 4.11. I do not have any programming/scripting background so I apologise if my questions are trivial to some of you.

My problem is the Plus Server won't connect to Motive. I have tried to modify the configuration files in different ways but I am not sure I am doing this correctly. My goal is to eventually run a neuronavigation system similar to what is presented on the IGT training module. But for now I just wanted to start with a simple stylus tracking configuration file. 

I have used the file provided in the config folder with a couple of changes (attached).
I have tried many variations but I keep getting a "connection failed!" error message. I wonder if it has to do with the fact Motive no longer use "Project" (.PTT) files (which are listed in the tutorial on IGT website)? Instead I have created an Optitrack "Profile" which is an .xml file, but maybe this is not appropriate?

Also, do I need to have all the necessary files in the same folder? Does the folder need to be at a specific location in the C: drive? 

Would anyone be willing to share an example of a recent configuration file they are using for Optitrack hardware?

Any help would be much appreciated.

Many thanks,
Guillaume

[PlusDeviceSet_Server_OptiTrack_AddMarkersUsingTRA.txt](https://github.com/PlusToolkit/PlusLib/files/3009361/PlusDeviceSet_Server_OptiTrack_AddMarkersUsingTRA.txt)

**Comment by ungi** [comment]
I haven't tried that exact PLUS build, but the download website says it is for Motive 2.1.1. Can you try upgrading your Motive?

Note that I personally use Motive 1.10.3 with OptiTrack Trio. It is quite hard to restore all the settings in Motive 2, so you may save yourself a lot of headache by downgrading to Motive 1. (You need a different PLUS build for Motive 1)

Please let me know how it goes.

 

Tamas

**Comment by Sunderlandkyl** [comment]
If you are trying to connect to a running version of Motive, can you confirm that data streaming is turned on? (In can be found in View->Data Streaming Pane->Broadcast Frame in Motive 2.1.1).

**Comment by GL1984** [comment]
Thank you for both your comments.
I have upgraded to Motive version 2.1.1 and the Broadcast Frame was indeed off. This solved the connection issue. I will work on the next steps of the configuration, hopefully it will go smoothly from here.
Thanks again.

**Comment by GL1984** [comment]
Hello again, I am afraid I did not make it much further before getting stuck again. Now Slicer is connecting to Plus server but I have not been able to generate any transforms from that connection (see screen copy).
![Slicer Screen copy](https://user-images.githubusercontent.com/44057909/55687690-d0237900-5967-11e9-8676-bc2ced86c5dc.png)

**I still am unsure of the compatibility of the ".motive" file type with IGT. Anyone knows?**
In my config file I have the following IDs: 
<Device
      Id="TrackerDevice"
      Type="OptiTrack"
      ToolReferenceFrame="Tracker" 
      Profile="Slicer tracking test1 (GL).motive"
      AttachToRunningMotive="TRUE"
      MotiveDataDescriptionsUpdateTimeSec="1.0" >
      <DataSources>
        <DataSource Type="Tool" Id="Stylus" RigidBodyFile="Stylus.motive" />
        <DataSource Type="Tool" Id="Reference" RigidBodyFile="Reference.motive" />

**Is that acceptable? I know the online examples use ".TPP" and ".TRA" files...**

**Unless the problem is coming from the output configuration?**
Here is what I have:
 <PlusOpenIGTLinkServer
    MaxNumberOfIgtlMessagesToSend="1"
    MaxTimeSpentWithProcessingMs="50"
    ListeningPort="18944"
    SendValidTransformsOnly="TRUE"
    OutputChannelId="TrackerStream" >
    <DefaultClientInfo>
      <MessageTypes>
        <Message Type="TRANSFORM" />
      </MessageTypes>
      <TransformNames>
	<Transform Name="StylusToReference" />
        <Transform Name="StylusToTracker" />
        <Transform Name="ReferenceToTracker" />
      </TransformNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>

Many thanks,
Guillaume

**Comment by GL1984** [comment]
Sorry, the config is not showing. here is the config file copied in word.
[PlusConfiguration GL.docx](https://github.com/PlusToolkit/PlusLib/files/3051912/PlusConfiguration.GL.docx)

**Comment by ungi** [comment]
In Slicer, you specified network port number 18904, while in PLUS you specified 18944. The ports don't connect unless they are the same.
