### ISSUE TITLE
What is ImageToProbe transformation exaclty?

### ISSUE THREAD

**Issue by MaXZon3** [PlusToolkit/PlusLib#520]
Hello :wave: ,

After [your good advices](https://github.com/PlusToolkit/PlusLib/issues/470), we succeed to perform a full calibration process using `fCal`! :tada: 

Now, we have a question regarding what exactly represents the final `ImageToProbe` matrix.

As written in [the documentation](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/UltrasoundImageOrientation.html), this `ImageToProbe` transform represents the transformation from the top left corner of the full image to a sensor (in our case, we use a `trakSTAR` device) attached to a US probe. Like in the following image:

![ImageToProbe01](https://user-images.githubusercontent.com/15032112/55161758-8fa54d80-5166-11e9-90fa-6cd1bab22e58.png)

Am i right?

When testing the resulting matrix, it looks like it could be the transformation between the top left corner of the "segmentation parameters" cropping box, as in the following image:

![ImageToProbe02](https://user-images.githubusercontent.com/15032112/55161874-cd09db00-5166-11e9-935e-91f859426e46.png)

Is it possible?

We calibrate with a trans-abdominal probe, and configured the `DataSource` with `PortUsImageOrientation="MF"`.

If it can help, our result matrix is:
```xml
<Transform From="Image" To="Probe"
   Matrix="
   -0.16392    0.10356   0.05294   77.806
   -0.09958   -0.16392   0.03177   33.5057
    0.06223   -0.00054   0.1903    -52.6064
   0   0  0   1"
   Error="0.279" Date="032819_160600" />
```

Thank you in advance for this clarification. :smiley:

**Comment by MaXZon3** [comment]
Hi :wave: :smiley: 
Any update on this question ? :wink:

**Comment by adamrankin** [comment]
Hi, it is from the top left of the image to the sensor.

**Comment by MaXZon3** [comment]
Ok, thank you! :smiley:

**Comment by zhaobingshuai** [comment]
@MaXZon3 hello, How is the transformation matrix of ImageToProbe obtained?

**Comment by ungi** [comment]
U-31 tutorial on this page: http://www.slicerigt.org/wp/user-tutorial/
