### ISSUE TITLE
Brachy stepper calibration

### ISSUE THREAD

**Issue by felixnavarro** [PlusToolkit/PlusLib#521]
Dear all,

We are trying to use PLUS  + 3DSlicer for TRUS guided prostate biposies.  We are using an UVC framegrabber since the US device may change.

I have written the following XML configuration file : [capturadoraYstepper.txt](https://github.com/PlusToolkit/PlusLib/files/3038479/capturadoraYstepper.txt)

I cannot find any example in the documentation using TRUS + brachy stepper, which I suppose that it is quite common. I cannot find the calibration procedure in the documentation either (I have seen somewhere that there is an application called iCal, but I cannot find neither the application nor its documentation).

Is it possible to have a working xml file for TRUS + BrachyStepper? Is there a link to download iCal and its documentation?

Thank you in advance

**Comment by adamrankin** [comment]
Hi, iCal is no longer supported. Perhaps @lassoan or @ungi can comment on its availability.

**Comment by felixnavarro** [comment]
Hi adamrakin, 
I have a grid that can be used to perform the calibration, but it would be really helpful to see an example of a working XML file for US + stepper hardware. Do any of you have used this file?

Thanks in advance.

**Comment by lassoan** [comment]
iCal has not been publicly released as there have been some calibration algorithms that we could not release before patenting (https://patents.google.com/patent/US20140121501A1/en). We could now release the application but it would need significant work to make it work with current version of Plus. Do you have resources (in-house developers or funding) to support this work? If not then probably you can compute the parameters manually (that are read from configuration file here: https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusDataCollection/BrachyTracking/vtkPlusBrachyTracker.cxx#L314-L405).

**Comment by felixnavarro** [comment]
Sorry, we have not any funds so we will try to do it manually. 

Thank you very much for your answer!

**Comment by felixnavarro** [comment]
Dear all, 

After several days of tests I am not able to write a working XML configuration file for a VFW frame grabber and a civco brachy stepper. 

I wonder if you could provide any xml file including a CIVCO brachy stepper, I don't feel capable to develop it using the online documentation.

I attach you the best XML file that I could do and the log file of its execution. Does any of you have a clue about what I'm doing wrong?

[LogForV3.txt](https://github.com/PlusToolkit/PlusLib/files/3131292/LogForV3.txt)

[configV3.txt](https://github.com/PlusToolkit/PlusLib/files/3131298/configV3.txt)

**Comment by adamrankin** [comment]
Duplicate #543
