### ISSUE TITLE
Uknown device type: VirtualTextRecognizer 

### ISSUE THREAD

**Issue by roozbehshams** [PlusToolkit/PlusLib#526]
Hi,

I'm trying to use the VirtualTextRecognizer device, but the server fails to start with this error in the log file:
`
Unknown device type: VirtualTextRecognizer. Supported devices: 3dConnexion, AuroraTracker, BkProFocusOem, ChRobotics, Epiphan, FakeTracker, GenericSerialDevice, ICCapturing, ImageProcessor, IntelRealSense, Microchip, MmfVideo, NDITracker, NoiseVideo, OpenCVVideo, OpenIGTLinkTracker, OpenIGTLinkVideo, OptiTrack, OpticalMarkerTracker, PhidgetSpatial, PolarisTracker, SavedDataSource, UsSimulator, VFWVideo, VirtualBufferedCapture, VirtualCapture, VirtualDiscCapture, VirtualMixer, VirtualSwitcher, VirtualVolumeReconstructor| in E:\D\PTNP64b\PlusLib\src\PlusDataCollection\vtkPlusDeviceFactory.cxx(451)`

I'm using PlusDeviceSet_Server_VirtualTextRecognizer.xml as config with PlusApp-2.7.0.20190412-Win64. Is there something I need to be doing before I can use that device?

Roozbeh

**Comment by Sunderlandkyl** [comment]
I'm going to try to enable the text recognizer in the nightly packages. If the size is not too big, then it will be available in the next built tomorrow morning.

**Comment by roozbehshams** [comment]
I see, that makes sense. Thanks!

**Comment by Sunderlandkyl** [comment]
The text recognizer wasn't too large, so I've enabled it in most builds (Except Ultrasonix and StealthLink).

**Comment by roozbehshams** [comment]
Hi again, thanks for including it in the nightly. I tested a bit and ran into a problem:

> |INFO|245.116000|SERVER> Error opening data file E:/D/PTNP64b/Deps/tessdata/eng.traineddata
|INFO|245.117000|SERVER> Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
|INFO|245.117000|SERVER> Failed loading language 'eng'
|INFO|245.117000|SERVER> Tesseract couldn't load any languages!
|ERROR|245.118000|SERVER> Unable to init tesseract library. Cannot perform text recognition.| in E:\D\PTNP64b\PlusLib\src\PlusDataCollection\VirtualDevices\vtkPlusVirtualTextRecognizer.cxx(241)

It seems like the tessdata is missing. Is it possible that it was left out during packaging?

I'll try to set up my build environment for PLUSLIb so I could also contribute when I can.

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
