### ISSUE TITLE
Adding a Device Page

### ISSUE THREAD

**Issue by fergujm2** [PlusToolkit/PlusLib#527]
Hi.  I just forked this and then added support for a device.  I noticed that in the instruction manual https://plustoolkit.github.io/devicecode for doing so, there is not a step requiring the user to edit vtkPlusDeviceFactory.cxx in the constructor of this class.  In order to make mine be found by PlusServer, I had to add 

#ifdef PLUS_USE_Device
    RegisterDevice("Device", "vtkPlusDeviceTracker", (PointerToDevice)& vtkPlusDeviceTracker::New);
#endif

**Comment by adamrankin** [comment]
Ah much appreciated. I will add that.

**Comment by adamrankin** [comment]
https://github.com/PlusToolkit/plustoolkit.github.io/commit/5a03a03475dbe87d2187d3cda27f316b576f871b
