### ISSUE TITLE
Remove support for VTK 7

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#532]
Currently Plus supports VTK 7.1 and 8.2.

Since Slicer only uses VTK 8, is there any reason why we should continue to maintain support for VTK 7 going forward?

@lassoan @adamrankin

**Comment by lassoan** [comment]
I don't think we need to support VTK7 anymore.

**Comment by Sunderlandkyl** [comment]
Sounds good. Unless there are any objections, I'll go ahead and remove VTK 7 support.

**Comment by adamrankin** [comment]
Just waiting on #529, which I guess isn't VTK related, except that I have the CMake code grab a newer OpenCV on VTK >= 8.x

**Comment by adamrankin** [comment]
The OpenCV fix has been merged, so maybe update the CMake code to grab 3.4 branch instead of tag 3.4.5?

**Comment by Sunderlandkyl** [comment]
Right, I'll go ahead and do that.
