### ISSUE TITLE
VolumeReconstructor Error

### ISSUE THREAD

**Issue by zoez526** [PlusToolkit/PlusLib#540]
Hello,

I got the following errors when running VolumeReconstructor.exe.
![image](https://user-images.githubusercontent.com/35669350/56978924-7872ca80-6b2d-11e9-821f-edf9836704b2.png)

However, the .mha file does have "BinaryData=true"
![image](https://user-images.githubusercontent.com/35669350/56979096-cdaedc00-6b2d-11e9-8bea-03d39b73f4f8.png)

The version of Plus I'm using was built from the master branch of PlusBuild on April 29,2019, using windows msvc2015 64bit.

**Comment by Sunderlandkyl** [comment]
Thanks! I'm running some tests on a new VTK 8 build. I'll let you know if I find the problem or if I need more information to replicate it.

**Comment by Sunderlandkyl** [comment]
I've pushed a fix to IGSIO. Let me know if that fixes it.

**Comment by zoez526** [comment]
> I've pushed a fix to IGSIO. Let me know if that solves it.

Thanks! The issue was fixed.
