### ISSUE TITLE
Brachy stepper library issue?

### ISSUE THREAD

**Issue by felixnavarro** [PlusToolkit/PlusLib#543]
Dear all,

After several tests I don't know if I have found an issue in the library for Civco Brachytherapy stepper or I'm writing a wrong xml configuration file.

When I define the data sources, the log file shows errors telling that those were previously defined. If I change their names, another problem appears. 

I have tested it in the latest stable version and the nightly built version. 

Please find attached the configuration files and their log files.

[configV4.xml.txt](https://github.com/PlusToolkit/PlusLib/files/3137860/configV4.xml.txt)
[configV5.xml.txt](https://github.com/PlusToolkit/PlusLib/files/3137861/configV5.xml.txt)
[Log_configV4.txt](https://github.com/PlusToolkit/PlusLib/files/3137862/Log_configV4.txt)
[Log_configV5.txt](https://github.com/PlusToolkit/PlusLib/files/3137863/Log_configV5.txt)

Regards.

**Comment by adamrankin** [comment]
Try this configuration:
* Removed AcquisitionRate="3" from mixer
* Changed IGT message type from `TRACKEDIMAGE` -> `IMAGE` and `TRANSFORM`

```xml
<PlusConfiguration version="2.0">
  <DataCollection StartupDelaySec="1.0" >
    <DeviceSet 
      Name="PlusServer: Capturadora UVC + CIVCO EXII Digital Stepper v4"
      Description="Capturadora UVC + CIVCO EXII Digital Stepper"
    />
  <Device
      Id="VideoDevice" 
      Type="VFWVideo"
      AcquisitionRate="30" >
      <DataSources>
        <DataSource Type="Video" Id="Video" PortUsImageOrientation="MF"  />     
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStream" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>

    <Device
      Id="TrackerDevice"
      Type="BrachyTracker"
      BrachyStepperType="CIVCO"
      ModelNumber="EXII"
      ModelVersion="7500"
      ModelSerialNumber="167"
      LocalTimeOffsetSec="0.0"
      SerialPort="5"
      BaudRate="9600"
      AcquisitionRate="3"
      ToolReferenceFrame="Tracker">
      <DataSources>
        <DataSource Id="Probe"
                    Type="Tool"
                    PortName="0" BufferSize="1500"
                    AveragedItemsForFiltering="20"/>
        <DataSource Id="Template"
                    Type="Tool"
                    PortName="1" BufferSize="1500"
                    AveragedItemsForFiltering="20"/>
        <DataSource Id="StepperEncoderValues"
                    Type="Tool"
                    PortName="2" BufferSize="1500"
                    AveragedItemsForFiltering="20"/>
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerOutput">
          <DataSource Id="Probe"/>
          <DataSource Id="Template"/>
          <DataSource Id="StepperEncoderValues"/>
        </OutputChannel>
      </OutputChannels>
    </Device>

     <Device
      Id="TrackedVideoDevice"
      Type="VirtualMixer"
      LocalTimeOffsetSec="0">
      <InputChannels>
        <InputChannel Id="TrackerOutput" />
        <InputChannel Id="VideoStream" />
      </InputChannels>
      <OutputChannels>
        <OutputChannel Id="TrackedVideoStream"/>
      </OutputChannels>
    </Device>
  </DataCollection>

  <CoordinateDefinitions>
    <Transform From="Image" To="Reference"
      Matrix="
        -0.2 0.0 0.0 0.0
        0.0 -0.2 0.0 0.0
        0.0 0.0 0.2 0.0
        0 0 0 1" />
  </CoordinateDefinitions>
  
  <PlusOpenIGTLinkServer 
    MaxNumberOfIgtlMessagesToSend="10" 
    MaxTimeSpentWithProcessingMs="50" 
    ListeningPort="18944" 
    SendValidTransformsOnly="true" 
    OutputChannelId="TrackedVideoStream" >
    <DefaultClientInfo> 
      <MessageTypes>
        <Message Type="TRANSFORM" />
        <Message Type="IMAGE" />
      </MessageTypes>
      <TransformNames> 
        <Transform Name="ProbeToTracker" />
        <Transform Name="TemplateToTracker"/>
        <Transform Name="StepperEncoderValuesToTracker"/> 
      </TransformNames> 
      <ImageNames>
        <Image Name="Image" EmbeddedTransformToFrame="Reference" />
      </ImageNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>
</PlusConfiguration>
```

**Comment by felixnavarro** [comment]
The log shows (Plus-2.6.0.63ba551d - Win32):

> |ERROR|028.939000|SERVER> Data source name "Probe" is not unique. Skipping.| in :\D\PSNPb\PlusLib\src\PlusDataCollection\vtkPlusDevice.cxx(1003)
|ERROR|028.962000|SERVER> Data source name "Template" is not unique. Skipping.| in :\D\PSNPb\PlusLib\src\PlusDataCollection\vtkPlusDevice.cxx(1003)
|ERROR|028.984000|SERVER> Data source name "StepperEncoderValues" is not unique. Skipping.| in :\D\PSNPb\PlusLib\src\PlusDataCollection\vtkPlusDevice.cxx(1003)

For version 2.7 the only change is the line of vtkPlusDevice.cxx (996)

When I connect to the server from 3DSlicer the log shows:  "No data is broadcasted, as no data is available yet"

**Comment by adamrankin** [comment]
That is with the config file I posted?

**Comment by felixnavarro** [comment]
Yes

**Comment by adamrankin** [comment]
I'm not sure what's happening then. The config file doesn't have duplicate IDs. Are you able to build Plus to investigate?

**Comment by felixnavarro** [comment]
I have no SDK and I need admin permissions, It will take me several days to get it installed. Meanwhile, is there any log file that I can upload?

**Comment by adamrankin** [comment]
Yes, you'll find them in <PlusInstall>/bin/Output I believe

**Comment by felixnavarro** [comment]
Dear Adam, sorry for the late reply.
Please find attached the log file.
[050319_081615_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/3158894/050319_081615_PlusLog.txt)

**Comment by felixnavarro** [comment]
I'm building the ITK/VTK required libraries.

Meanwhile, does anyone knows which options of the makefile should I take care of to compile the library including brachy steppers and frame grabbers (VFWvideo)?

**Comment by Sunderlandkyl** [comment]
You can enable the following options in PlusBuild:

Brachy stepper device:
- PLUS_USE_BRACHY_TRACKER

VFWVideo:
- PLUS_USE_VFW_VIDEO

**Comment by felixnavarro** [comment]
Dear all, I'm having some problems building the libray. 

I've build IGSIO with superbuild option but Release solution and I have sat up the following variable at CMake for PlusLib:

CMAKE_PREFIX_PATH to the binary IGSIO\vtkAddon-bin folder (since setting this path into vtkAddon_DIR variable didn't work).

When I configure the CMake project I get the following error:
`CMake Error at C:/lib/bin/IGSIO/IGSIOConfig.cmake:27 (INCLUDE):
  INCLUDE could not find load file:

    C:/lib/bin/IGSIO/IGSIOTargets.cmake
Call Stack (most recent call first):
  src/CMakeLists.txt:46 (FIND_PACKAGE)


CMake Error at C:/lib/bin/IGSIO/IGSIOConfig.cmake:27 (INCLUDE):
  INCLUDE could not find load file:

    C:/lib/bin/IGSIO/IGSIOTargets.cmake
Call Stack (most recent call first):
  src/PlusCommon/CMakeLists.txt:29 (FIND_PACKAGE)


CMake Error at src/PlusCommon/CMakeLists.txt:40 (GET_PROPERTY):
  GET_PROPERTY could not find TARGET igtlioConverter.  Perhaps it has not yet
  been created.`

**Comment by felixnavarro** [comment]
Dear all,

I have compiled the PlusBuild project  (thanks to Andras Lasso). 

Now, do you know the changes that I should perform in order to use the new compiled library? 

If the problems about duplicate IDs are still appearing, do you know how can I debug the code in order to find the problem?

Thank you in advance.

**Comment by lassoan** [comment]
I would recommend to create a simple configuration file first, which only sends the transform that it gets from the BrachyTracker device. Let us know if it works.

**Comment by felixnavarro** [comment]
The errors appear using only the brachy stepper device too. Please look at the first 3 errors of the log:
[020819_155005_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/3309301/020819_155005_PlusLog.txt)

**Comment by felixnavarro** [comment]
This is the log file that I obtain when the stepper is connected and I try to connect from the IGT link interface for 3D Slicer.
[062019_165114_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/3311005/062019_165114_PlusLog.txt)

**Comment by Sunderlandkyl** [comment]
It does look like the data sources are are hardcoded into the BrachyStepper device. https://github.com/PlusToolkit/PlusLib/blob/f0a2902025bd7a22de5f989f87a7bba04f96ee10/src/PlusDataCollection/BrachyTracking/vtkPlusBrachyTracker.cxx#L43-L63

Do the "No data is broadcasted" messages continue after you start moving the probe?

**Comment by felixnavarro** [comment]
Yes

**Comment by felixnavarro** [comment]
Any clue about this?

**Comment by lassoan** [comment]
If you have multiple sequence files that have corresponding timestamps then you can use those timestamps to synchronize replay of all the sequence files. To enable this, set "UseOriginalTimestamps" attribute to "TRUE" in your SavedDataSource type replay devices.

**Comment by felixnavarro** [comment]
Hi Andras, as you can read in the PlusLog file attached, I have only included the BrachyTracker device in the configuration xml file.
I have tested several buffer sizes (5 to 10*acquisition rate) , acquisition rates (3 to 20) and averaged items (from 0.5 to 2*acquisition rate) but I get the same result.

**Comment by lassoan** [comment]
Have you set "UseOriginalTimestamps" attribute to "TRUE" in the SavedDataSource device? Anyway, it is just a debug message, not even a warning, so it is not a problem, just tells that sequences are not replayed in a synchronized manner.

**Comment by felixnavarro** [comment]
The problem is that the BrachyTracker device seems not to send any information. Even moving the device while the IGTLinkIf of 3DSlicer is active, the log of the server shows that no data can be sent since the device has not sent any information.

Do anyone has a clue about this error?

**Comment by felixnavarro** [comment]
Dear developers, 
Could any of you find the reason why this device is not sending information to the IGT link server?

I attach the XML file for your convenience:
[Stepper_TX_v1.xml.txt](https://github.com/PlusToolkit/PlusLib/files/3368161/Stepper_TX_v1.xml.txt)

**Comment by Sunderlandkyl** [comment]
I've added some more debug info to the brachy stepper device (https://github.com/PlusToolkit/PlusLib/commit/41dd3d7e533a8f018d043e7817bf9291a73dd8bc).

Could you update your build and upload a log using log level trace?

**Comment by felixnavarro** [comment]
Thank you for the support. Attached you can find the new log file.
[070919_101546_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/3371915/070919_101546_PlusLog.txt)

**Comment by felixnavarro** [comment]
Could you guess where the bug is using that information? I can perform more tests if it is needed.

**Comment by felixnavarro** [comment]
Dear developers, is it possible to debug the code using Eclipse or do I need other IDE to try to find the bug?

**Comment by Sunderlandkyl** [comment]
Unfortunately, the added messages didn't provide any useful information. As far as I can tell, the data should be propagated correctly, so I'm not sure what the problem is, but I'll keep looking at it.
You can debug using VisualStudio on windows (see https://github.com/PlusToolkit/PlusBuild/blob/master/Docs/BuildInstructionsWindows.md).

**Comment by adamrankin** [comment]
It may be possible to use the eclipse CDT for debugging. I don't think anyone on the Plus team has tried it, but in theory it should be possible.

**Comment by felixnavarro** [comment]
While the IT department set up the debugging tools I'm available to test any changes that you can introduce. 
If you want to add more debug info I can execute it.

**Comment by felixnavarro** [comment]
Dear all,
I would like cmake to verify the updates of the local copy of the code instead of the one in github, is it possible? This way I could introduce more debugging messages that could help to find the bug.
If it is possible, do you know how to do it?
Thank in advance.

**Comment by felixnavarro** [comment]
I have created my own repository with a copy of PlusLib master branch where I have uploaded the code with some extra debug information. I have configured the compilation process using  -DPLUSLIB_GIT_REPOSITORY="https://github.com/felixnavarro/PlusLib-master_copy.git", however the plusApp executable is not built since an error appears:

>%Temp%\.NETFramework,Version=v4.0.AssemblyAttributes.cpp : fatal error C1083: Cannot open compiler generated file: 'Debug/.NETFramework,Version=v4.0.AssemblyAttributes.asm': No such file or directory [C:\D\PlusExp-x32-bin_copy\PlusLib.vcxproj]

> C:\Users\rayox010\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp : fatal error C1083: No se puede abrir el archivo generado por el compilador: 'Release/.NETFramework,Version=v4.0.AssemblyAttributes.asm': No such file or directory [C:\D\PlusExp-x32-bin_copy\PlusLib-bin\src\SEIDrv\vtkSEIDrv.vcxproj] [C:\D\PlusExp-x32-bin_copy\PlusLib.vcxproj]

I changed the Asm List Location property of the SEIdrv project from Debug/ to $(IntDir) but the problem is still appearing. 
In the log file I can see a warning recommending to use CMake 3.15.1 but as far as I know it is not still released (I'm using 3.14.5).

Is there any workaround? 

Attached you can find the configuration file and the log that I found in the forder C:\D\PlusExp-x32-bin_copy\testing\temporary
[CMakeCache.txt](https://github.com/PlusToolkit/PlusLib/files/3422897/CMakeCache.txt)
[LastBuild_20190723-1236.log.txt](https://github.com/PlusToolkit/PlusLib/files/3422929/LastBuild_20190723-1236.log.txt)

**Comment by Sunderlandkyl** [comment]
I'll take a look at the CMake issue, but I think if you disable PLUS_USE_USDIGITALENCODERS_TRACKER, it should fix the compile error.

**Comment by lassoan** [comment]
Unfortunately, Civco stepper uses US digital encoders, so he needs the PLUS_USE_USDIGITALENCODERS_TRACKER option enabled. You can confirm that your stepper uses these encoders by installing SEI software (https://www.usdigital.com/support/software/sei) and running diagnostic and test applications.

**Comment by Sunderlandkyl** [comment]
This is the same issue that was mentioned here: https://github.com/PlusToolkit/PlusLib/pull/575
Unfortunately, CMake 5.15.1 has not been released yet, so the option to update does not exist.

**Comment by adamrankin** [comment]
Nightly releases:
https://cmake.org/files/dev/?C=M;O=D

**Comment by felixnavarro** [comment]
I have installed the nightly version of CMake (3.15.20190720-g23990 win64-x64), reconfigured and rerunned the ctest command. 
I found this error in the log file:

> CUSTOMBUILD : CMake error : File C:/Program Files/CMake/share/cmake-3.14/Modules/CMakeSystem.cmake.in does not exist. [C:\D\PlusExp-x32-bin_copy\Deps\IGSIO-bin\vtkAddon.vcxproj] [C:\D\PlusExp-x32-bin_copy\IGSIO.vcxproj]
>    CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/CMakeDetermineSystem.cmake:185 (configure_file):

It seems that IGSIO is looking for 3.14 version instead of 3.15. I'll delete everything and I'll try it again from scratch. I'll inform you about the results in a couple of hours.

**Comment by felixnavarro** [comment]
The compilation process ended successfully after repeating it from scratch, the only detail is a warnin while linking SEIRDrv project:

> ".NETFramework,Version=v4.0.AssemblyAttributes.obj` : warning LNK4221: This object file does not define any symbol that were not defined previously, so it will not be linked in any link which uses this library. [C:\D\PlusExp-x32-bin_copy\PlusLib-bin\src\SEIDrv\vtkSEIDrv.vcxproj] [C:\D\PlusExp-x32-bin_copy\PlusLib.vcxproj]

> mocs_compilation.obj : warning LNK4221: his object file does not define any symbol that were not defined previously, so it will not be linked in any link which uses this library.  [C:\D\PlusExp-x32-bin_copy\PlusLib-bin\src\SEIDrv\vtkSEIDrv.vcxproj] [C:\D\PlusExp-x32-bin_copy\PlusLib.vcxproj]

Please notice that the text is a translation of the message in Spanish, so you could receive an sligtly different message in your language.

I'll add some debug text (LOG_TRACE)  in order to attempt to find why the information of the stepper is not populated.

**Comment by felixnavarro** [comment]
I have introduced some a trace comment in vtkPlusOpenIGTLinkServer.cxx (line 438) just before "if (self.LogWarningOnNoDataAvailable)". This is the result:

> |WARNING|038.171000|SERVER> No data is broadcasted, as no data is available yet.| in C:\D\PlusExp-x32-bin_copy\PlusLib\src\PlusServer\vtkPlusOpenIGTLinkServer.cxx(446)
|INFO|038.172000|SERVER> self.BroadcastChannel->GetVideoDataAvailable() :0
|INFO|038.174000|SERVER> self.BroadcastChannel->ToolCount() :3
|INFO|038.176000|SERVER> self.BroadcastChannel->GetTrackingDataAvailable() :1
|INFO|038.176000|SERVER> self.BroadcastChannel->FieldCount() :3
|INFO|038.177000|SERVER> self.BroadcastChannel->GetFieldDataAvailable() :0
|INFO|038.178000|SERVER> self.BroadcastChannel->GetVideoDataAvailable() :0
|INFO|038.179000|SERVER> self.BroadcastChannel->ToolCount() :3
|INFO|038.180000|SERVER> self.BroadcastChannel->GetTrackingDataAvailable() :1
|INFO|038.181000|SERVER> self.BroadcastChannel->FieldCount() :3
|INFO|038.181000|SERVER> self.BroadcastChannel->GetFieldDataAvailable() :0
|INFO|038.182000|SERVER> self.BroadcastChannel->GetVideoDataAvailable() :0
|INFO|038.183000|SERVER> self.BroadcastChannel->ToolCount() :3
|INFO|038.183000|SERVER> self.BroadcastChannel->GetTrackingDataAvailable() :1
|INFO|038.184000|SERVER> self.BroadcastChannel->FieldCount() :3
|INFO|038.184000|SERVER> self.BroadcastChannel->GetFieldDataAvailable() :0

Does it give you any clue about where the bug is?

**Comment by felixnavarro** [comment]
Dear all, did this information gave you any clue about where the problem is?
Thank you.

**Comment by Sunderlandkyl** [comment]
Unfortunately there is still not enough information.
If you have a debug build set up, and you are willing to let us access your computer, we can try to debug it remotely.

**Comment by felixnavarro** [comment]
I have asked to the IT department of the hospital. It is required to sign an agreement to grant the access to any computer from the hospital. I could set up the debug enviroment in my personal laptop and use my cell phone connect it to the internet.

I will inform you as soon as everything is ready.

Thank you very much for your support.

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
