### ISSUE TITLE
Update ITKv4.12 to ITKv5

### ISSUE THREAD

**Issue by jamesobutler** [PlusToolkit/PlusLib#544]
Similar to #532 which removed support for VTK7 since Slicer isn't using it anymore, should PLUS go ahead and update to ITKv5 since that is also what Slicer uses now?

**Comment by lassoan** [comment]
Yes, it would be nice to follow Slicer's ITK&VTK versions in Plus. We don't use that much ITK in Plus, so probably we would not need to update any code, but the build system may need some tuning.

**Comment by jamesobutler** [comment]
@adamrankin The PlusLib and PlusApp dashboards are showing the following build errors:
```
 fatal error C1083: Cannot open include file: 'itk_compiler_detection.h': No such file or directory
```

**Comment by Sunderlandkyl** [comment]
@jamesobutler I'm working to fix the builds now.

**Comment by adamrankin** [comment]
Is this a build machine thing? I built both versions clean in my local copy and they worked.

**Comment by Sunderlandkyl** [comment]
I think so. Had to update CMake, and now I'm getting an H5T error in ITK (http://perkdata.cs.queensu.ca/CDash/buildSummary.php?buildid=116398).

Might need to clean and rebuild the dashboard builds.

**Comment by adamrankin** [comment]
I ended up deleting the itk, itk-bin and itk-prefix folders, then re-running PlusBuild CMake between version switches. Existing files in those folders will throw off the build of ITK.

**Comment by Sunderlandkyl** [comment]
Deleting the ITK related folders fixed the error: http://perkdata.cs.queensu.ca/CDash/buildSummary.php?buildid=116400
