### ISSUE TITLE
Question about PLUS toolkit and Ultrasonix ultrasound

### ISSUE THREAD

**Issue by pctlr75** [PlusToolkit/PlusLib#545]
Good day everyone, 
I repost a topic from slicer forum.

-------------------------------------------------------------------------------------------------------------------

"Good morning everyone,

I have an issue with transfering us images from my Ultrasonix probe (running on a 32 bit os) to my main working PC (64 bits os).

I have seen that people should use toolKitPlus on the 32 bit pc and Slicer on my 64 bit os… Using OpenIGTLink

I configured the Ultrasonix pc as a client and my main pc as a server (recieving images). But it doesn’t work…

**Can someone give me a step-by-step manual** about how to transfer images from one pc to another… ?

Thank you for your patience."

-------------------------------------------------------------------------------------------------------------------

To be a little bit more precise, I do not have particular issues with Plus, I only need some clear explanations on how to configure my two pcs in order to transfer my probe images to my main pc throught IGTLink protocole...

The config of both pcs:
- the ultrasonix pc: 
     - Microsoft Windows Xp, embedded version, 2002, service pack 3, 32 bits
     - Intel(R) Core(TM), Duo CPU E4300@1.80GHz, 1.98 Gb of RAM
-  the main pc:
     - Linux Ubuntu 64 bits
     - 1,3 Gio or RAM, Intel® Xeon(R) CPU E5-1680 v3 @ 3.20GHz × 16 , GeForce GTX 980

Again, thank you.

**Comment by Sunderlandkyl** [comment]
You can find step-by-step tutorials on how to connect Plus and Slicer here: http://www.slicerigt.org/wp/user-tutorial/

On the Ultrasonix computer, you will need to download the Ultrasonix package here: http://perk-software.cs.queensu.ca/plus/packages/stable/

**Comment by adamrankin** [comment]
Please note the version of Ultrasonix software required. If you run into a specific issue, please post a new issue!
