### ISSUE TITLE
There is no track data when I connect to NDI polaris

### ISSUE THREAD

**Issue by polarseabear** [PlusToolkit/PlusLib#550]
I use the default configuration file "NDI polaris tracker with passive markers". Should I modify it?  
And I use it connect to NDI , it was connected successfully. But there were two errors in log file.
`051419_093837.776|ERROR|000.972000| Failed to get most recent timestamp from all the tracker tools| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(1321)
051419_093837.778|ERROR|000.973000| vtkPlusChannel::GetTrackedFrameListSampled failed: unable to get most recent timestamp. Probably no frames have been acquired yet.| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(1070)
051419_093837.778|ERROR|000.973000| Error while getting tracked frame list from data collector during capturing. Last recorded timestamp: 0.972000| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\VirtualDevices\vtkPlusVirtualCapture.cxx(336)`
I use Slicer to watch the track in real time.I clicked "active". But there is nothing under Scene/IGTLConnector/IN .

**Comment by adamrankin** [comment]
What tools are you using? Do they match the .rom files specified in the config file?

**Comment by polarseabear** [comment]
I use the NDI Polaris Vicra. The specified .com file in example config file is just like my .com file .Should I change it? My English is not so well，I don’t know if you get it. Thanks a lot for your reply.

**Comment by adamrankin** [comment]
What physical tool are you using?

**Comment by polarseabear** [comment]
I’m sorry. Is NDI not a physical tool?

**Comment by adamrankin** [comment]
![example](https://user-images.githubusercontent.com/3210398/57870531-4e7c0200-77d5-11e9-8779-16191c065767.png)

**Comment by polarseabear** [comment]
I use the same tools as in the example. But the file name is different. This is a part of my config file.
`For NDI Polaris passive marker starting kit: Tool (8700339), Stylus (8700340), Reference (8700338)" />
    <Device
      Id="TrackerDevice"
      Type="PolarisTracker"
      ToolReferenceFrame="Tracker" >
      <DataSources>
        <DataSource Type="Tool" Id="Tool" RomFile="NdiToolDefinitions/8700339.rom"  />
        <DataSource Type="Tool" Id="Stylus" RomFile="NdiToolDefinitions/8700340.rom"  />
        <DataSource Type="Tool" Id="Reference" RomFile="NdiToolDefinitions/8700338.rom"  />`
There is still no input data. 

Could you tell me what these errors mean?

`|ERROR|261.235000|SERVER> Failed to get most recent timestamp from all the tracker tools| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(1321)
|ERROR|261.252000|SERVER> Error while getting tracked frame list from data collector during capturing. Last recorded timestamp: 0.972000| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\VirtualDevices\vtkPlusVirtualCapture.cxx(336)`

Thanks a lot for your reply.

**Comment by adamrankin** [comment]
In my image, I made up the filenames, they are not real. Your file names match real NDI tools.

The errors mean that no data is available to send to the clients, and thus the most recent timestamp doesn't exist.

Could you attach a picture of the tools you are using?

**Comment by polarseabear** [comment]
My problem is solved. Just because I didn’t replace .com file with my own.
Thanks a lot for your help!
