### ISSUE TITLE
Multi-build environment broken with ITK install

### ISSUE THREAD

**Issue by adamrankin** [PlusToolkit/PlusLib#551]
This change of using the install dir has broken the build environment. All configurations point to the same libraries (`.../itk-int/lib/ITKXYZ.lib```) preventing a multi-build environment.

@Sunderlandkyl could you either revert the install ITK/VTK step or adjust the build environment to use the appropriate libraries for each build?

**Comment by Sunderlandkyl** [comment]
Well we can't revert it or most of the package builds would stop working (rc.exe failure), so probably the latter is the only viable solution.

**Comment by adamrankin** [comment]
Was it the switch to ITK 5 that stopped the package building?

**Comment by Sunderlandkyl** [comment]
The switch to VTK 8 caused some of them to stop working, but the ITK switch tipped most of the others over the edge.

**Comment by adamrankin** [comment]
Can we not just shorten the build paths? I know it's a workaround but it may be easier than doing generator expressions for library locations

**Comment by Sunderlandkyl** [comment]
I could maybe remove one character from the build paths, but most of them are as short as possible while still being informative (ex E:\D\PTNPThb is the ThorLabs package path).

**Comment by adamrankin** [comment]
I meant the ITK/VTK build paths.

Remove the Deps folder, shorten VTK and ITK to vs, vp, and vb (is, ip and ib)

**Comment by Sunderlandkyl** [comment]
Yeah, that might work.

**Comment by Sunderlandkyl** [comment]
Future proof wise, I'm not sure what the rc.exe command length would be once we made the path change.
We might still be close to the limit, which could reduce the number of devices that we can enable at a time going forward.

**Comment by adamrankin** [comment]
Yup, definitely a stop-gap.

**Comment by lassoan** [comment]
@Sunderlandkyl please ask on the VTK mailing list if there is a solution for multi-configuration builds from installed VTK.

**Comment by adamrankin** [comment]
I wonder if you can use generator expressions in the install dir

```cmake
SOURCE_DIR "${PLUS_VTK_SRC_DIR}"
BINARY_DIR "${PLUS_VTK_BIN_DIR}"
INSTALL_DIR "${CMAKE_BINARY_DIR}/Deps/vtk-int/$<CONFIG>" CACHE INTERNAL "Path to install vtk")
```

**Comment by Sunderlandkyl** [comment]
Made a post here: https://discourse.vtk.org/t/multi-configuration-from-installed-vtk/978

**Comment by mathstuf** [comment]
I replied over on Discourse (let's keep the VTK details over there; we can bring back a summary of the resolution to here once that's complete), but the `rc` command line limit issue is [known in CMake](https://gitlab.kitware.com/cmake/cmake/issues/16171).

**Comment by Sunderlandkyl** [comment]
@adamrankin

I didn't get a chance to try fixing this today, and I'm going to be traveling without a PC for the next week.

I should be back on the 27th.

**Comment by Sunderlandkyl** [comment]
Testing now, but it looks like adding -DCMAKE_DEBUG_POSTFIX:STRING=D to ITK and VTK external projects allows multiple installed configurations.

**Comment by jamesobutler** [comment]
Just following up, @Sunderlandkyl Is there still actions left to do for this issue?

**Comment by Sunderlandkyl** [comment]
Nope, multi-build environment seems to work fine now.
