### ISSUE TITLE
how do I import the scanned ultrasound sequence and pose data into the plus toolkit for 3D reconstruction?

### ISSUE THREAD

**Issue by zhaobingshuai** [PlusToolkit/PlusLib#554]
Hello, how do I import the scanned ultrasound sequence and pose data into the plus toolkit for 3D reconstruction? My ultrasound sequence is a set of png format images or a mpg format video. My pose data is a txt file. I want to know the specific operation process, but I can't find the corresponding tutorial online.

**Comment by adamrankin** [comment]
You can find tutorials here
http://www.slicerigt.org/wp/user-tutorial/

Specifically, U-33.

If you encounter a specific problem, please feel free to open a new issue!

**Comment by adamrankin** [comment]
Ah! Sorry, you

**Comment by zhaobingshuai** [comment]
Hello, under your guidance, I have converted the image sequence into a metaimage format via ImageJ, but I still don't understand how to convert my images and poses into metaimage format with Plus extensions.
Please help me solve this problem with as much detailed steps as possible.

**Comment by zhaobingshuai** [comment]
In addition, I converted the image sequence to mhd+raw instead of mha via ImageJ with metaimage importer/exporter. What should I do to convert directly to mha? Or how to convert mhd+raw to mha?

**Comment by zhaobingshuai** [comment]
my pose data as follows, it is a txt file.
num times x      y              z                  poll           yaw          pitch
1 0 -0.000000 0.000000 -0.000000 -9.625642 -0.652008 176.827563
2 17 0.003849 -0.018843 0.019765 -9.705239 -0.645206 176.886740
3 33 0.004341 -0.041139 0.041279 -9.815517 -0.626301 176.998167
4 50 0.003951 -0.064889 0.063110 -9.871499 -0.633918 177.086277
5 67 0.006440 -0.085995 0.085305 -9.873428 -0.665327 177.107177
6 83 -0.104705 0.056453 0.141668 -7.892624 0.684251 180.006374
7 100 -0.105894 0.053215 0.127525 -7.899557 0.654853 179.951418
8 117 -0.107241 0.049603 0.112423 -7.926344 0.651960 179.893293
