### ISSUE TITLE
Ultrasound simulation image quality

### ISSUE THREAD

**Issue by Lyla-M** [PlusToolkit/PlusLib#557]
I'm using Plus ultrasound simulator to make an unity app, but I ran into problems while scaling the simulated ultrasound image. 
It seemed like the image quality drops no matter which parameter I use to shrink the image size down. 
Please see attached document of my code and image results.

Thanks alot!

Lyla
[UltraoundSimulation.docx](https://github.com/PlusToolkit/PlusLib/files/3218407/UltraoundSimulation.docx)

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
