### ISSUE TITLE
how to convert my images and poses into metaimage format with Plus extensions

### ISSUE THREAD

**Issue by zhaobingshuai** [PlusToolkit/PlusLib#559]
Hello, under your guidance, I converted the image sequence to mhd+raw instead of mha via ImageJ with metaimage importer/exporter. And i convert mhd+raw to mha via 3d slicer .What should I do to convert directly to mha? In addition, I still don't understand how to convert my images and poses into metaimage format with Plus extensions (which extension? How to do?).
Please help me solve this problem with as much detailed steps as possible.

**Comment by adamrankin** [comment]
Please open an existing sample Plus file:
https://github.com/PlusToolkit/PlusLibData/blob/master/TestImages/fCal_Test_Validation_3NWires.igs.mha

Observe the format of transforms in the header area of the file. Duplicate that format with your transforms into your .mha file.

**Comment by zhaobingshuai** [comment]
this is the header area of the existing sample Plus file:
ObjectType = Image
NDims = 3
AnatomicalOrientation = RAI
BinaryData = True
BinaryDataByteOrderMSB = False
CenterOfRotation = 0 0 0
CompressedData = True
CompressedDataSize = 628173           
DimSize = 820 616 94              
Kinds = domain domain list
ElementSpacing = 1 1 1
ElementType = MET_UCHAR
Offset = 0 0 0
TransformMatrix = 1 0 0 0 1 0 0 0 1
UltrasoundImageOrientation = MFA

this is the header area of my .mha file:
ObjectType = Image
NDims = 3
BinaryData = True
BinaryDataByteOrderMSB = False
CompressedData = True
CompressedDataSize = 26447663
TransformMatrix = 1 0 0 0 1 0 0 0 1
Offset = 0 0 0
CenterOfRotation = 0 0 0
AnatomicalOrientation = RAI
ElementSpacing = 1 1 1
DimSize = 606 631 434
ElementType = MET_UCHAR
ElementDataFile = LOCAL

this is the pose data in sample Plus file:
Seq_Frame0000_ProbeToTrackerTransform = -0.0512488 0.284201 0.957394 252.89 -0.176415 0.941002 -0.288779 19.7569 -0.982981 -0.183698 0.00191215 -2.79053 0 0 0 1
Seq_Frame0000_ProbeToTrackerTransformStatus = OK

I still don't understand how to convert my images and poses into metaimage format with Plus extensions (which extension? How to do?).

**Comment by adamrankin** [comment]
The Plus extension is simply the addition of transform data in the header area.

Your images are already in metaimage format. You must add your transform data to the metaimage file. The format of how to add a transform is what you pasted above:
>Seq_Frame0000_ProbeToTrackerTransform = -0.0512488 0.284201 0.957394 252.89 -0.176415 0.941002 -0.288779 19.7569 -0.982981 -0.183698 0.00191215 -2.79053 0 0 0 1
>Seq_Frame0000_ProbeToTrackerTransformStatus = OK

The format is:
```
Seq_Frame<FrameNumber>_<TransformName>Transform = [16 element matrix]
Seq_Frame<FrameNumber>_<TransformName>TransformStatus = OK
```

`FrameNumber` corresponds to the image in the sequence at that index
`TransformName` is the name of the transform, your choice
`[16 element matrix]` is 16 numbers representing a 4x4 transformation matrix

**Comment by adamrankin** [comment]
Copy the sample header into your file, replacing the values with the values from your file.

**Comment by zhaobingshuai** [comment]
First of all, thank you very much for your guidance. I understand what you mean, but I still don't know how to do it. My current data includes a set of two-dimensional ultrasound scan sequences and six degrees of freedom for each frame of ultrasound image during scanning. My tutor hopes that I will reconstruct these data into three-dimensional ultrasound via the Plus tookkit. But I don't have a 4x4 transformation matrix. If I have one, according to your point of view, should I manually copy the pose data to the header area of my .mha file according to the format you gave? I think this is too much trouble, and it doesn't use the Plus toolkit.
Can PlusToolkit directly import my 2D ultrasound scan sequence and pose data, one-click reconstruction to 3D ultrasound? I need your help and I can send my data to you via email if necessary.

**Comment by lassoan** [comment]
> But I don't have a 4x4 transformation matrix.

This is a homogeneous coordinates transformation matrix. Convert roll/pitch/yaw angles to 3x3 orientation matrix (google if you don't know how ot do it) and set it in the top-left 3x3 matrix in the transformation matrix. Copy the 3 position values to the top-right column of the transformation matrix.

**Comment by adamrankin** [comment]
>If I have one, according to your point of view, should I manually copy the pose data to the header area of my .mha file according to the format you gave?

Correct.

>I think this is too much trouble, and it doesn't use the Plus toolkit.

If you would like to write a utility to convert your data to Plus format, we accept pull requests.

**Comment by zhaobingshuai** [comment]
Based on your guidance, I have successfully converted my pose data to a 4 * 4 Euclidean transformation matrix, but I still don't know how to write this data to the header area of my .mha file in the format you gave. I tried to read the .mha file with ImageJ, I did see the header area, but I can only cut and copy but not paste the values. What should I do to insert the pose data into the header area? Thank you. @lassoan @adamrankin

**Comment by adamrankin** [comment]
Notepad++

**Comment by gaoyi** [comment]
Hi Andras,

@lassoan 

This is Yi from Georgia Tech. How are you doing now! We in our lab now are working on this problem of 3D ultrasound reconstruction problem.

The original problem we were facing was that we have a bunch of 2D US image, each of which we have a 6DOF pose parameters. Now we want to perform a 3D reconstruction to form a 3D volume. Sorry for the confusion the original issue title may bring. (I guess what you and Adam kindly pointed out was about displaying individual 2D images with the correct pose in Slicer. We actually want to perform 3D recon.)


I was looking at the "Ultrasound volume reconstruction" figure in the https://plustoolkit.github.io/features.html
page. I think it's that function we'd like to perform through PLUS.

Could we have your advice on the direction we should go to check in PLUS?

The original title may be misleading... should i open another issue for this?

Thanks!

Best,
yi

**Comment by adamrankin** [comment]
By converting the images as described above, you can replay it into the volume reconstruction tool in Plus.

**Comment by gaoyi** [comment]
Thanks Adam! So the volume reconstruction tool will not only replay it, but also form a 3D volume and output as a, say, mha/nrrd/... files?

**Comment by adamrankin** [comment]
That's correct, instead of receiving the data from an ultrasound+tracker live, you replay the image+transforms described above into the volume reconstruction pipeline.

Tutorial [U-34](http://www.slicerigt.org/wp/user-tutorial/) should be the right tutorial once you've assembled the sequence file.

**Comment by gaoyi** [comment]
This is great! Thanks Adam! I'll try the approach.

**Comment by lassoan** [comment]
There is also a command-line tool to reconstruct a 2D+t sequence to a 3D volume (VolumeReconstructor).

**Comment by gaoyi** [comment]
Thanks Andras!
