### ISSUE TITLE
PlusServer Sending Transforms Slower Than Acquisition Rate:

### ISSUE THREAD

**Issue by fergujm2** [PlusToolkit/PlusLib#560]
Hi,

I have recently added a robotic device into PlusLib, and it seems as though I am maxing out the process thread that actually sends the OpenIGTLink messages.

I am using the `StartThreadForInternalUpdates = true` polling method to broadcast 15 - 30 robotic link transforms to Slicer so that I can render the robot motion with STL models that I have for the robot.

When I make `AcquisitionRate = 1` for example in my PlusServer XML file, everything works fine, and my robot transforms update at 1 Hz in my connected client in Slicer. However, when I increase the rate by `AcquisitionRate = 60`, my update rate seems like it is maxing out at about 15 - 20 Hz in Slicer.  Note that I am not rendering the models during this test, only receiving data through OpenIGTLinkIF.

I ran the CPU profiler in Visual Studio, and found that my `vtkDataCaptureThread` was using about 3% of my total CPU whereas my `DataSenderThread` was using around 80% in the `SendLatestFramesToClients` method.  

How can I alter my device to send all of my transforms at these higher acquisition rates?  I would like to see smooth robot motion in Slicer for our image-guidance system.

Thanks,

James

**Comment by adamrankin** [comment]
@lassoan Maybe it's time to implement TDATA support in Slicer/OpenIGTLinkIO?

**Comment by adamrankin** [comment]
Also, would you be willing to test with another IGTL client? I've noticed slow downs in Slicer when updating many IGT nodes (images, transforms, etc...)

**Comment by fergujm2** [comment]
@adamrankin I would be willing to test with another client.  Is there a command line tool for creating an IGTL client that I could use?  I couldn't find anything in the Plus Toolkit for this.

**Comment by adamrankin** [comment]
2 options that I can think of
`TrackingTest` executable (may be a bit simpler to add in FPS/UPS code as it's one file)

`PlusServer` executable (if no client connect, it basically uses 0% cpu)

Sample file with IGT client device
https://github.com/PlusToolkit/PlusLibData/blob/master/ConfigFiles/Queens/PlusDeviceSet_fCal_OpenIGTLink_ImageMessage_TransformMessage.xml
(fCal, but you can copy device to a plusserver config file for second option, first option requires command line arguments, described by `TrackingTest --help`)

**Comment by fergujm2** [comment]
Alright, I did a quick test with TrackingTest by writing the output to a sequence file.  I did this:
`TrackingTest.exe --acq-time-length=5 --config-file="SomeFile.xml" --rendering-off --output-tracker-buffer-seq-file-name=SomeFile.mha`

I pulled all of the frame timestamps out of this file, and it seems that it recorded to the sequence file at almost exactly the rate specified `AcquisitionRate` in my config file.

I'm assuming that TrackingTest creates a client that connects to a PlusServer specified by MyFile.xml? If so, maybe it is a problem with Slicer's ability to receive IGTL messages then?

**Comment by adamrankin** [comment]
`SomeFile.xml`, but yes, that's correct.

I have experienced Slicer's stuttering when sending many transforms. @lassoan A couple of use cases now where circular buffer/node updates is causing performance issues. Any options you can think of?

**Comment by lassoan** [comment]
Need to do profiling, without that we can only guess. First we need to see where the bottleneck is (Slicer or Plus) and then address that.

For initial exploration, VerySleepy profiler might give some clues, too (it does not require rebuilding of anything but only provides information at method call level and sometimes it provides misleading results, probably due to code optimization). 

For more reliable measurements, you need to build in RelWithDebInfo and use VisualStudio's built-in profiler or similar tools.

**Comment by lassoan** [comment]
> Maybe it's time to implement TDATA support in Slicer/OpenIGTLinkIO?

@Sunderlandkyl isn't TDATA already supported?

TDATA is used by BrainLab navigation systems, so it would be nice to have it working again.

BIND message could similarly send multiple messages at once and so grouped updates could be done more robustly (and maybe with a bit less overhead), and that would support both image and tracking data. However, using BIND message would complicate the implementation on both sides, so I would spend time with it only if there is a strong use case.

**Comment by Sunderlandkyl** [comment]
TDATA is not supported.
Supported devices are:
- Image
- ImageMeta
- LabelMeta
- Point
- PolyData
- Status
- String
- Transform
- Video

Any others besides TDATA/BIND that should be added?

**Comment by adamrankin** [comment]
I'd say leave bind until absolutely necessary.

**Comment by fergujm2** [comment]
Are there any thoughts on a temporary workaround for our project in particular? Would sending via multiple PlusOpenIGTLinkServers help speed up the receiving process on Slicer?

**Comment by adamrankin** [comment]
I don't think that would help. The bottleneck (I'm pretty sure) is SlicerOpenIGTLink unpacking messages and updating nodes). If it only has to unpack one message, it might speed it up.

**Comment by lassoan** [comment]
Everything is just guessing. Please do some performance testing first. We can decide on how to proceed depending on what you find.

**Comment by adamrankin** [comment]
I did performance testing a long time ago, it's just not fresh in my mind. I know it's those areas.

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
