### ISSUE TITLE
Unable to install Plus Build

### ISSUE THREAD

**Issue by lRaulMN7** [PlusToolkit/PlusLib#561]
Hello. I wanted to install Plus Build from the master branch to fix the delay that exists when I'm using OpenCVVideo between Plus Server and 3D Slicer.

However, when I install the Plus Build Cmakes and I compile them, I'm getting 4 packages ok, 7 incorrect and 6 omitted in Visual Studio.

These are some of my logs:

PlusLib log:

>   CMake Error at src/CMakeLists.txt:3 (FIND_PACKAGE):
>     Could not find a package configuration file provided by "VTK" with any of
>     the following names:
>   
>       VTKConfig.cmake
>       vtk-config.cmake
>   
>     Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
>     to a directory containing one of the above files.  If "VTK" provides a
>     separate development package or SDK, be sure it has been installed.
>   
>   
>   -- Configuring incomplete, errors occurred!

PlusApp log:

>   CMake Error at CMakeLists.txt:8 (FIND_PACKAGE):
>     Could not find a package configuration file provided by "PlusLib" with any
>     of the following names:
>   
>       PlusLibConfig.cmake
>       pluslib-config.cmake
>   
>     Add the installation prefix of "PlusLib" to CMAKE_PREFIX_PATH or set
>     "PlusLib_DIR" to a directory containing one of the above files.  If
>     "PlusLib" provides a separate development package or SDK, be sure it has
>     been installed.
>   
>   
>   -- Configuring incomplete, errors occurred!

I'm not really sure where do I have to change things in CMake to link everything. I guess this has an easy fix but I can't find out what I'm doing wrong :(

**Comment by Sunderlandkyl** [comment]
What version of Visual studio are you using?

**Comment by lRaulMN7** [comment]
@Sunderlandkyl Visual Studio 2017
In generator I choose Visual Studio 15 2017

**Comment by Sunderlandkyl** [comment]
What is the status of VTK? Were you able to compile it correctly?

**Comment by lRaulMN7** [comment]
Last lines of VTK log are these:

>     vtkRenderingLOD.vcxproj -> C:\D\PlusB-bii\bin\Release\vtkRenderingLOD-8.2.dll
>     vtkRenderingLabel.vcxproj -> C:\D\PlusB-bii\bin\Release\vtkRenderingLabel-8.2.dll
>     vtkRenderingVolumeOpenGL2.vcxproj -> C:\D\PlusB-bii\bin\Release\vtkRenderingVolumeOpenGL2-8.2.dll
>     vtkTestOpenGLVersion.vcxproj -> C:\D\PlusB-bii\bin\Release\vtkTestOpenGLVersion.exe
>     vtkViewsContext2D.vcxproj -> C:\D\PlusB-bii\bin\Release\vtkViewsContext2D-8.2.dll
>     vtkViewsInfovis.vcxproj -> C:\D\PlusB-bii\bin\Release\vtkViewsInfovis-8.2.dll

Can't really tell you if it compiled correctly or not, but I seems ok. @Sunderlandkyl

**Comment by Sunderlandkyl** [comment]
Can you run C:\D\PlusB-bii\BuildAndTest.bat.

That should upload the results of the build here: http://perkdata.cs.queensu.ca/CDash/index.php?project=PlusBuild, so that I can get a better look.

**Comment by lRaulMN7** [comment]
@Sunderlandkyl 
Submission keeps failing... I can show you the screenshot. 

![image](https://user-images.githubusercontent.com/39067731/59048703-baa6ce80-8886-11e9-8e4b-8e8bc064306d.png)

**Comment by lRaulMN7** [comment]
The error was that itk git CMake was doing several references to a branch called **v5.00** that just doesn't exists I rename it to **v5.0.0** and now itk compiles.

I have more issues but so far this is what I fixed

**Comment by Sunderlandkyl** [comment]
Can you upload your VTK and PlusLIb build logs.

Should be in directories like:
- C:/D/PlusB-bii/x86/Release/PlusLib
- C:/D/PlusB-bii/x86/Release/vtk

**Comment by lRaulMN7** [comment]
I think PlusLib and vtk are correctly installed now
I don't have a x86 folder, instead there is a x64. ¿Is that ok?
[vtk.log](https://github.com/PlusToolkit/PlusLib/files/3272222/vtk.log)
[PlusLib.log](https://github.com/PlusToolkit/PlusLib/files/3272223/PlusLib.log)

I think that the only issue I have to fix now is that OpenCV isn't able to find my python libs

[OpenCV.log](https://github.com/PlusToolkit/PlusLib/files/3272225/OpenCV.log)

I tried a few things but still not able to make it work. I'm compiling using Release and x64 mode.

**Comment by Sunderlandkyl** [comment]
Can you upload the CMakeCache.txt in .../Deps/OpenCV-bin?

**Comment by lRaulMN7** [comment]
[CMakeCache.txt](https://github.com/PlusToolkit/PlusLib/files/3272314/CMakeCache.txt)

**Comment by lRaulMN7** [comment]
OpenCV is build with python 2.7.16
Where can I force it to be built with python3 ?

**Comment by Sunderlandkyl** [comment]
I'm not sure.
@adamrankin Do you have any insight into fixing this OpenCV build?

**Comment by lRaulMN7** [comment]
I solved the python thingy by instaling a previous version, now I have Qt related problems so I'm trying different versions as well.

All I have now are LINKED errors that I'm slowly fixing ... so I hope to end this up for tomorrow. Thanks anyways! Make sure you check the v5.00 I have mentioned yesterday which I'm pretty sure is a typo in the CMakes. 

I close the issue once I fix everything, just I case I ran out of ideas

**Comment by Sunderlandkyl** [comment]
The ITK issue was actually fixed last Wednesday (https://github.com/PlusToolkit/PlusBuild/commit/93e2dbbe6f7e105b98a2c03e6b8b52de59c7bd25).

What version of Qt are you using? I tend to use 5.10.1 or newer.

**Comment by adamrankin** [comment]
We don't enable python for OpenCV, if you want to, you'll have to set the project variables for OpenCV appropriately. You can check out [https://github.com/Slicer/SlicerOpenCV/blob/master/SuperBuild/External_OpenCV.cmake](External_OpenCV.cmake) for the correct variables.

OpenCV wraps a number of video backends, which one are you using? You can also pass settings to whichever backend you choose.

**Comment by lRaulMN7** [comment]
Okay finally! I had Anaconda messing up my environmental variables. I deleted it, installed Qt 5.12.2 and now I'm able to launch Plus Server Launcher. Time to code :) Thanks a lot for your patience @Sunderlandkyl  , @adamrankin !
