### ISSUE TITLE
volume reconstruction

### ISSUE THREAD

**Issue by zhaobingshuai** [PlusToolkit/PlusLib#562]
In the header area of ElbowUltrasoundSweep.mha, the format of the pose is as follows: including ProbeToTrackerTransform, ReferenceToTrackerTransform, StylusToTrackerTransform,

`Seq_Frame0000_ProbeToTrackerTransform = 0.853646 -0.501315 0.141319 257.956 -0.50173 -0.718613 0.481521 -52.6852 -0.13984 -0.481953 -0.864966 25.5612 0 0 0 1
Seq_Frame0000_ProbeToTrackerTransformStatus = OK
Seq_Frame0000_ReferenceToTrackerTransform = -0.61495 0.0616122 -0.786156 307.759 -0.148385 -0.988175 0.0386253 -88.1807 -0.77448 0.140406 0.61682 -54.9176 0 0 0 1
Seq_Frame0000_ReferenceToTrackerTransformStatus = OK
Seq_Frame0000_StylusToTrackerTransform = -0.222281 -0.546831 0.807197 256.332 0.824925 -0.546787 -0.143254 368.738 0.519701 0.634035 0.572635 35.5851 0 0 0 1
Seq_Frame0000_StylusToTrackerTransformStatus = OK
Seq_Frame0000_Timestamp = 232.542071
Seq_Frame0000_ImageStatus = OK`

but after converting the 6DOF pose data into the 4*4 homogeneous coordination transformation matrix,Which kind of transform should this matrix correspond to? (ProbeToTrackerTransform or ReferenceToTrackerTransform or StylusToTrackerTransform?)

This is the header area of my .mha file
![微信截图_20190606182631](https://user-images.githubusercontent.com/38325759/59026455-035f8700-8889-11e9-9ea0-91ef355bd767.png)

This is my command.bat for Volume Reconstructor:
`C:\Users\11864\PlusApp-2.6.0.20190221-Win64\bin\VolumeReconstructor.exe --config-file="C:\Users\11864\Desktop\IgtTest\ElbowUltrasoundSweep-VolRec.xml" --image-to-reference-transform=ImageToReference --source-seq-file="C:\Users\11864\Desktop\15.mha" --output-volume-file="C:\Users\11864\Desktop\15-volume.mha"`

Here are the problems I encountered when using the volume reconstruction tool in Plus:
![微信截图_20190606165403](https://user-images.githubusercontent.com/38325759/59022144-c80c8a80-887f-11e9-86ca-e55b93f5f378.png)
![微信截图_20190606165709](https://user-images.githubusercontent.com/38325759/59022145-c8a52100-887f-11e9-9ed4-14929dff0434.png)
![微信截图_20190606200017](https://user-images.githubusercontent.com/38325759/59031269-c51c9480-8895-11e9-9fd1-879793aea32c.png)

**Comment by Sunderlandkyl** [comment]
There seems to be something wrong with your mha file.
Could you upload it somewhere?

**Comment by zhaobingshuai** [comment]
I put my .mha file, pose data.txt, the configuration file .xml, the .bat file for volume reconstruction, etc. are uploaded to OneDrive(https://1drv.ms/u/s!AnM4i3s95l5gggh2YY4PTQYNkPTv?e=whAdJ1). According to your colleague's suggestion, I will first paste the contents of the .txt into the header area of the .mha file. Run the .bat program on the PLUS command line. At this time I encountered the above error reminder.
Thank you for your help！

**Comment by Sunderlandkyl** [comment]
You need to update your header to look like this:
[header.txt](https://github.com/PlusToolkit/PlusLib/files/3262569/header.txt)

I only changed two things:
- Added: UltrasoundImageOrientation = MFA
- Added the Seq_ from the txt to the mha

**Comment by zhaobingshuai** [comment]
Hi，Sunderlandkyl. I did write MFA as MF. This is a very low-level mistake. Thank you very much for pointing me out. I have updated  my header.
I have a tracker attached to the ultrasound probe. This tracker can collect the 6DOF of the probe in real time. I saved the 6DOF pose data and converted it into a 4*4 homogeneous transformation transformation matrix, but I don't know the matrix. Which one of the following corresponds?
a.Seq_Frame0000_ProbeToTrackerTransform
b.Seq_Frame0000_ReferenceToTrackerTransform
c.Seq_Frame0000_StylusToTrackerTransform

**Comment by Sunderlandkyl** [comment]
The transform of the ultrasound probe to the tracker is "a": ProbeToTrackerTransform

**Comment by zhaobingshuai** [comment]
Still giving an error, what is the reason? I hope to get your specific advice. Thank you.
![微信截图_20190607013813](https://user-images.githubusercontent.com/38325759/59053965-36277080-88c5-11e9-8f57-fb8e7cec475b.png)
This is my configuration file：
![q](https://user-images.githubusercontent.com/38325759/59054108-90283600-88c5-11e9-924e-1af3bb509507.png)

**Comment by Sunderlandkyl** [comment]
Why did you change your config file? You don't need to provide Probe to Tracker, just Image to Probe in the config file.
I was able to perform a complete volume reconstruction using the files that you sent me by only editing the  header of the mha.

This is the file that I created:
https://www.dropbox.com/s/xi2ipyhua5q85yl/1.mha?dl=0

**Comment by zhaobingshuai** [comment]
Thank you very much for your suggestion. Can you send me your volume reconstruction configuration file and command script?
In addition，

> I was able to perform a complete volume reconstruction using the files that you sent me by only editing the header of the mha.

My pose data contains 2294 poses, and there are only 187 poses in the header area of your .mha file after volume reconstruction.How did you edit the header of the mha? Have you used the pose data .txt that I sent you? Thanks @Sunderlandkyl  : ）
![image](https://user-images.githubusercontent.com/38325759/59061245-9aeac700-88d5-11e9-91ab-48250d01f666.png)

**Comment by Sunderlandkyl** [comment]
Hmm... I thought that I copied the poses from pose_data.txt, but I must have copied them from another mha file.

I used the same config file and script that is in one drive.

One second, I'll test it with the updated pose data.

**Comment by Sunderlandkyl** [comment]
There are 2294 poses, but the DimSize only specifies 315 images.
How many tracked images are there supposed to be?

**Comment by Sunderlandkyl** [comment]
Another thing is that the frame number uses zero based indexing, so the first frame should be Seq_Frame0000, not Seq_Frame0001.

**Comment by zhaobingshuai** [comment]
> There are 2294 poses, but the DimSize only specifies 315 images.
> How many tracked images are there supposed to be?

The acquisition frequency of my tracker is much higher than the acquisition frequency of ultrasound images. There should be 315 sets of tracked images. Do you think I should sample in the pose data?



> Another thing is that the frame number uses zero based indexing, so the first frame should be Seq_Frame0000, not Seq_Frame0001.

I have realized this error, I have just corrected it, and I am still very grateful for your reminder.

**Comment by Sunderlandkyl** [comment]
Yes, the transforms and the images should be synchronized.

**Comment by Sunderlandkyl** [comment]
I've managed to perform volume reconstruction on the images you sent me.

I duplicated the first transform with index 0000 and deleted poses so that the number of poses matches the number of images.

I also reduced the spacing of the reconstructed volume in the config file to "1 1 1" (I was running out of memory.)

Here is a link: https://www.dropbox.com/sh/494sfsvrxiqokm4/AABQ08qzh4HVIlcAkaruXX_3a?dl=0

Let me know how this goes.

**Comment by zhaobingshuai** [comment]
I am very happy, and finally have hope under your guidance. Thank you. This is the result of my volume reconstruction. My phantom is two small balls, but I can't see them at all. I guess the volume reconstruction needs interpolation, but I won't modify the configuration file. (I just tried to add the interpolation option in the configuration file, but I got an error), I hope you can help me modify the configuration file for better reconstruction.

![微信截图_20190607051418](https://user-images.githubusercontent.com/38325759/59067078-3c2c4a00-88e3-11e9-9701-1ab4b7835a74.png)

This is the .mha file that contains the correct pose data before the volume reconstruction.
https://1drv.ms/u/s!AnM4i3s95l5ggg3XKjkMotz5iRq5?e=2WPYLv

This is the result of performing a volume reconstruction.
https://1drv.ms/u/s!AnM4i3s95l5ggg6ZRIO_R89jPmcU?e=1GdJLb

**Comment by zhaobingshuai** [comment]
Hello, I encountered a problem when I repeated the other .mha files as described above.
![111234](https://user-images.githubusercontent.com/38325759/59074037-50307580-88fc-11e9-889e-903fc8a08bfa.png)
This is another set of data:
https://1drv.ms/f/s!AnM4i3s95l5gghXdX_mdCplVhh8z

I need your help, I hope I didn't bother you, thank you.

**Comment by zhaobingshuai** [comment]
Sincerely thank you for your help, I have successfully solved the problem.
