### ISSUE TITLE
volume reconstraction result is error

### ISSUE THREAD

**Issue by zhaobingshuai** [PlusToolkit/PlusLib#568]
hi, when i use the volume reconstration CLI of PLUS, my result of volume reconstration is error,Most of the translations I used when I used the ultrasound scan, but the results of the reconstruction showed that all the 2D images were pinched in the upper left corner, which is contradictory.
I want to know if you have encountered this kind of situation? Can you give me some advice? Thank you very much, I wish you a wonderful weekend.

this is the result of volume reconstrction:
![微信截图_20190624031614](https://user-images.githubusercontent.com/38325759/59980989-28e1e400-9630-11e9-8ce4-8c4271090dc6.png)

**Comment by Sunderlandkyl** [comment]
Can you upload your ultrasound sequence somewhere?

**Comment by zhaobingshuai** [comment]
@Sunderlandkyl ，hi！Still the previous mistake，when i use the volume reconstration CLI of PLUS，Most of the translations I used when I used the ultrasound scan, but the results of the reconstruction showed that all the 2D images were pinched in the upper left corner, which is contradictory. Hope you give me some advice, thanks!

![微信截图_20190628210434](https://user-images.githubusercontent.com/38325759/60353632-0c152a00-99fd-11e9-972a-1061dd1f2f75.png)
![微信截图_20190628210409](https://user-images.githubusercontent.com/38325759/60353634-0cadc080-99fd-11e9-941a-b4a8732a74b0.png)
![微信截图_20190628210351](https://user-images.githubusercontent.com/38325759/60353636-0cadc080-99fd-11e9-8814-66c0395da7e2.png)

https://1drv.ms/u/s!AnM4i3s95l5ggX9wX4YzQHV8kpty?e=266ipB
There are three files in this shared directory: 9-sample.txt is the pose data, 9.mha is the volume data before reconstruction, and 9-volome.mha is the volume data after reconstruction.

**Comment by ungi** [comment]
Hi. You only have ProbeToTracker transform saved in that sequence. The ultrasound images are in the Image coordinate system. You need to apply ImageToProbe, then ProbeToTracker transform on the ultrasound images to reconstruct in the Tracker coordinate system. Then, your volume will already look good. But probably you want to reconstruct in the Reference coordinate system (if you have a Reference position marker). For convenience, I usually add ImageToReference to the mha sequence before loading the sequence in Slicer for reconstruction. Then put Image on ImageToReference, so it gets reconstructed in the Reference coordinate system.
I hope this helps.

**Comment by zhaobingshuai** [comment]
Thank you very much, I can't tell you what ProbeToTracker | ImageToProbe | ImageToReference, when I use ultrasound scanning, I recorded 6DOF of all images, I converted them to 4*4 non-homogeneous rotation matrix, and finally based on The fixed format was added to the .mha file. When I first did this I got the results I wanted, but I don't understand why this time went wrong? Can you give me detailed steps? I can provide any data if I need it.

**Comment by zhaobingshuai** [comment]
please help me,thanks! @lassoan @Sunderlandkyl @ungi 😭😭😭

**Comment by ungi** [comment]
When we track an ultrasound probe, we usually record more 4x4 matrices for every image. Not just one. Multiple 4x4 matrices can be concatenated (multiplied) to move the ultrasound image to different coordinate systems. The matrix transformations are always called SomethingToOtherthing. Where Something and Otherthing are coordinate systems.
You could read this to have a better idea on what ImageToProbe is: http://perk-software.cs.queensu.ca/plus/doc/nightly/user/CommonCoordinateSystems.html
Other than ImageToProbe, you need ProbeToTracker, and typically TrackerToReference. Although you may get ProbeToReference matrix directly from the tracker (which would be the concatenation of ProbeToTracker and TrackerToReference).

It is quite hard to figure these out for every image, unless you record your data with PLUS. The fastest way for you to get a working system is probably to use PLUS for data recording. So all of these matrices can be saved correctly. Even if PLUS doesn't support your ultrasound machine, it is probably easier to add the support than figuring out how to make the recorded data compatible with PLUS and Slicer.

**Comment by zhaobingshuai** [comment]
When I used the ultrasound scan, I recorded the real-time pose of the probe. I didn't use an optical positioning device or other additional tracking system, so I don't have a tracker. And the object I scanned was my carotid artery. In this case, what does Reference specifically mean? I guess if I should change Seq_Frame0000_ProbeToTrackerTransform to Seq_Frame0000_ImageToProbeTransform? I will try it right away.

**Comment by zhaobingshuai** [comment]
Hello, I have encountered some problems with the recent use of plus, my pose data is shown below, starting from the upper left corner are: x, y, z, pitch, yaw, roll curve, the trajectory in space is A curve (up and down mirroring of the sinusoid).
![1-z10-0-0](https://user-images.githubusercontent.com/38325759/63156925-653a2b00-c048-11e9-878b-d679bad58fce.png)
The result of my reconstruction is not expected, it is almost straight, and the results are as follows:
![image](https://user-images.githubusercontent.com/38325759/63156993-8c90f800-c048-11e9-981f-59c5a9582149.png)
My profile:
[ElbowUltrasoundSweep-VolRec2.zip](https://github.com/PlusToolkit/PlusLib/files/3508891/ElbowUltrasoundSweep-VolRec2.zip)
Input file:
[zhaobingshuai_input.zip](https://github.com/PlusToolkit/PlusLib/files/3508876/zhaobingshuai_input.zip)
Output file：
[result.zip](https://github.com/PlusToolkit/PlusLib/files/3508881/result.zip)
Thank you very much for your help and look forward to your reply.

**Comment by Sunderlandkyl** [comment]
I replayed the data that you sent. (I would recommend adding a "Kinds = domain domain list" line underneath the DimSize = 100 100 1000)

The motion that is recorded in the file is what you see in the reconstruction. The probe to tracker transform moves back and forth along a line.

Are you sure that you put the correct transforms in the mhd?

**Comment by zhaobingshuai** [comment]
Have you seen my MHD file? I think it is correct. It needs to be explained that because the change in the Z direction is not obvious, I have expanded Z by ten times. I suspect that the parameters of the rebuilt configuration file are incorrect. Do you know where the problem might be? Thank you for your help.

**Comment by Sunderlandkyl** [comment]
I don't know what the problem is.

As long as the transforms in your MHD and the ImageToProbe transform specified in your config file are correct, I cannot see any other issues.

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
