### ISSUE TITLE
Question/Problem displaying US Image. 

### ISSUE THREAD

**Issue by lRaulMN7** [PlusToolkit/PlusLib#570]
Hello. Today I tried to attach my US Image via streaming to the probe tracker.

As far as I know, this is accomplished by doing a fCal to calculate the matrix transformation, however, to do a fCal I need to perform a real calibration with a fCal phantom. And I don't want to do that yet, so I thought I should be able to set the image just where the tracker is.

Therefore I tried with this .xml setup:

[PlusConf_NDIAurora_OpenCV.txt](https://github.com/PlusToolkit/PlusLib/files/3326309/PlusConf_NDIAurora_OpenCV.txt)

In slicer, I get the two references and the Image. Then I create this hierarchy:

```
Scene
  ▸ReferenceToModel <- I create this one by hand in slicer.
     ▸NeedleToReference
          ▸NeedleModel
     ▸ProbeToReference
          ▸Image_Probe 
```

The needle works correctly, but the US Image is displayed as a line ( similar to https://github.com/PlusToolkit/PlusLib/issues/399 ).

In that issue, you guys told him to use Volume Reslice Driver and set the Driver to Transverse. I'll try that tomorrow and will tell the results, but why is this needed? Do I have to find the ImageToProbe reference by doing a fCal obligatory? And also, if I don't want to apply any matrix transformation, leaving the Identity Matrix is ok, right?

**Comment by Sunderlandkyl** [comment]
The volume reslice driver aligns the image plane in the slice to the ultrasound image plane in real time.
This means that you can move the probe and the slice view will follow.

You can calculate ImageToProbe many different ways ([see U-31 here for an example](http://www.slicerigt.org/wp/user-tutorial/)). If you don't perform the calibration, or if you set the matrix as identity, then the location of the image in 3D Slicer will not be accurate.

**Comment by lRaulMN7** [comment]
Oh, ok! I understand it now, and it works :) Thanks!
