### ISSUE TITLE
Extra header fields retained when switching between saving out .seq.mhd and .seq.nhdr

### ISSUE THREAD

**Issue by RMR54** [PlusToolkit/PlusLib#574]
When Virtual Capture is used for capture (vtkPlusWinProbeVideoSource in this case), using `OpenFile("Test.seq.mhd")`, `SetEnableCapturing(true)`,  record for a couple seconds,  `SetEnableCapturing(false)`, and `CloseFile()`, and then the same Virtual capture is used for recording again, using the same order of operations, with the difference in file type, i.e. `OpenFile("Test.seq.nhdr");`, then the file header includes MHD fields as well( such as "AnatomicalOrientation", "DimSize"):
![image](https://user-images.githubusercontent.com/8135181/61060643-dbec6480-a3c8-11e9-9ea9-d2fe9d69a1ff.png)

If we started Plus server, and then saved out as ".seq.nhdr" first, then the header appears normal:
![image](https://user-images.githubusercontent.com/8135181/61060841-31287600-a3c9-11e9-93bb-d116c61daed7.png)

Similarly, if we save out as .seq.nhdr, and then save out as .seq.mhd instead, then the .seq.mhd has additional headers (that's typically seen in .seq.nhdr, such as "data file", "space dimension"):
![image](https://user-images.githubusercontent.com/8135181/61061207-d2173100-a3c9-11e9-939b-33cbd831c666.png)

**Comment by jamesobutler** [comment]
Yes, I can independently confirm that after recording one and then recording a second of a different type results in the second having headers of both types.

**Comment by adamrankin** [comment]
This gets mildly complicated. When switching between file types, do we drop fields and re-add defaults, or try to copy fields over to their MHD/NRRD equivalent...

**Comment by jamesobutler** [comment]
@adamrankin What fields were you thinking might need to be copied over instead of using defaults?  

I would think the writer would set up the header fields from a clean start whenever start recording command is called instead of keeping some reference to the header fields of the previous recording.

**Comment by jamesobutler** [comment]
@Sunderlandkyl Do you have any input on this issue? The PlusRemote module within the SlicerOpenIGTLink extension doesn't handle this case so it allows to record+save a metaimage type and then record+save out a nrrd type, but the nrrd type will have header information of both types.

**Comment by Sunderlandkyl** [comment]
Does this issue cause any problems, besides the fact that it clutters up the header?

**Comment by jamesobutler** [comment]
Yes, so the nhdr file with metaimage header fields results in the volume not loading into Slicer. It can't parse the "AnatomicalOrientation: RAI" field from the metaimage file.
```
ReadImageInformation: Error reading C:/Users/JamesButler/PlusApp-2.9.0.20190708-Win64/data/Recording.igs.nhdr:
[nrrd] nrrdLoad: trouble reading "C:/Users/JamesButler/PlusApp-2.9.0.20190708-Win64/data/Recording.igs.nhdr"
[nrrd] nrrdRead: trouble
[nrrd] _nrrdRead: trouble reading NRRD file
[nrrd] _nrrdFormatNRRD_read: trouble parsing NRRD field identifier from in "AnatomicalOrientation: RAI"
[nrrd] _nrrdReadNrrdParseField: failed to parse "AnatomicalOrientation" as field identifier



Algorithm vtkITKArchetypeDiffusionTensorImageReaderFile(0000019E905AB180) returned failure for request: vtkInformation (0000019E97573E10)
  Debug: Off
  Modified Time: 350483
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_INFORMATION
  FORWARD_DIRECTION: 0
  ALGORITHM_AFTER_FORWARD: 1




ReadImageInformation: Error reading C:/Users/JamesButler/PlusApp-2.9.0.20190708-Win64/data/Recording.igs.nhdr:
[nrrd] nrrdLoad: trouble reading "C:/Users/JamesButler/PlusApp-2.9.0.20190708-Win64/data/Recording.igs.nhdr"
[nrrd] nrrdRead: trouble
[nrrd] _nrrdRead: trouble reading NRRD file
[nrrd] _nrrdFormatNRRD_read: trouble parsing NRRD field identifier from in "AnatomicalOrientation: RAI"
[nrrd] _nrrdReadNrrdParseField: failed to parse "AnatomicalOrientation" as field identifier



Algorithm vtkITKArchetypeImageSeriesVectorReaderSeries(0000019E905A9480) returned failure for request: vtkInformation (0000019E97569AA0)
  Debug: Off
  Modified Time: 351972
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_INFORMATION
  FORWARD_DIRECTION: 0
  ALGORITHM_AFTER_FORWARD: 1




ReadImageInformation: Error reading C:/Users/JamesButler/PlusApp-2.9.0.20190708-Win64/data/Recording.igs.nhdr:
[nrrd] nrrdLoad: trouble reading "C:/Users/JamesButler/PlusApp-2.9.0.20190708-Win64/data/Recording.igs.nhdr"
[nrrd] nrrdRead: trouble
[nrrd] _nrrdRead: trouble reading NRRD file
[nrrd] _nrrdFormatNRRD_read: trouble parsing NRRD field identifier from in "AnatomicalOrientation: RAI"
[nrrd] _nrrdReadNrrdParseField: failed to parse "AnatomicalOrientation" as field identifier



Algorithm vtkITKArchetypeImageSeriesVectorReaderFile(0000019E905AB180) returned failure for request: vtkInformation (0000019E97574B30)
  Debug: Off
  Modified Time: 352067
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_INFORMATION
  FORWARD_DIRECTION: 0
  ALGORITHM_AFTER_FORWARD: 1




ReadImageInformation: Error reading C:/Users/JamesButler/PlusApp-2.9.0.20190708-Win64/data/Recording.igs.nhdr:
[nrrd] nrrdLoad: trouble reading "C:/Users/JamesButler/PlusApp-2.9.0.20190708-Win64/data/Recording.igs.nhdr"
[nrrd] nrrdRead: trouble
[nrrd] _nrrdRead: trouble reading NRRD file
[nrrd] _nrrdFormatNRRD_read: trouble parsing NRRD field identifier from in "AnatomicalOrientation: RAI"
[nrrd] _nrrdReadNrrdParseField: failed to parse "AnatomicalOrientation" as field identifier



Algorithm vtkITKArchetypeImageSeriesScalarReader(0000019E905A9480) returned failure for request: vtkInformation (0000019E97574900)
  Debug: Off
  Modified Time: 352850
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_INFORMATION
  FORWARD_DIRECTION: 0
  ALGORITHM_AFTER_FORWARD: 1




ReadData: This is not a nrrd file


ReadData: Cannot read file as a volume of type DiffusionTensorVolume[fullName = C:/Users/JamesButler/PlusApp-2.9.0.20190708-Win64/data/Recording.igs.nhdr]
        Number of files listed in the node = 0.
        File reader says it was able to read 1 files.
        File reader used the archetype file name of C:/Users/JamesButler/PlusApp-2.9.0.20190708-Win64/data/Recording.igs.nhdr [reader 0th file name = C:/Users/JamesButler/PlusApp-2.9.0.20190708-Win64/data/Recording.igs.nhdr]
FileFormatError



ReadData: This is not a nrrd file


ReadData: Failed to instantiate a file reader


ReadData: Cannot read file as a volume of type Volume[fullName = C:/Users/JamesButler/PlusApp-2.9.0.20190708-Win64/data/Recording.igs.nhdr]
        Number of files listed in the node = 0.
        File reader says it was able to read 1 files.
        File reader used the archetype file name of C:/Users/JamesButler/PlusApp-2.9.0.20190708-Win64/data/Recording.igs.nhdr [reader 0th file name = C:/Users/JamesButler/PlusApp-2.9.0.20190708-Win64/data/Recording.igs.nhdr]
FieFormatError
```

**Comment by adamrankin** [comment]
Ok, I'll look into clearing it on switch.

**Comment by adamrankin** [comment]
> I would think the writer would set up the header fields from a clean start whenever start recording command is called instead of keeping some reference to the header fields of the previous recording.

I think it does that, but it doesn't do a clean start. I'll test that out now.

**Comment by adamrankin** [comment]
Pull latest IGSIO and try again.

**Comment by adamrankin** [comment]
See https://github.com/IGSIO/IGSIO/commit/60ebb448dcfdbb4fcc8c1cb0bc5e2033b1409d48

**Comment by RMR54** [comment]
Thanks @adamrankin! The headers fields are no longer carried over when switching file types on record.
