### ISSUE TITLE
RealSense Camera Maxed out at 15fps in Plus Server

### ISSUE THREAD

**Issue by nathanbmnt** [PlusToolkit/PlusLib#577]
Hello,
I am trying to stream my Intel RealSense D415 camera into slicer through Plus Server. In my .xml Plus Device settings file I have FrameSize = "1920 1080" and FrameRate = "30", yet the camera still streams into slicer at 15fps (or at least the Virtual Capture saves at 15fps). I have slicer connected to Plus Server through openIGTLinkIF.

I have also lowered the resolution to 960 by 540, and still get 15fps.

Here is the device settings .xml file I used:
[PlusDeviceSet_Server_IntelRealSenseVideo_D415.txt](https://github.com/PlusToolkit/PlusLib/files/3422668/PlusDeviceSet_Server_IntelRealSenseVideo_D415.txt)

Is there a workaround for this issue?

**Comment by jamesobutler** [comment]
> (or at least the Virtual Capture saves at 15fps)

It appears you are on the right track. VirtualCapture has a RequestedFrameRate default of 15 FPS. Try specifying `RequestedFrameRate="30"` in the VirtualCapture section of your config.
https://github.com/PlusToolkit/PlusLib/blob/99a41bb4a34ee5a7b1d0d6307aee4442e19c7976/src/PlusDataCollection/VirtualDevices/vtkPlusVirtualCapture.cxx#L41

It appears that the VirtualCapture documentation page is out of date from what is actually specified in the code. http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceVirtualCapture.html
See #579 where I've issued a PR to fix the documentation to reflect what the code is specifying.

**Comment by nathanbmnt** [comment]
Thanks, adding the RequestedFrameRate variable to my virtual capture device did the trick.
