### ISSUE TITLE
Editing .mha files recorded with PLUS

### ISSUE THREAD

**Issue by prash-p** [PlusToolkit/PlusLib#578]
I've been recording ultrasound sequences using PLUS, which saves them as .mha files. For some reason that I can't figure out, the spacing of the pixels is saved incorrectly (1mm in all directions), and I want to fix this in the .mha file

However on this [page](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/FileSequenceFile.html), it mentions that editing .mha files is 'not convenient'. Is it possible to this at all? I tried using Sublime but this corrupts the image information as mentioned in the above page.

EDIT: I realize it's also possible to edit the spacing in Slicer, but I also wanted to change NDims from 3 to 4, which I don't think is possible in Slicer?

**Comment by adamrankin** [comment]
You can open them with Notepad++ on Windows, not sure of other OS's

**Comment by prash-p** [comment]
Thanks, it works!
