### ISSUE TITLE
PLUS with Optitrack Prime13

### ISSUE THREAD

**Issue by BGWH** [PlusToolkit/PlusLib#580]
Dear all,

I tried to use SliceIGT and PLUS (PlusApp-2.9.0.20190802-Win64) in combination with Optitrack Prime 13 cameras (Motive version 2.0.0). To design the configuration file I have followed this guide:
http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceOptiTrack.html

So I have stored a .xml config file as well as two RigidBodyFiles.

According to the log files, the server started successfully and I see the transforms in the I/O configuration (in OpenIGTLinkIF).
But in IGT/PlusRemote I cannot select a 'Capture device ID' and a 'Reconstructor device ID' in the dropdown list (it is empty).

Does anyone know if PLUS is compatible with the Optitrack Prime13 or just with Duo/Trio?

Best,
Bernhard

**Comment by lassoan** [comment]
Yes, PLUS is compatible with the Optitrack Prime13, too. Let us know if you still have trouble setting it up.

**Comment by Sunderlandkyl** [comment]
Can you attach your config file?

**Comment by BGWH** [comment]
Dear all,

thanks for your answer.
I have attached the config file (packed in a zip file as I could not attach a xml file).
Actually I have figured out that streaming data from the Prime13 works perfectly fine. The only issue is that recording data with 'Plus Remote' does not work as the list of 'Capture device ID' (in Plus Server Control) is always empty, hence, I cannot start recording. I tried it with replaying data from the Slicer test data and the list was also empty.

[PlusDeviceSet_Server_OptiTrack_AddMarkersUsingTRA_Prime13_Test.zip](https://github.com/PlusToolkit/PlusLib/files/3473277/PlusDeviceSet_Server_OptiTrack_AddMarkersUsingTRA_Prime13_Test.zip)

Best,
Bernhard

**Comment by Sunderlandkyl** [comment]
You need to add a capture device to your config file (http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceVirtualCapture.html)

Something like:
```
    <Device
      Id="CaptureDevice"
      Type="VirtualCapture"
      BaseFilename="RecordingTest.igs.mha"
      EnableCapturingOnStart="FALSE" >
      <InputChannels>
        <InputChannel Id="TrackerStream" />
      </InputChannels>
    </Device>
```

**Comment by BGWH** [comment]
Great! Thanks a lot!

Best,
Bernhard
