### ISSUE TITLE
Support needed

### ISSUE THREAD

**Issue by EL-SHREIF** [PlusToolkit/PlusLib#582]
I need to use plus to make a 3D  volume reconstructing and I have a custom OCT that used by a matlab or cpp software. I got the frames one by one in the code in matlab then in the cpp one and I want to find a way that I can send this data to Plus to be able to view it in the Slicer 3D.

**Comment by lassoan** [comment]
Probably the easiest is to send the image frames via OpenIGTLink protocol directly to Slicer.

**Comment by EL-SHREIF** [comment]
I tried but I have many errors in building the OpenIGTLink library. I don't know why.
