### ISSUE TITLE
Ultrasound Simulation Thickness?

### ISSUE THREAD

**Issue by Lyla-M** [PlusToolkit/PlusLib#583]
Hi,
I'm developing an app using PLUS ultrasound simulator for training purpose. It would be useful to train the in-plane needle-beam alignment technique. The limitation is that real ultrasound probe have a fairly thick image plane, but PLUS simulation has a very thin plane, so its really hard to align the needle with image plane to be able to see the needle. Is there any solution for this in-plane approach? 
Thank you! 
Lyla

**Comment by ungi** [comment]
Hi,
I think ultrasound beam width is not featured in the current simulator. But you could trick the current simulator by adding concentric tube models around the needle with similar acoustic properties as the needle. That way something like the needle will show up in the image as you are approaching the needle. You would not show those tubes in view to the user, they would just exist in the simulator. I haven't tried this, but it should be better than just a needle model.

**Comment by Lyla-M** [comment]
> Hi,
> I think ultrasound beam width is not featured in the current simulator. But you could trick the current simulator by adding concentric tube models around the needle with similar acoustic properties as the needle. That way something like the needle will show up in the image as you are approaching the needle. You would not show those tubes in view to the user, they would just exist in the simulator. I haven't tried this, but it should be better than just a needle model.

Thank you for you suggestion Tamas! I would give it a try. However... that would limit the task to in-plane only right? If you decide to do out of plane approach, the needle would look unrealistic ?

**Comment by ungi** [comment]
Yes. It would create a halo around the needle in images close to perpendicular to the needle. Maybe there is good balance in acoustic parameters that will not make it too disturbing in out-of-plane images, but still usable in in-plane images. Also, make the original needle thicker than real by a few millimeters. That won't hurt, but compensates for some of the beam width.

**Comment by lassoan** [comment]
> The limitation is that real ultrasound probe have a fairly thick image plane

Vascular probes that are focused correctly have beam thickness is about 1-2mm at usual needle insertion depths. If you make the needle model 1-2mm then the difference compared to real conditions will not be huge.

You may also consider displaying the needle as a model in Slicer. You can choose to display the needle as projection. By setting an appropriate color table, you can specify what distance you want the needle to appear (you can set RGBA value for any distance from the slice plane).

**Comment by Lyla-M** [comment]
> Yes. It would create a halo around the needle in images close to perpendicular to the needle. Maybe there is good balance in acoustic parameters that will not make it too disturbing in out-of-plane images, but still usable in in-plane images. Also, make the original needle thicker than real by a few millimeters. That won't hurt, but compensates for some of the beam width.

Oh I see what you mean. Ok I will test this. Thank you so much!!!

**Comment by Lyla-M** [comment]
> > The limitation is that real ultrasound probe have a fairly thick image plane
> 
> Vascular probes that are focused correctly have beam thickness is about 1-2mm at usual needle insertion depths. If you make the needle model 1-2mm then the difference compared to real conditions will not be huge.
> 
> You may also consider displaying the needle as a model in Slicer. You can choose to display the needle as projection. By setting an appropriate color table, you can specify what distance you want the needle to appear (you can set RGBA value for any distance from the slice plane).

It was my clinician who said it's a too difficult to find the needle (in plane) right now. So he asked me to improve it.
That sounds like a really interesting approach. I'm currently running my cellphone app developed in Unity and PLUS is running on my laptop. So I'm not using slicer at the moment. But it's nice to have a backup solution. Thank you Andras!
