### ISSUE TITLE
Claron Microntracker fails to open in 2.8 binary

### ISSUE THREAD

**Issue by burnhamd** [PlusToolkit/PlusLib#585]
In the 2.8 build of Plus-App I am getting an error of

Connection failed!

Please select another device set and try again!

on the same computer with the same .ini and xml settings, I have a successful connection with the 2.6 version.

**Comment by Sunderlandkyl** [comment]
Can you attach config + log files?

**Comment by burnhamd** [comment]
[PlusDeviceSet_Server_MicronTrackerText.txt](https://github.com/PlusToolkit/PlusLib/files/3517048/PlusDeviceSet_Server_MicronTrackerText.txt)
[081919_134915_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/3517050/081919_134915_PlusLog.txt)

**Comment by Sunderlandkyl** [comment]
Can you change your log level to Trace, try again, and then upload the resulting log file?

**Comment by burnhamd** [comment]
[082119_150345_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/3526889/082119_150345_PlusLog.txt)

**Comment by Sunderlandkyl** [comment]
The 32-bit package of Plus is compiled with MTC 3.7.6.8.

What version of MicronTracker are you using?
Are you able to run the Claron demo application?

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
