### ISSUE TITLE
bad frame rate for USB capture frame Grabber

### ISSUE THREAD

**Issue by kristiii** [PlusToolkit/PlusLib#588]
I am using USB Capture HDMI Gen 2 (https://www.magewell.com/products/usb-capture-hdmi-gen-2) to capture the screen of an Ultrsound machine for further image processing! I get bad frame rate and image PPI. how can I improve that using PLUS config file? Please refer the config files in the PLUS website! http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceMicrosoftMediaFoundation.html

Thank you!
chriss

**Comment by adamrankin** [comment]
First, you can adjust `FrameSize="640 480"` to whatever resolution your device is currently set to.

As per frame rate, I'm not sure. If `AcquisitionRate="30"` is set, then you should get 30FPS. How are you viewing the images?

**Comment by kristiii** [comment]
Thanks for your response! You are right about the FrameSize. I was confused because "USB Capture Utility" software was showing two sets of FrameSize values. I am capturing the screen of the US machine, then using PLUS clipping the ROI, only the scanning area!
I finally got it to work. Thanks for the tip!
