### ISSUE TITLE
connecting ultrasonix machine to a pc

### ISSUE THREAD

**Issue by pctlr75** [PlusToolkit/PlusLib#589]
Hi everyone,
I have the following configuration: one ultrasonix us which is connected with an ethernet wire to a pc. My goal is to transfer us probe images to my main pc. I have installed PlusServer on us machine.
Which software should I install on the main pc to visualize us images? But I do not want to use 3d Slicer...
Can I use plusToolKit?
Or can I develop my own little software to perform this operation?
Thank you for your answer!

**Comment by lassoan** [comment]
> But I do not want to use 3d Slicer...

The obvious answer is to use 3D Slicer. Why would you not use 3D Slicer? What would you like to achieve?

**Comment by pctlr75** [comment]
My final goal is to "link" the ultraSonix with my tracking system, which is a fusionTrack. And I saw that, in plusToolKit, ultraSonix and fusionTrack were not compatible.
This is why I wanted to develop my own app in order to bind these two devices.

**Comment by adamrankin** [comment]
Yes, you can view images using fCal, which is a small app in the PlusApp repository.

**Comment by pctlr75** [comment]
> Yes, you can view images using fCal, which is a small app in the PlusApp repository.

Yup, but is fCal compatible with both ultraSonix and fusionTrack from Atracsys?

**Comment by adamrankin** [comment]
Ah, I see the download packages.

My recommendation is to have the following setup.

1. Install both Ultrasonix ([5.7](http://perk-software.cs.queensu.ca/plus/packages/nightly/PlusApp-2.9.0.20190814-Ultrasonix-5.7-Win32.exe), [6.1](http://perk-software.cs.queensu.ca/plus/packages/nightly/PlusApp-2.9.0.20190814-Ultrasonix-6.1-Win32.exe)) and [FusionTrack](http://perk-software.cs.queensu.ca/plus/packages/nightly/PlusApp-2.9.0.20190814-fusionTrack-Win64.exe) packages. Change installation folder of one to be able to install both at the same time.
1. Run PlusServer from each, each connecting to their respective device. Modify the config file to make sure the server ports don't conflict.
1. Create a new PlusServer config file, with a [OpenIGTLink tracker device](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceOpenIGTLinkTracker.html) and a [OpenIGTLink imaging device](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceOpenIGTLinkVideo.html).
1. In the same config file, create a [virtual mixer device](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceVirtualMixer.html) to merge the video and tracker stream.
1. In that same config file, create a third PlusServer on a third port to stream the output of the mixer device to any OpenIGTLink client (Slicer, Plus, your own)

**Comment by adamrankin** [comment]
You will introduce a bit of "network" lag, but with parameter tuning, this can be very low as it's all running on the same machine.

**Comment by pctlr75** [comment]
Ok, I'll try your solution. I may come back to ask extra technical questions...
Thank you for your help!

**Comment by lassoan** [comment]
Yes, running multiple PlusServers should work. You can orchestrate starting/stopping multiple Plus servers (even on remote computers) using PlusServerLauncher and Slicer.
