### ISSUE TITLE
Recommend a camera and the theory keywords?

### ISSUE THREAD

**Issue by timeanddoctor** [PlusToolkit/PlusLib#590]
Dear Professor.

I want to search some papers and study the theory of using two-dimensional code to navigate? Could you recommend a web camera(shopping) and any information, such as keywords or papers? 

Thank you.

**Comment by adamrankin** [comment]
> theory of using two-dimensional code to navigate

I'm not quite sure what you mean here. Do you mean [SLAM](https://en.wikipedia.org/wiki/Simultaneous_localization_and_mapping)?

**Comment by timeanddoctor** [comment]
I am sorry...
What I mean is traking based on webcam and marker which discreabled on [here](https://discourse.slicer.org/t/webcam-based-marker-tracking-is-available-in-slicer-now/565)

**Comment by timeanddoctor** [comment]
The keywords is "Optical Marker Tracker"?

**Comment by adamrankin** [comment]
No, ignore SLAM, I didn't know what you were looking for.

**Comment by adamrankin** [comment]
You could read this: http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceOpticalMarkerTracker.html

More generally:
https://en.wikipedia.org/wiki/Positional_tracking#Tracking_With_Markers
