### ISSUE TITLE
Using Blackmagic

### ISSUE THREAD

**Issue by MEDLab-ImageGuidance** [PlusToolkit/PlusLib#591]
Hi,

I am trying to build Plus Toolkit with Blackmagic. After cloning and create an project with CMake. I build this project and get the following error:

> 8>CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
8>  DeckLink SDK not found.  Please set DECKLINK_SDK_ROOT to the root folder of
8>  your DeckLink SDK install.  (missing: DeckLinkSDK_PATH
8>  DeckLinkSDK_INCLUDE_DIR)
8>Call Stack (most recent call first):
8>  C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
8>  C:/P/bmFA/PlusBuild/Modules/FindDeckLinkSDK.cmake:136 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
8>  src/PlusDataCollection/CMakeLists.txt:587 (FIND_PACKAGE)
8>
8>
8>-- Configuring incomplete, errors occurred!
8>See also "C:/P/bmFA/PlusB-bin/PlusLib-bin/CMakeFiles/CMakeOutput.log".
8>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(220,5): error MSB6006: "cmd.exe" exited with code 1.

Let me tell you my configurations:
I am using Microsoft Visual Studio 2019 and Qt5.12.3. Could the Microsoft Visual Studio be the problem? Also, I am using Blackmagic Decklink SDK 11.2 and I am doing all of this for a Windows machine.
I state __header_found_ as "C:\BM-DL-SDK-11.2\Win\include\DeckLinkAPI.idl" and all I got are these errors in the above.

**Comment by MEDLab-ImageGuidance** [comment]
Hi again, I successfully built Plus with Blackmagic, I have just edited the path of the sdk file to the FindDeckLinkSDK.cmake file, now it looks like that

```
FIND_FILE(_header_found
    ${__include_file}
    PATHS ${DECKLINK_SDK_ROOT}
          $ENV{DECKLINK_SDK_DIR} 
          $ENV{BLACKMAGIC_SDK_DIR} 
          $ENV{DECKLINK_DIR} 
          $ENV{BLACKMAGIC_DIR}
          # Plus specific paths to check
          "C:/P/bmdk/SDK"
          "../../VASSTTools/BlackmagicDeckLinkSDK-11.2"
          "../../PLTools/BlackmagicDeckLinkSDK-11.2"
          "../VASSTTools/BlackmagicDeckLinkSDK-11.2"
          "../PLTools/BlackmagicDeckLinkSDK-11.2"
    PATH_SUFFIXES ${_platform}/include/
   )
```

in my case the edited line was that:
```
"C:/P/bmdk/SDK"
```

**Comment by lassoan** [comment]
Note that you don't need to edit the path hints but instead follow instructions that CMake displayed in the configuration error message: "Please set DECKLINK_SDK_ROOT to the root folder of your DeckLink SDK install" (set DECKLINK_SDK_ROOT CMake variable).

**Comment by MEDLab-ImageGuidance** [comment]
Thanks for your help Mr. Lasso.
