### ISSUE TITLE
Broadcasting USB camera

### ISSUE THREAD

**Issue by caioath** [PlusToolkit/PlusLib#595]
Hello

I'm trying to broadcast a composite tracker and video stream from a usb webcam through Plus Server to 3D Slicer, but although I change the CaptureDeviceId number (1, 2 etc), I always get the image from the integrated Webcam (instead of USB video camera).
When I disable the integrated Webcam (Windows Device Manager), Plus server does not connect (Connection failed error). On that situation I can get the USB webcam video on Camera app.

Thank you

Caio

![image](https://user-images.githubusercontent.com/48572581/64483691-d12d3080-d1bb-11e9-841a-ccea9ad0c8f9.png)

**Comment by adamrankin** [comment]
I'll test with multiple devices.

**Comment by adamrankin** [comment]
Hmmm, I plug two webcams in and I am able to switch between them using the device id.

What is the make and model of your webcam, are you able to build Plus in debug to investigate with me?

**Comment by caioath** [comment]
I'm using a generic 2M Webcam [(like this )](https://www.ebay.com/itm/HDMI-HD-1080P-Endoscopy-Camera-Endoscope-Borescope-True-1200TVL-Storz-Wolf/283065608388?hash=item41e80668c4:g:uGQAAOSwh79bAyH5).

I'm not able to build Plus, lack of knowledge.

I tried on a desktop (no integrated webcam):

- No error (|ERROR|018.339000| Failed to open)... but
- Same error to retrieve the camera image



This is the log file from my laptop

|INFO|000.023000| Software version: Plus-2.8.0.283830c3 - Win32| in E:\D\PSNPb\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(122)
|INFO|000.024000| Logging at level 3 to file: C:/Program Files (x86)/PlusApp-2.8.0.20190617-Win32/data/090919_113615_PlusLog.txt| in E:\D\PSNPb\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(123)
|INFO|000.098000| Supported devices: - 3dConnexion (ver: Plus-2.8.0) - Ascension3DG (ver: Plus-2.8.0) - AuroraTracker (ver: NDICAPI-1.7) - BkProFocusOem (ver: Plus-2.8.0) - BrachyTracker (ver: Plus-2.8.0) - CertusTracker (ver: Optotrak API (Win32 DLL Version) Version 3.01.03) - ChRobotics (ver: Plus-2.8.0) - Epiphan (ver: Plus-2.8.0) - FakeTracker (ver: Plus-2.8.0) - GenericSerialDevice (ver: Plus-2.8.0) - ICCapturing (ver: The Imaging Source UDSHL-3.4) - ImageProcessor (ver: Plus-2.8.0) - IntelRealSense (ver: Plus-2.8.0) - Microchip (ver: Plus-2.8.0) - MicronTracker (ver: MTC-3.7.6.8) - MmfVideo (ver: Plus-2.8.0) - NDITracker (ver: NDICAPI-1.7) - NoiseVideo (ver: Plus-2.8.0) - OpenCVVideo (ver: Plus-2.8.0) - OpenIGTLinkTracker (ver: OpenIGTLink v3.1.0) - OpenIGTLinkVideo (ver: OpenIGTLink v3.1.0) - OptiTrack (ver: Plus-2.8.0) - OpticalMarkerTracker (ver: Plus-2.8.0) - PhidgetSpatial (ver: Plus-2.8.0) - PolarisTracker (ver: NDICAPI-1.7) - SavedDataSource (ver: Plus-2.8.0) - SonixPortaVideo (ver: UltrasonixSDK-6.1.1) - SonixVideo (ver: UltrasonixSDK-6.1.1) - USDigitalEncodersTracker (ver: Plus-2.8.0) - UsSimulator (ver: Plus-2.8.0) - VFWVideo (ver: Plus-2.8.0) - VirtualBufferedCapture (ver: Plus-2.8.0) - VirtualCapture (ver: Plus-2.8.0) - VirtualDiscCapture (ver: Plus-2.8.0) - VirtualMixer (ver: Plus-2.8.0) - VirtualSwitcher (ver: Plus-2.8.0) - VirtualTextRecognizer (ver: Plus-2.8.0) - VirtualVolumeReconstructor (ver: Plus-2.8.0) | in E:\D\PSNPb\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(127)
|INFO|000.104000| Server host name: Aero-Caio| in E:\D\PSNPb\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(158)
|INFO|000.117000| Server IP addresses: 169.254.7.67, 192.168.56.1, 169.254.89.44, 169.254.169.63, 10.39.75.97, 169.254.170.163, 127.0.0.1| in E:\D\PSNPb\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(178)
|INFO|000.118000| Start remote control server at port: 18904| in E:\D\PSNPb\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(187)
**|ERROR|018.339000| Failed to open C:/Program Files (x86)/PlusApp-2.8.0.20190617-Win32/bin/PlusConfig.xml for writing| in E:\D\PSNPb\PlusLib\src\PlusCommon\PlusCommon.cxx(527)**
|INFO|018.357000| Connect using configuration file: C:\Program Files (x86)\PlusApp-2.8.0.20190617-Win32\config\PlusDeviceSet_Server_MmfColorVideoCapture_updown.xml| in E:\D\PSNPb\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(639)
|INFO|018.358000| Server process command line: "C:/Program Files (x86)/PlusApp-2.8.0.20190617-Win32/bin/PlusServer.exe" --config-file="PlusDeviceSet_Server_MmfColorVideoCapture_updown.xml" --verbose=3| in E:\D\PSNPb\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(320)
|INFO|018.996000| Server process started successfully| in E:\D\PSNPb\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(329)
|INFO|027.185000|SERVER> System start timestamp: 6019
|ERROR|027.189000|SERVER> Failed to open C:/Program Files (x86)/PlusApp-2.8.0.20190617-Win32/bin/PlusConfig.xml for writing| in :\D\PSNPb\PlusLib\src\PlusCommon\PlusCommon.cxx(527)
|INFO|027.190000|SERVER> Software version: Plus-2.8.0.283830c3 - Win32
|INFO|027.190000|SERVER> Logging at level 3 (INFO) to file: C:/Program Files (x86)/PlusApp-2.8.0.20190617-Win32/data/090919_113642_PlusLog.txt
|INFO|027.191000|SERVER> Selected US image orientation: MF
|INFO|027.191000|SERVER> Server status: Reading configuration.
|INFO|027.192000|SERVER> Server status: Connecting to devices.
**|WARNING|027.440000|SERVER> > Unable to init capture device with requested details: device ID: 1 (2M WebCam) stream 0, 640x480, 30Hz, YUY2| in :\D\PSNPb\PlusLib\src\PlusDataCollection\MicrosoftMediaFoundation\vtkPlusMmfVideoSource.cxx(313)**
|INFO|027.441000|SERVER> Supported vide formats for Device Id 1 (2M WebCam)
|INFO|027.441000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: NV12, frame rate: 30
|INFO|027.441000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: MJPG, frame rate: 30
|INFO|027.442000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: NV12, frame rate: 25
|INFO|027.442000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: MJPG, frame rate: 25
|INFO|027.442000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: NV12, frame rate: 20
|INFO|027.442000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: MJPG, frame rate: 20
|INFO|027.444000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: NV12, frame rate: 15
|INFO|027.444000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: MJPG, frame rate: 15
|INFO|027.444000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: NV12, frame rate: 10
|INFO|027.445000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: MJPG, frame rate: 10
|INFO|027.445000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: NV12, frame rate: 5
|INFO|027.445000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: MJPG, frame rate: 5
|INFO|027.445000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: YUY2, frame rate: 30
|INFO|027.445000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: YUY2, frame rate: 25
|INFO|027.446000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: YUY2, frame rate: 20
|INFO|027.453000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: YUY2, frame rate: 15
|INFO|027.453000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: YUY2, frame rate: 10
|INFO|027.453000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: YUY2, frame rate: 5
|INFO|027.453000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 30
|INFO|027.454000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 25
|INFO|027.454000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 20
|INFO|027.454000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 15
|INFO|027.454000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 10
|INFO|027.455000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 5
|INFO|027.455000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 30
|INFO|027.455000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 25
|INFO|027.455000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 20
|INFO|027.455000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 15
|INFO|027.456000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 10
|INFO|027.456000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 5
|INFO|027.456000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 30
|INFO|027.456000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 25
|INFO|027.457000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 20
|INFO|027.457000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 15
|INFO|027.457000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 10
|INFO|027.457000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 5
|INFO|027.458000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 30
|INFO|027.458000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 25
|INFO|027.458000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 20
|INFO|027.458000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 15
|INFO|027.458000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 10
|INFO|027.459000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 5
|INFO|027.459000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 30
|INFO|027.459000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 25
|INFO|027.459000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 20
|INFO|027.460000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 15
|INFO|027.460000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 10
|INFO|027.460000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 5
|INFO|027.460000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 30
|INFO|027.461000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 25
|INFO|027.461000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 20
|INFO|027.461000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 15
|INFO|027.461000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 10
|INFO|027.461000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 5
|INFO|027.462000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 30
|INFO|027.462000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 25
|INFO|027.462000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 20
|INFO|027.463000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 15
|INFO|027.463000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 10
|INFO|027.463000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 5
|INFO|027.464000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 30
|INFO|027.464000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 25
|INFO|027.464000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 20
|INFO|027.464000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 15
|INFO|027.465000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 10
|INFO|027.465000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 5
|INFO|027.465000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 30
|INFO|027.465000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 25
|INFO|027.465000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 20
|INFO|027.466000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 15
|INFO|027.466000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 10
|INFO|027.466000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 5
|INFO|027.467000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 30
|INFO|027.467000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 25
|INFO|027.467000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 20
|INFO|027.467000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 15
|INFO|027.467000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 10
|INFO|027.468000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 5
|INFO|027.468000|SERVER> Stream index 2 - Frame size: 1920x1080, video format: NV12, frame rate: 1
|INFO|027.468000|SERVER> Stream index 2 - Frame size: 1920x1080, video format: MJPG, frame rate: 1
|INFO|027.470000|SERVER> Backing up to connecting with default capture settings: device ID: 0 (HD WebCam), 640x480, 30Hz, YUY2
|INFO|028.469000|SERVER> Server status: Starting servers.
|INFO|028.474000|SERVER> Plus OpenIGTLink server listening on IPs: 169.254.7.67, 192.168.56.1, 169.254.89.44, 169.254.169.63, 10.39.75.97, 169.254.170.163, 127.0.0.1 -- port 18944
|INFO|028.519000|SERVER> Server status: Server(s) are running.
|INFO|028.520000|SERVER> Press Ctrl-C to quit.

**Comment by adamrankin** [comment]
Ok, this is at least telling us that the camera doesn't support 640x480 capture.

Change the config file to 1920x1080

**Comment by Sunderlandkyl** [comment]
The log shows the list of supported configurations with your USB camera.
You can change the device parameters in the config file to match one of the supported formats, which are listed in the log:

```
|INFO|027.441000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: NV12, frame rate: 30
|INFO|027.441000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: MJPG, frame rate: 30
|INFO|027.442000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: NV12, frame rate: 25
|INFO|027.442000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: MJPG, frame rate: 25
|INFO|027.442000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: NV12, frame rate: 20
|INFO|027.442000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: MJPG, frame rate: 20
|INFO|027.444000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: NV12, frame rate: 15
|INFO|027.444000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: MJPG, frame rate: 15
|INFO|027.444000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: NV12, frame rate: 10
|INFO|027.445000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: MJPG, frame rate: 10
|INFO|027.445000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: NV12, frame rate: 5
|INFO|027.445000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: MJPG, frame rate: 5
|INFO|027.445000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: YUY2, frame rate: 30
|INFO|027.445000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: YUY2, frame rate: 25
|INFO|027.446000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: YUY2, frame rate: 20
|INFO|027.453000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: YUY2, frame rate: 15
|INFO|027.453000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: YUY2, frame rate: 10
|INFO|027.453000|SERVER> Stream index 0 - Frame size: 1920x1080, video format: YUY2, frame rate: 5
|INFO|027.453000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 30
|INFO|027.454000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 25
|INFO|027.454000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 20
|INFO|027.454000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 15
|INFO|027.454000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 10
|INFO|027.455000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 5
|INFO|027.455000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 30
|INFO|027.455000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 25
|INFO|027.455000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 20
|INFO|027.455000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 15
|INFO|027.456000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 10
|INFO|027.456000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 5
|INFO|027.456000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 30
|INFO|027.456000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 25
|INFO|027.457000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 20
|INFO|027.457000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 15
|INFO|027.457000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 10
|INFO|027.457000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 5
|INFO|027.458000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 30
|INFO|027.458000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 25
|INFO|027.458000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 20
|INFO|027.458000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 15
|INFO|027.458000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 10
|INFO|027.459000|SERVER> Stream index 1 - Frame size: 640x480, video format: H264, frame rate: 5
|INFO|027.459000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 30
|INFO|027.459000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 25
|INFO|027.459000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 20
|INFO|027.460000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 15
|INFO|027.460000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 10
|INFO|027.460000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 5
|INFO|027.460000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 30
|INFO|027.461000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 25
|INFO|027.461000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 20
|INFO|027.461000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 15
|INFO|027.461000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 10
|INFO|027.461000|SERVER> Stream index 1 - Frame size: 640x360, video format: H264, frame rate: 5
|INFO|027.462000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 30
|INFO|027.462000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 25
|INFO|027.462000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 20
|INFO|027.463000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 15
|INFO|027.463000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 10
|INFO|027.463000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 5
|INFO|027.464000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 30
|INFO|027.464000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 25
|INFO|027.464000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 20
|INFO|027.464000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 15
|INFO|027.465000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 10
|INFO|027.465000|SERVER> Stream index 1 - Frame size: 320x240, video format: H264, frame rate: 5
|INFO|027.465000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 30
|INFO|027.465000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 25
|INFO|027.465000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 20
|INFO|027.466000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 15
|INFO|027.466000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 10
|INFO|027.466000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 5
|INFO|027.467000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 30
|INFO|027.467000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 25
|INFO|027.467000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 20
|INFO|027.467000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 15
|INFO|027.467000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 10
|INFO|027.468000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 5
|INFO|027.468000|SERVER> Stream index 2 - Frame size: 1920x1080, video format: NV12, frame rate: 1
|INFO|027.468000|SERVER> Stream index 2 - Frame size: 1920x1080, video format: MJPG, frame rate: 1
```

**Comment by caioath** [comment]
Thank you for your inputs.

This is what I get trying different configurations

FrameSize="1920 1080"
      VideoFormat="NV12"
|ERROR|1535.861000|SERVER> > Unknown pixel type: NV12 (only YUY2, MJPG and RGB24 are supported)|

FrameSize="1920 1080"
      VideoFormat="MJPG"
|ERROR|1594.431000|SERVER> MJPEG is not supported yet| in :\D\PSNPb\PlusLib\src\PlusCommon\PixelCodec.h(370)
|ERROR|1594.432000|SERVER> Error while decoding the grabbed image| in :\D\PSNPb\PlusLib\src\PlusDataCollection\MicrosoftMediaFoundation\vtkPlusMmfVideoSource.cxx(660)

FrameSize="1920 1080"
      VideoFormat="YUY2"
|WARNING|1458.381000|SERVER> No data is broadcasted, as no data is available yet.


Is it possible to choose the other configurations (I guess I would need to choose a different "Stream index", as in (|INFO|027.465000|SERVER> Stream index 1 - Frame size: 1280x720, video format: H264, frame rate: 30)?

**Comment by adamrankin** [comment]
> FrameSize="1920 1080"
> VideoFormat="YUY2"
> |WARNING|1458.381000|SERVER> No data is broadcasted, as no data is available yet.

Can you also set `AcquisitionRate="30"`

But this one should have worked. You see nothing in Slicer?

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
