### ISSUE TITLE
No data is broadcasted, as no data available yet.

### ISSUE THREAD

**Issue by Ugurmustafa97** [PlusToolkit/PlusLib#597]
Hi @adamrankin, sorry for bothering you again.

After I read the Blackmagick Declink's SDK documentation and the code you wrote for device. I understand the logic. But I have still problems to capture frames from my Blackmagic Decklink Duo 2 device. 

My device settings in the xml file looks like this:
```
<Device
      Id="VideoDevice" 
      Type="DeckLinkVideo" 
      FrameSize="1920 1080"
      PixelFormat="8BitBGRA"
      VideoConnection="SDI"
      DisplayMode="HD1080p30"
      CaptureDeviceId="0" >
``` 
and I didn't change any this in your code. If I run the plusserver I get this error:
```
WARNING|091.149000| No data is broadcasted, as no data is available yet.| in C:\P\bmdk\PlusB-bin\PlusLib\src\PlusServer\vtkPlusOpenIGTLinkServer.cxx(440)
```
Do you thing that I should set the DeviceIndex in xml file?

Also, I realized that when I run the debug in Visual Studio, code goes to the **VideoInputFrameArrived** function in **Line 576** but it don't go through the **if statement** in **Line 591**. I think this could be the problem in my case but I don't know how to fix it.

I am just trying to capture my own desktop view and see it in 3D Slicer, so I connected my desktop output an DVI to SDI converter and plugged this SDI to my Blackmagic Decklink Duo 2 card. Also, I can see the desired capture in Blackmagic Media Express.

Thanks for your help, this is my last week in this project and I really want to figured out this problem. Also, I will not be asking about this after this week:)

**Comment by Ugurmustafa97** [comment]
Hi, I figured out how to capture. Now I am getting frames from my Blacklink Decklink Duo 2 device.  But I still need help.

I am getting images in reverse orientation and colors are changing also. I tried to change **PortUsImageOrientation** according to your [page](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/UltrasoundImageOrientation.html) about Ultrasound Image Orientation. But any of these orientations don't help. Here is my new configuration file:

```
<Device
      Id="VideoDevice" 
      Type="DeckLinkVideo" 
      FrameSize="1280 720"
      PixelFormat="10BitYUV"
      VideoConnection="SDI"
      DisplayMode="HD720p60"
      CaptureDeviceId="0" >
      <DataSources>
        <DataSource Type="Video" Id="Video" PortUsImageOrientation="MF" ImageType="RGB_COLOR" />
```

Here is a sceenshoot:
![Screenshot (4)](https://user-images.githubusercontent.com/28268392/64571645-1ff8d880-d32a-11e9-9e98-b603bb60e924.png)

Actually these blue robots in 3D Slicer must be exactly same with the orange ones. 

Thanks.

**Comment by adamrankin** [comment]
Yes, the color swapping is because I hadn't finished implementing that. DeckLink provides conversion to BGRA, but not RGBA, so red and blue are swapped.

With regards to rotation, that should work however... I don't have the setup at the moment to test. Can you keep exploring the image orientation value?

**Comment by Ugurmustafa97** [comment]
Hi @adamrankin, thanks for reply, I tested it with a green color it was fine. I realized that there might be a small bug in the code. Here is the situation that I faced this morning: 

I plugged the input cable in to second port and added **DeviceIndex="1"**  statement to my xml file but code broke. While I was doing debugging I saw that **count** doesn't increases actually when added the statement to the xml file. So the code never goes through the while loops. 

I tried to put the **count++** statement to outside of the if statement and connect the input to second device place in Blackmagic and it worked well.

The **count** statement I am talking is in the Line 384.

**Comment by juyoungkim304** [comment]
Hi- just a quick follow up from the lab!

We still had issues with the image orientation value - the image had the same orientation even after changing it to different orientation values in the configuration file. We've manually fixed this by transforming it with specified coordinate definitions. What's interesting is that the OpticalMarkerTracker config file has the same issues with orientation with a different capture device - I'll look more into that.

**Comment by markasselin** [comment]
@adamrankin @lasso We seem to have had a number of issues with setting image orientation pop up in the past few weeks. Is it possible these are linked by a unifying bug?

**Comment by adamrankin** [comment]
No, the image orientation for a couple of devices was hardcoded. They've been fixed.

**Comment by juyoungkim304** [comment]
Hi @adamrankin - has there been any update with the color swapping issue? I've been getting some other pixel formats to work, but the colors never match up. Thank you for your response in advance!

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
