### ISSUE TITLE
use the ProbeToTracker matrix for the real pose of each frame?

### ISSUE THREAD

**Issue by zhaobingshuai** [PlusToolkit/PlusLib#599]
Hi, we have our 2D in-plane resolution of 0.083*0.083mm/pixel, and we have our 6DOF pose in mm and degree.  In such a situation, is my understanding correct that I should use a constant ImageToProbe matrix to provide the in-plane resolution information as:

0.083    0         0          0
0          0.083   0          0
0         0           1          0
0         0           0          1

Then, use the ProbeToTracker matrix for the real pose of each frame?

![image](https://user-images.githubusercontent.com/38325759/64934497-c8a0be00-d87d-11e9-9690-7984e1ae474c.png)

**Comment by Sunderlandkyl** [comment]
The ImageToProbe transform converts from the pixel coordinates of the image to the position of the pixel in the world, relative to the sensor attached to the probe (in mm).

Depending on your setup, this can be just scaling between pixels and mm, but likely also includes additional spatial information.

See also:
http://perk-software.cs.queensu.ca/plus/doc/nightly/user/CommonCoordinateSystems.html

**Comment by zhaobingshuai** [comment]
@gaoyi

**Comment by zhaobingshuai** [comment]
When I read your tutorial about volume construction, I find the following link, but I got 404, Can you update this tutorial again? Thanks for your help.
SlicerIGT U33:Ultrasound volume reconstruction - offline
![image](https://user-images.githubusercontent.com/38325759/66218799-83451300-e6fc-11e9-960f-7f6f2fac5072.png)
https://www.assembla.com/spaces/plus/wiki/Volume_Reconstruction

**Comment by Sunderlandkyl** [comment]
I assume that the assembla page contained this information:
http://perk-software.cs.queensu.ca/plus/doc/nightly/user/AlgorithmVolumeReconstruction.html

@lassoan Do you know what the contents were of the wiki page this originally pointed to?

**Comment by lassoan** [comment]
Probably it pointed to the algorithm page you have found.

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
