### ISSUE TITLE
Connecting Telemed Micrus

### ISSUE THREAD

**Issue by VincenzoGemignani** [PlusToolkit/PlusLib#602]
Hi,
I am trying to use fCal with the Telemed Micrus device on Windows 10.
I have installed the Telemed drivers and the PlusApp-2.8.0.20190617-Telemed-Win32.
When I click "connect" ("PulsServer: Telemed ultrasound device") it says "connection successful" but I do not receive any image (see the attached log).
The software works with "PulsServer: Video for Windows video capture device" and I can see the webcam.
Any suggestion?

[log.txt](https://github.com/PlusToolkit/PlusLib/files/3621838/log.txt)

**Comment by adamrankin** [comment]
Unfortunately the Telemed API is not returning an image. Are you able to build Plus in debug to investigate with our help?

**Comment by VincenzoGemignani** [comment]
Thank you Adam.
Yes, I have now built in debug mode with the Telemed SDK and I have the same problem. 
How can I investigate?

**Comment by adamrankin** [comment]
Can you step into `vtkPlusTelemedVideoSource::InternalUpdate() line 141` and see which particular condition is failing?

Possibilities are `TelemedUltrasound.cxx`
`line 254`
`line 270`
`line 280`
`line 303`
`line 312`

**Comment by adamrankin** [comment]
Also, fCal will still work, but you are using a PlusServer configuration file with the fCal app. There are a few tags that fCal wants to see in the configuration file (those are some of the other errors/warnings in your log)

**Comment by VincenzoGemignani** [comment]
It returns on line 254 of TelemedUltrasound.cxx

**Comment by adamrankin** [comment]
Can you check `line 450` and/or `line 459`? Does it hit a breakpoint on either line?

**Comment by VincenzoGemignani** [comment]
no, it exit at line 364

**Comment by adamrankin** [comment]
Ok, can you paste the HRESULT return code?

**Comment by adamrankin** [comment]
However, this indicates that something is probably wrong with the driver/installation. Plus is unable to initialize the MFC component for usgfw2.

**Comment by VincenzoGemignani** [comment]
the error is:
REGDB_E_CLASSNOTREG Class not registered

**Comment by adamrankin** [comment]
Ok, I'm unfamiliar with the Telemed installation. Do they have an installer, do you have to register the DLL manually?

**Comment by lassoan** [comment]
Does the probe work well with Telemed's own software? Which Telemed software version do you use?

Try runnning the Telemed software while connecting with PlusServer and run PlusServer as an administrator.

**Comment by VincenzoGemignani** [comment]
OK thanks.
I had to use the redistributable installer that is in the Telemed SDK (Telemed's own software does not need it). Now the DLL is loaded and I can see the images.
I had also to modify the configuration file because it is for the PlusServer. Is there a configuration file for the fCal app with Telemed?

**Comment by ungi** [comment]
You can swap the VideoDevice in any config file to Telemed. Delete the section with "VideoDevice" in it, and insert this one below.
By the way, if your goal is to calibrate your ultrasound position tracking, then there are simpler and more accurate methods than fCal.
```
    <Device
      Id="VideoDevice"
      Type="TelemedVideo">
      <DataSources>
        <DataSource Type="Video" Id="Video" PortUsImageOrientation="UF" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStream" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>
```

**Comment by VincenzoGemignani** [comment]
Thank you Tamas,
I wanted to test PLUS with Telemed ultrasound.
