### ISSUE TITLE
TrakSTAR is not recognized

### ISSUE THREAD

**Issue by ttate1** [PlusToolkit/PlusLib#604]
Hello

I am trying to write the configuration file to connect a TrakSTAR EM tracker to fCal. I copied the example config file from the PLUS toolkit user guide, but I am receiving errors. It seems that fCal is not able to find the type "Ascension3DG".  I also tried using the type "NDITracker", however it does not recognize the device.  The TrakSTAR does work in its own software.
I've tried it with a few different versions of PLUS, with the most recent one being PlusApp-2.9.0.20190917(Win64). Attached are the errors I receive in fCal, as well as the configuration file I was using.
[config_file.txt](https://github.com/PlusToolkit/PlusLib/files/3637858/config_file.txt)
[fcal_errors.txt](https://github.com/PlusToolkit/PlusLib/files/3637859/fcal_errors.txt)

Thank you in advance!

**Comment by Sunderlandkyl** [comment]
Ascension is only available for 32-bit builds.
This chart shows the devices that are included in each package:
https://plustoolkit.github.io/download

**Comment by lassoan** [comment]
Note that this is not a limitation of Plus but NDI Ascension API, which is only available for 32-bit applications. Your application that receives data from Plus can be a 64-bit application.

**Comment by ttate1** [comment]
Thanks! I didn't know I would need the 32-bit version. It solved my issues.
