### ISSUE TITLE
Data Loss verification

### ISSUE THREAD

**Issue by JFDamasceno** [PlusToolkit/PlusLib#608]
Hi, I'm using plustoolkit to perform volume reconstructions of the ultrasound images obtained with my US machine using openigtlink protocol. I would like to verify if all the images captured are received in Plus. I'm using plus server launch to run the config file and slicer to visualize the volume, but i can't seem to find a way to know how many frames have been received by plus(i know how many are sent by the US). Is it possible to obtain the number of images used to reconstruct a volume in plus?
Thanks in advance
José Damasceno

**Comment by adamrankin** [comment]
You can use a virtual disc capture object to also record the stream.

http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceVirtualCapture.html

**Comment by JFDamasceno** [comment]
Thank you Adam! 
It solved this issue, but now i have another. Each time I start plus, the first 5 to 6 frames sent by the Ultrasound are not received. I haven't noticed any loss beyond that point. Is there a reason for this?
 My config file goes attached.


[Final.zip](https://github.com/PlusToolkit/PlusLib/files/3662115/Final.zip)

**Comment by adamrankin** [comment]
Try modifying the `StartupDelaySec="1.0"` parameter in the `<DataCollection ...>` tag to be `0.0`.

**Comment by JFDamasceno** [comment]
Changing the delay didn't solve my issue. 
I'm also receiving this info message from time to time |INFO|703.399000|SERVER>timeToolTimeStampedUpdate failed for tool: TransducerToProbe with timestamp: <...>
attached goes the log file

[093019_180110_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/3672390/093019_180110_PlusLog.txt)

**Comment by adamrankin** [comment]
Who is providing the OpenIGTLink server of the ultrasound?

**Comment by JFDamasceno** [comment]
Plus is running on an independent PC connecting as a client to the US machine (where the server is) through TCP/IP.

**Comment by adamrankin** [comment]
Right, I mean what software is running on the US machine that is providing the OpenIGTLink server?

**Comment by JFDamasceno** [comment]
I'm using propello 6.1.3 on a Ultrasonix Tablet.

**Comment by adamrankin** [comment]
What is your order of operations? Are you trying to start the US IGT server and the Plus client at exactly the same time?

**Comment by adamrankin** [comment]
Or, are you counting the number of frames sent as recorded by the propello and comparing that to the number of frames received by Plus?

**Comment by JFDamasceno** [comment]
I'm counting the number of frames captured and sent by propello and then comparing to the number of frames received on plus. I noticed the frames that were missing were the first ones by comparing the transform messages.

**Comment by adamrankin** [comment]
Ok, thanks, I get it now. Let me do some thinking and investigating.

**Comment by JFDamasceno** [comment]
i'm using the release version PlusApp-2.8.0.20190621-Win64. But i can try to build the debug using cmake.

**Comment by lassoan** [comment]
For a few seconds you just start filling recording buffers to make sure that by the time we start recording data, all data streams have valid items that you can interpolate between. This is mainly controlled by [StartupDelaySec](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/Configuration.html#Device) but maybe LocalTimeOffsetSec values are taken into acccount, too.

Note that you don't need to use Propello (it's just a demo application anyway). Relevant features from Propello are integrated into SonixPortaVideo device so that you can acquire tracked slices and reconstruct 3D volumes from them dynamically.

See example configuration file here: http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceSonixVideo.html

Demo video: https://www.youtube.com/watch?v=KTz0nwAmeMo

**Comment by JFDamasceno** [comment]
So this means there is no way to recover those first 5 frames?
What are the advantages of using the integrated sonixportavideo instead of using propello?

**Comment by lassoan** [comment]
Propello cannot reconstruct volume in real-time.

**Comment by JFDamasceno** [comment]
I'm using ultrasonixTablet and KUKA lbr med to build a TRUS/MRI-Guided prostate biopsy system. The approach i took so far was to reconstruct a volume with plus for each position of the manipulator until it aligned the needle to the region of interest.

**Comment by lassoan** [comment]
That's exactly the kind of task the SonixPortaVideo device was developed for. It acquires tracked frames directly from the images and motor positions that ultrasonix porta interface provides. Plus volume reconstructor can create volumes in real-time from this information. If you track the robot's end effector position then you can take that into account in the volume reconstruction, too (you can reconstruct volumes in patient coordinate system and not just in the transducer coordinate system).

**Comment by lassoan** [comment]
Ulterius cannot control motor or access motor coordinates.

Ulterius works when the Exam software is running while Porta requires that the Exam software is not running.

Ulterius can connect via network but that does not matter much, as Plus can run on the ultrasound machine and offers remote access to the data stream anyway.

I'm not sure about the impact of expired license.

**Comment by JFDamasceno** [comment]
Ok now i understood. I will try to run plus on the US machine then. Thank you!

**Comment by JFDamasceno** [comment]
Finally implemented sonixportavideo in my system! Thank you for that! But now i ran into a problem which i can't figure out. It seems that plus is sending me 2 (non-persistent) transforms called MotorToRotatedMotor and MotorRotatedToTranducer that come from porta (these transforms should give me the transform between the image and the tool right?). The problem is that this transforms are constant in time which means that i can't perform the volume reconstruction. 
I'm using the 4DEC9-5/10 Transducer
