### ISSUE TITLE
Simultaneous B-mode and RF data collection

### ISSUE THREAD

**Issue by ilkerh** [PlusToolkit/PlusLib#609]
Dear All;
We were wondering if it is possible to obtain simultaneous B-mode and RF data using plus software. If yes would appreciate if you could guide me to the information explaining how this could be done. 
Our machine is ultrasonix Touch
Thank you again for your help and time
Ilker

**Comment by Sunderlandkyl** [comment]
There is a config file on the Ultrasonix device page that accomplishes this:
http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceSonixVideo.html

Here is a direct link to the config file:
https://github.com/PlusToolkit/PlusLibData/blob/d2dcc2d2b8ad84eea14bd6147dcf289da1e4f405/ConfigFiles/Testing/PlusDeviceSet_DataCollectionOnly_SonixVideo_FakeTracker_DualMode.xml

**Comment by Sunderlandkyl** [comment]
That config file is set up for fCal, but you can modify it to add your own PlusOpenIGTLinkServer elements if needed.

You will need one PlusOpenIGTLinkServer each for B-mode and RF data.

**Comment by ilkerh** [comment]
Thank you. will check this out

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
