### ISSUE TITLE
Fetching raw tracker sphere positions (NDI Polaris)

### ISSUE THREAD

**Issue by christjt** [PlusToolkit/PlusLib#610]
Hello,

I was wondering if it is possible to fetch the positions of all spheres that the Polaris is currently tracking, regardless if there are any marker plates / tools using the PlusApp? Is it only a matter of defining a POSITION message type in the XML or is this simply not possible without modification?

**Comment by adamrankin** [comment]
It is currently not possible without modification. That functionality is possible, but you'd have to modify the Plus NDI device to request that from the ndi C api.

**Comment by adamrankin** [comment]
If you are interested in implementing this, let me know and I can jump start you significantly.

**Comment by christjt** [comment]
Thanks for the quick reply. I am currently scoping out the solution for the project I am working on so I don't know if I'll have time to do it or not. I might try implementing that functionality though. I'll let you know, and thanks for helping out 👍
