### ISSUE TITLE
WitMotion BWT901CL is not supported

### ISSUE THREAD

**Issue by gdlesage** [PlusToolkit/PlusLib#613]
I am unable to get plus server launcher to connect to BWT901CL.  I copied the configuration file from user manual, set serial port correctly but I get error "Unknown device type: WitMotionTracker. Supported devices: 3dConnexion, ..." in pluslog.txt.  I have enclosed pluslog.txt with all msg enclosed.  Has support for BWT901CL been dropped?
[101319_174855_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/3722528/101319_174855_PlusLog.txt)
Thanks in advance,  Gene

**Comment by adamrankin** [comment]
I don't think the Wit motion is included in the standard release. @Sunderlandkyl I don't think it needs a special SDK, could we add it to the standard release?

**Comment by Sunderlandkyl** [comment]
Sure. I'll enable the device. It should be available in the nightly and stable packages tomorrow morning.

**Comment by gdlesage** [comment]
I assumed it was in standard release, since its documented in manual.  Yes it would be great if it could be added to the standard release.
