### ISSUE TITLE
Plus Server Launcher Connection Failure Using Webcam

### ISSUE THREAD

**Issue by acvp17** [PlusToolkit/PlusLib#614]
I have a Microsoft Surfacebook 2 64-bit (Windows 10) computer and the latest nightly build of Plus Server Launcher (2.9; I had previously tried the stable build with no luck). 

I would like to use my webcam for marker tracking. My computer has a rear and front-facing camera. I cannot get a connection for the "Optical marker tracker using MMF video" device set. 

When I press "launch server," I receive the following errors:
Connection failed!
Please select another device set and try again!
Unable to initialize capture device with default details: device ID: 0 (microsoft camera front) stream 0, 640x480, 30Hz, YUY2

Because of this, I changed the .xml file CaptureDeviceID to 1. 
I received a new error that simply says "Server stopped unexpectedly. Return code: 1"

**I'm starting to suspect there is something wrong with the default video format. I changed it to NV12 (as suggested in the log files). I was then able to connect to the server. However, data are not being acquired (there is a warning error in the error log saying that the NV12 pixel type is not supported and am therefore not getting the "image_image" object in 3D Slicer).** 

I've tried various combinations of resolutions and video formats, but I just can't get it to work!

Any advice would be greatly appreciated. Thank you!

**Comment by Sunderlandkyl** [comment]
If none of the pixel types from the webcam are supported, try using the OpenCV video device instead (http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceOpenCVVideo.html).

**Comment by acvp17** [comment]
I will try the OpenCV video device - thank you for the suggestion! 

Unfortunately for my original case, it was a driver update that changed all of the video formats to NV12. I was able to rollback my drivers to get the YUY2 format and the plus server works great. However, not ideal because I would like updated drivers, so I'll play around with the OpenCV video device.

Thanks again for the help!
