### ISSUE TITLE
Connecting Ultrasonix Machine to a Laptop

### ISSUE THREAD

**Issue by dtz90** [PlusToolkit/PlusLib#615]
Hi,
I am trying to use ultrasound to reconstruct a phantom model of an arterial bifurcation. I have an Ultrasonix (5.7) machine running on windows XP. In order to track the position of the US probe I want to use the webcam based tracking (https://www.youtube.com/watch?v=MOqh6wgOOYs&feature=youtu.be) using a webcam and laptop. On the laptop I have downloaded 3D Slicer 4.11, PlusApp-2.8-Ultrasonix-5.7-Win32, SlicerIGT-Data and installed all the extensions on 3d Slicer (SlicerOpenIGTLink, SlicerIGT, SlicerIGSIO, SlicerJupyter) as per the Installing software powerpoint tutorial on SlicerIGT website. However I have not found any information on how to connect to the Ultrasonix machine. I am new to this so any help or guidance in achieving my goal would be much appreciated.
Regards,
Daniel

**Comment by adamrankin** [comment]
Ultrasonix is a network based connection, so you'll have to ensure that both laptop and ultrasonix are on the same network (direct connection is possible, just have to set up static IPs on both machines). 

Once that is completed, you can update the sample configuration file to use your IP information.

**Comment by dtz90** [comment]
Can this be done using a wireless internet connection?

**Comment by dtz90** [comment]
Hi Adam,
I connected the laptop to the US machine using a LAN cable. I know both computers are now communicating with each other using the ping command. However could you explain further where i can find and alter the sample configuration file?
Thanks,
Daniel

**Comment by adamrankin** [comment]
https://github.com/PlusToolkit/PlusLibData/tree/master/ConfigFiles

**Comment by dtz90** [comment]
Hi,
I have been using the Plus Launcher with the configuration file found here: (http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceOpticalMarkerTracker.html). However the connection fails and says to select another device set. What specifically has to be changed in the configuration file. Also is there any more detailed tutorials on how to use this for people with no coding experience.
Thanks

**Comment by adamrankin** [comment]
So, you'll have to create your own config file that has both a optical marker tracker and an ultrasonix. You'll also have to add a virtual mixer to combine the output of those two devices into a single channel.

An example of this with a different tracker is here:
https://github.com/PlusToolkit/PlusLibData/blob/master/ConfigFiles/PlusDeviceSet_Server_Ultrasonix_L14-5.xml

That config file assumes that Plus is running on the ultrasonix machine. If you want to run Plus on your laptop, you'll have to replace "127.0.0.1" with the IP of your ultrasonix machine.

If you take the `<Device>` tag for the optical marker tracker and replace the `Ascension3DG` device, you're most of the way there.

The last thing to do is to change the transforms that are propagated through your configuration. Are you able to identify those?

**Comment by dtz90** [comment]
No. Are you talking about the matrix under the Coordinate Definitions?

**Comment by adamrankin** [comment]
No, in the `<PlusOpenIGTLinkServer>` tag there is a subtag `<TransformNames>`. In the example config file, these are the transforms produced by the `Ascension3DG` tracker, which you are not using. You will have to change these values to match what the OpticalMarkerTracker device produces.

An example of OpticalMarkerTracker is available here:
https://github.com/PlusToolkit/PlusLibData/blob/master/ConfigFiles/PlusDeviceSet_Server_OpticalMarkerTracker_Mmf.xml

**Comment by dtz90** [comment]
[PlusDeviceSet_Server_Ultrasonix_L14-5_OpticalTracker.txt](https://github.com/PlusToolkit/PlusLib/files/3740052/PlusDeviceSet_Server_Ultrasonix_L14-5_OpticalTracker.txt)
 
I've attached the Configuration file in text format. I've made all the changes you suggested. What would be the next step?

**Comment by dtz90** [comment]
Hi I have been trying to launch the configuration file on the PlusLaunchServer but keep getting an error Unknown Device type: MmfVideo

**Comment by dtz90** [comment]
![Capture](https://user-images.githubusercontent.com/43064048/67104581-1aab6b00-f1bf-11e9-9a8a-315d3209333c.PNG)

Hi I have made a few changes mainly using VFMVideo instead of MmfVideo which is giving back less errors. It just seems to be having trouble finding the calibration file however I cannot find :\D\PSNPS57b\PlusLib\src\PlusDataCollection\OpticalMarkerTracking\vtkPlusOpticalMarkerTracker.cxx(239)

**Comment by Sunderlandkyl** [comment]
Did you create a custom calibration file (using aruco_calibration.exe) and place it in that directory?

**Comment by adamrankin** [comment]
Can you upload your Plus log file for your most recent attempt?

**Comment by dtz90** [comment]
Ok where do I find that?



On Fri, Oct 18, 2019 at 7:21 PM +0100, "notifications@github.com" <notifications@github.com<mailto:notifications@github.com>> wrote:


**CAUTION EXTERNAL EMAIL**
This email originated from outside of the University of Limerick. Do not click on links or open attachments unless you recognize the sender's email address and know the content is safe.



Can you upload your Plus log file for your most recent attempt?

**Comment by dtz90** [comment]
[101819_201527_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/3749535/101819_201527_PlusLog.txt)
[OpticalMarkerTracker2.txt](https://github.com/PlusToolkit/PlusLib/files/3749536/OpticalMarkerTracker2.txt)
[PlusDeviceSet_Server_Ultrasonix_L14-5_OpticalTracker.txt](https://github.com/PlusToolkit/PlusLib/files/3749537/PlusDeviceSet_Server_Ultrasonix_L14-5_OpticalTracker.txt)
[101819_202102_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/3749539/101819_202102_PlusLog.txt)

**Comment by adamrankin** [comment]
First basic question, does this file exist?
`C:\Users\marco\PlusApp-2.8.0.20190617-Ultrasonix-5.7-Win32\config\OpticalMarkerTracker\camera_calibration.yml`

**Comment by dtz90** [comment]
Yes. I actually got the Plus server to launch using the OpticalMarkerTracker2 this morning however even tho my camera light turns on there is no video feed showing in 3D slicer.

**Comment by dtz90** [comment]
I could send you my teamviewer details by email for you to have a look yourself if that would make things easier?

**Comment by dtz90** [comment]
time|level|timeoffset|message|location
102119_182336.709|INFO|000.000000| System start timestamp: 20627| in E:\D\PSNPS57b\PlusLib\src\PlusCommon\vtkPlusAccurateTimer.cxx(51)
102119_182336.713|INFO|000.004000| Software version: Plus-2.8.0.283830c3 - Win32| in vtkPlusLogger(188)
102119_182336.714|INFO|000.005000| Logging at level 3 (INFO) to file: C:/Users/marco/PlusApp-2.8.0.20190617-Ultrasonix-5.7-Win32/data/102119_182336_PlusLog.txt| in E:\D\PSNPS57b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(81)
102119_182336.731|INFO|000.022000| Selected US image orientation: UF| in E:\D\PSNPS57b\PlusLib\src\PlusDataCollection\vtkPlusDataSource.cxx(301)
102119_182336.754|INFO|000.045000| VideoDevice: Local time offset: -297.6ms| in E:\D\PSNPS57b\PlusLib\src\PlusDataCollection\vtkPlusDevice.cxx(1048)
102119_182336.755|INFO|000.046000| Server status: Reading configuration.| in E:\D\PSNPS57b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(92)
102119_182336.756|INFO|000.047000| Server status: Connecting to devices.| in E:\D\PSNPS57b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(103)
102119_182336.756|INFO|000.047000| Use aruco camera calibration file located at: C:\Users\marco\PlusApp-2.8.0.20190617-Ultrasonix-5.7-Win32\config\OpticalMarkerTracker\camera_calibration.yml| in E:\D\PSNPS57b\PlusLib\src\PlusDataCollection\OpticalMarkerTracking\vtkPlusOpticalMarkerTracker.cxx(236)
102119_182339.772|ERROR|003.063000| vtkPlusSonixVideoSource::SetParamValue failed (paramId=b-dyn log factor, paramValue=-2147483648) sendAndWait(): an error was returned by the server| in E:\D\PSNPS57b\PlusLib\src\PlusDataCollection\SonixVideo\vtkPlusSonixVideoSource.cxx(773)
102119_182348.732|INFO|012.023000| Server status: Starting servers.| in E:\D\PSNPS57b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(116)
102119_182348.760|INFO|012.051000| Plus OpenIGTLink server listening on IPs: 169.254.25.150, 169.254.82.224, 192.168.0.3, 10.53.160.106, 169.254.241.159, 127.0.0.1 -- port 18944| in e:\d\psnps57b\pluslib\src\plusserver\vtkPlusOpenIGTLinkServerWin32.cxx(81)

**Comment by dtz90** [comment]
This is what the log file says after running with research mode on. Do you have a step by step guide as to what has to be running before launching Plus server. Currently I have the ultrasonix machine on in research mode and 3d slicer open using  OpenIGTLinkIF module create a connection with default parameters for tracking data (port 18944 as client). For getting real-time video data, create a connection at port port 18945 as client

**Comment by adamrankin** [comment]
Sorry, I'm a bit lost. The config file has no ultrasonix device configured. What are you trying to capture with the VFW device?

**Comment by dtz90** [comment]
which one of the two configuration files I sent are you looking at?

**Comment by adamrankin** [comment]
The one you said you got working. OpticalMarkerTracker2.txt

**Comment by dtz90** [comment]
![Capture2](https://user-images.githubusercontent.com/43064048/67230176-b2fe5580-f434-11e9-8464-e4f4fd851d38.PNG)

Yes that one has no ultrasonix device configured as I was just testing if i could get the marker tracking to work. The above image shows what happens when i launch that configuration file. It says it was successful and my camera light comes on but there is no video feed in 3d slicer

**Comment by adamrankin** [comment]
Ok, and the second config file does or doesn't work when you have the ultrasonix on and in research mode?

**Comment by dtz90** [comment]
It say it connects successfully and the ultrasound image shows up in the red box in 3d slicer. But then it says the connection failed. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43064048/67232485-60736800-f439-11e9-82ec-fde704cf2f73.gif)

**Comment by dtz90** [comment]
This is the log file for the above issue.

time|level|timeoffset|message|location
102219_193325.236|INFO|000.000000| System start timestamp: 22192| in E:\D\PSNPS57b\PlusLib\src\PlusCommon\vtkPlusAccurateTimer.cxx(51)
102219_193325.240|INFO|000.004000| Software version: Plus-2.8.0.283830c3 - Win32| in vtkPlusLogger(188)
102219_193325.240|INFO|000.004000| Logging at level 3 (INFO) to file: C:/Users/marco/PlusApp-2.8.0.20190617-Ultrasonix-5.7-Win32/data/102219_193325_PlusLog.txt| in E:\D\PSNPS57b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(81)
102219_193325.256|INFO|000.019000| Selected US image orientation: UF| in E:\D\PSNPS57b\PlusLib\src\PlusDataCollection\vtkPlusDataSource.cxx(301)
102219_193325.256|INFO|000.020000| VideoDevice: Local time offset: -297.6ms| in E:\D\PSNPS57b\PlusLib\src\PlusDataCollection\vtkPlusDevice.cxx(1048)
102219_193325.257|INFO|000.021000| Server status: Reading configuration.| in E:\D\PSNPS57b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(92)
102219_193325.257|INFO|000.021000| Server status: Connecting to devices.| in E:\D\PSNPS57b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(103)
102219_193325.259|INFO|000.022000| Use aruco camera calibration file located at: C:\Users\marco\PlusApp-2.8.0.20190617-Ultrasonix-5.7-Win32\config\OpticalMarkerTracker\camera_calibration.yml| in E:\D\PSNPS57b\PlusLib\src\PlusDataCollection\OpticalMarkerTracking\vtkPlusOpticalMarkerTracker.cxx(236)
102219_193328.282|ERROR|003.046000| vtkPlusSonixVideoSource::SetParamValue failed (paramId=b-dyn log factor, paramValue=-2147483648) sendAndWait(): an error was returned by the server| in E:\D\PSNPS57b\PlusLib\src\PlusDataCollection\SonixVideo\vtkPlusSonixVideoSource.cxx(773)
102219_193334.832|INFO|009.595000| Server status: Starting servers.| in E:\D\PSNPS57b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(116)
102219_193334.845|INFO|009.608000| Plus OpenIGTLink server listening on IPs: 169.254.25.150, 169.254.82.224, 192.168.0.3, 10.53.161.92, 169.254.241.159, 127.0.0.1 -- port 18944| in e:\d\psnps57b\pluslib\src\plusserver\vtkPlusOpenIGTLinkServerWin32.cxx(81)
102219_193334.890|INFO|009.653000| Plus OpenIGTLink server listening on IPs: 169.254.25.150, 169.254.82.224, 192.168.0.3, 10.53.161.92, 169.254.241.159, 127.0.0.1 -- port 18945| in e:\d\psnps57b\pluslib\src\plusserver\vtkPlusOpenIGTLinkServerWin32.cxx(81)
102219_193339.046|INFO|013.810000| Server status: Server(s) are running.| in E:\D\PSNPS57b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(147)
102219_193339.046|INFO|013.810000| Press Ctrl-C to quit.| in E:\D\PSNPS57b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(148)
102219_193339.046|INFO|013.810000| Received new client connection (client 1 at 127.0.0.1:18944). Number of connected clients: 1| in E:\D\PSNPS57b\PlusLib\src\PlusServer\vtkPlusOpenIGTLinkServer.cxx(276)
102219_193339.046|INFO|013.810000| Received new client connection (client 2 at 127.0.0.1:18945). Number of connected clients: 1| in E:\D\PSNPS57b\PlusLib\src\PlusServer\vtkPlusOpenIGTLinkServer.cxx(276)
102219_193339.049|INFO|013.813000| OpenIGTLink broadcasting started. No data was available between 0-9.274sec, therefore no data were broadcasted during this time period.| in E:\D\PSNPS57b\PlusLib\src\PlusServer\vtkPlusOpenIGTLinkServer.cxx(427)
102219_193339.049|INFO|013.812000| Filtered timestamp is probably invalid for video buffer item with item index=60, time=13.812. The item may have been tagged with an inaccurate timestamp, therefore it will not be recorded.| in E:\D\PSNPS57b\PlusLib\src\PlusDataCollection\vtkPlusBuffer.cxx(363)
102219_193339.049|INFO|013.813000| OpenIGTLink broadcasting started. No data was available between 0-8.3494sec, therefore no data were broadcasted during this time period.| in E:\D\PSNPS57b\PlusLib\src\PlusServer\vtkPlusOpenIGTLinkServer.cxx(427)
102219_193339.052|INFO|013.815000| Filtered timestamp is probably invalid for video buffer item with item index=61, time=13.815. The item may have been tagged with an inaccurate timestamp, therefore it will not be recorded.| in E:\D\PSNPS57b\PlusLib\src\PlusDataCollection\vtkPlusBuffer.cxx(363)
102219_193339.052|INFO|013.816000| Filtered timestamp is probably invalid for video buffer item with item index=62, time=13.816. The item may have been tagged with an inaccurate timestamp, therefore it will not be recorded.| in E:\D\PSNPS57b\PlusLib\src\PlusDataCollection\vtkPlusBuffer.cxx(363)
102219_193339.056|INFO|013.820000| Filtered timestamp is probably invalid for video buffer item with item index=63, time=13.82. The item may have been tagged with an inaccurate timestamp, therefore it will not be recorded.| in E:\D\PSNPS57b\PlusLib\src\PlusDataCollection\vtkPlusBuffer.cxx(363)
102219_193339.098|INFO|013.862000| Filtered timestamp is probably invalid for video buffer item with item index=130, time=13.862. The item may have been tagged with an inaccurate timestamp, therefore it will not be recorded.| in E:\D\PSNPS57b\PlusLib\src\PlusDataCollection\vtkPlusBuffer.cxx(363)
102219_193339.157|INFO|013.921000| Filtered timestamp is probably invalid for video buffer item with item index=131, time=13.921. The item may have been tagged with an inaccurate timestamp, therefore it will not be recorded.| in E:\D\PSNPS57b\PlusLib\src\PlusDataCollection\vtkPlusBuffer.cxx(363)

**Comment by adamrankin** [comment]
Ok, that looks promising. And you are unable to see the image in Slicer? Does the Volumes module list a volume, does that volume have plausible dimensions and scalar range?

**Comment by dtz90** [comment]
The image appears in slicer but then the connection fails and only one image is left behind. I've attached what is on the volumes page. Also it will only connect for that second after restarting the computer. If i do it again without restarting it won't connect at all.

![Capture2](https://user-images.githubusercontent.com/43064048/67319152-7568fd80-f504-11e9-8f74-9195ae89d824.PNG)

**Comment by adamrankin** [comment]
Are you able to also show me the log for the PlusServerLauncher, not just the PlusServer? I'm trying to figure out if the PlusServer crashed.

**Comment by dtz90** [comment]
Do you mean this from when you click the green button on the Plus Server Launcher?

 |INFO|000.804000| Software version: Plus-2.8.0.283830c3 - Win32| in E:\D\PSNPS57b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(122)
|INFO|000.805000| Logging at level 3 to file: C:/Users/marco/PlusApp-2.8.0.20190617-Ultrasonix-5.7-Win32/data/102219_193127_PlusLog.txt| in E:\D\PSNPS57b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(123)
|INFO|000.814000| Supported devices: - 3dConnexion (ver: Plus-2.8.0) - Ascension3DG (ver: Plus-2.8.0) - AuroraTracker (ver: NDICAPI-1.7) - BrachyTracker (ver: Plus-2.8.0) - CertusTracker (ver: Optotrak API (Win32 DLL Version) Version 3.01.03) - ChRobotics (ver: Plus-2.8.0) - Epiphan (ver: Plus-2.8.0) - FakeTracker (ver: Plus-2.8.0) - GenericSerialDevice (ver: Plus-2.8.0) - ICCapturing (ver: The Imaging Source UDSHL-3.4) - ImageProcessor (ver: Plus-2.8.0) - Microchip (ver: Plus-2.8.0) - NDITracker (ver: NDICAPI-1.7) - NoiseVideo (ver: Plus-2.8.0) - OpenIGTLinkTracker (ver: OpenIGTLink v3.1.0) - OpenIGTLinkVideo (ver: OpenIGTLink v3.1.0) - OpticalMarkerTracker (ver: Plus-2.8.0) - PolarisTracker (ver: NDICAPI-1.7) - SavedDataSource (ver: Plus-2.8.0) - SonixPortaVideo (ver: UltrasonixSDK-5.7.4) - SonixVideo (ver: UltrasonixSDK-5.7.4) - USDigitalEncodersTracker (ver: Plus-2.8.0) - UsSimulator (ver: Plus-2.8.0) - VFWVideo (ver: Plus-2.8.0) - VirtualBufferedCapture (ver: Plus-2.8.0) - VirtualCapture (ver: Plus-2.8.0) - VirtualDiscCapture (ver: Plus-2.8.0) - VirtualMixer (ver: Plus-2.8.0) - VirtualSwitcher (ver: Plus-2.8.0) - VirtualVolumeReconstructor (ver: Plus-2.8.0) | in E:\D\PSNPS57b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(127)
|INFO|000.850000| Server host name: DESKTOP-CRL4N81| in E:\D\PSNPS57b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(158)
|INFO|000.885000| Server IP addresses: 169.254.25.150, 169.254.82.224, 192.168.0.3, 10.53.161.92, 169.254.241.159, 127.0.0.1| in E:\D\PSNPS57b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(178)
|INFO|000.885000| Start remote control server at port: 18904| in E:\D\PSNPS57b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(187)
|INFO|116.966000| Connect using configuration file: C:\Users\marco\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Slicer 4.11.0-2019-10-14\SlicerIGT-Data\PlusDeviceSet_Server_Ultrasonix_L14-5_OpticalTracker.xml| in E:\D\PSNPS57b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(639)
|INFO|116.966000| Server process command line: "C:/Users/marco/PlusApp-2.8.0.20190617-Ultrasonix-5.7-Win32/bin/PlusServer.exe" --config-file="PlusDeviceSet_Server_Ultrasonix_L14-5_OpticalTracker.xml" --verbose=3| in E:\D\PSNPS57b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(320)
|INFO|117.723000| Server process started successfully| in E:\D\PSNPS57b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(329)
|INFO|118.112000|SERVER> System start timestamp: 22192
|INFO|118.116000|SERVER> Software version: Plus-2.8.0.283830c3 - Win32
|INFO|118.116000|SERVER> Logging at level 3 (INFO) to file: C:/Users/marco/PlusApp-2.8.0.20190617-Ultrasonix-5.7-Win32/data/102219_193325_PlusLog.txt
|INFO|118.132000|SERVER> Selected US image orientation: UF
|INFO|118.133000|SERVER> VideoDevice: Local time offset: -297.6ms
|INFO|118.133000|SERVER> Server status: Reading configuration.
|INFO|118.134000|SERVER> Server status: Connecting to devices.
|INFO|118.134000|SERVER> Use aruco camera calibration file located at: C:\Users\marco\PlusApp-2.8.0.20190617-Ultrasonix-5.7-Win32\config\OpticalMarkerTracker\camera_calibration.yml
|ERROR|121.158000|SERVER> vtkPlusSonixVideoSource::SetParamValue failed (paramId=b-dyn log factor, paramValue=-2147483648) sendAndWait(): an error was returned by the server| in :\D\PSNPS57b\PlusLib\src\PlusDataCollection\SonixVideo\vtkPlusSonixVideoSource.cxx(773)
|INFO|127.707000|SERVER> Server status: Starting servers.
|INFO|127.720000|SERVER> Plus OpenIGTLink server listening on IPs: 169.254.25.150, 169.254.82.224, 192.168.0.3, 10.53.161.92, 169.254.241.159, 127.0.0.1 -- port 18944
|INFO|127.766000|SERVER> Plus OpenIGTLink server listening on IPs: 169.254.25.150, 169.254.82.224, 192.168.0.3, 10.53.161.92, 169.254.241.159, 127.0.0.1 -- port 18945
|INFO|131.922000|SERVER> Server status: Server(s) are running.
|INFO|131.925000|SERVER> Press Ctrl-C to quit.
|INFO|131.926000|SERVER> Received new client connection (client 1 at 127.0.0.1:18944). Number of connected clients: 1
|INFO|131.926000|SERVER> Received new client connection (client 2 at 127.0.0.1:18945). Number of connected clients: 1
|INFO|131.932000|SERVER> OpenIGTLink broadcasting started. No data was available between 0-9.274sec, therefore no data were broadcasted during this time period.
|INFO|131.932000|SERVER> Filtered timestamp is probably invalid for video buffer item with item index=60, time=13.812. The item may have been tagged with an inaccurate timestamp, therefore it will not be recorded.
|INFO|131.933000|SERVER> OpenIGTLink broadcasting started. No data was available between 0-8.3494sec, therefore no data were broadcasted during this time period.
|INFO|131.933000|SERVER> Filtered timestamp is probably invalid for video buffer item with item index=61, time=13.815. The item may have been tagged with an inaccurate timestamp, therefore it will not be recorded.
|INFO|131.933000|SERVER> Filtered timestamp is probably invalid for video buffer item with item index=62, time=13.816. The item may have been tagged with an inaccurate timestamp, therefore it will not be recorded.
|INFO|131.934000|SERVER> Filtered timestamp is probably invalid for video buffer item with item index=63, time=13.82. The item may have been tagged with an inaccurate timestamp, therefore it will not be recorded.
|INFO|131.975000|SERVER> Filtered timestamp is probably invalid for video buffer item with item index=130, time=13.862. The item may have been tagged with an inaccurate timestamp, therefore it will not be recorded.
|INFO|132.033000|SERVER> Filtered timestamp is probably invalid for video buffer item with item index=131, time=13.921. The item may have been tagged with an inaccurate timestamp, therefore it will not be recorded.
|ERROR|132.064000| Server process error: Crashed| in E:\D\PSNPS57b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(840)
|ERROR|132.064000| Server stopped unexpectedly. Return code: -1073741819| in E:\D\PSNPS57b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(864)
|INFO|132.065000| Disconnect request successful| in E:\D\PSNPS57b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(632)

**Comment by adamrankin** [comment]
Ah ha!

**Comment by adamrankin** [comment]
Now we're cooking. @Sunderlandkyl any thoughts? are there any known crashes in aruco?

**Comment by Sunderlandkyl** [comment]
None that I can think of.

**Comment by adamrankin** [comment]
Ok, @dtz90 I'll build aruco here and see if I can replicate the crash.

**Comment by adamrankin** [comment]
Ok, I've built and run aruco, and I'm not getting a crash. I'll hook up my own ultrasonix and give it a go.

**Comment by dtz90** [comment]
Ok thanks. I've a few questions. Do I need to be connected to the internet when running this software? Also can Plus be used with a siemens ACUSSON ultrasound machine?

**Comment by adamrankin** [comment]
No internet required. We don't have specific support for that machine, but you could use a framegrabber for 2D ultrasound.

**Comment by dtz90** [comment]
Would it solve the issue im having by using the framegrabber with the ultasonix machine?

**Comment by adamrankin** [comment]
You shouldn't have to use the framegrabber with the ultrasonix. I haven't been able to reproduce your crash, but I'll keep digging.

**Comment by dtz90** [comment]
You can have a look at my set-up over teamviewer if that would help?

**Comment by lassoan** [comment]
What is your Ultrasonix Exam software version?

**Comment by dtz90** [comment]
5.7.1

**Comment by lassoan** [comment]
I see, that's a very old software version. Maybe there is some things are not working correctly in that version, such as image compression, changing of imaging parameters, etc. Try to keep the config file as simple as possible.

**Comment by adamrankin** [comment]
Ok, I am unable to reproduce the crash. Are you able to build Plus in Debug locally? If so, we can do a teamviewer session next week?

**Comment by dtz90** [comment]
Hi Adam,
How do I go about building Plus in Debug locally?

**Comment by adamrankin** [comment]
https://github.com/PlusToolkit/PlusBuild/

**Comment by dtz90** [comment]
Hi,
I have downloaded PlusBuild git repository and visual studio 2015. However I am now stuck on step: Configure the PlusBuild project with CMake

**Comment by adamrankin** [comment]
Ok, what errors/logs do you get?

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
