### ISSUE TITLE
Intel Realsense for Point cloud Acquisition 

### ISSUE THREAD

**Issue by carmineog** [PlusToolkit/PlusLib#616]
Is there any way to stream the depth data from the Intel Realsense D415 to slicer via the plus toolkit? I can stream the RGB and DEPTH video feeds to slicer (as shown in the link) but the DEPTH feed just seems to be a colorized image without the actual point data. I need it to form a 3D pointcloud of the scene. Any thoughts? 

https://www.youtube.com/watch?v=W0NmrT4Z8go

![image](https://user-images.githubusercontent.com/44247758/66874379-c8b8da00-ef5f-11e9-9050-c3eb855bedaf.png)

**Comment by adamrankin** [comment]
Isn't the colour value somehow translatable to a depth value?

**Comment by lassoan** [comment]
We transfer the depth map as an image for efficiency. You can convert to a surface mesh in Slicer using a VTK filter.

See this Slicer project week project: https://projectweek.na-mic.org/PW31_2019_Boston/Projects/RealSensePatientRegistration/

I don't find the repository with the Slicer module. Please contact Colton Barr from PerkLab (https://perk.cs.queensu.ca) cc me.

**Comment by lassoan** [comment]
Here is the repository: https://github.com/PerkLab/DepthImageToPointCloud
