### ISSUE TITLE
How to use Plus ultrasound 3D reconstruction？

### ISSUE THREAD

**Issue by James858123** [PlusToolkit/PlusLib#618]
I am learning to use Plus, but I found some tutorials missing, which makes my learning very difficult. Please tell me how to quickly learn to use Plus ultrasound reconstruction.

                                                                                                         thank you very much for your help

**Comment by James858123** [comment]
I now have an ultrasound machine and a NDI Aurora device.  I want to test with real equipment

**Comment by Sunderlandkyl** [comment]
You need to add a [virtual volume reconstructor device]( http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceVirtualVolumeReconstructor.html) to your config file.

Then you can perform live volume reconstruction using 3D Slicer (https://www.youtube.com/watch?v=lfZeXabDjMg).

**Comment by James858123** [comment]
Thank you very much for your help, but the first step I need to do a magnetic alignment calibration on the body membrane. Can you tell me what to do?

**Comment by James858123** [comment]
To add, the body membrane I use is the following, the tracking device is the NDI Aurora ultrasound probe for the C5-1 abdominal probe.[https://www.cirsinc.com/products/ultrasound/zerdine-hydrogel/triple-modality-3d-abdominal-phantom/](url)

**Comment by ungi** [comment]
Have you read these tutorials? http://www.slicerigt.org/wp/user-tutorial/
Especially U-31 on tracked ultrasound calibration, and U-37 on how to build a complete system with registration of the patient too.
Unfortunately, most tutorials show an older version of Slicer and PLUS, but you can still learn many concepts from them.

**Comment by James858123** [comment]
Thank you very much for your help. I have seen that most of these documents will be about the body film built by Lego. However, these contents have certain reference significance. I will study these contents again.

**Comment by James858123** [comment]
I tried to write my own xml document according to the tutorial and tried to start the PLUS server. It can boot and initialize the device, and it can also connect to the PLUS server via OpenIGTLinkIF in 3DSlicer. But nothing happened in Slicer.

My device list: NDI Aurora video capture card (for acquiring ultrasound images) Windows10 64bit

Below is my xml file

[https://onedrive.live.com/?authkey=%21AGQkSCZOwjVYXw8&cid=949876B1ECEC2B5B&id=949876B1ECEC2B5B%21109&parId=949876B1ECEC2B5B%21104&o=OneUp](url)

**Comment by Sunderlandkyl** [comment]
I cannot see the config file in the link.

**Comment by James858123** [comment]
[https://onedrive.live.com/?authkey=%21AGQkSCZOwjVYXw8&cid=949876B1ECEC2B5B&id=949876B1ECEC2B5B%21109&parId=949876B1ECEC2B5B%21104&o=OneUp](url)

**Comment by James858123** [comment]
Sorry，I don't know why the link to jump directly is wrong, you can copy the entire link and then access it in the browser.

**Comment by Sunderlandkyl** [comment]
I mean that if I copy and paste the link, I see a page that says: "This item might not exist or is no longer availiable".

Can you also upload your log file from Plus?
