### ISSUE TITLE
Read Data Streamed from Plus Server to Unity

### ISSUE THREAD

**Issue by asgardee** [PlusToolkit/PlusLib#620]
Hello,

Thank you for taking the time to read my question. I am currently trying to read data streamed by the Plus Toolkit 2.8.0 to Unity to be used for an AR setup. The data being streamed by the server is 3 transforms obtained from an NDI Aurora electromagnetic tracker. I have used 3D Slicer to ensure that the data that is being sent over the server is correctly (which it is). We are currently trying to use WireShark with npcap to sniff out the local data that is being sent by the server but are having problems decoding the information.

Has anyone else streamed data to Unity, and if so could someone help me with reading the server data in Unity? If you would like to see the packets that we received through Wireshark (.pcapng) or the configuration file (.xml) that I am using please inquire and I will directly send you the files (as they are not supported to share in this message).

Thanks for taking the time to read this and I hope to be hearing from someone soon!

**Comment by lassoan** [comment]
There are several OpenIGTLink implementations for Unity. Do you use it on desktop, HoloLens, or phone?

**Comment by asgardee** [comment]
We are currently using it on a desktop.

**Comment by adamrankin** [comment]
https://github.com/franklinwk/OpenIGTLink-Unity might work

**Comment by adamrankin** [comment]
Also, you shouldn't have to reverse engineer anything. It's all open spec.

http://openigtlink.org/developers/spec

Plus server implements spec v3

**Comment by adamrankin** [comment]
Plus also implements a keep-alive mechanism using STATUS messages.
