### ISSUE TITLE
TrackSTAR transform not available in OpenIGTLinkIF

### ISSUE THREAD

**Issue by rgmorrison** [PlusToolkit/PlusLib#621]
I am trying to visualize live tracking data from TrackSTAR in 3D slicer (4.10.2) using a windows PC. There seems to be **something wrong with the Plus to 3D slicer link OpenIGTLinkIF**. It could also be an error in my XML file. 

Plus server (latest v4.8 32 bit) runs just fine and I can hear the TrackSTAR unit working.
![plus](https://user-images.githubusercontent.com/26419446/67151104-ddaea980-f28e-11e9-8aeb-c7344c6ea6e3.PNG)

I was just trying to get one tracker working so I edited the example XML file to this:
![xml file](https://user-images.githubusercontent.com/26419446/67151115-0c2c8480-f28f-11e9-84dd-dba448bdc837.PNG)
Text version of XML:
`<PlusConfiguration version="2.3">
  <DataCollection StartupDelaySec="1.0" >
    <DeviceSet 
      Name="PlusServer: Ascension 3DG tracker"
      Description="Broadcasting tool tracking data through OpenIGTLink" 
    />
    <Device
      Id="TrackerDevice" 
      Type="Ascension3DG" 
      FilterAcWideNotch="1"
      ToolReferenceFrame="Tracker" >
      <DataSources>
        <DataSource Type="Tool" Id="Tracker1" PortName="0"  />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream" >
          <DataSource Id="Tracker1"/>
        </OutputChannel>
      </OutputChannels>
    </Device>
  </DataCollection>
  <PlusOpenIGTLinkServer 
    MaxNumberOfIgtlMessagesToSend="1" 
    MaxTimeSpentWithProcessingMs="50" 
    ListeningPort="18944" 
    OutputChannelId="TrackerStream" > 
    <DefaultClientInfo> 
      <MessageTypes> 
        <Message Type="TRANSFORM" />
      </MessageTypes>
      <TransformNames> 
        <Transform Name="ReferenceToTracker" />
      </TransformNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>
</PlusConfiguration>`

There is no transform visible when I check the active button in slicer OpenIGTLinkIF:
![slicerigt](https://user-images.githubusercontent.com/26419446/67151135-38e09c00-f28f-11e9-9198-621572f00664.PNG)

Any advice as to how to fix this?

**Comment by ungi** [comment]
To send "ReferenceToTracker" to Slicer, you need a tool named "Reference" and a tool named "Tracker", at least.

Now, you only have one tool defined in your tracker device, named "Tracker1". Add those two tool definitions for the ports that the sensors are plugged in.

 

Tamas

**Comment by rgmorrison** [comment]
Thank you that's what I needed to know! Your software is incredible and I appreciate you making it available for free.

I didn't understand all of the terminology, so your comment and this image helped.
![CoordinateSystemDefinitionsfCal](https://user-images.githubusercontent.com/26419446/67153550-53c80600-f2b9-11e9-8d2b-12bc6ed90c4d.png)

My new XML which worked was much more similar to the original example:
![new xml](https://user-images.githubusercontent.com/26419446/67153557-807c1d80-f2b9-11e9-87bf-4aa6aed23354.PNG)
