### ISSUE TITLE
Bone Surface Image for Ultrasound Simulator

### ISSUE THREAD

**Issue by hripat** [PlusToolkit/PlusLib#622]
Hello, 
I'm trying to image the femur using the US simulator however, the simulated image does not look correct.  As seen in the picture below, you can see both the top and bottom of the femur however, the US should just one "line" at the bone surface and the remaining areas as black. That type of image only appears when the US transducer is moved directly on top of the bone surface (or a little bit into the bone). The problem might be with the Ultrasound parameters, specifically, the reflective index. If that is the cause of the problem, then can these parameters be changed?

![image](https://user-images.githubusercontent.com/56734075/67240367-4e84cb80-f41f-11e9-9a30-3ed0f234ff99.png)

**Comment by Sunderlandkyl** [comment]
Yes, each model in the ultrasound simulator has its own acoustic properties.
```       
<SpatialModel
          Name="Vessel"
          ObjectCoordinateFrame="Reference"
          ModelFile="SimulatedUltrasound_VesselModel_Reference.stl"
          ModelToObjectTransform="
            1 0 0 0
            0 1 0 0
            0 0 1 0
            0 0 0 1"
          DensityKgPerM3="1800"
          SoundVelocityMPerSec="2000"
          AttenuationCoefficientDbPerCmMhz="0.0001"
          BackscatterDiffuseReflectionCoefficient="0.03"          
          SurfaceSpecularReflectionCoefficient="0.1"
          SurfaceDiffuseReflectionCoefficient="0.0"
        />
```

In the above example. note the DensityKgPerM3, SoundVelocityMPerSec, AttenuationCoefficientDbPerCmMhz, BackscatterDiffuseReflectionCoefficient, SurfaceSpecularReflectionCoefficient and SurfaceDiffuseReflectionCoefficient attributes.

**Comment by lassoan** [comment]
It seems that you choose acoustic properties of blood vessel for femur. You need to use something like this instead: https://github.com/PlusToolkit/PlusLibData/blob/d2dcc2d2b8ad84eea14bd6147dcf289da1e4f405/ConfigFiles/Testing/PlusDeviceSet_UsSimulatorAlgoTestLinear.xml#L48

**Comment by hripat** [comment]
I'm not sure which section I have to change the acoustic properties in. I tried changing it under where it says "femur.stl" in the picture but it didn't make a difference in how the image showed up. Am I changing it in the correct location? I tried changing the values to:
      DensityKgPerM3="1900"
      SoundVelocityMPerSec="4000"
      AttenuationCoefficientDbPerCmMhz="15.0"
As it said in the code that @lassoan sent. Do I have to change the reflection coefficient values? 
![image](https://user-images.githubusercontent.com/56734075/67315639-fad4b980-f4d4-11e9-9c23-d5677e176450.png)

**Comment by lassoan** [comment]
Change all acoustic properties values in the SpatialModel element:

**Comment by hripat** [comment]
Yes, in the "Vessel" SpatialModel element, I changed those values to these:
      DensityKgPerM3="1900"
      SoundVelocityMPerSec="4000"
      AttenuationCoefficientDbPerCmMhz="15.0"
      BackscatterDiffuseReflectionCoefficient="0.03"
      SurfaceSpecularReflectionCoefficient="0.1"
      SurfaceDiffuseReflectionCoefficient="0.0"
But that didn't affect the ultrasound image on Slicer. Do I have to change the other SpatialModels?

**Comment by lassoan** [comment]
No, that should be enough. Make sure you modify the correct file and there are no duplicate elements with the same name.

**Comment by hripat** [comment]
I modified the PlusDeviceSet_Server_SimulatedUltrasound_3DSlicer.xml file. There weren't any duplicate elements in the file. Would modifying the reflection coefficients help?

**Comment by lassoan** [comment]
If you change the values (you can randomly change all parameters by increasing/decreasing by 1-2 magnitudes) then you must see changes. You can confirm that you are modifying the correct file by completely removing SpatialModel elements from the file.

**Comment by hripat** [comment]
Hi,

I was told to modify the:
SurfaceSpecularReflectionCoefficient="0.1"
SurfaceDiffuseReflectionCoefficient="0.0" and I changed both of them to 0.9 and then to a 100 to see the difference. The picture I got at 100 was just the brightness near the bone surface was higher but the image still looks like this:
![coef_100_acoustic](https://user-images.githubusercontent.com/56734075/67493910-68ecbe00-f646-11e9-937e-882b7f35a1c0.PNG)
When I put the transducer almost into the bone. I get what a proper ultrasound should look like:
![coef_100](https://user-images.githubusercontent.com/56734075/67493969-80c44200-f646-11e9-9d47-bd564a1e5392.PNG)

However, the first image should also look like the second image because the transducer is within the gel portion. But I'm still not sure what the problem is.

**Comment by hripat** [comment]
I've also tried changing the acoustic values for the Gel_Block Spatial Model with the femur Spatial Model in the PlusDeviceSet_Server_SimulatedUltrasound_3DSlicer.xml file:
![changed_gelblockModel_femur](https://user-images.githubusercontent.com/56734075/67495965-b159ab00-f649-11e9-8bbb-883e1baf26f5.PNG)
But, it looks like it's not having any affect because Slicer is giving the same image as above:
![same_image](https://user-images.githubusercontent.com/56734075/67496018-c5051180-f649-11e9-99d5-4c260cd0b595.PNG)

In the file above. the Spatial model was being changed so I tried changing both the gel and femur model, saved the xml file and then reloaded the scene but it doesn't seem to be making any changes.

**Comment by lassoan** [comment]
Amount of reflection from the surface is determined by acoustic impedance difference, which is computed from density and sound velocity. Make sure gel's and bone's impedance is sufficiently different and then you will get strong reflection from the first gel->bone surface and no reflection from the bone->gel surface. You may also increase attenuation in the bone to indicate that sound does not get far in bone. 

Reflection coefficients should be mostly between 0-1. You can boost it a bit to get brighter reflection but 100 is a bit excessive.

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
