### ISSUE TITLE
No 3dConnexion SpaceNavigator data stream

### ISSUE THREAD

**Issue by caioath** [PlusToolkit/PlusLib#624]
Hi all

Would like some help for a project for pre-planning osteotomies.

I have no data streamed from the 3dConnexion mouse. 

Plus server (tested 64 and 32 versions) connects to the device and with Slicer through IGT link. I can see the transform in Slicer (NavigatorToTracker), but it does not change when I move the mouse.

Thanks in advance

Caio

___
Connection successful!

Broadcasting tool tracking data through OpenIGTLink

Plus OpenIGTLink server listening on IPs: 169.254.179.126, 169.254.61.174, 169.254.145.139, 192.168.1.73, 169.254.85.110, 127.0.0.1 -- port 18945

![image](https://user-images.githubusercontent.com/48572581/67513207-3dba9c80-f64f-11e9-921a-9a5a425c02d3.png)

![image](https://user-images.githubusercontent.com/48572581/67513253-56c34d80-f64f-11e9-85f4-e82f43775dbb.png)

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
