### ISSUE TITLE
Modifying Plus USsimulator to use with real tracker

### ISSUE THREAD

**Issue by Arya-Prasad** [PlusToolkit/PlusLib#626]
I am trying to modify the US Simulator to use with Ascension TrakSTAR system. I'm using PlusDeviceSet_Server_SimulatedUltrasound_3DSlicer.xml configuration file. The simulator is not working when loaded as such on 3DSlicerIGT. Also I tried adding the "Ascension 3DG" tracker device in the XML file to use with real tracker. Is there a tutorial on how to get this working? Thanks

**Comment by Sunderlandkyl** [comment]
When is it not working, when you use the original config file with Slicer, or with the Ascension.
Can you upload a log file?

**Comment by Arya-Prasad** [comment]
When I use the original PlusDeviceSet_Server_SimulatedUltrasound_3DSlicer.xml and launch the server, I get the following message in the logs: 
|WARNING|368.008000|SERVER> Simulated US image generation is skipped, as no updated tracking data has become available since the last generated image (at 25.078). Probably the tracker device acquisition rate is lower than the simulator acquisition rate. Device ID: VideoDevice| in .\..\..\PlusLib\src\PlusDataCollection\UsSimulatorVideo\vtkPlusUsSimulatorVideoSource.cxx(96)

I can see the transforms when I load the SimulatedUltrasound_Scene.mrb in 3D slicer. Changing the ProbeToTracker and NeedleToTracker transforms does not seem to do anything.

Please see the modified xml file here: https://gist.github.com/Arya-Prasad/e2e331c6326c2e13a9f2819278b9d7b7
I can launch server without issues using this file, but I receive only 'ReferenceToTracker' transform

I'm on Slicer 4.10.2 and PlusApp-2.3.0.4819-win32

**Comment by Sunderlandkyl** [comment]
Can you try with the latest nightly Plus?
http://perk-software.cs.queensu.ca/plus/packages/nightly/

**Comment by Arya-Prasad** [comment]
I tried with PlusApp-2.9.0.20191023-Win32 nightly build. I get the same warning in the logs( is that normal?) Can change translation and rotation using ProbeToReference and NeedleToReference. Still cannot change ProbeToTracker and NeedleToTracker transforms by using the sliders. Am I missing anything here?

**Comment by Arya-Prasad** [comment]
Yes
![Capture](https://user-images.githubusercontent.com/33341121/68400218-a755a300-0145-11ea-90ce-a17590b11b86.PNG)

**Comment by Sunderlandkyl** [comment]
The warning messages are normal. I just tested with the same version of Plus/Slicer and didn't run into any problems. Moving the ProbeToTracker and NeedleToTracker transforms in the Transforms module updated everything as expected.

Could you upload your Plus and Slicer log files?

**Comment by Arya-Prasad** [comment]
[110719_161804_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/3821760/110719_161804_PlusLog.txt)
![Slicerlog](https://user-images.githubusercontent.com/33341121/68429044-59f42880-017b-11ea-85cc-f08964734da4.PNG)

**Comment by Sunderlandkyl** [comment]
Can you upload the full Slicer log file?
You should be able to find it under the help menu.

**Comment by Arya-Prasad** [comment]
[Slicer_28257_20191108_094324.log](https://github.com/PlusToolkit/PlusLib/files/3825005/Slicer_28257_20191108_094324.log)

**Comment by Sunderlandkyl** [comment]
Ok, so there are a couple of things that I see.
In your modified config file you send transforms for ProbeToTracker, ReferenceToTracker, and NeedleToTracker.
These are transforms that are sent from Slicer to Plus, so it is probably causing issues to send them from Plus to Slicer.

If you use the unmodified config file, are you able to use the ultrasound simulator successfully?
https://github.com/PlusToolkit/PlusLibData/blob/master/ConfigFiles/PlusDeviceSet_Server_SimulatedUltrasound_3DSlicer.xml

**Comment by Arya-Prasad** [comment]
Oh sorry, I've been using the unmodified config file and that's when I get these errors in Plus and Slicer. I've not tried the modified config file yet.

**Comment by Sunderlandkyl** [comment]
Ok, sounds good.

I've added some more debug messages to the ultrasound simulator device.
Can you download and try the latest nightly tomorrow with log level set to debug?
