### ISSUE TITLE
Portable Wifi Ultrasound UProbe Device

### ISSUE THREAD

**Issue by arpinerap** [PlusToolkit/PlusLib#627]
I have a portable US device and i should like to connect it to Slicer throw Plus.
Model device is Mides L7cs but i think it´s some king of Sonostar device because it uses same software in windows (WirelessUSG).
It runs a wifi network where you have to connect to with a serial as password. Then software shows images you can process.
Is there any way to send them to Slicer?
Thanks.

**Comment by adamrankin** [comment]
Does the manufacturer offer an API to receive images (like a device SDK or similar)?

If not, you could screen grab with software and stream it to Plus.

**Comment by arpinerap** [comment]
I have contact manufacter about this item but i´m waiting for response.
How should i do "screen grab with software and stream it to Plus"? Do you have any tutorial?
Thanks

**Comment by adamrankin** [comment]
You could OBS to capture your desktop, install something like this

https://obsproject.com/forum/resources/obs-virtualcam.539/

to output it as a directshow (webcam), and then use one of the Plus webcam devices (vfw, opencv).
