### ISSUE TITLE
Two webcam opticalmarkertrackers at same time

### ISSUE THREAD

**Issue by arpinerap** [PlusToolkit/PlusLib#628]
Hi,
I´ve been trying to use 2 webcams at same time tracking the same marker.
Till now, i can track with both cameras same marker but it just work if they are sending to the same transform, so model asigned to this transform becomes position inestable depending on which camera is seeing it.
I tried to change the output transform name but then, marker is not recognized...

DefaultClientInfo
      MessageTypes
               Message Type="TRANSFORM" /
      /MessageTypes
      TransformNames
               Transform Name=**"Marker2ToTracker2"** /
      /TransformNames
    /DefaultClientInfo

If I could link any marker to any transform, I think it should work properly as a multitracker system.

[PlusDeviceSet_Server_OpticalMarkerTracker_Mmf2.zip](https://github.com/PlusToolkit/PlusLib/files/3855994/PlusDeviceSet_Server_OpticalMarkerTracker_Mmf2.zip)

**Comment by Sunderlandkyl** [comment]
You'll need to change the ToolReferenceFrame of TrackerDevice2 to Tracker2.
