### ISSUE TITLE
Build Installation package 

### ISSUE THREAD

**Issue by carlos-luque** [PlusToolkit/PlusLib#630]
Hello everyone, 
   
I´d like to package a custom Plus toolkit and I couldn´t find the target o command to do that. I´m using the Visual Studio 2019 community with Visual Studio 2015 toolset and Windows 10. Also, I installed the NSIS

I see the nightly packages are done in PlusApp. I read the documentation and checked the commands used in dashboard, but they don´t give me any hint.

Is there anybody could tell me the command (cmake or others) or project in Visual studio or target to package a built Plus toolkit?  

Thanks in advance.

**Comment by Sunderlandkyl** [comment]
You can run CreatePackage.bat in the PlusApp-bin directory.

**Comment by carlos-luque** [comment]
Thanks so much. I generated the installation package. 
Is there any way to indicate the configuration files included in the folders "config" and "data" of the package?

**Comment by adamrankin** [comment]
That is modified in one of the config files. One sec, I'll look it up.

**Comment by adamrankin** [comment]
https://github.com/PlusToolkit/PlusApp/blob/master/InstallFiles.cmake

**Comment by carlos-luque** [comment]
Thanks. I see the files :) and I will modify it to include the configuration files I want to.
