### ISSUE TITLE
Send a command to a device or interact with a device 

### ISSUE THREAD

**Issue by carlos-luque** [PlusToolkit/PlusLib#637]
Hello everyone, 
   
 I´d like to know if it is possible to send a command to a device or to interact with a device from Plus server. 
I want to add a method for calibration in thermal expert Q1 device. I´d rather invoke the new method any time when the device is acquired images. For example the new method is invoked from Slicer.

I see some devices have the method FreezeDevice, but nothing invokes it.  How can I use it?

Thanks in advances.

**Comment by adamrankin** [comment]
Hi Carlos,

If you want the command to be invoked from a client, see the PlusCommand infrastructure.

https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusServer/Commands/vtkPlusCommand.h
https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusServer/vtkPlusCommandProcessor.h

Instigated here:
https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusServer/Tools/PlusServer.cxx#L164

and command received & processed here:
https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusServer/vtkPlusOpenIGTLinkServer.cxx#L647

command used to be sent (and can still be sent) using the IGTL STRING message, but this is deprecated. Please send a [COMMAND](https://github.com/openigtlink/OpenIGTLink/blob/release-3.0/Documents/Protocol/command.md) message.

Let me know if you have any specific questions!

An example is here:
https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusServer/Commands/vtkPlusStartStopRecordingCommand.h

**Comment by carlos-luque** [comment]
Thanks so much.  I will study the links and the example.

**Comment by carlos-luque** [comment]
I has a doubt about a setter method in device command. I see a setter method is invoked, but it is not defined in the device command header. The methods are each device command : SetVolumeReconstructorDeviceId, SetCaptureDeviceId, SetClariusDeviceId, and SetStealthLinkDeviceId. 

Could you help me to understand where this method is created?

Thanks in advance

**Comment by Sunderlandkyl** [comment]
The SetXYZDeviceId methods are created with vtkSetStdStringMacro in the command header:

Ex:
https://github.com/PlusToolkit/PlusLib/blob/b04613863f6f20c31a6851901fcd3317e042b6f7/src/PlusServer/Commands/vtkPlusClariusCommand.h#L60

**Comment by carlos-luque** [comment]
Hello Kyle, 
  
    Thanks so much for your reply. I found the macro definition in igsioCommon.h
