### ISSUE TITLE
I want to know which reconstruction algorithm PLUS uses?

### ISSUE THREAD

**Issue by zhaobingshuai** [PlusToolkit/PlusLib#638]
The real-time reconstruction algorithms of 3D voxel representation can be classified into 3 types based on implementation: that is, Voxel-Based Methods (VBMs), Pixel-Based Methods (PBMs), and Function-Based Methods (FBMs). I want to know which reconstruction algorithm PLUS uses?

**Comment by Sunderlandkyl** [comment]
Plus uses a pixel-based method of volume reconstruction:
>... each pixels of slice is inserted into a volume (distribution step). Each pixel value is inserted either into the spatially nearest single voxel or into the spatially nearest set of 8 voxels according to options specified in the config file.

Here is the information on the volume reconstruction algorithm: http://perk-software.cs.queensu.ca/plus/doc/nightly/user/AlgorithmVolumeReconstruction.html
