### ISSUE TITLE
ArUco Marker Shows Up as Needle Model Instead of Square

### ISSUE THREAD

**Issue by jennyrhodes** [PlusToolkit/PlusLib#639]
Hi everyone. I am using Plus Toolkit + Slicer IGT to track arUco markers with a webcam. Currently, the marker shows up as a needle model in 3D Slicer. How do I change this to a square that represents the shape of the marker?

Additional Context:
One arUco marker will go on a skull model so I can rotate the physical skull and have it reflected virtually in 3D Slicer. I will do this by using a separate stylus (that has another arUco marker) and doing landmark registration on the marker. 

My issue is that I don't know how the needle model generated for the arUco marker corresponds to the marker's actual shape (square). Is it just a horizontal line going through the midpoint of the marker? It would be easier to perform landmark registration if the marker was presented as a square.

Here is a picture for a better explanation:
<img width="576" alt="ARUCO" src="https://user-images.githubusercontent.com/43787082/72125405-127e4a00-332e-11ea-88e6-f2a12a0ed212.png">

Sorry if this is a basic question and thanks in advance for the help!

**Comment by Sunderlandkyl** [comment]
You can look at this scene to see how the marker squares are attached within Slicer: https://github.com/PlusToolkit/PlusLibData/blob/master/ConfigFiles/OpticalMarkerTracker/OpticalMarkerTracker_Scene.mrb

If you want to show the location of the tip of the tool, you can perform a pivot calibration to calculate ToolTipToTool transform, and add a needle model to that transform. Marker3 in the scene above shows an example.

See the pivot calibration tutorial here: http://www.slicerigt.org/wp/user-tutorial/

**Comment by jennyrhodes** [comment]
Thank you for your fast reply.

I think what is confusing me is how the program knows to put the center of the marker in the center of the virtual 3D square. I understand how this works with a needle model because we have pivot/spin calibration, but I get confused with any other type of model.

Let's say I use the IGT module in slicer in the following way:

Create a 50mmx50mmx1mm square model called **Marker3Model**
Use Plus Toolkit to get **Marker3toTracker** transform

Then under data, I create the following hierarchy:
```
Marker3ToTracker
      Marker3Model
```

**Would slicer automatically place the center of the marker in the center of 3D square?** Or do I need to perform landmark registration between the physical vs. virtual marker?

Does my question make sense? If not, I can try to explain more.

Building upon this scenario, if I then put Marker3 on a cylinder in physical space, I would then need to recreate this in virtual space. This is where I get even more confused on how to do this.

I could use the IGT module in slicer to do the following:
Create the virtual cylinder model and call it **CylinderModel**

**Then I get confused on how to create the hierarchy and how to link Marker3 to the cylinder model.**

I apologize for my lengthy post. I am just having difficulty understanding the concepts despite going through the tutorials.

Thanks again for all of the help.

**Comment by lassoan** [comment]
[U-12 Landmark Registration tutorial](http://www.slicerigt.org/wp/user-tutorial/) explains how to register a marker to an object with arbitrary shape (based on landmarks that you can identify on your 3D model and you can touch with your calibrated stylus on the real 3D object).
