### ISSUE TITLE
SonixPortaVideo: Transducer Motor Transformation missing

### ISSUE THREAD

**Issue by JFDamasceno** [PlusToolkit/PlusLib#640]
Hi!
I'm working with SonixPortaVideo to stream my US images to Slicer. The equipment I'm using is the Ultrasonix SonixTablet with Exam version 6.1, SDK 6.1.3 and a 4DEC9-5/10 probe with a sweeping motor on the transducer. 
I based my config xml file on the example of the User Manual and got it to stream the images, but the sweeping motor transformation matrix seems to be static while the motor is moving. The transformation matrices i'm looking at are: ImageToTransducer, MotorRotatedToTransducer and MotorToMotorRotate. These matrices remain constant during all the acquisition, which i verified by observing with slicer. I'm sending my config file attached. Where the problem might be?
Thank you in advance
José Damasceno

[test.txt](https://github.com/PlusToolkit/PlusLib/files/4046355/test.txt)

**Comment by Sunderlandkyl** [comment]
@lassoan

**Comment by lassoan** [comment]
Motor position computation was developed for 4DL14-5/38 and it may not be directly applicable to 4DEC9-5/10 probe as it lacks some of the sensors that are needed for robust and accurate absolute acquisition of motor position. You can go back in the history of vtkPlusSonixPortaVideoSource.cxx to see how position information was obtained earlier (using a less robust but potentially compatible with 4DEC9-5/10) and try to use that. You may also study Ultrasonix examples and Propello example application to get inspiration.

Unfortunately, all Ultrasonix products have been discontinued and no more support is available. We will use our systems as long as they still work but are moving on to other devices (Telemed and BK) and external tracking.

**Comment by JFDamasceno** [comment]
Now i understand. Thank you.
