### ISSUE TITLE
Pivot Calibration Constantly Failing

### ISSUE THREAD

**Issue by jennyrhodes** [PlusToolkit/PlusLib#641]
Hi everyone. I am trying the arUco webcam project. I am using the 50mm Marker 4 on a stick. I am attempting to do pivot calibration with little success. Even when it says I have <1mm RMS error, it is 100% wrong (ie, it is VERY obvious the needle/marker are not lined up). 

I am using the built in webcam on my surfacebook. 

For pivot calibration, I have tried slow pivots, fast pivots, exaggerated pivots, etc. but nothing has produced accurate or even close to accurate results. Also, I have completed camera calibration with a RMS error <1. 

If I had to guess, the main issue is depth, which I know isn't great with arUco markers, but there has to be a way to improve this.

Any ideas how to resolve this problem and get a better pivot calibration?

**Comment by jennyrhodes** [comment]
Also please note: I have completed camera calibration with a RMS error <1. Whenever I open the aruoc_calibration.exe program and use its video capture, the aruco_calibration.exe program has no issue identifying the marker identity at all. It's only when I broadcast through slicer with plus that there is an issue. The video quality is horrendous and lags so bad.

**Comment by Sunderlandkyl** [comment]
Can you upload your config file?

**Comment by jennyrhodes** [comment]
Yes, here is a config file for marker 3 and 4 (as .txt and .pdf file because it would not let me upload as .xml). It was lagging very bad until we changed MaxTimeSpentWithProcessingMS value to zero.

We are currently using built in surfacebook webcam. Would it help to use a real sense depth camera? We have an intel realsense depth camera d435.

[TrackMarker3-4.pdf](https://github.com/PlusToolkit/PlusLib/files/4054441/TrackMarker3-4.pdf)
[TrackMarker3-4.txt](https://github.com/PlusToolkit/PlusLib/files/4054443/TrackMarker3-4.txt)

Thank you again for your assistance.

**Comment by Sunderlandkyl** [comment]
You might try lowering the resolution of your webcam to something like 640x480.

I've had issues with lag using the OpticalMarkerTracker with my Surface Book in the past, and I've found that reducing resolution helps performance greatly.

For the issue with pivot calibration, can you save and send me the Slicer scene that you are using?

**Comment by jennyrhodes** [comment]
I tried lowering the resolution a bit and it seemed to help. I could not lower it to 640x480, no matter how I window leveled the volume, I could NOT get an image to show up. With the lower resolution, the image quality appears slightly wavy? **Would you recommend trying out the Intel Real Sense?**

With that said, **Slicer Scene + other files are attached as a .zip.** I used the 80mm Marker 1 for this scenario. Tried using different color background (white vs. black) and different lighting with little change in results. 

For this, I cannot get a RMS error under about 5mm with pivot calibration. Quite often I have been getting the "N/A not enough variation in transforms" error. Pivot calibration seems pretty hit or miss...I've gotten <1mm and it looks totally off and now I get about 5mm and can't get under that. Consistency has definitely been an issue.

Please let me know if you have any suggestions. Thanks again for the help.


[Slicer_80mm_1M.zip](https://github.com/PlusToolkit/PlusLib/files/4056888/Slicer_80mm_1M.zip)

**Comment by Sunderlandkyl** [comment]
As you've noticed, the RMS of the pivot calibration is very susceptible to the stability of the tracking.
I don't know if the RealSense would make much of a difference, but it might be worth trying. There was some development to utilize both the video and depth feeds from the RealSense to improve optical marker tracking.

@markasselin did you implement the OPTICAL_AND_DEPTH option for the optical marker tracker, or do you have any suggestions for improving optical marker tracking accuracy?

**Comment by lassoan** [comment]
> I tried lowering the resolution a bit and it seemed to help. I could not lower it to 640x480, no matter how I window leveled the volume

If you change the resolution then you may need to recalibrate your camera.

**Comment by jennyrhodes** [comment]
I went ahead and recalibrated after changing the resolution, but I am still having issues with getting a lower RMS error. 

Attached is a short video of a few calibration attempts (exaggerated pivot vs. small pivot). 

One issue might be the "autofocus" feature of the surfacebook's webcamera. Throughout the video, you can see the camera zoom in and out ever so slightly. I am looking into changing this. 

Another issue that might be affecting pivot calibration results is the lag. It might be difficult to tell in the video, but it is a lagging a few seconds from real time. At the very end of the video, you can see where the video feed freezes and then everything crashes. This happens **very often** whenever I use the plus server and 3D slicer. Sometimes I can only broadcast about 2 minutes before having to restart everything, and sometimes it works for longer. 

I have tried to use the plus server on several different internet connections and am still having this issue of extreme lag and constant crashing (which is making pivot calibration difficult). 

**Do you have any advice on how to fix this? I'm hoping better communication between the two programs might lead to better pivot calibration.**

Thanks again for the advice. 

[upload.mp4.zip](https://github.com/PlusToolkit/PlusLib/files/4062916/upload.mp4.zip)

**Comment by markasselin** [comment]
@Sunderlandkyl Yes, I did try implementing sensor fusion of the optical and depth streams, **but I don't recommend using it**. We found this improved accuracy, but still not enough to make this technique generally usable, and it adds computation time negatively affecting framerate. The (badly out of date) results of this experiment can be found [here](https://github.com/markasselin/PlusLib/tree/omt-sensor-fusion) for anyone who is curious.

@jennyrhodes I think you've hit on the primary issue here with the autofocus. I found in my original testing of the OpticalMarkerTracker PLUS device that autofocus severely negatively impacted tracking quality. This is true for any camera, not just on Surface Books. My guess as to why is that the while the autofocus is running the frames are blurry and Aruco (the underlying computer vision library) fails to detect the marker. Then it takes some frames to narrow down the marker position again, from the out of date prior position. Best is to turn autofocus off if you can!

As per the crashing, I have seen this behaviour on surface books in the past when using OpticalMarkerTracker but I myself don't have access to one for testing. If you're comfortable with building software you could try doing a debug build and letting that run until you experience the crash. The hope is that the debugger may provide some useful information about what is causing this.

One final thing you can do to improve accuracy is to calibrate close to the camera. This way the markers are as large as possible, and the Aruco accuracy is optimized.

**Comment by jennyrhodes** [comment]
Hi everyone and thank you for your comments!

I was able to get the RMS error at about 0.1 mm consistently, which should work for our purposes.

1. Auto-focus was a huge issue. Getting rid of auto-focus helped tremendously.

2. Instead of using a wifi connection, we hard-wired our computer into our ethernet cord. We have not experienced any lagging or crashing since then.

3. Calibrating close to the camera also helped. Thank you for this suggestion.

Thanks again for all of the help!

**Comment by lassoan** [comment]
> sensor fusion of the optical and depth streams, but I don't recommend using it. We found this improved accuracy, but still not enough to make this technique generally usable, and it adds computation time negatively affecting framerate.

We still need to fix this at some point, as we need the depth sensor's one magnitude better distance measurement,

**Comment by markasselin** [comment]
> We still need to fix this at some point, as we need the depth sensor's one magnitude better distance measurement,

@lassoan I agree! The code I have is written for the old (SR300 old) RealSense SDK, so it will need to be significantly updated. Let's talk about this at Project Week.
