### ISSUE TITLE
Unable to perform spatial calibration on laparoscopic US probe

### ISSUE THREAD

**Issue by MaXZon3** [PlusToolkit/PlusLib#642]
Hi PlusToolkit team,

Happy new year ! :tada: 

Once again we tried to perform a US probe calibration but we are facing some difficulties. :sweat_smile: 

# Context

This time, we would like to calibrate a small laparoscopic US probe.

![IMG_20200113_151237](https://user-images.githubusercontent.com/15032112/72262573-81ea8700-3617-11ea-938d-9711cd427af0.jpg)
![IMG_20200113_151220](https://user-images.githubusercontent.com/15032112/72262574-81ea8700-3617-11ea-8c0e-7c6d2b79e437.jpg)

To do so, we designed a dedicated phantom that we 3D printed.

![fOptiCal1 1](https://user-images.githubusercontent.com/15032112/72262720-be1de780-3617-11ea-9bf0-ef7a1a698037.png)

The idea here is to optically track this laparoscopic US probe so we developed a software that send the position of tracked objects (pointing device, phantom and US probe) through IGTL and send them to `fCal`.

![IMG_20191210_121410](https://user-images.githubusercontent.com/15032112/72262938-31bff480-3618-11ea-8de1-1c0bfb5692e9.jpg)
![IMG_20191210_121231](https://user-images.githubusercontent.com/15032112/72262946-34bae500-3618-11ea-9e81-96b7db07b7f0.jpg)

We successfully compute the pointer tool calibration, phantom registration and temporal calibration.

# Problem

When trying to compute the spatial calibration, the points never turns green, even after computing the spacing values (with green and blue slider).

We crop the image as close as possible to the border of the US image.

When giving `Max. candidate` to 9, it looks like we correctly have 9 red points but never turns green.

I know that the image is not very good but we didn't manage to get a better image quality.

# Help

That's why I'm currently writing this ticket. I have no idea why `fCal` is not able to, at least, correctly detects the wires in the US image.

- Do I miss something in the software?
- Is my configuration file very bad?
- Are the wires coordinates wrong (we already triple checked but it can still be possible)?
- Is the image quality too bad?

You can find some data and a recorded video performed with `fCal` [here](https://owncloud.ircad.fr/index.php/s/IlglNnoBzueRRLM) (config file, `.mha` video, phantom `.stl`).

Thank you very much for your ideas. :bowing_man:

**Comment by Sunderlandkyl** [comment]
Within the recorded file, your ProbeToTracker transform never changes.
Can you confirm that probe tracking is set up correctly?

**Comment by MaXZon3** [comment]
Yes, the probe wasn't tracked by the camera at this moment.

Does the probe need to be tracked to activate the wire detection in the US image?

**Comment by Sunderlandkyl** [comment]
Yes, the probe needs to be tracked.

**Comment by MaXZon3** [comment]
Oh, ok.

I'm pretty sure that the probe was tracked during our failed tries but we will check again and give some new data.

I let you know if it works or not asap. :wink:

**Comment by MaXZon3** [comment]
Hi,

[Here are some new data](https://owncloud.ircad.fr/index.php/s/Z5Dxplsc3veMmHY) acquired by the team with a particular attention on tracking when trying to perform the spatial calibration.

We weren't able to successfully identify the points in the images (never turns green) despite that they are well recognize by the dot detection algorithm (red points in the parameter window).

**Comment by MaXZon3** [comment]
> Hi,
> 
> [Here are some new data](https://owncloud.ircad.fr/index.php/s/Z5Dxplsc3veMmHY) acquired by the team with a particular attention on tracking when trying to perform the spatial calibration.
> 
> We weren't able to successfully identify the points in the images (never turns green) despite that they are well recognize by the dot detection algorithm (red points in the parameter window).

Hi, I hope everything goes well for you guys.

Do you have any update about this issue? Does the given fits the needs to understand what's happening?

Let me know if you need further information. :)

**Comment by Sunderlandkyl** [comment]
I think that your Segmentation parameters need to be tuned. @lassoan do you know which parameters need to be changed? I have the recorded sequence set up in fCal if you need to take a look.

**Comment by lassoan** [comment]
If points are detected but the points are not green then most likely the approximate spacing values are too far from the correct values.

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
