### ISSUE TITLE
Stealthlink version

### ISSUE THREAD

**Issue by RemiDelaunay** [PlusToolkit/PlusLib#644]
Hi,

We are having issues streaming data from the new StealthStation S8 using PLUS. Everything works fine like with the S7 except when trying to export the MR model from the Stealth. I know the StealthLink version on the S8 is 2.2 and I was wondering if the PLUS binaries are compiled with this version ? We are still waiting for the updated StealthLink library so we haven't try to build it ourselves yet.

Thank you for your help.

Best,

Remi Delaunay

**Comment by Sunderlandkyl** [comment]
The current version of the StealthLink libraries in Plus are 2.1.
I made a request for updated libraries (specifically for a more recent Visual Studio version) several months ago, but haven't received them yet.

I'll send them another email and see if we can get some updated libraries.

The other thing is that our StealthStation is currently running Synergy Cranial 2.2.6. Depending on the compatibility of the StealthLink libraries, it may be some time before we can upgrade and test with the newer version.

**Comment by RemiDelaunay** [comment]
Yes we have made the same requests to Medtronic. Thank you for your prompt answer !
