### ISSUE TITLE
Create a time sequence .mha file from .png images.

### ISSUE THREAD

**Issue by joshleiph** [PlusToolkit/PlusLib#645]
I have a number of png ultrasound images, and I want to create a mha or mhd time sequence file so that I could then load that file into the 3D Slicer program. I found some code from "PlusMatlabUtils" that can be used in Matlab to create volume mha files [https://github.com/PlusToolkit/PlusMatlabUtils/tree/master/MatlabMetafileIO](url), specifically the mha_write_volume function. However, this just creates voume mha files, and does not contain features for adding timestamp information to each png information.

I am wondering if there is a way to create either a mha or mhd time sequence files utilizing png images.

**Comment by lassoan** [comment]
You can probably import a sequence of pngs using MultiVolumeImporter module then convert it to Volume sequence (by saving to nrrd file and load it as Volume sequence). You can add fields (timestamps, transforms, etc.) using [EditSequenceFile](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/ApplicationEditSequenceFile.html) tool. However, process is quite complicated overall, so I would recommend to use a custom importer script instead.

I don’t think anyone has implemented a png importer script, but it would be useful to have and should not be longer than 20-30 lines in Python. We'll provide one soon.
