### ISSUE TITLE
Using different brands of ultrasound machines with Plus

### ISSUE THREAD

**Issue by eibhinwhite** [PlusToolkit/PlusLib#649]
I am currently trying to use an ultrasound machine connected to the plus App for use in Slicer. I'm wondering is it possible to connect any brand of ultrasound machine to Plus or is it specifically suited for Ultrasonix machines? Does the Sonixvideo only work with Ultrasonix machines?

**Comment by adamrankin** [comment]
You can use any ultrasound machine provided you can capture the ultrasound image in some way. The SonixVideo API allows capture of Ultrasonix machines, but Plus supports multiple capture interfaces.

What kind of US machine are you using?

**Comment by eibhinwhite** [comment]
It would be a Siemens ultrasound machine.

**Comment by adamrankin** [comment]
Unfortunately we don't have an interface for Siemens machines. A workaround is to use a screen capture device or software, depending on how the Siemens machine works.
