### ISSUE TITLE
Device configuration directory issue

### ISSUE THREAD

**Issue by eibhinwhite** [PlusToolkit/PlusLib#650]
I have written a code for using an ultrasound machine along with the optical tracker configuration and saved the xml file to my computer. However, when I open the Plus Server Launcher and set the 'set device configuration directory' to the location containing the file, the file does not appear in the drop down 'device set'. I'm wondering what action I my be taking incorrectly for it not to be showing up in the dropdown menu?

**Comment by adamrankin** [comment]
Click the circle in the bottom right to access the log. It might show an error which can help identify the issue.

Adam

**Comment by eibhinwhite** [comment]
This is what appears when I do this. I can't seem to figure out what needs to be changed.
![image](https://user-images.githubusercontent.com/57176240/72913942-ce2f7880-3d35-11ea-856e-af7c114262cd.png)

**Comment by adamrankin** [comment]
Ah... damn. I have no idea.
The only thing that may be strange is that you've selected `.../config/Config` as a directory? Maybe just one `/config`?
