### ISSUE TITLE
Intel realsense - plus config file for Aruco with depth

### ISSUE THREAD

**Issue by may1968** [PlusToolkit/PlusLib#655]
Hi,
I have managed to get marker tracking with Intel RealSense D415, colour image. 
The depth image can be streamed to Slicer, but not used for tracking. I tried integrating Marker and Realsense xml files, but this failed. I came across this - https://github.com/PerkLab/DepthImageToPointCloud But not sure if this would achieve what is needed and does not seem to be implemented as formal slicer extension yet. @markasselin also said an earlier integration of the 2 RealSence streams was not worth pursuing. 
thanks, John
Cape Town

**Comment by markasselin** [comment]
Hi John,

Could you please post your config file here, this will aid us immensely in helping you.

The DepthImageToPointCloud extension you link here will allow you to visualize the depth data in 3D in Slicer, but you are correct that it will not allow you to improve the tracking quality. To install this extension, simply clone the repository, then in Slicer choose Edit -> Application Settings -> Modules (on the left sidebar) -> then drag and drop the DepthImageToPointCloud.py file into the additional module paths list.

I still have a branch which does [use the depth data to improve the tracking quality
](https://github.com/markasselin/PlusLib/tree/omt-sensor-fusion), but it is stale and needs to be updated for the new RealSense SDK.

Cheers,
--Mark
