### ISSUE TITLE
Marker 'pose estimation failed' optical tracking in slicer

### ISSUE THREAD

**Issue by eibhinwhite** [PlusToolkit/PlusLib#656]
Hi, I have been previously able to use the markers within thw optical tracker scene and it has worked successfully, but for some reason now it has stopped working and whenever I place a marker in front of the camera, it will tell me which marker it is and that it has failed in plus. I've attached a screengrab below. I'm wondering would anyone have any information on why this might be hapoening? Thanks.
![image](https://user-images.githubusercontent.com/57176240/73766956-b06b0600-476e-11ea-836f-257ddcbe5ae1.png)

**Comment by markasselin** [comment]
Does the marker then become tracked successfully? If I remember correctly ArUco uses the past position of the marker as a starting point for estimating the current pose of the marker. The errors you have attached here are thrown whenever the algorithm is not confident in its pose estimation, and so these errors may just be from the first few frames while the marker is “locked onto”.

**Comment by lassoan** [comment]
Posen estimation fails if the input data is highly inconsistent. Most probably your camera calibration is very inaccurate.

**Comment by markasselin** [comment]
@lassoan has a great suggestion here, recalibrating may be the way to solve this issue. Here are [detailed instructions](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceOpticalMarkerTracker.html) on how to do this.

**Comment by eibhinwhite** [comment]
That worked, thanks for your help.
