### ISSUE TITLE
Volume Rendering with NDI Aurora and BlackMagic Intesity Shuttle 

### ISSUE THREAD

**Issue by cossairt** [PlusToolkit/PlusLib#657]
I have been working with the PlusToolkit and have got the tracking working with the NDI Aurora system but I would like to incorporate an ultrasound feed via a BlackMagic Intensity Shuttle using Decklink and was looking for help with a configuration xml file that would incorporate them both for volume rendering.  Just wondering if anyone has had success using this combination or could provide additional samples/guidance.  Thanks in advance.

**Comment by Sunderlandkyl** [comment]
Haven't tried that combination, but it should work.

You can use this config file as a basis, just switching out the Ascension3DG and SonixVideo devices for Aurora and DeckLink, and adding your own ultrasound calibration matrices:
https://github.com/PlusToolkit/PlusLibData/blob/master/ConfigFiles/PlusDeviceSet_Server_Ultrasonix_C5-2_Ascension3DG_calibrated.xml

**Comment by cossairt** [comment]
Thank You!  I will give it a try once I am back in the lab.  I'm sure I will have to do something in regards to calibrating the probe. I have posted the config file below....  If you happen to see any glaring errors I appreciate the feedback... Thanks.

 <PlusConfiguration version="2.1">

  <DataCollection StartupDelaySec="1.0" >
    <DeviceSet
      Name="PlusServer: DeckLink + Aurora 3D Tracking TESTING"
      Description="Broadcasting ultrasound images acquired from the Decklink through OpenIGTLink. Probe is spatially calibrated for any imaging depth. " />
    <Device
      Id="TrackerDevice" 
      Type="AuroraTracker"
      SerialPort="5"
      ToolReferenceFrame="Tracker" >
      <DataSources>
        <DataSource Type="Tool" Id="Needle" PortName="0" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream">
          <DataSource Id="Needle" />
        </OutputChannel>
      </OutputChannels>
    </Device>

    <Device
      Id="VideoDevice" 
      Type="DeckLinkVideo" 
      FrameSize="640 480"
      CaptureDeviceId="0" >
      <DataSources>
        <DataSource Type="Video" Id="Video" PortUsImageOrientation="MF" ImageType="RGB_COLOR"  />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStream" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>

    <Device 
      Id="TrackedVideoDevice" 
      Type="VirtualMixer" >
      <InputChannels>
        <InputChannel Id="TrackerStream" />
        <InputChannel Id="VideoStream" />
      </InputChannels>
      <OutputChannels>
        <OutputChannel Id="TrackedVideoStream"/>
      </OutputChannels>
    </Device>

    <Device
      Id="CaptureDevice"
      Type="VirtualCapture"
      BaseFilename="Recording.igs.mhd"
      EnableCapturingOnStart="FALSE"
      RequestedFrameRate="15" >
      <InputChannels>
        <InputChannel Id="TrackedVideoStream" />
      </InputChannels>
    </Device>

    <Device
      Id="VolumeReconstructorDevice"
      Type="VirtualVolumeReconstructor"
      OutputVolDeviceName="Volume_Reference"
      EnableReconstruction="FALSE" >
      <InputChannels>
        <InputChannel Id="TrackedVideoStream" />
      </InputChannels>
      <VolumeReconstruction
        ImageCoordinateFrame="Image" ReferenceCoordinateFrame="Reference"
        CompoundingMode="MEAN" Interpolation="LINEAR"
        Optimization="FULL" NumberOfThreads="2"
        ClipRectangleOrigin="0 0" ClipRectangleSize="820 616" PixelRejectionThreshold="1"
        OutputSpacing="0.5 0.5 0.5"
        FillHoles="ON" >
        <HoleFilling>
          <HoleFillingElement Type="GAUSSIAN" Size="5" Stdev="0.6667" MinimumKnownVoxelsRatio="0.50001" />
          <HoleFillingElement Type="STICK" StickLengthLimit="9" NumberOfSticksToUse="1" />
        </HoleFilling>
      </VolumeReconstruction>
    </Device>
  </DataCollection>

  <CoordinateDefinitions>
    
    <Transform From="Transducer" To="Probe"
      Matrix="
        0.0034    0.9433   -0.0140  -29.7558
       -1.0000    0.0033    0.0087   -0.0870
        0.0087    0.0132    0.9999   -0.7053
             0         0         0    1.0000" />
  </CoordinateDefinitions>
  
  <PlusOpenIGTLinkServer 
    MaxNumberOfIgtlMessagesToSend="1" 
    MaxTimeSpentWithProcessingMs="50" 
    ListeningPort="18944" 
    SendValidTransformsOnly="true" 
    OutputChannelId="TrackedVideoStream" > 
    <DefaultClientInfo> 
      <MessageTypes> 
        <Message Type="IMAGE" />
        <Message Type="TRANSFORM" />
      </MessageTypes>
      <TransformNames> 
        <Transform Name="ProbeToReference" />
        <Transform Name="StylusToReference" />
        <Transform Name="ReferenceToTracker" />
      </TransformNames>
      <ImageNames>
        <Image Name="Image" EmbeddedTransformToFrame="Reference" />
      </ImageNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>

</PlusConfiguration>

**Comment by adamrankin** [comment]
@cossairt Were you able to get this working?
