### ISSUE TITLE
OpenCL DLL Runtime Errors with Telemed Ultrasound Build

### ISSUE THREAD

**Issue by fergujm2** [PlusToolkit/PlusLib#658]
Hi,

We have used the Telemed MicrUS ultrasound probe successfully with the nightly Telemed Win32 build of Plus.  However, when switching to a different Windows machine, the same build gave us the following runtime errors:

![Capture](https://user-images.githubusercontent.com/38008662/74197718-92494e00-4c25-11ea-8c1c-fa5c030ecb70.PNG)

These errors did not affect our application or data streaming, and we could proceed as normal after closing out of them. It would make our application look more professional if they did not happen though.

Thanks.

**Comment by adamrankin** [comment]
I know this was a while ago, but what graphics cards/drivers were on both machines?

**Comment by fergujm2** [comment]
@brynpitt Do you know these? I know there were no errors on your personal machine, but the errors were thrown on the cart computer that we use in the OR.

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
