### ISSUE TITLE
real-time volume reconstruction in Slicer

### ISSUE THREAD

**Issue by eibhinwhite** [PlusToolkit/PlusLib#659]
Hi,
Im currently trying to reconstruct an arteriovenous fistula using real time ultrasound imaging within Slicer. I have the optical tracking, US probe and ultrasound images (real-time) all loaded into Slicer, however I'm unable to find a suitable configuration file to perform this next step of real-time reconstruction. From previous tutorials, I've seen an 'elbow reconstruction' file being used, however I'm unable to locate this configuration file. I'm wondering would someone be able to point me in the right direction with this, thank you!

**Comment by Sunderlandkyl** [comment]
You can use this config file as a basis, just switching out the Ascension3DG and SonixVideo devices for your tracking and ultrasound devices, and adding your own ultrasound calibration matrices:
https://github.com/PlusToolkit/PlusLibData/blob/master/ConfigFiles/PlusDeviceSet_Server_Ultrasonix_C5-2_Ascension3DG_calibrated.xml

**Comment by eibhinwhite** [comment]
Thank you. Would this allow for 3d reconstruction, as I already have the tracking and ultrasound imaging working within slicer?
