### ISSUE TITLE
Info about comunication between ultrasound device and 3DSlicer

### ISSUE THREAD

**Issue by kiki-ta** [PlusToolkit/PlusLib#661]
Is it possible to establish communication between a new ultrasound device and 3d slicer avoiding the use of plus servers? How?
Thanks

**Comment by adamrankin** [comment]
Yes, the ultrasound machine will have to have an API that can be called.
What make/model ultrasound are you considering?

Or, if you are using a screen grabber, you could see if that grabber has a
python, C++ interface, or network interface.

Adam

**Comment by lassoan** [comment]
The main goal of Plus toolkit is to serve as a bridge between devices and 3D Slicer. If you avoid Plus then you don't have this bridge. You may get access to an image stream via OpenCV but Plus offers background data acquisition, recording, synchronization, broadcasting, etc. Recent Plus and Slicer versions allow automatic launching/stopping of servers, storing Plus configuration file in the Slicer scene. So, Plus now behaves as it was part of Slicer.
