### ISSUE TITLE
Setting image spacing in ultrasound video config file

### ISSUE THREAD

**Issue by brynpitt** [PlusToolkit/PlusLib#663]
Hello all,

I believe this should be a simple question to answer. I am acquiring ultrasound video from a Telemed MicrUS device through PLUS, but the default image spacing (1mm x 1mm x 1mm) is not correct. The image dimensions default to the correct value; however (512px x 512px x 1px).

Is there a way I can set the image spacing in the PLUS config file for my device? 
Is there perhaps a way to determine the image spacing values automatically based on the image depth?

I saw a similar question resolved by creating a scaling matrix in the coordinate definitions: https://discourse.slicer.org/t/unable-to-edit-volume-information-on-ultrasound-image-in-volumes-module/8190/7.

I mostly wanted to check if there is a more direct method for setting this information.

Thanks,
Bryn

**Comment by Sunderlandkyl** [comment]
If you perform an ultrasound calibration to calculate the ImageToProbe matrix, you should get the correct scaling from image to world coordinates.
See the tracked ultrasound calibration tutorial here: http://www.slicerigt.org/wp/user-tutorial/

**Comment by ungi** [comment]
Kyle is right. Also, if you don't need to track the ultrasound in 6 DOF, just need the spacing, then you can check the depth setting of the ultrasound (e.g. 90 mm) and count the pixels in the middle column of the image (e.g. 450), and divide them to get the pixel spacing (e.g. 0.2 mm).
