### ISSUE TITLE
How to run multiple video streams in Slicer?

### ISSUE THREAD

**Issue by Fionahelen** [PlusToolkit/PlusLib#669]
I am trying to stream 2 videos by creating 2 instances of PlusOpenIGTLinkServer in one config file with the same port number. The server does work correctly however when broadcasting the server on slicer only one video will link correctly?

<PlusConfiguration version="2.7">
  <DataCollection StartupDelaySec="1.0">
    <DeviceSet
      Name="PlusServer: OptiTrack Fionas Server"
      Description="Broadcasting tracking data through OpenIGTLink."
    />
    <Device
      Id="TrackerDevice"
      Type="OptiTrack"
      ToolReferenceFrame="Tracker" 
      Profile="OptiTrack/EmptyProfile.xml"
      AttachToRunningMotive="TRUE"
      MotiveDataDescriptionsUpdateTimeSec="1.0" >
      <DataSources>
        <DataSource Type="Tool" Id="fetoscope" RigidBodyFile="fetoscope.tra" />
        <DataSource Type="Tool" Id="ultrasound" RigidBodyFile="ultrasound.tra" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream">
        <DataSource Type="Tool" Id="fetoscope" />
        <DataSource Type="Tool" Id="ultrasound" />
        </OutputChannel>
      </OutputChannels>
    </Device>
    <Device
      Id="VideoDevice" 
      Type="MmfVideo" 
      FrameSize="640 480"
      VideoFormat="YUY2"
      CaptureDeviceId="2" >
      <DataSources>
        <DataSource Type="Video" Id="Video" PortUsImageOrientation="MF" ImageType="RGB_COLOR"  />
      </DataSources>      
      <OutputChannels>
        <OutputChannel Id="VideoStream" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>
   <Device
      Id="VideoDevice2" 
      Type="MmfVideo" 
      FrameSize="640 480"
      VideoFormat="YUY2"
      CaptureDeviceId="0" >
      <DataSources>
        <DataSource Type="Video" Id="Video2" PortUsImageOrientation="MF" ImageType="RGB_COLOR"  />
      </DataSources>      
      <OutputChannels>
        <OutputChannel Id="VideoStream2" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>
    <Device 
      Id="TrackedVideoDevice" 
      Type="VirtualMixer" >
      <InputChannels>
        <InputChannel Id="TrackerStream" />
        <InputChannel Id="VideoStream" />
      </InputChannels>
      <OutputChannels>
        <OutputChannel Id="TrackedVideoStream"/>
      </OutputChannels>
    </Device>
  </DataCollection>
  <PlusOpenIGTLinkServer
    MaxNumberOfIgtlMessagesToSend="1"
    MaxTimeSpentWithProcessingMs="50"
    ListeningPort="18944"
    SendValidTransformsOnly="TRUE"
    OutputChannelId="TrackedVideoStream" >
    <DefaultClientInfo>
      <MessageTypes>
        <Message Type="TRANSFORM" />
        <Message Type="IMAGE" />
      </MessageTypes>
      <ImageNames>
        <Image Name="Image" EmbeddedTransformToFrame="Reference" />
      </ImageNames>
      <TransformNames>
        <Transform Name="FetoscopeToTracker" />
        <Transform Name="UltrasoundToTracker" />
      </TransformNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>
  <PlusOpenIGTLinkServer
    MaxNumberOfIgtlMessagesToSend="1"
    MaxTimeSpentWithProcessingMs="50"
    ListeningPort="18944"
    SendValidTransformsOnly="TRUE"
    OutputChannelId="VideoStream2" >
    <DefaultClientInfo>
      <MessageTypes>
        <Message Type="IMAGE" />
      </MessageTypes>
      <ImageNames>
        <Image Name="Image2" EmbeddedTransformToFrame="Image" />
      </ImageNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>
  <CoordinateDefinitions>
    <Transform From="Image" To="Reference"
      Matrix="
        0.2 0.0 0.0 0.0
        0.0 0.2 0.0 0.0
        0.0 0.0 0.2 0.0        
        0 0 0 1" />
    <Transform From="Image2" To="Image"
      Matrix="
        0.2 0.0 0.0 0.0
        0.0 0.2 0.0 0.0
        0.0 0.0 0.2 0.0        
        0 0 0 1" />
  </CoordinateDefinitions>
</PlusConfiguration>

**Comment by Fionahelen** [comment]
<PlusConfiguration version="2.7">
  <DataCollection StartupDelaySec="1.0">
    <DeviceSet
      Name="PlusServer: OptiTrack Fionas Server"
      Description="Broadcasting tracking data through OpenIGTLink."
    />

    <Device
      Id="TrackerDevice"
      Type="OptiTrack"
      ToolReferenceFrame="Tracker" 
      Profile="OptiTrack/EmptyProfile.xml"
      AttachToRunningMotive="TRUE"
      MotiveDataDescriptionsUpdateTimeSec="1.0" >
      <DataSources>
        <DataSource Type="Tool" Id="fetoscope" RigidBodyFile="fetoscope.tra" />
        <DataSource Type="Tool" Id="ultrasound" RigidBodyFile="ultrasound.tra" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream">
        <DataSource Type="Tool" Id="fetoscope" />
        <DataSource Type="Tool" Id="ultrasound" />
        </OutputChannel>
      </OutputChannels>
    </Device>

    <Device
      Id="VideoDevice" 
      Type="MmfVideo" 
      FrameSize="640 480"
      VideoFormat="YUY2"
      CaptureDeviceId="2" >
      <DataSources>
        <DataSource Type="Video" Id="Video" PortUsImageOrientation="MF" ImageType="RGB_COLOR"  />
      </DataSources>      
      <OutputChannels>
        <OutputChannel Id="VideoStream" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>

    <Device
      Id="VideoDevice2" 
      Type="MmfVideo" 
      FrameSize="640 480"
      VideoFormat="YUY2"
      CaptureDeviceId="0" >
      <DataSources>
        <DataSource Type="Video" Id="Video2" PortUsImageOrientation="MF" ImageType="RGB_COLOR"  />
      </DataSources>      
      <OutputChannels>
        <OutputChannel Id="VideoStream2" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>

    <Device 
      Id="TrackedVideoDevice" 
      Type="VirtualMixer" >
      <InputChannels>
        <InputChannel Id="TrackerStream" />
        <InputChannel Id="VideoStream" />
      </InputChannels>
      <OutputChannels>
        <OutputChannel Id="TrackedVideoStream"/>
      </OutputChannels>
    </Device>
    </DataCollection>

    <PlusOpenIGTLinkServer
    MaxNumberOfIgtlMessagesToSend="1"
    MaxTimeSpentWithProcessingMs="50"
    ListeningPort="18944"
    SendValidTransformsOnly="TRUE"
    OutputChannelId="TrackedVideoStream" >
    <DefaultClientInfo>
      <MessageTypes>
        <Message Type="TRANSFORM" />
        <Message Type="IMAGE" />
      </MessageTypes>
      <ImageNames>
        <Image Name="Image" EmbeddedTransformToFrame="Reference" />
      </ImageNames>
      <TransformNames>
        <Transform Name="FetoscopeToTracker" />
        <Transform Name="UltrasoundToTracker" />
      </TransformNames>
    </DefaultClientInfo>
    </PlusOpenIGTLinkServer>

    <PlusOpenIGTLinkServer
    MaxNumberOfIgtlMessagesToSend="1"
    MaxTimeSpentWithProcessingMs="50"
    ListeningPort="18944"
    SendValidTransformsOnly="TRUE"
    OutputChannelId="VideoStream2" >
    <DefaultClientInfo>
      <MessageTypes>
        <Message Type="IMAGE" />
      </MessageTypes>
      <ImageNames>
        <Image Name="Image2" EmbeddedTransformToFrame="Image" />
      </ImageNames>
    </DefaultClientInfo>
    </PlusOpenIGTLinkServer>

    <CoordinateDefinitions>
    <Transform From="Image" To="Reference"
      Matrix="
        0.2 0.0 0.0 0.0
        0.0 0.2 0.0 0.0
        0.0 0.0 0.2 0.0        
        0 0 0 1" />
    <Transform From="Image2" To="Image"
      Matrix="
        0.2 0.0 0.0 0.0
        0.0 0.2 0.0 0.0
        0.0 0.0 0.2 0.0        
        0 0 0 1" />
  </CoordinateDefinitions>
  </PlusConfiguration>

**Comment by adamrankin** [comment]
It can't be the same port number. Each server instance must run on its own port.

**Comment by Fionahelen** [comment]
If I set one image to a different port I still have the same issue? It also happens when I'm running it as 2 Plus server applications on different port numbers?

**Comment by adamrankin** [comment]
The way to run two image streams is to have the following:

(Two Plus instances can be in either one config file with two server entries, or two config files running in their own application)
```
Plus Instance 1 - port X
Plus Instance 2 - port Y

Slicer - OpenIGTLink Connector A - port X
       - OpenIGTLink Connector B - port Y
```

**Comment by Fionahelen** [comment]
I have set the plus instances to two config files running in their own application and opened these two ports on slicer, both servers are working but the image will still not come through 

![Capture](https://user-images.githubusercontent.com/61281968/75467822-20426a00-5984-11ea-8621-7a6efc7b37bc.PNG)

**Comment by adamrankin** [comment]
Are their any errors or warnings in the Plus log? (Green/Yellow/Red circle in Plus UI)

**Comment by z6zou** [comment]
@Fionahelen Hello, I'm wondering if you have fixed the issue. I'm experiencing the same issue now and would like to get some advice from you.
