### ISSUE TITLE
Errors in build process (Related to vtkPlusClarius.cxx)

### ISSUE THREAD

**Issue by askaderd** [PlusToolkit/PlusLib#675]
Hi All,

I'm having errors pop up when I try to build Plus. I think the issues have to do with Clarius having updated their SDK files (a previous member from my lab group was able to successfully build before this update). Their SDK files are located here: https://github.com/clariusdev/listener

I'm using vtkPlusClarius.cxx and vtkPlusClarius.h with the latest changes (Feb 28, 2020, 6:33 AM PST). I haven't been able to figure out why these errors are occurring (I'm also not too familiar with C++).

Error in Visual Studio:
14>C:\D\clarius\include\listen\listen.h(21): error C3861: 'visibility': identifier not found (compiling source file C:\D\PlusB-bin\PlusLib\src\PlusDataCollection\Clarius\vtkPlusClarius.cxx) [C:\D\PlusB-bin\PlusLib-bin\src\PlusDataCollection\vtkPlusDataCollection.vcxproj]
14>C:\D\clarius\include\listen\listen.h(21): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file C:\D\PlusB-bin\PlusLib\src\PlusDataCollection\Clarius\vtkPlusClarius.cxx) [C:\D\PlusB-bin\PlusLib-bin\src\PlusDataCollection\vtkPlusDataCollection.vcxproj]
14>C:\D\clarius\include\listen\listen.h(21): error C2448: '__attribute__': function-style initializer appears to be a function definition (compiling source file C:\D\PlusB-bin\PlusLib\src\PlusDataCollection\Clarius\vtkPlusClarius.cxx) [C:\D\PlusB-bin\PlusLib-bin\src\PlusDataCollection\vtkPlusDataCollection.vcxproj]
14>C:\D\clarius\include\listen\listen.h(36): error C3861: 'visibility': identifier not found (compiling source file C:\D\PlusB-bin\PlusLib\src\PlusDataCollection\Clarius\vtkPlusClarius.cxx) [C:\D\PlusB-bin\PlusLib-bin\src\PlusDataCollection\vtkPlusDataCollection.vcxproj]
14>C:\D\clarius\include\listen\listen.h(36): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file C:\D\PlusB-bin\PlusLib\src\PlusDataCollection\Clarius\vtkPlusClarius.cxx) [C:\D\PlusB-bin\PlusLib-bin\src\PlusDataCollection\vtkPlusDataCollection.vcxproj]
14>C:\D\clarius\include\listen\listen.h(36): error C2374: '__attribute__': redefinition; multiple initialization (compiling source file C:\D\PlusB-bin\PlusLib\src\PlusDataCollection\Clarius\vtkPlusClarius.cxx) [C:\D\PlusB-bin\PlusLib-bin\src\PlusDataCollection\vtkPlusDataCollection.vcxproj]
14>  C:\D\clarius\include\listen\listen.h(21): note: see declaration of '__attribute__' (compiling source file C:\D\PlusB-bin\PlusLib\src\PlusDataCollection\Clarius\vtkPlusClarius.cxx)

Thanks in advance for any feedback :)

**Comment by adamrankin** [comment]
What version of visual studio?

**Comment by askaderd** [comment]
Visual Studio 2017

**Comment by adamrankin** [comment]
I'm not sure, but it looks like the Clarius SDK doesn't compile with your setup. @Sunderlandkyl You semi-recently updated the Clarius SDK for Queen's. Have you compiled it? Do you need to use v140 for VS2017?

**Comment by Sunderlandkyl** [comment]
I don't recall having to specify v140. I'll take a look at this and see if I can reproduce.

**Comment by Sunderlandkyl** [comment]
I just checked. The version that is on that GitHub repo is incompatible with MSVC.
It will work if you change this line in listen_export.h from:
```define LISTEN_EXPORT __attribute__((visibility("default")))```
to
```define LISTEN_EXPORT __declspec(dllimport)```

**Comment by askaderd** [comment]
Thanks! That seemed to solve all the errors during the build process. However I still can't open the PlusServerLauncher, I keep getting this error: 
![image](https://user-images.githubusercontent.com/58088715/76470895-84b2ef80-63ae-11ea-857f-f307b0f9ffe4.png)

(I get the error saying VCRUNTIME140_1.dll, vtkCommonCore-8.2D.dll, vtkCommonDataModel-8.2D.dll, vtksys-8.2D.dll are not found either). Again any help would be appreciated.

**Comment by Sunderlandkyl** [comment]
Try downloading the Visual Studio 2015 redistributable:
https://www.microsoft.com/en-ca/download/details.aspx?id=48145

**Comment by askaderd** [comment]
How do I make sure the 2015 redestributable file is called? 
Right now I have Visual Studio 2017 with the 2015 Visual C++ redistributable installed. However when running CMake, I get this error:
![image](https://user-images.githubusercontent.com/58088715/76670764-84058f00-654f-11ea-867f-2056836b1bbd.png)

I modified the CMake_Linker input from C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/link.exe to C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\link.exe

I have also tried uninstalling Visual Studio 2017 and installing Visual Studio 2015 but I get the same error.

**Comment by lassoan** [comment]
Redistributable and build toolset are two very different things.

To build Plus, you need to install Visual Studio (Community version is fine) latest version (2019 is fine) with a few build tools (VS2015 and VS2017 should be enough).

To run Plus, you may need to install Visual Studio redistributable packages - whichever is reported to be missing when you attempt to launch a Plus application.

**Comment by askaderd** [comment]
To update, I was able fix this issue once I downloaded the Visual C++ 2015-2019 redistributable file from the link: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads, by selecting vc_redist.x64.exe. 

When I tried downloading the redistributable file from the link Sunderlandkyl provided it required me to replace the 2017 version with the 2015 version which was leading to other issues.

Thanks everyone for your help (including zoez526 who helped resolve the issue)

**Comment by lassoan** [comment]
@askaderd Thanks for the update.

@Sunderlandkyl Could you add this info to the build instructions? https://github.com/PlusToolkit/PlusBuild/blob/master/Docs/BuildInstructionsWindows.md
