### ISSUE TITLE
Slicer Ultrasound Simulation Image

### ISSUE THREAD

**Issue by hripat** [PlusToolkit/PlusLib#676]
Hi,

I'm trying to obtain a simulated US image of a radius bone using Slicer. I previously had used a femur STL file and it worked properly. But now, when I'm using the radius STL file I am not sure why I am not getting a good image of the ultrasound while using Transforms.

This is the picture of the US image that I am getting from Slicer. Is the radius STL file not placed right or is it an issue with the gel block model (I attempted to change the dimensions of it but then changed it back).

![slicer error](https://user-images.githubusercontent.com/56734075/76476884-fbb1ad80-63d9-11ea-8ed1-960cd712cfba.PNG)

**Comment by Sunderlandkyl** [comment]
You probably need to adjust your acoustic parameters for the femur model:
```
<SpatialModel
    Name="Air"
    DensityKgPerM3="1.2"
    SoundVelocityMPerSec="343"
    AttenuationCoefficientDbPerCmMhz="100.0"
    BackscatterDiffuseReflectionCoefficient="0.1"
    SurfaceReflectionIntensityDecayDbPerMm="50"
    />
```

**Comment by lassoan** [comment]
This change might impact you if you use a recent Slicer-4.11 version: https://discourse.slicer.org/t/model-files-are-now-saved-in-lps-coordinate-system/10446

**Comment by hripat** [comment]
@Sunderlandkyl  I already have the same properties in the Plus Files for 3D Slicer

@lassoan I have Slicer 4.11.0 from Oct 1st 2019. I have previously used this model for the same purposes only with a femur STL file. I'm just trying to replace that femur file with a radius STL file and I'm not getting a proper image.

**Comment by hripat** [comment]
Here are the files I am using if that helps.
I've added the GelBlockModel in there because I tried to change the dimensions and it didn't work so I changed it back. I'm using PLUS and Slicer to try to get the simulated US image.

[SimulatedUltrasound_RadiusUSProblem.zip](https://github.com/PlusToolkit/PlusLib/files/4324717/SimulatedUltrasound_RadiusUSProblem.zip)

**Comment by Sunderlandkyl** [comment]
Your models in the Slicer scene don't match the models used in Plus. You can see the correct location if you import the models in slicer using RAS coordinates.

**Comment by hripat** [comment]
@Sunderlandkyl Thank you for the reply. I'm following the link that @lassoan sent in the previous comment but when I try to change to RAS in Options when importing the Model in Slicer, the Options tab is coming up empty. 

![RAS Error](https://user-images.githubusercontent.com/56734075/76644777-0a10de00-652e-11ea-8822-97d6e0adb386.PNG)

Option C in that link says:
Write “SPACE=RAS” in the comment/description field in the mesh file (for STL, OBJ, PLY, VTK file; for VTP files, add in the first value of a vtkStringArray field array named “SPACE”) to indicate that the values are stored in RAS coordinate system. This option is useful if coordinates have to be stored in RAS coordinate system (for example, for compatibility with other software).

I'm not sure how to to access the mesh files for the STL and how exactly to change it. Do you have any tutorials? I saw the example STL file header on the link but I don't know how to get there.

**Comment by Sunderlandkyl** [comment]
I just double checked with your version of Slicer. You can just directly load the stl and they should be in the correct coordinate system.

**Comment by hripat** [comment]
@Sunderlandkyl Ok, so then why is the ultrasound image still not showing up until the transducer is directly almost inside the bone? Is it a problem with the properties?

**Comment by Sunderlandkyl** [comment]
Because the models in your current scene, do not match the stls that you provided:
![image](https://user-images.githubusercontent.com/9222709/76647310-f87e0500-6532-11ea-8778-df21864bf4d0.png)

**Comment by hripat** [comment]
@Sunderlandkyl  How do I fix that problem? I changed the gel block model and radius model but I deleted the old model from the "Data" tab in Slicer and reloaded the STL files in there but it still wasn't fixed.

**Comment by Sunderlandkyl** [comment]
If you want to use the models that are already in the scene in Slicer, then export them to stl and use them in the Plus config file. Here, I've exported them to this folder: https://www.dropbox.com/sh/nan04ryzix10392/AAC_QewGlZVBCA4j233vIf5ja?dl=0

**Comment by hripat** [comment]
@Sunderlandkyl Thank you for all your help! It's working!
