### ISSUE TITLE
Phidget Spacial 3/3/3 Precision HighRes - 1044_1B

### ISSUE THREAD

**Issue by may1968** [PlusToolkit/PlusLib#678]
Hi,
When using the Plus config for the Phidget - it returns a error - "cannot connect to device". See log below. The device works properly with the Phidget software. I've used a variety of PlusApp programmes including 2.9.0 20200123. Ive used a variety of USB cables - no help - all work OK with the Phidget software.
thanks
John

|ERROR|4316.241000|SERVER> Device TrackerDevice cannot connect to PhidgetSpatial hardware device (serial number: any). Problem waiting for attachment (Timed Out)| in E:\D\PTNP64b\PlusLib\src\PlusDataCollection\PhidgetSpatialTracking\vtkPlusPhidgetSpatialTracker.cxx(382)
|ERROR|4316.285000|SERVER> TrackerDevice: Cannot connect to device, ConnectInternal failed| in E:\D\PTNP64b\PlusLib\src\PlusDataCollection\vtkPlusDevice.cxx(1239)
|ERROR|4316.285000|SERVER> Unable to connect device: TrackerDevice.| in E:\D\PTNP64b\PlusLib\src\PlusDataCollection\vtkPlusDataCollector.cxx(369)
|ERROR|4316.286000|SERVER> Datacollector failed to connect to devices| in E:\D\PTNP64b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(106)
|ERROR|4316.325000| Server stopped unexpectedly. Return code: 1| in E:\D\PTNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(865)

**Comment by lassoan** [comment]
It is most likely because Plus is built with a different PhidgetSpatial software version than what you installed on your computer. You either need to install the same version that Plus uses or rebuild Plus with the your installed PhidgetSpatial software version.
