### ISSUE TITLE
witmotion tracking

### ISSUE THREAD

**Issue by gdlesage** [PlusToolkit/PlusLib#679]
I have witmotion (BWT901CL) connected at the rotation axis of a linear rectal ultrasound probe and I want to create 3d slicer data set as the probe rotates along its linear axis.  I have xml configuration file that enables data capture with my hardware, a usb video capture device and the wit motion tracker shown below (new text document (2).txt).  I see both the image from the frame grabber and motion of the wit tracker as a arrow vector in 3D slicer, but the motion is not translated to the image, eg the tracker vector moves but the image remains stationary. I used the "ConfigFileExample_IGTApplications.xml" as a roadmap to setup my hardware config file, but I am missing something in the transform part of the setup.  There are no errors in log file.

**Comment by gdlesage** [comment]
[New Text Document (2).txt](https://github.com/PlusToolkit/PlusLib/files/4417318/New.Text.Document.2.txt)

**Comment by Sunderlandkyl** [comment]
The reference coordinate frame for your image is "Accel":
```
<Image Name="Image" EmbeddedTransformToFrame="Accel" />
```

Which is defined by a static matrix here:
```
<CoordinateDefinitions>
    <Transform From="Image" To="Accel"
      Matrix="
        0.2 0.0 0.0 0.0
        0.0 0.2 0.0 0.0
        0.0 0.0 0.2 0.0
        0 0 0 1"  
       Error="0.0" Date="112317_141120" />
</CoordinateDefinitions>
```
