### ISSUE TITLE
Issue Connecting to NDI Polaris on Mac

### ISSUE THREAD

**Issue by mksigona** [PlusToolkit/PlusLib#680]
I am attempting to connect the NDI Polaris on macOS 10.14.4 Mojave. I was able to get this pipeline successfully running on a Windows computer but am completely new to Mac and am at a lost of what to try. I get the following error when trying to launch the server: 

|ERROR|008.469911| Server process error: FailedToStart| in /Users/brainsightuser/PlusBuild/build/PlusApp/PlusServerLauncher/PlusServerLauncherMainWindow.cxx(841)
|ERROR|008.472398| Failed to start server process| in /Users/brainsightuser/PlusBuild/build/PlusApp/PlusServerLauncher/PlusServerLauncherMainWindow.cxx(339)

I have tried using the PlusDeviceSet_Server_NDIPolaris.xml and one I edited but received the same error. I also have verified that the camera is connecting successfully with NDI Track.

**Comment by adamrankin** [comment]
Did you compile Plus? If so, in Release or Debug?

If Debug, we could use your help! Mac support is only experimental as none of us have a Mac to work with.

Are you able to help us debug the problem?

Adam

**Comment by mksigona** [comment]
Yes I compiled with Plus in Debug. I would be happy to help debug this problem!

**Comment by adamrankin** [comment]
Could you debug the PlusServer executable directly with --config-file="XYZ.xml" (where XYZ is your config file name) and see where it crashes?
