### ISSUE TITLE
volume reconstruction error, need help

### ISSUE THREAD

**Issue by zhaobingshuai** [PlusToolkit/PlusLib#681]
hello, let me intructueLet me introduce my current situation:
I bound some kind of tracker to the ultrasound probe, I only moved in the Z direction to scan(about 5 cm), so I got 377 images (605 * 672) and their corresponding poses (6 DOF, I have converted them to homogeneous coordinates, establish the coordinate system with the origin of the first image as the origin in space.)

My goal is to use PLUS VolumeReconstructor.exe to reconstruct these 377 images into a volume to show the scanned part.

I am a little confused and hope to get your help, thank you.
1. In the CLI (--image-to-reference-transform =), ElbowUltrasoundSweep-VolRec3.xml, --source-seq-file (input file before reconstruction), all require me to set a transform, but I am not clear what I should What is set? ProbeToTracker or ImageToProbe or other transformations? why?
![image](https://user-images.githubusercontent.com/38325759/79637750-901ae700-81b4-11ea-982e-f6f456429d5f.png)
![image](https://user-images.githubusercontent.com/38325759/79637812-aaed5b80-81b4-11ea-99cb-b43acfd6d6b9.png)

2. In the ElbowUltrasoundSweep-VolRec3.xml, What does the matrix here do? How should I set it up?
![image](https://user-images.githubusercontent.com/38325759/79637882-0ddef280-81b5-11ea-9437-07847658ae8e.png)

3. We know that the input image used for reconstruction is 605 * 672 * 377, and I guess the output image should be about the same size. However, I imported the reconstructed results into the 3D Slicer and found that it is very crowded in the Z direction. I think this is the wrong result. It is probably caused by the above two problems. What do you think is the reason?
![image](https://user-images.githubusercontent.com/38325759/79638019-ef2d2b80-81b5-11ea-87ce-e5a2cc7679e5.png)

The following is all my file:
https://1drv.ms/u/s!AnM4i3s95l5ggh3quDnHh-HLF46P?e=hOxA7E
* VAS_LINEAR_20200110214216072123456.avi is the video that scaned
* VAS_LINEAR_20200110214216072123456/ is all frame extract from above video
* VAS_LINEAR_20200110214216072123456.txt is all pose data that scaned
* VAS_LINEAR_20200110214216072123456-z1-3-381.mhd is input file for reconstruction
* VAS_LINEAR_20200110214216072123456-z1-3-381-result.mha is output file

**Comment by lassoan** [comment]
It is completely up to you what transforms you use. The only requirement for volume reconstruction is that you need to have a valid transform between then Image and the chosen "--image-to-reference-transform" transform must be possible to compute from all the transforms that you specify in the input sequence file and in the configuration file. Plus can combine all the available transforms (concatenate and invert as needed) to compute the needed transform.

**Comment by zhaobingshuai** [comment]
Dear Prof. lassoan. Thanks for your help,  Can you tell me how to set the matrix in the second question?

**Comment by lassoan** [comment]
ImageToProbe is the transform between Image and Probe coordinate systems - see their definition here: http://perk-software.cs.queensu.ca/plus/doc/nightly/user/CommonCoordinateSystems.html

Note the difference in unit: mm vs pixel - so it contains a pixel to mm scaling. The rotation and translation components define where the image coordinate system origin and axes are relative to the probe coordinate system.

**Comment by zhaobingshuai** [comment]
In my scan, the depth of the ultrasound probe is 38mm, which means that each pixel in the image corresponds to approximately 38mm / 672pixel = 0.0565mm in the physical world. I still can't understand how to set the 4 * 4 matrix in ElbowUltrasoundSweep-VolRec3.xml: how did the rotation matrix in the upper left corner come from? What does it stand for? How are the x, y, z in column 4 calculated?
Can you explain it in more detail? Very grateful for your help.
Bingshuai Zhao

**Comment by lassoan** [comment]
Homogeneous transformations are explained in [SlicerIGT tutorials](http://www.slicerigt.org/wp/user-tutorial/), [PerkLab bootcamp training materials](https://github.com/PerkLab/PerkLabBootcamp/tree/master/Doc) but if they are not clear or comprehensive enough then just search for it on the web (it is used very commonly for defining 3D transformations in computer graphics and robotics).

**Comment by zhaobingshuai** [comment]
I know the three-dimensional transformation you just mentioned (including rotation, translation, scaling, shear, homogeneous transformation, etc.). Sorry, I may not have made it clear what I mean, I want to know how to get the numbers in this 4 * 4 transformation matrix? How these figures affect the reconstruction results.

**Comment by ungi** [comment]
U-31 "Tracked ultrasound calibration" on this page: http://www.slicerigt.org/wp/user-tutorial/ explains how the 4x4 matrix is computed.
