### ISSUE TITLE
Plus Launcher keeps saying “Launching”

### ISSUE THREAD

**Issue by chrissMD** [PlusToolkit/PlusLib#683]
Hello,

I am trying to transmit some ultrasound images(NRRD format) thought Open IGTlink form PLUS to Slicer. The final goal is to reconstruct an accuracy evaluation phantom for evaluation of tracked Ultrasound.

Here is what I did:
1- set the Device " Replay recorded data from file" in the config file with a link to the directory
2- set the device “VolumeReconstructorDevice” in the config file
3- set up the connection through Open IGTlink
3.1- Add the connector (+)
3.1- check ACTIVE
3.2- I/O configuration: Image data as volume and Transform data is available but no output
4- View controllers: chose the right connection, Axial, and click the eye
5- Volume reslice driver: Transverse
I am using plus 2.8 and Slicer 4.10.2
![plus_lunching error](https://user-images.githubusercontent.com/48135643/80826320-53061a00-8be2-11ea-9f92-124f5af42714.PNG)
![Capture](https://user-images.githubusercontent.com/48135643/80826322-539eb080-8be2-11ea-9a40-8e505b1d273d.PNG)

Yet, the Plus Server indicates “Lunching …”. Is that right? And Should there be an output (3.2)

I should note that I could not see any image or Volume yet!
[TrackedImageSequence_20191207_172327_config .txt](https://github.com/PlusToolkit/PlusLib/files/4565516/TrackedImageSequence_20191207_172327_config.txt)

**Comment by Sunderlandkyl** [comment]
According to the log, you are using Plus 2.6, can you try again with 2.8 or 2.9?

**Comment by chrissMD** [comment]
That issue is resolved with Plus 2.9. However1, I do not get an output, as mentioned above? And am I on the right track to reconstruct the volume from the loaded data set? Is the VirtualCapture Device necessary for this purpose? Thank!
![2 1](https://user-images.githubusercontent.com/48135643/80828989-8fd41000-8be6-11ea-81c3-6e4167cd6719.PNG)

**Comment by Sunderlandkyl** [comment]
If you want to do the volume reconstruction from Slicer using the PlusRemote module, then the VirtualCapture device is necessary to record snapshots and add them to the reconstruction.

If you just want to reconstruct the volume from an already recorded sequence, you might want to look at using the VolumeReconstructor application directly:
http://perk-software.cs.queensu.ca/plus/doc/nightly/user/ApplicationVolumeReconstructor.html

**Comment by lassoan** [comment]
You can also load a recorded sequence into Slicer and use the volume reconstructor module.

Note that you don't have to to do the reconstruction in PlusServer anymore. You may do it directly in Slicer, too, as shown in this video:

https://www.youtube.com/watch?v=2vXeJxYFou4

The advantage is that the volume gets updated continuously, while if you reconstruct on the server then you can get usually get an updated volume once in every 1-2 seconds. The disadvantage is that reconstruction may compete with visualization, so if you have a slow CPU, very complex scene to visualize, or large volume to reconstruct then you may run into performance issues.

**Comment by chrissMD** [comment]
@Sunderlandkyl how do I load my config file (I need to do fan clipping of the frames) and data to Volumereconstructor.exe? I was only able to run the exe through command promt. Sorry for the ignorant question!

**Comment by chrissMD** [comment]
@lassoan The live reconstruction looks awesome! I tried live reconstruction via OpenIGTling using PLUS some 5 months ago, but It did not work that good. It was very laggy and the reconstruction output was not as nicely depicted as here. Is this a new update of the VolumeReconstruction module?

**Comment by chrissMD** [comment]
@lassoan I am trying to do the same as in the video ... but when I load the config file no image data or transform data is shown, therefore, I can not proceed in the volume reconstruction module! 

![slicer_plus_remote](https://user-images.githubusercontent.com/48135643/80964976-102a8900-8e12-11ea-9143-98539518ff7c.PNG)

I apologize for the overposting!

**Comment by Sunderlandkyl** [comment]
You just need to start the Plus Server and connect to it in Slicer with OpenIGTLinkIF.
As the sequence is replaying in Plus, you can run a live volume reconstruction on the image.

**Comment by lassoan** [comment]
Also make sure that you set up visualization for the volume. After doing a quick scan, set up volume rendering on the reconstructed volume. The rendering settings will be kept for all further reconstructions of that volume.

**Comment by adamrankin** [comment]
@chrissMD Were you able to find a solution?

**Comment by chrissMD** [comment]
> 
> 
> @chrissMD Were you able to find a solution?

Yes. Thanks for closing the issue!
