### ISSUE TITLE
Plus Server Not Transmitting NDI Polaris Tracking Data to Slicer Through OpenIGTLink

### ISSUE THREAD

**Issue by Nikhildave4** [PlusToolkit/PlusLib#684]
Our goal is to be able to show active tracking of a Passive NDI Polaris Pointer in 3D-Slicer. After thorough review of the tutorials on the slicerIGT, these are the steps we followed and the problems we encountered.
1. First we installed the PlusApp-…-Win64
2. Then we placed our .rom files in the NdiToolDefinitions folder in the Plus app program folder.
3. Using the sample configuration files available on the Plus applications user manual, we created our own device set configuration files. We tried many, and were able to have a successful connection with Polaris using the following .xml attached. We would like to show a single pointer with respect to a reference frame.
4. Running the Plus server Launcher with our config file said our connection was successful! We we got a green light on the Plus server window.
5. The log file gave **no errors** and is also attached. It would appear as if everything is working fine, however we are not able to receive any transforms in slicer.
6.  With: SendValidTransformsOnly="false", we were able to see a transform in slicer using OpenIGTLink. However, when we turn this value to "true", we had no transforms show up in slicer.
7. We assume our connection with Polaris is working and OpenIGTLink is able to receive a transform, but it is invalid and thus will not show up in slicer. 

We would like to resolve this issue to be able to see a pointer needle model move in slicer as we move it in real life. We have experimented with many config files, but I have only attached one here. If there is any other information needed from us please let  us know.

We know we can receive data from Polaris as we are able to run NDIs Track software successfully.

If the team would like to meet on Zoom, we are open to arranging a meeting.
The Log file:
[050220_175756_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/4569363/050220_175756_PlusLog.txt)
Our device set config file:
[PlusDeviceSet_Server_NDIPolarisBASEhelp.txt](https://github.com/PlusToolkit/PlusLib/files/4569366/PlusDeviceSet_Server_NDIPolarisBASEhelp.txt)

**Comment by Nikhildave4** [comment]
Followed all the steps on the Toolkit website exactly under the section: "Streaming of live images and tracking data to 3D Slicer". Please let us know what we could be doing wrong.

**Comment by chrissMD** [comment]
Technically you have no errors. That's why everything is green. As far as I can see in your config file you have not transformations defined in your config file (in `<CoordinateDefinitions>`), you have commented it. I would recommend calibrating the stylus first. You can use fCal.exe, which is in bin [fCal](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/Calibration.html) of Plus. Also, you might need some rendering!

Nevertheless, I am no expert. I just went through the same steps using NDI Aurora.
Good luck!

**Comment by adamrankin** [comment]
Hi @Nikhildave4, are you still having trouble?
