### ISSUE TITLE
using PLUS offline

### ISSUE THREAD

**Issue by fcenni** [PlusToolkit/PlusLib#691]
Hi all,
For a project, I need to have 3D pose of bony landmarks during subject walking. I do not need to have the 3D poses online. Therefore, I was thinking to acquire data and offline using PLUS for 3D reconstruction. Is this an option for PLUS toolkit?
Kind regards
Francesco

**Comment by lassoan** [comment]
Yes, this is fully supported. You can add a "VirtualCapture" type device and you can record all of its input data automatically when you start the server by setting "EnableCapturingOnStart" to "TRUE". See details and example configuration file here: http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceVirtualCapture.html
