### ISSUE TITLE
Plus Server Error with 3D Slicer: Cannot connect to the server

### ISSUE THREAD

**Issue by mxochicale** [PlusToolkit/PlusLib#692]
Hi @Sunderlandkyl et al. 

I am trying to run [Ultrasound simulation](https://www.youtube.com/watch?v=2Oc_tCu_uzs) following [these instructions](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/ProcedureUltrasoundSimulation.html) under windows10x64 with:
* 3DSlicer 4.10.2 r28257 with SlicerOpenIGTLink, SlicerIGSIO, SlicerJupyter and SlicerIGT, and
* Software version: Plus-2.8.0.62873a16 - Win64  with [PlusDeviceSet_Server_SimulatedUltrasound_3DSlicer.xml](https://github.com/PlusToolkit/PlusLibData/blob/master/ConfigFiles/PlusDeviceSet_Server_SimulatedUltrasound_3DSlicer.xml) which produce the below error: 

PS. I have read the closed https://github.com/PlusToolkit/PlusLib/issues/619 issue but I have not idea what I might be doing wrong. Wondering if you have any recommendations.
 
```
C:\Users\mx19\Desktop\simulated-ultrasound-example>PlusServer.exe --config-file=PlusDeviceSet_Server_SimulatedUltrasound_3DSlicer.xml

System start timestamp: 641
Software version: Plus-2.8.0.62873a16 - Win64
Logging at level 3 (INFO) to file: C:/Users/mx19/PlusApp-2.8.0.20191105-Win64/data/052520_221530_PlusLog.txt
Selected US image orientation: MF
VideoDevice: Local time offset: 0ms
Server status: Reading configuration.
Server status: Connecting to devices.
Debug: In E:\D\PSNP64b\Deps\OpenIGTLink\Source\igtlClientSocket.cxx, line 67
igtl::ClientSocket (00000292352B3F90): Failed to connect to server 127.0.0.1:18946

Debug: In E:\D\PSNP64b\Deps\OpenIGTLink\Source\igtlClientSocket.cxx, line 67
igtl::ClientSocket (00000292352B3F90): Failed to connect to server 127.0.0.1:18946

Debug: In E:\D\PSNP64b\Deps\OpenIGTLink\Source\igtlClientSocket.cxx, line 67
igtl::ClientSocket (00000292352B3F90): Failed to connect to server 127.0.0.1:18946

|ERROR|003.351000| Cannot connect to the server (127.0.0.1:18946).| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\OpenIGTLink\vtkPlusOpenIGTLinkDevice.cxx(152)
|ERROR|003.358000| TrackerDevice: Cannot connect to data source, ConnectInternal failed| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDevice.cxx(1147)
|ERROR|003.362000| Unable to connect device: TrackerDevice.| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDataCollector.cxx(353)
|ERROR|003.367000| Datacollector failed to connect to devices| in E:\D\PSNP64b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(106)
```

**Comment by Sunderlandkyl** [comment]
Have you loaded the Test_PlusConfiguration_SimulatedUS.mrb scene in Slicer, and made sure that all of the OpenIGTLink connectors are active?

**Comment by mxochicale** [comment]
Yes to: Have you loaded the Test_PlusConfiguration_SimulatedUS.mrb scene in Slicer but 
how to make sure OpenIGTLink connectors are active?

**Comment by Sunderlandkyl** [comment]
Switch to the OpenIGTLinkIF module. There should be two connectors (one incoming and one outgoing). They should both be active.

![image](https://user-images.githubusercontent.com/9222709/82844926-5ecac080-9eb0-11ea-8639-d41a7d28ed73.png)

**Comment by mxochicale** [comment]
Many thanks @Sunderlandkyl 

Simulations are now working : ) So this issue can be closed! 
![Capture3](https://user-images.githubusercontent.com/11370681/84091068-5bc0eb80-a9eb-11ea-9903-81fd242a1525.PNG)

PS. A quick question where I can find more [references](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceUsSimulator.html) on how to do simulations with a curvilinear transducer? (you let me know and I can create a new issue to raise such question)

**Comment by Sunderlandkyl** [comment]
I don't know if there are any other examples except for the one on the page that you linked:
```
<!-- Example for a curvilinear transducer: -->
<ScanConversion
  TransducerName="Ultrasonix_C5-2/60"
  TransducerGeometry="CURVILINEAR"
  RadiusStartMm="60.0"
  RadiusStopMm="120.0"
  ThetaStartDeg="-28.0"
  ThetaStopDeg="28.0"
  TransducerCenterPixel="410 100"
  OutputImageSizePixel="820 616"
  OutputImageSpacingMmPerPixel="0.084 0.087" />
````
