### ISSUE TITLE
CreateSliceModels.exe error!

### ISSUE THREAD

**Issue by chrissMD** [PlusToolkit/PlusLib#700]
I am trying to check the spatial distribution of a set of US images using CreateSliceModels.exe. I can run it but there is no output file created. The error says: Parsing line failed! 

Why there is no output file created?

![CreateSliceModels error](https://user-images.githubusercontent.com/48135643/87311489-91dc1880-c51f-11ea-94dc-61b846879288.PNG)

Run from a batch file: 
[Batchfile.txt](https://github.com/PlusToolkit/PlusLib/files/4912834/Batchfile.txt)

config file: 
[TrackedImageSequence_20191207_172327_ICE_3D_Cubes_Intervall_0_1008.txt](https://github.com/PlusToolkit/PlusLib/files/4912842/TrackedImageSequence_20191207_172327_ICE_3D_Cubes_Intervall_0_1008.txt)

Image data: (updated)
https://stovgude-my.sharepoint.com/:u:/g/personal/kristjan_qarri_st_ovgu_de/EZTlDNcLOGJIn0042hZKvd8BF6kKtds8QSJSSzUpl3zmHQ?e=Vd0BZe

**Comment by Sunderlandkyl** [comment]
The link to the image data is broken, could you update it?

**Comment by chrissMD** [comment]
> 
> 
> The link to the image data is broken, could you update it?

Updated: https://stovgude-my.sharepoint.com/:u:/g/personal/kristjan_qarri_st_ovgu_de/EZTlDNcLOGJIn0042hZKvd8BF6kKtds8QSJSSzUpl3zmHQ?e=Vd0BZe
