### ISSUE TITLE
PLUS Nightly build crashing

### ISSUE THREAD

**Issue by hareem-nisar** [PlusToolkit/PlusLib#701]
Hi there,
I want a PLUS build with Virtual text recognizer device. I believe it is only available on nightly builds right now.? 
The current version of Plus Nightly build for Windowsx64 is not working for me. It installs okay but then I get an error asking to reinstall in order to fix the issue. (It didn't)

Can you please fix this issue and if you can kindly provide me with an older, more reliable, nightly version as well? 
I am to use Epiphan framegrabber, Aurora tracking and Virtual text recognizer. (hnisar3@uwo.ca)

Thank you!

**Comment by adamrankin** [comment]
It runs without crashing on my machine. Could you post the error message that you get?

**Comment by Sunderlandkyl** [comment]
I added support for the latest Clarius version to the nightly build, which is what is causing the issue.

I had another user report the error this morning. Not all computers encounter the crash, but the error is `The procedure entry point SetThreadDescription could not be located in the dynamic link library.`

Trying to figure out what library is missing.

**Comment by adamrankin** [comment]
Does this help?

https://stackoverflow.com/a/62243579/1333429

**Comment by Sunderlandkyl** [comment]
@hareem-nisar I've uploaded the previous release here: https://www.dropbox.com/s/pk3bpdv4f0ls0v0/PlusApp-2.9.0.20200706-Win64.exe?dl=0

**Comment by Sunderlandkyl** [comment]
Thanks @adamrankin!

It looks like the SetThreadDescription API was only made available in Windows 10:
https://docs.microsoft.com/en-ca/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreaddescription?redirectedfrom=MSDN

I can reproduce the crash on a Windows 8 computer.

@hareem-nisar What version of Windows are you using?

If this is the case, then I'll remove the Clarius support from the main x64 build and create a separate one for Clarius.

**Comment by Sunderlandkyl** [comment]
@hareem-nisar I've removed Clarius from the Win64 build. Could you try it and see if it crashes?

**Comment by hareem-nisar** [comment]
Thank you @Sunderlandkyl  for putting the previous version - I have downloaded that as well. 
The error I was getting: "The code execution cannot proceed because VCRUNTIME140_1.dll was not found. Reinstalling the program may fix this problem."
I am using Windows 10. The current version uploaded loads properly now. However, the tessdata folder was missing so I placed it manually.

I am currently getting one error though: "|ERROR|004.003000| Server stopped unexpectedly. Return code: 1| in E:\D\PTNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(865) " 

Would you know if this is a build issue or possibly an error within my files?

Thank you

**Comment by adamrankin** [comment]
```Notes

Note: some browsers may indicate that the installers are malicious files. This is a common problem when offering download of executable files (for example see discussion here). If you doubt the safety of a package, download it and before you run it, submit to online malware scanners, such as https://www.metascan-online.com or https://www.virustotal.com/.
If Plus applications fail to start, install Microsoft Visual Studio redistributable packages:
MSVCP120.dll missing => install VS2013 redistributable and restart your computer
MSVCP140.dll missing => install VS2015 redistributable and restart your computer
Embedded XP requires XP SP3 and Visual Studio 2013 Redistributable x86 installed.
VCRUNTIME140_1.dll missing => install VS2015-2019 redistributable
```
