### ISSUE TITLE
CreateSliceModels.exe error!

### ISSUE THREAD

**Issue by chrissMD** [PlusToolkit/PlusLib#702]
I am trying to check the spatial distribution of a set of US images using CreateSliceModels.exe. I can run it but there is no output file created. The error says: Parsing line failed!

Why there is no output file created?
![87311489-91dc1880-c51f-11ea-94dc-61b846879288](https://user-images.githubusercontent.com/48135643/87520134-d59b6300-c682-11ea-926a-776c06825046.PNG)

Run from a batch file:
[Batchfile.txt](https://github.com/PlusToolkit/PlusLib/files/4923780/Batchfile.txt)

config file: 
[TrackedImageSequence_20191207_172327_ICE_3D_Cubes_Intervall_0_1008.txt](https://github.com/PlusToolkit/PlusLib/files/4923782/TrackedImageSequence_20191207_172327_ICE_3D_Cubes_Intervall_0_1008.txt)

Image data:
https://stovgude-my.sharepoint.com/:u:/g/personal/kristjan_qarri_st_ovgu_de/EZTlDNcLOGJIn0042hZKvd8BF6kKtds8QSJSSzUpl3zmHQ?e=Vd0BZe

**Comment by chrissMD** [comment]
Updated link: https://stovgude-my.sharepoint.com/:u:/g/personal/kristjan_qarri_st_ovgu_de/EZTlDNcLOGJIn0042hZKvd8BF6kKtds8QSJSSzUpl3zmHQ?e=4ol6sk

**Comment by chrissMD** [comment]
Updated link for image data: https://stovgude-my.sharepoint.com/:u:/g/personal/kristjan_qarri_st_ovgu_de/EZTlDNcLOGJIn0042hZKvd8BF6kKtds8QSJSSzUpl3zmHQ?e=SNJGtf

**Comment by chrissMD** [comment]
updated link for image data: https://drive.google.com/file/d/1NRgWoCrz6K7bEc77ieC5vbskk41iuBjn/view?usp=sharing

**Comment by adamrankin** [comment]
I'll check it out

**Comment by chrissMD** [comment]
> 
> 
> I'll check it out

we scanned this phantom.
![IMG_0247](https://user-images.githubusercontent.com/48135643/87564889-3e093500-c6c1-11ea-82c7-daee9ac5da35.jpg)

The reconstruction is far away from that shape!

**Comment by adamrankin** [comment]
The latest crashes with any nrrd input file. I'll fix that and let you know how it goes.

**Comment by adamrankin** [comment]
Fixed the crash, I get an empty output. Investigating.

**Comment by chrissMD** [comment]
which PLUS version did you use? I get same result with Version 2.6, V2.8, and V2.9 (no output)!
May I know which PLUS version did you use?

**Comment by adamrankin** [comment]
I built the latest, so 2.9, git commit 484f37f757c2a323b072cfae04e63d5e21693724

with my changes

**Comment by chrissMD** [comment]
> 
> 
> I built the latest, so 2.9, git commit [484f37f](https://github.com/PlusToolkit/PlusLib/commit/484f37f757c2a323b072cfae04e63d5e21693724)
> 
> with my changes

It works with the updates plus2.9. Thanks for the support!
