### ISSUE TITLE
Vega- Ethernet

### ISSUE THREAD

**Issue by MaDiBmDaD** [PlusToolkit/PlusLib#705]
Since one can see many changes for API 2019 cuz of using Ethernet, I could not use such libs based on the serial COM. USB converter does not help anymore when I was intending to make a virtual COM from TCP. Does it seem we have to rewrite a new one based on the latest version of API-Vega ?!

**Comment by adamrankin** [comment]
The NDICAPI supports ethernet connections.

https://github.com/PlusToolkit/ndicapi/blob/master/ndicapi.h#L260

**Comment by MaDiBmDaD** [comment]
Good, miss it cuz I had a look at the ndiBasicExample(cpp). I went through it but to make sure, would you please give me what must I change for putting the address and port number instead of?

**Comment by MaDiBmDaD** [comment]
changing : 
device = ndiOpenNetwork("169.254.91.254",139);
ndiCloseNetwork(device);
still thinking about another settings such as tool definition *.rom?(which I did not)
by the way, output is: The program '[10136] ndiBasicExample.exe: Native' has exited with code 1 (0x1).
