### ISSUE TITLE
I don't want clone PlusDoc

### ISSUE THREAD

**Issue by zhaobingshuai** [PlusToolkit/PlusLib#706]
Hello everyone, I am compiling PlusBuild. Due to the limitation of the GitHub network speed, I have to use to transfer the repositories needed for compilation to GITEE (China's Github). So I need to modify the address in *.cmake:
IF(NOT DEFINED(PLUSLIB_GIT_REPOSITORY))
  SET(PLUSLIB_GIT_REPOSITORY "${GIT_PROTOCOL}://gitee.com/szubingshuai/PlusLib2.git" CACHE STRING "Set PlusLib desired git url")

This method greatly improves the download speed, but it does not work for PlusLib. The reason is that it contains PlusDoc as a submodule. When I git clone PlusLib, I have to git clone PlusDoc at the same time, but PlusDoc contains a lot of large documents. My network environment does not support me to download such a large file.

I even created a new repository by myself and deleted PlusDoc (https://gitee.com/szubingshuai/PlusLib2), but when I compile, the steps of git clone PlusDoc still exist. I want to know how I should modify /PlusBuild /SuperBuild/*.cmake can avoid git clone PlusDoc.

The following information is the error when I compile PlusBuild:
Scanning dependencies of target PlusLib
[ 76%] Creating directories for 'PlusLib'
[ 78%] Performing download step (git clone) for 'PlusLib'
Cloning into 'PlusLib'...
Already on 'master'
Your branch is up to date with 'origin/master'.
Submodule 'PlusDoc' (https://github.com/PlusToolkit/PlusDoc.git) registered for path 'PlusDoc'
Cloning into '/home/zbs/PlusBuild_bin/PlusLib/PlusDoc'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://github.com/PlusToolkit/PlusDoc.git' into submodule path '/home/zbs/PlusBuild_bin/PlusLib/PlusDoc' failed
Failed to clone 'PlusDoc'. Retry scheduled
Cloning into '/home/zbs/PlusBuild_bin/PlusLib/PlusDoc'...

Thanks for your help.

**Comment by lassoan** [comment]
PlusDoc is not needed for building Plus. You can remove all references to it.
