### ISSUE TITLE
Add support for Andor camera

### ISSUE THREAD

**Issue by dzenanz** [PlusToolkit/PlusLib#707]
[iKon-M CCD](https://andor.oxinst.com/products/ikon-xl-and-ikon-large-ccd-series/ikon-m-934)

**Comment by dzenanz** [comment]
Needed for referencing in commits. Please assign to myself.

**Comment by adamrankin** [comment]
Any camera in particular? Link to their API?

**Comment by dzenanz** [comment]
I updated the description, I don't know whether they have their [SDK](https://andor.oxinst.com/products/software-development-kit/software-development-kit)/API public.

**Comment by adamrankin** [comment]
That's ok, just so someone else might know where to start looking. Thanks.

**Comment by dzenanz** [comment]
Done in #736.
