### ISSUE TITLE
create .mha ultrasound sequence with optical tracker and some serial string data

### ISSUE THREAD

**Issue by smaatze** [PlusToolkit/PlusLib#710]
Hi

I have been trying to fuse some serial data (from two port as a string packet) with optical tracker and ultrasound images as a .mha sequence synchronously. 
It is routine to create mha ultrasound sequence with default plus toolkit trackers (like emt and optical) using fcal and plus, but i could not fuse some serial port data with optical tracker transforms and ultrasound images.

is it a way to do this in plus or i should do some modification on its cpp source code? 
if i should modify source code, please help me on how to do it?

**Comment by smaatze** [comment]
i have 8 sensors with 3 measurement from each one, and thus serial data has at least 100 chars. from my knowledge, if we read this long string packet, in each serialread function call part of packet is captured and this leads the .mha file with fragmented string in each frame sequence recording.

is it true?

**Comment by adamrankin** [comment]
It depends how the sensor data is sent over the serial line. Easiest way is to set up a sensor config file and see what shows up in Slicer.

**Comment by lassoan** [comment]
Plus reads complete lines (terminates with the designated end-of-line string) or when a timeout is reached. However, I'm not sure how and if unrequested data is handled. You may need to create a new device class that interprets the data and put it peoperly into data streams - similarly to how other serial devices do this (for example https://github.com/PlusToolkit/PlusLib/tree/master/src/PlusDataCollection/MicrochipTracking).

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
