### ISSUE TITLE
How to set the input frame resolution in volumetric reconstruction?

### ISSUE THREAD

**Issue by zhaobingshuai** [PlusToolkit/PlusLib#711]
Hi All,

I was trying to reconstruct a volume from a series of 2D frames. Each frame has its spatial pose (position and orientation, 6DOF). I was wondering where I can set the resolution of the 2D frames (0.087*0.087 mm/pixel)?

Seems to me that the Image to Probe homogeneous matrix is where it should be set?

I, therefore, give the following content in the config file:

<PlusConfiguration version="2.3" PlusRevision="Plus-2.0.0.2801">

```
<CoordinateDefinitions>
  <Transform From="Image" To="Probe"
Matrix="
        0.08     0.12    0     5
        0.21      0.08       0    6
        0     0    0.08  0
        0     0       0     1"
      Error="0.582721" Date="012712_152030"/>
  </CoordinateDefinitions>

  <VolumeReconstruction
    OutputSpacing="1 1 0.3"
    Interpolation="LINEAR"
    Optimization="FULL"
    CompoundingMode ="MEAN"
    FillHoles="OFF">
  </VolumeReconstruction>
</PlusConfiguration>
```

However, with all the other parameters fixed, changing this part does not affect the final output. So I'm wondering if there is something I did wrong?

Thank you for any hint!

**Comment by ungi** [comment]
You are right that ImageToProbe is typically the transformation that converts from pixels to millimeters. But ImageToProbe needs to be computed during a calibration process, e.g.: U-31 in the SlicerIGT tutorials: http://www.slicerigt.org/wp/user-tutorial/
ImageToProbe is not something you can figure out without calibration.
I don't see the reference coordinate system specified in your VolumeReconstruction configuration. It hink it is necessary to tell VolumeReconstructor what coordinate system do you need the output volume in. This page has lots of information about volume reconstruction: http://perk-software.cs.queensu.ca/plus/doc/nightly/user/AlgorithmVolumeReconstruction.html

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
