### ISSUE TITLE
Update ITK to 5.1.1?

### ISSUE THREAD

**Issue by dzenanz** [PlusToolkit/PlusLib#714]
Is it desirable to update PlusLib to build against most recent stable release of ITK, the v5.1.1?

Option 1:  change `ITK_LEGACY_REMOVE` from `ON` to `OFF`.
Option 2: drop support for ITK 4.x, and update code to use the new strongly typed enums (`enum class`).

**Comment by dzenanz** [comment]
I tested option 1, and it works. Option 2 requires a bit of effort.

**Comment by jamesobutler** [comment]
Yes updating to ITK 5.1.1 would be good since PLUS is generally to supposed to use the same version used by Slicer which is currently ITK 5.1.1.

**Comment by jamesobutler** [comment]
Regarding dropping ITK 4.x support, it looks like Stealthlink is driving this (https://github.com/PlusToolkit/PlusBuild/commit/382fad1280cadd506f98a252bf0baf4a68e69740). @Sunderlandkyl, should ITK 4.x support be kept for Stealthlink to continue using latest PlusLib or should it just be that Stealthlink has to use an older version of PlusLib?

**Comment by Sunderlandkyl** [comment]
Ideally we would upgrade the StealthLink libraries to a later version, at which point we could drop 4.x support altogether.
For now, I suggest we keep ITK 4 support so that the StealthLink package can continue to receive PlusLib updates.
