### ISSUE TITLE
Cannot connect the realsense 435?

### ISSUE THREAD

**Issue by LiZhenzhuBlog** [PlusToolkit/PlusLib#716]
|INFO|000.360000| Software version: Plus-2.8.0.62873a16 - Win64| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(122)
|INFO|000.360000| Logging at level 3 to file: C:/Users/1/PlusApp-2.8.0.20191105-Win64/data/091120_195357_PlusLog.txt| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(123)
|INFO|000.775000| Supported devices: - 3dConnexion (ver: Plus-2.8.0) - AuroraTracker (ver: NDICAPI-1.7) - BkProFocusOem (ver: Plus-2.8.0) - ChRobotics (ver: Plus-2.8.0) - Epiphan (ver: Plus-2.8.0) - FakeTracker (ver: Plus-2.8.0) - GenericSerialDevice (ver: Plus-2.8.0) - ICCapturing (ver: The Imaging Source UDSHL-3.4) - ImageProcessor (ver: Plus-2.8.0) - IntelRealSense (ver: Plus-2.8.0) - Microchip (ver: Plus-2.8.0) - MmfVideo (ver: Plus-2.8.0) - NDITracker (ver: NDICAPI-1.7) - NoiseVideo (ver: Plus-2.8.0) - OpenCVVideo (ver: Plus-2.8.0) - OpenIGTLinkTracker (ver: OpenIGTLink v3.1.0) - OpenIGTLinkVideo (ver: OpenIGTLink v3.1.0) - OptiTrack (ver: Plus-2.8.0) - OpticalMarkerTracker (ver: Plus-2.8.0) - PhidgetSpatial (ver: Plus-2.8.0) - PolarisTracker (ver: NDICAPI-1.7) - SavedDataSource (ver: Plus-2.8.0) - UsSimulator (ver: Plus-2.8.0) - VFWVideo (ver: Plus-2.8.0) - VirtualBufferedCapture (ver: Plus-2.8.0) - VirtualCapture (ver: Plus-2.8.0) - VirtualDiscCapture (ver: Plus-2.8.0) - VirtualMixer (ver: Plus-2.8.0) - VirtualSwitcher (ver: Plus-2.8.0) - VirtualTextRecognizer (ver: Plus-2.8.0) - VirtualVolumeReconstructor (ver: Plus-2.8.0) - WitMotionTracker (ver: Plus-2.8.0) | in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(127)
|INFO|000.792000| Server host name: DESKTOP-16RE59P| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(158)
|INFO|000.814000| Server IP addresses: 169.254.102.2, 169.254.25.44, 169.254.214.162, 192.168.0.104, 127.0.0.1| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(178)
|INFO|000.814000| Start remote control server at port: 18904| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(187)
|INFO|072.827000| Connect using configuration file: C:\Users\1\PlusApp-2.8.0.20191105-Win64\config\PlusDeviceSet_Server_3dConnexion.xml| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(639)
|INFO|072.830000| Server process command line: "C:/Users/1/PlusApp-2.8.0.20191105-Win64/bin/PlusServer.exe" --config-file="PlusDeviceSet_Server_3dConnexion.xml" --verbose=3| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(320)
|INFO|073.447000| Server process started successfully| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(329)
|INFO|073.524000|SERVER> System start timestamp: 6562
|INFO|073.525000|SERVER> Software version: Plus-2.8.0.62873a16 - Win64
|INFO|073.525000|SERVER> Logging at level 3 (INFO) to file: C:/Users/1/PlusApp-2.8.0.20191105-Win64/data/091120_195510_PlusLog.txt
|INFO|073.525000|SERVER> Selected US image orientation: UN
|INFO|073.527000|SERVER> Selected US image orientation: UN
|INFO|073.534000|SERVER> Server status: Reading configuration.
|INFO|073.535000|SERVER> Server status: Connecting to devices.
|ERROR|076.250000|SERVER> Failed to start IntelRealSense streams. Check your RealSense camera supports the stream types, resolutions & frame rates you are trying to use. RealSense API gave the error: 'Couldn't resolve requests'| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\IntelRealSense\vtkPlusIntelRealSense.cxx(289)
|ERROR|076.290000|SERVER> VideoDevice: Cannot connect to data source, ConnectInternal failed| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDevice.cxx(1147)
|ERROR|076.290000|SERVER> Unable to connect device: VideoDevice.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDataCollector.cxx(353)
|ERROR|076.291000|SERVER> Datacollector failed to connect to devices| in :\D\PSNP64b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(106)
|ERROR|076.408000| Server stopped unexpectedly. Return code: 1| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(864)
|INFO|076.410000| Disconnect request successful| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(632)

**Comment by LiZhenzhuBlog** [comment]
<PlusConfiguration version="2.3">

  <DataCollection StartupDelaySec="1.0" >
    <DeviceSet 
      Name="PlusServer: Intel RealSense camera "
      Description="Broadcasting acquired RGB and Depth video through PlusServer from Intel RealSense 3D camera"
  />
  
    <Device
      Id="VideoDevice"
      Type="IntelRealSense"
      UseRealSenseColorizer="TRUE"
      AlignDepthStream="TRUE">
      <DataSources>
        <DataSource Type="Video" Id="VideoRGB" FrameType="RGB" FrameSize="640 480" FrameRate="10" PortUsImageOrientation="UN" />
        <DataSource Type="Video" Id="VideoDEPTH" FrameType="DEPTH" FrameSize="640 480" FrameRate="10" PortUsImageOrientation="UN" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStreamRGB" VideoDataSourceId="VideoRGB" />
        <OutputChannel Id="VideoStreamDEPTH" VideoDataSourceId="VideoDEPTH" />
      </OutputChannels>
    </Device>
  </DataCollection>

  <PlusOpenIGTLinkServer
    MaxNumberOfIgtlMessagesToSend="1"
    MaxTimeSpentWithProcessingMs="50"
    ListeningPort="18944"
    SendValidTransformsOnly="true"
    OutputChannelId="VideoStreamRGB" >
    <DefaultClientInfo>
      <MessageTypes>
        <Message Type="IMAGE" />
      </MessageTypes>
      <ImageNames>
        <Image Name="ImageRGB" EmbeddedTransformToFrame="ImageRGB" />
      </ImageNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>
  <PlusOpenIGTLinkServer
    MaxNumberOfIgtlMessagesToSend="1"
    MaxTimeSpentWithProcessingMs="50"
    ListeningPort="18945"
    SendValidTransformsOnly="true"
    OutputChannelId="VideoStreamDEPTH" >
    <DefaultClientInfo>
      <MessageTypes>
        <Message Type="IMAGE" />
      </MessageTypes>
      <ImageNames>
        <Image Name="ImageDEPTH" EmbeddedTransformToFrame="ImageDEPTH" />
      </ImageNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>

</PlusConfiguration>

**Comment by LiZhenzhuBlog** [comment]
`<PlusConfiguration version="2.3">

  <DataCollection StartupDelaySec="1.0" >
    <DeviceSet 
      Name="PlusServer: Intel RealSense camera "
      Description="Broadcasting acquired RGB and Depth video through PlusServer from Intel RealSense 3D camera"
  />
  
    <Device
      Id="VideoDevice"
      Type="IntelRealSense"
      UseRealSenseColorizer="TRUE"
      AlignDepthStream="TRUE">
      <DataSources>
        <DataSource Type="Video" Id="VideoRGB" FrameType="RGB" FrameSize="640 480" FrameRate="10" PortUsImageOrientation="UN" />
        <DataSource Type="Video" Id="VideoDEPTH" FrameType="DEPTH" FrameSize="640 480" FrameRate="10" PortUsImageOrientation="UN" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStreamRGB" VideoDataSourceId="VideoRGB" />
        <OutputChannel Id="VideoStreamDEPTH" VideoDataSourceId="VideoDEPTH" />
      </OutputChannels>
    </Device>
  </DataCollection>

  <PlusOpenIGTLinkServer
    MaxNumberOfIgtlMessagesToSend="1"
    MaxTimeSpentWithProcessingMs="50"
    ListeningPort="18944"
    SendValidTransformsOnly="true"
    OutputChannelId="VideoStreamRGB" >
    <DefaultClientInfo>
      <MessageTypes>
        <Message Type="IMAGE" />
      </MessageTypes>
      <ImageNames>
        <Image Name="ImageRGB" EmbeddedTransformToFrame="ImageRGB" />
      </ImageNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>
  <PlusOpenIGTLinkServer
    MaxNumberOfIgtlMessagesToSend="1"
    MaxTimeSpentWithProcessingMs="50"
    ListeningPort="18945"
    SendValidTransformsOnly="true"
    OutputChannelId="VideoStreamDEPTH" >
    <DefaultClientInfo>
      <MessageTypes>
        <Message Type="IMAGE" />
      </MessageTypes>
      <ImageNames>
        <Image Name="ImageDEPTH" EmbeddedTransformToFrame="ImageDEPTH" />
      </ImageNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>

</PlusConfiguration>`

**Comment by LiZhenzhuBlog** [comment]
![屏幕截图 2020-09-12 002603](https://user-images.githubusercontent.com/66670720/92950017-9a54bf00-f48e-11ea-9bdc-65820122284c.jpg)

**Comment by Sunderlandkyl** [comment]
What version of the RealSense SDK do you have installed?

Could you try with the latest nightly (2.9.0) release?

**Comment by markasselin** [comment]
One idea from personal experience would be to try different stream resolutions and frame rates (I would start with 1080p and 30fps). Not all RealSense camera's support the same streams. Checking the [datasheet](https://www.intel.com/content/dam/support/us/en/documents/emerging-technologies/intel-realsense-technology/Intel-RealSense-D400-Series-Datasheet.pdf) the D435 does not support 10fps.

I will update the default config to use 30fps since this works on both the new and older generations of RealSense hardware.

**Comment by timeanddoctor** [comment]
Thanks. I can connect the realsense camera. But I donnot know how to steam a 3d volume or vtk-model into slicer? Can I deal with it with plus?

**Comment by adamrankin** [comment]
At this time we only stream the image data, not point clouds.

**Comment by lassoan** [comment]
The realsense camera stores the depth measurement as a depth image, Plus can stream that depth image to Slicer, and in Slicer you can convert the depth image to point cloud using https://github.com/PerkLab/DepthImageToPointCloud.
