### ISSUE TITLE
Connecting multiple atracsys cameras

### ISSUE THREAD

**Issue by hgueziri** [PlusToolkit/PlusLib#717]
Hi everyone,

Is it possible to set Plus to connect to multiple atracsys cameras? If so, what would be the best way to do it?
Thanks

**Comment by markasselin** [comment]
I've never tried this, but I don't see any reason in theory why it shouldn't work. The best way to do this would be to create a config file with two Atracsys camera blocks in it. Ensure the ToolReferenceFrame attributes are different for each tracker. If both trackers can see the same marker (i.e. a reference marker) you should even be able to get the transform between the two tool reference frames (the positions of the trackers).

Cool idea - let us know if this works!
