### ISSUE TITLE
how to calibrate the stylus posture？

### ISSUE THREAD

**Issue by timeanddoctor** [PlusToolkit/PlusLib#722]
I used a magic navigation and connect with slicerIGTlinkIF，after the pivot calibbration I get a precise  location of position but the posture seems not correct. (the red showed in this picture should be the posture in the real world )
![image](https://user-images.githubusercontent.com/28825816/94360850-ff412380-00e2-11eb-9494-7e2fa0ed37c3.png)

I flipped and it was wrong still

**Comment by timeanddoctor** [comment]
after flip 
![image](https://user-images.githubusercontent.com/28825816/94360944-7f678900-00e3-11eb-9c9c-5b82b0aada6b.png)

**Comment by ungi** [comment]
You could add a 90 degree rotation to the CoordinateTransforms section of your PLUS config file, and apply that in the transformation chain when you specify what transform to send to Slicer. But it is better to move as many algorithms (including calibration) to Slicer as possible. And leave minimal tasks for PLUS. In Slicer, you could add a StylusModel-to-Stylus transformation and apply the rotation there. Note that the Pivot Calibration module in SlicerIGT extension has a "spin calibration" procedure too, which could help you determine the exact angle (if it's not precisely 90 degrees).

**Comment by timeanddoctor** [comment]
Thank you very much Professor ungi.
I calculate with the spin calibration but nothing happen. Maybe the method was wrong for I never used this spin calibration. Could you give me some information or video(the best) how to spin to calibration? 
Thanks.

**Comment by ungi** [comment]
Even better than video, U-37 on this page: http://www.slicerigt.org/wp/user-tutorial/ which shows the correct procedure that you can repeat with the same data on your computer. Hopefully you will be able to find the difference between my setup and yours.

**Comment by timeanddoctor** [comment]
Thanks, I get the correct transform..
