### ISSUE TITLE
Controlling Plus from Slicer

### ISSUE THREAD

**Issue by dzenanz** [PlusToolkit/PlusLib#723]
Is [PlusRemote](https://www.slicer.org/wiki/Documentation/Nightly/Modules/PlusRemote) still alive? I don't see it in [ExtensionsIndex](https://github.com/Slicer/ExtensionsIndex) and can't find it as a Slicer extension in my local installation of Slicer 4.10.2. More directly, what is the best way to control some devices hosted by a PlusServer from Slicer? The desired actions are start/stop recording, freeze, set parameters (e.g. frequency, depth, voltage), switch mode (B/M) etc.

Currently, we are doing it via a customized clone of PlusServer which accepts commands via console IO, and we connect to it from Slicer. The problem is that some longer actions can overlap with other actions. Would using [PlusServerRemoteControl](https://github.com/PlusToolkit/PlusLib/blob/b04613863f6f20c31a6851901fcd3317e042b6f7/src/PlusServer/Tools/PlusServerRemoteControl.cxx) be better?

How much effort would be required to fully support complete control over Capistrano and WinProbe ultrasound devices, and over a serial device in Plus? Do Plus maintainers have any plans to do some infrastructure work for this? If we do this all by ourselves, would it have a warm reception for inclusion into PlusLib? Where would we start adding/modifying code?

CC: @jamesobutler @tomekcz @adamaji @jrojasUNC

**Comment by Sunderlandkyl** [comment]
The PlusRemote module is included in SlicerOpenIGTLink.

It should be relatively easy to add control for ultrasound parameters in Plus. The UltrasoundRemoteControl module in SlicerOpenIGTLink has custom sliders to control parameters (Depth/Frequency/Gain/etc.) for ultrasound devices. It's just a simple python module and the parameter sliders can be added to any module.

Ultrasound remote control module:
https://github.com/openigtlink/SlicerOpenIGTLink/blob/master/UltrasoundRemoteControl/UltrasoundRemoteControl.py

Ultrasound parameter widgets:
https://github.com/openigtlink/SlicerOpenIGTLink/tree/master/UltrasoundRemoteControl/Widgets

**Comment by adamrankin** [comment]
I’m on board to contribute towards this. As Kyle said there is some infrastructure already towards this end.

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
