### ISSUE TITLE
PlusServerLaunch Error

### ISSUE THREAD

**Issue by nkusongzhichao** [PlusToolkit/PlusLib#724]
I am sorry to trouble you.

When I run PlusServerLaunch in windows 10 with NDI Vega by IP, it works well.

but in the same way, I use PlusServerLaunch with NDI vega by IP, it didn't work.

it returned:
``Server host name: wordstation-HP-Z6-G4-Workstation
Server IP addresses: 127.0.0.1, 169.254.0.1, 10.134.67.98
Start remote control server at port: 18904
Connect using configuration file: /home/wordstation/PlusBuild/PlusLibData/ConfigFiles/PlusDeviceSet_Server_NDIVega.xml
Server process command line: "/home/wordstation/PlusBuild/bin/PlusServer" --config-file="PlusDeviceSet_Server_NDIVega.xml" --verbose=3
|ERROR|028.891077| Server stopped unexpectedly. Return code: 1| in /home/wordstation/PlusBuild/PlusApp/PlusServerLauncher/PlusServerLauncherMainWindow.cxx(865)
Disconnect request successful
|ERROR|028.930866| Failed to start server process| in /home/wordstation/PlusBuild/PlusApp/PlusServerLauncher/PlusServerLauncherMainWindow.cxx(339)
Connect using configuration file: /home/wordstation/PlusBuild/PlusLibData/ConfigFiles/PlusDeviceSet_Server_NDIVega.xml
Server process command line: "/home/wordstation/PlusBuild/bin/PlusServer" --config-file="PlusDeviceSet_Server_NDIVega.xml" --verbose=3
|ERROR|360.451359| Server stopped unexpectedly. Return code: 1| in /home/wordstation/PlusBuild/PlusApp/PlusServerLauncher/PlusServerLauncherMainWindow.cxx(865)
Disconnect request successful
``
Thank you very much!!

**Comment by nkusongzhichao** [comment]
``|ERROR|008.162871| Server stopped unexpectedly. Return code: 1| in /home/wordstation/PlusBuild/PlusApp/PlusServerLauncher/PlusServerLauncherMainWindow.cxx(865)
|INFO|008.201269| Disconnect request successful| in /home/wordstation/PlusBuild/PlusApp/PlusServerLauncher/PlusServerLauncherMainWindow.cxx(633)
|ERROR|008.201995| Failed to start server process| in /home/wordstation/PlusBuild/PlusApp/PlusServerLauncher/PlusServerLauncherMainWindow.cxx(339)``
```
<PlusConfiguration version="2.1">
  <DataCollection StartupDelaySec="1.0" >
    <DeviceSet
      Name="PlusServer: NDI Vega tracker with passive markers - by IP"
      Description="Broadcasting tool tracking data through OpenIGTLink
For NDI Vega: Tool (8700339), Stylus (8700340), Reference (8700449)" />
    <Device
      Id="TrackerDevice"
      Type="NDITracker"
      NetworkHostname="169.254.121.19"
      NetworkPort="8765"
      ToolReferenceFrame="Reference" >
      <DataSources>
        <DataSource Type="Tool" Id="Tool" RomFile="NdiToolDefinitions/8700339.rom"  />
        <DataSource Type="Tool" Id="Stylus" RomFile="NdiToolDefinitions/8700340.rom"  />
        <DataSource Type="Tool" Id="Reference" RomFile="NdiToolDefinitions/8700449.rom"  />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream" >
          <DataSource Id="Tool"/>
          <DataSource Id="Stylus"/>
          <DataSource Id="Reference"/>		  
        </OutputChannel>
      </OutputChannels>
    </Device>
	<!--
    <Device
      Id="VideoDevice"
      Type="OpenCVVideo"
      VideoURL="rtsp://169.254.121.19/video">
      <DataSources>
        <DataSource Type="Video" Id="Video" ImageType="RGB_COLOR" PortUsImageOrientation="MF"  />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStream" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>
    <Device
      Id="TrackedVideoDevice"
      Type="VirtualMixer" >
      <InputChannels>
        <InputChannel Id="TrackerStream" />
        <InputChannel Id="VideoStream" />
      </InputChannels>
      <OutputChannels>
        <OutputChannel Id="TrackedVideoStream"/>
      </OutputChannels>
    </Device>
	-->
  </DataCollection>
  <CoordinateDefinitions>	
    <Transform From="Image" To="Reference"
      Matrix="
        1 0 0 0
        0 1 0 0
        0 0 1 0
        0 0 0 1"
       Error="0.554951" Date="012617_105449" />	   
    <Transform From="StylusTip" To="Stylus"
      Matrix="
        1 0 0 0
        0 1 0 0
        0 0 1 0
        0 0 0 1"		
       Error="0.554951" Date="012617_105449" />
	  <!--
        1 0 0.000203823 0.0180449
        3.31529e-09 -1  -1.62655e-05  -0.00144002
        0.000203823 1.62655e-05 -1  -88.5321
        0 0 0 1"
		-->
  </CoordinateDefinitions>
  <PlusOpenIGTLinkServer
    MaxNumberOfIgtlMessagesToSend="1"
    MaxTimeSpentWithProcessingMs="50"
    ListeningPort="18944"
    SendValidTransformsOnly="true"
    OutputChannelId="TrackerStream" >
    <DefaultClientInfo>
      <MessageTypes>
        <Message Type="IMAGE" />
        <Message Type="TRANSFORM" />
      </MessageTypes>
      <ImageNames>
        <Image Name="Image" EmbeddedTransformToFrame="Reference" />
      </ImageNames>
      <TransformNames>
        <Transform Name="StylusTipToReference" />
      </TransformNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>
</PlusConfiguration>
```

**Comment by nkusongzhichao** [comment]
I add two pic to show my ip setting
![eth setting](https://user-images.githubusercontent.com/45937564/95462662-62b43680-09aa-11eb-98de-15b83ca80ef6.png)
![NDI Vega](https://user-images.githubusercontent.com/45937564/95462675-6647bd80-09aa-11eb-9679-bf09c4d9f3c2.png)

**Comment by adamrankin** [comment]
Do you mean it works with bonjour (Vega name) but not with ip?

**Comment by nkusongzhichao** [comment]
> Do you mean it works with bonjour (Vega name) but not with ip?

No, on Linux I use ip to connect Vega with my computer. It can work well with track software but it can't run with PlusServerLauncher.

But in Windows, it can work well both with track software and PlusServerLauncher by ip.

**Comment by adamrankin** [comment]
Hmm, I'm not sure. Have you tried in linux to disable AppArmor or SELinux?

**Comment by nkusongzhichao** [comment]
> AppArmor



> Hmm, I'm not sure. Have you tried in linux to disable AppArmor or SELinux?

Thanks, I will try it
