### ISSUE TITLE
Plus Installation

### ISSUE THREAD

**Issue by nayanw775** [PlusToolkit/PlusLib#726]
Hello Plusapp Team,

I was going through the manual shown in the image to install Plusapp for Slicer3D. Since i am new to the page and the topic can you please guide me to how to install Plus for slicer and what are the actual requirements.  After opening the .exe file of Plusapp it ask me to the "Plus Server Launcher and under Device set configuration directory: Open the directory path
to the ending in the Config folder" but i am unable to find the config file.
Can you please help me the issue?

![Untitled](https://user-images.githubusercontent.com/72604275/95574558-bfffc480-0a4a-11eb-9d83-eabd20b235c9.jpg)

**Comment by nayanw775** [comment]
Hello Plusapp team,

I request you to please help me in solving this issue.

Thank you
Nayan Wadhwani

**Comment by Sunderlandkyl** [comment]
The config file directory should be:
PlusApp-XYZ\config.

Where is this Manual.pdf from?

**Comment by nayanw775** [comment]
Thanks Sunderland for the reply.

Author of the manual is Frank Preiswerk et,al., I don't know when they published this article and full of the paper is "Manual for open source Neuro-Navigation System"

One more question I would like to ask is how to link Plusapp and Slicer and to setup things to make them work in sync.

**Comment by adamrankin** [comment]
PlusServer broadcasts data, and Slicer, with OpenIGTLink extension, receives this data. 

I think you will find this page helpful
http://www.slicerigt.org/wp/user-tutorial/

**Comment by adamrankin** [comment]
Let us know if you have any further questions!

**Comment by nayanw775** [comment]
Hello Adam,

I downloaded plus server launcher successfully but when i try to open, it pops with the error shown in the image. I tried to solve the issue by downloading .dll files and putting it into the bin folder after that i tried to open the file again and it pops with some other error message which is attached below. I tried to solve the issue at my level but i still keep getting the same error. 
Updated my .NET framework, Rebooted Application several times, Updated my windows.
Is there anything else that you can suggest me!!

PFA
Thank you
Nayan



![Plusapp error](https://user-images.githubusercontent.com/72604275/96689931-acd0eb00-13a0-11eb-992d-abd8a8e2f154.jpg)
![Application error](https://user-images.githubusercontent.com/72604275/96689963-b8241680-13a0-11eb-9bc5-5f9ab69290bc.jpg)

**Comment by adamrankin** [comment]
You have to install the Visual Studio 2013 redistributable.

https://support.microsoft.com/en-us/help/4032938/update-for-visual-c-2013-redistributable-package

If you are running 32 bit plus, install the x86 of your language. If
running 64 bit plus, install the x64 of your language.
