### ISSUE TITLE
FusionTrack500 last SDK version connection with PlusServer

### ISSUE THREAD

**Issue by orubioDeneb** [PlusToolkit/PlusLib#728]
Hi all,

Im trying to use PlusServer for creating a OpenIGTLink Server and get marker information with a FusionTrack 500 device. I can succesfully connect the device and track some markers (with good error values) with the demo program from atracsys Included in their last driver version (4.5.2).
When I use Plus server, I also get connected, but I cant see any transformation value on Slicer, and i get some Warnings

![Captura de pantalla 2020-10-16 152152](https://user-images.githubusercontent.com/72980989/96263574-71f73d80-0fc3-11eb-84ab-ae9459f99707.png)

I tried to Increase max registration error and activated sending non valid transformation, but I only see Identity matrices on Slicer. Checked that geometry files are OK because they give me errors less than 0.1mm in the fusionTrack Demo software.
Also tried to compile plusBuild with atracsys compatibility activated but i get error on some missing  XXX-config.cmake for Pluslib,PlusApp and OpenIGTLinkIO.

I would appreciate any advice. Thanks in advance.
Oliver

**Comment by Sunderlandkyl** [comment]
Do you have a USB 3.0 port? The warning message says the Atracsys is plugged into USB 2.0.

According to the device documentation at: http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceAtracsys.html, the latest supported SDK in Plus is fusionTrack 4.1.3.

@markasselin Do you have any suggestions?

**Comment by orubioDeneb** [comment]
@Sunderlandkyl Thanks for your suggestions.The device is connected to the USB-C port of a laptop by means of a Ethernet to USB-C adapter, as the laptop does not have an ethernet port, but tried to connect to a desktop computer directly by ethernet and had the same warning(neither working).

The used port should not be the problem as the demo API program works connected to the same port at full supported speed even sending raw images. Will try to install the 4.1.3 Version and see if it works.

**Comment by orubioDeneb** [comment]
Tried in the desktop computer with the 4.1.3 SDK with same results. Also tried compiling without device compatibility for checking if the Atracsys API compilation was the problem and had same issue when building the project:

```
CMake Error at src/CMakeLists.txt:45 (FIND_PACKAGE):
13>  Could not find a package configuration file provided by "OpenIGTLinkIO"
13>  with any of the following names:
13>
13>    OpenIGTLinkIOConfig.cmake
13>    openigtlinkio-config.cmake
13>
13>  Add the installation prefix of "OpenIGTLinkIO" to CMAKE_PREFIX_PATH or set
13>  "OpenIGTLinkIO_DIR" to a directory containing one of the above files.  If
13>  "OpenIGTLinkIO" provides a separate development package or SDK, be sure it
13>  has been installed.
```

**Comment by Sunderlandkyl** [comment]
Did you check out and compile Plus using the PlusBuild repository?
https://github.com/PlusToolkit/PlusBuild/

Windows build instructions:
https://github.com/PlusToolkit/PlusBuild/blob/master/Docs/BuildInstructionsWindows.md

**Comment by orubioDeneb** [comment]
I did tried to compile with the update repository, also changed from msvc2017 to msvc2015 for qt (already using visual studio 2017) and still having the same errors of the last post, for OpenIGTLinkIO and PlusLib. Searching the compilation output for errors, i've seen the following:

```
12>CMake Error at C:/D/PlusB-bin/vtk-int/lib/cmake/vtk-8.2/vtkModuleAPI.cmake:140 (message):
12>  Requested modules not available:
12>
12>    IOImage
12>    ImagingMath
12>Call Stack (most recent call first):
12>  C:/D/PlusB-bin/vtk-int/lib/cmake/vtk-8.2/VTKConfig.cmake:143 (vtk_module_config)
12>  Converter/CMakeLists.txt:10 (find_package)
```
Even if I search for IOImage and ImagingMath and I get output lines returning that the code is up to date.

**Comment by orubioDeneb** [comment]
It could have something to do with #727, as here there is a change on the prefix of that 2 modules not found, even if its stated that it compiler OK with vtk8.2.

I did a checkout on a previous commit on OpenIGTLinkIO repo and forced offline build for not allowing a update of the rep to the problematic comit (as all the rest of the modules should be already updated). Also changed to 4.4.1 Atracsys SDK as #634 states (Last SDK version had some missing definition and failed). Now it compiles and i connect and receive data from the tracker on Slicer.

**Comment by adamrankin** [comment]
OpenIGTLinkIO has been fixed up and should be able to run the PlusBuild again.
