### ISSUE TITLE
Question about the application of PLUS to the acquisition of ultrasound images from Philip ultrasound machine.

### ISSUE THREAD

**Issue by zxmboshi** [PlusToolkit/PlusLib#729]
Dear friends:

Our groups is trying to use PLUS to acquire the ultrasound images from Philip ultrasound machine.  

On the webist https://plustoolkit.github.io/features, it mentions that PLUS  can realize
Image acquisition from ultrasound systems:  through direct digital interface (for Ultrasonix, BK, Interson, Telemed, Philips ultrasound scanners) and through framegrabbers.

However, we have checked all the packages listed at https://plustoolkit.github.io/download and found that no special package can be used for our task. 

Here we wonder which package can be chosen for your task!

Thanks a lot!

**Comment by Sunderlandkyl** [comment]
Thanks! There is an issue with the Plus nightly build, but I'm in the process of fixing it. I'll let you know when they're available.

**Comment by zxmboshi** [comment]
> Thanks! There is an issue with the Plus nightly build, but I'm in the process of fixing it. I'll let you know when they're available.

Dear Sunderlandkyl:

Thank you for your response. Do you mean that the application of PLUS to Philip ultrasound machine can be found in the the Plus nightly build and currently it needs to be fixed for some issues? For the plus,  there are Latest stable release and
Latest development snapshot. Which one should we download? I find that even for Latest stable release, I can find the following programs and it seems that no special program can be found  for the Philip ultrasound machine.  


  | PlusApp-2.8.0.20191105-Interson-MTC-3.7-Win32.exe | 2020-10-17 07:21 | 79M | 
  | PlusApp-2.8.0.20191105-MTC-3.7-Win32.exe | 2020-10-17 07:09 | 79M |  
  | PlusApp-2.8.0.20191105-Telemed-Win32.exe | 2020-10-17 07:33 | 79M |  
  | PlusApp-2.8.0.20191105-ThorLabs-Win32.exe | 2020-10-17 06:57 | 103M |  
  | PlusApp-2.8.0.20191105-Ultrasonix-5.7-Win32.exe | 2020-10-17 06:31 | 65M |  
  | PlusApp-2.8.0.20191105-Ultrasonix-6.1-Win32.exe | 2020-10-17 06:43 | 82M |  
  | PlusApp-2.8.0.20191105-Win32.exe | 2020-10-17 06:20 | 106M |  
  | PlusApp-2.8.0.20191105-Win64.exe | 2020-10-17 08:20 | 102M |  
  | PlusApp-2.8.0.20191105-fusionTrack-Win64.exe | 2020-10-17 07:57 | 102M |  
  | PlusApp-2.8.0.20191105-spryTrack-Telemed-Win32.exe | 2020-10-17 07:45 | 80M |  
  | PlusApp-StealthLink.zip

**Comment by adamrankin** [comment]
Philips does not provide a research interface for their machines, so a framegrabber must be used. There are many options, and almost all of them can be used with the mmfvideo device, which is in all windows packages.

**Comment by zxmboshi** [comment]
> Philips does not provide a research interface for their machines, so a framegrabber must be used. There are many options, and almost all of them can be used with the mmfvideo device, which is in all windows packages.
> […](#)
> On Oct 17, 2020, at 09:39, zxmboshi ***@***.***> wrote: ﻿ Thanks! There is an issue with the Plus nightly build, but I'm in the process of fixing it. I'll let you know when they're available. Dear Sunderlandkyl: Thank you for your response. Do you mean that the application of PLUS to Philip ultrasound machine can be found in the the Plus nightly build and currently it needs to be fixed for some issues? For the plus, there are Latest stable release and Latest development snapshot. Which one should we download? I find that even for Latest stable release, I can find the following programs and it seems that no special program can be found for the Philip ultrasound machine. | PlusApp-2.8.0.20191105-Interson-MTC-3.7-Win32.exe | 2020-10-17 07:21 | 79M | | PlusApp-2.8.0.20191105-MTC-3.7-Win32.exe | 2020-10-17 07:09 | 79M | | PlusApp-2.8.0.20191105-Telemed-Win32.exe | 2020-10-17 07:33 | 79M | | PlusApp-2.8.0.20191105-ThorLabs-Win32.exe | 2020-10-17 06:57 | 103M | | PlusApp-2.8.0.20191105-Ultrasonix-5.7-Win32.exe | 2020-10-17 06:31 | 65M | | PlusApp-2.8.0.20191105-Ultrasonix-6.1-Win32.exe | 2020-10-17 06:43 | 82M | | PlusApp-2.8.0.20191105-Win32.exe | 2020-10-17 06:20 | 106M | | PlusApp-2.8.0.20191105-Win64.exe | 2020-10-17 08:20 | 102M | | PlusApp-2.8.0.20191105-fusionTrack-Win64.exe | 2020-10-17 07:57 | 102M | | PlusApp-2.8.0.20191105-spryTrack-Telemed-Win32.exe | 2020-10-17 07:45 | 80M | | PlusApp-StealthLink.zip — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

We have tried to use the framegrabber to acquire the ultrasound images from philip ultrasound machine. However, it can only work for 2D ultrasound. For 4D ultrasound, we cannot get the original data in this way because what we have acquired through the  framegrabber are not the true 3D images but their 2D images. The 2D images seem to be same to 3D images shown on the screen of the ultrasound machine and they have not any 3D spatial information. Therefore, the data we have  acquired through the framegrabber cannot be used for medical image analysis on our computer.  It seems that we must give up this scheme based on framegrabber.  

Suppose that the data will be submitted from the ultrasound machines that the PLUS does not support to our computer through network, what is the reasonable method to show the received ultrasound data in 3D slicer synchronously?  Is it possible to still use PLUS to receive the data and send them through the openIGTlinkIF to show in 3D Slicer? If it is impossible to use PLUS in this case, can we directly use 3D slicer to receive the data submitted from the ultrasound images through the network?

Thanks a lot~~~~

**Comment by adamrankin** [comment]
Yes, if you're trying to capture streaming 3D data from Philips, you'll have to have a research agreement and access to that data over the network.

If you already have this capability, you could create a device in Plus to receive this data, repackage it, and forward it along. I have already done this with an existing Philips research interface, but it may not work for you.

https://github.com/PlusToolkit/PlusLib/tree/master/src/PlusDataCollection/Philips3D

If you want to try and stream it directly to Slicer, you will have to implement an OpenIGTLink server that Slicer can connect to (this is what PlusServer is).

**Comment by lassoan** [comment]
We had a couple of tries with interfacing Philips ultrasound systems and technically there should be no problems at all (they have suitable interfaces), but the company always wanted too much control over what we can do with their systems and how, so this was just not worth the trouble.

In contrast, GE seems to be much more open. You can get access to GE 3D ultrasound interfaces and SDKs by filling out a web form (https://www.gehealthcare.com/products/edison/edison-developer-program).
