### ISSUE TITLE
Transfer self-build plustoolkit to other computer

### ISSUE THREAD

**Issue by Marinho95** [PlusToolkit/PlusLib#730]
Hi,
We built the plustoolkit ourselves on one computer and it works for our application. However, I want to use this plustoolkit on another computer as well. How do you transfer the built program from one computer to another?

I tried to zip the whole directory and unpack it on the other computer. But when I tried running the PlusServerLauncher it gave the following error message: This application failed to start because it could not find or load the Qt platform plugin "windows" in "". Reinstalling the application may fix this problem.

Is there a way to fix this or is there another way to transfer the built program?

Thanks

**Comment by adamrankin** [comment]
Yes, you have to build the PACKAGE target in PlusApp. That will create a zip file (and an NSIS installer on windows, if installed).
