### ISSUE TITLE
Low frame rate from the ultrasound frame grabber 

### ISSUE THREAD

**Issue by AurelieSar** [PlusToolkit/PlusLib#732]
Hi everyone,

I am using Slicer 4.11.0 with PlusServer to do 3D ultrasound. 
I have an Optitrack motion analysis system and a frame grabber called ElGato CamLink 4K USB video capture device linked to a SuperShearing Imaging ultrasound. 

All is working fine, except whatever the frame rate I request, the video frame rate from the ultrasound does not go above 5-6Hz, which is very low. 
I tried both by recording using the module 'Sequences' with the following configuration file : 

`<PlusConfiguration version="2.7" PlusRevision="Plus-2.8.0.62873a16 - Win64">
  <DataCollection StartupDelaySec="1">
    <DeviceSet Name="PlusServer: LaboMIP ACQUISITION" Description="Configuration file with Optitrack Flex 13 (Motive 2.2.0) and video feed from the SSI ultrasound Probe SL10-2 with CAM LINK 4K USB." />
    <Device
      Id="TrackerDevice"
      Type="OptiTrack"
      ToolReferenceFrame="Tracker"
      Profile="motiveprofilefile.xml"
      AttachToRunningMotive="TRUE"
      MotiveDataDescriptionsUpdateTimeSec="1.0"
      LocalTimeOffsetSec="0.5347">
      <DataSources>
        <DataSource Type="Tool" Id="Probe" BufferSize="150" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream">
          <DataSource Type="Tool" Id="Probe" />
        </OutputChannel>
      </OutputChannels>
    </Device>
    <Device Id="VideoDevice" Type="MmfVideo" FrameSize="1680 1050" VideoFormat="YUY2" CaptureDeviceId="0">
      <DataSources>
        <DataSource
          Type="Video"
          Id="Video"
          PortUsImageOrientation="UF"
          ClipRectangleOrigin="240 120 0"
          ClipRectangleSize="920 880 1"
          BufferSize="150" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStream" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>
    <Device Id="TrackedVideoDevice" Type="VirtualMixer">
      <InputChannels>
        <InputChannel Id="TrackerStream" />
        <InputChannel Id="VideoStream" />
      </InputChannels>
      <OutputChannels>
        <OutputChannel Id="TrackedVideoStream" />
      </OutputChannels>
    </Device>
  </DataCollection>
  <PlusOpenIGTLinkServer MaxNumberOfIgtlMessagesToSend="1" MaxTimeSpentWithProcessingMs="50" ListeningPort="18944" SendValidTransformsOnly="TRUE" OutputChannelId="TrackedVideoStream">
    <DefaultClientInfo>
      <MessageTypes>
	    <Message Type="IMAGE" />
        <Message Type="TRANSFORM" />
      </MessageTypes>
      <TransformNames>
		<Transform Name="ProbeToTracker" />
      </TransformNames>
	  <ImageNames>
        <Image Name="Image" EmbeddedTransformToFrame="Image" />
      </ImageNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>
  <fCal
    StylusModelId="StylusModel"
    ImageDisplayableObjectId="LiveImage"
    NumberOfCalibrationImagesToAcquire="200"
    NumberOfValidationImagesToAcquire="100"
    NumberOfStylusCalibrationPointsToAcquire="200"
    RecordingIntervalMs="100"
    MaxTimeSpentWithProcessingMs="70"
    ImageCoordinateFrame="Image"
    ProbeCoordinateFrame="Probe"
    ReferenceCoordinateFrame="Tracker"
    TransducerOriginCoordinateFrame="TransducerOrigin"
    TransducerOriginPixelCoordinateFrame="TransducerOriginPixel"
    TemporalCalibrationDurationSec="20"
    FixedChannelId="VideoStream"
    FixedSourceId="Video"
    MovingChannelId="TrackerStream"
    MovingSourceId="ProbeToTracker"
    DefaultSelectedChannelId="TrackedVideoStream"
    FreeHandStartupDelaySec="5" />
</PlusConfiguration>
`

And using the PlusRemote using this configuration file : 
`<PlusConfiguration version="2.7" PlusRevision="Plus-2.8.0.62873a16 - Win64">
  <DataCollection StartupDelaySec="1">
    <DeviceSet Name="PlusServer: LaboMIP ACQUISITION" Description="Configuration file with Optitrack Flex 13 (Motive 2.2.0) and video feed from the SSI ultrasound Probe SL10-2 with CAM LINK 4K USB." />
    <Device
      Id="TrackerDevice"
      Type="OptiTrack"
      ToolReferenceFrame="Tracker"
      Profile="motiveprofilefile.xml"
      AttachToRunningMotive="TRUE"
      MotiveDataDescriptionsUpdateTimeSec="1.0"
      LocalTimeOffsetSec="0.5347">
      <DataSources>
        <DataSource Type="Tool" Id="Probe" BufferSize="150" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream">
          <DataSource Type="Tool" Id="Probe" />
        </OutputChannel>
      </OutputChannels>
    </Device>
    <Device Id="VideoDevice" Type="MmfVideo" FrameSize="1680 1050" VideoFormat="YUY2" CaptureDeviceId="0">
      <DataSources>
        <DataSource
          Type="Video"
          Id="Video"
          PortUsImageOrientation="UF"
          ClipRectangleOrigin="240 120 0"
          ClipRectangleSize="920 880 1"
          BufferSize="150" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStream" VideoDataSourceId="Video" />
      </OutputChannels>
    </Device>
    <Device Id="TrackedVideoDevice" Type="VirtualMixer">
      <InputChannels>
        <InputChannel Id="TrackerStream" />
        <InputChannel Id="VideoStream" />
      </InputChannels>
      <OutputChannels>
        <OutputChannel Id="TrackedVideoStream" />
      </OutputChannels>
    </Device>
    <Device
      Id="CaptureDevice"
      Type="VirtualCapture"
      BaseFilename="RecordingTest.igs.mha"
      EnableCapturingOnStart="FALSE"
      EnableCapturing="FALSE"
      EnableFileCompression="FALSE"
      EnableCaptureOnStart="FALSE"
      RequestedFrameRate="15">
      <InputChannels>
        <InputChannel Id="TrackedVideoStream" />
      </InputChannels>
    </Device>
  </DataCollection>
  <PlusOpenIGTLinkServer MaxNumberOfIgtlMessagesToSend="1" MaxTimeSpentWithProcessingMs="50" ListeningPort="18944" SendValidTransformsOnly="TRUE" OutputChannelId="TrackedVideoStream">
    <DefaultClientInfo>
      <MessageTypes>
	    <Message Type="IMAGE" />
        <Message Type="TRANSFORM" />
      </MessageTypes>
      <TransformNames>
		<Transform Name="ProbeToTracker" />
      </TransformNames>
	  <ImageNames>
        <Image Name="Image" EmbeddedTransformToFrame="Image" />
      </ImageNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>
  <fCal
    StylusModelId="StylusModel"
    ImageDisplayableObjectId="LiveImage"
    NumberOfCalibrationImagesToAcquire="200"
    NumberOfValidationImagesToAcquire="100"
    NumberOfStylusCalibrationPointsToAcquire="200"
    RecordingIntervalMs="100"
    MaxTimeSpentWithProcessingMs="70"
    ImageCoordinateFrame="Image"
    ProbeCoordinateFrame="Probe"
    ReferenceCoordinateFrame="Tracker"
    TransducerOriginCoordinateFrame="TransducerOrigin"
    TransducerOriginPixelCoordinateFrame="TransducerOriginPixel"
    TemporalCalibrationDurationSec="20"
    FixedChannelId="VideoStream"
    FixedSourceId="Video"
    MovingChannelId="TrackerStream"
    MovingSourceId="ProbeToTracker"
    DefaultSelectedChannelId="TrackedVideoStream"
    FreeHandStartupDelaySec="5" />
</PlusConfiguration>
`

In both cases and whatever the frequency I request, the video frame rate is the same, about 5-6Hz, while the tracker frame rate can go up to about 30Hz. 

When I use another recording software for the video feed (like OBS), the default frequency is 60Hz and all is working perfectly fine. 

I obtain huge log files when I do acquisitions having a lot of errors like this one : 

`102920_155800.907|ERROR|127.340000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.909|ERROR|127.341000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.909|ERROR|127.341000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.910|ERROR|127.342000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.910|ERROR|127.342000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.910|ERROR|127.342000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.911|ERROR|127.343000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.911|ERROR|127.343000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.912|ERROR|127.344000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.912|ERROR|127.344000|SERVER> Failed to get tracked frame list from data collector (last recorded timestamp: 106.983814| in :\D\PSNP64b\PlusLib\src\PlusServer\vtkPlusOpenIGTLinkServer.cxx(432)
102920_155800.913|ERROR|127.345000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.913|ERROR|127.345000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.914|ERROR|127.346000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.914|ERROR|127.346000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.914|ERROR|127.346000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.914|ERROR|127.346000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.914|ERROR|127.347000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.914|ERROR|127.347000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.914|ERROR|127.347000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.916|ERROR|127.348000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.916|ERROR|127.348000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.917|ERROR|127.349000|SERVER> Failed to get tracked frame list from data collector (last recorded timestamp: 106.983814| in :\D\PSNP64b\PlusLib\src\PlusServer\vtkPlusOpenIGTLinkServer.cxx(432)
102920_155800.917|ERROR|127.349000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.917|ERROR|127.350000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.917|ERROR|127.350000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
102920_155800.917|ERROR|127.350000|SERVER> Failed to get tracker buffer item by timestamp 106.984. Item not available yet.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(833)
`

do you know what is wrong ?
Thanks in advance,
Aurélie

**Comment by AurelieSar** [comment]
Sorry about the unreadable code, here are both config files and the log file : 
[config.zip](https://github.com/PlusToolkit/PlusLib/files/5464420/config.zip)

**Comment by Sunderlandkyl** [comment]
Does the framerate increase if you try a lower resolution?
Also, is there a demo application with your framegrabber? What kind of framerate do you get with that?

**Comment by AurelieSar** [comment]
Thank you for your response. 
I managed to get back to the lab to perform further testing this morning, and actually the CAM LINK USB frame grabber needed to be plugged in an USB 3.0 plug for the video feed to be able to go up to 40Hz in Slicer (versus 5Hz when plugged into an USB 2.0 plug).... surprisingly, this difference in frame rate recording was not present in 'classical' softwares like OBS.
Anyway you can close this ticket, thanks again for all your work.
