### ISSUE TITLE
Microsoft Media Foundation compatible imaging device

### ISSUE THREAD

**Issue by yogeren** [PlusToolkit/PlusLib#733]
Hi! I'm using MmfVideo, the code is attached.  The problem: it conneceds to my webcam instead of the frame grabber.

Thank you very much

[PlusDeviceSet_Server_Compatible frame grabber.txt](https://github.com/PlusToolkit/PlusLib/files/5473703/PlusDeviceSet_Server_Compatible.frame.grabber.txt)

**Comment by Sunderlandkyl** [comment]
Try changing the CaptureDeviceId to a different number,
