### ISSUE TITLE
Cannot connect to NDI Polaris with Plus Server Launcher

### ISSUE THREAD

**Issue by IngerGrunbeck** [PlusToolkit/PlusLib#741]
Hi! 
I'm trying to connect my Polaris Spectra to 3DSlicer using the Plus Server, but the connection keeps failing. My configuration file is based on the example provided by Plus. The error log and my config-file are attached. 

![Screenshot 2020-12-04 093710](https://user-images.githubusercontent.com/55082964/101142110-77f9ba00-3615-11eb-95f1-60505a4de2ac.png)

[Polaris_config.txt](https://github.com/PlusToolkit/PlusLib/files/5641539/Polaris_config.txt)

**Comment by adamrankin** [comment]
Are you able to upload the log file for the PlusServer itself?

**Comment by IngerGrunbeck** [comment]
Sure! 

[120320_180034_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/5643430/120320_180034_PlusLog.txt)

**Comment by adamrankin** [comment]
Hmm, sadly not much information there. Is this reproduceable? If so, we could investigate further.

**Comment by Zulex** [comment]
Try following this tutorial, worked in my case: 
https://www.slicer.org/w/img_auth.php/f/f1/OpenIGTLinkTutorial_Slicer4.1.0_JunichiTokuda_Apr2012.pdf

Also, make sure the provided software by NDI is also able to connect. I had some issues with that and apparently it was an usb driver issue. If that works, the tutorial is pretty straightforward.

**Comment by IngerGrunbeck** [comment]
Sorry for a late answer, and thanks for the help! I've finally managed to connect :)

**Comment by drvarunagarwal** [comment]
Hi,

I am also having trouble connecting Polaris to plus server.
My setup is as follows:

actually I have a spare medtronic stealthstation S7.
So I am trying to use its NDI polaris to connect to plus server.

I opened the front panel of the stealth and found the control box for the camera. I disconnected the serial port cable connecting that box to the stealthstation computer.

Then connected a serial cable from my windows 10 computer running plus server to the control box.
Please see the pic:

![IMG_1167](https://user-images.githubusercontent.com/76910274/103481786-0fb01b00-4e03-11eb-8fa7-d4ce109937ca.JPG)

There was default config file for NDI polaris with passive trackers.

I added 3 lines to it as below.

![IMG_1166](https://user-images.githubusercontent.com/76910274/103481830-3cfcc900-4e03-11eb-87bd-3601d06f35ee.JPG)

![IMG_1165](https://user-images.githubusercontent.com/76910274/103481833-3f5f2300-4e03-11eb-9973-845d507df5e0.JPG)

I get a connection failed message.

Please advise how to go about this.

Will be highly grateful.
many thanks in anticipation

**Comment by adamrankin** [comment]
What is the error message in the log? (Click on the red circle to see the log, or find the log file on disk)

**Comment by drvarunagarwal** [comment]
can you please tell me the name and location of the log file. I can't seem to find it.
thanks

**Comment by adamrankin** [comment]
It will be under <PlusInstall>/bin/Output

**Comment by drvarunagarwal** [comment]
hi,

there is no folder named output in the /bin folder

also not file with the name log.

what is the name of log file.
how to check it?
Please advise

many thanks

**Comment by drvarunagarwal** [comment]
Hi,

Attached is the file I could find.

[010321_010408_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/5769977/010321_010408_PlusLog.txt)


Please advise.
many thanks

**Comment by adamrankin** [comment]
Here is the relevent error:
`010321_010745.077|ERROR|216.447000|SERVER> Failed to detect device on serial port COM2`

Could you remove the serial port line from the config file and try again?

**Comment by drvarunagarwal** [comment]
Thanks for all the help

I also tried using the value of -1 that makes it to scan all ports?
that is also not working

So the original file that comes with plus toolkit doesn't have a serial port line.
It was not detecting with that

So I added three highlighted in blue lines.
Still no detection.

Failed to detect device. Port scanning failed. Error opening serial connection| in :\D\PSNPb\PlusLib\src\PlusDataCollection\NDICAPITracking\vtkPlusNDITracker.cxx(332)

I guess this last one is the latest error.

Also do I need to install any driver software or some such for NDI first?

I am just using a cable to attach from stealth station to computer running plus and have not installed any NDI software on that computer.

Please advise
thanks

**Comment by adamrankin** [comment]
Does the tracker work with NDI's Track software? There is a USB-to-serial driver that they provide as well, that might be the issue. Does is show up in your list of devices on your computer?

**Comment by drvarunagarwal** [comment]
No it doesn't show.

Can you tell me where I can get the drivers.
Since it is not officially bought from NDI, I don't have any software CD with me.

**Comment by lassoan** [comment]
You can get the driver, firmware, etc. from [NDI Support](https://support.ndigital.com/), but for your convenience, I include here a link to the software versions that we use: https://1drv.ms/u/s!Arm_AFxB9yqHlaAC8UXlYiYdRpLzZQ?e=kzfflc

If you update the SCU firmware then there is a chance (not likely, but possible) that it won't work with StealthStation anymore.

**Comment by drvarunagarwal** [comment]
many thanks

let me try and get back
thanks

**Comment by drvarunagarwal** [comment]
Hello everyone.

I tried with the files.
managed to install the NDI toolbox.

Still not able to connect.

![IMG_1182](https://user-images.githubusercontent.com/76910274/103888746-3b851680-510b-11eb-8cf8-130003b17c66.JPG)

NDI tooltracker says - COM1 USB converter fault.

Please see image below for my setup
![IMG_1184](https://user-images.githubusercontent.com/76910274/103889277-2957a800-510c-11eb-91a3-5542d0e4589c.JPG)

This is what my device manager shows.

![IMG_1183](https://user-images.githubusercontent.com/76910274/103888813-56f02180-510b-11eb-88ee-ad6044d85655.JPG)

When I try to update these drivers using the files from @lassoan they give error of either not found or some error ocurred.

Please guide and advise
many thanks

P.S. - I am also not able to connect the phidget MARG sensor. Thread below:
[https://github.com/PlusToolkit/PlusLib/issues/758](url)

**Comment by adamrankin** [comment]
I would use a known-working USB-to-serial for Windows 10 and connect it directly to your computer. Bypass that USB box directly (I'm not sure what that is).

**Comment by drvarunagarwal** [comment]
Ok

You mean connect the rs 232 port of control box to ‘known working USB to serial’ with the USB end in my computer.
Will try that tomorrow and get back.

Btw if I connect this rs 232 on control box directly via dual ended serial cable to my computer rs 232 port, (by passing the USB all together), it still doesn’t work.

Best Regards,
Dr. Varun Agarwal

**Comment by adamrankin** [comment]
NDI SCU (Control box I assume) -> rs232 to USB -> computer running Plus

**Comment by lassoan** [comment]
Yes, definitely don't use the Medtronic USB/serial hub/converter.

We had lots of problems finding reliable USB/RS232 converters 5-10 years ago. We bought about 8 different types that all looked very similar, they all used the Prolific chipset (original or counterfeit, we could not figure it out), but had different brand names. There were also lots of drivers - the one that was originally supplied usually did not work. At the end, only 1 or 2 worked reliably, and only with a specific driver. I think there were some IP theft issues and Prolific intentionally made it harder to use counterfeit chipsets with their drivers. The situation might have been improved by now. Make sure you buy a good brand name converter, with lots of good reviews.

If you have a physical RS232 port then you can avoid the uncertainty about the USB/RS232 converters. Note that many PC boxes still have a RS232 port, but usually it is not connected to the motherboard. You need to make sure that your motherboard has an RS232 interface and get a cable that connects the motherboard to the RS232 port on the PC box.

If you need to use

**Comment by drvarunagarwal** [comment]
I checked my computer RS-232 is connected to mother board.
So even by bypassing USB, still not able to connect.

Even to NDI software.
NDI tools also not detecting the camera.

**Comment by adamrankin** [comment]
Unfortunately I'm not sure if we can help you fix that issue. Perhaps the serial port on the motherboard is dead? You'll have to get the tracker detected by the NDI software.

**Comment by lassoan** [comment]
You may need to enable COM ports in your BIOS/UEFI settings and in your operating system.

**Comment by drvarunagarwal** [comment]
I just ran the setup file from the windows folder you sent.

It is not getting shown in NDI software also. It says COM1 USB Converter fault.

NDI help file says that NDI camera should also show in windows device manager.
It is not showing there also

Can it be medtronic has configured it in such a way that it can be used only with its own system?

**Comment by adamrankin** [comment]
Unlikely. I recommend you buy another USB to serial adapter. One with a TI chipset.

**Comment by lassoan** [comment]
> Can it be medtronic has configured it in such a way that it can be used only with its own system?

We used the Polaris tracker of a StealthStation from Plus without problems. StealthStation is mostly put together from off-the-shelf components, without any customization. Also note that if you have a research agreement in with Medtronic then they can give you a license to use StealthLink, which allows Plus to get live tracking data, calibration, and image from StealthStation and send it to Slicer.

**Comment by arterialflow** [comment]
"Unlikely. I recommend you buy another USB to serial adapter. One with a TI chipset."

hi I have three retired S7s and would like to use one with Plus/Slicer/Win10 for demo/educ.   I removed  SCU and localizer from one unit and found straight USB alone and Bluetooth serial adapter failed to connect to both NDI tools and Free-hand.  I will search to USB-serial with TI chipset - is baud 115200,  8,1,n  ?
thanks

**Comment by ningw-git** [comment]
> Sorry for a late answer, and thanks for the help! I've finally managed to connect :)

hello, I have the same trouble,how do you solve the problem. Help please.
