### ISSUE TITLE
BrainLabTrackerSim not sending TDATA messages

### ISSUE THREAD

**Issue by nclBaz** [PlusToolkit/PlusLib#743]
Hello everyone!

I've managed in building BrainLabTrackerSim.exe by following these instructions : [https://github.com/PlusToolkit/PlusBuild/blob/master/Docs/BuildInstructionsWindows.md](url)

I've got some problems with this executable, 'cause when I try to connect to it with 3DSlicer and I ask for sending me tracking data messages the application simply does not send anything at all as you can see in the following image:

![image](https://user-images.githubusercontent.com/25009192/101366900-d2a94500-38a5-11eb-8fc8-b3ea57bf88b6.png)

It receives STT_TDATA and STP_TDATA messages but does not start sending tracking messages. I've tried doing the same thing with an application I've developed, which is able to communicate following OpenIGTLink protocol, but I've obtained the very same result as with 3DSlicer. My application was able to successfully communicate with other simulators like TrackerServer.exe, obtaining TDATA messages

Any idea about this issue? Thanks in advance for any help :)

**Comment by Sunderlandkyl** [comment]
Thanks for reporting, I'll taking a look at it.

Could you tell me what versions of Plus and Slicer you are using?

**Comment by nclBaz** [comment]
Thanks for the answer :)
I'm using Slicer version 4.10.2 r28257. And we built pluslib 2.8

**Comment by Sunderlandkyl** [comment]
If you copy the changes from https://github.com/PlusToolkit/PlusLib/commit/605600e6ccc3c7e56e69bf920b33fda6065326ef in your 2.8 branch, the example should be functional.

**Comment by nclBaz** [comment]
It worked perfectly! Thank you so much sir!
