### ISSUE TITLE
 build a Slicer loadable module using Plus 

### ISSUE THREAD

**Issue by leilonghit** [PlusToolkit/PlusLib#747]
Dear friends:
I am trying to  build a Slicer loadable module using Plus, just as the Instructions said, I turned on PLUSBUILD_USE_3DSlicer option and set the PLUSBUILD_SLICER_BIN_DIRECTORY to my installed 3D Slicer binary folder, unfortunately, an error occured as "CMake Error at CMakeLists.txt:417 (MESSAGE):
  Unable to find Slicer at D:/Program Files (x86)/Slicer 4.11.20200930/bin
  directory.  Please verify configuration".
I dont know how to fix it, so could you do me a favor and give some more detailed instrucions about this obstacle. Thank you very much!
Best regards,
Long Lei

**Comment by adamrankin** [comment]
I'll take a look at the Slicer build setup. I don't know if it's been maintained in a while.

**Comment by adamrankin** [comment]
Ok, the build from Slicer source is working. Please note that you need to build Slicer, not download it. Building from Slicer source is to save compilation time or to ensure the same dependencies as Slicer.

**Comment by leilonghit** [comment]
> Ok, the build from Slicer source is working. Please note that you need to build Slicer, not download it. Building from Slicer source is to save compilation time or to ensure the same dependencies as Slicer.

okay，thanks!
