### ISSUE TITLE
Virtual Text Recognizer

### ISSUE THREAD

**Issue by hareem-nisar** [PlusToolkit/PlusLib#748]
Hi there, 

I am trying to read numbers from a video through PLUS Virtual Text Recognizer. But the language packages are not integrated properly. I have placed the tessdata folder in the PLUS folder and added it to environment variables as well.
The error I get is: 
|INFO|004.090000|SERVER> Error opening data file E:/D/PSNP64b/Deps/tessdata/eng.traineddata

**|INFO|004.091000|SERVER> Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
|INFO|004.091000|SERVER> Failed loading language 'eng'
|INFO|004.092000|SERVER> Tesseract couldn't load any languages!
|ERROR|004.092000|SERVER> Unable to init tesseract library. Cannot perform text recognition.| in: \D\PSNP64b\PlusLib\src\PlusDataCollection\VirtualDevices\vtkPlusVirtualTextRecognizer.cxx(241)
|ERROR|004.118000|SERVER> TextRecognizerDevice: Cannot connect to data source, ConnectInternal failed| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDevice.cxx(1147)
|ERROR|004.119000|SERVER> Unable to connect device: TextRecognizerDevice.| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDataCollector.cxx(353)
|ERROR|004.176000|SERVER> Datacollector failed to connect to devices| in :\D\PSNP64b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(106)
|ERROR|004.260000| Server stopped unexpectedly. Return code: 1| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(864)
|INFO|004.260000| Disconnect request successful| in E:\D\PSNP64b\PlusApp\PlusServerLauncher\PlusServerLauncherMainWindow.cxx(632)**

sample data files are [here](https://uwoca-my.sharepoint.com/:f:/g/personal/hnisar3_uwo_ca/EmvB6pyrx2pAmFbAziI60KQB__4rQcWd4jfHV4RdSIw1zg?e=RLybNz)

Thank you!

**Comment by adamrankin** [comment]
Couple of issues:

1) I'll check in 64 bit to see if this works.
2) You've got outdated code. We haven't used the Deps folder in a long time. Try with a more recent version of the code.

**Comment by adamrankin** [comment]
I built and ran it using current build under 32 bit and it worked. I'm building 64 bit now.

**Comment by hareem-nisar** [comment]
Thanks for looking into it. I was just installed the PlusApp - didn't know I had to build it - I am guessing that necessary for Text Recognizer to work?  
Also, I was using this ([here](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceVirtualTextRecognizer.html)) as a reference for code, is there an alternate webpage?

**Comment by adamrankin** [comment]
Found it. Glad I bumped into you.

Directory is hard coded to a location on the build server, not an installed location. I'll fix it.

**Comment by adamrankin** [comment]
Ok, download and use the version starting tomorrow (build machine runs overnight).

**Comment by hareem-nisar** [comment]
Perfect! Thank you Adam. It works great. 

P.S. There was a file missing (Qt5Multimedia.dll) but I copied it from another version and then it was ok.
