### ISSUE TITLE
PS-Tech optical tracker.

### ISSUE THREAD

**Issue by drvarunagarwal** [PlusToolkit/PlusLib#755]
Does the PS-Tech optical tracker system work with PlusToolkit?

https://www.ps-tech.com/products-pst-base-hd/

Has anyone any experience using this? esp need guidance regarding its accuracy vis a vis NDI polaris vega.

Any help appreciated.
thanks

**Comment by lassoan** [comment]
Plus does not support this device. A few people asked about it during the past 10 years, but nobody ended up needing it that much to spend a few weeks of work developing an interface class for it.

Plus already supports optical tracking devices in all price and accuracy range, so you should be able to find the hardware you need among them. For example, the Optitrack Duo is probably comparable to the device you linked.

If you want to get support for this device in Plus then you can get one and a software engineer with C++ programming experience should be able to develop the Plus interface class in a few weeks (we can help in getting that developer started). Or you may ask the company to develop this or add OpenIGTLink interface to their device.

**Comment by drvarunagarwal** [comment]
Thanks for the revert.

Optitrack Duo doesn't have linux.
that was the reason.
NDI is very expensive.

Is there any other you can suggest?

**Comment by lassoan** [comment]
Linux is not commonly used in medical devices. You can choose to deviate from the mainstream but then you have to accept that there are much less hardware to choose from and expect to pay more.

Plus supports Atracsys and it works on Linux, but it's software is not great and as far as I remember its cost is similar to NDI.

I don't see price list on ps-tech website. Did you get a quote from them?

**Comment by drvarunagarwal** [comment]
It is roughly half the price of NDI. But still more than optitrack.

The concern was that ROS (for robot) is on linux and would need an emulator environment to integrate with navigation based on slicer. And may not be stable. 

maybe I am missing something here.

Looking forward to your advise.
thanks for guidance.

**Comment by lassoan** [comment]
If you buy a robotic positioner (starting from about $50-100k) then saving $5-10k on position tracker should not make a difference.

Regarding ROS: You probably want to run your real-time robot control system on a separate computer than the GUI application. If you don't use the optical tracker in a tight control loop then you can run the GUI application on a Windows PC and connect the tracker to that.

**Comment by drvarunagarwal** [comment]
I was also thinking on the same lines of using 2 separate computers.

What are the pros and cons of such an approach? Would appreciate a little more clarity on this aspect.

Many thanks

Best Regards,
Dr. Varun Agarwal

**Comment by lassoan** [comment]
You can comfortably send tracking data from one computer to another at a rate of few ten Hz. If the robot controller uses internal sensors for the real-time control loop (that runs at many hundreds Hz) and the optical tracker just provides target pose then the system should work well.

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
