### ISSUE TITLE
ToolTimeStampedUpdate failed using Optical marker tracker with local server setup

### ISSUE THREAD

**Issue by inyeol** [PlusToolkit/PlusLib#757]
Hello

I'm currently trying to carry out spatial calibration using Aruco optical marker tracker, but with little success.
Our setup is as follows : 
 Terason 3200T NexGen sending captured US video frames over network.
 fCal running on a laptop carrying out calibrations.
 PlusServer running on the same laptop sending optical marker tracker transforms from captured webcam video.

I first tried to use opencvvideo device with marker tracking within fCal, but I had to abandon this since temporal calibration does not support virtual devices(why is this?). The optical marker tracker device wasn't available for selection, so no temporal calibration between US frames and trackers.

I then moved onto running Aruco tracking on a separate plus server process on the same laptop. Now temporal calibration itself is available, but fCal started to complain that ToolTimeStampedUpdate failed.

Time spans before error manifestations vary. There were occasions where fCal ran successfully long enough for me to finish a stylus calibration, although most of the time they are too short for me to do anything productive.

I have attached config files for fCal and PlusServer, as well as a output log from a trial.

Any guidance would be much appreciated
Thanks
[010621_154621_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/5774235/010621_154621_PlusLog.txt)
[Server_opticalmarkertracker.txt](https://github.com/PlusToolkit/PlusLib/files/5774245/Server_opticalmarkertracker.txt)
[Client_opticalmarkertracker_20210104.txt](https://github.com/PlusToolkit/PlusLib/files/5774246/Client_opticalmarkertracker_20210104.txt)

**Comment by inyeol** [comment]
When I change to UseReceivedTimestamps = "false" in client config file transforms get updated correctly.
Is this an expected behavior?

**Comment by lassoan** [comment]
> When I change to UseReceivedTimestamps = "false" in client config file transforms get updated correctly.
Is this an expected behavior?

Yes, this is the expected behavior. UseReceivedTimestamps makes Plus server use timestamps in embedded in the input data stream. You must turn off this option if system clocks of the sender and receiver computers are not synchronized.

> I first tried to use opencvvideo device with marker tracking within fCal, but I had to abandon this since temporal calibration does not support virtual devices(why is this?).

I think virtual devices are not supported because the idea is that you calibrate the original physical data sources. But probably the distinction is not always very clear, so maybe this limitation could be removed in fCal (QTemporalCalibrationToolbox::OnActivated()). @Sunderlandkyl what do you think?

**Comment by Sunderlandkyl** [comment]
Makes sense to me, I'll remove the restriction.

**Comment by Sunderlandkyl** [comment]
Virtual requirement removed in https://github.com/PlusToolkit/PlusApp/commit/d6a1a7c8ba2301fd5166167bfd4dc3764048ca35.

**Comment by inyeol** [comment]
@lassoan @Sunderlandkyl
But why would a PlusServer instance and a fCal instance running on a same laptop be out of sync? Also does UseReceievedTimestamps = "false" have negative impact on the quality of results? I don't have a strong understanding of the whole calibration processes yet, wouldn't it at least make temporal calibrations meaningless?. 
I would to love to know if it's fine to continue calibrating using this option.

Lastly, how does an acceptable calibration result using ArUco marker tracking look like?
I'm constantly getting pivot calibration errors of <0.5 mm which seem okay. However the phantom registration errors don't go lower than 2.4mm. 
Is there something I can do to improve the results?

Thank you for your great work and prompt responses

**Comment by adamrankin** [comment]
@lassoan @Sunderlandkyl [!urgent] I would test that change extensively to ensure that temporal calibration works correctly for any devices being passed through a virtual device. I would recommend a whitelist of intended virtual devices rather than a blanket blacklist.

**Comment by lassoan** [comment]
UseReceivedTimestamps makes the measurements independent of network transfer or processing times. If you work on the same computer and you don't use devices that provide hardware timestamp then there is probably no benefit in using received timestamp.

> Lastly, how does an acceptable calibration result using ArUco marker tracking look like?

Single-camera marker tracking is expected to have 10x-50x larger error than when using stereo camera. 2.4mm landmark registration error is very good. The actual absolute error is probably much higher, but if you don't rely on measuring absolute distance from camera and the rotation angle range is limited then you might get as low as a couple of mm error.

**Comment by inyeol** [comment]
Thank you very much for your replies.

I think I can proceed to spatial calibration without worrying too much then. Also pose estimation with a stereo camera sounds very interesting. I will definitely have to try it out.

I think the issue can be closed.

Have a nice one.
Inyeol
