### ISSUE TITLE
Unable to connect PHIDGET MARG sensor to plus server.

### ISSUE THREAD

**Issue by drvarunagarwal** [PlusToolkit/PlusLib#758]
Hello everyone,

I am trying to connect PHIDGET MARG sensor to plus server.

![IMG_1181](https://user-images.githubusercontent.com/76910274/103889675-cca8bd00-510c-11eb-8f47-aa2e197abf14.JPG)

As you may see in the server the phidget sensor is being detected in phidget toolkit. But plus server is not detecting it.

I am using the default config file that comes with the plus server installation without any changes.

[PlusDeviceSet_Server_PhidgetSpatial.txt](https://github.com/PlusToolkit/PlusLib/files/5781427/PlusDeviceSet_Server_PhidgetSpatial.txt)

These are my error logs:

[010721_163307_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/5781410/010721_163307_PlusLog.txt)
[010721_163716_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/5781413/010721_163716_PlusLog.txt)
[010721_163942_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/5781414/010721_163942_PlusLog.txt)

Do I need to change anything in the config file?

Please guide and advise.
Many thanks in anticipation

**Comment by adamrankin** [comment]
I'm not familiar with the phidget devices. Is it USB? Could you try closing the Phidget Control Panel and try to connect again?

**Comment by drvarunagarwal** [comment]
Yes it is USB only.

Can these devices work directly with the default config files or do I need to change some things?

Best Regards,
Dr. Varun Agarwal

**Comment by lassoan** [comment]
Plus can only connect if you disconnect the Phidget Control Panel.

It may also be a 32-bit/64-bit driver and Plus mismatch. Try all combinations (64-bit driver with 32-bit and 64-bit Plus; 32-bit driver with 32-bit and 64-bit Plus).

**Comment by drvarunagarwal** [comment]
Thanks 
Will try asap and get back

Would I need to change anything in the default config file?

Best Regards,
Dr. Varun Agarwal

**Comment by drvarunagarwal** [comment]
I installed plus 64 bit

Still not able to connect. Even after shutting down phidget control panel.

**Comment by lassoan** [comment]
Also make sure the Phidget Network Server is not running.

**Comment by drvarunagarwal** [comment]
Hi,

I tried witmotion 901CL and it connects without problems.

However phidget is still not connecting.

Are there some new files for phidget below:
[https://github.com/PlusToolkit/PlusLib/tree/master/Tools/Phidget/Phidget22](url)

Or can it be because plus manual phidget 1044_0
and I am using 1044_1?

Please advise

thanks

**Comment by lassoan** [comment]
You can try downloading the SDK from Phidget website and compare with files that Plus is built with (https://github.com/PlusToolkit/PlusLib/tree/master/Tools/Phidget/Phidget22). You can then build the PhidgetSpatial example to see if that connects. If that does, then most likely the PhidgetSpatial SDK that Plus is built with is not compatible with your device. To confirm that, you can build Plus on your computer with the new PhidgetSpatial SDK files. We may also consider updating the PhidgetSpatial SDK files in Plus if you confirm that this update is needed to connect to latest version of these devices.

**Comment by drvarunagarwal** [comment]
Let me try and get back

thanks

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
