### ISSUE TITLE
Difficulty building PlusLib Ubuntu 16.04

### ISSUE THREAD

**Issue by mkomaiha** [PlusToolkit/PlusLib#762]
Hi,
I am having a lot of difficulty getting PlusLib built and running. I have read through all of the documentation on how to get it set up and ended up following these steps:

1. Build Qt5
2. Build VTK
3. Build Slicer Superbuild (Linking **ITK**)
4. Build SlicerOpenIGTLink (Linking **OpenIGTLink-build** and **OpenIGTLinkIO-build**)
5. Build IGSIO

I am trying to run PlusLib using StealthLink, so I have:
PLUS_USE_STEALTHLINK = ON
PLUS_USE_OpenIGTLink = ON

When I use the /IGSIO/build/inner-build/ I get this error
```bash
In file included from /usr/local/include/vtk-9.0/vtkPlot.h:33:0,
                 from ~/PlusLib/src/PlusRendering/PlusPlotter.cxx:21:
/usr/local/include/vtk-9.0/vtkDeprecation.h:39:29: error: missing binary operator before token "("
 #if VTK_DEPRECATION_LEVEL < VTK_MINIMUM_DEPRECATION_LEVEL
                             ^
/usr/local/include/vtk-9.0/vtkDeprecation.h:75:47: error: missing binary operator before token "("
 #if VTK_DEPRECATION_LEVEL >= VTK_VERSION_CHECK(9, 1, 0)
                                               ^
/usr/local/include/vtk-9.0/vtkDeprecation.h:82:47: error: missing binary operator before token "("
 #if VTK_DEPRECATION_LEVEL >= VTK_VERSION_CHECK(9, 0, 0)
```

When i use /IGSIO/build I get this error.
```bash
Linking CXX shared library ../../lib/libvtkPlusCommon.so
/usr/bin/ld: cannot find -lvtkAddon
collect2: error: ld returned 1 exit status
```

I am new to cmake and this whole process, so I would really appreciate the help or if someone could guide me through getting the library built step-by-step from scratch.

Thank you in advanced!

**Comment by adamrankin** [comment]
Have you tried using the PlusBuild approach? 

See https://github.com/PlusToolkit/PlusBuild

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
