### ISSUE TITLE
Problem combining two inputs with VirtualMixer

### ISSUE THREAD

**Issue by tggadda** [PlusToolkit/PlusLib#769]
I have two devices that I would like to combine their inputs using PlusServer and then stream them out together to 3D slicer, effectively making a tracked ultrasound.  One of these devices is the Verasonics ultrasound machine, for which I have written a pyigtl based OpenIGTLink output.  The other device is the NDI Aurora tracker.  Individually I can use the PlusServer to take in each device's data and then see the output in 3D Slicer.  But when I try to use VirtualMixer to combine the outputs, I get an error in PlusServer (012821_140357.732|ERROR|005.677000| Failed to get video buffer item UID from time: 3.136000| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(1198)
) and in 3D Slicer the OpenIGTLinkIF Module shows the connector as ON, but no data is coming across.  

I will attach the 3 config files (as txt files because xml files are not allowed?) as well as the log file. 
[Working Aurora config file](https://github.com/PlusToolkit/PlusLib/files/5890261/PlusDevice_Aurora.xml.txt)
[Working Verasonics config file](https://github.com/PlusToolkit/PlusLib/files/5890262/PlusDevice_Verasonics.xml.txt)
[NOT working combined config file](https://github.com/PlusToolkit/PlusLib/files/5890263/PlusDevice_VerasonicsAndAurora.xml.txt)

[PLUS Server Log File](https://github.com/PlusToolkit/PlusLib/files/5890253/012821_140352_PlusLog.txt)

I would appreciate any suggestions or help anyone might be able to offer.

**Comment by adamrankin** [comment]
That should work, so let's try some unusual settings. Can you change UseReceivedTimestamps="false" to true?

**Comment by tggadda** [comment]
Thank you for your response! Unfortunately nothing changed.  PlusServer still shows a million repetitions of 
`|ERROR|379.381000|SERVER> Failed to get video buffer item UID from time: 2.461000| in :\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(1198)` 
and the data is not transmitted to slicer.

**Comment by lassoan** [comment]
Can you send the debug (or even trace) level logs?

**Comment by tggadda** [comment]
This time when I went to gather more detailed logs for you it all worked.  Maybe I had changed UseReceivedTimestamps to true in the wrong config files?  

Thanks for your help.
