### ISSUE TITLE
Plus and NDI polaris 

### ISSUE THREAD

**Issue by nayanw775** [PlusToolkit/PlusLib#771]
Hello Plus team,

We purchased a new NDI polaris camera to for navigation and i am trying to connect NDI and Plus toolkit and when i launch plusapp with the default config file it always say connection failure i also tried by changing the path for the rom files and also tried by putting a config and rom files in the same folder, its still not working i am attaching the config file and the error.
![image](https://user-images.githubusercontent.com/72604275/106354368-5831fa00-6317-11eb-87a3-b92429bafdab.png)

**Comment by nayanw775** [comment]
>

**Comment by adamrankin** [comment]
Can you upload the config file you're using to connect? Have you tested the ROM file with the NDI Track software to confirm it works?

**Comment by nayanw775** [comment]
Thank you for the quick response Yes I checked it in NDI track it is tracking with the tool definition files(ROM) files that I loaded.
I am attaching the screeshot of the config file since I am unable to upload it.

![image](https://user-images.githubusercontent.com/72604275/106436012-98b98100-6499-11eb-8944-39da17003d77.png)
![image](https://user-images.githubusercontent.com/72604275/106436485-25fcd580-649a-11eb-8315-6eb9d4f9fd54.png)

**Comment by adamrankin** [comment]
Hmm. And is it always the same error on every run? (it's very uncommon to see the "Failed to enable tool ports" error message)
