### ISSUE TITLE
Failed to get video buffer item by timestamp

### ISSUE THREAD

**Issue by arciasan** [PlusToolkit/PlusLib#788]
Hi,
[PlusServerLauncherError.zip](https://github.com/PlusToolkit/PlusLib/files/6003974/PlusServerLauncherError.zip)

I am trying to connect the NDI Polaris Vega optical tracking with US images acquired with a BK system. I am using PLUS toolkit and 3Dslicer.  Everything seems to work fine in PlusServerLauncher when I connect the US system and the polaris vega, however, as soon as I start 3Slicer I get an error in PlusServerLauncher ("Failed to get video buffer item by timestamp") and after a while it closes. However, 3Dslicer continues working even though PlusServerLauncher is closed.

I attached the configuration file I am using in PlusServerLauncher  and the log file. 

Any help would be welcome.

Thanks in advance,
Alba

**Comment by adamrankin** [comment]
Could you try the same setup but disable one of the devices at a time to identify which one is causing the problem?

**Comment by lassoan** [comment]
Would need more information from the user to investigate.
