### ISSUE TITLE
Volume reconstructed by PlusRemote is shifted

### ISSUE THREAD

**Issue by lassoan** [PlusToolkit/PlusLib#79]
As previously reported by others, too, volumes reconstructed using PlusRemote appear shifted in Slicer. If the volume is loaded from file then position is correct, the position is only corrupted when the volume is sent over Openigtlink.

**Comment by lassoan** [comment]
@Sunderlandkyl Can you confirm that volume reconstruction works well now (live 2D frames, scout scan, live 3D reconstruction are all well aligned)?

**Comment by Sunderlandkyl** [comment]
I've tested it on the fCal phantom scan replay, and it looks good to me.

**Comment by lassoan** [comment]
@Sunderlandkyl thanks for testing. Closing this issue then.
