### ISSUE TITLE
Connection Issues - Plus ToolKit Server and NDI Polaris Vega XT

### ISSUE THREAD

**Issue by blake-herrema** [PlusToolkit/PlusLib#795]
Hi,

I've been reading through the issues posted already and have been having similar issues. Unfortunately, none of the suggestions from those threads have worked for me. Here is the procedure I followed in an attempt to connect the Plus ToolKit Server to our NDI Polaris Vega XT. Note that the device connects to NDI Track and works as intended, and no NDI software is running when I attempt to connect via Plus ToolKit. Also, the device is connected via ethernet - a cable is running directly from the computer to the PoE adapter. 

I uninstalled Plus ToolKit and performed a clean install. Following this, I opened the server and attempted to connect after selecting the NDI Polaris Tracker config file. This did not work and provided the error shown in "Error.txt". I then tried to modify the config file by adding "NetworkHostname" and "NetworkPort" lines as discussed on other threads. I tried three different names and ports, as follows: 
- "Second Error.txt." gives the error provided when I used the address and port shown in "Connections.png"
- "Third Error.txt." gives the error provided when I used the device's Bonjour name and port shown in "Network.png"
- "Fourth Error.txt" gives the error provided when I used the address and port shown in "Static IP.png" - Note that this IP address is also the address that shows up next to the device's Bonjour name when I mouse over "File" -> "Connect To" in NDI Track. 

Lastly, I attached my current config file, which contains the information used in the fourth attempt stated above. It strikes me as strange that I am receiving an error that mentions serial ports since the computer I'm using doesn't even have a serial port and the config file, seemingly, has no mention of a com port. Hopefully someone can make more sense of this than I can.

Thanks,
Blake

![Connections](https://user-images.githubusercontent.com/71461831/110041881-12939300-7d02-11eb-87f4-4c2d745990bc.PNG)
![Network](https://user-images.githubusercontent.com/71461831/110041893-17584700-7d02-11eb-9770-df3d7ccdc0ee.PNG)
![Static IP](https://user-images.githubusercontent.com/71461831/110041900-19baa100-7d02-11eb-9dfa-6efd46946be1.PNG)

[Error.txt](https://github.com/PlusToolkit/PlusLib/files/6087081/Error.txt)
[Second Error.txt](https://github.com/PlusToolkit/PlusLib/files/6087082/Second.Error.txt)
[Third Error.txt](https://github.com/PlusToolkit/PlusLib/files/6087083/Third.Error.txt)
[Fourth Error.txt](https://github.com/PlusToolkit/PlusLib/files/6087084/Fourth.Error.txt)

[Current Config.txt](https://github.com/PlusToolkit/PlusLib/files/6087090/Current.Config.txt)

**Comment by itSeez** [comment]
I was having a similar error to your second error. What worked for me was to replace the IP address in NetworkHostname for the device's serial number, P9-06602 in your case. I also removed the NetworkPort, and let plus use the default.
Hope this helps.

**Comment by adamrankin** [comment]
I've just tested with our Vega, and everything worked as expected. I can confirm that we've had intermittent behaviour when connecting. The solution is a very frustrating reboot and try again.

My config file specified the Bonjour name of the device in Hostname, and 8765 for the Port. Vega had default configuration (dhcp address, ended up with 169.x.y.z address)

**Comment by lassoan** [comment]
No feedback from the user, assuming the problem has been resolved.
