### ISSUE TITLE
Creating MHA sequences from scratch

### ISSUE THREAD

**Issue by prash-p** [PlusToolkit/PlusLib#804]
Hello,

Our team are trying to create MHA sequences from scratch given a set of ultrasound images and timestamped transformations. We are trying to do this in Matlab using these utility functions: https://github.com/PlusToolkit/PlusMatlabUtils

We are trying to read an existing .mha file (the Elbow sweep provided by PLUS), and overwrite the image and transform data into a new .mha file with an image that has different dimensions than the one in the original .mha file.

However this method doesn't work as I guess the .mha MATLAB utility functions were not designed for this purpose. Is there a better way to do this where we have images and transformations, and want to create a file which could then be input into the PLUS volume reconstruction tool?

Thanks!

**Comment by lassoan** [comment]
Since all you need is to write out the transform into a text file, you can implement that in any language you are comfortable with. 

It is probably simpler if you use mhd+raw format instead of mha, because then you don't need to mix text with binary data in a single file.

**Comment by prash-p** [comment]
@lassoan I see. Is there a .mhd format guidelines as to what information should be included? And a guide for saving in raw format?

**Comment by lassoan** [comment]
The simplest is to save as .mhd using Plus to see an example. You can convert mha to mhd+raw using EditSequenceFile tool.

**Comment by adamrankin** [comment]
There are some examples here:
https://github.com/PlusToolkit/PlusLibData/tree/master/TestImages

**Comment by prash-p** [comment]
Thanks!

**Comment by lassoan** [comment]
By the way, we mostly moved to nrrd file format (and nhdr+raw) because metafile does not have a standard way of specifying if a 3D volume is 2D+t sequence or a single 3D volume. So, if you implement file writing then you may be better off using nhdr+raw file format.

**Comment by prash-p** [comment]
Okay, thanks - we will try nhdr+raw.
