### ISSUE TITLE
EditSequenceFile.exe overwrites ElementSpacing

### ISSUE THREAD

**Issue by nathanbmnt** [PlusToolkit/PlusLib#829]
If EditSequenceFile.exe compression/uncompression is run on an mhd, the ElementSpacing header is reset to 1 1 1.
On the left is the uncompressed file, on the right is after compression:
![image](https://user-images.githubusercontent.com/40271210/123976431-2091b180-d98c-11eb-8563-143d6db873a2.png)

**Comment by adamrankin** [comment]
Confirmed, investigating.

**Comment by lassoan** [comment]
Element spacing is only included in the file header for compatibility, but in sequence metafiles this tag is generally ignored, because it may change in time (e.g., when the imaging depth is changed during the acquisition). Instead, `Seq_FrameNNNN_ElementSpacing` frame field should be used.

**Comment by nathanbmnt** [comment]
OK I've gotten around this issue by using `--operation=UPDATE_FIELD_VALUE --field-name=ElementSpacing --updated-field-value=0.1 0.0386 0.1`
