### ISSUE TITLE
Failed Build of PlusBuild when using StealthLink

### ISSUE THREAD

**Issue by purav70** [PlusToolkit/PlusLib#83]
Hello,

I'm trying to build Plus to communicate with StealthLink (I'm using VS2010 on an 64 bit Windows 10 machine). Without Stealthlink, Plus is able to build fully, with no failed builds or errors. However, upon including the Stealthlink flag, the build fails (specifically PlusLib and PlusApp) and build errors such as the following come up. 

I've tried using only static libraries given the boost libraries asked for in the final error message posted below are static, but to no avail, as well as ensuring the library directories and libraries themselves are linked to. 

I'm unsure how to proceed at this point and would appreciate any help.

Thanks,

Purav

`12>msvcprt.lib(MSVCP100.dll) : error LNK2005: "public: virtual __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::~basic_streambuf<char,struct std::char_traits<char> >(void)" (??1?$basic_streambuf@DU?$char_traits@D@std@@@std@@UEAA@XZ) already defined in StealthLink_static.lib(SubscriptionUpdateHandler.obj) [C:\D\PlusB-bin\PlusApp-bin\DiagnosticTools\DiagDataCollection.vcxproj]`
`12>msvcprt.lib(MSVCP100.dll) : error LNK2005: "public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::flush(void)" (?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV12@XZ) already defined in StealthLink_static.lib(SubscriptionUpdateHandler.obj) [C:\D\PlusB-bin\PlusApp-bin\DiagnosticTools\DiagDataCollection.vcxproj]`
`12>msvcprt.lib(MSVCP100.dll) : error LNK2005: "public: void __cdecl std::basic_ostream<char,struct std::char_traits<char> >::_Osfx(void)" (?_Osfx@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAXXZ) already defined in StealthLink_static.lib(SubscriptionUpdateHandler.obj) [C:\D\PlusB-bin\PlusApp-bin\DiagnosticTools\DiagDataCollection.vcxproj]`
`12>msvcprt.lib(MSVCP100.dll) : error LNK2005: "public: void __cdecl std::basic_ios<char,struct std::char_traits<char> >::setstate(int,bool)" (?setstate@?$basic_ios@DU?$char_traits@D@std@@@std@@QEAAXH_N@Z) already defined in StealthLink_static.lib(SubscriptionUpdateHandler.obj) [C:\D\PlusB-bin\PlusApp-bin\DiagnosticTools\DiagDataCollection.vcxproj]`
`12>msvcprt.lib(MSVCP100.dll) : error LNK2005: "public: __int64 __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sputn(char const *,__int64)" (?sputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAA_JPEBD_J@Z) already defined in StealthLink_static.lib(SubscriptionUpdateHandler.obj) [C:\D\PlusB-bin\PlusApp-bin\DiagnosticTools\DiagDataCollection.vcxproj]`
`12>msvcprt.lib(MSVCP100.dll) : error LNK2005: "public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sputc(char)" (?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHD@Z) already defined in StealthLink_static.lib(SubscriptionUpdateHandler.obj) [C:\D\PlusB-bin\PlusApp-bin\DiagnosticTools\DiagDataCollection.vcxproj]`
`12>LINK : fatal error LNK1104: cannot open file 'libboost_system-vc100-mt-s-1_46_1.lib' [C:\D\PlusB-bin\PlusApp-bin\DiagnosticTools\DiagDataCollection.vcxproj]`

**Comment by adamrankin** [comment]
Give me a few minutes to install VS2010 and get a build setup.

**Comment by purav70** [comment]
Much appreciated

**Comment by adamrankin** [comment]
My build completed successfully using StealthLink 2.0.1.

The other thing that's strange is that Plus doesn't use boost.

**Comment by adamrankin** [comment]
What other devices do you have enabled?

**Comment by purav70** [comment]
Stealthlink is the only device that I've enabled. The boost libraries are in the StealthLink directory, I'm not sure if they were there initially, or if Plus built them. Also I'm using StealthLink 2.0.0.

**Comment by adamrankin** [comment]
Hmm, interesting. Our StealthLink's differ then, because mine is just a .lib, .dll and .h files. Do you have access to 2.0.1?

**Comment by purav70** [comment]
This is odd, the StealthLink DVD says version 2.0.1, however in the release notes in one of the folders within, it specifies version 2.0.0. Regardless, I checked the DVD itself and in the windows/x64/release, it contains 3 libboost libs (libboost_date_time-vc100-mt-s-1_46_1.lib, libboost_regex-vc100-mt-s-1_46_1.lib, libboost_system-vc100-mt-s-1_46_1.lib) along with the .dll and .lib files.

**Comment by adamrankin** [comment]
I admit I'm not sure where to go from here.

Let me check the StealthLink find script, and see if it's just grabs all .libs in the folder.

**Comment by adamrankin** [comment]
No, not that. Is your StealthLink only .lib files? If not, can you use DependencyWalker on the StealthLink.dll to see if the boost libraries are a dependency?

**Comment by purav70** [comment]
The Stealthlink DVD contains different folders, 2 of which are relevant. One contains all header files and the other contains .lib and .dll files (include the boost libs). I'll give DependencyWalker a go, and I'll report back what I find. Would it be possible for you to check the release notes on your version of StealthLink to see if it says 2.0.0? That way we can assume someone forgot to change the release file and can isolate the problem to the libraries.

**Comment by adamrankin** [comment]
Ours doesn't have any release files, just the .lib, .dll and .h files.

**Comment by purav70** [comment]
I ran Dependency Walker but didn't find the boost libraries to be a dependency. I do get an unnerving number of errors however:
![image](https://user-images.githubusercontent.com/25391951/30712586-808bf44c-9eda-11e7-8ff3-b04a2f9b0aa8.png)

It's interesting that your copy has different contents. It may be worth calling Medtronic to see if they have an answer. Also, I'm using qt5.5, I'm not sure if that could be contributing to these errors.

**Comment by lassoan** [comment]
The errors that you see are normal. Dependency walker was developed before side-by-side assemblies existed and while the tool may be used to find some leads, you cannot fully rely on it.

Here are the MD5 sums for our files:
12cfa689a08928144d9222e77c04b827 *Debug\StealthLink.dll
45cc9a3df1f0fb498b26e1eedb340f5c *Debug\StealthLink.lib
11d34d0e3dd2f1e61044e8945a678c53 *Debug\StealthLink.pdb
5c73a1e041b05a54e9b74f07d1fa59d8 *Release\StealthLink.dll
5b752c07cbad0e14ca3f8eb96184e29e *Release\StealthLink.lib

Your errors seem to be due to using different versions of MSVC runtime libraries, not related to boost. We have those boost libs as well, but we figured we don't need them.

We haven't tested building StealthLink with static libraries, so there might be some problem there (for example, you may need to link StealthLink_static.lib instead of StealthLink.lib). Try to build Plus with default options - with shared libraries.

**Comment by purav70** [comment]
The MD5 hashes for my files do not match the ones you put up. I believe I'm using only the /MD runtime library for the builds (I'm assuming that's the one you used as well). 

When you say linking StealthLink_static.lib instead of StealthLink.lib, do you mean in cmake, for the flags that ask for the static/shared library? (As in, should I be linking shared libraries for both flags, or static libraries for both flags?)

**Comment by purav70** [comment]
I rechecked the MD5 hashes and they match my 32 bit hashes. Did you build on a 32 bit system?

**Comment by lassoan** [comment]
Closing this now. We successfully build Plus with StealthLink on multiple computers (64-bit systems, 32-bit builds). Please reopen if you have further questions related to this topic.
