### ISSUE TITLE
Connect Plus to Polaris Vicra

### ISSUE THREAD

**Issue by Matteo-0** [PlusToolkit/PlusLib#831]
Hello,
I am trying to connect the Polaris Vicra to 3D slicer to be able to read the position of the tip of an instrument, but every time I try to connect the Polaris Vicra with Plus I got the following errors: 

|WARNING|2784.624000|SERVER> vtkPlusChannel::GetTrackedFrameListSampled: Frames in the buffer are not available any more at time: 0.672000. Skipping 0.113000 seconds from the recording to catch up. Increase the buffer size or decrease the acquisition rate to avoid this situation.| in :\D\PSNPb\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(1089)

|ERROR|2784.825000|SERVER> Unable to retrieve number of scalar components.| in :\D\PSNPb\PlusLib\src\PlusCommon\IO\vtkPlusNrrdSequenceIO.cxx(585)

|ERROR|2784.841000|SERVER> Unable to prepare header| in :\D\PSNPb\PlusLib\src\PlusDataCollection\VirtualDevices\vtkPlusVirtualCapture.cxx(614)

Hope anybody can help!

**Comment by Matteo-0** [comment]
My config file: 
<PlusConfiguration version="2.1">

  <DataCollection StartupDelaySec="1.0" >
    <DeviceSet 
      Name="PlusServer: NDI Polaris tracker with passive markers" 
      Description="Broadcasting tool tracking data through OpenIGTLink
For NDI Polaris passive marker starting kit: Reference (8700339), Stylus (8700340)" />
    <Device
      Id="TrackerDevice"
      Type="PolarisTracker"
      ToolReferenceFrame="Tracker" >
      <DataSources>
        <DataSource Type="Tool" Id="Reference" RomFile="NdiToolDefinitions/8700339.rom"  />
        <DataSource Type="Tool" Id="Stylus" RomFile="NdiToolDefinitions/8700340.rom"  />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream" >
		  <DataSource Id="Reference"/>
          <DataSource Id="Stylus"/>
        </OutputChannel>
      </OutputChannels>
    </Device>
    <Device
      Id="CaptureDevice"
      Type="VirtualCapture"
      BaseFilename="RecordingTest.igs.nrrd"
      EnableFileCompression="TRUE"
      EnableCapturingOnStart="TRUE" >
      <InputChannels>
        <InputChannel Id="TrackerStream" />
      </InputChannels>
    </Device>    
  </DataCollection>

  <CoordinateDefinitions>
    <Transform From="StylusTip" To="Stylus"
      Matrix="
        1	0	0.000203823	0.0180449
        3.31529e-09	-1	-1.62655e-05	-0.00144002
        0.000203823	1.62655e-05	-1	-88.5321
        0	0	0	1"
       Error="0.554951" Date="012617_105449" />
  </CoordinateDefinitions>

  <PlusOpenIGTLinkServer 
    MaxNumberOfIgtlMessagesToSend="1"
    MaxTimeSpentWithProcessingMs="50"
    ListeningPort="18944"
    SendValidTransformsOnly="true"
    OutputChannelId="TrackerStream" >
    <DefaultClientInfo>
      <MessageTypes>
        <Message Type="TRANSFORM" />
      </MessageTypes>
      <TransformNames>
        <Transform Name="StylusToReference" />
      </TransformNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>

</PlusConfiguration>

**Comment by lassoan** [comment]
The question was also posted on discourse: https://discourse.slicer.org/t/connect-plus-to-the-polaris-vicra/18461

Closing the issue here to avoid parallel discussions.
