### ISSUE TITLE
Use PlusLib with OpenVR/SteamVR

### ISSUE THREAD

**Issue by waterfall414** [PlusToolkit/PlusLib#832]
Recently we have been playing with a HTC tracker and wanted to connect it with PLUS via SteamVR in the backend. To build the library with the SteamVR, I tried to build and compile in PlusBuild with the following argument in CMake

```
DPLUS_USE_STEAMVR:BOOL=ON 
```

on a Windows 10 x64 Platform with Visual Studio 2017, which complains about missing OpenVR directories:

```
Could NOT find OpenVR (missing: OPENVR_INCLUDE_DIR OPENVR_LIBRARY)
```

I wonder what are the correct steps to build PLUS with StreamVR supports. Do I also need to manually set those in the PlusBuild cmake process?

Additionally I cloned and built OpenVR in this [repo](https://github.com/ValveSoftware/openvr) with version 1.14.15.

Thanks!

**Comment by adamrankin** [comment]
I've improved the passing of variable from PlusBuild to PlusLib, so in future builds it should Just Work™. For now, set the OPENVR_ROOT_DIR in PlusLib to be the root folder of the downloaded SDK.

**Comment by waterfall414** [comment]
@adamrankin Thanks for the reply, but I am not able to follow and solve my issue.

After I cloned and built the OpenVR SDK [repo](https://github.com/ValveSoftware/openvr) 1.14.15, it has the following folder structure
```
OpenVR_root
- bin
- controller_callouts
- headers
- lib
- samples
- src
- CMakeLists.txt
- LICENSE
- README.md
- Toolchain-clang.camke
```
where bin contains the built dll/lib for different platforms (for example, I am using win64)

Currently I am using PlusLib commit 31c00cceddba525e9916db87d268eac122730608, which is checked out around March 2020. When I CMake, the following warning came up:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    OPENVR_ROOT_DIR
```

When I built PlusBuild, same error persisted:
```
Could NOT find OpenVR (missing: OPENVR_INCLUDE_DIR OPENVR_LIBRARY)
```

**Comment by adamrankin** [comment]
Hmm, in PlusBuild/Modules/FindOpenVR.cmake, does the code look for some sort of root variable?

**Comment by waterfall414** [comment]
@adamrankin good question... since I am not that good at CMake, I cannot answer this question confidently. Here is the FindOpenVR.cmake in my PlusBuild. I guess it may look for other variables.

<details>
 <summary>FindOpenVR.cmake</summary>

    set(OPENVR_ROOT_DIR
      "${OPENVR_ROOT_DIR}"
      CACHE
      PATH
      "Directory to search for OpenVR SDK")
    
    set(OPENVR_HEADERS_ROOT_DIR
      "${OPENVR_HEADERS_ROOT_DIR}"
      CACHE
      PATH
      "Directory to search for private OpenVR headers")
    
    set(_root_dirs)
    if(OPENVR_ROOT_DIR)
      set(_root_dirs "${OPENVR_ROOT_DIR}" "${OPENVR_HEADERS_ROOT_DIR}" "${OPENVR_ROOT_DIR}/public")
    endif()
    
    # todo fails for universal builds
    set(_dll_suffix)
    if(${CMAKE_SIZEOF_VOID_P} EQUAL 8)
      set(_bitness 64)
      if(WIN32)
        set(_dll_suffix _x64)
      endif()
    else()
      set(_bitness 32)
    endif()
    
    # Test platform
    
    set(_platform)
    if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
      set(_platform_base osx)
      # SteamVR only supports 32-bit on OS X
      set(OPENVR_PLATFORM osx32)
    else()
      if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
        set(_platform_base linux)
        # TODO Massive hack!
        add_definitions(-DGNUC -DPOSIX -DCOMPILER_GCC -D_LINUX -DLINUX -DPOSIX -D_POSIX)
      elseif(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
        set(_platform_base win)
      endif()
      set(OPENVR_PLATFORM ${_platform_base}${_bitness})
      set(_libpath lib/${OPENVR_PLATFORM})
    endif()
    
    find_path(OPENVR_INCLUDE_DIR
      NAMES
        openvr_driver.h
      HINTS
        "${_libdir}"
        "${_libdir}/.."
        "${_libdir}/../.."
      PATHS
        ${_root_dirs}
        ${OpenVR_DIR}
      PATH_SUFFIXES
        headers
        public/headers
        steam
        public/steam)
    
    FIND_LIBRARY(OPENVR_LIBRARY_TEMP
      NAMES openvr_api
      HINTS
      PATH_SUFFIXES ${_libpath}
      PATHS 
        ${OPENVR_ROOT_DIR}
        ${OpenVR_DIR}
    )
    
    if(OPENVR_LIBRARY_TEMP)
      # Set the final string here so the GUI reflects the final state.
      set(OPENVR_LIBRARY ${OPENVR_LIBRARY_TEMP} CACHE STRING "Where the openvr Library can be found")
      # Set the temp variable to INTERNAL so it is not seen in the CMake GUI
      set(OPENVR_LIBRARY_TEMP "${OPENVR_LIBRARY_TEMP}" CACHE INTERNAL "")
    endif()
    
    include(FindPackageHandleStandardArgs)
    find_package_handle_standard_args(OpenVR
      DEFAULT_MSG
      OPENVR_INCLUDE_DIR OPENVR_LIBRARY)
    
    if(OPENVR_FOUND)
      if(OPENVR_ROOT_DIR STREQUAL "")
        get_filename_component(_root_dir ${OPENVR_INCLUDE_DIR} DIRECTORY)
        set(OPENVR_ROOT_DIR ${_root_dir} CACHE PATH "Directory to search for OpenVR SDK" FORCE)
      endif()
    
      list(APPEND OPENVR_INCLUDE_DIRS ${OPENVR_INCLUDE_DIR})
      mark_as_advanced(OPENVR_ROOT_DIR OPENVR_HEADERS_ROOT_DIR)
    
      add_library(OpenVR SHARED IMPORTED)
      set_target_properties(OpenVR 
        PROPERTIES
          IMPORTED_IMPLIB ${OPENVR_LIBRARY}
          IMPORTED_LOCATION ${OPENVR_ROOT_DIR}/bin/${OPENVR_PLATFORM}/openvr_api${CMAKE_SHARED_LIBRARY_SUFFIX}
          IMPORTED_LOCATION_RELEASE ${OPENVR_ROOT_DIR}/bin/${OPENVR_PLATFORM}/openvr_api${CMAKE_SHARED_LIBRARY_SUFFIX}
          INTERFACE_INCLUDE_DIRECTORIES ${OPENVR_INCLUDE_DIRS}
      )
      if(MSVC)
      set_target_properties(OpenVR
        PROPERTIES
          PDB_NAME ${OPENVR_ROOT_DIR}/bin/${OPENVR_PLATFORM}/openvr_api.pdb
        )
      endif()
    endif()
    
    mark_as_advanced(OPENVR_INCLUDE_DIR)

</details>

**Comment by adamrankin** [comment]
Hmm, it should be looking for that `OPENVR_ROOT_DIR` variable... The other option is to set the `OPENVR_INCLUDE_DIR` to the full path of `<path to sdk>/headers` and `OPENVR_LIBRARY` to `<path to sdk>/lib/win64/openvr_api.lib`

**Comment by waterfall414** [comment]
Can I pass OPENVR_INCLUDE_DIR and OPENVR_LIBRARY from PlusBuild to PlusLib when PlusLib is being built?

**Comment by adamrankin** [comment]
You won't need to, as I've fixed PlusBuild to correctly pass the needed variables to PlusLib

https://github.com/PlusToolkit/PlusBuild/commit/79507f55a2892d5fe404a2de15fe93cb4dbcf21f

**Comment by waterfall414** [comment]
Thanks @adamrankin ! After spending some time in updating the libraries to the lastest commits on the Win64 platform, now it is able to populate those variables.
