### ISSUE TITLE
about the old  NDI polaris sensor connect fail problem with plusapp

### ISSUE THREAD

**Issue by solberghu** [PlusToolkit/PlusLib#844]
Hi.
The model of my old polaris camera is "Polaris Hybrid Position Sensor". It only connected with the com port. I can connect the camera through the NDI ToolViewer. It has a com port and is connected with the pc through com-usb adapter. The pc recognize it. But still cannot connect with plus. I create and choose “ndi polaris tracker with passive markers” as configuration xml file. and I tried to type “Serial Port = the com port number i have” but still no connection. Do you have ideas especially for this kind of Polaris camera connection?
In the attach file is my configuration xml.
![configure](https://user-images.githubusercontent.com/84711523/133402499-24ab7b00-0a48-429f-8ec6-96608135291e.png)

regards,

**Comment by adamrankin** [comment]
Is the system correctly detected with NDI Track?

**Comment by solberghu** [comment]
Yes, It's detected correctly with NDI toolviewer. You can refer the image. 
![未命名](https://user-images.githubusercontent.com/84711523/133535085-c2ec98ee-bbc9-4122-a719-36266442ada8.png)

**Comment by solberghu** [comment]
I own both the NDI P4 and P7 position cameras. There is no problem driving the NDI P7 on the plusapp system, as you can see from the pictures below. Do I need to make any adjustments to the xml file to drive the old NDI P4 camera? Because it only has an RS232/RS485 connection port.
![未命名](https://user-images.githubusercontent.com/84711523/133535637-c0b7c61f-ef88-4e5c-8a47-9a98525adea5.png)

**Comment by solberghu** [comment]
> Is the system correctly detected with NDI Track?

Yes, It's detected correctly with NDI toolviewer. You can refer the image. I own both the NDI P4 and P7 position cameras. There is no problem driving the NDI P7 on the plusapp system, as you can see from the pictures below. Do I need to make any adjustments to the xml file to drive the old NDI P4 camera? Because it only has an RS232/RS485 connection port.

**Comment by solberghu** [comment]
> Is the system correctly detected with NDI Track?

Can you offer any solutions?

**Comment by adamrankin** [comment]
If the system works with NDI Track, then it should work with Plus. Can you upload the Plus log?

**Comment by solberghu** [comment]
[092321_181135_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/7216725/092321_181135_PlusLog.txt)
You can to refer the plus log txt file.

**Comment by solberghu** [comment]
Hi, I use the PlusApp-2.3.0.4272-Win32 version. The old NDI sensor is connected successful. Does the version is working with silcer 4.1?

**Comment by adamrankin** [comment]
The interface hasn't changed, but the software around it has. What did the log say for the latest versions?

**Comment by solberghu** [comment]
time|level|timeoffset|message|location
092321_181135.986|INFO|000.000000| System start timestamp: 3754| in E:\D\PSNP64b\PlusLib\src\PlusCommon\vtkPlusAccurateTimer.cxx(51)
092321_181135.989|INFO|000.002000| Software version: Plus-2.8.0.62873a16 - Win64| in vtkPlusLogger(188)
092321_181135.989|INFO|000.002000| Logging at level 3 (INFO) to file: C:/Users/solberg/PlusApp-2.8.0.20191105-Win64/data/092321_181135_PlusLog.txt| in E:\D\PSNP64b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(81)
092321_181136.009|INFO|000.022000| Server status: Reading configuration.| in E:\D\PSNP64b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(92)
092321_181136.009|INFO|000.022000| Server status: Connecting to devices.| in E:\D\PSNP64b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(103)
092321_181136.079|ERROR|000.093000| Failed to detect device on serial port COM2 (index 1). Error opening serial connection| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\NDICAPITracking\vtkPlusNDITracker.cxx(332)
092321_181136.081|ERROR|000.094000| Unable to connect to NDI device.| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\NDICAPITracking\vtkPlusNDITracker.cxx(311)
092321_181136.081|ERROR|000.094000| TrackerDevice: Cannot connect to data source, ConnectInternal failed| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDevice.cxx(1147)
092321_181136.082|ERROR|000.095000| Unable to connect device: TrackerDevice.| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDataCollector.cxx(353)
092321_181136.085|ERROR|000.098000| Datacollector failed to connect to devices| in E:\D\PSNP64b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(106)

**Comment by adamrankin** [comment]
Remove the serialport="" line in the config

**Comment by solberghu** [comment]
ok, I remove the serialport="", but it happen error.

time|level|timeoffset|message|location
092821_115125.298|INFO|000.000000| System start timestamp: 9058| in E:\D\PSNP64b\PlusLib\src\PlusCommon\vtkPlusAccurateTimer.cxx(51)
092821_115125.300|INFO|000.002000| Software version: Plus-2.8.0.62873a16 - Win64| in vtkPlusLogger(188)
092821_115125.300|INFO|000.002000| Logging at level 3 (INFO) to file: C:/Users/solberg/PlusApp-2.8.0.20191105-Win64/data/092821_115125_PlusLog.txt| in E:\D\PSNP64b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(81)
092821_115125.305|INFO|000.007000| Server status: Reading configuration.| in E:\D\PSNP64b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(92)
092821_115125.313|INFO|000.015000| Server status: Connecting to devices.| in E:\D\PSNP64b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(103)
092821_115132.948|ERROR|007.650000| Failed to detect device. Port scanning failed. Error opening serial connection| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\NDICAPITracking\vtkPlusNDITracker.cxx(332)
092821_115132.948|ERROR|007.650000| Unable to connect to NDI device.| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\NDICAPITracking\vtkPlusNDITracker.cxx(311)
092821_115132.948|ERROR|007.650000| TrackerDevice: Cannot connect to data source, ConnectInternal failed| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDevice.cxx(1147)
092821_115132.949|ERROR|007.651000| Unable to connect device: TrackerDevice.| in E:\D\PSNP64b\PlusLib\src\PlusDataCollection\vtkPlusDataCollector.cxx(353)
092821_115132.950|ERROR|007.652000| Datacollector failed to connect to devices| in E:\D\PSNP64b\PlusLib\src\PlusServer\Tools\PlusServer.cxx(106)

**Comment by solberghu** [comment]
My config xml file.

<PlusConfiguration version="2.1">

  <DataCollection StartupDelaySec="1.0" >
    <DeviceSet 
      Name="PlusServer: NDI Polaris tracker with passive markers" 
      Description="Broadcasting tool tracking data through OpenIGTLink
For NDI Polaris passive marker starting kit: Tool (8700339), Stylus (8700340), Reference (8700449)" />
    <Device
      Id="TrackerDevice"
      Type="PolarisTracker"
      ToolReferenceFrame="Tracker" >
      <DataSources>
        <DataSource Type="Tool" Id="Tool" RomFile="NdiToolDefinitions/8700339.rom"  />
        <DataSource Type="Tool" Id="Stylus" RomFile="NdiToolDefinitions/8700340.rom"  />
        <DataSource Type="Tool" Id="Reference" RomFile="NdiToolDefinitions/8700449.rom"  />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream" >
          <DataSource Id="Tool"/>
          <DataSource Id="Stylus"/>
          <DataSource Id="Reference"/>
        </OutputChannel>
      </OutputChannels>
    </Device>
    <Device
      Id="CaptureDevice"
      Type="VirtualCapture"
      BaseFilename="RecordingTest.igs.nrrd"
      EnableFileCompression="TRUE"
      EnableCapturingOnStart="TRUE" >
      <InputChannels>
        <InputChannel Id="TrackerStream" />
      </InputChannels>
    </Device>    
  </DataCollection>

  <CoordinateDefinitions>
    <Transform From="StylusTip" To="Stylus"
      Matrix="
        1	0	0.000203823	0.0180449
        3.31529e-09	-1	-1.62655e-05	-0.00144002
        0.000203823	1.62655e-05	-1	-88.5321
        0	0	0	1"
       Error="0.554951" Date="012617_105449" />
  </CoordinateDefinitions>

  <PlusOpenIGTLinkServer 
    MaxNumberOfIgtlMessagesToSend="1"
    MaxTimeSpentWithProcessingMs="50"
    ListeningPort="18944"
    SendValidTransformsOnly="true"
    OutputChannelId="TrackerStream" >
    <DefaultClientInfo>
      <MessageTypes>
        <Message Type="TRANSFORM" />
      </MessageTypes>
      <TransformNames>
        <Transform Name="StylusTipToReference" />
        <Transform Name="ToolToReference" />
        <Transform Name="ToolToTracker" />
        <Transform Name="StylusToTracker" />
        <Transform Name="ReferenceToTracker" />
      </TransformNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>

</PlusConfiguration>

**Comment by adamrankin** [comment]
Can you show me a screenshot of NDI Track with the device?

**Comment by adamrankin** [comment]
Hmm, I wonder if this is a port numbering issue. Are you able to try renumbering it in Windows to Port 1-4?
