### ISSUE TITLE
Missing dlls in CPack generated package

### ISSUE THREAD

**Issue by kenavolic** [PlusToolkit/PlusLib#893]
- OS: Windows 10
- PlusBuild branch: **master** (_latest_)
- CMake version:3.22.0
  -  Option: `PLUS_USE_TELEMED_VIDEO=ON` `PLUS_USE_OPTICAL_MARKER_TRACKER=ON` `PLUS_USE_OpenCV_VIDEO=ON` `PLUS_USE_MMF_VIDEO=ON`
  - All dependencies built via cmake Superbuild with default versions and args
- Compiling toolchain: Visual Studio 2017 **x86** (Win32)

When trying to deploy an artifact built with `PlusApp-bin/CreatePackage.bat`, 3 dlls are missing:
- `itkhdf5-shared-5.2.dll` (needed by fcal)
- `itkhdf5_cpp-shared-5.2.dll` (needed by fcal)
- `Qt5Test.dll` (needed by aruco)

The aruco issue seems to occur with the latest package `PlusApp-2.9.0.20220121-Telemed-Win32.exe` also while it does not occur with the last stable release package `PlusApp-2.8.0.20191105-Telemed-Win32.exe`.

The ITK issue is due to the CPack config installing only the `RuntimeLibraries` component (see [ITK forum thread](https://discourse.itk.org/t/install-hdf5-component-naming/4762)).

The `Qt5Test.dll` seems to be more problematic. It is generated in the `bin/Release` directory thanks to a routine located at the end of `External_PlusApp.cmake` in PlusBuild.

For now, we use a dirty workaround in [PlusApp CPack config](https://github.com/PlusToolkit/PlusApp/blob/master/CPackConfig.cmake) config file:

`SET(CPACK_INSTALLED_DIRECTORIES "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/Release;/${PLUSAPP_INSTALL_BIN_DIR}")`

**_Note:_** If it is an usage error, I would be thankful if you could redirect me to the correct packaging process

**Comment by Sunderlandkyl** [comment]
Should be fixed in latest version.
