### ISSUE TITLE
Clarius-Plus Server connection error

### ISSUE THREAD

**Issue by javan-del** [PlusToolkit/PlusLib#902]
Hi there,

I am a new user of Plus and need some help to solve the error that I get.  I want to stream data (Image) from Clarius to 3D Slicer by using Plus Server Launcher. I am using Clarius App on a tablet, and I used “PlusApp-2.9.0.20220128-Clarius-Win64.exe”. The error I get is in the attached file. I should mention that when I click on the “Launch server” button it will stay on lunching.. mode.
I really appreciate it if you can help me in this regard.

[PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/8027848/PlusLog.txt)

**Comment by Sunderlandkyl** [comment]
The Clarius device doesn't seem to be able to connect to the device. It's possible that the version of the listener SDK that is currently used by Plus is not compatible with the App. I'll see if it can be easily updated.

What version of the Clarius App are you using?

**Comment by Sunderlandkyl** [comment]
Looks like Plus is using the "listen" api (7.1.0), the latest version has been renamed to "cast" and is on version 9.0.0.

**Comment by javan-del** [comment]
I am using Clarius App version 9.0.0.

**Comment by javan-del** [comment]
> Looks like Plus is using the "listen" api (7.1.0), the latest version has been renamed to "cast" and is on version 9.0.0.

@Sunderlandkyl Thank you so much for your reply
Does that mean the  “PlusApp-2.9.0.20220128-Clarius-Win64.exe” is updated?
Because I just downloaded “PlusApp-2.9.0.20220128-Clarius-Win64.exe” but still get the same error. I am not sure if it has been already updated or it will be updated later.

**Comment by Sunderlandkyl** [comment]
Not updated yet, I'll let you know when it's available.

**Comment by Sunderlandkyl** [comment]
I'll try to have a version ready to test either tomorrow or early next week.

**Comment by javan-del** [comment]
@Sunderlandkyl Thank you so much.

**Comment by Sunderlandkyl** [comment]
The Clarius device in the nightly release has been updated to the latest version, but I haven't tested it.

Let me know if it works.

**Comment by Sunderlandkyl** [comment]
Does the image in the red view continue to update?

Can you provide the full log?

**Comment by Sunderlandkyl** [comment]
Ok, it looks like the image is being sent correctly from Plus. Can you provide the Slicer log as well?

**Comment by javan-del** [comment]
Sorry, I am a new user and I am not sure this is what you want but, in 3D Slicer I moved to View ->Error Log and this is the error:

Failed to determine texture parameters. IF=0 F=6407 T=5121

if  you need more information please let me know how should I get it and send it to you.

**Comment by Sunderlandkyl** [comment]
It looks like this is a known issue with regards to displaying RGBA volumes in the 3D view (see https://github.com/Slicer/Slicer/issues/5753). I'll see if I can modify the Clarius device to send images as grayscale or RGB instead. It may be a couple of days before I can get to it, but I'll let you know when it's ready to test.

**Comment by javan-del** [comment]
I really appreciate it. Thank you so much.

**Comment by Sunderlandkyl** [comment]
No, I haven't had a chance to look at this yet.

**Comment by javan-del** [comment]
Thank you for your reply.

**Comment by javan-del** [comment]
Thank you for your reply.

**Comment by javan-del** [comment]
Hello, 

After the Plus server was updated for Clarius version 9.0.0  I was able to get the image in 3D Slicer. However, by a new update of Clarius (version 9.1.0), I am not able to get the image. Here is the log file and errors.

[log.txt](https://github.com/PlusToolkit/PlusLib/files/8343574/log.txt)

I really appreciate it if you can help to fix this issue.
Thank you in advance.

**Comment by Sunderlandkyl** [comment]
I've updated the Clarius libraries to the latest version. It should be available tomorrow.

**Comment by javan-del** [comment]
Thank you so much.

**Comment by ChristophG123T** [comment]
Hello, I am having these issues:

Operating system: Windows 10 64 bits
Slicer version: 5.1.0 2022-05-04
Expected behavior: Connecting Clarius to 3D Slicer using Cast API and Plus Server
Actual behavior:
Both the computer & tablet are connected on the same network. The computer can ping the Clarius device, however when it tries to connect via Plus server, it gets this error:
|ERROR|018.164000|SERVER> error: connect failure: Exception ocurred (Error connecting to TCP socket: No connection could be made because the target machine actively refused it)| in E:\D\PTNPCb\PlusLib\src\PlusDataCollection\Clarius\vtkPlusClarius.cxx(572)
|ERROR|018.165000|SERVER> … Clarius device connected but could not get valid udp port| in E:\D\PTNPCb\PlusLib\src\PlusDataCollection\Clarius\vtkPlusClarius.cxx(535)

The IP and tcp port in the config file match the IP and casting port in the Clarius tablet application. I’m not sure what the utp port is and how to find/change it; this seems to be causing the error.

**Comment by ChristophG123T** [comment]
Ok, so the error I had before with the udp port seems to resolve when I change the port in the config file to the Casting port shown in the Clarius app. However, I now get this issue:
|ERROR|000.077000| Error destoying the listener| in E:\D\PTNPCb\PlusLib\src\PlusDataCollection\Clarius\vtkPlusClarius.cxx(139)

Furthermore, the version of Clarius Plus on the nightly packages seems to be the same one as May 19, even though it said it was updated May 27, and downloads the same installer as my previous version:
[PlusApp-2.9.0.20220519-Clarius-Win64.exe](http://perk-software.cs.queensu.ca/plus/packages/nightly/PlusApp-2.9.0.20220519-Clarius-Win64.exe)	2022-05-27 05:37	150M

Will all these issues be resolved when you update Plus on Saturday? I remember you mentioned doing that when we spoke during the bootcamp a couple days ago. Thanks.

**Comment by Sunderlandkyl** [comment]
Possibly, I'm working on some updates for the Clarius device now. I don't think the "Error destroying listener" message will cause any issues.

Does the image streaming work for you now?

**Comment by Sunderlandkyl** [comment]
>Furthermore, the version of Clarius Plus on the nightly packages seems to be the same one as May 19, even though it said it was updated May 27, and downloads the same installer as my previous version:
[PlusApp-2.9.0.20220519-Clarius-Win64.exe](http://perk-software.cs.queensu.ca/plus/packages/nightly/PlusApp-2.9.0.20220519-Clarius-Win64.exe) 2022-05-27 05:37 150M

The builds are updated every night, however the version is only changed if there is a new commit.
I've fixed this error: ```|ERROR|000.077000| Error destoying the listener| in E:\D\PTNPCb\PlusLib\src\PlusDataCollection\Clarius\vtkPlusClarius.cxx(139)```

If you're still having trouble, we can talk on Monday.
