### ISSUE TITLE
Aruco Calibration Program Will Not Execute

### ISSUE THREAD

**Issue by helpmepls67** [PlusToolkit/PlusLib#904]
I have tried both the nightly and stable release of Windows Plus Toolkit and I cannot get Aruco_Calibration.exe to run on my windows platform. 

I get the following system error: "The code execution cannot proceed because Qt5Test.dll was not found. Reinstalling the program may fix this problem." 

I have tried reinstalling the program several times and nothing has fixed it. The error persists. I cannot even find the file Qt5Test.dll anywhere. This is when I use the stable release of 32 bit plus.

I then tried the 32 bit Telemed and Qt5Test.dll was present. Now, however, when I try to click on Aruco_Calibration.exe the command prompt opens for a second and then closes very quickly. When I try to manually type the command, I get the error "aruco_calibration.exe is not recognized as an internal or external command, operable program or batch file" in command prompt. 

Please advise if possible. Thank you.

**Comment by helpmepls67** [comment]
Do you keep old versions of the downloads? I know it used to work back in 2018, and I could use the aruco_calibration.exe program.

**Comment by Sunderlandkyl** [comment]
Should be fixed in latest version.
