### ISSUE TITLE
 I have the Siemens ultrasound connected to ClonerBox to record the ultrasound screen. Is there a way to connect this to PLUS so that I can see the realtime video on 3D slicer?

### ISSUE THREAD

**Issue by rachelbonfini** [PlusToolkit/PlusLib#938]
Thank you for the information! Sorry about the late response. I have the Siemens ultrasound connected to ClonerBox to record the ultrasound screen. Is there a way to connect this to PLUS so that I can see the realtime video on 3D slicer?

_Originally posted by @rachelbonfini in https://github.com/PlusToolkit/PlusLib/discussions/922#discussioncomment-2597215_

**Comment by adamrankin** [comment]
Is it this device?

https://www.cloner-alliance.com/cloneralliance-box-pro/

**Comment by rachelbonfini** [comment]
Yes, that is the correct one. I can use it to display the ultrasound screen onto my computer, but do not know how to display it on 3D slicer as if it is connected directly to the ultrasound.

**Comment by adamrankin** [comment]
Is it connected to a Windows computer? If so, can the built-in Camera app show the captured stream?

On Linux, you could try the Cheese app.

**Comment by rachelbonfini** [comment]
Yes, it's connected to a Windows 7 computer and the built-in Camera app can show the captured stream on it.

**Comment by rachelbonfini** [comment]
Hello! I apologize but I believe that I misinterpreted what the built-in Camera App was. I am actually not able to connect Cloner Box to the Camera App but I am currently working on it. Would you recommend another way to connect Cloner Box to Slicer if this way does not work?

**Comment by adamrankin** [comment]
Ok, if it doesn't work with the Camera app then it's not a device that Plus can recognize out of the box. Your two options are two implement a new device class that uses the ClonerBox SDK or to use a different capture device. If you want to use another capture device, we support the Epiphan devices, as well as any capture device that provides a Media Foundation (webcam) interface.
