### ISSUE TITLE
Clarius IMU Streaming

### ISSUE THREAD

**Issue by gibsoncw** [PlusToolkit/PlusLib#954]
### Discussed in https://github.com/PlusToolkit/PlusLib/discussions/952
Hello, I am having issues streaming Clarius IMU data in realtime to slicer. How can I do this using an xml file? My discussion with more information can be found below.
<div type='discussions-op-text'>

<sup>Originally posted by **ChristophG123T** May 30, 2022</sup>
Hello, I was wondering how to configure Clarius so I can stream IMU data (https://github.com/clariusdev/motion) in realtime and use it to track the Clarius' position on 3D Slicer. We have been able to write IMU data onto a file, but not in realtime. We think we need an xml file to do this. We also can successfully stream Clarius images to 3D Slicer using Plus. Thanks.</div>

**Comment by Sunderlandkyl** [comment]
There is code in Plus for live streaming IMU data from Clarius however I don't think it was ever finished.
I'll take a look into it.

**Comment by adamrankin** [comment]
We got it working. Imu has to be enabled in the app and transform is XToVideoDevice
