### ISSUE TITLE
Plus server can not launch

### ISSUE THREAD

**Issue by Cua57** [PlusToolkit/PlusLib#960]
Hello,

I'm trying to launch Plus server to connect with Clarius OEM, but it says 'launching' all the time and can not start the sever.
I also don't see the scanner IP configuration in the config file (PlusDeviceSet_Server_ClariusOEMVideoCapture.xml)
I wonder if you completed the app for Clarius OEM? Or any suggestion to fix it?

Thanks a lot!
![Screenshot 2022-06-17 163059](https://user-images.githubusercontent.com/36097437/174408891-44d079cb-dd21-4245-90a4-a24d2824805f.png)

**Comment by Sunderlandkyl** [comment]
Have you followed all of the setup instructions listed on this page?:
http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceClariusOEM.html

**Comment by Sunderlandkyl** [comment]
Can you change your log level to Trace, run the server again and upload the latest log file here?

**Comment by Cua57** [comment]
They said, SDK version not available. I'm working on Clarius 9.3.
![image](https://user-images.githubusercontent.com/36097437/174851008-975ff467-5d35-4b71-b5a7-ccc9b210cb1a.png)

**Comment by Sunderlandkyl** [comment]
What model of probe are you using?

I've added some additional debugging statements to the device. Could you try again with the latest nightly release and upload the entire log file? Just run the server and click the "Latest log" button and upload that file. You can also send it to me at 1krs1@queensu.ca if you don't want to share it publicly.
