### ISSUE TITLE
Frame grabber for Siemens Acuson P300 Ultrasound?

### ISSUE THREAD

**Issue by HaocongYang1** [PlusToolkit/PlusLib#972]
Hi! I am new to the Plus toolkit and would appreciate any help I can get. I currently have the Siemens Acuson P300, and I would like to find a frame grabber that works with it to get the screen in real time to 3D Slicer. I see in the previous discussion that experts have suggested to use a frame grabber that works with existing configurations (Epiphan and 'any capture device that provides a Media Foundation (webcam) interface'). The problem is that Acuson P300 only have VGA video output available and after asking Epiphan support they said that the only product available that supports VGA is the DVI2PCIe Duo, which is an internal installed device and kind of expensive. So, are there any suggestions for frame grabber that works with VGA signal output/input and is <$1000? Thanks!

**Comment by HaocongYang1** [comment]
Thanks for the answer! Also, I don't really understand what 'any capture device that provides webcam interface/Media Foundation interface ' means. Does that mean it is supported and the captured screen can be viewed on the Windows Camera app? How do I look for capture devices that can do that? Does the Startech capture device that you recommended fall in this category (since there is no specific configuration for it)? Appreciate the time!

**Comment by adamrankin** [comment]
Any device that supports a UVC (https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/uvc-camera-implementation-guide) interface is usable by Plus. Some capture devices provide a UVC interface (and can be seen in the Camera app).

The StarTech device uses DirectShow which is supported by the Plus VFW device type (http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceVideoForWindows.html)

**Comment by HaocongYang1** [comment]
Understood, thanks for the help!
