### ISSUE TITLE
PlusLib build errors while trying to use Telemed + NDI Polaris

### ISSUE THREAD

**Issue by martynakielbasa** [PlusToolkit/PlusLib#978]
Hello, 

I'm trying to build PlusLib in order to use Telemed EchoBlaster 128 with NDI Polaris at the same time. I've managed to build Plus with only PLUS_USE_NDI enabled. However, it failed to build in VS when I enabled both PLUS_USE_NDI and PLUS_USE_TELEMED_VIDEO. I entered Telemed SDK location in Cmake. Here's the list of files I obtained:

- multfreq.h
- usgdata.h
- usgfw.h
- usgfwex.h
- usgscanb.h
- usgscanm.h

Here are the errors I'm getting in VS:

Error	LNK2019	unresolved external symbol _NdrCStdStubBuffer_Release@8 referenced in function _CStdStubBuffer_Release@4 [C:\D\PlusB-bin_al\PlusLib-bin\src\PlusDataCollection\vtkPlusDataCollection.vcxproj]	PlusLib	C:\D\PlusB-bin_al\dlldata.obj	1	
Error	LNK2019	unresolved external symbol _NdrCStdStubBuffer2_Release@8 referenced in function _CStdStubBuffer2_Release@4 [C:\D\PlusB-bin_al\PlusLib-bin\src\PlusDataCollection\vtkPlusDataCollection.vcxproj]	PlusLib	C:\D\PlusB-bin_al\dlldata.obj	1	
Error	LNK2019	unresolved external symbol __imp__NdrDllGetClassObject@24 referenced in function _DllGetClassObject@12 [C:\D\PlusB-bin_al\PlusLib-bin\src\PlusDataCollection\vtkPlusDataCollection.vcxproj]	PlusLib	C:\D\PlusB-bin_al\dlldata.obj	1	
Error	LNK2019	unresolved external symbol __imp__NdrDllCanUnloadNow@4 referenced in function _DllCanUnloadNow@0 [C:\D\PlusB-bin_al\PlusLib-bin\src\PlusDataCollection\vtkPlusDataCollection.vcxproj]	PlusLib	C:\D\PlusB-bin_al\dlldata.obj	1	
Error	LNK2001	unresolved external symbol _NdrStubForwardingFunction@16 [C:\D\PlusB-bin_al\PlusLib-bin\src\PlusDataCollection\vtkPlusDataCollection.vcxproj]	PlusLib	C:\D\PlusB-bin_al\Usgfw2_p.obj	1	
Error	LNK2001	unresolved external symbol _NdrOleAllocate@4 [C:\D\PlusB-bin_al\PlusLib-bin\src\PlusDataCollection\vtkPlusDataCollection.vcxproj]	PlusLib	C:\D\PlusB-bin_al\Usgfw2_p.obj	1	
Error	LNK2001	unresolved external symbol _NdrOleFree@4 [C:\D\PlusB-bin_al\PlusLib-bin\src\PlusDataCollection\vtkPlusDataCollection.vcxproj]	PlusLib	C:\D\PlusB-bin_al\Usgfw2_p.obj	1	
Error	LNK2001	unresolved external symbol _NdrStubCall2@16 [C:\D\PlusB-bin_al\PlusLib-bin\src\PlusDataCollection\vtkPlusDataCollection.vcxproj]	PlusLib	C:\D\PlusB-bin_al\Usgfw2_p.obj	1	
Error	LNK2001	unresolved external symbol _IUnknown_QueryInterface_Proxy@12 [C:\D\PlusB-bin_al\PlusLib-bin\src\PlusDataCollection\vtkPlusDataCollection.vcxproj]	PlusLib	C:\D\PlusB-bin_al\Usgfw2_p.obj	1	
Error	LNK2001	unresolved external symbol _IUnknown_AddRef_Proxy@4 [C:\D\PlusB-bin_al\PlusLib-bin\src\PlusDataCollection\vtkPlusDataCollection.vcxproj]	PlusLib	C:\D\PlusB-bin_al\Usgfw2_p.obj	1	
Error	LNK2001	unresolved external symbol _IUnknown_Release_Proxy@4 [C:\D\PlusB-bin_al\PlusLib-bin\src\PlusDataCollection\vtkPlusDataCollection.vcxproj]	PlusLib	C:\D\PlusB-bin_al\Usgfw2_p.obj	1	
Error	LNK1120	11 unresolved externals [C:\D\PlusB-bin_al\PlusLib-bin\src\PlusDataCollection\vtkPlusDataCollection.vcxproj]	PlusLib	C:\D\PlusB-bin_al\bin\Debug\vtkPlusDataCollection.dll	1	
Error	LNK1104	cannot open file 'C:\D\PlusB-bin_al\lib\Debug\PlusWidgets.lib' [C:\D\PlusB-bin_al\PlusApp-bin\fCal\Testing\SegmentationParameterDialogTest.vcxproj]	PlusApp	C:\D\PlusB-bin_al\LINK	1	
Error	LNK1104	cannot open file 'C:\D\PlusB-bin_al\lib\Debug\vtkPlusServer.lib' [C:\D\PlusB-bin_al\PlusApp-bin\DiagnosticTools\TrackingDataServer.vcxproj]	PlusApp	C:\D\PlusB-bin_al\LINK	1	
Error	C1083	Cannot open include file: 'ui_QPlusDeviceSetSelectorWidget.h': No such file or directory [C:\D\PlusB-bin_al\PlusApp-bin\PlusServerLauncher\PlusServerLauncher.vcxproj]	PlusApp	C:\D\PlusB-bin_al\PlusLib\src\PlusWidgets\QPlusDeviceSetSelectorWidget.h	13	
Error	C1083	Cannot open include file: 'ui_QPlusConfigFileSaverDialog.h': No such file or directory [C:\D\PlusB-bin_al\PlusApp-bin\fCal\fCal.vcxproj]	PlusApp	C:\D\PlusB-bin_al\PlusLib\src\PlusWidgets\QPlusConfigFileSaverDialog.h	13	
Error	C1083	Cannot open include file: 'ui_QPlusConfigFileSaverDialog.h': No such file or directory [C:\D\PlusB-bin_al\PlusApp-bin\fCal\fCal.vcxproj]	PlusApp	C:\D\PlusB-bin_al\PlusLib\src\PlusWidgets\QPlusConfigFileSaverDialog.h	13	
Error	C1083	Cannot open include file: 'ui_QPlusDeviceSetSelectorWidget.h': No such file or directory [C:\D\PlusB-bin_al\PlusApp-bin\fCal\fCal.vcxproj]	PlusApp	C:\D\PlusB-bin_al\PlusLib\src\PlusWidgets\QPlusDeviceSetSelectorWidget.h	13	

My setup is:

- Windows 11 x64
- VS2017 Community Edition
- Cmake 3.24.0 (32-bit build)
- Qt 5.7 x86

**Comment by Sunderlandkyl** [comment]
What version of the Telemed SDK are you using?

**Comment by martynakielbasa** [comment]
Thank you for replying. 

It's version 1.1.3.

**Comment by martynakielbasa** [comment]
Update: used the latest version of the Telemed SDK: 4.1.1. Still getting the same errors.

**Comment by Sunderlandkyl** [comment]
Nightly versions of Plus are built using the Telemed 4.0.0 SDK.

I made this branch that compiles with SDK 4.1.0 but haven't fully tested it yet:
https://github.com/Sunderlandkyl/PlusLib/tree/telemed_64

You could try cherry picking this commit (80f81c8eb1cf5b9f26dbb85d7da6cf0c77201b90) from this branch and see if it compiles.

**Comment by kenavolic** [comment]
Hi,

We nightly build a version of Plus with Telemed under vs2017. Here are our setup and patches if it helps:

* CMake `Telemed_INCLUDE_DIR`="C:\Program Files (x86)\Telemed\SDK\4.1\include\USGFWSDK\include"

The dir contains:

```
22/04/2020  14:35               803 cvieinterface.h
20/01/2005  15:17               616 iusgreg.h
25/01/2005  09:51               882 iusgregd.h
25/01/2005  09:49             1 094 iusgregs.h
26/06/2004  16:57             1 316 multfreq.h
26/10/2015  14:48             2 233 usgbase.h
16/10/2014  15:56             9 325 usgdata.h
23/02/2005  14:50               394 usgdata2.h
21/02/2009  10:05             4 298 usgdata3d.h
07/11/2013  09:45             3 440 usgdatapw.h
27/06/2017  14:40             5 568 usgdatarf.h
10/11/2015  12:35             2 681 usgdatatemp.h
01/03/2021  15:09            79 070 usgfw.h
09/09/2020  10:54             7 402 usgfw2.h
28/04/2021  10:56            91 049 Usgfw2.idl
08/08/2007  10:23             5 190 Usgfw2_01.h
23/11/2005  13:36               762 usgfw3.h
23/11/2006  11:03               686 usgfweeprom.h
23/11/2006  11:03               937 usgfwex.h
02/08/2015  18:24             1 342 usgfwkoelis.h
30/12/2009  13:44             8 494 usgfwplugins.h
07/12/2017  11:34               751 usgfwqinova.h
27/12/2011  12:18               411 usgfwtemp.h
17/01/2008  14:19             6 172 usgscanb.h
20/06/2007  10:04               397 usgscanm.h
19/05/2005  13:08            21 422 usgstr.h
02/03/2005  17:07               522 usgutils.h
```
* C++ patch to _src/PlusDataCollection/Telemed/Usgfw2_h.h_

`#pragma comment(lib, "RpcRT4.lib") /* NOTE: Add this line to compile with vs2017 */`

Not sure it's the best way to overcome our linking issues but at least it works...

**Comment by martynakielbasa** [comment]
Hi guys, 

Thank you so much for your help. 

I built the project using the second solution in VS2017 and I'm going to stick to the setup for now. 

FYI, I also tested both of your solutions in VS2022 and they worked fine.
