### ISSUE TITLE
DeviceSetSelectorWidget doesn't emit DeviceSetSelected signal at launch

### ISSUE THREAD

**Issue by atracsys-sbt** [PlusToolkit/PlusLib#983]
Hi,
I am developping an application that includes a DeviceSetSelectorWidget and I would like to display some kind of preview of the content of the configuration file upon selection. Connecting a slot function to QPlusDeviceSetSelectorWidget::DeviceSetSelected does the trick nicely. However, upon relaunching the application, the last selection is stored and automatically set in the configuration list. In that case, the signal is not emitted.
I think it would be helpful to have the signal emitted at launch or at least to have access in read-only to the currently config file path from outside the class (so far only the description is accessible via QPlusDeviceSetSelectorWidget::GetSelectedDeviceSetDescription).
Thanks

**Comment by adamrankin** [comment]
Interestingly enough, DeviceSetSelected is listed as a signal but is never emitted... exploring further

**Comment by adamrankin** [comment]
According to the code, it should emit the signal on launch. The connection is made before the drop down is populated:

https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusWidgets/QPlusDeviceSetSelectorWidget.cxx#L64

then the directory is parsed and a previously selected item is restored:

https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusWidgets/QPlusDeviceSetSelectorWidget.cxx#L479

which should trigger currentIndexChanged(...) which should trigger DeviceSetSelected which should emit the signal. Can you confirm that this is not the case?

**Comment by atracsys-sbt** [comment]
Thank you for the fix :)
