### ISSUE TITLE
Error connecting to brand new NDI Polaris Vega ST

### ISSUE THREAD

**Issue by dgcare** [PlusToolkit/PlusLib#992]
I just begin to set up a NDI Polaris Vega ST on local network. I can track all 3 tools (8700339), Stylus (8700340), Reference (8700449) in NDI Toolbox and Cygna-6D

When using Plus Server Launcher (PlusApp-2.9.0.20220930-Win64.exe) with NDI Polaris tracker with passive markers Device set, the connection is successful with the following warnings and errors

|WARNING|015.204000|SERVER> Buffer item is not in the buffer (Uid: 0)!| in E:\D\PTNP64b\PlusLib\src\PlusDataCollection\vtkPlusTimestampedCircularBuffer.cxx(176)
|WARNING|015.230000|SERVER> Unable to get timestamp from ReferenceToTracker tool tracker buffer for time: 0| in E:\D\PTNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(1293)
|WARNING|015.230000|SERVER> Buffer item is not in the buffer (Uid: 0)!| in E:\D\PTNP64b\PlusLib\src\PlusDataCollection\vtkPlusTimestampedCircularBuffer.cxx(176)
|WARNING|015.230000|SERVER> Unable to get timestamp from StylusToTracker tool tracker buffer for time: 0| in E:\D\PTNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(1293)
|WARNING|015.231000|SERVER> Buffer item is not in the buffer (Uid: 0)!| in E:\D\PTNP64b\PlusLib\src\PlusDataCollection\vtkPlusTimestampedCircularBuffer.cxx(176)
|WARNING|015.231000|SERVER> Unable to get timestamp from ToolToTracker tool tracker buffer for time: 0| in E:\D\PTNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(1293)
|ERROR|015.232000|SERVER> Failed to get most recent timestamp from all the tracker tools| in E:\D\PTNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(1310)
|ERROR|015.258000|SERVER> vtkPlusChannel::GetTrackedFrameListSampled failed: unable to get most recent timestamp. Probably no frames have been acquired yet.| in E:\D\PTNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(1064)
|ERROR|015.259000|SERVER> Error while getting tracked frame list from data collector during capturing. Last recorded timestamp: 0.283000| in E:\D\PTNP64b\PlusLib\src\PlusDataCollection\VirtualDevices\vtkPlusVirtualCapture.cxx(343)
|WARNING|015.259000|SERVER> vtkPlusChannel::GetTrackedFrameListSampled: Frames in the buffer are not available any more at time: 0.283000. Skipping 0.117000 seconds from the recording to catch up. Increase the buffer size or decrease the acquisition rate to avoid this situation.| in E:\D\PTNP64b\PlusLib\src\PlusDataCollection\vtkPlusChannel.cxx(1089)
|ERROR|015.382000|SERVER> Unable to retrieve number of scalar components.| in E:\D\PTNP64b\IGSIO\SequenceIO\vtkIGSIONrrdSequenceIO.cxx(584)
|ERROR|015.383000|SERVER> Unable to prepare header| in E:\D\PTNP64b\PlusLib\src\PlusDataCollection\VirtualDevices\vtkPlusVirtualCapture.cxx(611)

What do I need to do to correct these problems? Thank you in advance

<Device
      Id="TrackerDevice"
      Type="PolarisTracker"
	  NetworkHostname="P9-12666"
	  NetworkPort="8765"
      ToolReferenceFrame="Tracker" >

I only added  NetworkHostname="P9-12666"
	              NetworkPort="8765"
to the PlusDeviceSet_Server_NDIPolaris.xml, all other line unchanged.

[101122_154657_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/9752805/101122_154657_PlusLog.txt)
[101122_154918_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/9752811/101122_154918_PlusLog.txt)

**Comment by adamrankin** [comment]
Honestly I'm not sure. It should work. Just to cover some basics, is the NDI software running at the same time? Has the camera been enabled in the Configure app?

**Comment by dgcare** [comment]
Thank you for your help,

No, I did not have NDI software running at the same time. It will cause connection failed in Plus Server Launcher

![image](https://user-images.githubusercontent.com/89897468/195230937-70b24a10-3cc7-4477-8644-93d282b17b2d.png)

![image](https://user-images.githubusercontent.com/89897468/195231014-11300372-a5a5-445c-8b47-64c57f999df4.png)

[101222_094829_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/9760826/101222_094829_PlusLog.txt)

The NDI model is VEGA ST, I think it does not has a camera

![image](https://user-images.githubusercontent.com/89897468/195231903-56e20807-6d3e-4b72-a90c-ec2d5394cc1d.png)

[PlusDeviceSet_Server_NDIPolaris.txt](https://github.com/PlusToolkit/PlusLib/files/9760857/PlusDeviceSet_Server_NDIPolaris.txt)

**Comment by adamrankin** [comment]
I haven't had a chance to test with the ST model, but I assumed it would have worked. I will see if I can access an ST model.

**Comment by adamrankin** [comment]
I am able to connect to an ST with the following minimalist config file, could you test with it (changing your hostname)?

```xml
<PlusConfiguration version="2.1">

  <DataCollection StartupDelaySec="1.0" >
    <DeviceSet
      Name="PlusServer: NDI Vega tracker with passive markers - by Bonjour"
      Description="Broadcasting tool tracking data through OpenIGTLink
For NDI Vega: Stylus (8700248)" />
    <Device
      Id="TrackerDevice"
      Type="NDITracker"
      NetworkHostname="P9-14620"
      NetworkPort="8765"
      ToolReferenceFrame="Reference" >
      <DataSources>
        <DataSource Type="Tool" Id="Stylus" RomFile="NdiToolDefinitions/8700248.rom"  />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="TrackerStream" >
          <DataSource Id="Stylus"/>
        </OutputChannel>
      </OutputChannels>
    </Device>
  </DataCollection>

  <CoordinateDefinitions>
  </CoordinateDefinitions>

  <PlusOpenIGTLinkServer
    MaxNumberOfIgtlMessagesToSend="1"
    MaxTimeSpentWithProcessingMs="50"
    ListeningPort="18944"
    SendValidTransformsOnly="true"
    OutputChannelId="TrackerStream" >
    <DefaultClientInfo>
      <MessageTypes>
        <Message Type="TRANSFORM" />
      </MessageTypes>
      <TransformNames>
        <Transform Name="StylusToReference" />
      </TransformNames>
    </DefaultClientInfo>
  </PlusOpenIGTLinkServer>

</PlusConfiguration>
```

**Comment by dgcare** [comment]
Thank you Adamrankin, the minimalist config works.

and I figure out the following code from the original config cause the error, is there way to fix it?

    <Device
      Id="CaptureDevice"
      Type="VirtualCapture"
      BaseFilename="RecordingTest.igs.nrrd"
      EnableFileCompression="TRUE"
      EnableCapturingOnStart="TRUE" >
      <InputChannels>
        <InputChannel Id="TrackerStream" />
      </InputChannels>
    </Device>
