### ISSUE TITLE
Stylus cannot be calculated from given inputs

### ISSUE THREAD

**Issue by martynakielbasa** [PlusToolkit/PlusLib#994]
Hello, 

I'm trying to perform tracked ultrasound probe calibration in fCal.exe. I use NDI Polaris Spectra + Telemed EchoBlaster 128. 

The stylus calibration (below) seems to be correct.
![Zrzut ekranu (1883)](https://user-images.githubusercontent.com/111685804/196152931-2ae71ab3-3718-435a-abcb-0a666f608310.png)

However, when I proceed to phantom registration, I get huge errors (~16 mms) and I get the message 'Stylus cannot be calculated from given inputs'. The green points also seem to be rotated by 90deg related to the phantom model. 

![Zrzut ekranu (1886)](https://user-images.githubusercontent.com/111685804/196153359-7ecefb03-32d4-478a-9a70-6090fc5a70e4.png)

I tried saving the stylus calibration to a new config file, starting the app again with the new file, but it still didn't work. 

I'm also attaching my config file (the one without stylus calibration result): https://we.tl/t-57sJrstUI4

Btw, I'm also curious if it's okay to attach the reference to the phantom like this? Maybe it's also a problem?

![311377891_868357731211158_5973397441498221612_n](https://user-images.githubusercontent.com/111685804/196155222-aef7a1f9-d32b-4e04-ba68-74d11844fc41.jpg)

Do you know any solution to the problem?

Kind regards
Martyna

**Comment by Sunderlandkyl** [comment]
Try using the landmark positions from the config file on this page: http://perk-software.cs.queensu.ca/plus/doc/nightly/user/AlgorithmPhantomRegistration.html

**Comment by martynakielbasa** [comment]
Thank you for your help. It worked!
